### ISSUE TITLE
documentation: add some vision notes to clarify relationships with FluentBit and Prometheus

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-collector#10]
This is vision/documentation issues.

There are other log forwarding and metrics aggregation products on the market and used by some customers as side cars or collectors. Namely [FluentBit](http://fluentbit.org/) and [Prometheus](https://prometheus.io/). OpenTelemetry agent and collector has some unique capabilities comparing to either of those solutions. It will be great to have some document explaining relationships between those products and OpenTelemetry Agent/Service and give end user some recommendations on when to use what.

**Comment by tigrannajaryan** [comment]
PR submitted which clarifies the relationship with FluentBit: https://github.com/open-telemetry/opentelemetry-specification/pull/737
