### ISSUE TITLE
Define minimum supported period for 1.0

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10004]
On the [GA roadmap] we stated as a requirement for 1.0 that

> A minimum support period for 1.0 is documented, similarly to [API and SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#api-support) stability guarantees.

We likely want to differentiate between Go API guarantees vs behavior guarantees and have the guarantees be per component

**Comment by mx-psi** [comment]
Thinking about this, I feel like there are two kinds of APIs here to consider that we may want to have different support periods: those that directly concern component creation (pdata, component, confmap...) and those that are only of concern to distro/distro-like use cases (otelcol, service...).

**Comment by tiffany76** [comment]
During the Comms SIG meeting on August 5, we discussed **where this content should live**: website or repo. The initial preference was for option 1, but we've asked for additional comments. 

Options:
1. Mention the existence of support policies on the website but link to policy details in the repos. This placement serves two purposes: 
  - It grants the Collector SIG easy access to the policy content, especially if it's going to change. 
  - The users most concerned about the API policies are [component developers](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#component-developers) and [library users](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#collector-library-users), not end users (the website's intended audience). 
    - But that leaves the question of what to do with behavior guarantees per component, which are most useful to end users. 
2. Divide the policies so API support periods are housed in the repos and component guarantees are placed on the website.
  - This option aligns the intended audience of the doc with the user most in need of the policy, but it could complicate the maintenance of the policies.
3. Place all policies with their full content on the website.
  - End users are happy, but developers might not be.

Comms SIG would also like to hear what the Collector SIG thinks.
