### ISSUE TITLE
[telemetry] Define lifecycle and stability of telemetry

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10003]
On the [GA Roadmap](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md), we have

> - Metrics, or a subset of them, should be marked as stable in the documentation
> - [...]
> - Stability expectations and lifecycle for telemetry should be documented, so that users can know what they can rely on for their dashboards and alerts

A starting point can be https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metric-lifecycle

**Comment by lavishpal** [comment]
@mx-psi 
Could you assign this issue to me and it will be helpful if you provide guidance on how to get started?

**Comment by mx-psi** [comment]
@lavishpal We can start with a document that lists out what we guarantee from a stable metric (in terms of what can change). We can initially host the document in the `docs/` folder of this repository. Once we have that, we can consider next steps

**Comment by tiffany76** [comment]
During the Comms SIG meeting on August 5, we discussed where this content should live: website or repo. Since the lifecycle of the telemetry affects whether it can be used, the group felt this content belongs on the website where it can benefit end users. We are seeking additional comments as well.
