### ISSUE TITLE
Define support guidelines for major revisions

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#10009]
As we gear towards supporting v1, we will need to define a set of support statements providing answers to the following:
* When we publish a v2, do we still support v1?
* If yes, how long do we plan to support v1 once v2 is published?
* Once we release v1, can we make clear that no further releases of v0.x components will be made?

**Comment by luke6Lh43** [comment]
That is a really good idea! 

I think we should have well defined release cycle and support policy. We could follow the one which is used currently in Kubernetes N-2 (meaning that the 3 most recent minor versions receive security and bug fixes) or something similar. This should be documented and published on opentelemetry.io, so everyone is aware of that.

**Comment by mx-psi** [comment]
@atoulme Do you feel like #11001 covers all the points on this issue?
