### ISSUE TITLE
DNS gRPC OTEL exporter endpoing incorrectly sanitised

### ISSUE THREAD

**Issue by nmiculinic** [open-telemetry/opentelemetry-collector#10017]
**Describe the bug**

https://github.com/open-telemetry/opentelemetry-collector/blob/v0.97.0/exporter/otlpexporter/config.go

Until v0.96.0 this was fine, and I could do 

```
endpoint:  dns:host:port
```

as per spec https://github.com/grpc/grpc/blob/master/doc/naming.md ; however this overly eager sanitisation is killing it. 

This is important for fast network failover within gRPC itself; plain old "endpoint" doesn't work that well, and there's increase in send failures

**Comment by TylerHelmuth** [comment]
I suspect this will be fixed when https://github.com/open-telemetry/opentelemetry-collector/pull/10010 is released
