### ISSUE TITLE
[exporterhelper] batch sender seems to be stuck during shutdown

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector#10061]
**Describe the bug**
If there are data in flight in the pipeline, or if there is a queue size, batch sender seems to be stuck during shutdown

**Steps to reproduce**
1. Send data constantly to the pipeline
2. Update configurations

**What did you expect to see?**
- collector shut down and restart with the new configurations

**What did you see instead?**
- collector seems to be stuck at shutdown. Shutdown never finishes with exporter

**What version did you use?**
v0.99

**What config did you use?**
Custom exporter with exporter batch option enabled

**Environment**
go 1.21

**Additional context**
Attaching an example trace file from profiling
[trace3.log](https://github.com/open-telemetry/opentelemetry-collector/files/15179140/trace3.log)

Setting up debugger, the follow code block in batch_sender loops forever:
```
	for bs.activeRequests.Load() > 0 {
		time.Sleep(10 * time.Millisecond)
	}
```
`activeRequests` is constantly to be 1

**Comment by atoulme** [comment]
Would you have a way to reproduce the issue with a failing test?

The collector shuts down in order, starting with receivers, processors and then exporters. Is your receiver still receiving data even though Shutdown was called on it?

**Comment by atoulme** [comment]
See this behavior here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/graph/graph.go#L418

**Comment by atoulme** [comment]
Understood. Can you send complete logs of the collector in debug mode to see why the exporter is stuck? It seems like the batch_sender is waiting for the export to finish to shut down.

**Comment by dmitryax** [comment]
Also please post the provided configuration for both queue and batching

**Comment by dmitryax** [comment]
...and `timeout` config as well. I can see it happening if timeout is disabled (set to `0`) and the current request is stuck.

**Comment by splunkericl** [comment]
@dmitryax we don't se timeout to be `0` but we do set maxElapsedTime from backoff to be `0`. I am attaching 
[settings.log](https://github.com/open-telemetry/opentelemetry-collector/files/15192948/settings.log) to show all the exporter helper options we set.

Including local_test.log as well. After the last entry, the collector is just [stuck.]([local_test.log](https://github.com/open-telemetry/opentelemetry-collector/files/15193072/local_test.log))

**Comment by splunkericl** [comment]
@dmitryax yeah i set a time out in my test to be 5 minutes

**Comment by splunkericl** [comment]
Had a sync with @dmitryax . The batch configuration we set was incorrect. Setting a `MaxSizeItems` with a small value while having `MinSizeItems` value of 0 causes the exporter to send every request in sequential order when shutting down.

The recommendation was to change to `MinSizeItems` to the value and not setting values for `MaxSizeItems`. This causes exporter helper to do merge only instead of merge split. The issue is gone after setting the configurations this way.

Will close the issue now as user error.
