### ISSUE TITLE
Dead link in the mdatagen README

### ISSUE THREAD

**Issue by woody1872** [open-telemetry/opentelemetry-collector#10071]
**Describe the bug**
There is a dead link in the mdatagen README page, which no longer links to a page that exists

**Steps to reproduce**

1. Visit the [mdatagen README page](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/mdatagen)
2. Click the `documentation.md` link [here](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/mdatagen#:~:text=be%20found%20in-,documentation.md,-.)

**What did you expect to see?**
The sample documentation.md page it references in the README

**What did you see instead?**
A "404 - page not found" error

**Additional context**
I'm guessing the `documentation.md` link in the README is supposed to link to [this page](https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/mdatagen/internal/samplereceiver/documentation.md) now?

**Comment by lavishpal** [comment]
@woody1872     
could you assign this issue to me?

**Comment by woody1872** [comment]
I don't think I have such permissions to be honest - I think it'd have to be a maintainer/codeowner
