### ISSUE TITLE
Explore/Consider Dynamic Configuration re-upload

### ISSUE THREAD

**Issue by PettitWesley** [open-telemetry/opentelemetry-collector#1007]
As mentioned in the Collector SIG today, I think it'd be useful to be able to dynamically re-upload and change configuration with zero downtime. This should be discussed/explored- is stopping and restarting the collector to change the config acceptable? How much data will be lost?

This is a very long term thing; I don't think it is a high priority right now. Opening this issue mostly just so that if we someday start seriously talking about it, I can claim that I first brought up the idea 😁

**Comment by shilicqupt** [comment]
```
type Component interface {
	Start(ctx context.Context, host Host) error

	Shutdown(ctx context.Context) error

       // may be we can add reload func to support
        Reload(ctx context.Context) error
}
```

**Comment by appdashishmehta** [comment]
Definitely a novel idea, I just wonder so far it was not given much thought. We are hitting such requirement as well for our use case of enabling/disabling exporter(s) dynamically without re-building the pipeline or data loss.
