### ISSUE TITLE
Ability to log instrumentation library of the span

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector#1008]
**Is your feature request related to a problem? Please describe.**
When debugging auto-instrumentations it is very helpful to understand which instrumentation has created the specific span.

**Describe the solution you'd like**
All spans already have instrumentation library information. Just logging it alongside other span info would be of much help.

**Comment by tigrannajaryan** [comment]
This does not seem to be a Collector request. Collector does not do instrumentation. You should probably raise this in a corresponding language SDK repo or if unsure ask in gitter https://gitter.im/open-telemetry/opentelemetry-specification

**Comment by iNikem** [comment]
For the sake of whoever stumbles here in the future: collector already logs this info:
```
tracing-server       | 2020-05-22T13:36:06.679Z	DEBUG	loggingexporter/logging_exporter.go:147	ResourceSpans #0
tracing-server       | InstrumentationLibrarySpans #0
tracing-server       | InstrumentationLibrary io.opentelemetry.auto.jdbc 
tracing-server       | Span #0
tracing-server       |     Trace ID       : 39cf493f9541eb06638b5d30e108bff1
tracing-server       |     Parent ID      : 
tracing-server       |     ID             : 01d58450f3089d1b
tracing-server       |     Name           : SELECT NAME, VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME IN (?, ?, ?, ?)
tracing-server       |     Kind           : CLIENT
tracing-server       |     Start time     : 2020-05-22 13:36:01.571002683 +0000 UTC
tracing-server       |     End time       : 2020-05-22 13:36:01.576832899 +0000 UTC
tracing-server       |     Status code    : Ok
tracing-server       |     Status message : 
```

If this info is available in collector. E.g. `otlp` exporter for java does send this information to collector, but `Zipkin` exporter does not.
