### ISSUE TITLE
[exporterhelper] The exporterhelper should force the mutation flag to be true if splitting batches is enabled

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#10140]
**Describe the bug**
Today it is possible to set the mutation flag to false and provide a batcher that splits the payload. I think this should be considered a mutation of the data since it undoes work that could have been done earlier in the pipeline, such as the groupbyattributes processor.

**What did you expect to see?**
If a batcher is configured to split the payload to maximize batch sizes, the mutation flag such be forced to be true.

**Comment by dmitryax** [comment]
Oh, actually enabling batcher sender already sets the mutable flag :)

https://github.com/open-telemetry/opentelemetry-collector/blob/ebf03d53e4209813007504788df00af6ca3b2f5d/exporter/exporterhelper/common.go#L285-L286
