### ISSUE TITLE
[component] Naming of methods of `component.Host`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10180]
Methods in `component.Host` start with `Get`. This is not idiomatic per https://go.dev/doc/effective_go#Getters. We should fix it!

**Comment by rogercoll** [comment]
Current usage within the opentelemetry-collector-contrib:

**component.GetFactory**
```
receiver/receivercreator
exporter/rabbitmqexporter
exporter/fileexporter
exporter/awss3exporter
```

**component.GetExtensions**

```
receiver/purefbreceiver
receiver/receivercreator
receiver/purefareceiver
receiver/splunkenterprisereceiver
receiver/filelogreceiver
receiver/splunkhecreceiver
extension/opampcustommessages
extension/storage
internal/aws
pkg/stanza
exporter/awss3exporter
receiver/otelarrowreceiver
exporter/sumologicexporter
exporter/rabbitmqexporter
exporter/otelarrowexporter
exporter/fileexporter
```

Given that those functions are widely used in multiple components within the contrib collector, should we duplicate interface methods and mark them as duplicated for later replacement in the contrib repository? Note that any other external component might be affected too (component interface). External implementations of the Host interface will be broken with any change.

```go
type Host interface {
	// Deprecated: [v0.x.0] Use Factory.
	GetFactory(kind Kind, componentType Type) Factory

	// Factory of the specified kind. Returns the factory for a component type.
    // ...
	Factory(kind Kind, componentType Type) Factory

	// Deprecated: [v0.x.0] Use Extensions.
	GetExtensions() map[ID]Component

	// Extensions returns the map of extensions. Only enabled and created extensions will be returned.
    // ...
	Extensions() map[ID]Component
}
```

By extending the current interface we avoid breaking components at first deprecation and we would just need to extend the `service/host.go` implementation. If this works for you, I can start drafting the pull request and share it for your feedback.

**Comment by yurishkuro** [comment]
I think this is just a completely unnecessary churn. How many eng cycles will be spent on this and then on fixing all the broken dependencies? Why is it valuable?

So it's not idiomatic. Protobuf generates classes with Get methods all the time.

**Comment by mx-psi** [comment]
> I think this is just a completely unnecessary churn. How many eng cycles will be spent on this and then on fixing all the broken dependencies? 

A couple search and replaces across two repositories doesn't seem like too much work to me :smile: 

> Why is it valuable?

Being consistent with the rest of the Go ecosystem makes our library easier to use, which I think should be one of our goals. This is basically impossible to change after 1.0, not even with deprecation since this is an interface and we can't add new methods without breaking implementers. 

If we get to a point where naming issues are the only thing stopping us from getting to 1.0, then we can consider ignoring this. We are not at that point yet, so if someone wants to pick this up I don't see how this is bad.

> Protobuf generates classes with Get methods all the time.

I don't think "others do it wrong" is a valid argument here. If this was a widespread practice then so be it, but I don't believe it is.

**Comment by mx-psi** [comment]
> If we get to a point where naming issues are the only thing stopping us from getting to 1.0, then we can consider ignoring this. We are not at that point yet, so if someone wants to pick this up I don't see how this is bad.

I think we are sort of at that point now for component, so I am going to close this as wontfix because of it
