### ISSUE TITLE
The ballast-size of collector seems incorrect in the example k8s file

### ISSUE THREAD

**Issue by bohrasd** [open-telemetry/opentelemetry-collector#1019]
**Describe the bug**
According to the memory limiter, the same value configured on the command line option `mem-ballast-size-mib` must also be defined in the `memory_limiter` processor. But they are not the same in the example k8s file.
[L118](https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/k8s.yaml#L118)
[L196](https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/k8s.yaml#L196)

**What did you expect to see?**
The same value configured on the command line option `mem-ballast-size-mib` must also be defined in the `memory_limiter` processor.

**What did you see instead?**
They are not the same.

**What version did you use?**
Version: `daf2fc7`

**Comment by owais** [comment]
> According to the memory limiter, the same value configured on the command line option mem-ballast-size-mib must also be defined in the memory_limiter

This is not true. @bohrasd can you please point us to the docs that say this so we can fix the docs?

**Comment by flands** [comment]
@owais I believe it is -- see the PR

**Comment by owais** [comment]
Yes, I misread it as ballast size and memory limiter size being the same.

**Comment by owais** [comment]
@flands I think we should remove everything related to ballast from the default configuration and mention it in the docs as an "advanced technique" for very high throughput scenarios. Majority of the deployment do not need it IMO and would benefit from a simpler setup.
