### ISSUE TITLE
Use most reasonable default config in E2E tests

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1023]
Identify the default configuration and default recommended processors (memory ballast, memlimiter, batcher, queued_retry, etc) and use them in end-to-end tests.

**Comment by pavolloffay** [comment]
@tigrannajaryan are there any plans to support default configuration  (memory ballast, memlimiter, batcher, queued_retry, healthcheck) in the standard distribution?
