### ISSUE TITLE
Don't spawn Collector process for certain E2E tests

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1024]
E2E tests today spawn a separate Collector process. This is useful for performance tests and certain other classes of tests (e.g. verifying the behavior after restarting from crash).

However many other E2E tests, such as verifying correctness of end-to-end operation of the Collector starting from receiving data, processing it, then exporting it do not necessarily require a separate process and can be run as regular Go tests.

We want ability to run full instance of the Collector `Service`, configurable similar to how testbed does it (with Data Senders and Receivers) but which do not run Collector executable as separate process.

This will speed up the test execution and will allow to have E2E test results in total coverage reports.

**Comment by tigrannajaryan** [comment]
@flands I am removing this from this milestone since we won't have time to do it. Will be done later.

**Comment by kbrockhoff** [comment]
I have this working in my generalize-testbed branch. It just needs some polish. Please assign this ticket to me.

**Comment by kbrockhoff** [comment]
This is fixed by PR #1062
