### ISSUE TITLE
Have separate CircleCI job for long running tests

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1028]
Split very long-running tests (such as [stability tests](https://github.com/open-telemetry/opentelemetry-collector/issues/1022)) into a separate build job that is triggered automatically by master branch commits and when passing tags the tested commit as "auto-full-tested".

If the job fails create a Github issue and link to the failed job.

**Comment by owais** [comment]
Is the idea to make such jobs async so they don't block a PR from being merged but asynchronously "bless" a commit as being good?

**Comment by tigrannajaryan** [comment]
Yes. Some tests potentially may run for hours. We cannot wait for so long for PRs. We should probably just skip those tests in PR builds and only execute the for master branch commits. Technically we could make this all in one job when building the master branch but I think it helps to break it down to 2 jobs, especially if we can configure the second, long-running job to only execute on the latest available successful build of master branch, i.e. avoid concurrent runs, because we may want to run them on dedicated machines to have stable performance. We may have many master branch commits in short succession and if the entire test suite takes hours to run we will be end up with a very long queue of jobs if we decide to fully test all commits.

**Comment by owais** [comment]
We could also schedule a nightly build that runs every 12 or 24 hours and tests the latest commit in master.

**Comment by tigrannajaryan** [comment]
Nightly is possible but I'd prefer to run as soon as a commit is made. This reduces time to discover problems introduces by changes.

**Comment by owais** [comment]
I'm researching CircleCI and figuring out the exact flow we'll have. Will update proposal shortly.

**Comment by tigrannajaryan** [comment]
@owais do you have time to work on this? OK to assign to you?

**Comment by tigrannajaryan** [comment]
Ah, I see you already self assigned, thanks. :-)
