### ISSUE TITLE
Automatically create bug reports for test failures

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1029]
Automatically create bug reports for test failures on master branch and assign them to area or test owners (use CODEOWNERS if possible). Increase priority of the bug report on repeat failures.

**Comment by tigrannajaryan** [comment]
@jrcamp I am currently manually inspecting failed builds and create bugs for failing tests. We need to automate it.
Assigning to you since this falls into developer ergonomics :-)

**Comment by jrcamp** [comment]
> @jrcamp I am currently manually inspecting failed builds and create bugs for failing tests. We need to automate it.
> Assigning to you since this falls into developer ergonomics :-)

Could arguably be more aligned with Quality but I'm fine either way.

**Comment by tigrannajaryan** [comment]
@owais is doing something similar for Stability tests here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/278/files

Once he is done we can adopt that code.
