### ISSUE TITLE
[exporterhelper] Batchsender hangs generated component shutdown test

### ISSUE THREAD

**Issue by carsonip** [open-telemetry/opentelemetry-collector#10306]
**Describe the bug**

Any exporter using exporterhelper batchsender will cause its generated_component_test.go `-shutdown` test to hang as Shutdown will never return if it is not started.

Control will be stuck at https://github.com/open-telemetry/opentelemetry-collector/blob/release/v0.102.x/exporter/exporterhelper/batch_sender.go#L231

@dmitryax I wonder if the generated shutdown test needs to start the exporter, or batchsender needs to handle unstarted batcher.

**Steps to reproduce**

Use batchsender with `WithBatcher`. Run `generated_component_test.go`

**What did you expect to see?**

Test passes

**What did you see instead?**

Test hangs

**What version did you use?**

v0.102.0

**What config did you use?**

**Environment**

**Additional context**

**Comment by atoulme** [comment]
The shutdown test explicitly checks calling shutdown without starting first.

**Comment by carsonip** [comment]
> The shutdown test explicitly checks calling shutdown without starting first.

Thanks, then it is a batchsender problem. I'll put up a patch
