### ISSUE TITLE
github.com/rs/cors v1.11.0 causes issues on tests

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10322]
The error on CI is possibly related to rs/cors/issues/176

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector/issues/10045#issuecomment-2084725756_

**Comment by songy23** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/10045
