### ISSUE TITLE
Track @evan-bradley interest and contributions for approver 

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10371]
Hi @evan-bradley ,

This is a tracking issue to know if you are interested and have time to become an approver for the core collector repository. If yes please confirm here. This issue should track contributions to ensure when requirements are met we add you to the approver list.

For previous work see #9576.

**Comment by evan-bradley** [comment]
I would be interested in becoming an approver for the core Collector repository.

Here's a selection of PRs I've authored:

[confmap] Encode string-like map keys: https://github.com/open-telemetry/opentelemetry-collector/pull/10137
[chore] Allow sometimes skipping deprecation process when adding variadic arguments: https://github.com/open-telemetry/opentelemetry-collector/pull/10041
[chore][cmd/builder] Test for unreleased versions: https://github.com/open-telemetry/opentelemetry-collector/pull/10030
[chore][cmd/builder] Improve missing replace statements test: https://github.com/open-telemetry/opentelemetry-collector/pull/10196
[cmd/builder] Allow configuring confmap providers: https://github.com/open-telemetry/opentelemetry-collector/pull/9513
[otelcol] Allow passing confmap.Providers to otelcol.Collector: https://github.com/open-telemetry/opentelemetry-collector/pull/9228
[confmap] Add converter and provider settings to confmap.ResolverSettings: https://github.com/open-telemetry/opentelemetry-collector/pull/9516
[confmap] Split converters and providers into their own modules: https://github.com/open-telemetry/opentelemetry-collector/pull/9461
[receiver/nopreceiver] Add the nopreceiver: https://github.com/open-telemetry/opentelemetry-collector/pull/9446
[exporter/nopexporter] Add the nopexporter: https://github.com/open-telemetry/opentelemetry-collector/pull/9448
Handle partial success responses in the OTLP HTTP exporter: https://github.com/open-telemetry/opentelemetry-collector/pull/6970
Handle partial success responses in the OTLP exporter: https://github.com/open-telemetry/opentelemetry-collector/pull/6971

Full list here: https://github.com/open-telemetry/opentelemetry-collector/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Aevan-bradley

Here's a selection of PRs I've reviewed:

[confmap] Add ability to set default provider: https://github.com/open-telemetry/opentelemetry-collector/pull/10182
[confmap] Remove top level condition when considering struct as Unmarshalers.: https://github.com/open-telemetry/opentelemetry-collector/pull/9862
[otelcol] rfc for how to log during startup: https://github.com/open-telemetry/opentelemetry-collector/pull/10066
OTLP HTTP Exporter: Propagate HTTP 429s: https://github.com/open-telemetry/opentelemetry-collector/pull/9905
[service/telemetry] Switch to a factory pattern: https://github.com/open-telemetry/opentelemetry-collector/pull/10001
[cmd/builder] Remove undocumented strictness check: https://github.com/open-telemetry/opentelemetry-collector/pull/9999
[component] Add MustNewType constructor for component.Type: https://github.com/open-telemetry/opentelemetry-collector/pull/9414
[confmap] Pass ConverterSettings and ProviderSettings to converters and providers: https://github.com/open-telemetry/opentelemetry-collector/pull/9443
[OTLP/GRPC] Ensure OTLP receiver handles consume errors correctly: https://github.com/open-telemetry/opentelemetry-collector/pull/8080
Add template converter: https://github.com/open-telemetry/opentelemetry-collector/pull/8507
Add template provider: https://github.com/open-telemetry/opentelemetry-collector/pull/8504

GitHub claims there are 65 PRs I've reviewed not counting "reviews" on my own PRs.

**Comment by codeboten** [comment]
Thanks for opening the tracking issue @mx-psi, and thanks @evan-bradley for your continued efforts and contributions. They're very much appreciated
