### ISSUE TITLE
Missing way to create pdata.Metrics from OTLP

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-collector#1039]
The existing functionality to create internal metric data structures from OTLP data does not support creation of `pdata.Metrics`, a struct needed to test the collector gRPC server functionality.

There exists [a translation function for OTLP `ResourceMetrics`](https://github.com/open-telemetry/opentelemetry-collector/blob/master/consumer/pdata/metric.go#L34-L37), however, this is not usable given this needs to be wrapped in the `pdata.Metrics` struct as an unexported type.

This missing functionality will block the ability to provided end-to-end testing for receivers or exporters wanting to implement the new collection methods.

**Comment by MrAlias** [comment]
Blocks https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/229#discussion_r424010548

**Comment by tigrannajaryan** [comment]
@MrAlias `pdata` for Metrics is not yet ready because metrics ProtoBuf definitions are in-flux and are not ready. I believe @bogdandrutu hid `pdata.Metrics` internationally because of this.

I think for now you have to use the old interfaces that use OpenCensus as internal data type.

**Comment by MrAlias** [comment]
> @MrAlias `pdata` for Metrics is not yet ready because metrics ProtoBuf definitions are in-flux and are not ready. I believe @bogdandrutu hid `pdata.Metrics` internationally because of this.
> 
> I think for now you have to use the old interfaces that use OpenCensus as internal data type.

Ah, okay. Thanks for the info @tigrannajaryan.

**Comment by bogdandrutu** [comment]
@MrAlias https://github.com/open-telemetry/opentelemetry-collector/blob/master/consumer/pdatautil/pdatautil.go#L47

**Comment by MrAlias** [comment]
@bogdandrutu you linked to a function that takes `[]consumerdata.MetricsData`, is there one that accepts OTLP `ResourceMetrics` that you can point me at?

**Comment by MrAlias** [comment]
Or, did I miss the meaning of that?
