### ISSUE TITLE
Decide what to do w/ `mapstructure` stuct tag

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#10412]
The question of whether support for `mapstructure` struct tags should stay or be removed prior to releasing v1.0 of the Collector. Deciding on this is important to unblock marking various config packages as stable.

**Comment by codeboten** [comment]
At this point, I would suggest we should keep the tag and if there's a need to remove it in the future, we should do so in a post v1 effort

**Comment by codeboten** [comment]
After further discussion, there's no short term plan to move away from mapstructure. Marking this as closed

**Comment by yurishkuro** [comment]
Just for my understanding - what would be the alternative to `mapstructure`?

**Comment by codeboten** [comment]
@yurishkuro a proposed alternative was to use `yaml` instead

**Comment by yurishkuro** [comment]
yaml would be more readable, but would that require changing of the underlying library?

**Comment by atoulme** [comment]
It would not. The `mapstructure` tag itself can be changed: https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/confmap.go#L159
