### ISSUE TITLE
Removing deprecated methods cause issues in dependencies

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#10447]
The following PR https://github.com/open-telemetry/opentelemetry-collector/pull/10423 causes issues w/ dependencies that rely on the funcs/structs removed:

```
# github.com/DataDog/datadog-agent/comp/otelcol/otlp/components/exporter/logsagentexporter
Error: /home/runner/go/pkg/mod/github.com/!data!dog/datadog-agent/comp/otelcol/otlp/components/exporter/logsagentexporter@v0.54.0/factory.go:61:10: undefined: exp.CreateSettings
WARN invalid TestEvent: FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector [build failed]
bad output from test2json: FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector [build failed]
✓  internal/metadata (1.012s)

=== Errors
ERROR rerun aborted because previous run had errors
Error: /home/runner/go/pkg/mod/github.com/!data!dog/datadog-agent/comp/otelcol/otlp/components/exporter/logsagentexporter@v0.54.0/factory.go:61:10: undefined: exp.CreateSettings
make[3]: *** [../../Makefile.Common:126: test] Error 3
```

**Comment by codeboten** [comment]
@songy23 @mx-psi can you take a look at this dependency?

**Comment by yurishkuro** [comment]
@mx-psi how can we ensure that the deprecation practices are followed more strictly? I think in the last release cycle some structs were first deprecated but then removed in the same cycle, so the impact on the users was that the structs just disappeared, and required investigation into what replaced them, which wouldn't be necessary if the removal happened in the following release (deprecation messages would've pointed to the replacement).

**Comment by mx-psi** [comment]
@yurishkuro I think it would really help to address #7443, but nobody is working on it. There are also some instances in which it's kind of hard for us to do things in two steps (e.g. when changing a method's type on an interface). Do you have thoughts on how we should handle those?

Also, if you have details about the concrete breaking change we can see if we can learn something specific about that case.
