### ISSUE TITLE
[configgrpc] endpoint validation causes failures in dns resolution

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#10449]
The validation that was added for `dns:///` makes it impossible for end users to use dns resolution as documented here: https://github.com/grpc/grpc/blob/master/doc/naming.md#detailed-design

The documentation for NewClient suggests that `dns:///` is correct, but that causes the `authority` to be empty, making it impossible for anyone using a custom authority to configure a custom authority

**Comment by oosariemen** [comment]
Thanks for addressing this issue. It would be preferrable to be able to use a custom authority.
