### ISSUE TITLE
Binary asset missing for ocb - cmd/builder for v0.103.0 

### ISSUE THREAD

**Issue by sehej2110** [open-telemetry/opentelemetry-collector#10465]
With the release of opentelemetry collector - v1.10.0/v0.103.0,
the binary assets for cmd/builder are missing:
https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.103.0

and instead tagged as part of v0.103.1 here:
https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.103.1

**Steps to reproduce**
We update our custom collector which is built using the upstream collector builder to get the latest changes on receivers, processors and exporter modules from collector and the collector-contrib.

When we tried to update our custome otel collector builder, we first get the latest release of the opentelemetry-collector
via https://api.github.com/repos/open-telemetry/opentelemetry-collector/releases?per_page=10

We get the latest version from this list via the "tag_name", ie. v0.103.0
and then we try to get opentelemetry collector builder (ocb) binary from https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.103.0/ocb_0.103.0_linux_amd64
which is missing with the latest release.

**What did you expect to see?**
A linux_amd64 collector builder binary for the latest v0.103.0 collector version.
https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.103.0 

**What did you see instead?**
Missing binary - ocb_0.103.0_linux_amd64

**What version did you use?**
https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.103.0
and https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.103.0

**Comment by mx-psi** [comment]
We had a bug on the `v0.103.0` release of the builder which caused the artifacts to not be available. Please use builder's `v0.103.1` binaries instead

cc @djaglowski
