### ISSUE TITLE
Remove extra closing parenthesis in sub-config error

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector#10480]
**Is your feature request related to a problem? Please describe.**

Formatting issue in confmap error: https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/confmap.go#L140

The error contains an extra closing parenthesis: `unexpected sub-config value kind for key:%s value:%v kind:%v)`

**Describe the solution you'd like**

Remove the closing parenthesis: `unexpected sub-config value kind for key:%s value:%v kind:%v`

**Additional context**

Found while adding unmarshall tests in the geoip contrib processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33268/files#diff-9137db5fde5eb0d6870425c0023cec1a5bdfe92f58f8a72e278b55635afc6e95R48

**Comment by mx-psi** [comment]
Fixed by #10479
