### ISSUE TITLE
Expose public API to create trace data

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1051]
https://github.com/open-telemetry/opentelemetry-collector/pull/1037 changed the way how the proto files are generated. The generated files are now under `"go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/trace/v1"` which cannot be imported due to `internal` scope. 

Exporter/consumer has this API
```
ConsumeTraces(ctx context.Context, td pdata.Traces) error
```

And `pdata` interface looks like this:
```
// TracesFromOtlp creates the internal Traces representation from the OTLP.
func TracesFromOtlp(orig []*otlptrace.ResourceSpans) Traces {
	return Traces{&orig}
}
```

Hence I was not able to create test data to test out expoter.

cc) @tigrannajaryan

**Comment by tigrannajaryan** [comment]
@pavolloffay why you need to call `TracesFromOtlp`? This function is intended to be called by OTLP receiver.

To create test data you can start with `pdata.NewTraces()`. See for example https://github.com/open-telemetry/opentelemetry-collector/blob/034d92d6475f6ae8d97f9dd8a656893c1ca2c2f7/translator/trace/jaeger/jaegerproto_to_traces.go#L37

**Comment by pavolloffay** [comment]
Initially, I didn't get how the API should be used. I am closing this.
