### ISSUE TITLE
[exporterhelper] Reconsider the need of Go API related to `ObsReport`

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#10592]
`receiverhelper.ObsReport` is extensively used by many receivers in the contrib. However, exported API related to `exporterhelper.ObsReport` is not being used because that functionality is already incapsulated into top-level helpers  `exporterhelper.New[Metrics|Traces|Logs]Exporter` and there is no reason to interact with `exporterhelper.ObsReport` directly.

Given that we want to limit exposed API before 1.0, I suggest we deprecate and remove public API in https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/obsexporter.go

**Comment by dmitryax** [comment]
@codeboten please let me know if it makes sense to you

**Comment by codeboten** [comment]
Yup, makes sense
