### ISSUE TITLE
pcommon.Map's Range function expects an internal type argument

### ISSUE THREAD

**Issue by himamulch** [open-telemetry/opentelemetry-collector#10597]
The Range function of pdata.pcommon.Map expects an argument of Value type which is defined under _internal_ package. Is this expected?

https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pcommon/map.go#L219

**Comment by mx-psi** [comment]
@himamulch `Value` is not defined in the `internal` package, it's a public symbol just like `Map`: https://github.com/open-telemetry/opentelemetry-collector/blob/2d7dea6a5a2e7d755a710fe2cc4554650786c6c6/pdata/pcommon/value.go#L70. You can find its public documentation here: https://pkg.go.dev/go.opentelemetry.io/collector/pdata/pcommon#Value
