### ISSUE TITLE
Implement Fluentd Forward Protocol DataReceiver for performance testbed.

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1064]
We need to implement `ForwardProtocolDataReceiver` that implements `DataReceiver` interface for logs.

Depends on part 1 of https://github.com/open-telemetry/opentelemetry-collector/issues/1063

**Comment by keitwb** [comment]
This is implemented in #1407.

**Comment by andrewhsu** [comment]
i'm taking the initiative to close this issue because PR #1407 was merged. feel free to re-open if there is something else missing to resolve this issue's initial intent.
