### ISSUE TITLE
Bogus service.name used for internal telemetry

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector#10644]
**Describe the bug**

When initializing TracerProvider the `BuildInfo.Version` is used as a service name.

https://github.com/open-telemetry/opentelemetry-collector/blob/43ed6184f9fedb403ce6eeda02d6eb4d3da94422/service/telemetry/tracer.go#L31

**What did you expect to see?**
Assuming that `BuildInfo` is the right thing to use in the first place, the reasonable mapping would be
  * `Command` -> `service.name`
  * `Version` -> `service.version`

https://github.com/open-telemetry/opentelemetry-collector/blob/43ed6184f9fedb403ce6eeda02d6eb4d3da94422/component/build_info.go#L22-L24

**What version did you use?**
Version: `v0.105.0`

**Comment by mx-psi** [comment]
The proposed change makes sense to me
