### ISSUE TITLE
Migrate release of OpenTelemetry Collector Builder (ocb) to the opentelemetry-collector-releases repository

### ISSUE THREAD

**Issue by jackgopack4** [open-telemetry/opentelemetry-collector#10662]
Currently, the ocb binary is released in the opentelemetry-collector repository, as opposed to the rest of the binaries related to the collector, including core, contrib, and k8s distributions in the opentelemetry-collector-releases repository. Since many OpenTelemetry Collector users actually build their own custom opentelemetry collector using ocb, it may be confusing to find the binary in a different repository 

I would like to migrate the release workflows from the opentelemetry-collector repository to the opentelemetry-collector-releases repository. 

Alternatively, the workflows could remain inside the opentelemetry-collector repo but be modified to publish the binaries to the opentelemetry-collector-releases repository instead of the collector repository when the release train is run. I am not opposed to either solution, but will have to get more familiar with the actions and scripts involved with the build and release process (would love to dive into any documentation we have about this process)!

I intend to add a standard dockerfile for the ocb binary, in reference to [Issue 5712](https://github.com/open-telemetry/opentelemetry-collector/issues/5712), but in that ticket and the [subsequent PR](https://github.com/open-telemetry/opentelemetry-collector/pull/6451), it was generally agreed that the ocb binary should be released to the opentelemetry-collector-releases repository prior to adding dockerfile support.

Anyone available to point me in the right direction for the build/release process for the collector? Thanks!

**Comment by himamulch** [comment]
Hi @jackgopack4 
We at still using an older version (0.89.0) and we used to be able to download the ocb from https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd/builder/v0.89.0/ to build our custom collector.  
While we are planning to upgrade to a recent version soon, could you please let me know where I can find the older version builders?

Thanks

**Comment by jackgopack4** [comment]
Previous releases (v0.106.1 and older) are still in their original location.

**Comment by himamulch** [comment]
@jackgopack4 Could you please check as https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd/builder/v0.89.0/ returns a 404

**Comment by himamulch** [comment]
Actually, found them under a slightly different path: https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.89.0

Thanks for responding
