### ISSUE TITLE
TestBatchProcessorTraceSendWhenClosing fails

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1069]
See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1039/workflows/eed1abcb-c5e7-4fce-aa1d-fe69e8d64129/jobs/6532/steps

```
--- FAIL: TestBatchProcessorTraceSendWhenClosing (5.00s)
    batch_processor_test.go:189: failed to wait for sender timed out waiting for spans
    batch_processor_test.go:193: 
        	Error Trace:	batch_processor_test.go:193
        	Error:      	Not equal: 
        	            	expected: 100
        	            	actual  : 90
        	Test:       	TestBatchProcessorTraceSendWhenClosing
FAIL
```

**Comment by tigrannajaryan** [comment]
Also https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1036/workflows/3dae5981-94d6-432d-89b3-eeb6dc8b409e/jobs/6514

**Comment by tigrannajaryan** [comment]
Also https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1035/workflows/320caee1-d6ec-4e6b-bb27-f7374d0cb688/jobs/6506

**Comment by tigrannajaryan** [comment]
@ccaraman assigning this to you too, I think you are the author. Please have a look as high priority since it fails the builds sporadically. If there is no quick fix please disable it, since it prevents PRs from building and fails master build too.

**Comment by tigrannajaryan** [comment]
Looks like the tests is still unstable: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1044/workflows/fe4e2fb7-cf38-419a-8657-21a1cb2ea4da/jobs/6560

@ccaraman Can you please have a look?

**Comment by ccaraman** [comment]
@tigrannajaryan looking at https://github.com/open-telemetry/opentelemetry-collector/pull/1072 it doesn't have my test change in it.

**Comment by bogdandrutu** [comment]
This seems to be fixed, was my PR which did not include the temporary fix

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan looking at #1072 it doesn't have my test change in it.

@ccaraman By bad, thanks for checking.
