### ISSUE TITLE
[mdatagen] Documentation is not generated for resource attributes without metrics

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector#10705]
**Describe the bug**

When looking into https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34210, I was confused as to why no `documentation.md` file was generated for the EKS detector of the resource detection processor, as it has a [metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/aws/eks/metadata.yaml) file. However, I found that the `documentation.md` file is [only generated if there are metrics or internal metrics defined](https://github.com/open-telemetry/opentelemetry-collector/blob/33168130eae774331f8f771a0022e0a58cf6c28c/cmd/mdatagen/main.go#L99-L101).

**Steps to reproduce**

Run mdatagen against a `metadata.yaml` file that does not include metrics or internal metrics, but includes resource attributes

**What did you expect to see?**

A `documentation.md` file that includes information about valid resource attributes and how to enable and disable them.

**What did you see instead?**

No file is generated.

**What version did you use?**

`v0.104.0`

**Comment by ChrsMark** [comment]
@crobert-1 I tried my hand at it and filed https://github.com/open-telemetry/opentelemetry-collector/issues/10705. I'm not quite familiar with mdatagen concept so I'm not sure if I have missed/break anything in my attempt :).

**Comment by crobert-1** [comment]
> I tried my hand at it and filed https://github.com/open-telemetry/opentelemetry-collector/issues/10705

_It looks like you opened #11242, just clarifying for future reference_ 🙂
