### ISSUE TITLE
[CI] validate-versions workflow should validate versions only when a release is needed

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#10735]
See https://github.com/open-telemetry/opentelemetry-collector/pull/10734
- If we only release beta modules, validate beta candidate versions 
- If we only release stable modules, validate stable candidate versions 
- If we release both, validate both
- If neither candidate is set, fail the workflow

**Comment by mowies** [comment]
@songy23 I fixed this in my PR #10826 :)
