### ISSUE TITLE
TemporalityPreference / DefaultHistogramAggregation are ignored

### ISSUE THREAD

**Issue by pirgeo** [open-telemetry/opentelemetry-collector#10745]
I recently tried [configuring the OTLP exporter for internal telemetry](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/telemetry/config.go#L114-L128) in the OpenTelemetry collector. While doing that, I tried to set the TemporalityPreference for the exported telemetry, which [is passed through](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/proctelemetry/config.go#L212-L215) to the [`initOTLPHTTPExporter` and `initOTLPgRPCExporter` methods](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/proctelemetry/config.go#L234-L303). However, when looking through the code, it seems like TemporalityPreference and DefaultHistogramAggregation are not converted to options to be passed on to the creation of the metrics exporter (https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/proctelemetry/config.go#L264, I assume this is where it would go). Also, setting these options does not affect the telemetry that the collector emits at all.

**Is your feature request related to a problem? Please describe.**
TemporalityPreference and DefaultHistogramAggregation can't be set on the internal telemetry exporters.

**Describe the solution you'd like**
`temporality_preference` and `default_histogram_aggregation` are passed to the exporter. I have [created a branch](https://github.com/open-telemetry/opentelemetry-collector/compare/main...dynatrace-oss-contrib:opentelemetry-collector:int-telemetry-otlp-options?expand=1) but am unsure if this is how it's supposed to be done (using the `metricdata` package directly). I am happy to open a PR or hand off the code if you think this is the right approach.

**Comment by codeboten** [comment]
Thanks @pirgeo, feel free to open a PR to add the feature. I've opened a similar PR in the go contrib repo to add it to the config package as well https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5860

**Comment by pirgeo** [comment]
Thanks, I might ~~steal~~ copy your tests :)
