### ISSUE TITLE
Complete switch to new Collector metrics and avoid inadvertent changes

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#1082]
We should complete the switch from the Collector legacy metrics to the new Collector metrics and make harder for inadvertent changes affecting Collector metric names or labels.

- [X] Ensure `obsreport` test breaks on metric name or label changes. #1083
- [ ] Add tests to ensure no Collector metrics not generated via obsreport also have tests that break on rename (eg.: process related metrics)
- [x] Switch new-metrics on by default, legacy-metrics off by default. #1148 
- [ ] Remove legacy metrics.

**Comment by nilebox** [comment]
> Remove legacy metrics.

As described in https://github.com/open-telemetry/opentelemetry-collector/pull/1148#pullrequestreview-433774846, we need access to new metrics before deleting legacy metrics, to be able to reference them in our custom extensions.

**Comment by nilebox** [comment]
Alternatively, we may make the telemetry more customizable instead of just exposing its internal parts, e.g. add support for passing custom exporters and more granular configuration for a set of metrics that need to be set up.
