### ISSUE TITLE
[exporterhelper] Run performance tests to compare exporter batching with the batcher processor

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#10836]
We can use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/oteltestbedcol to compare the performance of an OTLP pipeline with a batch processor versus an OTLP pipeline with an enabled batcher in the OTLP exporter.

**Comment by swiatekm** [comment]
@dmitryax I can take this on, can you assign it to me?

**Comment by dmitryax** [comment]
@swiatekm, done. Thank you!

**Comment by swiatekm** [comment]
Can we reopen? I'd like add benchmarks for more processing-heavy scenarios, as suggested by @sfc-gh-sili and @jmacd in the PR.
