### ISSUE TITLE
Consider removing `Validate` from confignet.AddrConfig

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#10833]
See https://github.com/open-telemetry/opentelemetry-collector/pull/9801#pullrequestreview-1958102837

> For the implicit dependency on component, I don't really get why we are adding Validate(): the UnmarshalText method from the transport should already do validation at unmarshaling time. Shouldn't that be enough? If we can remove that method, we eliminate one implicit dependency.

This may unblock stabilizing confignet. Alternatively, we can wait for component to be declared stable.

**Comment by TylerHelmuth** [comment]
I believe https://github.com/open-telemetry/opentelemetry-collector/pull/9801#issuecomment-2018474103 still applies. A user could construct this struct without Unmarshal and should be able to validate if it is valid.

**Comment by atoulme** [comment]
OK I think we can close this issue as addressed.
