### ISSUE TITLE
Clarify memory limiter operation

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1084]
It is not entirely clear what currently happens when memory limiter hits the limit. Do we continue receiving data and we drop it? Or we stop receiving data? Do receivers indicate to their senders to stop sending, i.e. backpressure/throttle them?

TODO:
1. We need to document the behavior clearly and make any corresponding changes needed in the memory limiter code.
2. We need to make sure all receivers consistently follow the documented behavior.
3. We ~may~ likely want to make the behavior configurable, i.e. drop vs backpressure. Depending on the use-case the desired behavior may be different.

**Comment by nilebox** [comment]
Currently Memory Limiter drops the data and returns an error back to receiver: https://github.com/open-telemetry/opentelemetry-collector/blob/f134f50df819ea09b0274e5242352d46ccba8afa/processor/memorylimiter/memorylimiter.go#L166, so the action is actually specific to the receiver implementation - it may ignore the error, log it, retry etc.

We should probably at least define a public type / const for this error to be able to consistently process it everywhere.

Additionally, it may be useful to implement some callback interface to be called by MemoryLimiter or any other component to backpressure or stop the pipeline from receiving data, or perform some other action. It may even be useful for exporter receiving API throttling errors like in #1121 to stop the pipeline.

Definining such interface will allows to directly control the pipeline.

**Comment by tigrannajaryan** [comment]
>     3. We may want to make the behavior configurable, i.e. drop vs backpressure. Depending on the use-case the desired behavior may be different.

@flands here is the issue I mentioned.

**Comment by flands** [comment]
Definitely need 3. I also still confused why it is a processor :) you can only define once per instance right? it applies to all pipelines (or the least defined one wins for all pipelines. Then we also have: https://github.com/open-telemetry/opentelemetry-collector/issues/1078

**Comment by tigrannajaryan** [comment]
It has to be a processor. Today it is the only way you can affect the pipeline (drop the data or return errors to receivers).
We can turn into a special concept that does not fit our receiver/exporter/processor/extension component model but I am not sure it is necessary.

**Comment by owais** [comment]
@flands  It might not conceptually be a "processor" as it does not process data but it is part of the data pipeline. Data has to flow through it in order for it to be able to drop it. This is a very simple design that fits quite well with the rest of the system. Data goes into the memory limiter "processor" and depending on memory pressure, it'll either come out on the other side or never be seen again.

**Comment by tigrannajaryan** [comment]
This should not be closed. It is important to clarify how the Collector works in memory limited mode and what we expect the receiver implementations to do.

**Comment by tigrannajaryan** [comment]
cc @open-telemetry/collector-approvers

**Comment by tigrannajaryan** [comment]
I am going to close this since I think the current documentation is now clear about how memory limiter works.

Any additional changes (e.g. adding an option to choose between refusing and droping) can be filed as a new issue.
