### ISSUE TITLE
Migrate to math/rand/v2

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#10885]
Go 1.22 introduced [math/rand/v2](https://pkg.go.dev/math/rand/v2) which replaces the `math/rand` stdlib package. We should migrate to it!

Once we have migrated, we can forbid its usage via [depguard](https://github.com/open-telemetry/opentelemetry-collector/blob/d5d1f82bc728d31d4e757f1c1573e754c335ebd1/.golangci.yml#L103).

Components using `math/rand` v1:

- [x] exporter/exportertest
- [x] receiver/receivertest

(generated using `rg math/rand -l -tgo | cut -d'/' -f1-2 | sort | uniq | sed 's/^/- [ ] /'`)

Counterpart to open-telemetry/opentelemetry-collector-contrib/issues/34676.

**Comment by webstradev** [comment]
I can pick this up
