### ISSUE TITLE
pdata.TracesFromOtlp  can't be used externally

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-collector#1101]
```go
package pdata

import (
	otlptrace "go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/trace/v1"
)

func TracesFromOtlp(orig []*otlptrace.ResourceSpans) Traces {
	return Traces{&orig}
}
```

I want to use `TracesFromOtlp` to build `pdata.Traces`, buf found that `otlptrace.ResourceSpans` cannot be used externally

**Comment by bogdandrutu** [comment]
How do you receive otlp data? Why don't you just use otlp exporter?

Not saying that your bug report is not valid but trying to understand the use-case

**Comment by ibawt** [comment]
fwiw you can import the proto directly instead of using the internal embedded package.

**Comment by tensorchen** [comment]
@bogdandrutu I am implementing kafka collector exporter.

```go
func (k *kafkaExporter) ConsumeTraces(ctx context.Context, td pdata.Traces) error 
```

I will write unit tests for this function, therefore I want to use `TracesFromOtlp` to build `pdata.Traces`

**Comment by bogdandrutu** [comment]
@tensorchen we have exporter for Kafka here, soon will have a Receiver as well :)

**Comment by pavolloffay** [comment]
FYI kafka receiver and exporter landed in master. 

@tensorchen is this issue still relevant?
