### ISSUE TITLE
Links for images and binaries and for release v0.108.1 is broken

### ISSUE THREAD

**Issue by ericwenn** [open-telemetry/opentelemetry-collector#11036]
**Describe the bug**

The [release for v0.108.1](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.108.1) contains a link for images and binaries that results in a 404.

**What did you expect to see?**
When there is a version, it should be possible to download binaries.

**Comment by mx-psi** [comment]
Thanks! I fixed the link. The link is generated automatically but it should have pointed to v0.108.0. We did not do a v0.108.1 binary release for any distribution; we only released the source code under v0.108.1

**Comment by ericwenn** [comment]
I understand. With risk of bike-shedding a bit, why isn't there a binary release for v0.108.1?

In order to get dependabot updates for opentelemetry tooling we use the version from the go module to fetch the precompiled binary. This process has worked so far (even after binary releases was moved to other repository), but if go module releases doesnt imply there will be a binary releases any more it wont.

Are we abusing the releases in opentelemetry project, or is the existing release process w.r.t. binaries too complicated?

**Comment by ericwenn** [comment]
@mx-psi thanks!

It seems we will have to update tooling on our side then to have it work :)
