### ISSUE TITLE
Expose API to retrieve otelcol.Config from confmap.Conf

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector#11133]
**Is your feature request related to a problem? Please describe.**
We have an extension which sends the collectors effective and redacted config to our backend. 

Our current approach entails using the ConfigProvider [Get](https://github.com/open-telemetry/opentelemetry-collector/blob/main/otelcol/configprovider.go#L27) at collector start up, and we then store the config into a third custom component. Our extension then fetches the config from this custom component.

We would like to switch from this approach to using [NotifyConfig](https://github.com/open-telemetry/opentelemetry-collector/blob/3ed205e03a471e4928aaeb1107d831cab60d62c1/extension/extensioncapabilities/interfaces.go#L48) from within our extension in order to retrieve the effective and redacted config. The issue with this approach is that to take advantage of the marshalling of fields such as `configopaque.String`, this requires the `otelcol.Config`, whereas `NotifyConfig` provides the `confmap.Conf`.

**Describe the solution you'd like**
An API that allows retrieving `otelcol.Config` from the `confmap.Conf`. Currently, the logic that does this is unexposed/ uses internal packages (https://github.com/open-telemetry/opentelemetry-collector/blob/main/otelcol/unmarshaler.go).

Example API to be added:
```
func ConfmapToConfig(conf *confmap.Conf, factories Factories) (*Config, error) {
	var cfg *configSettings
	if cfg, err = unmarshal(conf, factories); err != nil {
		return nil, fmt.Errorf("cannot unmarshal the configuration: %w", err)
	}

	return &Config{
		Receivers:  cfg.Receivers.Configs(),
		Processors: cfg.Processors.Configs(),
		Exporters:  cfg.Exporters.Configs(),
		Connectors: cfg.Connectors.Configs(),
		Extensions: cfg.Extensions.Configs(),
		Service:    cfg.Service,
	}, nil
}

```
**Describe alternatives you've considered**
The alternative that we will likely be using in the short/medium term is to replicate the [logic](https://github.com/open-telemetry/opentelemetry-collector/blob/main/otelcol/unmarshaler.go) manually. 

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by bogdandrutu** [comment]
@evan-bradley said that we need confmap not the final config.

**Comment by evan-bradley** [comment]
I'm sorry, I missed the notification for this.

Currently extensions only have a need for a map object that can be serialized to a text format (e.g. YAML) and reported to a server. We could probably give extensions the whole config if we moved `otelcol.Config` out of the otelcol package to avoid circular dependencies, but there hasn't been a need for this yet.

@mackjmr Could you detail more about your use case? The effective config reported to extensions has fields with `configopaque.String` redacted since v0.105.0. Are you seeing otherwise, or do you need to do something with the `otelcol.Config` struct itself?

**Comment by mackjmr** [comment]
> The effective config reported to extensions has fields with configopaque.String redacted since v0.105.0

This is what I needed, we are good to close this issue.
