### ISSUE TITLE
Fuzzing tests failures

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#11162]
Looking at the fuzzing badge on the landing page, it looks like things are failing:

![Screenshot 2024-09-12 at 1 53 08 PM](https://github.com/user-attachments/assets/3d942d01-c492-41af-a1bb-00799b70bc5b)

The badge is linked to https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:opentelemetry which shows some failures from August, are they still current? Pinging @AdamKorcz as you may know more about this

**Comment by AdamKorcz** [comment]
Looking into this.

**Comment by codeboten** [comment]
Thanks @AdamKorcz, assigned to you.

**Comment by AdamKorcz** [comment]
This should be fixed.

**Comment by AdamKorcz** [comment]
> Yup! Looks good:
> 
> ![Screenshot 2024-09-17 at 11 41 53 AM](https://private-user-images.githubusercontent.com/223565/368296575-a4b7a38d-0ee0-4a58-9c92-ea93e9446ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTk2NTAsIm5iZiI6MTcyNjU5OTM1MCwicGF0aCI6Ii8yMjM1NjUvMzY4Mjk2NTc1LWE0YjdhMzhkLTBlZTAtNGE1OC05YzkyLWVhOTNlOTQ0NmFkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxODU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTkxMDk0MGNjNWMzNmU5OGU3MWJiZjI1NjNjMDVjMjlhZTdhYTAzYzY4ZDA5OTNmOTJjNzM1MTcxZmUyNjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1ZsJskMTNzUpNhBck4qegkWm_E3dvJmNIxiTG_TX0yg)
> 
> Thanks @AdamKorcz, what was the fix in case this happens again in the future?

in this case it shouldn't have happened, so the best thing is to ping me.
