### ISSUE TITLE
Make `processortest` into its own module

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#11218]

**Comment by mx-psi** [comment]
@wildum will work on this one :)

**Comment by wildum** [comment]
The trick is that processorhelper is part of the processor module and it uses processortest. I believe that in order to have processortest in its own module, we would need to also have processorhelper in its own module.
Or am I missing something? @mx-psi

**Comment by mx-psi** [comment]
Hm, cyclic dependencies between modules should not be a problem for Go as far as I am aware; they are not great, but since this is only meant to be used in tests and we can move those around easily I am not worried about creating the cycle, we can get rid of it easily

**Comment by wildum** [comment]
I believe that Go does not allow cycle dependencies between modules. I tested and I got the error "import cycle not allowed"

**Comment by mx-psi** [comment]
> I believe that Go does not allow cycle dependencies between modules.

As I understand it, Go does not allow cycle dependencies between *packages* but it does allow them between *modules*.

>  I tested and I got the error "import cycle not allowed"

Maybe you can file the PR so I can take a look? Tackling this issue shouldn't need moving code around, so I am confused as to how this error could happen

**Comment by wildum** [comment]
Apologies about my previous statements, my implementation was wrong, you are correct :)
The PR is open: https://github.com/open-telemetry/opentelemetry-collector/pull/11229
