### ISSUE TITLE
Make test packages into separate modules

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#11216]
Similar to what we did in the case of `consumertest` (see #10692), we can turn the `exportertest`, `receivertest`, `extensiontest`, `processortest` and `connectortest` packages into modules. 

- [x] #11461
- [x] #11462
- [x] #11463
- [x] #11464
- [x] #11465
- [x] #11218
- [x] #11460

**Comment by wildum** [comment]
I can help with this one, I can start with the processortest pkg

**Comment by mx-psi** [comment]
Thanks! I opened a subissue for processortest

**Comment by wildum** [comment]
I did it for the connectortest pkg: https://github.com/open-telemetry/opentelemetry-collector/pull/11228

I can also do it for the extension once the PR for the connector is reviewed.

For the processor, receiver and exporter it's a bit more complicated because the helper pkgs  don't have their own modules which creates cyclic dependencies as explained in https://github.com/open-telemetry/opentelemetry-collector/issues/11218 (the processortest pkg should depend on the processor pkg but the processor pkg should not depend on the processortest pkg)

**Comment by bogdandrutu** [comment]
@mx-psi doesn't this cause lots of duplicate code, since we cannot use the test package in the main package because of circular deps? E.g. you cannot use `processortest` in the `processor` package for testing reasons.

**Comment by mx-psi** [comment]
@bogdandrutu This causes zero duplicate code. You can use `processortest` in the `processor` package; there are no cycles between Go modules, only cycles between Go packages, so this does not improve or worsen cycles

**Comment by bogdandrutu** [comment]
If that is ok, this should be fine. Do we do this for all test packages? consumer/component/etc?

**Comment by mx-psi** [comment]
I think doing it everywhere gives us more flexibility, yes, these are test APIs that we may want to change more liberally

**Comment by wildum** [comment]
the PRs are modifying a lot of go.mod files and it conflicts with main pretty easily. I already rebased once on Friday but it conflicts again now. I would appreciate if a maintainer could merge it right after I rebase or if the maintainer could rebase it and merge it

**Comment by bogdandrutu** [comment]
Also `componenttest`

**Comment by bogdandrutu** [comment]
> the PRs are modifying a lot of go.mod files and it conflicts with main pretty easily. I already rebased once on Friday but it conflicts again now. I would appreciate if a maintainer could merge it right after I rebase or if the maintainer could rebase it and merge it

If you can rebase and ping me on Slack, I can do that right away.

**Comment by wildum** [comment]
it's a bit late for me today (I'm in EMEA), we can do this tomorrow if you have time, I will prepare it for the late afternoon my time and ping you at around this time

**Comment by mx-psi** [comment]
Updated with componenttest and authtest. I will move this to the component milestone since it's the closest to get completed

**Comment by mx-psi** [comment]
Only `confmaptest` remains, but we can't really split that one since confmap is 1.0 :( Closing!
