### ISSUE TITLE
Add more coverage to mdatagen

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#11219]
We should add more tests, for example by templating a connector.

              LGTM. Your move of the code from main.go to internal/command.go shows we don't have enough test coverage for some of the templating functions, something we can spin into a new issue.

_Originally posted by @atoulme in https://github.com/open-telemetry/opentelemetry-collector/pull/11196#pullrequestreview-2316358972_

**Comment by narcis96** [comment]
@atoulme I'm interested in working on this! What do you think ?

**Comment by narcis96** [comment]
@bogdandrutu @atoulme PTAL on https://github.com/open-telemetry/opentelemetry-collector/pull/11352
