### ISSUE TITLE
Default batch size potentially too large for OTLP exporter

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-collector#1122]
**Describe the bug**
Correctness tests using golden dataset result in error when using the default batch process settings.

**Steps to reproduce**
Remove this line from correctness_test.go
    send_batch_size: 1024

**What did you expect to see?**
Tests to pass.

**What did you see instead?**
grpc: received message larger than max (4987657 vs. 4194304)

**What version did you use?**
Version: 6dcfa475e2c0a31d891801a0992f62e889674162

**What config did you use?**
Config: See testbed/correctness/correctness_test.go

**Environment**
OS: OS X
Compiler(if manually compiled): go1.14.3 darwin/amd64

**Additional context**

**Comment by bogdandrutu** [comment]
@kbrockhoff the max message size can be configured https://github.com/open-telemetry/opentelemetry-collector/blob/master/config/configgrpc/configgrpc.go#L122 to a larger value if the intent is to support larger batches.

I think this works as expected, gRPC otlp receiver respects the config. I would close this issue but feel free to reopen or start a new issue if this config is not enough.

**Comment by cwegener** [comment]
For anyone who comes across this post and is wondering what "Line 122" in `configgrpc.go` actually refers to in Bogdan's comment.
It's this:  https://github.com/open-telemetry/opentelemetry-collector/blob/8a385c22e5f7e05d790cd992baafcb31ea42db9a/config/configgrpc/configgrpc.go#L128-L129
