### ISSUE TITLE
OTLP exporter status codes to retry on are incorrect

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-collector#1123]
**Describe the bug**
OTLP exporter retries sending of data when receiving back a ResourceExhausted status code even though the call will never succeed.

**Steps to reproduce**
Remove this line from correctness_test.go and then run tests.
    send_batch_size: 1024

**What did you expect to see?**
Log message reporting the problem and dropping of the message.

**What did you see instead?**
Nothing. Have to put a breakpoint in exporter/otlpexporter/exporter.go at line 116 to identity the problem.

**What version did you use?**
Version: 6dcfa475e2c0a31d891801a0992f62e889674162

**What config did you use?**
Config: See testbed/correctness/correctness_test.go

**Environment**
OS: OS X
Compiler(if manually compiled): go1.14.3 darwin/amd64

**Additional context**

**Comment by bogdandrutu** [comment]
@kbrockhoff  is this resolved?

**Comment by tigrannajaryan** [comment]
@kbrockhoff I see this is assigned to you. Did you intend to work on this?

**Comment by kbrockhoff** [comment]
I won't have time to work on it for at least two weeks. If somebody else does not pick it up by then, I will work on it

**Comment by tigrannajaryan** [comment]
@kbrockhoff OK. From the description I think what you are saying is that we should treat ResourceExhausted as a fatal error and should not retry. Is ResourceExhausted fatal in the sense that retries will never succeed?

**Comment by kbrockhoff** [comment]
In my experience if the message rate is high enough to trigger throttling, you will never be able to catch up. Dropping data is the only way to restore service.

**Comment by bogdandrutu** [comment]
I think this is fixed.
