### ISSUE TITLE
Update Prometheus to v2.19.0

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1124]
**Is your feature request related to a problem? Please describe.**
OpenTelemetry Collector currently depends on Prometheus v2.13.0 (September 2019), which is missing some of the features and bugfixes from the latest v2.19.0 release.

**Describe the solution you'd like**
- Update `go.mod` dependency to v2.19.0 (it's written as`v1.8.2-0.20200609102542-5d7e3e970602` by `go mod`)
- Fix breaking changes in Prometheus Receiver (`Appender` interface)
- Fix conflicting dependencies: see https://github.com/uber/tchannel-go/issues/781 - **this a blocker, breaking Jaeger receiver**

**Additional context**
One specific feature we need is support for `selectors:` section in the Kubernetes discovery config for Prometheus, which was introduced in Prometheus v2.17.0: https://github.com/prometheus/prometheus/pull/6807

**Comment by nilebox** [comment]
Please assign this issue to me.

**Comment by nilebox** [comment]
Updating Jaeger to v1.18.0: #1132
Still blocked on https://github.com/jaegertracing/jaeger/issues/1972.
Getting the following error:
```
# github.com/jaegertracing/jaeger/cmd/agent/app/processors
../../go/pkg/mod/github.com/jaegertracing/jaeger@v1.18.0/cmd/agent/app/processors/thrift_processor.go:71:30: cannot use trans (type *customtransport.TBufferedReadTransport) as type thrift.TTransport in argument to factory.GetProtocol:
	*customtransport.TBufferedReadTransport does not implement thrift.TTransport (wrong type for Flush method)
		have Flush() error
		want Flush(context.Context) error
```

This is due to Jaeger using an outdated Thrift dependency.

**Comment by pavolloffay** [comment]
@nilebox I have submitted a PR to update the Jaeger receiver https://github.com/open-telemetry/opentelemetry-collector/pull/1203.
