### ISSUE TITLE
Add build commands for Windows MSI installer

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#1125]
**Add a command to build a Windows MSI installer**

I'm intending to use [wix](https://wixtoolset.org) to generate the MSI, and [wixl / wixl-heat](https://wiki.gnome.org/msitools) to run this with make on Linux, if that is relatively straightforward to get working. Failing that, I'll add some powershell commands.

**Questions:**

It wouldn't make sense to bake any "default" config into the MSI. Instead, I believe we can do either or both of the following (I need to confirm that the second point is possible, but it looks like it should be doable with the right `wix` config):

- Make the config file an argument to the build command
- Make the config file an argument that needs to be passed into the MSI at install time

If we do the second option, then we can produce a "generic" MSI that is broadly useful (that could be published). The install command would require something like `msiexec /i otelcol.msi CONFIG=config.yaml /q`

If we do the first option, then we can bake a customizable-at-build-time config into the generated MSI and users could simply install this with `msiexec /i otelcol.msi /q`. This could be useful for vendors who want to package their own default config.

Is there any desire for either of these options in the Core or Contrib repos? And if so, would we want to include any of this as part of CI?

**Comment by jrcamp** [comment]
> I'm intending to use wix to generate the MSI

👍 

Maybe we could install https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/otel-local-config.yaml similar to how the [Docker image](https://opentelemetry.io/docs/collector/about/) does. If a user wants to use it they could set (just making up a path) `CONFIG=%programfiles%\OT\otel-local-config.yaml` or if they've written their own config they would put it on the filesystem themselves (or maybe a tool like chef) then set CONFIG to point to it. It'd be nice to have an out of the box experience that just works without any config but it really comes down to which vendor you're using.

> If we do the first option, then we can bake a customizable-at-build-time config into the generated MSI and users could simply install this with msiexec /i otelcol.msi /q. This could be useful for vendors who want to package their own default config.

I wonder if this is likely to be used given many times things need to be user-configured like access tokens, etc. Guess it depends on how well-known the environment is, like if it's reporting to some other collector at a well-known address.

> Is there any desire for either of these options in the Core or Contrib repos? And if so, would we want to include any of this as part of CI?

Yeah I think we should have it in core and contrib seeing as we already produce a win32 binary in core. How it gets including in CI/release process I don't really know much about how that works. Maybe @owais or @dmitryax can help on how to add this to release.

**Comment by james-bebbington** [comment]
> Maybe we could install https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/otel-local-config.yaml similar to how the [Docker image](https://opentelemetry.io/docs/collector/about/) does.

Hmm that's weird. The Docker image doesn't seem to include any config by default from what I saw? I think the documentation is incorrect and you would actually need to mount the local config file as part of the docker run command if you want that to work? But maybe we should update the build commands to copy in the default config as per what the documentation implies.

**Comment by owais** [comment]
We don't publish docker images with any default config. We expect the user to mount a config file at `/etc/otel/config.yaml`.

**Comment by owais** [comment]
> Is there any desire for either of these options in the Core or Contrib repos? And if so, would we want to include any of this as part of CI?

Yes! This would be great to have in CI. I think we already have a window verification build. We can add a this step after that (and other build/test steps) in the publish pipeline. The publish step should also upload the MSI files to Github releases. Currently we only upload linux binaries and source tarballs.

**Comment by bogdandrutu** [comment]
@james-bebbington is this resolved? If yes please close the issue.
