### ISSUE TITLE
Update Jaeger to v1.18.0

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1126]
**Is your feature request related to a problem? Please describe.**
Collector is currently using Jaeger v1.17.0: https://github.com/open-telemetry/opentelemetry-collector/blob/b28cbd9c8e2e70bf385c3e4788ada839aa457b7d/go.mod#L28, which has a dependency on https://github.com/uber/tchannel-go. The `tchannel-go` uses an old Thrift release (a fork of `v0.9.3` AFAICT), which is incompatible with the latest Thrift `v0.13.0`.
As a result, we can't bring dependencies that depend on newer Thrift releases.
One specific example is Prometheus: #1124

**Describe the solution you'd like**
In Jaeger v1.18.0 the dependency on `tchannel-go` was removed (see changelist in https://github.com/jaegertracing/jaeger/releases/tag/v1.18.0), which should resolve the issue described above, and unblock updating the Prometheus dependency #1124

**Additional context**
The issue was originally reported on the `tchannel-go` side: https://github.com/uber/tchannel-go/issues/781, but that may not be necessary if we get rid of this dependency altogether.

**Comment by nilebox** [comment]
Actually, Jaeger still has a dependency on `tchannel-go`, as well as old Thrift dependency: `v0.0.0-20151001171628-53dd39833a08` (https://github.com/jaegertracing/jaeger/blob/b46738c68a906f7330e5e1a5ba6937b58e52b9dc/go.mod#L10), so dependency update won't resolve the issue.

In https://github.com/open-telemetry/opentelemetry-collector/blob/b28cbd9c8e2e70bf385c3e4788ada839aa457b7d/receiver/jaegerreceiver/trace_receiver.go#L33, we import Jaeger package which imports Thrift (https://github.com/jaegertracing/jaeger/blob/master/cmd/agent/app/processors/thrift_processor.go), so we still need to resolve https://github.com/jaegertracing/jaeger/issues/1972 to unblock #1124

/cc @pavolloffay @yurishkuro

**Comment by yurishkuro** [comment]
Dependency on tchannel was not fully removed (it's still in go.mod), but a refactoring was done so that you might not pick up those packages anymore.

**Comment by nilebox** [comment]
Still fail to update Prometheus to v2.19.0, getting the error for Jaeger:
```
# github.com/jaegertracing/jaeger/cmd/agent/app/processors
../../go/pkg/mod/github.com/jaegertracing/jaeger@v1.18.0/cmd/agent/app/processors/thrift_processor.go:71:30: cannot use trans (type *customtransport.TBufferedReadTransport) as type thrift.TTransport in argument to factory.GetProtocol:
	*customtransport.TBufferedReadTransport does not implement thrift.TTransport (wrong type for Flush method)
		have Flush() error
		want Flush(context.Context) error
```
i.e. latest releases of Jaeger and Prometheus are still incompatible.
