### ISSUE TITLE
Use confighttp.NewDefaultClientConfig instead of manually creating struct

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector#11274]
Related to second point in: https://github.com/open-telemetry/opentelemetry-collector/issues/9478#issuecomment-2241891068.

Move away from manually creating `confighttp.ClientConfig` in favor of using `confighttp.NewDefaultClientConfig`. 

This is necessary for the following components:
- [x] [otlphttpexporter](https://github.com/open-telemetry/opentelemetry-collector/pull/11273)

This will be done following conditions:
- Fields that are currently different than the default will be updated after call to `NewDefaultClientConfig`
- Fields that are same as default will not be set manually anymore
- Fields that are set in the default but currently unset in above components will be either manually unset (for backwards compatibility) or will be updated to match default.

For the third point, I am unsure of which approach to follow. An example is the `otlphttpexporter` (#11273),  where previously `MaxIdleConns`, `MaxIdleConnsPerHost`, `MaxConnsPerHost` and `IdleConnTimeout` were unset (equivalent of `nil`), which is different than the default which has values.

**Comment by bogdandrutu** [comment]
Can you please separate this into 2 different issues: one for core components and one for contrib?
