### ISSUE TITLE
Inefficient use of sliceOfValues in profiles data

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#11281]
We should never use sliceOfValues for large objects (more than ~32B). See https://github.com/open-telemetry/opentelemetry-collector/pull/10195 where everything is marked as "nullable" which will make re-allocation which happens quite often during unmarshaling very expensive because copies lots of data.

One concrete example `MappingSlice` or `LocationSlice` should not be a value slice. But someone needs to re-evaluate all of them.

**Comment by bogdandrutu** [comment]
Assigning to @mx-psi based on the maintainer who merged the PR.

**Comment by mx-psi** [comment]
I am not going to work on this any time soon since I am focusing on Collector 1.0, so I am un-assigning myself to make that clear

**Comment by bogdandrutu** [comment]
@mx-psi I understand that, but we need to make it clear that approvers/maintainers that are reviewing PRs become the owners of the code, so hence you need to find someone to help you with this.

**Comment by narcis96** [comment]
Hi@bogdandrutu and @mx-psi ! I'm interested in working on this! Would you be able to guide me on what needs to be done?

**Comment by dmathieu** [comment]
As the person who's been working on profiles so far, I'm looking into this.
