### ISSUE TITLE
Deprecate and remove processorhelper.NewUnhealthyProcessorCreateSettings

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#11307]
Not used and equivalent with NewNopSettings

**Comment by zzzk1** [comment]
@bogdandrutu, may I give it a try?

**Comment by olamideTiana** [comment]
@bogdandrutu Can I work on this as well?

**Comment by bogdandrutu** [comment]
@olamideTiana sorry, @zzzk1 is on this one. Happy to file more opportunities

**Comment by bogdandrutu** [comment]
@olamideTiana you can give this a try, I don't see yet a PR from @zzzk1

**Comment by olamideTiana** [comment]
Thank you @bogdandrutu
