### ISSUE TITLE
Missing image for opentelemetry-collector-builder on DockerHub

### ISSUE THREAD

**Issue by bootstrap314** [open-telemetry/opentelemetry-collector#11347]
**Describe the bug**
No tags are present on DockerHub for opentelemetry-collector-builder

**Steps to reproduce**
See: [otel/opentelemetry-collector-builder](https://hub.docker.com/r/otel/opentelemetry-collector-builder)
**What did you expect to see?**
A list of tags I can use to run `opentelemetry-collector-builder` from
**What did you see instead?**
Nothing.

**Comment by andrzej-stencel** [comment]
Hey @bootstrap314, thanks for the report. It's true, the builder images haven't been published. This is expected, as the pull request to publish those images as part of the release process https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671 has not been merged before releasing v0.111.0 (the PR is currently neither merged nor approved as I'm writing this comment).

The pull request adding the docs describing the builder container image https://github.com/open-telemetry/opentelemetry-collector/pull/11234 has been merged perhaps a bit prematurely, with the assumption that https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671 would be merged before releasing v0.111.0. We probably should have waited with merging until https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671 is merged. I believe we should revert that and restore it only after the images are actually published.
