### ISSUE TITLE
Span Kind data loss in OpenCensus protocol

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-collector#1136]
**Describe the bug**
OpenCensus protocol only defines Unknown, Client and Server span kinds. When translating between OTLP protocol and OpenCensus protocol this results in data loss because other Kind values get translated to Unknown.

**Steps to reproduce**
Run the tracing correctness tests and view the results summary.

**What did you expect to see?**
Zero failure count.

**What did you see instead?**
Failure count of 296 and failures: Kind,1!=0,count=296;.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Correctness test configuration per receiver-exporter combination.

**Environment**
OS: OS X
Compiler(if manually compiled): go1.14.3 darwin/amd64

**Additional context**

**Comment by tigrannajaryan** [comment]
Supposedly this should be handled by https://github.com/open-telemetry/opentelemetry-collector/blob/e3df9f36f13f08aee0edcbffe89ee4e27cfb3a6a/translator/internaldata/traces_to_oc.go#L174 and https://github.com/open-telemetry/opentelemetry-collector/blob/e3df9f36f13f08aee0edcbffe89ee4e27cfb3a6a/translator/internaldata/oc_to_traces.go#L239
But apparently it is not.
