### ISSUE TITLE
Span translation to Jaeger data loss

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-collector#1137]
**Describe the bug**
Translation of OTLP protocol data by Jaeger exporter results in some data loss and incorrect translations.

**Steps to reproduce**
Execute golden dataset correctness tests and view test results summary.

**What did you expect to see?**
Zero failure count.

**What did you see instead?**
Failure count of 3247 and failures: TraceState,"lasterror=f39cd56cc44274fd5abd07ef1164246d10ce2955"!="",count=2719; Kind,1!=0,count=296; Status,(*v1.Status)(nil)!=&v1.Status{Code:0, Message:""},count=232;.

**What version did you use?**
Version: latest

**What config did you use?**
Config: Correctness test config per receiver-exporter combination.

**Environment**
OS: any
Compiler(if manually compiled): any

**Additional context**
Recommend fixing #1136 first as this will resolve some errors and then rerun correctness tests to determine what issues remain.

**Comment by bogdandrutu** [comment]
@kbrockhoff can I close this? Is this still a problem?

**Comment by kbrockhoff** [comment]
This is fixed
