### ISSUE TITLE
Span translation to Zipkin data loss

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-collector#1138]
**Describe the bug**
Translation of OTLP protocol data by Zipkin exporter results in some data loss and incorrect translations.

**Steps to reproduce**
Execute golden dataset correctness tests and view test results summary.

**What did you expect to see?**
Zero failure count.

**What did you see instead?**
Failure count of 9283 and failures: Attributes,0!=2,count=3586; Links,2!=0,count=2441; Status,&v1.Status{Code:0, Message:""}!=(*v1.Status)(nil),count=241; TraceState,"lasterror=f39cd56cc44274fd5abd07ef1164246d10ce2955"!="",count=2719; Kind,1!=0,count=296;

**What version did you use?**
Version: latest

**What config did you use?**
Config: Correctness test config per receiver-exporter combination.

**Environment**
OS: any
Compiler(if manually compiled): any

**Additional context**
Recommend fixing #1136 first as this will resolve some errors and then rerun correctness tests to determine what issues remain.

**Comment by bogdandrutu** [comment]
@kbrockhoff  can I close this? Is this still a problem?

**Comment by kbrockhoff** [comment]
This is still an issue. Plan on fixing this at the same time as #1303 and #1304
