### ISSUE TITLE
Metrics tagging with the same name but different values bug

### ISSUE THREAD

**Issue by bcorrigeux** [open-telemetry/opentelemetry-collector#1149]
**Describe the bug**
 I have tested creating metrics with both python and golang using the opencensus receiver in python and the prometheus receiver in golang, exporting to prometheus in both cases. When i send in metrics with the same name but different tags and values i expect to see them show up separately in prometheus (as they do when exporting directly to prometheus) but when the metrics go through the ot-collector i find the metrics with different labels but the same name show up with the same value in prometheus.
Example
metric foo{a=1}=123 and metric foo{a=2}=456 -> collector -> prometheus i see foo{a=1}=foo{a=2}=123

**Steps to reproduce**
Send two of the same metric but with different tags to the collector then to prometheus. In prometheus the output is the metric with both tags but the same value. 

**What did you expect to see?**
The correct value on each metric/tag combo
The same result as when exporting directly to prometheus

**What did you see instead?**
Both metric/tag combos but with only one of the values and the other one dropped

**What version did you use?**
"GitHash":"746db76"
following instructions below and later modifying collector config for extra testing
https://github.com/open-telemetry/opentelemetry-collector/tree/master/examples/demo

**What config did you use?**
attached otel-collector-config.yml  and docker-compose.yml
[docker-compose.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector/files/4801515/docker-compose.yaml.txt)
[otel-collector-config.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector/files/4801518/otel-collector-config.yaml.txt)

**Environment**
Debian GNU/Linux 9 (stretch)

**Additional context**

**Comment by arpitjindal97** [comment]
I'm facing a similar problem like this. I have configured collector to scrape metrics from 2 Grafana. I'm also add labels to both of them for differentiating but metrics is coming from 1 Grafana at a time.
