### ISSUE TITLE
OTEL collector builder(v0.112.0) use a non-existing httpsprovider package

### ISSUE THREAD

**Issue by weijiany** [open-telemetry/opentelemetry-collector#11547]
**Describe the bug**

It will build failed when I use v0.112.0 dist version to build my customized OTEL collector.

**Steps to reproduce**

1. Preconditions
- golang v1.23
- git cli
- builder v0.112.0
2. Create **builder-config.yaml** file
     ```yaml
    dist:
      module: github.com/open-telemetry/opentelemetry-collector-releases/contrib
      name: otelcol-contrib
      description: OpenTelemetry Collector Contrib
      version: 0.112.0
      output_path: ./_build
      otelcol_version: 0.112.0

    extensions: []

    receivers:
      - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.112.0

    processors:
      - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.112.0
      - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.112.0

    exporters:
      - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.112.0
      - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.112.0

    connectors:
      - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector v0.112.0
     ```
3. Run `builder --skip-compilation --config builder-config.yaml`, it will show the following logs:
     ```txt
    2024-10-28T13:05:22.018+0800    INFO    internal/command.go:125 OpenTelemetry Collector Builder {"version": "v0.112.0"}
    2024-10-28T13:05:22.020+0800    INFO    internal/command.go:161 Using config file       {"path": "builder-config.yaml"}
    2024-10-28T13:05:22.020+0800    INFO    builder/config.go:142   Using go        {"go-executable": "/opt/homebrew/bin/go"}
    2024-10-28T13:05:22.022+0800    INFO    builder/main.go:101     Sources created {"path": "./_build"}
    Error: failed to update go.mod: go subcommand failed with args '[mod tidy -compat=1.22]': exit status 1, error message: go: downloading go.opentelemetry.io/collector/confmap/provider/fileprovider v0.112.0
    go: downloading go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.112.0
    go: downloading go.opentelemetry.io/collector/confmap/provider/envprovider v0.112.0
    go: downloading go.opentelemetry.io/collector/confmap/provider/httpprovider v0.112.0
    go: downloading go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.112.0
    go: go.opentelemetry.io/collector/confmap/provider/httpsprovider@v0.112.0: reading go.opentelemetry.io/collector/confmap/provider/httpsprovider/go.mod at revision confmap/provider/httpsprovider/v0.112.0: unknown revision confmap/provider/httpsprovider/v0.112.0
     ```

**Additional context**

I have tried to find the `confmap/provider/httpsprovider/v0.112.0` in [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) repository, it doesn't exist. I guess maybe it the root cause. 🤔

**Comment by vincentfree** [comment]
I just got the same issue, I do not request this module myself, but it's used when version 0.112.0 is referenced.

**Comment by vincentfree** [comment]
Seems like the versions have been updated here: #11357 
When running the builder I don't see the version defined: `1.17.0` but I get the collector version `0.112.0` Which is not the correct version anymore.

**Comment by vincentfree** [comment]
It seems that the sources are there but the pkg proxy does not resolve them correctly.

**Comment by andrzej-stencel** [comment]
Please try again, the providers `v1.18.0` have been double-tagged as `v0.112.0`, which should fix this issue.

As an ultimate solution, I recommend to explicitly list providers in your builder config like this:

```yaml
dist:
 module: github.com/open-telemetry/opentelemetry-collector-releases/contrib
 name: otelcol-contrib
 description: OpenTelemetry Collector Contrib
 version: 0.112.0
 output_path: ./_build
 otelcol_version: 0.112.0

extensions: []

receivers:
 - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.112.0

processors:
 - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.112.0
 - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.112.0

exporters:
 - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.112.0
 - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.112.0

connectors:
 - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector v0.112.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
```

**Comment by antonio** [comment]
> As an ultimate solution, I recommend to explicitly list providers in your builder config like this

We've also been affected by this problem a couple of times. Can you elaborate on why is this better than letting the builder resolve the dependencies?

If the providers weren't explicitly listed in the manifest of e.g. https://github.com/open-telemetry/opentelemetry-collector-releases/pull/705, would the tests have failed because of the missing tag?

**Comment by robododge** [comment]
Same issue but a little different follow up question.  
Even after the the double tagging, I could not get any providers at v0.112.0 to resolve using standard go proxy.

I added the providers block as recommend, by @andrzej-stencel above, and the proper versions of the providers appeared in go.mod and `go mod tidy` was happy.  

**Question**: If the OCB chose to use v0.112.0 but the true tag is v1.18.0, wouldn't it be much cleaner just to have the OCB to choose v1.18.0?  No confusing double tagging or resolving issues.

**Comment by antonio** [comment]
> Even after the the double tagging, I could not get any providers at v0.112.0 to resolve using standard go proxy.

Right, I forgot to mention that this is not working for me either.

**Comment by vincentfree** [comment]
> Please try again, the providers `v1.18.0` have been double-tagged as `v0.112.0`, which should fix this issue.
> 
> As an ultimate solution, I recommend to explicitly list providers in your builder config like this:
> 
> ```yaml
> dist:
>  module: github.com/open-telemetry/opentelemetry-collector-releases/contrib
>  name: otelcol-contrib
>  description: OpenTelemetry Collector Contrib
>  version: 0.112.0
>  output_path: ./_build
>  otelcol_version: 0.112.0
> 
> extensions: []
> 
> receivers:
>  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.112.0
> 
> processors:
>  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.112.0
>  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.112.0
> 
> exporters:
>  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.112.0
>  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.112.0
> 
> connectors:
>  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector v0.112.0
> 
> providers:
>   - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
>   - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
> ```

I have done this right after reporting the issue and it works but this means users have to manage yet another dependency and keep trace of which collector version needs which provider version.

**Comment by antonio** [comment]
> I have done this right after reporting the issue and it works but this means users have to manage yet another dependency and keep trace of which collector version needs which provider version.

For anyone that can find it helpful, this is how I'm getting the provider version number in my scripts, using the GitHub release and [the gh cli](http://github.com/cli/cli):

```
core_version="v0.112.0"
providers_version="$(gh release -R open-telemetry/opentelemetry-collector view $core_version | grep $core_version | perl -nle 'm/(v1\.\d+\.\d+)/; print $1' | sed '/^$/d' | uniq)"
```

Now, this is a hacky, brittle solution, as it depends on the release notes being formatted the way they are. That's why I'd prefer a single tag or that `ocb` resolves the provider version itself.
