### ISSUE TITLE
go.opentelemetry.io/collector@v0.109.0 with error does not contain experimental/storage package

### ISSUE THREAD

**Issue by janeli1** [open-telemetry/opentelemetry-collector#11600]
**Describe the bug**
I used go.opentelemetry.io/collector@v0.109.0 in my go.mod file, when I run go mod tidy,
I got error as:
```
go: code.uber.internal imports
	go.opentelemetry.io/collector/exporter/exporterhelper imports
	go.opentelemetry.io/collector/exporter/internal/queue imports
	go.opentelemetry.io/collector/extension/experimental/storage: module go.opentelemetry.io/collector@latest found (v0.0.0-00010101000000-000000000000, replaced by go.opentelemetry.io/collector@v0.109.0), but does not contain package go.opentelemetry.io/collector/extension/experimental/storage
```

**Steps to reproduce**
Add go.opentelemetry.io/collector v0.109.0 in go.mod and run "go mod tidy"

**What did you expect to see?**
After this change https://github.com/open-telemetry/opentelemetry-collector/pull/11020  included in v0.109.0, experimental/storage is exposed, so this error is not expected. 
I tried v0.108.1 as well, I got the same error. 

**What did you see instead?**
I got error as:
```
go: code.uber.internal imports
	go.opentelemetry.io/collector/exporter/exporterhelper imports
	go.opentelemetry.io/collector/exporter/internal/queue imports
	go.opentelemetry.io/collector/extension/experimental/storage: module go.opentelemetry.io/collector@latest found (v0.0.0-00010101000000-000000000000, replaced by go.opentelemetry.io/collector@v0.109.0), but does not contain package go.opentelemetry.io/collector/extension/experimental/storage
```

**What version did you use?**
go.opentelemetry.io/collector@v0.109.0

**Comment by dmathieu** [comment]
The module does exist, and can be imported:
https://pkg.go.dev/go.opentelemetry.io/collector/extension/experimental/storage

```golang
package main

import _ "go.opentelemetry.io/collector/extension/experimental/storage"

func main() {}
```

Here with v0.113.0, but 0.109.0 does exist as well.

Could you share the content of a `go.mod` that reproduces your issue?
I also see the following in your error:

> module go.opentelemetry.io/collector@latest found (v0.0.0-00010101000000-000000000000, replaced by go.opentelemetry.io/collector@v0.109.0)

It looks like something is using `latest`, with a replace statement.
It's likely a replace statement is making Go conflict different versions (and possibly local copies of the code), which is causing that error.

**Comment by janeli1** [comment]
Hi, I manually added 
`require go.opentelemetry.io/collector/extension/experimental/storage v0.113.0`
in my go.mod and it is able to resolve the problem.
Thank you!
