### ISSUE TITLE
[service] logs emitted by collector don't follow severity

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#11717]
The collector supports emitting its internal logs via OTLP. After testing this functionality, it appears that logs of all severities are emitted via the logger provider configured. This is because the otelzap bridge doesn't have a configuration for severity level. This requires a separate processor ([minsev](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/processors/minsev)) which is currently not supported by the otel configuration schema.

I will submit a pull request that proposes wrapping the Tee'd zap core into another zap core that will apply the filtering before logs are sent to the logger provider.

**Comment by skandragon** [comment]
I was coming here to report this exact issue.  Will the level be set per provider?

I would like to not get debug messages for sure, generally :)

**Comment by AntonBazhal** [comment]
Hey, great to see this issue fixed already! Any idea when the fix will be released?

**Comment by codeboten** [comment]
@AntonBazhal it will be released in v0.115.0 which is set to go out this week
