### ISSUE TITLE
Unable to set "additionalLabels"

### ISSUE THREAD

**Issue by diamantn** [open-telemetry/opentelemetry-collector#11777]
**Describe the bug**
YAML parse error on opentelemetry-collector/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context

**Steps to reproduce**
Add:
--set-json 'additionalLabels={"app.kubernetes.io/part-of": "myApp"}'

**What version did you use?**
0.110.3

**Comment by dmathieu** [comment]
This looks like an [opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-operator) issue?
