### ISSUE TITLE
JSON/HTTP support in OTLP receiver

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1177]
We need to decide if the currently supported JSON via gRPC Gateway should be made official, or whether we need to address the issue https://github.com/open-telemetry/opentelemetry-proto/issues/129 first.

**Additional context**
We still need to keep gRPC Gateway integration to support "Protobuf over HTTP" protocol introduced in #1021.
We just need to disable the default "wildcard" handler, which accepts JSON by default: https://github.com/grpc-ecosystem/grpc-gateway/blob/ee3ef70b7777cde4e61e4e224cb11e92beecee6a/runtime/marshaler_registry.go#L78

**Comment by tigrannajaryan** [comment]
I fail to see the problem. This is how JSON encoding in grpc-gateway is supposed to work. Why do we not want to support it?

**Comment by nilebox** [comment]
> This is how JSON encoding in grpc-gateway is supposed to work. 

Yes, but it has issue with encoding trace/span IDs and JSON is not officially supported yet AFAIK. See https://github.com/open-telemetry/opentelemetry-proto/issues/129
It's better to disable unsupported protocol to prevent clients from using it IMO? We can always enable back if we decide that https://github.com/open-telemetry/opentelemetry-proto/issues/129 doesn't need to be addressed, or implement a custom marshaler for it.

@tigrannajaryan see your own comment in the discussion thread https://github.com/open-telemetry/opentelemetry-proto/issues/129#issuecomment-622443175: JSON support is not documented by the spec.

@yurishkuro has previously shared that in Jaeger they use a custom serialization to solve the problem with base64 vs hex encoding.
Also see @bogdandrutu 's comment https://github.com/open-telemetry/opentelemetry-proto/issues/129#issuecomment-630413454

The consensus seems to be that JSON is not supported, but in fact it is technically supported by collector. We should either declare it as supported, or disable it to make the documentation and implementation consistent. Please correct me if I'm wrong.

**Comment by nilebox** [comment]
@tigrannajaryan @bogdandrutu @yurishkuro Alternatively, if we all agree that supporting JSON is important, I can look into addressing https://github.com/open-telemetry/opentelemetry-proto/issues/129 via custom marshaler instead.

Most likely, this will require defining new (internal) Go types specifically for unmarshalling trace spans, or using `gogo/protobuf`'s feature https://github.com/gogo/protobuf/blob/master/custom_types.md. It might be better to work on that once OTLP is considered stable with no planned breaking changes though.
Metrics don't have that issue AFAIK, so we could just use auto-generated types from `opentelemetry-proto` (i.e. keep current behavior).

**Comment by tigrannajaryan** [comment]
@nilebox I am not convinced https://github.com/open-telemetry/opentelemetry-proto/issues/129 is a problem that needs a solution either :-) It seems to me base64 is an acceptable way to encode trace id and span id in JSON.

**Comment by yurishkuro** [comment]
@tigrannajaryan I am personally conflicted about that. I often catch myself looking at raw trace data in JSON, maybe because UI doesn't show something, or there's some other information/correlation I am looking for. Having the IDs in JSON  base64 encoded makes it difficult to correlate. The tracing UI could be smart to recognize both encodings, but if I tag my logs with trace/span IDs and that's done in hex encoding, then the user needs to jump through hoops to correlate the data (not everything can be solved via UI integrations). I tend to agree with @Oberon00 (https://github.com/open-telemetry/opentelemetry-proto/issues/129#issuecomment-599686909), it could be better if we always used base64 instead of hex, including log fields.

**Comment by nilebox** [comment]
If we do want to support JSON and fine with base64 encoding, then no code changes are required (apart from making sure that we also use base64 in logs), but we need to document `application/json` as a supported OTLP protocol over HTTP, and then SDKs may start introducing support for it on the client side.

**Comment by nilebox** [comment]
Rephrased the issue to discuss the path to official JSON support rather than just disabling it.

**Comment by tigrannajaryan** [comment]
Spec was updated to require hex instead of base64 for trace id and span id: https://github.com/open-telemetry/opentelemetry-specification/pull/911

**Comment by tigrannajaryan** [comment]
This is now done and should confirm to OTLP/JSON spec. Closing. Submit separate bugs if any problems are found.
