### ISSUE TITLE
[Vote] Define naming guidelines for experimental APIs

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector#11783]
Forking from #11778 to agree on a naming decision

### Proposal

When introducing experimental APIs into a module already declared stable, use a different module with similar name that has `experimental` in the name in some form. The two proposed naming forms are
  * Option 1: Prefix package name with `x`. Example:
    * Stable package: `confighttp`
    * Experimental package: `xconfighttp`
  * Option 2: Suffix package name with `exp`. Example:
    * Stable package: `confighttp`
    * Experimental package: `confighttpexp`

The change to applied to https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#naming-convention

### Stakeholders

| Stakeholders                        | As defined on date | Number of people |
|-------------------------------------|--------------------|------------------|
| @open-telemetry/collector-approvers | 2024-12-02         | 10               |

### Voting options

Vote counts as of Dec 7:

| Option | Description | # Votes (stakeholders) | # Votes (total) |
|--------|-------------|------------------------|-----------------|
| Option 1 | Prefix package name with `x` | 3 | 5 |
| Option 2 | Suffix package name with `exp` | 2 | 3 |

### Result

The vote is in progress. A minimum of 4 total votes is required to select an option.

### Vote process

Please **leave a comment** with your vote and any additional context you would like to provide.
Start your comment with "I vote for **Option N**." and then provide any additional context.

### Related links

Include here any links to the RFC, other PRs and resources that help make an informed vote.

### Checklists

When starting the vote:

- [x] Announce the vote in the #otel-collector-dev CNCF Slack channel.
- [x] Add an entry to announce the vote in the next Collector SIG meeting.

For closing the vote:

- [x] At least five business days have passed since the vote was announced.
- [x] At least one-third of the stakeholders have voted.
- [x] The "Voting options" and "Result" sections have been updated reflecting the votes casted.
- [ ] The ~~RFC~~ docs have been updated reflecting the votes casted.

**Comment by dmitryax** [comment]
I vote for **Option 2** since it is easier to understand and short enough. If `x<module>` was an established pattern in the go ecosystem, I would consider it, but I'm not aware of any. Only https://pkg.go.dev/golang.org/x comes to mind, but it's not a prefix.

**Comment by dmathieu** [comment]
Option 2 also seems clearer to me.

**Comment by jpkrohling** [comment]
I vote for Option 1 -- "exp" can be confused with "exporter" depending on the context. A "x" prefix reminds me of "X-" for HTTP headers, which seems fitting here. The RFC 6648, which deprecates such prefixes, states in the intro:

> Historically, designers and implementers of application protocols have often distinguished between standardized and unstandardized parameters by prefixing the names of unstandardized parameters with the string "X-" or similar constructs (e.g., "x."), where the "X" is commonly understood to stand for "eXperimental" or "eXtension".

**Comment by mx-psi** [comment]
@yurishkuro Thanks for opening this. Would you mind following the steps under "When starting the vote"? Happy to bring this vote on the Collector SIG on your behalf if you add the topic to the agenda.

**Comment by yurishkuro** [comment]
@mx-psi done

**Comment by yurishkuro** [comment]
My vote (non-binding) is for Option 1. I like that it is more concise and (for me personally) more readable / obvious that this is "just like the main package name but with `x`".

**Comment by codeboten** [comment]
option 1 makes sense to me

**Comment by mx-psi** [comment]
I vote for **Option 2**. I feel like it is clearer and agree with the points been made by Dmitrii here https://github.com/open-telemetry/opentelemetry-collector/issues/11783#issuecomment-2512776944. I don't feel particularly strongly about this tho, I just want us to be consistent :smile:

**Comment by evan-bradley** [comment]
I vote for **Option 1**.

I agree with the reasons Juraci called out. Additionally, for me personally, it's easier to quickly parse `xpackagename` into `x` and `packagename` than it is to quickly parse `packagenameexp` into `packagename` and `exp`.

I also like that `x` is a little more abstract, because `exp` could be an abbreviation for any of the following technology-adjacent terms:

* exporter
* experience
* expectation
* expiration
* expression

All that said, I agree with Pablo that consistency is what matters, and ultimately regardless all of the name we should document that a given package is experimental.

**Comment by dmitryax** [comment]
Looks like we can conclude the vote and proceed with `x<version>` naming schema. I've submitted https://github.com/open-telemetry/opentelemetry-collector/pull/11836
