### ISSUE TITLE
Flaky load tests

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1180]
**Describe the bug**
Load tests running in CI build are flaky, and require repeating `git commit --amend` + `git push --force` a few times until they succeed (non-maintainers don't have permissions to re-run build in Circle CI).

Recent example: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1337/workflows/fdade6e0-3cbe-40db-865a-01574e39b7c0/jobs/8675/steps
Similar issue last week: https://github.com/open-telemetry/opentelemetry-collector/pull/1113#issuecomment-643918137

**Steps to reproduce**
Hard to reproduce by definition, just try sending a few PRs and see load tests randomly failing in Circle CI.

**What did you expect to see?**
Tests not being flaky :)

**What did you see instead?**
Tests are flaky 🤷

**Comment by tigrannajaryan** [comment]
All we can do for now is increase the limits to give more room when the CI machines are slow. A rule of thumb has been to use limits that are +15% to observed max. That is until we have a dedicated machine with stable performance to run load tests on.

**Comment by bogdandrutu** [comment]
@dmitryax merged a PR that fixes this.
