### ISSUE TITLE
"Prepare Release" action fails to add label

### ISSUE THREAD

**Issue by jade-guiton-dd** [open-telemetry/opentelemetry-collector#11808]
I recently merged a PR (#11744) to add a CI check which prevents PRs from being merged in `main` while a "Prepare Release" PR is open, enforcing the merge freeze described in the [release procedure](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md). To detect the Prepare Release PR, I decided to rely on a new "release:merge-freeze" label, to be added automatically to said PR.

However, during the latest release, the ["Prepare Release" action failed](https://github.com/open-telemetry/opentelemetry-collector/actions/runs/12130228415/job/33840863531), with the message _"opentelemetrybot does not have permission to update the pull request"_. The PR was still created, but the label was not added, presumably because the `OPENTELEMETRYBOT_GITHUB_TOKEN` used by the action does not have the permissions to add labels to PRs.

I see two possible solutions:
1. Generate a new token with the appropriate additional permission;
2. Have the bot comment on the PR / add something in the description that triggers another workflow which adds the label.

**Comment by atoulme** [comment]
1. seems like the painless option.

**Comment by mx-psi** [comment]
I am in favor of 1 as well

**Comment by mx-psi** [comment]
@open-telemetry/collector-approvers does (1) look good to you?

**Comment by mx-psi** [comment]
Looking at https://github.com/open-telemetry/community/blob/main/assets.md#opentelemetry-bot it may be hard to do (1) given that this is an OpenTelemetry-wide token. So we may want to look into an alternative solution

**Comment by jade-guiton-dd** [comment]
The idea to add the label using the regular CI token instead of the OTelBot token did not work out. The label was properly added, but [the release PR ended up being blocked by itself](https://github.com/open-telemetry/opentelemetry-collector/issues/11906):
- The initial run of the check on PR creation wasn't skipped because the PR did not have the label on creation, but by the time the check *actually* ran, it DID have the label, causing the check to fail.
- The check should have been re-run once the label was added, solving the issue, but _events caused by CI do not trigger CI_ (in fact, that is the entire raison d'être of the OTelBot)...

**Comment by jade-guiton-dd** [comment]
Right, that is what I was about to suggest. The other solution would be to try to convince the Technical Committee to give the OTel Bot permission to add labels, but that might not be worth the effort. The only issue I see with this is that we need to make sure release managers only ever use the bot to create the PR, but there's only one semi-recent instance of a release PR being created manually (#10190), so it's probably fine.

**Comment by mx-psi** [comment]
> The only issue I see with this is that we need to make sure release managers only ever use the bot to create the PR, but there's only one semi-recent instance of a release PR being created manually (https://github.com/open-telemetry/opentelemetry-collector/pull/10190), so it's probably fine.

I think a bot-only release is what we should be strive for so I don't see a big issue with that :robot:
