### ISSUE TITLE
Branch protection rules are different from contrib

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#11840]
Huh, it looks like the current branch protection rules require the `exporter/debugexporter` codeowner to approve PRs like this... we may want to either change the owners for `go.mod`/`go.sum` PRs or to change the rules to make them look more like contrib

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector/issues/11833#issuecomment-2532149177_
            
This is an issue since I merged #11766

cc @andrzej-stencel, I assume you don't want to review every dep update PR

**Comment by TylerHelmuth** [comment]
We need to add `@open-telemetry/collector-approvers` to all lines like https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS
