### ISSUE TITLE
Label release:merge-freeze should not block the release PR

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#11906]
See an example in https://github.com/open-telemetry/opentelemetry-collector/pull/11904

**Comment by jade-guiton-dd** [comment]
Note to future self: the label was correctly added to the release PR, but the "Merge freeze / Check" check was not skipped, even though it is supposed to: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/12358329691/job/34488568972
