### ISSUE TITLE
receiver/statsd: add statsd metrics receiver

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#121]

**Comment by huikang** [comment]
HI, Steve (@flands), I am interested in helping some tasks in the Otel project. Based on my understanding of [the migration doc](https://github.com/open-telemetry/opentelemetry-service/blob/master/docs/migrating-from-opencensus.md#migration-tasks), should this issue go to https://github.com/open-telemetry/opentelemetry-service-contrib? Thanks for your guidance.

**Comment by tigrannajaryan** [comment]
> Based on my understanding of the migration doc, should this issue go to https://github.com/open-telemetry/opentelemetry-service-contrib? Thanks for your guidance.

@huikang yes, that's correct. All receivers/exporters that didn't make into the core can be added to the contrib.

**Comment by bogdandrutu** [comment]
I will close this, if necessary we should consider adding this to the contrib.
