### ISSUE TITLE
Prometheus collector not respecting address in config file

### ISSUE THREAD

**Issue by leonsp-ai** [open-telemetry/opentelemetry-collector#1230]
**Describe the bug**
Prometheus receiver listen to traffic on localhost rather than 0.0.0.0 despite being configured to listen on 0.0.0.0

**Steps to reproduce**
1. Use the `otel/opentelemetry-collector-contrib:0.4.0` image
2. Configure Prometheus as follows:
    ```
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']
    ```

**What did you expect to see?**

Logs:

`2020-06-29T19:54:11.984Z	INFO	service/telemetry.go:94	Serving Prometheus metrics	{"address": "0.0.0.0:8888", "legacy_metrics": true, "new_metrics": false, "level": 3, "service.instance.id": ""}`

Network info:
 ```
    $ netstat -tulpn | grep LISTEN
    tcp        0      0 :::14268                :::*                    LISTEN      1/otelcontribcol
    tcp        0      0 :::13133                :::*                    LISTEN      1/otelcontribcol
    tcp        0      0 :::8888                 :::*                    LISTEN      1/otelcontribcol
 ```

**What did you see instead?**

Logs:

`2020-06-29T19:54:11.984Z	INFO	service/telemetry.go:94	Serving Prometheus metrics	{"address": "localhost:8888", "legacy_metrics": true, "new_metrics": false, "level": 3, "service.instance.id": ""}`

Network info:
```
    $ netstat -tulpn | grep LISTEN
    tcp        0      0 127.0.0.1:::14268       :::*                    LISTEN      1/otelcontribcol
    tcp        0      0 :::13133                :::*                    LISTEN      1/otelcontribcol
    tcp        0      0 :::8888                 :::*                    LISTEN      1/otelcontribcol
```

**What version did you use?**
Version: `0.4.0`

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: Alpine 3.12.0

**Additional context**
The manual workaround is to start otel-collector with this additional command-line parameter: `--metrics-addr=0.0.0.0:8888`

**Comment by jrcamp** [comment]
Dupe of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/355

**Comment by leonsp-ai** [comment]
Thanks. Sounds like it's fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/356
