### ISSUE TITLE
PR 1047 broke CI

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1237]
**Describe the bug**

Merge of PR https://github.com/open-telemetry/opentelemetry-collector/pull/1047 is causing CI to fail on the master branch.

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/1533/workflows/51ce08ed-22fd-43e3-bf03-b2d94c88ae17/jobs/10304/steps

Locally also the ` make test` target is failing. 

cc) @james-bebbington

**Steps to reproduce**

`make test` on the master/HEAD

**What version did you use?**
master/HEAD
af5bdb15ff48148e2bdf2b321d9f6dfb9bdca286

**Comment by james-bebbington** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/1238

**Comment by pavolloffay** [comment]
Done in #1238
