### ISSUE TITLE
Add 3 host metrics and delete vmmetricsreceiver

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#1240]
Currently we miss https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/vmmetricsreceiver/vm_metrics_constants.go#L63 `system/processes/xyz` metrics from vmmetricsreceiver and then we can remove the vmmetricsreceiver.

Would be good @james-bebbington if you can fix this soon so we can remove that old code.

**Comment by james-bebbington** [comment]
Pending https://github.com/shirou/gopsutil/pull/897

**Comment by bogdandrutu** [comment]
@james-bebbington you can start a PR with the two values that you already have and we can add the third one later.

**Comment by james-bebbington** [comment]
@bogdandrutu I think you can close this now
