### ISSUE TITLE
Log rotation in logging exporter

### ISSUE THREAD

**Issue by jan25** [open-telemetry/opentelemetry-collector#1262]
Logging exporter is handy for debugging reasons but if let to stay on it can fill up memory and cause OOM (even after sampling). Also, since this exporter is useful for checking recent logs(traces/spans) we could allow for auto cleanup of older logs from stdout.

I can think of 2 additional options to add in exporter config for this:
* `retention-time` - duration to keep logs for certain amount of time
* `max-num-logs` - amount of logs allowed to keep in stdout

Suggestions and more ideas?

**Comment by tigrannajaryan** [comment]
Zap logger that we use has no log rotation capabilities. [Their stance](https://github.com/uber-go/zap/issues/268#issuecomment-277176810) is that log rotation is an separate concern and I agree with them.

I am going to close this as "won't do" unless other @open-telemetry/collector-approvers have other thoughts.

**Comment by tigrannajaryan** [comment]
Closing since I don't see other opinions.
