### ISSUE TITLE
Reduce the indirection to create a component

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#1289]
The codebase contains a lot of interfaces, factories, and intermediate helpers such as factory maps. It adds a lot of indirection and unfortunately makes the code very to read, debug and maintain. To give an example,

Exporters component introduces 5 interfaces:
type Exporter
type ExporterCreateParams
type ExporterFactory
type ExporterFactoryBase
type ExporterFactoryOld

The configuration needs the following types:
type Exporter
type ExporterSettings

And another type just to represent a map:
type Exporters map[string]Exporter

These are all the types maintainer need to understand to work on exporters.

I'd like to see if we can reduce the current level of indirection. I'd like to give exporters a try and send a prototype on how we can improve the boilerplate without compromising from flexibility.

**Comment by rakyll** [comment]
Btw, I just realized these interfaces doesn't help you to implement anything yet! You need 3 more (depending on the type of exporter you are implementing) to actually start implementing an exporter. For example, for metrics:

type MetricsExporter
type MetricsExporterBase
type MetricsExporterOld

It's really hard to figure out where to start and the level of interface composition is making it harder to understand what exactly to implement. Especially given how Go developers like obvious and small interfaces, the current number of interfaces add a lot more indirection and confusing the developers.

**Comment by rakyll** [comment]
I just realized there is more. The service/builder package also introduces more types to build exporters. https://pkg.go.dev/go.opentelemetry.io/collector/service/builder/?tab=doc#pkg-index

type Exporters
type ExportersBuilder

These types are also probably adding up to the mental overhead and boilerplate.

**Comment by tigrannajaryan** [comment]
We need to be careful with these changes since they are publicly exported interfaces and changes will break other people's code (custom components). `Old` variations are scheduled to be removed once the transition to new data types is completed (traces are current done, metrics are waiting for opentelemetry-proto to be finalized).

**Comment by bogdandrutu** [comment]
@tigrannajaryan Old and Base (no need for this) will be removed. So it will clean a lot.
