### ISSUE TITLE
receiver/octrace: allow configuring limits in TraceConfig

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#129]
See: https://github.com/census-instrumentation/opencensus-service/issues/173

**Comment by pjanotti** [comment]
Perhaps this should be done as a general "sanitizer processor" so it works for all receivers of a given pipeline while providing standard observability of any trimming that may happen. It has the disadvantage of the receiver itself let the data pass (causing extra work/data that may be trimmed later) but seems a reasonable compromise to get consistent data.

Notice that doing at the service level we lose the possibility of keeping entries in a LRU as client libraries can do, we have to be careful here to not make things confuse for the users, e.g.: why sometimes my span has this attribute and other not...

**Comment by flands** [comment]
Given focus on OTLP, closing this.
