### ISSUE TITLE
Don't export example configs

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#1290]
The collector/config package exports a lot of example types to be used in tests. These types shouldn't be exported to the user-visible packages. See https://pkg.go.dev/go.opentelemetry.io/collector/config/?tab=doc#ExampleExporterConsumer.

**Comment by bogdandrutu** [comment]
We want to use these in some tests, do you recommend renaming? Or just moving them to a different package?

**Comment by rakyll** [comment]
Moving them would be the best, naming them as Test* types would be second option if moving is not possible. I was trying to move them to another package two weeks ago but I hit some hard-to-deal circular import cases. Having said that, I haven't spent too much on it and if moving is possible, that'd be the best.
