### ISSUE TITLE
Migrate Zipkin receiver to the new OTLP-based internal data model

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1303]
**Is your feature request related to a problem? Please describe.**
Zipkin receiver uses old OpenCensus data model which causes unnecessary translation: internal data Zipkin -> OC -> internal data model.

**Describe the solution you'd like**
Zipkin receiver should use OTLP-based internal data model (consumer/pdata/trace.go) instead of OC.

**Comment by dmitryax** [comment]
@kbrockhoff is working this

**Comment by bogdandrutu** [comment]
@kbrockhoff do you mind applying to be a member of the opentelemetry community? https://github.com/open-telemetry/community/blob/master/community-membership.md#member :)

**Comment by kbrockhoff** [comment]
I will do that

**Comment by dmitryax** [comment]
Created a ticket for the part that still uses OC https://github.com/open-telemetry/opentelemetry-collector/issues/1594
