### ISSUE TITLE
Migrate Zipkin exporter to the new OTLP-based internal data model

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1304]
**Is your feature request related to a problem? Please describe.**
Zipkin exporter uses old OpenCensus data model which causes unnecessary translation: internal data model -> OC -> Zipkin.

**Describe the solution you'd like**
Zipkin exporter should use OTLP-based internal data model (consumer/pdata/trace.go) instead of OC.

**Comment by dmitryax** [comment]
@kbrockhoff is working this

**Comment by dmitryax** [comment]
@bogdandrutu @kbrockhoff I see that zipkin receiver still uses OC to translate from Zipkin v1 to OTLP. Do we have plans to have direct Zipkin v1 -> OTLP translation? If not can create another issue to cover that.

**Comment by bogdandrutu** [comment]
Can you please create the issue?
