### ISSUE TITLE
Migrate Probabilistic Sampling Processor to the new OTLP-based internal data model

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1305]
**Is your feature request related to a problem? Please describe.**
Migrate Probabilistic Sampling Processor uses old OpenCensus data model which causes unnecessary translations to OC format.

**Describe the solution you'd like**
Migrate Probabilistic Sampling Processor should use OTLP-based internal data model (consumer/pdata/trace.go) instead of OC.

**Comment by vikrambe** [comment]
@dmitryax i can take this

**Comment by dmitryax** [comment]
@vikrambe thanks!

**Comment by vikrambe** [comment]
@dmitryax sorry, was caught up with other work. I had made changes to use new factory and the helper, i see @bogdandrutu has already made these changes.  I will make some progress in next few days and submit a PR.

**Comment by dmitryax** [comment]
@vikrambe nice! thank you
