### ISSUE TITLE
Processor that waits for a trace to be completed

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#1309]
**Is your feature request related to a problem? Please describe.**
Currently, there's no native way to write processors to act on entire traces, making it hard to take actions based on the whole trace. The tail-based sampling processor has the need for this feature, keeping traces in a map in memory (see references). Any other processor needing to do trace-based decisions would have to implement something similar, which is very ineffective.

References:
https://github.com/open-telemetry/opentelemetry-collector/blob/4dd70256c718aacb8b063fbf752b402133003d1c/processor/samplingprocessor/tailsamplingprocessor/processor.go#L62
https://github.com/open-telemetry/opentelemetry-collector/blob/4dd70256c718aacb8b063fbf752b402133003d1c/processor/samplingprocessor/tailsamplingprocessor/sampling/policy.go#L27-L39

**Describe the solution you'd like**
As discussed in the SIG meeting on 08 July 2020, the idea is to split the waiting logic out of the tail-based sampling processor. This way, the map would be kept in the "waiting" processor and the entire trace is released after N seconds to the next processor. Next processors will then receive complete traces as part of its `pdata.Traces` parameter, so that it can make decisions on it without waiting for new spans to arrive.

Action plan:

1. Create a new `waitfortrace` processor, possibly based on the logic from the tail-based sampling processor
1. Optional: create a new processor that acts on the entire trace, to validate the above
1. In another PR, perhaps for the next version of the collector, change the `tailsamplingprocessor` to follow this new design

This way, the change is applied in a minimally intrusive way, with low-risk to current tail-based sampling processor users.

**Describe alternatives you've considered**
n/a

**Additional context**
1 - Discussed in the SIG meeting from 08 July 2020: https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/view?ts=5de972a2#heading=h.2di13sfliull

**Comment by jpkrohling** [comment]
@objectiser suggested a better name: "group by trace" processor, instead of "wait for trace". This is the name I ended up going with.

**Comment by yue9944882** [comment]
@jpkrohling i think new processor is valuable for tracing [kubernetes operators](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/).. especially for the use-cases where multiple operator reconciles hierarchically.. properly grouping the traces will help visualizing the operators' work-flow
