### ISSUE TITLE
Broken dev image - binary has no execute bit set

### ISSUE THREAD

**Issue by hairyhenderson** [open-telemetry/opentelemetry-collector#1317]
**Describe the bug**

The current `otel/opentelemetry-collector-dev:latest` Docker image seems to not have the `x` bit set on the `/otelcol` binary.

Here's how I discovered that - if I copy the binary out of the container, it lacks the execute bit:

```console
$ docker create --name otc otel/opentelemetry-collector-dev:latest
885e3c7ddd2eea4e66deda0b304b48dced8529c2079a2181bccd18f0c630e20f
$ docker cp -a otc:/otelcol .                                     
$ ls -alh otelcol
-rw-r--r-- 1 hairyhenderson 78M Jul 10 02:09 otelcol
```

**Steps to reproduce**

```console
$ docker pull otel/opentelemetry-collector-dev:latest
latest: Pulling from otel/opentelemetry-collector-dev
801b69c84586: Pull complete 
f25b9210c4d2: Pull complete 
8c0940e8dadd: Pull complete 
Digest: sha256:073991f72fa8907dfe66fd91da09b2c327a30ddcbc5b315b56c5e2a47ef7b0ff
Status: Downloaded newer image for otel/opentelemetry-collector-dev:latest
docker.io/otel/opentelemetry-collector-dev:latest
$ docker run -it --rm otel/opentelemetry-collector-dev:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/otelcol\": permission denied": unknown.
ERRO[0000] error waiting for container: context canceled 
```

**What did you expect to see?**

The `otelcol` binary should run in the container.

**What did you see instead?**

It doesn't 😉

**What version did you use?**

Version: `otel/opentelemetry-collector-dev:latest@sha256:073991f72fa8907dfe66fd91da09b2c327a30ddcbc5b315b56c5e2a47ef7b0ff`

**What config did you use?**

n/a

**Environment**

OS: Docker Desktop 2.3.2.0 on macOS
Compiler(if manually compiled): n/a

**Additional context**

I briefly looked to see if I could find where in this repo the `Dockerfile` for this image is stored, but couldn't find it.

**Comment by bogdandrutu** [comment]
@james-bebbington you were the last to touch the main function :)

**Comment by hairyhenderson** [comment]
This is a bit strange actually - if I run `make docker-otelcol` locally, the image contains an executable binary. The only cause I can think of is if the image was built from a filesystem where the execute bit wasn't preserved. But it seems to be built in CircleCI, in a Linux VM...

**Comment by hairyhenderson** [comment]
I've issued a PR that fixes this in #1321

**Comment by bogdandrutu** [comment]
@hairyhenderson thank you so much

**Comment by hairyhenderson** [comment]
You're very welcome!

**Comment by james-bebbington** [comment]
My best guess is that this somehow broke because we now have a Windows executor sharing a workspace with the Linux VMs and it does something weird with the permissions.

Thanks for the fix! :)

**Comment by hairyhenderson** [comment]
Ah - if Windows is running some of the builds, that totally explains it!
