### ISSUE TITLE
OTLP/HTTP receiver does not support gzip

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1344]
**Describe the bug**
OTLP/HTTP receiver does not support gzip encoding.

**Steps to reproduce**
1. Setup Collector with otlp receiver.
2. Send OTLP/HTTP request with “Content-Encoding: gzip” request header and gzipped content.

**What did you expect to see?**
Request is accepted.

**What did you see instead?**
400 Bad Requdst response.

**What version did you use?**
v0.5.0

**Comment by tannaga** [comment]
Coincidently i was checking for the same thing today.

**Comment by code-haven** [comment]
@tigrannajaryan I would like to work on this issue as it's unassigned.

 I've spent some time trying to debug this. It appears that point of failure is inside [xProtobufMarshaler](https://github.com/open-telemetry/opentelemetry-collector/blob/2ba9cdcc2b3c7f45288c1152b97e9ec64b9d6706/receiver/otlpreceiver/otlp.go#L66) as it's attempting to unmarshal a gzipped payload. 

I don't see an option in grpc-gateway that lets us modify request body before the marshaller is called. I think we could implement a handler/middleware that wraps [gatewayMux](https://github.com/open-telemetry/opentelemetry-collector/blob/a2b2aeddb0ea5ee8493f6768e19551cc7d4371a9/receiver/otlpreceiver/otlp.go#L68) to select a gzip reader based on the `Content-Encoding` header similar to how it's done in [zipkinreceiver](https://github.com/open-telemetry/opentelemetry-collector/blob/c4a38294b0f8cab47f63ed7819cb66199c7c53f8/receiver/zipkinreceiver/trace_receiver.go#L208) but I'm not certain if this is the right approach.

**Comment by mstumpfx** [comment]
Hi @code-haven, I am intending to work on this now unless you have already started the work. Please let me know, thanks.

**Comment by code-haven** [comment]
hey @mstumpfx I was away last week so missed raising the PR. I've done that now. However, I'm relatively new to Go & this project so if the fix is going nowhere, I am happy to hand it over!
