### ISSUE TITLE
Define role to ensure bug reports, PRs, etc. are handled in a timely manner

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1380]
As the project grows we need a process to make sure things don't fall through the cracks. We need to define a role that will:

* Monitor Gitter and respond or delegate for someone to respond
* Assign any unassigned PRs or issues to the appropriate party
* Ensure a release is cut on Tuesday if it is a release week
* Ensure Collector milestone is up-to-date (both adding and removing items)
* Ensure someone runs Collector SIG meeting if SIG meeting week

I will create a PR to add these to the README.

/cc @tigrannajaryan @bogdandrutu @mtwo @flands

**Comment by jrcamp** [comment]
(please assign to me)

**Comment by lizthegrey** [comment]
Related to https://github.com/open-telemetry/community/pull/357
