### ISSUE TITLE
Enhance CONTRIBUTING.md for component type best practices

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1391]
We have https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#coding-guidelines which has some generic advice. We should also formalize best-practices for the various component types (receiver, processors, exporters mainly). Things like "does it use exporterhelper if applicable", does it rely on processors for retry logic and buffering, etc. Ideally we could have code that adheres to all best practices as examples.

**Comment by bogdandrutu** [comment]
@jrcamp maybe a reference to the overall design and best practices and having this in there. The structure is less important than the fact that we lack these rules

**Comment by jrcamp** [comment]
@bogdandrutu sorry I don't follow you

**Comment by huyan0** [comment]
a minor thing of that doc to fix is the reference to opentelemetry-service under "Add your for as an origin"
