### ISSUE TITLE
Decide on Disabled vs Enabled config to control if a component is enabled or not.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#1397]
From a comment in #1386 
> Do we have a enabled/disabled flag already elsewhere in the project? If not, it would be best to have enabled instead of disabled: having something happening on double negatives is confusing to users (disabled: false == enabled)

**Comment by jrcamp** [comment]
I think enabled is the more intuitive one. We had `disabled` in `<ComponentType>Settings` before right? Is there a reason we got rid of it in the first place? The reason it was called disabled before was possibly for a matter of convenience as bool defaults to false in Go and we wanted it to default to enabled I assume.

In terms of implementation if we go with enabled:

One way to default enabled to true would be to use default tags using something like https://github.com/creasty/defaults. I'd like to start using this in a number of components going forward anyway. It would be convenient for this to just be part of general config loading in core but at the same time it's an addition to the API that must be preserved going forward. But it's not a large library in terms of code.

I'm sure there's other ways to implement it that don't require using defaults tags but it is a useful thing to have.
