### ISSUE TITLE
Startup and shutdown should timeout after some period

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1402]
**Is your feature request related to a problem? Please describe.**
During startup or shutdown if a receiver blocks then the startup or shutdown process hangs indefinitely. See https://github.com/open-telemetry/opentelemetry-collector/issues/1192 for history.

**Describe the solution you'd like**
Startup or shutdown should timeout after a configured period in the service section. Not sure what the default should be. 30s?

**Describe alternatives you've considered**
Letting orchestrator kill process if graceful shutdown doesn't happen.

**Comment by bogdandrutu** [comment]
Would go with a default of 1 minute
