### ISSUE TITLE
observability: consistent naming for metrics produced by OTel service

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#141]
Before first release we should make the name of metrics generated consistent, currently these are not consistent through the code base.

**Comment by ledor473** [comment]
Would that include changing the namespace used for the metrics? 
https://github.com/open-telemetry/opentelemetry-collector/blob/7a6e5f1955139a3c99ca37746e9ce17aa642fcc9/service/telemetry.go#L86-L88

Currently we get the following metric:
```
oc_collector_otelcol_receiver_received_spans
oc_collector_otelcol_exporter_received_spans
...
```

**Comment by pjanotti** [comment]
Yes, @ledor473 at least making it configurable: there is the case to keep the old one for people that have alerts/dashboards based on `oc_collector` but it makes sense to update the namespace.

**Comment by bogdandrutu** [comment]
I think this is covered by the transition to the new obsreport package.
