### ISSUE TITLE
Attribute processor cannot be programmatically configued 

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1411]
**Describe the bug**

Attribute processor cannot be programmatically configured because the `attraction.Settings` is in a private package `"go.opentelemetry.io/collector/internal/processor/attraction"`

It was done in https://github.com/open-telemetry/opentelemetry-collector/pull/1322/files#diff-1ffa1fe6fd27ddd9fe65f23171080144R19 cc) @bogdandrutu 

**Steps to reproduce**

Programmatically configure the attribute processor.

**What did you expect to see?**

Be able to programmatically configure the attribute processor.

**What did you see instead?**

The config object of the attribute processor is composed of structs from private packages.

**What version did you use?**

master/HEAD

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by bogdandrutu** [comment]
Can you provide some motivation?

**Comment by pavolloffay** [comment]
In Jaeger we are injecting properties from variable to the config.
