### ISSUE TITLE
Consider adding telemetry level to CreateParams structs or component config

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1413]
**Is your feature request related to a problem? Please describe.**

Created from https://github.com/open-telemetry/opentelemetry-collector/pull/1270#discussion_r458823422

Components (receivers, processors, exporters) can report additional metrics. Calculation of these metrics can have a performance impact hence the component should have access to the telemetry level `--metrics-level` to enable these metrics only when appropriate.

**Describe the solution you'd like**

Add telemetry level to create params struct or add it to component config. The second option would enable us telemetry level per individual component. 

**Describe alternatives you've considered**
Get the level from global accessor `level,  error := telemetry.GetLevel()`

**Additional context**
None

**Comment by bogdandrutu** [comment]
Already in `component.TelemetrySettings`
