### ISSUE TITLE
Add binary size check to PR

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1415]
As new dependencies are added (or even existing ones reved that may then bring in new transitive dependencies) binary sizes can creep up. It'd be nice to have better visibility into this at review/PR time. At a minimum we would want to see what the delta is between the PR and its merge base. If we don't have size data for merge base then maybe fall back to master. I think this would require saving this data (in CircleCI?) as part of the build so it could be fetched later to compute the delta.

See https://github.com/jondot/goweight for a tool that can break down the size per package as well.

I thought there was a github bot similar to codecov that did this but I couldn't find it so may be worth doing some more research to see if there's a prepackaged solution.

This should be added to both core and contrib.

**Comment by jchengsfx** [comment]
We should be able to use circleci caching for saving the deltas across builds.

Would we fail the build if the delta crosses some threshold in order to notify the submitter?

**Comment by jrcamp** [comment]
I think we should just provide the info to the reviewer to make a judgement call on for now. Once we see what typical values are maybe we can add an enforcement mechanism.

**Comment by jrcamp** [comment]
btw I was thinking at least for the first pass if all we have is change in binary size we probably don't need a full comment like codecov but the text in the check should be sufficient:

<img width="927" alt="Screen Shot 2020-07-22 at 3 38 53 PM" src="https://user-images.githubusercontent.com/156260/88220953-baf05d80-cc31-11ea-9acc-b760c8744c99.png">

Maybe for a second phase adding diff of goweight of base vs PR could be useful. (Assuming there isn't a turnkey solution elsewhere.)
