### ISSUE TITLE
checksum mismatch for v0.6.0

### ISSUE THREAD

**Issue by chenqi0805** [open-telemetry/opentelemetry-collector#1418]
**Describe the bug**
go: downloading go.opentelemetry.io/collector v0.6.0
go get: go.opentelemetry.io/collector@v0.6.0: verifying module: checksum mismatch
        downloaded: h1:j7TJX0CMNfGDu2zx9ohmw8li/G6ZZYX/kEpA2B0A5fg=
        sum.golang.org: h1:ade+H/U3+m+Bf234cap10+rnBV4x7RMNLFl4/1jI0Io=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

go get -u go.opentelemetry.io/collector@v0.6.0

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by jrcamp** [comment]
@owais do you know if the v0.6.0 tag got force pushed that would cause checksums to fail?

**Comment by bogdandrutu** [comment]
@owais did a "retag" I think, which is not allowed by golang :(

**Comment by owais** [comment]
I deleted the tag from github but then tagged the exact same commit thinking that was fine. May be I made a mistake and amended the commit before re-tagging it. We can release `0.6.1` to fix this. I'm not back till Monday. I can make the release then or someone else can do it before then.

**Comment by bogdandrutu** [comment]
Pushed tag v0.6.1, this should be resolved now. CI is building the docker image and soon golang will pick this.
