### ISSUE TITLE
Vendor in queue implementation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector#1429]
I was looking at the queue processor and was surprised to see it depend on a jaeger package

https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/queuedprocessor/queued_processor.go#L24

While the readme for `jaeger/pkg` indicates it's not tied to internals

https://github.com/jaegertracing/jaeger/tree/master/pkg

it still seems like these are utilities meant for use by the jaeger binary, not utilities exported for other codebases. Does it make sense to copy this package in?

**Comment by bogdandrutu** [comment]
Fixed. Copied the code.
