### ISSUE TITLE
Receiver notification of message processing status

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector#1432]
Looking at the [current interface](https://github.com/open-telemetry/opentelemetry-collector/blob/master/component/receiver.go), the receiver cannot find out whether the received message was successfully processed.
However, this capability is critical for some receivers.
For example, receivers from message queues should only acknowledge messages (or commit offset) if the messages processed successfully. This will make the collector more reliable. And also this is the only way to make a persistent queue (queued retry is in memory and it loses data when collector crashes).

I propose to consider options for providing hooks or a notification channel.

**Comment by bogdandrutu** [comment]
@morigs the receiver is constructed with a "nextConsumer" (https://github.com/open-telemetry/opentelemetry-collector/blob/master/consumer/consumer.go). 

You call `Consume` on the consumer from the receiver which should return nil if the pipeline consumed the message or an error otherwise.

Not sure I understand the problem.

**Comment by morigs** [comment]
But what if the message was dropped after several unsuccessful attempts in queued retry? I think `Consume` will return `nil`

**Comment by bogdandrutu** [comment]
If that is the case, what about you don't configure the queue part, only the retry so you do the requests synchronous

**Comment by morigs** [comment]
OK, that doesn't sound very intuitive, but real)
thx

**Comment by bogdandrutu** [comment]
You are correct, I just try to not complicate for the moment the overall design if unnecessary and same thing can be achieved. Thanks for understanding
