### ISSUE TITLE
LoggingExporter does not print span events

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector#1454]
LoggingExporter currently does not log events nor links. There is even a todo [in the source ](https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/loggingexporter/logging_exporter.go#L301):

>TODO: Add logging for the rest of the span properties: events, links.

**Comment by bogdandrutu** [comment]
@iNikem great opportunity to code some golang :)
