### ISSUE TITLE
cert_pem_file in jaeger exporter error

### ISSUE THREAD

**Issue by snypez** [open-telemetry/opentelemetry-collector#1459]
**Describe the bug**
Specify a cert_pem_file for client auth in the jaeger exporter causes the process to fail to start with the error 
Error: cannot load configuration: error reading settings for exporter type "jaeger": 1 error(s) decoding:

* '' has invalid keys: cert_pem_file
2020/07/29 19:02:57 application run finished with error: %v: cannot load configuration: error reading settings for exporter type "jaeger": 1 error(s) decoding:

* '' has invalid keys: cert_pem_file
**Steps to reproduce**
start the process with cert_pem_file in the jaeger exporter config

**What did you expect to see?**
A clear and concise description of what you expected to see.
the process start and use the specified client cert for tls auth.
**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
0.6.1
**What config did you use?**
Config: (e.g. the yaml config file)
exporters:
  jaeger:
    cert_pem_file: /my-cert.pem
**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
docker container
**Additional context**

**Comment by bogdandrutu** [comment]
Short answer is that the `cert_pem_file` in your config is not the actual parameter to use. You need to use `ca_file` or `cert_file` or `key_file`. See https://github.com/open-telemetry/opentelemetry-collector/blob/master/config/configtls/configtls.go#L28

Will do a fix for the error to be clear. Also need a fix for jaeger documentation.
