### ISSUE TITLE
Docs for grpc receivers/exporters about insecure

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector#1479]
All grpc-related components (otlp, jaeger) docs says that certificates are required when `insecure` is true. It doesn't make sense. If transport security is disabled why we need certificates? For example: https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/jaegerexporter/README.md

> insecure (default = false): whether to enable client transport security for the exporter's gRPC connection. See grpc.WithInsecure().
ca_file path to the CA cert. For a client this verifies the server certificate. S**hould only be used if insecure is set to true.**
cert_file path to the TLS cert to use for TLS required connections. **Should only be used if insecure is set to true.**
key_file path to the TLS key to use for TLS required connections. **Should only be used if insecure is set to true.**

**Comment by flands** [comment]
If I recall correctly the parameter used to be called `secure`, but was then changed to `insecure`. Docs were likely not updated at the same time. I will take this.
