### ISSUE TITLE
Create library for Subprocess Management

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#1492]
We currently have two implementations of Subprocess Management:

1. https://github.com/open-telemetry/opentelemetry-collector/tree/master/extension/fluentbitextension
2. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/prometheusexecreceiver/subprocessmanager

We should understand the different requirements for these components and extract the shared logic for process management into a separate package. This package would need to:

- Manage process restarts (configurable)
- Ability to write to stdin
- Ability to capture stdout
- Hook to allow cmd to be arbitrarily changed on process restarts

It will also be useful to consolidate sub process management logic into a single package to consolidate any related [security concerns](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/453#issuecomment-663076098).

**Comment by bogdandrutu** [comment]
This can be marked as done in core, if still needed will reopen in contrib
