### ISSUE TITLE
Tail Sampling Processor emits trace data multiple times

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-collector#1514]
**Describe the bug**
When using multiple sampling policies with the tailsamplingprocessor, if multiple policies decide to sample the trace data is emitted multiple times (multiple calls to `tsp.nextConsumer.ConsumeTraceData`)

**Steps to reproduce**
Example config
```
receivers:
  zipkin:
    endpoint: "0.0.0.0:8080"

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  tail_sampling:
    decision_wait: 5s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
          {
            name: error-policy,
            type: string_attribute,
            string_attribute: {key: error, values: [SomeError]}
          },
          {
            name: rate-limit-policy,
            type: rate_limiting,
            rate_limiting: {spans_per_second: 35}
         }
      ]

service:
  pipelines:
     traces/to_log:
       receivers: [zipkin]
       processors: [tail_sampling]
       exporters: [logging]
```

Send a single span to the collector 
example
```
[
  {
    "name": "get",
    "traceId": "4d1e00c0db9010dc",
    "id": "4d1e00c0db9010d",
    "kind": "CLIENT",
    "timestamp": 1502787600000000,
    "duration": 207000,
    "localEndpoint": {
      "serviceName": "frontend",
      "ipv6": "7::0.128.128.127"
    },
    "remoteEndpoint": {
      "serviceName": "backend",
      "ipv4": "192.168.99.101",
      "port": 9000
    },
    "tags": {
      "http.path": "/api",
      "http.status_code": "500",
      "error": "SomeError"
    }
  }
]
```

**What did you expect to see?**
The span should be printed once by the logging exporter

**What did you see instead?**
The span is logged twice

**What version did you use?**
`81e3c64c302b61e065a583e0090ce062fdb6cf4b`

The bug occurs because the call to `nextConsumer.ConsumeTraceData` is called from within the Policy for loop
https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/samplingprocessor/tailsamplingprocessor/processor.go#L181-L183

I believe all policies should be evaluated, and if any return `Sampled` then the trace should be sampled once. If this approach is good I can submit a pr.

**Comment by chris-smith-zocdoc** [comment]
@tigrannajaryan Is my proposed fix ok? If so I'll submit a pr for this

**Comment by tigrannajaryan** [comment]
@chris-smith-zocdoc yes, your proposal sounds correct.

**Comment by chris-smith-zocdoc** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/1735
