### ISSUE TITLE
internal: Unify internal/collector/telemetry and receiver/vmmetrics.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#154]
Currently all of the metrics collected by [internal/collector/telemetry](https://github.com/open-telemetry/opentelemetry-service/tree/6566e78b4bb8e0cceec21abec91731611e3ca31a/internal/collector/telemetry) are covered by [VM metrics receiver](https://github.com/open-telemetry/opentelemetry-service/tree/6566e78b4bb8e0cceec21abec91731611e3ca31a/receiver/vmmetricsreceiver). It should be consolidated into VM metrics receiver.

This is blocked by Collector support on Metrics pipeline.

**Comment by tigrannajaryan** [comment]
>This is blocked by Collector support on Metrics pipeline.

The OpenTelemetry service already supports Metrics pipeline. Is there anything particular that blocks this?

**Comment by songy23** [comment]
That's correct - just found the internal telemetry is using a different metrics pipeline (`ViewData` -> Prometheus exporter): https://github.com/open-telemetry/opentelemetry-service/blob/4c7c3ca57110c32803b56cec3fe4733afd74c952/service/telemetry.go#L82-L101. That part needs to be updated as well.

**Comment by bogdandrutu** [comment]
vmmetrics is removed. we need to cleanup the internal/collector/telemetry as a separate bug
