### ISSUE TITLE
Access application version in components

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#1559]
**Is your feature request related to a problem? Please describe.**
I would like to include the application version in metadata on requests sent by an exporter.

**Describe the solution you'd like**
Add the version string to the parameters passed to components on initialization, i.e. update https://github.com/open-telemetry/opentelemetry-collector/blob/v0.8.0/component/exporter.go#L97 (similar for other components)

When building the pipelines, set this value based on the value provided in https://github.com/open-telemetry/opentelemetry-collector/blob/v0.8.0/service/service.go#L109

**Comment by nilebox** [comment]
While version is the immediate use case that needs this feature, it may make more sense to support a generic way of passing the pipeline-level metadata.

e.g. if in the exporter we want to distinguish the "distro" it's being used in (`opentelemetry-collector`, `opentelemetry-collector-contrib`, or some vendor-specific binary like [GoogleCloudPlatform/opentelemetry-operations-collector](https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector)), we may declare a struct like

```go
type ApplicationInfo interface {
  Name() string    // e.g. "opentelemetry-collector"
  Version() string // e.g. "v0.10.0"
}
```

and pass it to all component constructors.

**Comment by james-bebbington** [comment]
> we may declare a struct ... and pass it to all component constructors.

True, maybe we could just pass in the ApplicationStartInfo struct directly: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.8.0/service/service.go#L101

**Comment by andrewhsu** [comment]
Closing this as done because PR #1582 was merged
