### ISSUE TITLE
MetricPoint or MetricDataPoint

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#1575]
From https://github.com/open-telemetry/opentelemetry-collector/pull/1571#discussion_r471807141 we need to make a decision on this.

**Comment by tigrannajaryan** [comment]
Needed for GA since this is a public/exported name.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I vote for not changing anything and suggest to close this as "won't do". Objections?

**Comment by bogdandrutu** [comment]
Keeping what we have.
