### ISSUE TITLE
Reload TLS certificates

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1591]
**Is your feature request related to a problem? Please describe.**

I would like to renew certificates without shutting down OTEL service.

**Describe the solution you'd like**

Watch for filesystem changes and load certificates if they change.

**Describe alternatives you've considered**

Restart the service if certs have to be changed.

**Additional context**

A similar feature is being done in https://github.com/jaegertracing/jaeger/pull/2389

**Comment by tigrannajaryan** [comment]
This perhaps can be done as part of config hot-reload feature.

**Comment by pavolloffay** [comment]
Do you have any pointer to issue/PR? 

Note that the certs names might not change only the content of the files.

**Comment by fujin** [comment]
Would very much love this feature! I am using cert-manager to provision certificates (via Kubernetes Secret) to my OpenTelemetry Collectors for the oltp receiver. We fortunately have an HPA on the deployment so pods are replaced frequently such that a certificate renewal is likely to be picked up.

**Comment by bogdandrutu** [comment]
This is done by #4737
