### ISSUE TITLE
Zipkin receiver should translate Zipkin v1 directly to OTLP-based internal data model

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1594]
**Is your feature request related to a problem? Please describe.**
Zipkin receiver uses old OpenCensus data model to translate from Zipkin v1 to OTLP. It affects receiver performance.

**Describe the solution you'd like**
Zipkin receiver should translate Zipkin v1 format directly to the OTLP-based internal data model and don't use OC.

**Comment by andrewhsu** [comment]
Closing this as done because PR #1446 was merged
