### ISSUE TITLE
TLS client config unification

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1602]
We still have the open issue of how to specify TLS is enabled in the case where tls_settings are not needed (ie you just want default TLS config). This is a followup to #933.

Do you do:

```yaml
endpoint: https://localhost:1234
```

```yaml
endpoint: unix+tls:///var/run/sock
```

I think we (@bogdandrutu and @ccaraman) started discussing it but couldn't come to a conclusion.

**Comment by andrewhsu** [comment]
from the collector sig mtg today, closing it because this is resolved (done)

**Comment by jrcamp** [comment]
Relevant part of HTTPClientSettings:

```go
type HTTPClientSettings struct {
	// The target URL to send data to (e.g.: http://some.url:9411/v1/traces).
	Endpoint string `mapstructure:"endpoint"`

	// TLSSetting struct exposes TLS client configuration.
	TLSSetting configtls.TLSClientSetting `mapstructure:",squash"`
}
```

I think this is solved for HTTP clients (https has to be included as part of the endpoint). May need to figure out something else for unix sockets later but can deal with it when the need arises. @bogdandrutu do you remember these discussions? Anything else to add for this ticket?
