### ISSUE TITLE
Extract user's browser/device/platform information from user agent

### ISSUE THREAD

**Issue by tannaga** [open-telemetry/opentelemetry-collector#1606]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need browser/device/platform information from useragent.  useragent field is available as a tag inside span
For ex: a user-agent value of `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36` is parsed to get below values

```
deviceType: mac
browser: chrome 84
platformOS; macOS (Catalina)
```

**Describe the solution you'd like**
A processor which can parse the user-agent (configurable) field and add them as additional tags will be great. Somewhat similar to attributes processor but with the flexibility to add instrumentation details on how to extract data.

I am willing to work on this and contribute back. 
Please let me know if this makes sense and should be part of the opentelemetry-collector repo.

**Comment by bogdandrutu** [comment]
@tannaga This seems like "extract" action in https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor/attributesprocessor

**Comment by tannaga** [comment]
Yes it is very much like extract function but the main difference is that it cannot be achieved with a single regex. 
Different user agents have different formats and the regex that is needed will change accordingly.  
In ua-parser github  all the possible user agents are maintained in a [regex format](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) and different languages use that as input file to extract info like device type, browser, os, etc.
That is why I believe we may need a new processor to perform this extraction logic.
