### ISSUE TITLE
Enable OC span translation to handle `span.kind` attribute with `client` and `server` values

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-collector#1608]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/envoyproxy/envoy/issues/12538
We want to set the span kind within the Envoy OC tracer. Problem is that the OC C++ impl doesn't support SpanKind.

**Describe the solution you'd like**
Currently the OC span translation code handles `span.kind` attribute for values `producer`, `consumer` and `internal` - with `client` and `server` being handled via the span kind field on the Span. Proposal would be to extend the [switch statement](https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/internaldata/oc_to_traces.go#L249-L258) to enable `client` and `server` span kinds to also be handled in the `span.kind` attribute.

**Describe alternatives you've considered**
Implement the span kind field in the OC cpp impl.

**Additional context**

**Comment by tigrannajaryan** [comment]
@objectiser it is not entirely clear why the fix for this needs to be in the Collector. If I understand the description correctly it appears that the problem is that  does not fully support all span kinds that it is supposed to support. If that's the case it seems the right approach to fix OpenCensus C++ implementation.

**Comment by objectiser** [comment]
@tigrannajaryan Yes, one approach would be to add support in the OpenCensus C++ implementation. However as the OpenTelemetry collector has already set the precedent of supporting receiving span kind info (producer and consumer values) via an attribute, this seemed the most expedient approach - and adds flexibility to the OC receiver in the collector to be able to support client/server span kind either via the field or attribute.
