### ISSUE TITLE
Default Metric Labels

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector#1624]
[Documentation ](https://opentelemetry.io/docs/collector/about/#agent) says
> It is recommended to deploy the Agent on every host within an environment. In doing so, the Agent is capable of adding metadata to observability data it receives or collects.

But I can't figure out what kind of metadata it adds.
I need all metrics to contain a label with the hostname. It seems the agent could add it (similar to as prometheus does with job/instance)

**Comment by tigrannajaryan** [comment]
To add data to all telemetry see for example these processors:
- https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/resourceprocessor 
- https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
