### ISSUE TITLE
Add logs support to resource processor

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1650]
This is part of OpenTelemetry Logs roadmap: https://github.com/open-telemetry/oteps/blob/master/text/logs/0130-logs-1.0ga-definition.md

**Comment by pmm-sumo** [comment]
I can help with that one and if this would go well, could copy the approach to other processors (I believe it should be simple piece of code most of the time)

**Comment by tigrannajaryan** [comment]
@pmm-sumo sounds good, assigning to you.
