### ISSUE TITLE
Add logs support to batch processor

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1651]
This is part of OpenTelemetry Logs roadmap: https://github.com/open-telemetry/oteps/blob/master/text/logs/0130-logs-1.0ga-definition.md

**Comment by keitwb** [comment]
See #1723

**Comment by tigrannajaryan** [comment]
Fixed via https://github.com/open-telemetry/opentelemetry-collector/pull/1723
