### ISSUE TITLE
Add perf test for OTLP logs

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1655]
Add performance test to testbed, with OTLP in -> OTLP out logs.

**Comment by chamilad** [comment]
I can contribute to this task. Would like a direction and a point to start with.

**Comment by tigrannajaryan** [comment]
@chamilad great, thank you for helping.

There is currently one log performance tests implemented here https://github.com/open-telemetry/opentelemetry-collector/blob/master/testbed/tests/log_test.go

We would like to have more scenarios covered, e.g. sending/receiving using OTLP protocol instead of Fluent forward protocol. This will require adding OTLP logs sender to the testbed (we currently have OTLPTraceDataSender and  OTLPMetricsDataSender in senders.go, but there is no equivalent for logs - should be straightforward to add).

**Comment by tigrannajaryan** [comment]
@chamilad if you have yet have a chance please read the contributing guide: https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md particuarly around structuring PRs and recommendations for PR sizes.

**Comment by chamilad** [comment]
Thanks @tigrannajaryan ! I'll have a look around.

**Comment by chamilad** [comment]
@tigrannajaryan Sorry about the delayed response. But I couldn't attend to this. It looks like the load tests for OTLP has been added by commits ec36a15e and 3f967434.

**Comment by tigrannajaryan** [comment]
Done.
