### ISSUE TITLE
Change Prometheus remote write exporter to use the new internal metrics structs

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#1681]

**Comment by huyan0** [comment]
Thanks for updating the OTLP. Can I do this in the histogram PR? #1643

**Comment by huyan0** [comment]
Hi @bogdandrutu, Should I convert from data.MetricsData or convert from the underlying v0.5 OTLP data? I remember you saying that more change will happen to this current version of OTLP on Thursday, and using data.MetricsData would hide those changes from the exporter. Is this correct?

**Comment by bogdandrutu** [comment]
You should change from using dataold.MetricData to use `data.MetricData`

**Comment by bogdandrutu** [comment]
You should change to use:
`dataold.MetricsData` -> `data.MetricsData`
`pdatautil.*OldInternal*` -> `pdatautil.*Internal*`
`testdataold` -> `testdata` (prefix was changed `GenerateMetricData` -> `GenerateMetrics`)

**Comment by huyan0** [comment]
> You should change to use:
> `dataold.MetricsData` -> `data.MetricsData`
> `pdatautil.*OldInternal*` -> `pdatautil.*Internal*`
> `testdataold` -> `testdata` (prefix was changed `GenerateMetricData` -> `GenerateMetrics`)

Okay, sounds good. Thanks.

**Comment by bogdandrutu** [comment]
Don't know why this issue got closed probably I pressed random buttons :))

**Comment by bogdandrutu** [comment]
@huyan0 are you working on this?

**Comment by huyan0** [comment]
> @huyan0 are you working on this?

Yeah I have the code. will file a PR today
