### ISSUE TITLE
Discussion: consider moving away from config functional pattern

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#172]
I'm seeing this from #167, the functional pattern for OC receiver is a bit verbose and it seems we can achieve the same effects using a config struct with good defaults, i.e.: code just touches what it is special for its configuration. Ideally we would come to an agreement and use only a single model in the core code base of OTelSvc. This anyway becomes prescriptive to others implementers in the contrib repo.

**Comment by tigrannajaryan** [comment]
@pjanotti can you clarify what pattern is that does not look good?

**Comment by pjanotti** [comment]
(Linked description to the wrong PR), here it is: https://github.com/open-telemetry/opentelemetry-service/blob/e0a5e9b276453481f9e28682a6e13fc32ed44e66/receiver/opencensusreceiver/options.go#L63-L77

It at least can be made less verbose with something like: https://github.com/open-telemetry/opentelemetry-service/blob/e0a5e9b276453481f9e28682a6e13fc32ed44e66/receiver/opencensusreceiver/octrace/options.go#L20-L28

But perhaps we should switch to simply pass a config struct and properly set the values internally.

**Comment by tigrannajaryan** [comment]
>But perhaps we should switch to simply pass a config struct and properly set the values internally, or have them set directly in the struct itself.

I agree. I think the functional pattern unnecessarily complicates it.

**Comment by bogdandrutu** [comment]
This is done for all the components except OpenCensus which still has Options, but only between factory and receiver.
