### ISSUE TITLE
Consider adding OpenTelemetry [Metrics] Exporter

### ISSUE THREAD

**Issue by sargun** [open-telemetry/opentelemetry-collector#1727]
**Is your feature request related to a problem? Please describe.**
We would like to be able to chain OpenTelemetry components and send metrics from the opentelemetry collector to other systems that have opentelemetry compatibility.

**Describe the solution you'd like**
A exporter which can export to either the protobuf / JSON over HTTP or GRPC Opentelemetry collector endpoint as described in (https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/collector/metrics/v1/metrics_service.proto). 

**Describe alternatives you've considered**
We can either fork OT Contrib and add a custom exporter that exports to our internal system, or read from the file based exporter. The Prometheus exporter just adds another layer of indirection. The closest thing to this we have right now is the [opencensus exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/opencensusexporter), which basically does everything that the Opentelemetry protocol does, but not quite.

**Additional context**
We have an internal metrics system which probably doesn't make sense to add to contrib. We would like to be able to use collector and have it send metrics to our internal system. We can (relatively) easily implement the OpenTelemetry Metrics endpoint, or alternatively, build a custom exporter for opentelemetry collector. 

What we would then do is something like this:

```
                           ┌−−−−−−−−−−−−−−−−−−−−−−−−−−−┐
                           ╎        generators         ╎
                           ╎                           ╎
                           ╎ ┌───────────────────────┐ ╎
                           ╎ │        Kubelet        │ ╎
                           ╎ └───────────────────────┘ ╎
                           ╎                           ╎
                           └−−−−−−−−−−−−−−−−−−−−−−−−−−−┘
                               │
                               │ kubeletstatsreceiver
                               │
┌−−−−−−−−−−−−−−┐               │                                       ┌−−−−−−−−−−−−−┐
╎              ╎               │                                       ╎             ╎
╎              ╎               ▼                                       ╎             ╎
╎ ┌──────────┐ ╎             ┌───────────────────────┐                 ╎ ┌─────────┐ ╎
╎ │          │ ╎             │     Opentelemetry     │                 ╎ │         │ ╎
╎ │ Node App │ ╎  statsd     │   Contrib Collector   │    prometheus   ╎ │ Systemd │ ╎
╎ │          │ ╎ ────────▶   │    otelcontribcol     │   ◀──────────── ╎ │         │ ╎
╎ └──────────┘ ╎             └───────────────────────┘                 ╎ └─────────┘ ╎
╎              ╎                                                       ╎             ╎
└−−−−−−−−−−−−−−┘                                                       └−−−−−−−−−−−−−┘
                               │
                               │ OT grpc
                               ▼
                             ┌───────────────────────┐
                             │     Opentelemetry     │
                             │   Custom Collector    │
                             └───────────────────────┘
                               │
                               │ Custom exporter
                               ▼
                             ┌───────────────────────┐
                             │      Propietary       │
                             │    Global Metrics     │
                             │        System         │
                             └───────────────────────┘
```

This way we wouldn't have to do a bunch of messy go forking / mod hackery.

**Comment by bogdandrutu** [comment]
This is already supported (using gRPC) unless I am missing something

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/otlpexporter

**Comment by sargun** [comment]
@bogdandrutu Would HTTP (either protobuf or JSON) be considered to be added?

**Comment by bogdandrutu** [comment]
Yes, see #1719 where someone else asks for the same thing.

**Comment by sargun** [comment]
Linking the actual bug: https://github.com/open-telemetry/opentelemetry-collector/issues/882
