### ISSUE TITLE
IsNil in pdata causes panic: nil pointer dereference

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1731]
**Describe the bug**

`IsNil` methods from `pdata` package cause `panic: nil pointer dereference`.

**Steps to reproduce**

```golang
func TestNil(t *testing.T) {
	rs := pdata.Resource{}
	assert.Equal(t, true, rs.IsNil())
}
```

**What did you expect to see?**

Not panic either `false` or `true`.

**What did you see instead?**

panic

**What version did you use?**

**What config did you use?**

**Environment**

**Additional context**

cc @tigrannajaryan

**Comment by pavolloffay** [comment]
The method logic should be for instance

```
func (ms Resource) IsNil() bool {
	if ms.orig == nil {
		return true
	}
	return *ms.orig == nil
}
```

**Comment by tigrannajaryan** [comment]
>rs := pdata.Resource{}

This is not a valid usage as it is described in the comments for pdata.Resource:

```go
// Must use NewResource function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Resource struct {
```

**Comment by pavolloffay** [comment]
> This is not a valid usage as it is described in the comments for pdata.Resource:

How does the consumer of the resource/pdata structs know that the struct is zero initialized? There should be an API to check for that.
