### ISSUE TITLE
Return consumererror.Permanent in the Prometheus remote write exporter

### ISSUE THREAD

**Issue by huyan0** [open-telemetry/opentelemetry-collector#1733]
The Prometheus remote write exporter right now returns vanilla Go errors. This breaks the retry mechanism in the Collector. If a batch contains a metric with invalid temporailty or it gets a 400 response code from the backend, the collector will exponentially backoff and retry, getting the same error  every time.  

If the Prometheus remote write returns error of `consumererror.Permanent` type, the retry mechanism will not be triggered

cc: @bogdandrutu @alolita @huyan0

**Comment by amanbrar1999** [comment]
I will pick up this issue 

-cc @alolita @bogdandrutu @jmacd @tigrannajaryan

**Comment by amanbrar1999** [comment]
This issue should be resolved from my latest PR

**Comment by andrewhsu** [comment]
from the issue triage session at the collector sig, looks like this is done so closing
