### ISSUE TITLE
Testbed expects all receivers to listen on a port

### ISSUE THREAD

**Issue by camdencheek** [open-telemetry/opentelemetry-collector#1802]
I'm working on adding support in the testbed for a [stanza](https://github.com/observIQ/stanza) receiver. I'm running into an issue where the testbed expects all receivers to be [listening on a port](https://github.com/open-telemetry/opentelemetry-collector/blob/bf44da52e8e8acddd34cf754fa88dd6aaa73f240/testbed/testbed/test_case.go#L195-L199), and runs a liveness test against the subprocess to ensure that it's ready. 

The stanza log receiver, unlike the Fluent Bit receiver, is embedded in the collector and reads logs from files, so there is no need to open a listening port. I'm currently working around this by simply [starting a listener](https://github.com/observIQ/opentelemetry-collector-contrib/blob/4db01f28f87f583fd984f0529c9ded1089076612/testbed/tests/log_test.go#L32) at the beginning of the test so that that wait condition passes, but this is a little bit hacky, and if we want to expand the stanza testbed tests, it would be great to have a better alternative. 

One idea might be to replace a port check with the more generic [health check](https://github.com/open-telemetry/opentelemetry-collector/blob/caadbbc476cc13ba87503b8ae7a1a8a50d5b22c4/extension/healthcheckextension/README.md). Does a passing health check guarantee that the receivers have been started?

**Comment by bogdandrutu** [comment]
@pmcollins I think you solved something like this for Prometheus

**Comment by pmcollins** [comment]
I did add support for pull-based protocols (e.g. Prometheus) to metrics correctness, but not anything relating to a port check.

**Comment by camdencheek** [comment]
It looks to me like the correctness tests do everything with the in-process collector, so there is no need to wait for the port

**Comment by bogdandrutu** [comment]
I think this fixes the issue https://github.com/open-telemetry/opentelemetry-collector/pull/2035, feel free to re-open if that is not the case
