### ISSUE TITLE
Prometheus receiver observability metrics

### ISSUE THREAD

**Issue by djjayeeta** [open-telemetry/opentelemetry-collector#1814]
The PR https://github.com/open-telemetry/opentelemetry-collector/pull/327 says that prometheus receiver has some metrics exposed to get statistics about the receiver. I am not able to find how to access those metrics, I tried port 8888 but they seem to have
```
Metric #0
Descriptor:
     -> Name: otelcol_exporter_send_failed_metric_points
     -> Description: Number of metric points in failed attempts to send to destination.
Metric #1
Descriptor:
     -> Name: otelcol_exporter_sent_metric_points
     -> Description: Number of metric points successfully sent to destination.
Metric #2
Descriptor:
     -> Name: otelcol_process_cpu_seconds
     -> Description: Total CPU user and system time in seconds
Metric #3
Descriptor:
     -> Name: otelcol_process_runtime_heap_alloc_bytes
     -> Description: Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')
Metric #4
Descriptor:
     -> Name: otelcol_process_runtime_total_alloc_bytes
     -> Description: Cumulative bytes allocated for heap objects (see 'go doc runtime.MemStats.TotalAlloc')
Metric #5
Descriptor:
     -> Name: otelcol_process_runtime_total_sys_memory_bytes
     -> Description: Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')
Metric #6
Descriptor:
     -> Name: otelcol_receiver_accepted_metric_points
     -> Description: Number of metric points successfully pushed into the pipeline.
Metric #7
Descriptor:
     -> Name: otelcol_receiver_refused_metric_points
     -> Description: Number of metric points that could not be pushed into the pipeline.
```

I am particularly interested in the up metric. Can someone please help me out

**Comment by djjayeeta** [comment]
Can anyone point to me to a slack/google group(if there exists one) to ask for configuration related help

**Comment by jmacd** [comment]
@djjayeeta I am also interested in this question. I don't know the answer, but I'm looking for people to help make OTel collectors observable.  We expect to be able to direct an OTLP stream of spans, metrics, and logs describing the collector itself to an endpoint for observing collectors that are part of an observability infrastructure.

**Comment by jmacd** [comment]
@djjayeeta You may want to ask in https://gitter.im/open-telemetry/opentelemetry-service

**Comment by alolita** [comment]
Stale issue - hence closed.

**Comment by mfilipe** [comment]
@djjayeeta did you find a solution?
