### ISSUE TITLE
Support single Zipkin thrift span in kafka receiver

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1815]
**Is your feature request related to a problem? Please describe.**

Legacy Zipkin deployments support single Zipkin thrift span per message https://github.com/openzipkin/zipkin/blob/master/zipkin-collector/kafka/README.md#legacy-encoding.

Gitter message from @mrajah-twttr
```
we are trying to use OTELCO to read zipkin thrift from kafka and running into errors like below when unmarshalling.. any ides on how to go about debugging this? where is the thrift type defined (may be the thirft type is out of sync with what we have) {"level":"error"
"ts":1600291094.6969838
"caller":"kafkareceiver/kafka_receiver.go:170"
"msg":"failed to unmarshall message"
"component_kind":"receiver"
"component_type":"kafka"
"component_name":"kafka"
"error":"Unknown data type 154"
"stacktrace":"go.opentelemetry.io/collector/receiver/kafkareceiver.(*consumerGroupHandler).ConsumeClaim
/tmp/opentel/receiver/kafkareceiver/kafka_receiver.go:170
github.com/Shopify/sarama.(*consumerGroupSession).consume
```

@mrajah-twttr could you please point us to the Kafka exporter you are using?

**Describe the solution you'd like**

Consider supporting single Zipkin thrift span in Kafka message.

**Comment by tmcarr** [comment]
This is our current kafka reciever configuration:

`receivers:
  kafka:
    protocol_version: 2.0.0
    topic: zipkin-prod-v1thriftspan
    encoding: zipkin_thrift
    brokers:
      - <HOSTNAMES>`

We ended up just having to change the messages we published into kafka to be a list of spans and things started working. It seems the doc updates have made this clearer, I'd consider this solved.

**Comment by pavolloffay** [comment]
Closing this for now. If there are people using legacy single span producer then please comment and we could add support for it in the collector. It should be very simple fix.
