### ISSUE TITLE
Go 1.15 compatiblity

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector#1820]
**Describe the bug**
Similar issue to the one discovered in https://github.com/jaegertracing/jaeger/issues/2435, whereby certificates are generated using the Common Name field, instead of SANs.

**Steps to reproduce**
```
$ go version
go version go1.14.9 darwin/amd64

$ go test -run TestHttpReception ./config/configgrpc
ok  	go.opentelemetry.io/collector/config/configgrpc	6.168s

# Switch to go 1.15.1
$ go version
go version go1.15.1 darwin/amd64

$ go test -run TestHttpReception ./config/configgrpc
--- FAIL: TestHttpReception (10.03s)
    --- FAIL: TestHttpReception/TLS (2.00s)
        configgrpc_test.go:418:
            	Error Trace:	configgrpc_test.go:418
            	Error:      	Received unexpected error:
            	            	rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for foo, not localhost"
            	Test:       	TestHttpReception/TLS
        configgrpc_test.go:419:
            	Error Trace:	configgrpc_test.go:419
            	Error:      	Expected value not to be nil.
            	Test:       	TestHttpReception/TLS
    --- FAIL: TestHttpReception/mTLS (2.01s)
        configgrpc_test.go:418:
            	Error Trace:	configgrpc_test.go:418
            	Error:      	Received unexpected error:
            	            	rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for foo, not localhost"
            	Test:       	TestHttpReception/mTLS
        configgrpc_test.go:419:
            	Error Trace:	configgrpc_test.go:419
            	Error:      	Expected value not to be nil.
            	Test:       	TestHttpReception/mTLS
FAIL
FAIL	go.opentelemetry.io/collector/config/configgrpc	10.245s
FAIL
```

**What did you expect to see?**
Tests to pass with Go 1.15.

**What did you see instead?**
Failing tests for:

- `go.opentelemetry.io/collector/config/configgrpc`
- `go.opentelemetry.io/collector/config/confighttp`
- `go.opentelemetry.io/receiver/jaegerreceiver`

**What version did you use?**
Version: master HEAD

**What config did you use?**
Config: N/A

**Environment**
OS: MacOS
Compiler(if manually compiled): go 1.15.1

**Additional context**
I propose to add a script (similar to https://github.com/jaegertracing/jaeger/pull/2461) that will provide a self-documenting means of generating certs for now and in future, which is configurable enough to generate certs for each of the above failing tests via a Makefile target: `make cert`. If maintainers agree with this proposal, where should this script belong?

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector/tree/master/internal/buildscripts
