### ISSUE TITLE
Zipkin receiver no longer converts strings to Int/Bool/Floats

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-collector#1888]
**Describe the bug**
Zipkin receiver no longer converts strings to Int/Bool/Floats

This was introduced in https://github.com/open-telemetry/opentelemetry-collector/pull/1656 and this TODO remained in the final merge https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/trace/zipkin/zipkinv2_to_traces.go#L347

@kbrockhoff @tigrannajaryan If I'm understanding the conversation on that pr, the intention was to introduce a configuration option for the zipkin receiver to enable this behavior, is that correct? If so I can work on that

**Steps to reproduce**
Submit a zipkin trace that has ints/bools/floats as string tags, inspect the types after they are received in the processor (or use the logging exporter to view them)

```
[
{
        "traceId": "98bea8e9894443d9",
        "id": "98bea8e9894443d9",
        "kind": "SERVER",
        "name": "get",
        "timestamp": 1599577303251000,
        "duration": 4130,
        "localEndpoint": {
            "serviceName": "client-name",
            "ipv4": "127.0.0.1"
        },
        "tags": {
            "http.status_code": "500"
        }
    }
]
```  

**What did you expect to see?**
Data types should be parsed from strings to the correct type 

eg: `http.status_code` should be an integer not a string

**What did you see instead?**
Remained as strings

**What version did you use?**
`07e8d7b3fe56`

**Comment by tigrannajaryan** [comment]
>Data types should be parsed from strings to the correct type

Why is this needed? This is not obvious to me.

**Comment by chris-smith-zocdoc** [comment]
> > Data types should be parsed from strings to the correct type
> 
> Why is this needed? This is not obvious to me.

The zipkin api specifies tag (attributes) as a map of key(string): value(string) https://zipkin.io/zipkin-api/#/default/post_spans

**Comment by tigrannajaryan** [comment]
> The zipkin api specifies tag (attributes) as a map of key(string): value(string) https://zipkin.io/zipkin-api/#/default/post_spans

@chris-smith-zocdoc I am not sure this answers my question.

You wrote in the PR description:

>eg: http.status_code should be an integer not a string

What does this have to do with attributes being a map of key(string): value(string)?

I do not understand why we need to try to guess the type of the data? We receive a string from Zipking, why doesn't it stay a string in Collector? Why the attempt to parse it and why is Collector making decisions like this? What problem is this solving? 

Collector's philosophy is to preserve data, we only change data when the user asks us to or when we have to because there is no way to represent the received data in the outgoing format. This is not the case here.

**Comment by chris-smith-zocdoc** [comment]
> I do not understand why we need to try to guess the type of the data

Currently all attributes are received as strings, so without this parsing all operations in the pipeline would only be able to perform string comparisons

> Why the attempt to parse it and why is Collector making decisions like this? What problem is this solving?

In our case this is useful for two reasons
1. The ability to write processors that rely on having the correct datatype, eg a sampling policy that does an integer compairison `http.status_code >= 500`

2. Sending the correct datatypes to backend systems
Depending on the backend system, they may or may not be able to deal with all attributes as strings. In our case we need to ensure we send ints/bools/floats where possible so that the backend works correctly. We're using Honeycomb with their Secure Tenancy configuration which requires this.

**Comment by tigrannajaryan** [comment]
>The ability to write processors that rely on having the correct datatype, eg a sampling policy that does an integer compairison http.status_code >= 500

This works with strings as well. http.status_code >= "500" works fine since HTTP status codes are lexicographically in the same order as numerically.

>We're using Honeycomb with their Secure Tenancy configuration which requires this.

This appears to be a specific backend issue. It should be addressed in the backend or in the corresponding vendor specific exporter.

I am not convinced this is a good idea. In fact I believe it is a bad idea since it can incorrectly turn a string that looks like a number into a string and I do not think it is desirable.

**Comment by chris-smith-zocdoc** [comment]
> This works with strings as well. http.status_code >= "500" works fine since HTTP status codes are lexicographically in the same order as numerically.

In my toy example yes it works but it won't reliably work for other custom attributes I may wish to use. 

> This appears to be a specific backend issue. It should be addressed in the backend or in the corresponding vendor specific exporter.

I don't consider this a backend issue, source of the real issue is with with the zipkin api + zipkin libraries. Having this feature in the opentelemetry collector has been incredibly helpful to us because it allows us to process trace data across our organization without swapping the tracing libraries in every application (we have wide zipkin library adoption). 

> I am not convinced this is a good idea. In fact I believe it is a bad idea since it can incorrectly turn a string that looks like a number into a number and I do not think it is desirable because it may break things that we don't know about.

I think this is a really useful feature and it would be a shame to lose it. I understand it may not be desirable to enable by default and we may want to pull this logic out into a separate processor though. 

I'd like to hear thoughts of others in the community who might be using this. The original implementation (contributed by @pjanotti https://github.com/census-instrumentation/opencensus-service/pull/271) for zipkin v1 including the string parsing logic, so this has been around for quite some time. The parsing is [still happening](https://github.com/open-telemetry/opentelemetry-collector/blob/393e98f73e42a1c40f91c56cdabd9b0f07ddacf0/translator/trace/zipkin/zipkinv1_to_protospan.go#L253-L271) for v1 so either way these behaviors should be unified

**Comment by tigrannajaryan** [comment]
I am open to making this either a separate processor or an optional non-default behavior of Zipkin receiver. I would not want to change the default behavior though.

**Comment by tigrannajaryan** [comment]
@chris-smith-zocdoc let me know how you prefer to proceed (see previous comment). If you prefer not to change anything we can close the issue.

**Comment by chris-smith-zocdoc** [comment]
@tigrannajaryan I'll make it a configuration option on the zipkin receiver (default off). I should be able to get to this later this week, will push changes to https://github.com/open-telemetry/opentelemetry-collector/pull/1893 when ready
