### ISSUE TITLE
Writing traces from current @opentelemetry/exporter-collector fails with "cannot unmarshal ID from string"

### ISSUE THREAD

**Issue by tmc** [open-telemetry/opentelemetry-collector#1899]
See https://github.com/open-telemetry/opentelemetry-js/issues/1568

The payloads that the exporter are sending look like:

```
{"resourceSpans":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"collector-trace-exporter"}},{"key":"telemetry.sdk.language","value":{"stringValue":"nodejs"}},{"key":"telemetry.sdk.name","value":{"stringValue":"opentelemetry"}},{"key":"telemetry.sdk.version","value":{"stringValue":"0.11.0"}}],"droppedAttributesCount":0},"instrumentationLibrarySpans":[{"spans":[{"traceId":"In34NtT/Ay92zZ0Akx1KYg==","spanId":"WESYaWFU+/g=","name":"foo","kind":1,"startTimeUnixNano":1601839169774235400,"endTimeUnixNano":1601839169774460700,"attributes":[{"key":"key","value":{"stringValue":"value"}}],"droppedAttributesCount":0,"events":[],"droppedEventsCount":0,"status":{"code":0},"links":[],"droppedLinksCount":0}],"instrumentationLibrary":{"name":"default","version":"*"}}]}]}
```

And the collector currently responds with:
```
{
  "code": 3,
  "message": "cannot unmarshal ID from string 'In34NtT/Ay92zZ0Akx1KYg==': encoding/hex: invalid byte: U+0049 'I'",
  "details": [
  ]
}
```

**Comment by bogdandrutu** [comment]
I think this is because @tigrannajaryan changed the specs and implementation to use hex for IDs instead of base64

**Comment by tigrannajaryan** [comment]
@tmc Collector now expects Trace ID and Span ID to be hex-encoded as it is defined in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#request
The spec was changed a few weeks ago: https://github.com/open-telemetry/opentelemetry-specification/pull/911

Closing this issue since the behavior is as expected.

**Comment by tmc** [comment]
Why was this change made? it seems like a departure from the protobuf json representation standard.

**Comment by tmc** [comment]
Can we make the unmarshalling in the collector accept either?
