### ISSUE TITLE
Implement Summary Metric for PrometheusReceiver

### ISSUE THREAD

**Issue by JasonXZLiu** [open-telemetry/opentelemetry-collector#1913]
## Is your feature request related to a problem? Please describe.

Prometheus Summary metrics are currently not supported and converted to the OTel metric data format. Under the specifications and design of the PrometheusReceiver ([here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/prometheusreceiver/DESIGN.md#summary)), it mentions that Prometheus Summary metrics should be handled properly. However, when the PrometheusReceiver finds Summary metrics, the OTel Collector returns a Nil metric, resulting in dropped metrics.

The summary metric was previously implemented in [OpenCensus](https://github.com/census-instrumentation/opencensus-proto/pull/110) and is a missing feature in OpenTelemetry. 

Related to this issue: https://github.com/open-telemetry/opentelemetry-collector/issues/1638

## Describe the solution you'd like

We would like an implementation of the Summary metric (similar to the one in [Prometheus](https://prometheus.io/docs/concepts/metric_types/#summary)) in OpenTelemetry such that the PrometheusReceiver can convert Prometheus summary metrics to OpenTelemetry summary metrics. In the current [metrics.proto](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/metrics/v1/metrics.proto), only the gauge, sum, and histogram metric types are supported. However, the PrometheusReceiver design specifies that the Summary metric will be converted to a corresponding summary metrics with percentile values as shown [here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/prometheusreceiver/DESIGN.md#summary). 

It seems like the OTEL receivers (including the PrometheusReceiver) convert first to the OpenCensus metric format ([here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/prometheusreceiver/internal/transaction.go#L169)) and then uses a separate method to convert to the OpenTelemetry metrics ([here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/prometheusreceiver/internal/transaction.go#L180)). I believe the PrometheusReceiver currently converts the Prometheus Summary metrics to OpenCensus correctly. However, the conversion between those OpenCensus metrics to OTel is currently not implemented ([here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/internaldata/oc_to_metrics.go#L227-L228)). 

-- cc @alolita @jmacd

**Comment by jmacd** [comment]
This has been discussed in the Metrics SIG and we have agreed that a Summary data point should be added in the next release of OTLP. The protocol change is here: https://github.com/open-telemetry/opentelemetry-proto/pull/227

I do not believe we need to add both integer- and floating-point forms of this data point. I would prefer to see that we remove OpenCensus data format where possible, but you're right that the OC->OTLP conversion should be fixed after this protocol change is finished.

**Comment by JasonXZLiu** [comment]
Yes, sorry this proposal was originally created before the other two in OTel spec. I'm currently working on a PR to implement the OC->OTLP conversion and generate the proper summary structs in the Collector (based on the proto change that you referred to above). Would love your feedback on the PR when it's up! 

p.s. If it's possible, would you be able to assign this issue to me? Thank you!

**Comment by alolita** [comment]
@jmacd @bogdandrutu @tigrannajaryan can you please assign @JasonXZLiu to this issue - we will file a PR shortly.

**Comment by JasonXZLiu** [comment]
Closing this issue as it's a duplicate of this bug (https://github.com/open-telemetry/opentelemetry-collector/issues/1638).
