### ISSUE TITLE
zpages /debug/tracez shows a mismatched encoding for trace IDs

### ISSUE THREAD

**Issue by kevincantu** [open-telemetry/opentelemetry-collector#1920]
I've been experimenting with otel-collector (contrib) 0.11.0, and hooked up the OTLP gRPC receiver and the logging exporter. (My full config is mostly in [this ticket](https://github.com/open-telemetry/opentelemetry-collector/issues/1916), FWIW.)

When I do the following:
* create spans in a Python demo app,
* use the Python Console Exporter (to look at traces),
* use the Python OTLP gRPC exporter,
* use the otel-collector's OTLP gRPC receiver,
* use the otel-collector's logging exporter (to look at traces)...

Expected: when browsing to zpages' /debug/tracez page, and clicking to see detail, the trace IDs should match between interfaces.

Actual: the IDs differ in zpages `/debug/tracez`!

For example, this console trace:
```
{
    "name": "kevin-doing-more",
    "context": {
        "trace_id": "0x127f68ce78b35244e1c202019c4be195",
        "span_id": "0x54f8c53815a7ce90",
        "trace_state": "{}"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": "0xd9458faf2617e74c",
    "start_time": "2020-10-07T21:52:11.216741Z",
    "end_time": "2020-10-07T21:52:11.216805Z",
...
{
    "name": "kevin-otel-hello",
    "context": {
        "trace_id": "0x127f68ce78b35244e1c202019c4be195",
        "span_id": "0xd9458faf2617e74c",
        "trace_state": "{}"
    },
    "kind": "SpanKind.INTERNAL",
    "parent_id": null,
    "start_time": "2020-10-07T21:52:11.216656Z",
    "end_time": "2020-10-07T21:52:11.216823Z",
```

Turns into (expected) this logging exporter trace:
```
Span #0
    Trace ID       : 127f68ce78b35244e1c202019c4be195
    Parent ID      : d9458faf2617e74c
    ID             : 54f8c53815a7ce90
    Name           : kevin-doing-more
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2020-10-07 21:52:11.216741 +0000 UTC
    End time       : 2020-10-07 21:52:11.216805 +0000 UTC
    Status code    : STATUS_CODE_OK
Span #1
    Trace ID       : 127f68ce78b35244e1c202019c4be195
    Parent ID      : 
    ID             : d9458faf2617e74c
    Name           : kevin-otel-hello
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2020-10-07 21:52:11.216656 +0000 UTC
    End time       : 2020-10-07 21:52:11.216823 +0000 UTC
    Status code    : STATUS_CODE_OK
```

But (unexpected) is visible as _this_ in `/debug/tracez`:
```
2020/10/07-21:52:11.407349      .    33 trace_id: 6211ea005157f6b0ff1856141018e0cd span_id: fb81590a89d3fe76
                                        Attributes:{accepted_spans=2, format="protobuf", refused_spans=0, transport="grpc"}
```
<img width="1055" alt="Screen Shot 2020-10-07 at 3 19 17 PM" src="https://user-images.githubusercontent.com/27978219/95394050-809d7080-08b0-11eb-9c7d-f06a943701aa.png">

Is there some leftover encoding difference from OpenCensus?

**Comment by kevincantu** [comment]
There are also some smaller nits: the CSS is missing, the page refers to TraceID instead of trace_id, and the "(sec)" label is wrong.

**Comment by bogdandrutu** [comment]
Hello @kevincantu, I think this is working as intended, the Spans you see in the zpages are internal spans created by the collector tracing instrumentation and suppose to be used for debugging, the spans that you see in the logging exporter are incoming spans (spans received and flowing in our pipelines). So these two are different spans and different traces.

Please send a fix to the zpages CSS in the https://github.com/census-instrumentation/opencensus-go/tree/master/zpages.

Thank you.
