### ISSUE TITLE
observability: add metrics for metric pipelines

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#193]
observability package provides metrics for traces pipelines but there aren't metrics for trace pipelines

**Comment by tigrannajaryan** [comment]
>observability package provides metrics for traces pipelines but there aren't metrics for trace pipelines

metrics for trace pipelines or metrics for metric pipelines?

**Comment by bogdandrutu** [comment]
@pjanotti I think this is resolved, please reopen if that is not the case.
