### ISSUE TITLE
Allow marshalling and unmarshalling of pdata.Traces

### ISSUE THREAD

**Issue by Vemmy124** [open-telemetry/opentelemetry-collector#1939]
**Is your feature request related to a problem? Please describe.**
We want to do an in-memory storage of traces in our fork of the project so it's necessary to be able to convert traces to bytes and wise-versa. Now there is a function allowing to convert traces to proto via `ExportTraceServiceRequest` structure, but no way to unmarshal that protobuf (due to structure's aim of course). 

This missing functionality doesn't expose proto structure, so in my opinion has its chance to be implemented.

**Describe the solution you'd like**
The one solution is to add unmarshalling function from `ExportTraceServiceRequest` to `pdata.Traces` - this is cheap and requires a few lines of code. Seems not perfect, so would be nice to hear alternatives.

**Describe alternatives you've considered**
1. Incapsulated nature of the structure disallows to wrap it with any marshalling tool - can't do this trick.
2. It is possible to convert traces to specific traces from some source and then do implemented marshal/unmarshal, but this is also expensive and can be just used as a workaround.
3. (alternative from our perspective, not otlp) We are bounded by the bytes format of the value to store, so there is no way to get rid of this issue (of course, there is an option to change underlying storage, but this is expensive).

**Comment by bogdandrutu** [comment]
I am ok to support a function that produces pdata from bytes. Please craft a PR to add that

**Comment by tigrannajaryan** [comment]
@Vemmy124 I am not against having he unmarshaling capability, but I am not sure how it helps with in-memory storage. Why not keep the pdata.Traces itself in the memory?

**Comment by Vemmy124** [comment]
@tigrannajaryan To be clear, this is an open-source solution, which has a mode to work with disk. So its interface accepts bytes to be able to dump data to the disk. In my particular situation I'm constrained only by interface. But for those who might want to save traces to disk, it is necessary feature

**Comment by Vemmy124** [comment]
Thanks everyone. This is no longer an issue

**Comment by tigrannajaryan** [comment]
@Vemmy124 yes, makes sense. I am open to adding the functionality in the future once there is an actual component that needs to use it.
