### ISSUE TITLE
For java based application ReadMessageBegin UDP Binary Thrift receiver fails 

### ISSUE THREAD

**Issue by saikishore143** [open-telemetry/opentelemetry-collector#1965]
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by saikishore143** [comment]
We have pulled latest docker image for collector and agent and when we enable opnetracing for java based application on port "6832" we are observing below errors

ReadMessageBegin","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:122\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:86"}
{"level":"debug","ts":1602693102.4759972,"caller":"processors/thrift_processor.go:119","msg":"Span(s) received by the agent","bytes-received":383}
{"level":"error","ts":1602693102.476057,"caller":"processors/thrift_processor.go:122","msg":"Processor failed","error":"Bad version in ReadMessageBegin","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:122\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger


We have also tried on port 6831 it is failing with different depedency

{"level":"error","ts":1602689284.6372876,"caller":"processors/thrift_processor.go:122","msg":"Processor failed","error":"Unknown function emitZipkinBatch","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:122\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:86"}
{"level":"debug","ts":1602689285.6373525,"caller":"processors/thrift_processor.go:119","msg":"Span(s) received by the agent","bytes-received":383}

{"level":"error","ts":1602689285.63745,"caller":"processors/thrift_processor.go:122","msg":"Processor failed","error":"Unknown function emitZipkinBatch","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\tgithub.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:122\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\tgithub.com/jaegertracing/jaeger/cmd/agent/ap

**Comment by saikishore143** [comment]
Sample app code from JAVA
package BOOT-INF.classes.com.example.demoopentracing;

import com.uber.jaeger.Configuration;
import io.opentracing.Tracer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class DemoOpentracingApplication {
  @Bean
  public RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder) {
    return restTemplateBuilder.build();
  }
  
  @Bean
  public Tracer jaegerTracer() {
    return (new Configuration("MyJavaApplication", new Configuration.SamplerConfiguration("probabilistic", 
          1, "**IPOFAGENT:6832**"), new Configuration.ReporterConfiguration(
       true, "**IPOFAGENT**", 6832, 1000, 100)))
      .getTracer();
  }
  
  public static void main(String[] args) {
    SpringApplication.run(com.example.demoopentracing.DemoOpentracingApplication.class, args);
  }
}

**Comment by jpkrohling** [comment]
Could you please provide more details about your setup? Apparently, you are using the Jaeger client with a Spring Boot application, and the error message you shared is an error message that would appear on Jaeger, not OpenTelemetry. I'm wondering where the OpenTelemetry Collector fits here: are you using it as an agent, with the Jaeger receivers? In any case, I'd need an example of your OpenTelemetry Collector configuration file.

A couple more comments:

1. The port 6832 (Thrift Binary) on Jaeger is the wrong one here. The Jaeger Client for Java uses Thrift Compact, which is expected to be sent to the port 6831. See this docs page: https://www.jaegertracing.io/docs/1.20/client-features/
2. Please, share the exact versions of the components you are using: Jaeger Client, OpenTelemetry Collector, Jaeger backend
3. Your Jaeger Client for Java seems quite old (com.uber.jaeger vs. io.jaegertracing)

**Comment by jpkrohling** [comment]
I just tried it out here, and it seems to work fine:

1. get a Spring Boot application from https://start.spring.io/ , selecting "Spring Web" as dependency
1. add the `io.opentracing.contrib:opentracing-spring-jaeger-web-starter:3.2.2` dependency to `pom.xml`
1. start Jaeger (`podman run -p 16686:16686/tcp -p 14250:14250 jaegertracing/all-in-one:1.20.0`)
1. start the OpenTelemetry Collector with the configuration below
1. start the Spring Boot application (`mvn spring-boot:run`)

Collector configuration
```yaml
receivers:
  jaeger:
    protocols:
      thrift_compact:

processors:

exporters:
  logging:
  jaeger:
    endpoint: localhost:14250
    insecure: true

service:
  pipelines:
    traces:
      receivers:
        - jaeger
      processors: []
      exporters:
        - logging
        - jaeger
```

**Comment by saikishore143** [comment]
Hey thanks the issue is resolved now after upgrading my dependencies and
connecting on port 6831.
