### ISSUE TITLE
Panic in marshalling ResourceSpans

### ISSUE THREAD

**Issue by Vemmy124** [open-telemetry/opentelemetry-collector#1985]
**Describe the bug**
Marshalling `otlpcollectortrace.ExportTraceServiceRequest` panics if there are nil components in `ResourceSpans` (e.g. nil `InstrumetationLibrarySpans`). Can we fix that somehow?

**Comment by bogdandrutu** [comment]
Yes, can you provide a test that proves this?

**Comment by Vemmy124** [comment]
Created PR with test which panics

**Comment by tigrannajaryan** [comment]
@Vemmy124 thanks a lot for the repro. Since you went this far are you perhaps also able provide the fix for the bug?

**Comment by bogdandrutu** [comment]
@tigrannajaryan I would like to discuss the solution here, because I think it implies a lot of work. Already started to think about this.

**Comment by bogdandrutu** [comment]
One option that I have in mind and looking to do is actually to change all fields to be not-nullable, which will avoid this case.

**Comment by Vemmy124** [comment]
BTW, what was the purpose of nullable fields? I don't really understand. There are comments everywhere like "panics on non-initialized structure" and it's very hard to understand semantical difference between nil and zero-initialized structure

**Comment by bogdandrutu** [comment]
That is how protobuf by default generates repeated fields (slices), as a slice to pointer of objects. I think this is historical because iterating with range over a slice of objects (not pointers) was slow (it may still be, not sure if it was fixed) because `for _, obj := range slice{}` will copy the object.

Here is a proposal that includes your test: https://github.com/open-telemetry/opentelemetry-collector/pull/2002

**Comment by bogdandrutu** [comment]
We modeled a bit too much on the proto generated code to avoid allocating nil objects. But I think we can make all the objects not nullable and remove that confusion

**Comment by Vemmy124** [comment]
SGTM, would you like me to provide PR for that or we're still trying to agree on the idea?

**Comment by Vemmy124** [comment]
As long as there are no nil objects now, we can close the issue
