### ISSUE TITLE
TestApplication_GetExporters is unstable

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#1987]
See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector/4091/workflows/45011afc-83d4-4c77-8b32-ba3a09c1bb70/jobs/45858

It happened in the past too https://github.com/open-telemetry/opentelemetry-collector/issues/1235

**Comment by codeboten** [comment]
The function mentioned in this issue has been renamed to `TestService_GetExporters` and doesn't appear to be causing issues. Closing for now.
