### ISSUE TITLE
Logging Exporter Histogram Bucket Labels Do Not Increment

### ISSUE THREAD

**Issue by amanbrar1999** [open-telemetry/opentelemetry-collector#2008]
**Describe the bug**
Bucket labels should increment to conform with the Explicit Bound labels

**Steps to reproduce**
Any usage of logging exporter with histograms should produce this

**What did you expect to see?**
<pre>
HistogramDataPoints #0
Data point labels:
     -> Namespace: rpc-app
     -> Service: rpc-app-service
     -> app: rpc-app
     -> container_name: rpc-app-cont
     -> kubernetes_node: xxx
     -> pod_name: xxxx
     -> pod_template_hash: xxxx
StartTime: 1603477500826000000
Timestamp: 1603477800826000000
Count: 2709
Sum: 0.029219
ExplicitBounds #0: -0.000990
ExplicitBounds #1: -0.000890
ExplicitBounds #2: -0.000790
ExplicitBounds #3: -0.000690
ExplicitBounds #4: -0.000590
ExplicitBounds #5: -0.000490
ExplicitBounds #6: -0.000390
ExplicitBounds #7: -0.000290
ExplicitBounds #8: -0.000190
ExplicitBounds #9: -0.000090
ExplicitBounds #10: 0.000010
ExplicitBounds #11: 0.000110
ExplicitBounds #12: 0.000210
ExplicitBounds #13: 0.000310
ExplicitBounds #14: 0.000410
ExplicitBounds #15: 0.000510
ExplicitBounds #16: 0.000610
ExplicitBounds #17: 0.000710
ExplicitBounds #18: 0.000810
ExplicitBounds #19: 0.000910
<b>Buckets #0, Count: 0
Buckets #1, Count: 0
Buckets #2, Count: 0
Buckets #3, Count: 0
Buckets #4, Count: 5
Buckets #5, Count: 14
Buckets #6, Count: 45
Buckets #7, Count: 124
Buckets #8, Count: 255
Buckets #9, Count: 405
Buckets #10, Count: 485
Buckets #11, Count: 523
Buckets #12, Count: 424
Buckets #13, Count: 234
Buckets #14, Count: 130
Buckets #15, Count: 46
Buckets #16, Count: 14
Buckets #17, Count: 3
Buckets #18, Count: 2
Buckets #19, Count: 0
Buckets #20, Count: 0</b>
</pre>

**What did you see instead?**
<pre>
HistogramDataPoints #0
Data point labels:
     -> Namespace: rpc-app
     -> Service: rpc-app-service
     -> app: rpc-app
     -> container_name: rpc-app-cont
     -> kubernetes_node: xxx
     -> pod_name: xxxx
     -> pod_template_hash: xxxx
StartTime: 1603477500826000000
Timestamp: 1603477800826000000
Count: 2709
Sum: 0.029219
ExplicitBounds #0: -0.000990
ExplicitBounds #1: -0.000890
ExplicitBounds #2: -0.000790
ExplicitBounds #3: -0.000690
ExplicitBounds #4: -0.000590
ExplicitBounds #5: -0.000490
ExplicitBounds #6: -0.000390
ExplicitBounds #7: -0.000290
ExplicitBounds #8: -0.000190
ExplicitBounds #9: -0.000090
ExplicitBounds #10: 0.000010
ExplicitBounds #11: 0.000110
ExplicitBounds #12: 0.000210
ExplicitBounds #13: 0.000310
ExplicitBounds #14: 0.000410
ExplicitBounds #15: 0.000510
ExplicitBounds #16: 0.000610
ExplicitBounds #17: 0.000710
ExplicitBounds #18: 0.000810
ExplicitBounds #19: 0.000910
<b>Buckets #0, Count: 0
Buckets #0, Count: 0
Buckets #0, Count: 0
Buckets #0, Count: 0
Buckets #0, Count: 5
Buckets #0, Count: 14
Buckets #0, Count: 45
Buckets #0, Count: 124
Buckets #0, Count: 255
Buckets #0, Count: 405
Buckets #0, Count: 485
Buckets #0, Count: 523
Buckets #0, Count: 424
Buckets #0, Count: 234
Buckets #0, Count: 130
Buckets #0, Count: 46
Buckets #0, Count: 14
Buckets #0, Count: 3
Buckets #0, Count: 2
Buckets #0, Count: 0
Buckets #0, Count: 0</b>
</pre>

**What version did you use?**
latest

**What config did you use?**
config has prometheus receiver to get histograms + logging exporter

**Comment by bogdandrutu** [comment]
This is fixed now
