### ISSUE TITLE
Add "IsEmpty" to TraceID

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2014]
Context: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1377#discussion_r512548225

For better readability and context, the TraceID should have a `IsEmpty`, so that code like `traceID.Bytes() != nil` can be related to `!traceID.IsEmpty()`. Using `traceID.IsValid()` does not directly relate (semantically) to the old check.

**Comment by bogdandrutu** [comment]
Just to clarify `!traceID.IsEmpty()` is equivalent with `traceID.IsValid()` as it is implemented right now, it is just a name change you are suggeting.

**Comment by jpkrohling** [comment]
Right, and that exemplifies my point: without looking at the code, they could actually mean something different ;-)
