### ISSUE TITLE
TestScrape/Validate_Start_Time failed

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#2033]
Auto-generated report for `test` job build.

Link to failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/48157

#### Test Failures
-  [build failed]
-  [build failed]
-  [build failed]
-  [build failed]
-  [build failed]
-  [build failed]

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/48988

#### Test Failures
-  TestScrape
-  TestScrape/Validate_Start_Time

**Comment by tigrannajaryan** [comment]
```
=== RUN   TestScrape/Validate_Start_Time
    network_scraper_test.go:169: 
        	Error Trace:	network_scraper_test.go:169
        	            				network_scraper_test.go:149
        	Error:      	Not equal: 
        	            	expected: 12
        	            	actual  : 13
        	Test:       	TestScrape/Validate_Start_Time
```

**Comment by tigrannajaryan** [comment]
@james-bebbington I assigned this one to you too since you are the author. Please have a look.
