### ISSUE TITLE
Otlphttp Exporter Configuration Does Not Work

### ISSUE THREAD

**Issue by jeffreywang1** [open-telemetry/opentelemetry-collector#2037]
**Describe the bug**
Cannot seem to get otlphttp working while following README in [otlphttpexporter](https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/otlphttpexporter). 

**Steps to reproduce**
Defined configs below following the README via a Docker container, exporters portion of config was similar to this:
```
exporters:
  otlphttp:
    endpoint: "https://<placeholder>"
    insecure: true
```

**What did you expect to see?**
Expected to see the containers started up and data exported over http. 

**What did you see instead?**
Received the following error upon Docker container startup:
```
otel-collector        | Error: cannot load configuration: unknown exporters type "otlphttp" for otlphttp
otel-collector        | 2020/10/29 23:19:45 application run finished with error: cannot load configuration: unknown exporters type "otlphttp" for otlphttp
```

**What version did you use?**
Version: `0.13.0`

**What config did you use?**
Config: mentioned above under Steps to Reduce

**Environment**
OS: "MacOS Catalina 10.15.7"

**Additional context**

**Comment by tigrannajaryan** [comment]
OTLP/HTTP exporter is not available in 0.13.0. It is not yet released. Try master build.
