### ISSUE TITLE
Configurable jaegerreceiver server parameters

### ISSUE THREAD

**Issue by Vemmy124** [open-telemetry/opentelemetry-collector#2045]
**Is your feature request related to a problem? Please describe.**
As I can see, these constants https://github.com/open-telemetry/opentelemetry-collector/blob/1d38caf3b757b4d2f3db10ce9dc04187f170705f/receiver/jaegerreceiver/trace_receiver.go#L96-L98 cannot be configured and server is created with default parameters. If I'm not right - correct me please and to my mind it's the reason to add information to README

**Describe the solution you'd like**
Would be good to add these parameters to receiver config. Even if there is currently some magical way to do this via env variables - would be better to have an explicit way to configure them.

**Comment by Vemmy124** [comment]
I assume, that the problem is wider as long as there are many other different configurable parameters for Jaeger receiver

**Comment by Vemmy124** [comment]
Can we come up with a solution? This might involve making changes in Jaeger. With some approve I can start working on the PR

**Comment by bogdandrutu** [comment]
@Vemmy124 I would suggest to start with offering configs for things that we control, then if anything is necessary we can work with Jaeger to offer that. Do you have one parameter in mind that you want to control?

**Comment by Vemmy124** [comment]
@bogdandrutu There are 3 actually
```
defaultAgentQueueSize     = 1000
defaultAgentMaxPacketSize = 65000
defaultAgentServerWorkers = 10
```
And these settings should be separate for binary and compact thrift formats, so I suggest extending specified protocols in config. Seems to be easy
https://github.com/open-telemetry/opentelemetry-collector/blob/1d38caf3b757b4d2f3db10ce9dc04187f170705f/receiver/jaegerreceiver/config.go#L34

**Comment by Vemmy124** [comment]
Yes, there is a problem for sure - the incoming traffic may be a lot more than default settings can allow. Moreover, socket buffer setting should also be configurable in case of spikes

**Comment by Vemmy124** [comment]
@tigrannajaryan are we moving forward with that?

**Comment by tigrannajaryan** [comment]
Yes, I think we can move forward, I'll review the PR.
