### ISSUE TITLE
OpenTelemetry should a Support for stackdriver tracing as exporter

### ISSUE THREAD

**Issue by jainbhavya65** [open-telemetry/opentelemetry-collector#2056]
I try to export traces to stackdriver using opentelemetry collector but its say i don't have a support of stackdriver exporter any idea. when its support will come?
 Thank you

**Comment by bogdandrutu** [comment]
@jainbhavya65 the support is offered as part of the contrib (extra vendor specific) binary. In core we only support open-source solutions.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/stackdriverexporter it supports trace and metrics.
