### ISSUE TITLE
Missing selector label for 'app: opentelemetry'

### ISSUE THREAD

**Issue by dominthomas** [open-telemetry/opentelemetry-collector#2058]
https://github.com/open-telemetry/opentelemetry-collector/blob/de104da4f136c8798971d66eecdc60e0fb339743/examples/k8s/otel-config.yaml#L173

**Comment by bogdandrutu** [comment]
@dominthomas not sure I understand the issue, can you craft a small PR to fix this?

**Comment by andrewhsu** [comment]
from the the issue triage mtg today, need more info before we can triage

**Comment by bogdandrutu** [comment]
I think is fixed https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/k8s/otel-config.yaml#L55
