### ISSUE TITLE
Links from parent to child not supported in Jaeger

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#206]
This is a follow-up issue from #197. Jaeger does not add a span link from a parent span to its children, only a "ChildOf" link from the child to its parent.

This ticket is to figure out what should be done regarding this mismatch: 

- [ ] In the exporter side, should OpenTelemetry also present this information somewhere else, in order to be restored later? Perhaps it can be stored under a special attribute name.
- [ ] If the information is stored in an alternative location, should the Jaeger receivers then be prepared to look for this information there, even though Jaeger clients won't be sending this data natively?

**Comment by bogdandrutu** [comment]
I think this is fixed.
