### ISSUE TITLE
Allow user to register no exporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2067]
Requiring minimally an exporter is making development harder. The logs are extremely busy and makes it impossible to see the development-time println debugging statements. Please allow user to start the collector without any exporters.

**Comment by flands** [comment]
Is the use-case just for development? You still need to create a receiver right? One workaround might be `--log-level warn`.

**Comment by rakyll** [comment]
--log-level warn is the solution I've been looking for. Thanks.
