### ISSUE TITLE
Include service name label in span receiver/exporter metrics

### ISSUE THREAD

**Issue by linjmeyer** [open-telemetry/opentelemetry-collector#2070]
**Is your feature request related to a problem? Please describe.**
When collecting traces/spans there are several metrics created (e.g. `exporter_send_failed_spans`).  These metrics do not include the span's service name.  Other collectors (e.g. Jaeger Collector) add this label, which is very helpful when determining which services are sending the most spans/traces.

**Describe the solution you'd like**
It would be helpful to include labels with the service name (e.g. `exporter_send_failed_spans{svc="my-service"}`) to identify if a particular service is sending a high amount of spans.  

**Describe alternatives you've considered**
If using an indexed storage backend you can query it directly (e.g. Elastic/Kibana) to get this info.  This is not possible when using un-indexed storages like Grafana Tempo.

**Additional context**
[This was originally a feature request for grafana/agent which uses this repo](https://github.com/grafana/agent/issues/242).

**Comment by andrewhsu** [comment]
from the triage mtg today, setting to p3 allowed for if this change does not affect perf
