### ISSUE TITLE
panic while creating new base exporter

### ISSUE THREAD

**Issue by vipragupta** [open-telemetry/opentelemetry-collector#2086]
**Describe the bug**
When creating a base exporter using [newBaseExporter](https://github.com/open-telemetry/opentelemetry-collector/blob/6c8a8967796c2c67f58ea4d6208187045383c463/exporter/exporterhelper/common.go#L168), when the Logger is not initialized, the code panics while creating logger.

Panic at: https://github.com/open-telemetry/opentelemetry-collector/blob/6c8a8967796c2c67f58ea4d6208187045383c463/exporter/exporterhelper/queued_retry.go#L88

**Steps to reproduce**
In the following test function, give the second parameter of newBaseExporter as nil. 
https://github.com/open-telemetry/opentelemetry-collector/blob/6c8a8967796c2c67f58ea4d6208187045383c463/exporter/exporterhelper/common_test.go#L40

**What did you expect to see?**
no-op when the logger is not initialized

**What did you see instead?**
nil pointer exception

**What version did you use?**
Version: v0.14.0

**Log Trace:**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46f2436]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).Core(...)
        /go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:249
go.opentelemetry.io/collector/exporter/exporterhelper.createSampledLogger(0x0, 0x0)
        /go/pkg/mod/go.opentelemetry.io/collector@v0.14.0/exporter/exporterhelper/queued_retry.go:88 +0x26
go.opentelemetry.io/collector/exporter/exporterhelper.newQueuedRetrySender(0x4c68400, 0x0, 0x0, 0xc000410000, 0x0, 0x0, 0x0, 0x4f48a60, 0xc0003653b0, 0x0, ...)
        /go/pkg/mod/go.opentelemetry.io/collector@v0.14.0/exporter/exporterhelper/queued_retry.go:108 +0x55
go.opentelemetry.io/collector/exporter/exporterhelper.newBaseExporter(0x4f632c0, 0xc00043a000, 0x0, 0xc00021b360, 0x3, 0x3, 0x400e458)
        /go/pkg/mod/go.opentelemetry.io/collector@v0.14.0/exporter/exporterhelper/common.go:176 +0x140
go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter(0x4f632c0, 0xc00043a000, 0x0, 0xc00034dd20, 0xc00021b360, 0x3, 0x3, 0x10, 0xc00034dcd0, 0x57e8f20, ...)
        /go/pkg/mod/go.opentelemetry.io/collector@v0.14.0/exporter/exporterhelper/metricshelper.go:97 +0x84
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter.createMetricsExporter(0x4f6e500, 0xc0000c6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter@v0.14.0/factory.go:83 +0x1fb
go.opentelemetry.io/collector/exporter/exporterhelper.(*factory).CreateMetricsExporter(0xc000360fc0, 0x4f6e500, 0xc0000c6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/go.opentelemetry.io/collector@v0.14.0/exporter/exporterhelper/factory.go:127 +0xbd

**Comment by Vemmy124** [comment]
Let me do PR with this little check. Actually I don't even know in which case this could be crucial, but nevertheless...

**Comment by Vemmy124** [comment]
I feel like nil logger should be interpreted as an error in exported methods but not no-op logger

**Comment by Vemmy124** [comment]
@vipragupta can you please verify, that your problem is solved and we can close the issue. The solution with NewNop() would be a way to hide the possible problems if you accidentally passed nil logger. That is why the error is thrown

**Comment by andrewhsu** [comment]
looks like PR #2141 was merged so closing this issue. feel free to reopen if original issue is not addressed.
