### ISSUE TITLE
otlpreceiver http - send ok to client before running exporters

### ISSUE THREAD

**Issue by nirsky** [open-telemetry/opentelemetry-collector#2100]
Guess this is either a question or a feature request.

We're trying to use opentelemetry for tracing AWS lambda.
Using `otlpreceiver` over HTTP.

That means we have to wait for an Ok from the receiver before terminating the lambda execution (otherwise the span won't get sent).
Our client is node and we're achieving this by waiting for the [export callback](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-tracing/src/export/SpanExporter.ts#L34).

It's taking a long time due to the collector sending ok only after exporting to all the registered exporters, which means the lambda execution time is dramatically increased.  

We're trying to get the collector to send ok immediately after getting the span, and proceed to export it asynchronously after.

**Comment by bogdandrutu** [comment]
@nirsky I can see this as an interesting use-case, but also comes with a problem. By sending ok immediately we may drop the data and the client may not know and may not be able to retry for example. But your use-case is valid and probably we should support it.

As a quick "solution" add the batching porcessor in the pipeline or enable sending_queues in the exporter that you use so the response is sent back quicker. I know this is not the right solution, but a quick hack :)

**Comment by nirsky** [comment]
@bogdandrutu Thanks for your response!
I understand the problem and don't think it should be the default behavior, but rather configurable in some way (maybe some header?).  
In some cases like lambda, we prefer speed over data reliability.

I'll try the suggested solution and see if it helps, thanks!

**Comment by jpkrohling** [comment]
+1 for using batching for that

**Comment by bogdandrutu** [comment]
@nirsky let me know how that went

**Comment by tigrannajaryan** [comment]
> but rather configurable in some way (maybe some header?).

It is configurable in the Collector. You can use a batch processor or just use an exporter with enabled queue. If a particular exporter does not have the queue enabled then that would be good to fix. What exporter do you use?

It could be a receiver config option too but given that batch processor is recommended by default anyway I am not sure we need another approach.

**Comment by andrewhsu** [comment]
from the triage mtg today, adding discussion label since more info is also needed, but initially setting to p3

**Comment by nirsky** [comment]
@tigrannajaryan We use 4 different exporters and unfortunately non has `sending_queue` implemented (kinesis, zipkin and 2 custom ones).

@bogdandrutu Tried using batch processor, seem to help a lot!
I think we can close this issue, I tried implementing an immediate response endpoint myself, and tested it on my lambda.  
Didn't see any significant improvement over using the batch processor.

**Comment by tigrannajaryan** [comment]
Closing. Feel free to reopen if necessary.
