### ISSUE TITLE
Request: repository for the OpenTelemetry Collector Builder

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2129]
The [OpenTelemetry Collector Builder](https://github.com/observatorium/opentelemetry-collector-builder) is a CLI tool that generates OpenTelemetry Collector binaries based on a manifest.  It has been incubating in another organization (`observatorium`) for a while. I believe it's stable enough by now and could be useful to a wider audience, so, I'd like to ask whether it would be in this community's interest to host the main repository for the project.

cc @open-telemetry/collector-maintainers and @open-telemetry/collector-approvers for opinions.

**Comment by bogdandrutu** [comment]
I think this should go to the community if a new repository is needed. Otherwise you may consider in contrib one cmd

**Comment by jpkrohling** [comment]
Opened an issue there:  open-telemetry/community#568
