### ISSUE TITLE
Doc: how to have a custom build and link to contrib repo

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#213]
We need to document how to have builds with custom sets of receivers/processors/exporters and link to contrib repo.

**Comment by jpkrohling** [comment]
I'm planning on building an "opentelemetry-collector-builder", which would generate a binary based on a list of extra go modules as input. For that, I would certainly appreciate if someone could write a couple of paragraphs on the supported (or expected) way to have a custom build.

My understanding is that I would need to create an entrypoint (`main()`) that would get `defaultcomponents.Components()`, generates an `component.ApplicationStartInfo`, and creates a `service.Parameters` based on both. From there, all it needs is a `service.New().Start()`. Is that pretty much it ? If so, please assign this to me, and I'll create this doc as I go along.

**Comment by jpkrohling** [comment]
The builder that I mentioned above could be used to address open-telemetry/opentelemetry-collector-contrib#873 and open-telemetry/opentelemetry-collector-contrib#35

**Comment by jpkrohling** [comment]
I got a builder working. It's currently located in my own namespace, but I could move it to OpenTelemetry contrib if you think it's suitable: https://github.com/jpkrohling/opentelemetry-collector-builder .

**Comment by jpkrohling** [comment]
Updated link to the repository: https://github.com/observatorium/opentelemetry-collector-builder

Should I use this as base for the doc? I could write a few lines about how to build a custom distribution and briefly mention the builder somewhere.

@kbrockhoff, once you figure out where the docs should go, we might know where to place this here as well.

**Comment by jpkrohling** [comment]
@tigrannajaryan you can assign this to me.

**Comment by jpkrohling** [comment]
@pjanotti, @tigrannajaryan, is it OK if I document this in a blog post first, until a decision about an appropriate home for the docs is made?

**Comment by tigrannajaryan** [comment]
> @pjanotti, @tigrannajaryan, is it OK if I document this in a blog post first, until a decision about an appropriate home for the docs is made?

Sounds good to me.

**Comment by jpkrohling** [comment]
I tried pinging @SergeyKanzhelev and @mtwo on Gitter but got no replies yet. I really want to publish this in the OpenTelemetry publication, but in case it's not possible/desired, let me know and I'll find an alternative place.

**Comment by mtwo** [comment]
Apologies, I must have missed the notification. Will take a look today.

________________________________

**Comment by SergeyKanzhelev** [comment]
the process for the blog post is to send draft and request to join OpenTelemetry publication to cncf-opentelemetry-comms@lists.cncf.io. This is a draft of how to do comms: https://docs.google.com/document/d/1tyy9SJw4ma7qGhjmJrNDBVC98qGxA1ssbYOJY2Jlok4/edit#heading=h.egqr4xhr9jrz - still in progress

**Comment by jpkrohling** [comment]
Thanks for the doc, I'll follow it and propose a blog post. Is this already public information and I missed it?

**Comment by SergeyKanzhelev** [comment]
> Thanks for the doc, I'll follow it and propose a blog post. Is this already public information and I missed it?

It was never widely publicized. This doc is intended to do this. Last blog post was using this doc to validate it has enough info. Please share your feedback as well

**Comment by jpkrohling** [comment]
Can this be closed? I think there's now a sufficient documentation about this (blog post + link from the doc).
