### ISSUE TITLE
Allow contributors to see the CI logs

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2142]
Currently, it's not possible to the CI logs as a contributor not invited into the organization. This situation makes it slightly harder to contribute and is wasting the reviewer's time because they need to call out for the problems. Please allow contributors to see the CI logs so the contributors can take action as soon as something fails.

**Comment by andrewhsu** [comment]
from the issue triage mtg today, discussed this and seems like this can be resolved by moving to github actions. related issue: #1234
