### ISSUE TITLE
Config: better errors from config factories

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#215]
Errors raised in config factories report errors from settings in yaml files. They should reference the corresponding tag on the yaml, not the actual field name. On the short run we can just ensure that the messages are using the tag instead of the field name. Ideally we can should look into provide helper types that can extract the tags from the structures so errors always follow the desired pattern.

**Comment by bogdandrutu** [comment]
This was done https://github.com/open-telemetry/opentelemetry-collector/pull/1460
