### ISSUE TITLE
Make default config per type (metric, traces, etc.)

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#2160]
**Is your feature request related to a problem? Please describe.**

Created from https://github.com/open-telemetry/opentelemetry-collector/pull/1966#discussion_r524005206

I want to create default config that is different for each entity (traces, metrics, logs). Currently the `Factory.createDefaultConfig` creates a default config for all entities.

**Describe the solution you'd like**

A factory interface that allows creating different default config for each entity. 

**Describe alternatives you've considered**

Create a single default config with zero values and set appropriate defaults in the create exporter. 

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector/pull/1966#discussion_r524005206

**Comment by bogdandrutu** [comment]
This is a bit too late to implement at this point.
