### ISSUE TITLE
Build OTel Collector for darwin/arm64

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-collector#2172]
**Is your feature request related to a problem? Please describe.**
ARM64 Macs should be able to run the Collector from a container image without needing to manually build.

**Describe the solution you'd like**
Build Collector for darwin/arm64

**Additional context**
https://github.com/golang/go/issues/38485 is slated to go out with go1.16, which is a prereq.

**Comment by rakyll** [comment]
Beyond the container images, having a standalone binary would be great for the development time. BTW, there is an active issue with Docker on macOS ARM64: https://github.com/docker/for-mac/issues/4733.

**Comment by bhautikpip** [comment]
I can help with this issue.
