### ISSUE TITLE
Add note about the Prometheus receiver's capabilities

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2175]
The Prometheus receiver has a variety of issues at the moment:

* It provides redundancy when scaled up but there is no good solution yet to run multiple replicas of it.
* When scaled up with the same config, it scrapes the same endpoint multiple times. This might be surprising for the user.
* It can't scale the scraping unless user runs multiple collectors with different Prometheus configuration.
* It's a stateful component but we don't mention it clearly. This may cause data loss.

We have a long-term plan to address some of the issue described above but in the meantime, it'd be good to add a note on the receiver's README that there are limitations. We may also suggest users to only rely on the receiver if there are ok with the current limits.

**Comment by bogdandrutu** [comment]
PR was merged.
