### ISSUE TITLE
[RPM/MSI] Enable logging level

### ISSUE THREAD

**Issue by wyTrivail** [open-telemetry/opentelemetry-collector#2255]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem but a pain point for linux/windows instance customers who are installing rpm/msi, i find no way to enable the logging level since the collector is running within service. no parameters can be sent into it. 

**Describe the solution you'd like**
I'd like to have a unified solution for both msi and rpm/deb so that customers can enable debug logging level. 

One way i can think of is to ask customer to `touch` a file named `debug`, so that collector can read it and change the logging level.

**Describe alternatives you've considered**

I have been thinking about using env var, however the ways to set up env var for linux service and windows service are different, so that it's not a unified solution.  

**Additional context**

I'm happy to implement this feature if it's reasonable to you.

**Comment by jpkrohling** [comment]
Do you want to change the log-level for a running instance, or do you want to change the service configuration?

**Comment by wyTrivail** [comment]
we have logging level config in the yaml just for the logging exporter, for that, yes we can configure it, i'm pointing this out just in case we are confused with the logging exporter.

today, we can use command line `--log-level` to change the logging level while starting collector. However, if customers install collector via rpm, collector will be running as a service in linux, in this case, do we expect customers to directly change the [service config](https://github.com/open-telemetry/opentelemetry-collector/blob/master/internal/buildscripts/packaging/fpm/otel-collector.service#L6) to add the `--log-level` into it? 

This feature request is assuming we are not expecting customers to touch the service config, and trying to figure out a way for customers to config the log level.

**Comment by jpkrohling** [comment]
Agree that we should allow CLI flags to be specified externally. For the moment, you can create a `/etc/collector.conf` with env vars like `LOG_LEVEL=debug` and set your unit file as:

```
EnvironmentFile=/etc/collector.conf
ExecStart=/usr/bin/otelcol --log-level=$LOG_LEVEL
```

**Comment by wyTrivail** [comment]
@jpkrohling thx for the suggestion! it's doable.

maybe better to build `EnvironmentFile=/etc/collector.conf` into https://github.com/open-telemetry/opentelemetry-collector/blob/master/internal/buildscripts/packaging/fpm/otel-collector.service#L12 ?

For long-term, do you have any idea?

**Comment by jpkrohling** [comment]
For the long term, we should consider using another instance of viper, to bind env vars to flags.

**Comment by niemyjski** [comment]
Just upgraded from 0.56 to 0.66 docker images (get this is different from this issue but related) and noticed that `--log-level` is no longer a thing but not documented (only saw this issue)

```
2022-12-06 11:24:27 Error: unknown flag: --log-level
2022-12-06 11:24:27 2022/12/06 17:24:27 collector server run finished with error: unknown flag: --log-level
```

**Comment by atoulme** [comment]
@niemyjski this was deprecated and removed from the collector. This was done in https://github.com/open-telemetry/opentelemetry-collector/pull/6334.

**Comment by atoulme** [comment]
Closing this issue now as the original problem is fixed. Please consider opening a new issue if you see follow up work.

**Comment by niemyjski** [comment]
@atoulme I saw that as well. For anyone reading this is there a better way to enable log level because I'm not seeing it.
