### ISSUE TITLE
Rename service.Application.SignalTestComplete to Shutdown

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2260]
SignalTestComplete doesn't belong to an external API, rename this method to Shutdown and follow up with https://github.com/open-telemetry/opentelemetry-collector/issues/483 in the future.

**Comment by rakyll** [comment]
Alternative, document that SignalTestComplete API is not stable and might be removed in the future.

**Comment by tigrannajaryan** [comment]
+1. We should rename to Shutdown and also rename stopTestChan to just stopChan. I can't see anything special about this stopping that is only applicable to tests. It is just a way to stop the service.

**Comment by tigrannajaryan** [comment]
@rakyll would you like to submit a PR that fixes this?

**Comment by rakyll** [comment]
Surely.
