### ISSUE TITLE
Honor retry, queue and timeout settings in prometheusremotewriteexporter

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2266]
prometheusremotewriteexporter is accepting RetrySettings, QueueSettings and TimeoutSettings but are not honoring them. These settings are critical for fine tuning the Prometheus Remote Writes.  https://prometheus.io/docs/practices/remote_write/ Use these settings when exporting.

cc @huyan0  @amanbrar1999 @JasonXZLiu

**Comment by amanbrar1999** [comment]
I'm not sure what you mean here by the exporter not honoring these settings. The `exporterhelper` package, which this exporter implements, uses these settings.

**Comment by rakyll** [comment]
We discussed offline. Retries are handled outside the PRW exporter which was not initially visible to me. Closing this issue for now but we can follow up if we want to provide a PRW-specific retry strategy.
