### ISSUE TITLE
Improve error message for bind failures

### ISSUE THREAD

**Issue by jchengsfx** [open-telemetry/opentelemetry-collector#2275]
**Is your feature request related to a problem? Please describe.**
If a component, e.g. the prometheus receiver, fails to bind to an address, the output shows something like:
```
Dec 10 18:50:24 ip-172-31-6-45 otelcol[4059]: 2020-12-10T18:50:24.427Z        ERROR        service/service.go:264        Asynchronous error received, terminating process        {"error": "listen tcp 127.0.0.1:8888: bind: address already in use"}
```

**Describe the solution you'd like**
Improve the error message to include the component that is failing to bind and possible workaround.  For example, the error message above would include that it came from the prometheus receiver and that the address can be changed with the `--metric-addr` option.

**Comment by bogdandrutu** [comment]
Resolved, since we wrapped the host with the logger for each component.
