### ISSUE TITLE
Question about how to configure zap logger

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-collector#2293]
I built a custom collector using [this guide](https://medium.com/opentelemetry/building-your-own-opentelemetry-collector-distribution-42337e994b63) with collector v0.16.0.

Everything works great, except that I need to configure the logger to output json format with MessageKey equals "message" (instead of the default "msg").
I want to be able to set this configuration when calling service.New:
`conf.EncoderConfig.MessageKey = "message"`

My current code looks like this:
```go
app, err := service.New(service.Parameters{ApplicationStartInfo: info, Factories: factories, LoggingOptions: loggingOptions})
```
but was not able to understand how to set EncoderConfig with LoggingOptions.

Is it possible? any help will be appreciated as I'm new to GO. thanks

**Comment by bogdandrutu** [comment]
It is now, you can use the "service::telemetry::logs" section.
