### ISSUE TITLE
Prometheus remote write exporter is failing with "out of order samples" under load

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2315]
The Prometheus remote writer exporter is failing with the following errors under load:

* out of order samples
* duplicate sample for timestamp

These issues can be potentially caused by the concurrent writes at https://github.com/open-telemetry/opentelemetry-collector/blob/a16c599d26b6db7a95489568ca890b06380463cc/exporter/prometheusremotewriteexporter/exporter.go and/or samples produced for the same metric type at the same replica of the target without pod labels.

I'm consistently able to reproduce the problem in a Kubernetes cluster. To reproduce, run a single replica of the collector and try to collect from 50/60 targets or more and produce 40-50 metrics at each target .

**Comment by bogdandrutu** [comment]
I think this is a backend error correct? Does the Prometheus remote write require samples to come in a specific ordering?

**Comment by rakyll** [comment]
This is a backend error, but we must make sure our fan-out logic is causing this error. Prometheus is an append-only system, so you can't ingest older data points to a series after appending relatively newer ones.

The second error might be potentially cased by a failure to label data points correctly. Assume you have N replicas of the same program exporting the same metric. If the scraper fails to label the data points with the source program's unique identifier, we might be sending duplicate samples for the same metric at the same timestamp.

**Comment by andrewhsu** [comment]
talked about this at the collector sig mtg today, @rakyll can you provide more info on what you expect to see?

**Comment by jmacd** [comment]
There's something here about how metrics are meant to be "single source". It should not be possible to get out-of-order samples in a correctly configured system, since each metric should come from a single source of truth.  I wrote about how "single-homed" metrics are always easier in this document: https://docs.google.com/document/d/1hed5J_Lk_l1qz5rei4V7kDSzcIlr4b0qKG4m7VfbS0I/edit?usp=sharing

**Comment by rakyll** [comment]
We produce remote write requests not in the choronological order:


first req ============> timeseries:<labels:<name:"__name__" value:"test_histogram0_count" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"0.1" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_summary0_count" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.1" > samples:<value:0.4774478099834713 timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.5" > samples:<value:0.8713202045000787 timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_gauge0" > samples:<value:5.723645357596498 timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_sum" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"0.005" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"1" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"+Inf" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_summary0_sum" > samples:<timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.99" > samples:<value:0.9977474185974964 timestamp:1618297785608 > > timeseries:<labels:<name:"__name__" value:"test_counter0_total" > samples:<timestamp:1618297785608 > >

second req ============> timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"0.005" > samples:<timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"1" > samples:<value:17 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"+Inf" > samples:<value:17 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_summary0_sum" > samples:<value:16.256622262869485 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.5" > samples:<value:0.920758717698257 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_gauge0" > samples:<value:5.41446628663609 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_sum" > samples:<value:16.256622262869485 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_bucket" > labels:<name:"le" value:"0.1" > samples:<timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_summary0_count" > samples:<value:17 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.1" > samples:<value:0.5881942475189074 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_summary0" > labels:<name:"quantile" value:"0.99" > samples:<value:0.9984683987641793 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_counter0_total" > samples:<value:0.06368703615839877 timestamp:1618297785602 > > timeseries:<labels:<name:"__name__" value:"test_histogram0_count" > samples:<value:17 timestamp:1618297785602 > >
2021-04-13T07:09:45.676Z	error	exporterhelper/queued_retry.go:279	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "awsprometheusremotewrite", "error": "Permanent error: server returned HTTP status 400 Bad Request: user=516699956539_ws-ce1f837b-8384-42dc-8c55-4e3834673ad5: err: out of order sample. timestamp=2021-04-13T07:09:45.602Z, series={__name__=\"test_summary0_sum\"} ", "dropped_items": 4}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	/Users/jbd/opentelemetry-collector/exporter/exporterhelper/queued_retry.go:279
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	/Users/jbd/opentelemetry-collector/exporter/exporterhelper/metricshelper.go:120
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	/Users/jbd/opentelemetry-collector/exporter/exporterhelper/queued_retry.go:152
github.com/jaegertracing/jaeger/pkg/queue.ConsumerFunc.Consume
	/Users/jbd/go/pkg/mod/github.com/jaegertracing/jaeger@v1.22.0/pkg/queue/bounded_queue.go:104
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory.func1
	/Users/jbd/go/pkg/mod/github.com/jaegertracing/jaeger@v1.22.0/pkg/queue/bounded_queue.go:83

Second request proto has an earlier timestamp than the first one.

**Comment by rakyll** [comment]
In the exporter, the internal type we use for the incoming metric data (map[string]*prompb.TimeSeries{}) is a map and shuffles the order of the data. Let's replace this with a slice, we need to preserve the order.
