### ISSUE TITLE
TimestampUnixNano vs time.Time

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector#2330]
Just curious, why do we have a separate type for a timestamp, `TimestampUnixNano`.

https://github.com/open-telemetry/opentelemetry-collector/blob/51563860af5a558b6e7087feea2502b5d348375c/consumer/pdata/common.go#L29

`time.Time` is also an instant in time with nanosecond precision

https://golang.org/pkg/time/#Time

So it seems we don't need to introduce a custom type?

**Comment by tigrannajaryan** [comment]
`time.Time` is a more complicated type:
```go
type Time struct {
	wall uint64
	ext  int64
	loc *Location
}
```
Using it would result in a (probably tiny but still) performance impact.

TimestampUnixNano matches the exact definition of the OTLP protocol for timestamps.
