### ISSUE TITLE
Use the same port for OTLP/HTTP receiver as for OTLP/gRPC

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#2353]
According to https://github.com/open-telemetry/opentelemetry-specification/issues/1148#issuecomment-721889635 we need to use port 4317 for OTLP/HTTP receiver.

@bogdandrutu you looked into this previously. Are you able to do this? I believe we need to do this before GA.

**Comment by jpkrohling** [comment]
We discussed this in the past and this is not a good idea, as it's not possible to do that when TLS is involved.

**Comment by axw** [comment]
Is this a duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/1256?

**Comment by jpkrohling** [comment]
Looks like it is.

**Comment by tigrannajaryan** [comment]
Specification says it must be the same port. @bogdandrutu looked into it and I think concluded that it should be possible. If it turns out to be impossible we will be not compliant with the spec or will need to change the spec again.

**Comment by tigrannajaryan** [comment]
Closing, duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/1256
