### ISSUE TITLE
Report OTel Collector version in the collector health page and/or diagnostic pages

### ISSUE THREAD

**Issue by CeeBeeCee** [open-telemetry/opentelemetry-collector#2382]
**Is your feature request related to a problem? Please describe.**
It is hard to know what version of the collector is running without logging into the server to find out

**Describe the solution you'd like**
Add a version key-value pair to the health check and/or the tracez/pprof pages. Something like :
{**"version": "0.18.0"**. status":"Server available","upSince":"2021-01-20T16:26:04.209548064Z","uptime":"9m34.530382956s"}

**Comment by bogdandrutu** [comment]
We have all these informations in "/debug/servicez" page if you enable the zpages extension.

**Comment by bogdandrutu** [comment]
Not sure about the "status" thing, how do we determine if status OK or NOT?

**Comment by CeeBeeCee** [comment]
When I access the servicez page, it reports "latest" as the version and not 0.18 which is what I'm running (using docker). Anyway to get it to return the actual version number? Also, the status, upSince and uptime is the current response coming from the health_check extension. I was just proposing that we add version to it.

Version | \| | latest
-- | -- | --
GitHash | \| | <NOT PROPERLY GENERATED>
BuildType | \| | release
Goversion | \| | go1.14.13
OS | \| | linux
Architecture | \| | amd64

**Comment by bogdandrutu** [comment]
Ok.. so you need only to fix the version then

**Comment by CeeBeeCee** [comment]
Correct

**Comment by CeeBeeCee** [comment]
@bogdandrutu : I see that you have closed this issue. Is there a way for me to test the changes? Perhaps from the otel/opentelemetry-collector-dev image on dockerhub?
