### ISSUE TITLE
Add ability to use aggregate logger in pipeline

### ISSUE THREAD

**Issue by pkositsyn** [open-telemetry/opentelemetry-collector#2397]
**Is your feature request related to a problem? Please describe.**
Currently we cannot globally limit number of logs, produced by the pipelines. The common mistake among the whole repository is that every request can result in a log in some consumer, which overrides logging pipelines. Yesterday I got the situation, such that collector started producing 150k logs/min because of exporter failure (which was external error actually).

**Describe the solution you'd like**
I think the best way to avoid such situations is adding config options for general logger, passed into every consumer.
This is already done in logging exporter and I like this as a way to limit logs
https://github.com/open-telemetry/opentelemetry-collector/blob/2c8915a34925b1ffaf87c21a927f5f9a442d83ab/exporter/loggingexporter/factory.go#L90-L111

**Comment by andrewhsu** [comment]
closing as duplicate because this issue is taken care of in #2102
