### ISSUE TITLE
vsock support in library and agent, and support for multiple inputs in agent

### ISSUE THREAD

**Issue by egernst** [open-telemetry/opentelemetry-collector#242]
Very happy to see the active work on this project!

I am eager to adopt opencensus/open-telemetry for the [Kata Containers](https://katacontainers.io) project, but we have a couple of particular needs that I'd like to see if we can add support for.

## Background on use case
Kata is a container runtime, with part of the runtime infrastructure running on a host, _kata-runtime_, and the portion managing the container workload running within a virtual machine, _kata-agent._ Communication between the __kata-runtime_ and the _kata-agent_ are carried out via gRPC running over vsock.

## How we handle tracing today
Tracing is great, and we currently utilize open-tracing.  We have to do several workarounds in order to get traces/metrics from both the _kata-agent_ and the _kata-runtime_.  Basically, in the guest we'd use a standard opencensus exporter and [run socat to transfer from UDP->vsock](https://github.com/kata-containers/agent/blob/94e2a254a94a77c02280f4f84d7f82269be163ce/jaeger-client-socat-redirector.service), and then on the host run another instance of [socat to take the data from vsock->UDP](https://github.com/kata-containers/agent/blob/94e2a254a94a77c02280f4f84d7f82269be163ce/scripts/vsock-to-udp-server.sh). This isn't very flexible, and makes tracing of the _kata-agent_ very painful and error prone for our end users. 

## Ideal scenario
Opencensus/OpenTelemetry support for exporting to a vsock and receiving from both UDP and vsock.  I'm happy to work with folks in the Kata community to get a PR in place, but wanted to get feedback from the open-telemetry and opencensus folks.

**Comment by tigrannajaryan** [comment]
If I am reading this issue correctly this is a request to add a receiver and exporter that support vsock format. Our approach with OpenTelemetry Service is that core (this repo) will contain support limited number of open-source formats and additional receivers/exporters/processors can be added to contrib repo at https://github.com/open-telemetry/opentelemetry-service-contrib/

As an example on how to do it see the StackDriver exporter at https://github.com/open-telemetry/opentelemetry-service-contrib/tree/master/exporter/stackdriverexporter

**Comment by egernst** [comment]
In a perfect world, I don't want yet another exporter/receiver.  I'd rather existing one be flexible to be able to make use of either/or vsock as well as UDP.

**Comment by tigrannajaryan** [comment]
>In a perfect world, I don't want yet another exporter/receiver. I'd rather existing one be flexible to be able to make use of either/or vsock as well as UDP.

By design each receiver and exporter support one specific protocol. New protocols can be added by implementing new receiver and exporter types. The intended way is for community member who are willing to contribute new receivers, exporters or processors is to propose them in the contrib repo I linked to in the previous post.

**Comment by bogdandrutu** [comment]
@egernst any update on this, I am not very familiar with `vsock` or Kata, but would like to understand better what is needed: 
1. What "protocol" do you want to talk over `vsock`? gRPC?
2. How easy is to use `vsock` in golang? Is there a standard library for this?
