### ISSUE TITLE
Supportability: Revisit the log entries we have

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2431]
Context: https://github.com/open-telemetry/opentelemetry-collector/issues/2098#issuecomment-736820622

This issue here is to track which log entries we have in the usual case, which ones are shown when a problem happens, and what we could be having to help identify problems.

**Comment by jpkrohling** [comment]
When the logging exporter is enabled with `logLevel: debug`, the following is seen when a batch with 2 spans is sent and the pipeline is properly configured:

```
2021-02-02T13:24:36.255+0100	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 2}
2021-02-02T13:24:36.255+0100	DEBUG	loggingexporter/logging_exporter.go:352	ResourceSpans #0
Resource labels:
     -> service.name: STRING(tracegen)
InstrumentationLibrarySpans #0
InstrumentationLibrary tracegen 
Span #0
    Trace ID       : 2cdd9ff21dc834d442d4762e8cffef12
    Parent ID      : 163337910d2306b2
    ID             : f2d897eeeb45c938
    Name           : okey-dokey
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2021-02-02 13:24:36.25349814 +0100 CET
    End time       : 2021-02-02 13:24:36.253622118 +0100 CET
    Status code    : STATUS_CODE_OK
    Status message : 
Attributes:
     -> span.kind: STRING(server)
     -> net.peer.ip: STRING(1.2.3.4)
     -> peer.service: STRING(tracegen-client)
Span #1
    Trace ID       : 2cdd9ff21dc834d442d4762e8cffef12
    Parent ID      : 
    ID             : 163337910d2306b2
    Name           : lets-go
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2021-02-02 13:24:36.253494558 +0100 CET
    End time       : 2021-02-02 13:24:36.253622118 +0100 CET
    Status code    : STATUS_CODE_OK
    Status message : 
Attributes:
     -> span.kind: STRING(client)
     -> net.peer.ip: STRING(1.2.3.4)
     -> peer.service: STRING(tracegen-server)
```

**Comment by jpkrohling** [comment]
When using the Jaeger exporter and the remote backend isn't available, the following can be seen in the default configuration:

```
2021-02-02T13:40:44.298+0100	INFO	jaegerexporter/exporter.go:190	State of the connection with the Jaeger Collector backend	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger", "state": "TRANSIENT_FAILURE"}
2021-02-02T13:40:49.424+0100	INFO	exporterhelper/queued_retry.go:276	Exporting failed. Will retry the request after interval.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:14250: connect: connection refused\"", "interval": "5.52330144s"}
```

**Comment by akankshahulge** [comment]
> When the logging exporter is enabled with `logLevel: debug`, the following is seen when a batch with 2 spans is sent and the pipeline is properly configured:
> 
> ```
> 2021-02-02T13:24:36.255+0100	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 2}
> 2021-02-02T13:24:36.255+0100	DEBUG	loggingexporter/logging_exporter.go:352	ResourceSpans #0
> Resource labels:
>      -> service.name: STRING(tracegen)
> InstrumentationLibrarySpans #0
> InstrumentationLibrary tracegen 
> Span #0
>     Trace ID       : 2cdd9ff21dc834d442d4762e8cffef12
>     Parent ID      : 163337910d2306b2
>     ID             : f2d897eeeb45c938
>     Name           : okey-dokey
>     Kind           : SPAN_KIND_INTERNAL
>     Start time     : 2021-02-02 13:24:36.25349814 +0100 CET
>     End time       : 2021-02-02 13:24:36.253622118 +0100 CET
>     Status code    : STATUS_CODE_OK
>     Status message : 
> Attributes:
>      -> span.kind: STRING(server)
>      -> net.peer.ip: STRING(1.2.3.4)
>      -> peer.service: STRING(tracegen-client)
> Span #1
>     Trace ID       : 2cdd9ff21dc834d442d4762e8cffef12
>     Parent ID      : 
>     ID             : 163337910d2306b2
>     Name           : lets-go
>     Kind           : SPAN_KIND_INTERNAL
>     Start time     : 2021-02-02 13:24:36.253494558 +0100 CET
>     End time       : 2021-02-02 13:24:36.253622118 +0100 CET
>     Status code    : STATUS_CODE_OK
>     Status message : 
> Attributes:
>      -> span.kind: STRING(client)
>      -> net.peer.ip: STRING(1.2.3.4)
>      -> peer.service: STRING(tracegen-server)
> ```

where do i add loglevel:debug in configmap.yaml how cani able to see these logs now i am able to see only 2023-06-29T10:39:46.672Z	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 1}
