### ISSUE TITLE
Supportability: Improve troubleshooting guide

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2433]
Once both #2430 and #2431 are done, we should create a troubleshooting guide, making it easier for people to understand what's wrong in their setup. It should also make it easier for us to provide support, as people can just tell us which part of the guide is failing for them.

**Comment by tigrannajaryan** [comment]
Improve this: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md
