### ISSUE TITLE
Supportability: make the sending_queue observable

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2435]
Similar to #2434 but for the sending_queue. It does contain some log entries but no metrics. Apparently, it annotates spans that might exist in the context, but it's not clear how to access this data.

**Comment by alolita** [comment]
@bogdandrutu can this be moved to a Phase 3 backlog which will be done post GA?

**Comment by bogdandrutu** [comment]
This is not a breaking change, so definitely not required for "API stability" but a GA collector has to have observability. So we can move this to phase3 and make that phase GA phase required.
