### ISSUE TITLE
Doesn't build when GOOS=freebsd

### ISSUE THREAD

**Issue by vibhavp** [open-telemetry/opentelemetry-collector#2437]
**Describe the bug**
`opentelemetry-collector` doesn't build when `GOOS` is set to `freebsd`.

**Steps to reproduce**

```sh
git clone https://github.com/open-telemetry/opentemetry-collector
cd opentemetry-collector
GOOS=freebsd make install-tools && make install
```

**What did you expect to see?**
`opentelemetry-collector` should build and output a FreeBSD `otelcol` binary

**What did you see instead?**
The build fails:
```
go generate ./...
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_freebsd_amd64 -ldflags "-X go.opentelemetry.io/collector/internal/version.GitHash=e12dee4c -X go.opentelemetry.io/collector/internal/version.Version=v0.19.0-13-ge12dee4c -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcol
# go.opentelemetry.io/collector/receiver/hostmetricsreceiver/internal/scraper/processesscraper
receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go:31:52: undefined: unixSystemSpecificMetricsLen
receiver/hostmetricsreceiver/internal/scraper/processesscraper/processes_scraper_unix.go:43:2: undefined: appendUnixSystemSpecificProcessesMetrics
make: *** [otelcol] Error 2
```

**What version did you use?**
Version: `e12dee4c85377ba5bf4aea7136a8bc51efb3d8e5`

**Environment**
Go version: 1.15.7
GOOS=freebsd

**Comment by andrewhsu** [comment]
Talked about this at the collector sig mtg and @tigrannajaryan will post response

**Comment by tigrannajaryan** [comment]
Freebsd is not a supported platform. We will accept small PRs if they fix the build on Freebsd provided that the change does not complicate the maintenance of the officially supported platforms.

I want to make it clear that acceptance of patches that fix problems on unsupported platforms is not a commitment by maintainers to support the platform going forward.

**Comment by vibhavp** [comment]
@tigrannajaryan I understand. The PR I created for the fix doesn't add any new code, but simply renames an existing file to have a prefix that isn't a `GOOS` value. Given that the change is just a file rename, do I still need to sign a CLA?

**Comment by tigrannajaryan** [comment]
Yes, CLA is enforced, it is not possible to merge a PR without one.
