### ISSUE TITLE
Official documentation needs to be updated

### ISSUE THREAD

**Issue by 13667285528** [open-telemetry/opentelemetry-collector#2441]
**Failed to start the sample app**

Unable to properly execute 'make' command to generate bytecode file
[collector-getting-started](https://opentelemetry.io/docs/collector/getting-started/)

**command**
`$ git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd opentelemetry-collector; make otelcol; \
    go build examples/demo/app/main.go; ./main & pid1="$!"; \
    ./bin/otelcol_$(go env GOOS)_$(go env GOARCH) --config ./examples/local/otel-config.yaml; kill $pid1`

**error info** 
`receiver/hostmetricsreceiver/codegen.go:17: running "mdatagen": exec: "mdatagen": executable file not found in $PATH
service/internal/gen.go:17: running "esc": exec: "esc": executable file not found in $PATH
make: *** [otelcol] 错误 1`

**Comment by flands** [comment]
Hmm, I think the issue is with the build:

```
make otelcol
go generate ./...
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_darwin_amd64 -ldflags "-X go.opentelemetry.io/collector/internal/version.GitHash=b06922fa -X go.opentelemetry.io/collector/internal/version.Version=v0.19.0-15-gb06922fa -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcol
# go.opentelemetry.io/collector/receiver/hostmetricsreceiver/internal/metadata
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:130:10: metric.InitEmpty undefined (type pdata.Metric has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:136:8: data.InitEmpty undefined (type pdata.DoubleGauge has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:145:10: metric.InitEmpty undefined (type pdata.Metric has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:151:8: data.InitEmpty undefined (type pdata.DoubleGauge has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:160:10: metric.InitEmpty undefined (type pdata.Metric has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:166:8: data.InitEmpty undefined (type pdata.DoubleGauge has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:175:10: metric.InitEmpty undefined (type pdata.Metric has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:181:8: data.InitEmpty undefined (type pdata.DoubleSum has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:192:10: metric.InitEmpty undefined (type pdata.Metric has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:198:8: data.InitEmpty undefined (type pdata.IntSum has no field or method InitEmpty)
receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go:198:8: too many errors
make: *** [otelcol] Error 2
```

@tigrannajaryan @jrcamp is local/refresh build working for you?

**Comment by tigrannajaryan** [comment]
This sequence works for me (cloning to a new directory):

```
git clone git@github.com:open-telemetry/opentelemetry-collector.git
cd opentelemetry-collector
make otelcol
```

No error messages. I do not have a clean machine to try.

Can you try `make install-tools` before `make otelcol` and see if it helps?

**Comment by mwear** [comment]
I'm running into to the same problem. Running `make install-tools` first does not fix it.

**Comment by mwear** [comment]
I was able to solve this on my machine. I don't have a `GOBIN` environment variable set and I noticed that `make install-tools` installs `mdatagen` in `$HOME/go/bin`, which I'm guessing is derived off my `GOPATH`. Adding it to my path  (`export PATH=$PATH:$HOME/go/bin`) fixed this for me.

**Comment by flands** [comment]
Confirmed, this worked. @13667285528 please file against open-telemetry/opentelemetry.io repo and adding `make install-tools` does appear to resolve the issue.
