### ISSUE TITLE
Clarify the effect of shutdown on processors

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/opentelemetry-collector#2443]
**Is your feature request related to a problem? Please describe.**
It isn't clear what the shutdown does when called in processors. The current description says:

```go
// Shutdown is invoked during service shutdown.
//
// If there are any background operations running by the component they must be aborted as soon as possible.
// Remember that if you started any long-running background operation from the Start() method that operation
// must be also cancelled.

func Shutdown (ctx context.Context) error
```

While this is correct, it is very open to what a processor should do when the Shutdown call happens, e.g. in `batcherprocessor`, a call to shutdown will drain the buffer but that isn't required from the description because "cancelling a long-running background operation" is not the same as "complete as it is".

**Describe the solution you'd like**
I'd like the description of the method to be clear about what batching-like processors should do with the holding data.

**Describe alternatives you've considered**
Introduce a optional `Flusher` interface that would make explicit the flush so you can call it before the shutdown:

```go
type Flusher interface {
    Flush(ctx context.Context) error
}
```

The context would allow use to introduce a deadline for the flush in case we are in a need to limit the time.

**Comment by bogdandrutu** [comment]
Agreed that extra documentation about clearing the internal buffers and sending data to the next component would be a good addition. Would you mind doing that?

**Comment by jcchavezs** [comment]
Sure I can do that.

**Comment by jcchavezs** [comment]
Done https://github.com/open-telemetry/opentelemetry-collector/pull/2480

**Comment by bogdandrutu** [comment]
@jcchavezs I think this is done per your comment :) Feel free to reopen

**Comment by jcchavezs** [comment]
Yes it is solved. Thank you!
