### ISSUE TITLE
Rotating TLS exporter kafka

### ISSUE THREAD

**Issue by owenhaynes** [open-telemetry/opentelemetry-collector#2456]
**Is your feature request related to a problem? Please describe.**
Our TLS certs for kafka are rotated every N days and connections will fail if the certs when this happens. 

**Describe the solution you'd like**
Certs are reloaded without downtime, it should be possible with setting up VerifyConnection && GetClientCertificate on tlsconfig, as this is how we rotate for our kafka consumers and publisher

**Comment by bogdandrutu** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-collector/issues/1591
