### ISSUE TITLE
Add 3rd-party LICENSE files to Docker Image distribution

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-collector#2458]
**Is your feature request related to a problem? Please describe.**
Many OSS licenses require re-distribution with said license.   E.g. the MIT licenses explicitly states:

`The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`

**Describe the solution you'd like**
We create a `licenses/` directory in the relevant distributed DOCKER files that contains all 3p licenses.

Ideally the following would work:

```
docker create --name="tmp_collector" otel/opentelemetry-collector
docker export tmp_collector | tar -x licenses
docker rm tmp_collector
cat licenses/*
```

(Note: I can submit a PR).

**Describe alternatives you've considered**
I didn't consider other alternatives to distributing the license. I guess you could encode it in the binary and dump it in logs at startup?

**Comment by jsuereth** [comment]
There are two tools I think could be really helpful here:

1. [Pivotal's license finder](https://github.com/pivotal/LicenseFinder)
   - It allows you to opt-in to copy-left license and approve/disallow any the community is uncomfortable with
   - It's highly configurable / flexible
   - It drops an "authorization" report on what decisions were made
   - Available as a docker image
2. [Google's go license finder](https://github.com/google/go-licenses)
  - Dead simple
  - Encodes google's notions of allowable licenses (we can ignore that feature)

**Comment by punya** [comment]
Is it worth broadening this issue to include tooling that collector distributions (i.e. bundling some set of out-of-tree plugins) can use to generate and bundle a valid LICENSE file?

**Comment by jrcamp** [comment]
@alolita

**Comment by jpkrohling** [comment]
As mentioned in the PR, this would be a great fit for the builder.
