### ISSUE TITLE
Support the `resource_to_telemetry_conversion` config option in OpenCensus exporter

### ISSUE THREAD

**Issue by serena7981** [open-telemetry/opentelemetry-collector#2465]
**Is your feature request related to a problem? Please describe.**
PR #2060 adds a new `resource_to_telemetry_conversion` configuration option to the `exporterhelper`. We would like this config option to be added to the OpenCensus exporter so that it can be enabled and our resource attributes can be added to our metric labels.

**Describe the solution you'd like**
Add the [`WithResourceToTelemetryConversion`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/common.go#L152) option to the OpenCensus exporter.

Similar solution to awsemf exporter in the collector contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1552

**Additional context**
I'm open to contributing to this FR if the proposal looks good to the maintainers.

**Comment by bogdandrutu** [comment]
OpenCensus has its own mechanism to propagate resources so no need to propagate resource attributes as labels

**Comment by jrcamp** [comment]
Please reopen if not addressed by previous comment.
