### ISSUE TITLE
Consider renaming package `oterr`

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#247]
See discussions: https://github.com/open-telemetry/opentelemetry-service/pull/191#issuecomment-514432106 and https://github.com/open-telemetry/opentelemetry-service/pull/239#discussion_r312013149.

**Comment by flands** [comment]
I am tempted to close this -- @songy23 @tigrannajaryan thoughts?

**Comment by tigrannajaryan** [comment]
I'd vote to close, since we haven't been able to come up with anything better.
