### ISSUE TITLE
 Review and improve consumererror package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2476]
This is an umbrella issue for feedback and improvements for the `consumererror` package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.20.0/consumer/consumererror

**Comment by alolita** [comment]
@Aneurysm9 will review the Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.22.0/consumer/consumererror and make recommendations.

**Comment by Aneurysm9** [comment]
Fixed in #2768
