### ISSUE TITLE
Clarify whether processors should accept data or not after shutdown

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/opentelemetry-collector#2481]
**Is your feature request related to a problem? Please describe.**
Currently the documentation on components don't clarify whether the component should/shouldn't continue accepting data after the Shutdown has been called. This is specially misleading on those cases you want to control the component lifecycle but also want to make sure zero data loss.

**Describe the solution you'd like**
Component documentation makes it clear that it should not accept more data after the shutdown method has been called.

Ping @bogdandrutu

**Comment by bogdandrutu** [comment]
Right now it is guaranteed by the framework that components will not receive data after shutdown, so I don't think we should do anything in the components to protect for that, but maybe we can document this guarantee.
