### ISSUE TITLE
Cleanup manually/automatic generated class in pdata related to trace

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2488]
This is a preparation for pdata (TraceID, SpanID, AttributeValue, AttributeMap) to be marked as stable API.

- [x] Cleanup translator code to work only with pdata types (TraceID, SpanID)
- [x] Should we consider to move translator code as helper to pdata (NewTraceIDFromLong, NewSpanIDFromLong, etc.). Translator code is in translator/trace/big_endian_converter?
- [x] Review public API for TraceID, SpanID - Punya
- [x] Review public API for AttributeValue and AttributeMap. 
  - [x] One thing that we should consider is to rename `ForEach` with `Range` to be consistent with `sync.Map`.
  - [x] Remove deprecated `NewAttributeValue`, needs changes in pdatagen which is the only user of this.
  - [x] Remove `InitEmptyWithCapacity` 
  - [x] Add `EnsureCapacity` (replacement for `InitEmptyWithCapacity`) that does not remove existing elements.
- [x] Review comments for all public API, maybe we have things to improve. - Punya
- [x] Review the `Resize` api for slices.
  - [x] MAY consider to replace the API with `EnsureCapacity` + `AppendEmpty` usage. Or `AppendEmptyN(int)`.
- [x] Remove deprecated `Resize` - Anthony
- [x] Remove deprecated `Append` api for slices. 
  - [x] Cleanup core usages of `pdata.Append`.
  - [x] Cleanup contrib usages of `pdata.Append`.
- [x] Consider to change StartTime/EndTime to StartTimestamp/EndTimestamp

**Comment by alolita** [comment]
@bogdandrutu can you assign @Aneurysm9 to this issue?

**Comment by alolita** [comment]
@bogdandrutu is this issue considered complete with @Aneurysm9 's PRs? Can we close this issue?

**Comment by bogdandrutu** [comment]
@alolita I have not seen any PR from @Aneurysm9 related to this, we discussed that this is a larger effort, see issue description

**Comment by alolita** [comment]
@bogdandrutu we're working on this - will sync up w @Aneurysm9

**Comment by bogdandrutu** [comment]
@alolita this is one of the blockers to finish Phase1 milestone.

**Comment by jpkrohling** [comment]
About "eliminate use of .Append", what's the reasoning? Callers now have to make two calls to have the same effect: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3861/files#diff-6211e1422cb9d2f03e84e85892a9a659a0d7d3d42de41cae0d130f63767d8a56L479-R482

**Comment by alolita** [comment]
@punya As we discussed assigning you the following reviews to help complete the tasks itemized in this issue.
1.  Review public API for TraceID, SpanID
2.  Review comments for all public API, maybe we have things to improve.

**Comment by alolita** [comment]
@Aneurysm9 do you have bandwidth to complete the last review and related PR for the changes. This would help us get all items in this issue done :-)
1. Review the Resize api for slices.
** You MAY consider replacing the API with EnsureCapacity + AppendEmpty usage. Or AppendEmptyN(int).

**Comment by Aneurysm9** [comment]
> @Aneurysm9 do you have bandwidth to complete the last review and related PR for the changes. This would help us get all items in this issue done :-)
> 
>     1. Review the Resize api for slices.
>        ** You MAY consider replacing the API with EnsureCapacity + AppendEmpty usage. Or AppendEmptyN(int).

I will get started on this.  

@bogdandrutu am I understanding correctly that we will remove the ability to resize a slice downward?  EnsureCapacity will only be able to increase the capacity of a slice.

**Comment by alolita** [comment]
@punya will you still be able to work on these reviews?

**Comment by punya** [comment]
@alolita yes (we discussed offline but I'm commenting here for the record).

**Comment by punya** [comment]
`AttributeValue.Equals()` has a [TODO](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/pdata/common.go#L304) for supporting map data types. Should this be considered a GA blocker?

**Comment by alolita** [comment]
Action Item: Remove deprecated Resize -- @Aneurysm9 please complete the removal of usage of Resize from contrib and definitions from core.

**Comment by alolita** [comment]
Thanks @Aneurysm9

**Comment by alolita** [comment]
@Aneurysm9 are there PRs in flight for collector changes for removing pdata slice Resize()?
