### ISSUE TITLE
Need a document that explains how auth works

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#2507]
I have a hard time understanding how the auth features work. Reading the code is difficult since it is scattered across multiple packages and I can't see high level explanations of how things work.

We need a design doc (preferably with a diagram that explains what happens with auth).

This is needed for Phase 1 GA since it is a public API.

**Comment by tigrannajaryan** [comment]
@jpkrohling since you added the auth capabilities can you work on this?

**Comment by gramidt** [comment]
@jpkrohling - I'm happy to help you with this if you would like.

**Comment by jpkrohling** [comment]
@gramidt, absolutely, if you have enough information about how it works, feel free to start a doc and I'll review it. There's a blog post that shows how it works from the perspective of end-users: https://medium.com/opentelemetry/securing-your-opentelemetry-collector-1a4f9fa5bd6f

**Comment by gramidt** [comment]
Awesome, thank you @jpkrohling!

**Comment by gramidt** [comment]
@tigrannajaryan @jpkrohling - Would it still be beneficial to still do this now or wait on 

https://github.com/open-telemetry/opentelemetry-collector/pull/2229#issuecomment-785929521

> Bogdan and I briefly discussed the auth in Collector and believe that there need to be changes in how it is handled generally. I am not able to review this PR right now, but we will try to settle the auth before the GA.
> I am going to reopen this and remove the stale label and it is best to keep this PR as draft for now.
> I do not have an ETA on when exactly we can review this PR, we are going over GA-related items one by one and auth is on our list (though we don't yet know if we will have time to solve it by GA).

**Comment by tigrannajaryan** [comment]
If it is trivial to add a doc on how it works today then it is still beneficial even if it is temporary. If it is a lot of work then don't spend time on it since it may be changed.

**Comment by gramidt** [comment]
Sounds like a plan, @tigrannajaryan! The document should be rather trivial to create.

**Comment by pavankrish123** [comment]
@gramidt @jpkrohling - A humble request, kindly include documentation on how clients (exporters) can pass in authentication credentials (tokens, client credentials etc) as well along with the excellent content from @jpkrohling medium article which is deals with receiver side.

As of today, I believe exporters can only authenticate by directly embedding tokens in headers.  [OAuth2 client credentials workflow for http clients is submitted in #2464 (pending)]

Thanks,
Pavan

**Comment by jpkrohling** [comment]
>As of today, I believe exporters can only authenticate by directly embedding tokens in headers.

Mutual TLS is also possible.

**Comment by gramidt** [comment]
Quick update, I've been sick the past few days and plan to catch back up on my open-source commitments later this week.

**Comment by tonglil** [comment]
I'm exploring mTLS (mutual TLS) and seemed unable to use it with the OpenCensus receiver.
The receiver seems unable to receive any data when mTLS is configured.

Has anyone else given this a try?

**Comment by jpkrohling** [comment]
I thought I had an e2e test for this in a downstream distribution, but looks like I'm not using mTLS there. I can give it a try and report back.

**Comment by gramidt** [comment]
@jpkrohling - I would love to; however, I likely won't be able to prioritize it until the week after next due to some urgent priorities. If we need it sooner rather than later, it may be best for someone else to point on it and I can help review.

**Comment by jpkrohling** [comment]
@alolita, how soon do you need this by?

**Comment by alolita** [comment]
@jpkrohling May 31 - would that be doable? We're trying to fix as many issues as possible to get to 1.0 by 5/31.

**Comment by jpkrohling** [comment]
@gramidt, if you can't do it by May 24, let me know and I'll write something up by May 31.

**Comment by gramidt** [comment]
That timeline currently fits with my priorities and should be able to take this, @jpkrohling.

**Comment by alolita** [comment]
@gramidt any update on this issue? This is an issue needed for 1.0 :-)

**Comment by pavankrish123** [comment]
Hello @alolita I believe https://github.com/open-telemetry/opentelemetry.io/pull/605 is the documentation @jpkrohling is working on. As of today It is complete and is waiting on #3369 to be merged.

**Comment by jpkrohling** [comment]
Indeed, that's the doc I prepared that should address this one. I'm closing this issue, but feel free to reopen if you think something is missing.
