### ISSUE TITLE
Delete configauth/context.go

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#2510]
It is a public API but does not appear to be used anywhere in core or contrib.

Need to delete or actually use.

**Comment by tigrannajaryan** [comment]
@jpkrohling can you help me understand what for is this? oidcAuthenticator seems to set groupsKey/subjectKey in the context but no-one appears to read it.

**Comment by jpkrohling** [comment]
The idea is to use it in other components that would use the subject to make decisions. For instance, the routing processor could use the subject key to route the spans to a tenant-specific backend. This last piece is missing, as I couldn't work on it yet.

**Comment by bhautikpip** [comment]
@jpkrohling @tigrannajaryan What are the next steps for this issue? Do we want to continue having these public APIs?

**Comment by tigrannajaryan** [comment]
context.go was deleted in https://github.com/open-telemetry/opentelemetry-collector/pull/2767
