### ISSUE TITLE
OTLP exporter endpoint config should require scheme

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-collector#2539]
Running collector version 0.20.0 configured to use the OTLP exporter as follows:

```yaml
exporters:
  otlp:
    endpoint: https://my-otlp-endpoint:4317/
```

I get the following error `address https://my-oltp-endpoint:4317/: too many colons in address`

```shell
INFO    exporterhelper/queued_retry.go:276
Exporting failed. Will retry the request after interval.
{
    "component_kind": "exporter",
    "component_type": "otlp",
    "component_name": "otlp",
    "error": "failed to push trace data via OTLP exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address https://my-otlp-endpoint:4317/: too many colons in address\"",
    "interval": "23.404886645s"
}
```

This [comment](https://github.com/open-telemetry/opentelemetry-collector/issues/1602#issuecomment-768675715) seems to suggest that including `https:` in the `endpoint` configuration is how to enable things to use default TLS settings.

**Comment by vmihailenco** [comment]
I am also interested in this. I've proposed a solution for opentelemetry-go in https://github.com/open-telemetry/opentelemetry-go/issues/1584

**Comment by alanwest** [comment]
@vmihailenco Ah interesting, I was under the impression that the collector already used system certificates by default. I guess this is not the case.

**Comment by tigrannajaryan** [comment]
otlp exporter is not an http exporter. The endpoint is not supposed to be a URL, it is a hostname:port.

**Comment by alanwest** [comment]
@tigrannajaryan Hi, sorry for delay. I'm interested in learning a bit more regarding your comment [here](https://github.com/open-telemetry/opentelemetry-collector/pull/2601#issuecomment-791620428).

Specifically:

> This paragraph in the spec is incorrectly worded. URL is non intended to be overridable in OTLP/gRPC. I don't think any implementation does and the protocol specification does not say that it is allowed or possible.

Regarding language implementations, I know that both Java and .NET both require a scheme even for OTLP/gRPC.

* [Java](https://github.com/open-telemetry/opentelemetry-java/blob/43f1ecf7ede49104c2aac1c9e5448b7cf7859ce7/exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L88)
* [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpTraceExporter.cs#L80)

The scheme is used to determine whether a secure (with default TLS config) or an insecure channel will be established. Currently, the OTLP exporter spec does not define a `insecure=[true|false]` configuration option like in the collector.

Even though this is the collector, it seems like it would be ideal that its OTLP exporter was aligned with the other implementations. To your point, this is something that needs to be clarified with the spec.

**Comment by alolita** [comment]
@tigrannajaryan is this bug fix needed for GA? else we can move it to the Phase 3 backlog. Please advise.

**Comment by tigrannajaryan** [comment]
Not a must have. We can fix it after GA and if we want to be very careful we can do fix it in a backward compatible way.

**Comment by bogdandrutu** [comment]
I would say if this is marked as a bug we should treat it with high priority and fix it, if that is not the case we should change it as feature improvement etc. not as a bug.

**Comment by alolita** [comment]
Let's discuss in the next SIG meeting and finalize a decision.

**Comment by alolita** [comment]
Action Item from Collector SIG 5/19: @alanwest please provide more details on how to replicate this issue. Can you file a PR for a fix? Thx.

**Comment by alanwest** [comment]
@alolita I'm not sure any more details are required. The collector currently cannot be configured with an endpoint that includes a scheme (i.e., `https` in this example):

```yaml
exporters:
  otlp:
    endpoint: https://my-otlp-endpoint:4317/
```

This differs from the implementation for configuring the OTLP exporters of some of the language SDKs. It also differs from what the specification for the OTLP exporter requires.

I'd be happy to submit a PR if the decision was made to conform the collector to the specification. Also, @tigrannajaryan posed the idea of doing this in a backwards compatible way. Was there any decision made about this?

**Comment by alanwest** [comment]
I'll join the 5/26 SIG this week to clarify with y'all what direction to go with this issue.

**Comment by alolita** [comment]
Thanks @alanwest 

@jrcamp @anuraaga @Aneurysm9 can you please help review? Ty!

**Comment by mxiamxia** [comment]
It looks with this proposal we'll going to apply the changes to SDKs and Collector. (if it is approved and merged)

@alanwest, will you be able to continue work on the changes in collector side?  It seems we need to fix the endpoint colons check error in the collector. Although I think it is not a OTel v1.0 blocker since there is no breaking change.

**Comment by alolita** [comment]
@alanwest do you have an update on this work? We will revisit this issue next week if we don't see a response from you.

**Comment by alanwest** [comment]
Yes sorry just back from a week off and catching up with things...

I can make the changes in the collector though it may be a week or two before I can get to it. I'm on board with doing this work in a backwards compatible way so I agree that this should not be a blocker for v1.0 - though, let me know if others share a different opinion.

@alolita @mxiamxia

**Comment by alolita** [comment]
Hi @alanwest thanks for responding. We're trying to complete all the changes in this milestone by July 16. Would you have time to work on this in a week? :-)

**Comment by alolita** [comment]
@bogdandrutu can you please take a look? Ty :-)

**Comment by alolita** [comment]
@tigrannajaryan @bogdandrutu can this issue be considered complete and be closed? Please advise.

**Comment by tigrannajaryan** [comment]
Yes, https://github.com/open-telemetry/opentelemetry-collector/pull/3575 completes this.
