### ISSUE TITLE
Review and improve componenttest package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2540]
This is an umbrella issue for feedback and improvements for the componenttest package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.25.0/component/componenttest

**Comment by alolita** [comment]
@bogdandrutu please assign to @dhruv-vora thx

**Comment by bogdandrutu** [comment]
I need @dhruv-vora to comment on this PR since they are not a member of the org

**Comment by dhruv-vora** [comment]
Can you assign this issue to me?

**Comment by alolita** [comment]
@dhruv-vora can you update your PRs and resubmit?

**Comment by bogdandrutu** [comment]
I think we are good on this. Unless we find other problems this is done.
