### ISSUE TITLE
Add `Validate` to configmodels interfaces (e.g. configmodels.Processor)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2541]
In order for the collector to be able to verify the config without creating components we need to validate every config before calling `New` on the factory.

This way we can add a flag like "--dry-run" that verifies the configuration, also we can ensure that we fail fast, etc.

**Comment by alolita** [comment]
@bogdandrutu can you please assign @mxiamxia to this issue. I don't have rights to assign.

When the Collector is initialized, there is already basic configuration validation. Can you provide more detail on what else needs to be added for verification?

**Comment by bogdandrutu** [comment]
Few things here:
1. @mxiamxia is not part of opentelemetry org which you should fix :)
2. I am talking about adding this func to the `configmodels.[Receiver|Exporter|Processor|Extension]` so components can provide custom verification logic for their own config.

**Comment by alolita** [comment]
@mxiamxia See https://github.com/open-telemetry/opentelemetry-collector/issues/2597 too.
