### ISSUE TITLE
Propose a plan, and the necessary steps to get there for splitting core into multiple modules

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2542]
To ensure stability guarantees, and allow individual parts of the component to move independently we need to split the core repository into multiple gomodules.

Some documentation:
https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository

Goals:
We need to make sure we avoid the problem we have in contrib when importing packages that it is necessary to add an extra replace statement, also ensure that while developing we can make changes across packages easily (they build from head).

**Comment by bogdandrutu** [comment]
Extra thoughts:

* Investigate if splitting into smaller, more granular, modules is possible.
  * Define the modules schema, try to not break everyone.
  See [here](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository).
  * Investigate how can we release multiple golang modules from the same repo, without asking
  people that consume them to use a replace statement. See problem in contrib.
  * Investigate how to release test-only utils.

**Comment by bogdandrutu** [comment]
@punya can you document the decision based on the slack discussion?

**Comment by jpkrohling** [comment]
From my side, I can confirm that it is indeed possible to build a distribution with the builder even when multiple components are part of the same module. No changes are required to the builder to support that.

**Comment by bogdandrutu** [comment]
Thanks a lot @punya I will open two other issues to start discussing what receivers/processors/exporters to keep in core.
