### ISSUE TITLE
Write a version doc as per spec requirements

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2543]
See [version and stability document](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md).

From the document see the section:

> Each language implementation MUST take these versioning and stability requirements, and produce a language-specific document which details how these requirements will be met. This document SHALL be placed in the root of each repo and named VERSIONING.

**Comment by alolita** [comment]
@bogdandrutu is the current doc adequate or needs work for the Collector?

**Comment by bogdandrutu** [comment]
We need a document in the https://github.com/open-telemetry/opentelemetry-collector/tree/main/docs and specify:
1. Do we go for v1 before everything is stable? 
  a. If not how do we mark packages as stable?
  b. If yes how do we mark packages as experimental?
2. What are the guarantees that we provide for a stable package?
3. etc.

**Comment by alolita** [comment]
@Aneurysm9 please share any updates on related PRs :-)
