### ISSUE TITLE
Do we want to support custom tracing in the first stability phase?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2546]
If yes, we probably should consider moving to opentelemetry-go. We know we want to get rid of opencensus sooner than later.

**Comment by jpkrohling** [comment]
What's custom tracing here? Tracing of internal otelcol components?

**Comment by bogdandrutu** [comment]
Yes. I think this is part of obsreport stabilizing so I will close this at this moment.
