### ISSUE TITLE
Review and improve componenterror package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2547]
This is an umbrella issue for feedback and improvements for the componenterror package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.24.0/component/componenterror

**Comment by alolita** [comment]
Hi @bogdandrutu can you please assign this issue to @dhruv-vora - thanks!

**Comment by dhruv-vora** [comment]
Hi @bogdandrutu, could you elaborate which package this references to? There isn't a componenterror package present in the consumer

**Comment by gramidt** [comment]
@dhruv-vora - I believe @bogdandrutu meant the following:

https://github.com/open-telemetry/opentelemetry-collector/commits/main/component/componenterror

https://github.com/open-telemetry/opentelemetry-collector/tree/main/consumer/consumererror

Bogdan is out on vacation, so he won't be able to confirm until he returns.

**Comment by dhruv-vora** [comment]
Thanks @gramidt for this, I thought this too.

There was another issue for the consumererror package, that has already been closed [Review and improve consumererror package #2476](https://github.com/open-telemetry/opentelemetry-collector/issues/2476)

Also, the componenterror package contains only 1 file, so I am not sure what this references to
