### ISSUE TITLE
configgrpc.go should support more encoding/compressions

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-collector#2548]
**Is your feature request related to a problem? Please describe.**
Gzip is CPU intensive and offers less of a compression benefit than more modern compression like snappy or zstd

**Describe the solution you'd like**
https://github.com/mostynb/go-grpc-compression should be supported, not just gzip encoding, at https://github.com/open-telemetry/opentelemetry-collector/blob/68c5961f7bc2d8d55fd431ab07367fc16f8b26d0/config/configgrpc/configgrpc.go#L45

**Describe alternatives you've considered**
Do nothing, support gzip only

**Comment by hyunuk** [comment]
@alolita I can work on this issue!
