### ISSUE TITLE
Move custom unmarshaler to config instead of component factory

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2597]
Currently we have:

```golang
// ConfigUnmarshaler interface is an optional interface that if implemented by a Factory,
// the configuration loading system will use to unmarshal the config.
type ConfigUnmarshaler interface {
	// Unmarshal is a function that un-marshals a viper data into a config struct in a custom way.
	// componentViperSection *viper.Viper
	//   The config for this specific component. May be nil or empty if no config available.
	// intoCfg interface{}
	//   An empty interface wrapping a pointer to the config struct to unmarshal into.
	Unmarshal(componentViperSection *viper.Viper, intoCfg interface{}) error
}
```

It would be good to move this to the current `configmodels` and have this as an optional interface for the components configuration:

```golang
// ConfigUnmarshaler is an optional interface that if implemented by configmodels.Receiver/etc.,
// the configuration loading system will use to unmarshal the config.
type ConfigUnmarshaler interface {
	// Unmarshal is a function that un-marshals a viper data into a config struct in a custom way.
	// componentViperSection *viper.Viper
	//   An empty interface wrapping a pointer to the config struct to unmarshal into.
	Unmarshal(componentViperSection *viper.Viper) error
}
```

**Comment by mx-psi** [comment]
@bogdandrutu Would this mean removing `WithCustomUnmarshaler` from the `(receiver/exporter/...)helper`s?

Keeping it would mean that the factory config would be different from the `CreateDefaultConfig` config:

```go
func TestExample(t *testing.T) {
  factory := receiverhelper.NewFactory("example", CreateDefaultConfig, WithCustomUnmarshaler(someFunc))
  cfgFactory := factory.CreateDefaultConfig()
  cfgDefault := CreateDefaultConfig()

  // This would fail; `cfgFactory` needs to have the `Unmarshal` method, while `cfgDefault` doesn't have to
  assert.Equal(t, cfgFactory, cfgDefault)
}
```

I don't think we want that (makes things clumsy to test and it is a bit unexpected). We can move the custom unmarshaler to the config struct from each component instead, maybe creating a helper function to do this, something like
```go

type ReceiverCustom interface {
  configmodels.Receiver
  configmodels.ConfigUnmarshaler
}

func ReceiverConfigWithUnmarshaler(cfg configmodels.Receiver, unmarshaler configmodels.CustomUnmarshaler) configmodels.ReceiverCustom {
  // ...
}
```

Does that sound good?

**Comment by bogdandrutu** [comment]
The way I was thinking:

// In configmodels 
```
// Additional interface to be implemented by a configmodel ...
type ConfigUnmarshaler interface {
}

type Receiver interface {
}
```

// In confighelper, this way only configs that need the custom unmarshaler will use this.
// Reason to have options is because https://github.com/open-telemetry/opentelemetry-collector/issues/2541 needs to add also a Verify to the config.
```
func WithReceiverUnmarshaler(cfg configmodels.Receiver, unmarshaler configmodels.CustomUnmarshaler) Option {
  // ...
}

func NewReceiverConfig(cfg configmodels.Receiver, cfg Option...) configmodels.Receiver
```

But we can also add the `ConfigUnmarshaler` to all the configs and force them to use the helper, and if no option default is to unmarshal exact yaml, that way the logic of how to unmarshal is no longer in the config.Load but belongs to every config.

**Comment by mxiamxia** [comment]
@bogdandrutu @mx-psi , I sent draft PR and added the following 2 interfaces. Each Config should implement `CustomConfigOptions` and do configuration `cfg.validate()` in `config.Load`.
The Collector will be failed for the following when starting
* Config structure doesn't implement `CustomConfigOptions` interface
* Component `validate` failed in `config.Load`

```
// CustomConfigOptions defines the interfaces for configuration customization options
// Different custom interfaces can be added like CustomConfigValidator, CustomConfigUnmarshaller, etc.
type CustomConfigOptions interface {
	ConfigValidator
	// CustomConfigUnmarshaller
}
// ConfigValidator defines the interface for the custom configuration validation on each component
type ConfigValidator interface {
	Validate() error
}
```

Sorry, I didn't follow the discussion on helper part below. does it still need with my approach? 
```
func WithReceiverUnmarshaler(cfg configmodels.Receiver, unmarshaler configmodels.CustomUnmarshaler) Option {
  // ...
}

func NewReceiverConfig(cfg configmodels.Receiver, cfg Option...) configmodels.Receiver
```

**Comment by mx-psi** [comment]
I left some comments on your PR; I think your `ConfigValidator` interface should be optional; only components that need to do custom validation should implement the interface (the same thing should happen with unmarshaler).

I think the helper would still be useful when making the interface optional
