### ISSUE TITLE
Ensure semantic conventions are up to date

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2600]
We should build a tool or share a tool with opentelemetry-go for all semantic conventions.

/cc @MrAlias @punya

**Comment by bogdandrutu** [comment]
@MrAlias @punya so to understand there is no such thing :)) Maybe we should start talking about building this.

**Comment by MrAlias** [comment]
> @MrAlias @punya so to understand there is no such thing :)) Maybe we should start talking about building this.

Sure, I'm onboard. What does this entail? Should we schedule a meeting, or can it be done asynchronously here?

**Comment by MrAlias** [comment]
Currently we use the hand-crafted [`semconv`](https://github.com/open-telemetry/opentelemetry-go/tree/main/semconv) package to contain all the semantic conventions. There are some curated comments in there that help relate the semantic conventions to OTel Go implementation concepts. It would be ideal if the thing we build could preserve these types of comments.

**Comment by punya** [comment]
There are some existing tools that process the semconv yaml files: https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/README.md. It looks like they are already being used for Java codegen. @bogdandrutu were you thinking about extending that tooling with a new Jinja template, or building something else?

**Comment by alolita** [comment]
@rakyll are you looking at this - can you share your doc / thoughts here?

**Comment by rakyll** [comment]
There is a spec change related to this: https://github.com/open-telemetry/opentelemetry-specification/pull/1515

**Comment by bogdandrutu** [comment]
@Aneurysm9 I think we should share the generated semconv if go library has already this. We can do the following:

1. Rename the go-proto repo to go-shared and expose multiple modules there like:
  a. protos 
  b. semconv
  c. pdata (for collector and other users)
2. Change the vanity URL so we don't break the current proto package.

Otherwise we can ask for a different repo as well.

**Comment by MrAlias** [comment]
I like the idea of having a new repository dedicated to the `semconv` package. I'm in favor of something like `opentelemetry-semantic-conventions-go` being created to house the package and generation tooling and pointing at that with `go.opentelemetry.io/semconv`.

I think isolating the purpose of each repository (i.e. protos and semantic conventions) will promote cohesive and single-focused Go packages.

**Comment by alolita** [comment]
@Aneurysm9 - can you provide your recommendations used for the Go API/SDK which we can reuse here? Thx.

**Comment by Aneurysm9** [comment]
I'm with @MrAlias in thinking that a new repo with a new vanity URL would be the way to go.  I think the generation tooling we recently added to the Go repo can easily be moved elsewhere.  

The one problem I see that we'll need to work through is that the `semconv` package currently depends on the `attribute` package from the API as all of the conventions are defined as `attribute.Key`s or `attribute.KeyValue`s.  The `attribute` package has a dependency on an `internal` package, but it's just for a few conversion helpers that can easily be moved/duplicated.  Moving that package will cause a lot of churn, but probably less than the two times we've previously renamed it.

I've put this topic on the agenda for the Go SIG meeting today.

**Comment by MrAlias** [comment]
From the Go SIG:

Currently the `semconv` package represents the semantic conventions with our `attribute` package `KeyValue` type. Would it be okay to keep the generation in this type? Would the collector be okay transforming from these to the `pdata` format?

Would it make more sense to just move the generation code to a separate repo?

@bogdandrutu @tigrannajaryan

**Comment by alolita** [comment]
@MrAlias Having the generation code to a separate repo would help in both the Go library and the Collector being able to leverage the same package. @bogdandrutu had mentioned this strategy could be reused in the long run for all Go components.

**Comment by MrAlias** [comment]
> @MrAlias Having the generation code to a separate repo would help in both the Go library and the Collector being able to leverage the same package. @bogdandrutu had mentioned this strategy could be reused in the long run for all Go components.

I'm not sure I understand what is being said here.

I agree that unifying the location of shared code is a good idea.

Do we want to put the _generation_ code in the repository or the _generated_ code? If it is the _generated_ code, would the collector be okay with that code using `"go.opentelemetry.io/otel/attribute".KeyValue` type to represent the conventions?

**Comment by alolita** [comment]
Based on the Collector SIG discussion today, the Go library and Collector maintainers will sync to finalize next steps in setting up a common repo as proposed by @Aneurysm9 to reuse common packages between Go based code bases.

**Comment by alolita** [comment]
@bogdandrutu Have you signed off on all the items that need to be completed for this task? I can close the issue if you sign off. Thx.
