### ISSUE TITLE
Support port reuse when integrated as a library.

### ISSUE THREAD

**Issue by Diddaa** [open-telemetry/opentelemetry-collector#2607]
**Is your feature request related to a problem? Please describe.**
When integrate collector in an exist project, due to Security and maintenance requirements, we must reuse port used by extant project, e.g 9335.  But receiver always create new Listener, result in "address already in use" error. This problem is not same as #1256 .

**Describe the solution you'd like**
1. Add "muxListener net.Listener" to GRPC/HTTPSetting's field, ToListener method return muxListener if it is not nil, otherwise run current logic.
2. Add SetMuxListener(ml net.Listener) method to receiver/exporter config, createDefaultConfig will set this value to GRPC/HTTPSetting's field.

**Describe alternatives you've considered**
Ways can support custom muxListener setting:

- support interface ;

**Comment by bogdandrutu** [comment]
What receiver(s) are you trying to multiplex?

**Comment by Diddaa** [comment]
> What receiver(s) are you trying to multiplex?

otlp receiver

**Comment by pkositsyn** [comment]
I might be wrong, but SO_REUSEPORT solves the issue - https://github.com/open-telemetry/opentelemetry-collector/issues/2670

It allows many sockets on the same port. But the first socket on the port must also use this option, so it is necessary for external application to use this option as well

**Comment by bogdandrutu** [comment]
@alolita I think the action item for this phase is to ensure that we don't need API changes to support this. If we can do that then we can move this to phase3

**Comment by alolita** [comment]
@bogdandrutu we will take a look at the code to verify if API changes are needed or not and respond on this issue.

**Comment by bogdandrutu** [comment]
I think we can implement this later by adding an optional argument to these funcs. So postpone this for phase3.

**Comment by Saber-W** [comment]
Hi @Diddaa, can you please elaborate on what your need is? Also, please check out my proposal PR and see if it resolves your problem. Thanks!
