### ISSUE TITLE
Rename Stop*Receiver to Shutdown*Receiver

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#262]
Shutdown() is the naming convention as detailed in the [exporter spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-exporter.md)

To keep naming consistent, update the receiver interface to `Shutdown` from `Stop`
https://github.com/open-telemetry/opentelemetry-service/blob/master/receiver/receiver.go#L53
https://github.com/open-telemetry/opentelemetry-service/blob/master/receiver/receiver.go#L73

**Comment by tigrannajaryan** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/issues/477 for deeper refactoring proposal.
