### ISSUE TITLE
hostmetricsreceiver metadata.yaml missing label entries

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#2635]
Metrics that are emitted with labels should be declared, see for example:
https://github.com/open-telemetry/opentelemetry-collector/blob/3e5d49e6fab26eeac3d49fc53bfb9c4db60c7600/receiver/hostmetricsreceiver/metadata.yaml#L139

However metrics like `system.filesystem.usage` are missing labels entries even though the labels are described in the labels section.

**Comment by tigrannajaryan** [comment]
@asuresh4 is this resolved?

**Comment by asuresh4** [comment]
Yes, this has been addressed via #2662
