### ISSUE TITLE
Avoid exposing publicly constants in `obsreport_exporter.go`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2641]

**Comment by gunturaf** [comment]
@bogdandrutu so the constants here
https://github.com/open-telemetry/opentelemetry-collector/blob/c7e9b68f84bbe5ed9082f8d62c4b54c56dc3397a/obsreport/obsreport_exporter.go#L27-L45
should be changed to private?

**Comment by humivo** [comment]
Hey I can take on this issue as my first one.  So all this entails is to make the constants listed above not public?

**Comment by humivo** [comment]
@bogdandrutu @tigrannajaryan do you mind assigning this issue to me whenever you can!

**Comment by alolita** [comment]
@humivo - let's sync up on completing the rest of this issue.

**Comment by humivo** [comment]
@alolita Ok will do, seems like my PR get approved

**Comment by mxiamxia** [comment]
This issue is fixed by my PR #3253 !
