### ISSUE TITLE
Avoid exposing public APIs that uses opencensus in obsreport and obsreporttest

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2648]
We should not expose any public API that uses opencensus since we are planning to switch to OpenTelemetry

**Comment by mxiamxia** [comment]
List the all files under `obsreport` and `obsreporttest` and track the checking progress with checkboxes.

obsreport
 - [ ] doc.go
 - [ ] observability.go
 - [ ] obsreport.go
 - [ ] obsreport_exporter.go
 - [ ] obsreport_processor.go
 - [ ] obsreport_receiver.go
 - [ ] obsreport_scraper.go
 - [ ] obsreport_test.go
 - obsreporttest
     - [x] obsreporttest.go
     - [x] obsreporttest_test.go

**Findings**
Not find any public API directly uses OC yet

**Comment by mxiamxia** [comment]
This issue can be closed. /cc @alolita

**Comment by alolita** [comment]
This is completed. Thanks @mxiamxia
