### ISSUE TITLE
Change obsreport helpers for receiver to use the same pattern as Processor/Exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2649]
* Define a struct and helpers similar with `ProcessorObsReport` (it will be renamed to just `Processor`)

**Comment by lonewolf3739** [comment]
I can pick this up.

**Comment by bhautikpip** [comment]
@bogdandrutu I could not find similar name pattern any more in any of the file in `obsreport` package. I also checked `obsreport_receiver.go` for more sanity. I think PR https://github.com/open-telemetry/opentelemetry-collector/pull/2658 and https://github.com/open-telemetry/opentelemetry-collector/pull/2657 covered most of the change. Am I missing anything here?

**Comment by alolita** [comment]
@bogdandrutu is this still an open issue? Looks like the changes have already been made.

**Comment by bogdandrutu** [comment]
@bhautikpip those PRs are for exporters and processors, but for the Receiver/Scraper we have a completely different API that uses global functions instead of a per receiver object. So look at these APIs:
* Receiver https://github.com/open-telemetry/opentelemetry-collector/blob/main/obsreport/obsreport_receiver.go#L149
* Processor https://github.com/open-telemetry/opentelemetry-collector/blob/main/obsreport/obsreport_processor.go#L121

We need them to be consistent.

**Comment by alolita** [comment]
Pending PR #3327 to be merged.
