### ISSUE TITLE
Refine the Exporter interfaces

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#265]
1. There is a function Name()
defined here:
https://github.com/open-telemetry/opentelemetry-service/blob/master/exporter/exporter.go#L26-L27
However, it doesn't appear to be used anywhere other than tests. Is this a necessary method?

2. Should the Shutdown() function return an error or just log anything that might go wrong?
Alternatively, could the exporter_builder be required to handle these errors in a certain way.

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-service/pull/316 to fix/explain 1)

**Comment by bogdandrutu** [comment]
@ccaraman we fixed 1, please update the issue if for 2 more discussion is required.
