### ISSUE TITLE
Migrate code base to use "github.com/stretchr/testify/assert"

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#266]
Currently there are parts of the code base that still use the pattern
```
if <some property> != <expected property> {
  t.Fatalf("...")
}
```
Migrate these instances to use 
assert.* in place of this pattern.

**Comment by pjanotti** [comment]
It doesn't need to be done all at once, PRs doing it partially are helpful.

**Comment by huikang** [comment]
Hi, @ccaraman @pjanotti , I'd like to try working on this issue. If no one has taken it, please assign it to me. Thanks.

**Comment by tigrannajaryan** [comment]
@huikang assigned to you, thank you.

**Comment by ccaraman** [comment]
@huikang Let us know if you have any questions!
