### ISSUE TITLE
Transform ComponentDocs into a "command"

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2664]
Right now this is a test in `componenttest`, but it will be good to have this as a binary that we can run as standalone and limit the public API we expose.

This binary can take as flags the arguments needed in the current API.

**Comment by alolita** [comment]
@bogdandrutu can you please assign @mxiamxia to this issue - I don't have rights to assign. Thanks!

**Comment by bogdandrutu** [comment]
@mxiamxia before you apply to become member of the org can you comment something on this issue so I can assign to you?

**Comment by mxiamxia** [comment]
> @mxiamxia before you apply to become member of the org can you comment something on this issue so I can assign to you?

Thanks @bogdandrutu, sent the member request - https://github.com/open-telemetry/community/issues/677

**Comment by mxiamxia** [comment]
#2703

**Comment by mxiamxia** [comment]
Convert `CheckDocs` from `componenttest` to the standalone command tool and remove the checks from unit test in service module to minimize the exposed API.
- [x] Convert `CheckDocs` to binary command tool in Core repository, add it in `workflow` check and remove related check from unit test
- [ ] Import `CheckDocs` tool in Contrib repository, add it in `workflow` check and remove related check from unit test. (Will be done in separate PR)
- [ ] Delete `doc.go`, `docs.go` and `docs_test.go` files from `componenttest` in Core repository
