### ISSUE TITLE
Remove TChannel support from Jaeger Receiver

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#267]
See for context and path forward if required
https://github.com/open-telemetry/opentelemetry-service/pull/264#discussion_r314504172

**Comment by jpkrohling** [comment]
We might want to keep the receivers for a while and remove the legacy exporters. Most Jaeger Clients still can't send data via gRPC to the collector.

**Comment by pjanotti** [comment]
Thanks for the info @jpkrohling - let's keep this for later then.

**Comment by jpkrohling** [comment]
I think it's time to remove this already. We'll be removing TChannel soon from the collector, and we shouldn't have it here by then.

**Comment by pjanotti** [comment]
Let's create one on the contrib repo first so there will be a fallback for anyone that needs it (we did this for zipkin scribe).
