### ISSUE TITLE
Add SO_REUSEPORT socket option to net config.

### ISSUE THREAD

**Issue by pkositsyn** [open-telemetry/opentelemetry-collector#2670]
**Is your feature request related to a problem? Please describe.**
Whether the deployment is done via orchestrator like Kubernetes or not, the collector redeployment process includes old deployment socket shutdown and initialization of a new socket. In order to lose less incoming data it would be helpful to have an ability to bind server sockets to the same address and eventually accept all requests for connection, without a rejection window. This will allow to firstly run new deployment and only then shutdown the old one once the new instances are ready.

**Describe the solution you'd like**
Add additional confignet parameter and adjust `Dial` and `Listen` functions to create connections with SO_REUSEPORT socket option if applicable. This can be done via `net.ConfigListener` for TCP and IP.

By the way, UDP transport currently doesn't work for `NetAddr.Listen` due to `net.Listen` logic as there is no entity for UDP to implement `net.Listener` interface. In my opinion, this should be noted in documentation.

**Comment by pkositsyn** [comment]
Note that this socket option is completely orthogonal to this issue https://github.com/open-telemetry/opentelemetry-collector/issues/1256

**Comment by pkositsyn** [comment]
Let me demonstrate how it works

Firstly, change example config in `example/local/otel-config.yaml`:
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

```

Current behaviour:
```
% make otelcol
... (skipped output)
% ./bin/otelcol_darwin_amd64 --metrics-level=none --config=examples/local/otel-config.yaml &
...
2021-03-13T19:10:39.222+0300	info	service/service.go:267	Everything is ready. Begin running and processing data.
% ./bin/otelcol_darwin_amd64 --metrics-level=none --config=examples/local/otel-config.yaml &
Error: cannot setup pipelines: cannot start receivers: listen tcp 0.0.0.0:4317: bind: address already in use
2021/03/13 19:10:48 application run finished with error: cannot setup pipelines: cannot start receivers: listen tcp 0.0.0.0:4317: bind: address already in use
```

Behaviour with my example PR (works for unix systems):
% make otelcol
...
% ./bin/otelcol_darwin_amd64 --metrics-level=none --config=examples/local/otel-config.yaml &
...
2021-03-13T19:14:12.175+0300	info	service/service.go:267	Everything is ready. Begin running and processing data.
% ./bin/otelcol_darwin_amd64 --metrics-level=none --config=examples/local/otel-config.yaml &
...
2021-03-13T19:14:35.851+0300	info	service/service.go:267	Everything is ready. Begin running and processing data.
```

Then start sending data and first collector receives all of it
```
...
2021-03-13T19:20:57.740+0300	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 10}
...
```

When first collector is stopped, connection resets and binds to second collector
```
...
2021-03-13T19:21:02.768+0300	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 10}
...
```

What should be done to make it all work:

1. All components that have a listen socket should be configurable to use SO_REUSEPORT, via confignet I suppose (internal metrics as well)
2. Confignet structures should be extended with config parameter and `UDPAddr` structure should be added, because there is currently no way to create UDP server using it
3. Add socket option under build tags (this is unix only option)
4. Possibly add e2e test to verify the abovementioned scenario works well for unix
5. Decide, whether this option should be enabled or disabled by default. Note that socket cannot be bound to the port, where another socket is running without SO_REUSEADDR option. Anyway, I think that it should be disabled everywhere it is possible (might be very hard to make internal metrics configurable)

Would be nice to hear any thoughts, especially about internal metrics - they seem to be hardly configurable. And is it a good idea to ask to put flag in every component in config to make it work?

**Comment by jpkrohling** [comment]
That's a cool trick, I had no idea this was possible at all. This will be useful for the external configuration sources feature: https://docs.google.com/document/d/1jUfWCUgvXaWelZ81Ot2yprFWHyjdjMxvm75IdhCyaY8/edit#

cc @pjanotti
