### ISSUE TITLE
Move fluentbitextension to contrib and remove from core after

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2674]

**Comment by evkuzin** [comment]
As far as I can see nobody is working on this one. I'll take a look then

**Comment by paulosman** [comment]
@evkuzin just FYI, I'm working on something adjacent: https://github.com/open-telemetry/opentelemetry-collector/issues/2675 Looks like `fluentbitextension` may have a dependency on `fluentforwardreceiver`. I don't think the PRs will overlap, but I wanted to give you a heads up just in case :)

**Comment by alolita** [comment]
@bogdandrutu can this issue be closed. Is anything left to be done for this move?

**Comment by bogdandrutu** [comment]
Done.
