### ISSUE TITLE
Move ProcessorCapabilities to Consumer

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2678]
The current `ProcessorCapabilities` as defined is a property of any consumer and not only for Processors. Exporters may also mutate data (even though we did not allow that), for example we may provide helper consumers that can be appended in front of an exporter (e.g. what the Timeout helper that we have now in exporter helper better to implement the consumer interface, or resource to telemetry). This will allow users to share common parts of exporters/processors when a standalone processor is to heavy for a small functionality.

**Comment by alolita** [comment]
@Aneurysm9 will evaluate and do a sanity check.
