### ISSUE TITLE
Run gendependabot on CI

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#2704]
**Is your feature request related to a problem? Please describe.**
As seen in #2686, the dependabot configuration gets out of sync from time to time. It would then be beneficial to run the command in the CI and fail the build in case it reports changes.

**Describe the solution you'd like**
A new GitHub workflow running this make target, failing when changes were made by the script. Something like this:
https://github.com/jaegertracing/jaeger-operator/blob/d8fbe6c0fdc9d795ea1c6f1316f6882fe86f8e17/Makefile#L52-L55

**Comment by bryanuribe** [comment]
Is this still open/available? Would I be able to pick this up?
cc: @alolita

**Comment by jpkrohling** [comment]
I believe this is still open, but it would be better to take a look at the current workflows before start working on this.

**Comment by hyunuk** [comment]
@alolita I would like to work on this issue.

**Comment by alolita** [comment]
Completed. Closing issue.
