### ISSUE TITLE
Build and publish Docker container for Windows

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector#2715]
**Is your feature request related to a problem? Please describe.**
open-telemetry/opentelemetry-java-instrumentation wants to run a bench of smoke tests on Windows platform as well. We extensively use testcontainers and Docker images as part of our testing setup. Currently GitHub actions do not allow running Linux Docker images on Windows Server environment.

**Describe the solution you'd like**
This project provides Windows executable for the Collector and also Docker images for Linux platform. I would like to ask to also provide pre-built Windows docker images.

**Describe alternatives you've considered**
We currently are going to build our own Docker images to run Collector on Windows. But there is no sense for us to do it :)

**Comment by bogdandrutu** [comment]
Do you want to run the windows msi image there instead of docker?

**Comment by iNikem** [comment]
> Do you want to run the windows msi image there instead of docker? For the moment, until this is resolved

I don't :) For now it is easier for me to build my own docker images for Windows that are good enough for our test infra. I prefer to have the same test setup both for Linux and Windows and prefer not to run msi from Java test class.

**Comment by Jmorjsm** [comment]
I'm interested in picking this one up.

**Comment by astencel-sumo** [comment]
Closed in favor of https://github.com/open-telemetry/opentelemetry-collector-releases/issues/339.
