### ISSUE TITLE
OpenTelemetry Service Operator for Kubernetes

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#274]
As the setup of the OpenTelemetry Service might be complex, with a set of agents and collectors, it probably makes sense to create an Operator for Kubernetes. An additional advantage is that other Operators, such as the Jaeger Operator, might indirectly make use of this, by creating CRs based on the end-users requests.

**Comment by jpkrohling** [comment]
I can start working on this right away. I just need this issue to be assigned to me, and a new GitHub repository, probably under `open-telemetry/opentelemetry-operator`.

**Comment by tigrannajaryan** [comment]
@jpkrohling there is already an ongoing effort in this area (not yet captured in the issues here). You may want to sync with @owais to avoid duplicate work.

**Comment by jpkrohling** [comment]
Is it public already, or should we use this issue here to discuss it?

**Comment by pjanotti** [comment]
There was some misunderstanding here: what @owais has been investigating is about enriching telemetry data with k8s information, not a k8s Operator to facilitate management/deployment of the service.

**Comment by jpkrohling** [comment]
I'll go ahead with it then. @bogdandrutu, @SergeyKanzhelev, could any of you create a repository named `opentelemetry-operator` and concede me push rights?

**Comment by jpkrohling** [comment]
Future versions of the operator might manage more OpenTelemetry pieces, not only the service. Also, the code for the service might be big enough to deserve its own lifecycle/release scheme/dependencies/...

**Comment by jpkrohling** [comment]
I have started a new [operator project under my account](https://github.com/jpkrohling/opentelemetry-operator). Once I have an initial working version, I'll add a notice to this issue here and we can then decide if it fits this repository.

**Comment by jpkrohling** [comment]
An initial version of the operator is ready. It still can't deploy a production-quality `otelsvc`, but it is very close already to how the operator will look like.

@tigrannajaryan, @bogdandrutu: once the final repository is created, let me know and I'll send a PR. Until then, I'll keep working on it under my own account.

**Comment by tigrannajaryan** [comment]
>It still can't deploy a production-quality otelsvc

@jpkrohling is this due to some problem in otelsvc? If so please create an issue in this repo so that we can fix it.

>once the final repository is created, let me know and I'll send a PR. Until then, I'll keep working on it under my own account.

Thanks for your work. Based on Bogdan's suggestion this will need to wait until contrib org is setup. Until that when you feel that the operator is ready we (otelsvc maintainers) can review it and link to it from this repo.

**Comment by jpkrohling** [comment]
> is this due to some problem in otelsvc?

Not at all. It's more like it's missing features that I would expect from a production-grade operator, like opening the proper ports based on the configuration (ie, expose `14250` only when the receiver `jaeger-grpc` is used) or the ability to update/upgrade existing instances. It also lacks a `mode` property, to get the collector deployed as a `DaemonSet` (mode=agent). Currently, it's only being deployed as a `Deployment` (mode=collector).

The underlying `otelsvc` is using an image that I built and published under my Quay namespace, as the only image available seems to be under omnition's namespace, so, it would be nice to switch to an official image once that is available.

**Comment by jpkrohling** [comment]
I believe the OpenTelemetry Operator is now ready to be reviewed. It's currently located here:

https://github.com/jpkrohling/opentelemetry-operator/

If this is good enough for an initial release and contains no blockers, I would like to request a new repository either under the official organization (open-telemetry), or under a "-contrib" organization. I certainly prefer this to be part of the official organization.

cc @objectiser, @tigrannajaryan, @pjanotti, @bogdandrutu.

**Comment by jpkrohling** [comment]
ping @bogdandrutu, @SergeyKanzhelev

**Comment by songy23** [comment]
Consider putting the Operator under https://github.com/open-telemetry/opentelemetry-collector-contrib.

**Comment by jpkrohling** [comment]
@songy23 unfortunately, all the tooling around operators expect the operator to reside on its own repository. To me, it doesn't matter much under which organization it resides (open-telemetry, open-telemetry-contrib, ...), and I think the other people who will help me maintain it won't mind that much as well. 

The only thing that I think that would be beneficial is to have this operator close to the open-telemetry project, and not in some private account.

**Comment by jpkrohling** [comment]
As discussed yesterday in the SIG call, I would like to have the operator reviewed, with the goal of placing it under its own repository owned by SIG Collector, under some organization managed by the OpenTelemetry project.

As promised, here are the parts that are of interest for a first review:

1. current repository: https://github.com/jpkrohling/opentelemetry-operator
1. the boilerplate code was generated by the [operator-sdk](https://github.com/operator-framework/operator-sdk)
1. bootstrap code is located in [cmd/manager/main.go](https://github.com/jpkrohling/opentelemetry-operator/blob/master/cmd/manager/main.go), but that's pretty much all generated boilerplate
1. CRD is at [deploy/crds/opentelemetry.io_opentelemetrycollectors_crd.yaml](https://github.com/jpkrohling/opentelemetry-operator/blob/e3c6e1e45fcb3323cb2f6189c2c897ed45eb4cac/deploy/crds/opentelemetry.io_opentelemetrycollectors_crd.yaml#L1-L78) and an example is at [deploy/crds/simplest.yaml](https://github.com/jpkrohling/opentelemetry-operator/blob/e3c6e1e45fcb3323cb2f6189c2c897ed45eb4cac/deploy/crds/simplest.yaml#L1-L20)
1. reconciliation loop starts at [pkg/controller/opentelemetrycollector/reconcile.go](https://github.com/jpkrohling/opentelemetry-operator/blob/e3c6e1e45fcb3323cb2f6189c2c897ed45eb4cac/pkg/controller/opentelemetrycollector/reconcile.go#L75-L126). All sources in the same package deal with reconciliation of the objects required to build an OpenTelemetry Collector installation. 
1. The upgrade mechanism to migrate from one OpenTelemetry Collector to the next is located at [pkg/upgrade/upgrade.go](https://github.com/jpkrohling/opentelemetry-operator/blob/e3c6e1e45fcb3323cb2f6189c2c897ed45eb4cac/pkg/upgrade/upgrade.go#L16-L48).

**Comment by joe-elliott** [comment]
Overall this is looking really good.  I have run it in a local k8s environment successfully and have used it to operate an otel-collector.

I agree with @jpkrohling this belongs in its own repo regardless of the organization.

**Comment by jpkrohling** [comment]
Nice, thanks @joe-elliott! 

@tigrannajaryan, do you, or anyone else, want to review it as well before moving it off of my personal account?

**Comment by tigrannajaryan** [comment]
@jpkrohling I had a very cursory look and see that your repo already has an established CI and all the wiring for building is in place (which is good). If we wanted to move it to this or contrib repo we would need to make changes to the build process at least. I do not see good reasons why we would want to do that and why not keep it as a separate project.
I think a better approach would be to create a separate repo under open-telemetry org and move it there. 

@open-telemetry/technical-committee what do you think?

**Comment by owais** [comment]
@jpkrohling I took a quick look and LGTM. Since we now have the ability to build multiple distributions of the collector, would it make sense to add a field that allows to specify which build/distribution of Otel the operator should use?

We already have core, contrib and omnition distributions. I think Google has one they use internally as well. May be we can we add a `docker_image` or `docker_repo` field that allows fetching the image from a custom source? Also would be nice if the config allows to pin to a specific version of collector. 

So may be something like:


```
$ kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  docker_image: custom-registry/image:tagname
spec:
  config: |
    receivers:
      jaeger:

    processors:
      queued-retry:

    exporters:
      logging:

    pipelines:
      traces:
        receivers: [jaeger]
        processors: [queued-retry]
        exporters: [logging]
EOF
```

**Comment by objectiser** [comment]
@owais This can be done now:
```
$ kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: custom-registry/image:tagname
  config: |
    receivers:
      jaeger:

    processors:
      queued-retry:

    exporters:
      logging:

    pipelines:
      traces:
        receivers: [jaeger]
        processors: [queued-retry]
        exporters: [logging]
EOF
```

**Comment by owais** [comment]
Great. Overall LGTM. I'll try it out on a local cluster today and share any feedback here.

**Comment by jpkrohling** [comment]
Any further feedback on this?

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee please post your thoughts on this. If you agree with what I wrote in my previous comment please create a repo for the operator.

**Comment by jpkrohling** [comment]
@bogdandrutu, @SergeyKanzhelev, @carlosalberto, @yurishkuro, could any of you please create the repository if there are no objections?

**Comment by yurishkuro** [comment]
Created https://github.com/open-telemetry/opentelemetry-operator

@jpkrohling you're an admin for now (https://github.com/open-telemetry/opentelemetry-operator/invitations), please finish the set up .

**Comment by jpkrohling** [comment]
Thanks @yurishkuro! I accepted the invitation and was able to push my repo there, but looks like I can't see the "Settings" tab, which is required to setup the CI tokens under the "Secrets" page.

![image](https://user-images.githubusercontent.com/13387/71158979-2bbb3b80-2245-11ea-86e2-5667dd17532a.png)

**Comment by yurishkuro** [comment]
for some reason you only had Write access, I just changed it to Admin.

**Comment by tigrannajaryan** [comment]
Closing, any further discussion can be done at https://github.com/open-telemetry/opentelemetry-operator
