### ISSUE TITLE
Error messages reported to the Windows Event Viewer are getting truncated

### ISSUE THREAD

**Issue by ekund** [open-telemetry/opentelemetry-collector#2756]
**Describe the bug**
When starting up the collector on Windows, there is an error message due to not being able to get hostmetrics for some pids.  The text of the error message is cut off so it is difficult to figure out what the actual problem is.

**Steps to reproduce**
Can be reproduced using a GCP Windows instance of windows-server-2019-dc-v20210112 image.
And installed using the GCP ops-agent instructions: http://cloud/stackdriver/docs/solutions/ops-agent/installation#agent-install-latest-windows

**What did you expect to see?**
An error message with clear indication of what went wrong.

**What did you see instead?**
A shorter error message:

```
{ "EventCategory": 0.0, "StringInserts": [ ... ], "SourceName": "google-cloud-ops-agent-opentelemetry-collector", "ComputerName": "test-20210316-c1c00-aa570a92-a2e6-49e6-b55a-547c6a529126", "EventID": 3.0, "TimeGenerated": "2021-03-17 19:28:45 +0000", "Channel": "Application", "TimeWritten": "2021-03-17 19:28:45 +0000", "Data": "", "Sid": "", "EventType": "Error", "Message": "Error scraping metrics

Stack Trace:
go.opentelemetry.io/collector/receiver/receiverhelper.(*scraperController).scrapeMetricsAndReport
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.15.0/receiver/receiverhelper/scrapercontroller.go:214
go.opentelemetry.io/collector/receiver/receiverhelper.(*scraperController).startScraping.func1
	C:/Users/ContainerAdministrator/go/pkg/mod/go.opentelemetry.io/collector@v0.15.0/receiver/receiverhelper/scrapercontroller.go:194
", "RecordNumber": 3058.0 } 
```
**What version did you use?**
v0.15.0

**What config did you use?**
Collected hostmetrics
```
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      swap:
      process:
```

**Environment**
OS:  GCP Windows instance of windows-server-2019-dc-v20210112 image.

**Additional context**
When forwarding logs to the Windows EventViewer, the Collector uses zap.Hooks ([link](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/service_windows.go#L126)). The actual error is embedded as a structured field, and this function doesn't allow access to structured fields ([link](https://github.com/uber-go/zap/blob/master/options.go#L55)). As per the comment on that function, we should migrate this code to use zapcore.RegisterHooks so we can access / report on all the structured fields as well.

**Comment by tigrannajaryan** [comment]
Not directly commenting on the PR change, but I did not know we are logging our logs to Event Viewer under Windows. Is this even desirable? AFAIK vast majority of Windows application simply log to log files. Do we think that Windows users prefer Event Viewer that what we do is warranted? I wonder if this is a wanted behavior by most of our users.
I just want to make sure we are not doing some weird thing and if we do just get rid of it and write to a text log like we do under other OS-es.

**Comment by tigrannajaryan** [comment]
Appears to be fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/3147

Re-open if anything else is needed or comment on https://github.com/open-telemetry/opentelemetry-collector/issues/3241
