### ISSUE TITLE
Health check extension `config should use Endpoint instead of Port

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#2764]
**Describe the bug**
Unlike the other extensions, the health check extension is using `Port` instead of `Endpoint`.

**Comment by bogdandrutu** [comment]
@dstdfx what is left on this is to make all other extensions use the helper net address

**Comment by dstdfx** [comment]
Wilco

**Comment by bogdandrutu** [comment]
This is resolved.
