### ISSUE TITLE
confighttp.go should support more encoding/compressions

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#2766]
**Is your feature request related to a problem? Please describe.**
Similarly as [#2548](https://github.com/open-telemetry/opentelemetry-collector/issues/2548), we would like to enable more compression capabilities for HTTP-based exporters

**Describe the solution you'd like**
Perhaps [PR #2614](https://github.com/open-telemetry/opentelemetry-collector/pull/2614) could be used as a base for this solution

**Comment by bogdandrutu** [comment]
@hyunuk do you want to pickup this as well?

**Comment by hyunuk** [comment]
For sure. I will take this issue.

**Comment by alolita** [comment]
Assigned to you @hyunuk

**Comment by alolita** [comment]
Completed.
