### ISSUE TITLE
Latest release does not have all assets

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector#2784]
[Previous release](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.22.0) has pre-built binaries for various platforms. [Latest release](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.23.0) does not have any binaries. Is it expected?

**Comment by bogdandrutu** [comment]
Fixed, the build failed for loadtest. now it is good.
