### ISSUE TITLE
Avoid duplicating With[Start|Shutdown] in exporterhelper

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2787]
Rather than needing to duplicate every `componenthelper.Option` here, might it be better to have something like this:

```go
func WithComponentOptions(opts componenthelper.Option...) Option {
  return func( o *baseSettings) {
    o.componentOptions = opts
  }
}
```

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/pull/2778#discussion_r600067388

**Comment by punya** [comment]
I tried to make this change, but saw that it saves a little bit of verbosity in the core in exchange for a lot of verbosity (and a module import) for every single processor. I would personally recommend leaving these convenience wrappers as-is.

**Comment by alolita** [comment]
@bogdandrutu can we close this issue given @punya's comments and closed PR?

**Comment by alolita** [comment]
@bogdandrutu should this issue be closed?
