### ISSUE TITLE
Avoid duplicating With[Start|Shutdown] in processorhelper

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2788]
Rather than needing to duplicate every `componenthelper.Option` here, might it be better to have something like this:

```go
func WithComponentOptions(opts componenthelper.Option...) Option {
  return func( o *baseSettings) {
    o.componentOptions = opts
  }
}
```

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/pull/2778#discussion_r600067388

**Comment by alolita** [comment]
@bogdandrutu can we close this issue given @punya's comments?

**Comment by alolita** [comment]
@bogdandrutu should this issue be closed?

**Comment by alolita** [comment]
This seems like a style-based decision. @Aneurysm9 had made a suggestion so @punya can we chat w Anthony and figure out the best practice in this case :-) ty!

**Comment by Aneurysm9** [comment]
I think @punya covered the pros/cons well in [this comment](https://github.com/open-telemetry/opentelemetry-collector/pull/2825#issuecomment-808500380).  The important question is probably whether/how often we expect to add new options that can benefit from this change.  If we don't, then maybe it's not worth it.  The value of the change goes up with each additional option that can utilize it. v0v

**Comment by punya** [comment]
We haven't added any more "generic" options like Start and Shutdown since the time this issue first came up. To me, that's decent evidence that we don't need to optimize for ease of adding future options of this sort.
