### ISSUE TITLE
Need receiverhelper to create resource object for convention-defined attributes

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#2805]
**Describe the bug**
Most protocols don't have a separate notion of resource attributes vs. record attributes. For example in the splunkhec{receiver,exporter} it doesn't use resource attributes at all but puts host, etc. into the log attributes. This means that if you use something like the resourcedetection processor it updates the resource attributes but the splunkhecreceiver may have put host.name in the log attributes.

Known impacted components are:

- [ ] fluentforwarder
- [ ] signalfxreceiver
- [ ] splunkhecreceiver

It seems we need some sort of helper to filter/group incoming attributes into Resource objects. It can use the attributes in the list from `conventions.GetResourceSemanticConventionAttributeNames()`. The only limitation I see is that if a user puts a non-convention attribute into resource, exports via splunkhecexporter to splunkhecreceiver it won't make the round-trip back into the resource.

**Comment by jrcamp** [comment]
Does prometheus have same issue?

**Comment by bogdandrutu** [comment]
@jrcamp not sure what a helper will do, every protocol has their own way to represent "record attributes". Maybe we can have a helper that accepts a function to retrieve and delete (possibly) "record attributes". But then I would ask what else is in the helper?

**Comment by jrcamp** [comment]
@bogdandrutu yes we will probably have to have some sort of generic interface that can be implemented since the record attributes will vary by protocol. The helper would group common runs of resource attributes. So for example let's say you had logs with log attributes that go:

host.id: i-1234
host.name: host-a

host.id: i-1234
host.name: host-a

host.id: i-7890
host.name: host-b

The output of the helper would be 2 resources. One resource (i-1234,host-a) with 2 entries and another resource with (i-7890, host-b) with 1 entry. You would have to identify common "runs" of identical resource groupings. 

Another option might be to extend https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor and have an option to pre-populate it with all otel resource attributes.

I will have to play with it to see if it's actually workable (assigning to myself).
