### ISSUE TITLE
Dockerhub: publish service releases under opentelemetry org

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#281]
There is an `opentelemetry` in dockerhub but we don't have the rights/access to publish under it. The `opentelemetry` org should be under the umbrella of CNCF. 

This issue tracks the steps and progress in this regard.

**Comment by tigrannajaryan** [comment]
@bogdandrutu do you know how this can be done or know who can help with this?

**Comment by pjanotti** [comment]
There is already an org https://hub.docker.com/u/opentelemetry hopefully it was created by someone participating on the project...

**Comment by pjanotti** [comment]
So far no success tracking the owner of https://hub.docker.com/u/opentelemetry

**Comment by lizthegrey** [comment]
It sounds like we now have a repo, so we should change over the CI to release there, yeah?

**Comment by aheadmode** [comment]
@pjanotti did you contact legal@docker.com?

**Comment by tigrannajaryan** [comment]
We contacted Docker but was unable to resolve this.
We are now publishing official images to https://hub.docker.com/u/otel
Closing the issue as it has been decided that `otel` will be the official org.
