### ISSUE TITLE
Track @Aneurysm9 interest and contributions for approver

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#2820]
Hi @Aneurysm9,

This is a tracking issue to know if you are interested and have time to become approver for the collector repository. If yes please confirm here, and we should track contributions here to ensure when requirements are met we add you to the approver list.

**Comment by Aneurysm9** [comment]
I do have interest in, and time to, become an approver for the collector repository.  I'll start making notes of contributions on this issue.

**Comment by alolita** [comment]
Thank you @bogdandrutu

**Comment by Aneurysm9** [comment]
### Pull Requests created

Updated sample app to build re-usable container image (#2760)
Cleaned up `consumer/consumererror` package (#2768)
Fix Prometheus counter metric naming in PRW exporter (#2993)
Fix Prometheus receiver start timestamp adjustment logic (#3047)
API change detection (#3081)

### Pull Requests reviewed

Bump github.com/prometheus/prometheus (#3074)
Changed usage of ApplicationStartInfo to BinaryInfo (#3045)
exporter/prometheusremotewrite: add a Write-Ahead-Log (#3017)
Simplify the Prometheus remote write export (#2987)
Don't drop instance and job labels from the Prometheus receiver (#2964)
receiver/prometheus: propagate Prometheus.Debug error values into .Warn for easy display (#2906)
exporter/prometheusexporter: support Summary (#2900)
Fix prometheusexporter droping the OTEL resource labels (#2899)
Add job and instance as well-known labels in prometheus receiver (#2897)
Change constants in obsreport_exporter.go to private and add getter methods (#2895)
Start fixing lint errors, golangci-lint had bunch of linters disabled (#2786)
Use Option pattern for componenthelper (#2778)

**Comment by Aneurysm9** [comment]
### Pull Requests reviewed (-contrib)

\[metrics_transform_processor\] Add filtering capabilities matching metric label values for applying changes (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3201)
introduce aws container insights processor (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3265)
\[ resource generation processor\] add new processor skeleton and configuration examples (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3266)
\[extension/ecsobserver\] Add docker label based matcher (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3276)
AWSPrometheusRemoteWriteExporter - Add SDK and system information to User-Agent header (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3317)

**Comment by alolita** [comment]
@Aneurysm9 added as approver. Closing this resolved issue.
