### ISSUE TITLE
Update the attributes processor example to reflect its comment

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-collector#2843]
**Description:**
The comment and the `value` below don't match.

The comment looks more correct (based on it being `match_type: regexp`), but [it looks like the tests depend on the `value`](https://github.com/open-telemetry/opentelemetry-collector/pull/2702#issuecomment-804415172).

https://github.com/open-telemetry/opentelemetry-collector/blob/2dbc66cfc1588208506b2799678b889dd4d888d0/processor/attributesprocessor/testdata/config.yaml#L294-L297

**Comment by Saber-W** [comment]
I would like to pick up this one.
cc @alolita
