### ISSUE TITLE
Flaky `TestQueuedRetry_StopWhileWaiting`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#2883]
I got a flaky error on `TestQueuedRetry_StopWhileWaiting`:
```
=== RUN   TestQueuedRetry_StopWhileWaiting
    queued_retry_test.go:407: 
        	Error Trace:	queued_retry_test.go:407
        	            				queued_retry_test.go:139
        	Error:      	Condition never satisfied
        	Test:       	TestQueuedRetry_StopWhileWaiting
    queued_retry_test.go:461: 
        	Error Trace:	queued_retry_test.go:461
        	            				queued_retry_test.go:142
        	Error:      	Not equal: 
        	            	expected: int(2)
        	            	actual  : int64(0)
        	Test:       	TestQueuedRetry_StopWhileWaiting
--- FAIL: TestQueuedRetry_StopWhileWaiting (1.01s)

```

The job log is available [here](https://github.com/open-telemetry/opentelemetry-collector/pull/2867/checks?check_run_id=2252506384). 

It is possibly related to #2858, cc @dmitryax

**Comment by codeboten** [comment]
I was unable to repro the failure and it looks like the logs are no longer available. @mx-psi I propose we close this and re-open if it starts failing again, what do you think?

**Comment by mx-psi** [comment]
Sounds good, I haven't seen it in a while either. Closing...
