### ISSUE TITLE
prometheus receiver : external labels are not honored

### ISSUE THREAD

**Issue by vishiy** [open-telemetry/opentelemetry-collector#2904]
external lables specified in the global config are not flowing. Its hard to use re-labeling to add same label to every job.

**Comment by yeya24** [comment]
External labels are only used with remote storage (read and write) in Prometheus and it has nothing to do with the metrics scraping part.

**Comment by vishiy** [comment]
@yeya24 i did not say external labels are scraped. The point is , to be Prometheus compliant, external labels specified in Prometheus config should flow out of the receiver .

**Comment by rakyll** [comment]
The receiver has to do work to enable external_labels. The scrape manager is not populating the samples with external labels, we may need to manually add them based on the Prometheus configuration user has provided.

**Comment by rakyll** [comment]
One more thing to consider whether https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor is sufficient enough to replace the external labels support in the Prometheus remote write exporter.

**Comment by vishiy** [comment]
> One more thing to consider whether https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor is sufficient enough to replace the external labels support in the Prometheus remote write exporter.

ok. Attribute processor doesn't work for metric stream. Also, to be prometheus complaint, it would be easier to manufacture this in the receiver , rather than having this a pipeline settings , which is outside scrape settings.

**Comment by rakyll** [comment]
Agree that we should support it in the receiver config to be compatible with Prometheus.

**Comment by jmacd** [comment]
Does Prometheus make external labels available for target relabeling rules?

**Comment by vishiy** [comment]
> Does Prometheus make external labels available for target relabeling rules?

Don’t think so. From what I have seen so far, these are global labels that are ‘finally’ applied *if* there are no collisions (after applying all relabeling rules). If there are collisions, they are ineffective (meaning the external label values are not applied irrespective of honor label configuration)

**Comment by brian-brazil** [comment]
> (after applying all relabeling rules)

External labels are applied before `write_relabel_configs`.

**Comment by vishiy** [comment]
> > (after applying all relabeling rules)
> 
> External labels are applied before `write_relabel_configs`.

Thanks. Does that mean we can relabel external labels ?
