### ISSUE TITLE
TestBatchProcessorSpansDeliveredEnforceBatchSize test fails intermittently

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#2905]
Auto-generated report for `test` job build.

Link to failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74115

#### Test Failures
-  TestApplication_updateService
-  TestApplication_updateService/retire_service_ok_load_ok

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74231

#### Test Failures
-  TestBatchProcessorSpansDeliveredEnforceBatchSize

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74653

#### Test Failures
-  TestAccumulateSummary
-  TestAccumulateSummary/Summary_with_single_point/WithTimestamp
-  TestAccumulateSummary/Summary_with_single_point

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74750

#### Test Failures
-  TestDefaultReceivers
-  TestDefaultReceivers/jaeger

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74753

#### Test Failures
-  TestApplication_ReportError

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/74906

#### Test Failures
-  TestApplication_ReportError

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/75290

#### Test Failures
-  TestApplication_ReportError

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/76139

#### Test Failures
-  TestBatchProcessorSpansDeliveredEnforceBatchSize

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/76307

#### Test Failures
-  TestLogsReceiver_error

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/76778

#### Test Failures
-  TestLogsReceiver_error

**Comment by owais** [comment]
Link to latest failed build: https://circleci.com/gh/open-telemetry/opentelemetry-collector/77183

#### Test Failures
-  TestLogsReceiver_error

**Comment by alolita** [comment]
@owais is this fixed? Can we close this issue?

**Comment by codeboten** [comment]
Closing this for now, not currently seeing failures from the tests reported here.

**Comment by tigrannajaryan** [comment]
Failed again during the release: https://github.com/open-telemetry/opentelemetry-collector/runs/7219622539?check_suite_focus=true

**Comment by mx-psi** [comment]
Closing this again, it's been some time and we have not seen this happening
