### ISSUE TITLE
Add ability to pass config as an environment variable

### ISSUE THREAD

**Issue by pmatyjasek-sumo** [open-telemetry/opentelemetry-collector#2910]
**Is your feature request related to a problem? Please describe.**
To make OpenTelemetry collector easier to deploy in environments like a ECS Fargate I would like to suggest to add possibility to pass configuration file as an environment variable. Similar to solution that is provided in AWS Otel Distro implementation.

**Describe the solution you'd like**
It can be upstream from AWS Otel Distro:
https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/config/config_factory.go#L37

**Comment by bogdandrutu** [comment]
Done. Use `--config=env:MY_ENV_CONFIG_VAR_NAME`
