### ISSUE TITLE
Add CustomUnmarshaler to other config interfaces

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#292]
We can wait requests for it to be 100% sure that this is needed for other types, however, we currently have `CustomUnmarshaler` for the case of Prometheus receiver. It is generic enough that it can be moved higher in the hierarchy: it doesn't need to be specific to receivers. The downside is that in current implementation most types will need to implement it by just returning nil. OTOH if we delay and later find the need this will likely be a breaking change.

**Comment by tigrannajaryan** [comment]
This can be added in the future without breaking the existing interfaces by introducing a different interface (e.g. `CustomUnmarshalable`)
