### ISSUE TITLE
Move unused exporter check to config.go

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#294]
https://github.com/open-telemetry/opentelemetry-service/blob/master/service/builder/exporters_builder.go#L170-L177

Should be during config loading and validation
https://github.com/open-telemetry/opentelemetry-service/blob/master/config/config.go#L434-L452
That way when setupPipelines https://github.com/open-telemetry/opentelemetry-service/blob/master/service/service.go#L192 is creating the exporters it is expected to already have a valid and actionable configuration

**Comment by bogdandrutu** [comment]
I think this is done via a series of PRs that kind of achieved this. If I am missing something please reopen.
