### ISSUE TITLE
replace the protobuf dependencies from internal/data to https://github.com/open-telemetry/opentelemetry-proto-go

### ISSUE THREAD

**Issue by chenzhihao** [open-telemetry/opentelemetry-collector#2958]
**Is your feature request related to a problem? Please describe.**
Do we have a plan to replace the protobuf dependencies from [internal/data](https://github.com/open-telemetry/opentelemetry-collector/tree/main/internal/data) to https://github.com/open-telemetry/opentelemetry-proto-go?

**Describe the solution you'd like**
Similar to this PR https://github.com/open-telemetry/opentelemetry-go/pull/1713/files, migrate to use the centrally generated protobuf.

**Additional context**
 Reason for requesting this change:
- Would avoid the problem that Google and Gogo protocol buffer implementations emit warnings when you register the same protocol message name twice in some cases. (Similar issue: https://github.com/open-telemetry/opentelemetry-go/issues/1324.)
- As the go SDK has already migrated to https://github.com/open-telemetry/opentelemetry-proto-go, it would be more consistent for us to migrate the Golang codebase to use it as same.

If this request is legit and aligns with the roadmap I could help.

**Comment by bogdandrutu** [comment]
No we don't plan to do this sorry.

**Comment by alolita** [comment]
Closed issue since its a won't fix.
