### ISSUE TITLE
how can I use prometheus exporter based on prometheus consul sd?

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-collector#2983]
Does collector support this ability at present?

**Comment by rakyll** [comment]
The collector supports [consul_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). Please report any bugs if you see any.

**Comment by tydhot** [comment]
@rakyll Thanks you for your replay, I have found the https://github.com/open-telemetry/opentelemetry-collector/blob/03c7bf98f7edf6e578aac303e4d8b767f117541e/receiver/prometheusreceiver/testdata/config_sd.yaml that prometheus receiver is support to config the consul sd. 
But what I want to know is that if I want to use the prometheus exporter provided by collector to export metric into prometheus, can I config the consul url in collector's config file to make  my prometheus can just discovery the collector by consul?

**Comment by rakyll** [comment]
I'm not a consul user, so don't how how the consul discovery works on Prometheus. Think about the collector as a drop-in replacement for the Prometheus server and configure and run it like how you do it with Prometheus.

**Comment by tydhot** [comment]
Thanks!
