### ISSUE TITLE
Add support for a health route for each receiver endpoint

### ISSUE THREAD

**Issue by secat** [open-telemetry/opentelemetry-collector#3002]
When exposing an endpoint to the external world (by example using a cloud ELB), the health route must be configured on the same endpoint on which the traffic is sent.

Concrete example: if exposing the otlp http endpoint using port 55681 to a cloud ELB, if we configure the load balancer with a health route to "/", it will try to reach the endpoint on port 55681.

The health extensions is configured on an isolated endpoint, i.e. on port 13133, therefore unreachable by the ELB with the example above.

Would it be possible to have a `/health` route on each receiver endpoint and redirect the traffic to the health extension endpoint?

**Comment by rakyll** [comment]
Isn't ELB allowing custom targets?

```
$ aws elb configure-health-check --load-balancer-name my-load-balancer --health-check Target=HTTP: 13133/health,Interval=30,UnhealthyThreshold=2,HealthyThreshold=2,Timeout=3
```

**Comment by secat** [comment]
@rakyll on GCP with GKE, it is not possible to configure a different port for _health check_ with `ingress` resources using [gke container-native load balancing](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg).

It uses the pod `readinessProbe`  to configure the _health check_ and it assumes that it is on the same port on which the traffic is sent. When it is not the case, the readiness gate added by the GCP network endpoint group (neg) will never pass and the pod will get stuck in the `unready` state, therefore not receiving traffic.

**Comment by secat** [comment]
As a workaround, I could add a `proxy sidecar container` in front of the `opentelemetry-collector container`, but I wanted to avoid this solution.

```
                                  (opentelemetry-collector)
                                 +-------------------------+
                           +---> | 0.0.0.0:55681/v1/traces | (otlphttp endpoint)
    (proxy)                |     +-------------------------+
+--------------+           |
| 0.0.0.0:8080 | ----------+
+--------------+           |
                           |     +----------------+
                           +---> | 0.0.0.0:13133/ | (health endpoint)
                                 +----------------+
```

**Comment by rakyll** [comment]
The workaround introduces one more component to operate and is not pretty. I agree that we should consider supporting /health at the HTTP endpoint.

**Comment by AlexeiZenin** [comment]
Judging by the PR that was merged I believe this issue was not addressed. The OP asked if a modification could be made on the receiver endpoints not the separate health check endpoint.
