### ISSUE TITLE
Hostmetrics Receiver throws 'error reading process name' error for process scraper

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-collector#3004]
**Describe the bug**
I'm using the OTEL _contrib_ collector to collect host metrics from an Ubuntu machine. However, when I add the _process_ scraper to the _hostmetrics_ receiver config, it throws an _error reading process name ... permission denied_ error for seemingly every PID in my system.

I haven't specifically reproduced this with the _core_ collector but, since the issue is with the core _hostmetrics_ receiver, I assume the bug is present in the _core_ collector as well.

**Steps to reproduce**
- Assume root on the Ubuntu machine: `sudo -s`
- Download `v0.24.0` of the contrib collector deb file ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))
- Install contrib collector: `dpkg --install otel-contrib-collector_0.24.0_amd64.deb`
- Configure it to collect host metrics (specifically, process data) via the _hostmetrics_ receiver and _process_ scraper

**What did you expect to see?**
No errors

**What did you see instead?**
Every minute, an error message is generated complaining about _error reading process name ... permission denied_ for seemingly every PID on the machine:
> Apr 23 15:34:37 ip-10-249-29-79 otelcontribcol[...]: 2021-04-23T15:34:37.264-0400        error        scraperhelper/scrapercontroller.go:206        Error scraping metrics        {"kind": "receiver", "name": "hostmetrics", "error": "[error reading process name for pid 1: readlink /proc/1/exe: permission denied; error reading process name for pid 2: readlink /proc/2/exe: permission denied; error reading process name for pid 3: readlink /proc/3/exe: permission denied; ...]"}

**What version did you use?**
`v0.24.0` of the contrib collector ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))

**What config did you use?**
```
receivers:
  hostmetrics:
    collection_interval: 1m
    scrapers: 
      process:
...
```

**Environment**
OS: `Ubuntu 18.04`

**Additional context**
N/A

**Comment by Jammicus** [comment]
By default I was not able to duplicate this, however with some manual hacking I was.

To replicate this I removed the other users read permission from process 1. Eg `sudo chmod  u-r /proc/1/exe` This resulted in the following:


```
Apr 25 14:19:23 vagrant otelcontribcol[1912]: 2021-04-25T14:19:23.322Z        error        scraperhelper/scrapercontroller.go:206        Error scraping metrics        {"kind": "receiver", "name": "hostmetrics", "error": "[error reading process name for pid 1: readlink /proc/1/exe: permission denied; error reading process name for pid 2: readlink /proc/2/exe: permission denied; error reading process name for pid 4: readlink /proc/4/exe: .........
```


Removing that permission seemed to prevent all subsequent processes from being read. A few more debugging steps would be useful if you have time @pranavmarla:

1. Whats the permissions on process 1 for you? Can get this with `sudo ls -la /proc/1/exe`
2. What is the process name? Can get this with` sudo cat /proc/1/cmdline`, I suspect its /sbin/init
3. Is this system locked down/have any additional security added to it?

**Comment by pranavmarla** [comment]
Thanks @Jammicus ! I've added the info you requested below:

1. 
```
> sudo ls -la /proc/1/exe
lrwxrwxrwx 1 root root 0 Apr 26 17:32 /proc/1/exe -> /lib/systemd/systemd
```

2. 
```
> sudo cat /proc/1/cmdline
/sbin/init
```

3. This system is an AWS EC2 machine. I'm afraid I don't know if there has been any additional security added to it -- I personally haven't added any.
```
> uname -a
Linux ip-... 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Hope that helps -- let me know if you need any more info!

**Comment by Jammicus** [comment]
Thanks, managed to reproduce.

Otel user is trying to get information on processes that have been started by other users. If otel had any other processes started it would be the only one you see in the logs.

Switching to the root user instead of otel to run the service (Don't recommend doing this) kind of resolved this, though a new error message decided to show its face:

```
error reading process name for pid 2: readlink /proc/2/exe: no such file or directory;
```

Can also replicate by changing the otel user to have a login shell and trying to readlink the exe, which will return a non 0 exit code.


I suspect the original error is ultimately due to permissions, but I did notice that the  library in the collector used for this receiver  will just return an [error straight away](https://github.com/shirou/gopsutil/blob/539c0d52c022dd05770517674d4f0cd3eaa311da/process/process_linux.go#L651) compared to some which just continue what I suspect[ would be a permission error](https://github.com/shirou/gopsutil/blame/539c0d52c022dd05770517674d4f0cd3eaa311da/process/process_linux.go#L618). This makes me wonder if other metrics are throwing permission errors but are being hidden. 


Ideally you would not want to run the collector as the root user so I'm not sure what the best steps for this should be.  It should also be noted the EXE process in this library has not implemented  for OSX so might also cause problems for users on different machines: https://github.com/shirou/gopsutil/tree/539c0d52c022dd05770517674d4f0cd3eaa311da#process-class

**Comment by ajsaclayan** [comment]
Hi, is there a workaround for this? I'm experiencing this in a Windows environment as well.

**Comment by norbertwnuk** [comment]
I experience the same issue, the problem is related to inability to read /proc data for APP process(es) by OTEL binary (in other containers on the POD). All the attempts to make it working with `shareProcessNamespace`, `SYS_PTRACE`, `apparmor unconfined` failing, even `SYS_ADMIN` does not work on GKE. The same time I can access /proc data from console using the same account...

```
apiVersion: apps/v1
kind: Deployment
spec:
  ...
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/otel-collector: unconfined
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 0
      containers:
        - name: application
		  ...
        - name: otel-collector
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
```

```
"2021-07-14T17:28:18.721Z	ERROR	scraperhelper/scrapercontroller.go:206	Error scraping metrics	{"kind": "receiver", "name": "hostmetrics", "error": "[error reading process name for pid 1: readlink /proc/1/exe: permission denied; error reading username for process \"java\" (pid 7): user: unknown userid 185; error reading username for process \"/bin/bash\" (pid 192): user: unknown userid 185; error reading username for process \"otel-collector\" (pid 228): user: unknown userid 185]"}"
```

```
2021-07-14T17:33:51.858Z	ERROR	scraperhelper/scrapercontroller.go:206	Error scraping metrics	{"kind": "receiver", "name": "hostmetrics", "error": "error reading process name for pid 1: readlink /proc/1/exe: permission denied"}
```

```
[root@XXX]# readlink /proc/8/exe

/usr/lib/jvm/java-11-openjdk-11.0.10.0.9-4.el8_3.x86_64/bin/java
```

**Comment by yuryu** [comment]
Just adding a data point, this issue reproduces on Ubuntu 20.04 as well.

**Comment by quentinmit** [comment]
I think silently discarding all process scrape errors is the best option. There might be other cases (SELinux, AppArmor, containers, network filesystems, Windows kernel protections, etc.) that cause parts of a process's status to be unreadable. While a user might conceivably want to debug that, it happens on ~all systems for one reason or other so it shouldn't be part of anything that gets logged by default.

**Comment by qingling128** [comment]
+1 for mute the errors here (potentially with a flag guard like `mute_invalid_process_scraping_error: true` if needed): https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bb386a3b9e59691aa619a1fadb5db4ed56b7955d/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go#L147.

Braydon from our side is planning to send a PR. Will see what the community thinks.

**Comment by pranavmarla** [comment]
> Note that in Google Cloud, this is an expected/non-harmful error (though I think it should still be fixed):
> 
> > The following logs are examples of non-harmful log spam that you can safely ignore.
> > 
> > * Errors scraping metrics from pseudo-processes or restricted processes
> >   -- https://cloud.google.com/logging/docs/agent/ops-agent/troubleshooting#log-spam

FYI, above link no longer contains quoted info. Here's the updated link I found: https://github.com/open-telemetry/opentelemetry-collector/issues/3004

**Comment by lalithkumar1196** [comment]
how did you solve this error?
1. If i run as a otel user mean im getting, error reading process name for pid 1: readlink /proc/1/exe: permission denied;
2. If i run as a root user mean im getting, error reading process name for pid 1: readlink /proc/1/exe: no file or directory;

**Comment by quisse** [comment]
@lalithkumar1196 I'm experiencing the same thing

**Comment by lalithkumar1196** [comment]
@quisse i got a solution for that issue

**Comment by ifalex** [comment]
@lalithkumar1196 which?
