### ISSUE TITLE
Proposal: `Registry` Support

### ISSUE THREAD

**Issue by sincejune** [open-telemetry/opentelemetry-collector#3022]
**Is your feature request related to a problem? Please describe.**
Opentelemetry-Collector can either be pull-based or push-based at this time.
For receivers that are pull-based (e.g. `kafka` and `filelog` receivers), we actually need a `registry` file for them so that Opentelemetry-Collector can continue consuming data from the last stop.

**Comment by pmm-sumo** [comment]
This is in progress for `filelog` receiver. Related issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2947

**Comment by djaglowski** [comment]
Yes, `filelogreceiver` will make use of a [file_storage extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage), if configured as part of the service.

Any other component of the collector can do the same. You will need to enhance the component's Start method to check for a storage extension, and then make use of it. [Here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/stanza/storage.go) is where `filelogreceiver` checks for a storage extension.

**Comment by sincejune** [comment]
@djaglowski It looks great!
I can try to make a contribution to Kafka Receiver. But it looks like we need to move the [storage definition](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/storage/storage.go) into this repo? Thoughts?

**Comment by djaglowski** [comment]
@sincejune That is a good point. I believe there is a good chance the storage extension code may end up in this repo, but this will be up to the maintainers to decide. //cc @tigrannajaryan

**Comment by tigrannajaryan** [comment]
> @sincejune That is a good point. I believe there is a good chance the storage extension code may end up in this repo, but this will be up to the maintainers to decide. //cc @tigrannajaryan

Let's give a bit time for storage extension to be polished and stabilized in the contrib and then we will move it to this repo. It should like happen after the GA to avoid delaying the GA further.

**Comment by sincejune** [comment]
I just realized that Kafka had already stored offset information itself so we don't have to add supports particularly for that.
Closing this as we already have [filestorage](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage).
