### ISSUE TITLE
Jaegerreceiver drop the real process info of span, if span report from jaeger agent to opentelemtry collector

### ISSUE THREAD

**Issue by sunfuze** [open-telemetry/opentelemetry-collector#3024]
**Describe the bug**

Our system use jaeger to collect spans as follow pattern:

Applications ------> Jaeger Agent ---------> Jaeger Collector --------> Alibaba Cloud Log Service

We want change to 

Applications ------> Jaeger Agent ---------> Opentelemetry Collector --------> Alibaba Cloud Log Service

Alibaba Cloud Log Service provide a new log product for opentelemetry, so we want switch to use opentelemetry collector. Jaeger receiver translate jaeger spans to otlp spans, and use the process info from batch request for all spans in the batch request. it make all spans use the process info of the jaeger agent instead of the real process info of application.

https://github.com/open-telemetry/opentelemetry-collector/blob/1e1f24b462e58b141ce967f744aa60efeeb349c7/translator/trace/jaeger/jaegerproto_to_traces.go#L75-L89

https://github.com/open-telemetry/opentelemetry-collector/blob/1e1f24b462e58b141ce967f744aa60efeeb349c7/translator/trace/jaeger/jaegerproto_to_traces.go#L137-L158

**Steps to reproduce**
1. Application reporter spans to jaeger agent
2. Jaeger agent report spans to opentelemetry collector by jaegerreceiver

**What did you expect to see?**

Jaegerreceiver should keep the real process info of spans.

**What version did you use?**
Version: main

**Comment by bogdandrutu** [comment]
@jpkrohling if I read this correctly, there is a misunderstanding here. I think the batch process info should be the correct once, am I missing something?

**Comment by sunfuze** [comment]
> @jpkrohling if I read this correctly, there is a misunderstanding here. I think the batch process info should be the correct once, am I missing something?

I have misunderstood. Jaeger agent proxy batch to collector, so process in batch is process of spans.
