### ISSUE TITLE
Config: use "strict mode" to read config

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#303]
Instead of using `UnmarshalKey` to read config we could use `UnmarshalKeyExact` and avoid misconfiguration due to typos in the config. The main downside is that due to the factory interfaces one can always implement one component that doesn't follow this recommendation.

Creating this item to give full visibility and discussion before making any changes to the code.

**Comment by bogdandrutu** [comment]
@pjanotti not sure I understand the "downside", can you explain more?

**Comment by pjanotti** [comment]
@bogdandrutu the receivers can have a custom unmarshaler (it was needed by the Prometheus receiver) so we can't enforce the usage of `UnmarshalKeyExact` in that case, although we should recommend as guidance for implementers.

**Comment by pjanotti** [comment]
Adding to beta since changes in config may cause unexpected issues for customers.
