### ISSUE TITLE
component support custom metric view register

### ISSUE THREAD

**Issue by shilicqupt** [open-telemetry/opentelemetry-collector#3039]
**Is your feature request related to a problem? Please describe.**
- custom Component need more rich metric to reflect Component internal states, however appTelemetry only support limited component metric views(batchprocessor, kafkareceiver, ....), we need a solution to help custom component to define MetricView and add to appTelemetry

**Describe the solution you'd like**
- in appTelemetry.go add metric register solution

```golang
var customViews = make(map[string][]*view.View)

// RegisterCustomView registers component views.
func RegisterCustomView(typ string, customView []*view.View) {
	if _, ok := customViews[typ]; ok {
		panic(" typ exists:" + typ)
	}
	customViews[typ] = customView
}
```

**Describe alternatives you've considered**
- without register func, we need to modify the source code support

**Additional context**
- self health metric is very import to see collector state

**Comment by bogdandrutu** [comment]
OpenCensus is a singleton, you can do this for the moment in an `init` func and will work until we change to OpenTelemetry. Then we will give an explicit call.

**Comment by shilicqupt** [comment]
> OpenCensus is a singleton, you can do this for the moment in an `init` func and will work until we change to OpenTelemetry. Then we will give an explicit call.

what means change to OpenTelemetry?
