### ISSUE TITLE
Remove unnecessary locking in Start/Stop

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#3041]
Don't think this locking is needed is it? Starting and Stopping components get run in same goroutine so I assume memory ordering should be ok. I think most components depend on this memory consistency as well.

_Originally posted by @jrcamp in https://github.com/open-telemetry/opentelemetry-collector/pull/3037#discussion_r621670235_

**Comment by bhautikpip** [comment]
Fix for this issue https://github.com/open-telemetry/opentelemetry-collector/pull/3070 is merged so we can probably close out this issue.

**Comment by alolita** [comment]
@mxiamxia can you please check if there are other components that have this unnecessary mutex lock? Please comment on the issue with your findings?

This issue should not be a GA blocker.

**Comment by bogdandrutu** [comment]
@bhautikpip there are more places where that happens.
