### ISSUE TITLE
Review and improve component package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3049]
This is an umbrella issue for feedback and improvements for the component package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.26.0/component

Things that we should look for:
1. Can we avoid exposing publicly some of the APIs? Better to have less public APIs.
2. Can we improve the names of the public APIs?
3. Can we improve the documentation of the package/public APIs?

**Comment by alolita** [comment]
@bogdandrutu can this be closed - since PR #3015 has been merged.

**Comment by alolita** [comment]
@rakyll @mxiamxia does an overall description (doc.go) need to be added at the package level? See https://pkg.go.dev/go.opentelemetry.io/collector@v0.26.0/component

**Comment by alolita** [comment]
@bryanuribe is working on this issue.

**Comment by bryanuribe** [comment]
I'll take a look at this!

**Comment by alolita** [comment]
Please see https://github.com/open-telemetry/opentelemetry-collector/issues/2677 for more details on the component package.

**Comment by alolita** [comment]
Completed.
