### ISSUE TITLE
Test: create a test loading all core components

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#305]
We have a test to validate that the expected default set of configurable components is the expected one, however, we don't have one that ensure that all intended components are present. We need to add one, this will avoid issues like the one fixed by #304

**Comment by punya** [comment]
@jpkrohling will such a test still be appropriate when the components have been moved to a separate repo, and the "core distribution" will be defined by a config file?

**Comment by jpkrohling** [comment]
For this repository, this test would load only the OTLP components, which will still reside in this repo. But such a test is certainly more appropriate for the new "releases" repository.
