### ISSUE TITLE
Review and improve consumer package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3050]
This is an umbrella issue for feedback and improvements for the consumer package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.26.0/consumer

Things that we should look for:
1. Can we avoid exposing publicly some of the APIs? Better to have less public APIs.
2. Can we improve the names of the public APIs?
3. Can we improve the documentation of the package/public APIs?

**Comment by alolita** [comment]
Assigning to @mxiamxia

**Comment by alolita** [comment]
@eddieleelin is working in this issue.

**Comment by eddyleelin** [comment]
I'll take a look at this issue!
