### ISSUE TITLE
Review and improve config package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3051]
This is an umbrella issue for feedback and improvements for the config package.

Godoc: https://pkg.go.dev/go.opentelemetry.io/collector@v0.26.0/config

Things that we should look for:
1. Can we avoid exposing publicly some of the APIs? Better to have less public APIs.
2. Can we improve the names of the public APIs?
3. Can we improve the documentation of the package/public APIs?

**Comment by alolita** [comment]
@bogdandrutu can this be closed? The docs look good for the config package - see https://pkg.go.dev/go.opentelemetry.io/collector@v0.26.0/config
