### ISSUE TITLE
Refactor: create OTelSvc own health-check extension

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#307]
OTelSvc re-uses Jaeger Health-Check to report liveness and readiness. This is an HTTP endpoint that responds with proper status codes. While it works well it is standard code that can be implemented directly reducing the dependencies from external projects. This likely helps also in implementing common code for the extensions so less boilerplate code is required.

**Comment by pjanotti** [comment]
It can also switch the configuration of health-check from `port` to `endpoint` like the other core extensions.

**Comment by ccaraman** [comment]
Currently, the version of the jaeger pkg hc returns a 204 instead of a 200.

**Comment by rakyll** [comment]
This can be closed now, see https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/healthcheckextension.
