### ISSUE TITLE
Upgrade prometheus deps (core, common, etc)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3071]
Prometheus broke some of the APIs that we use, and we need to upgrade it in order to stay up to date with k8s and other transitive deps.

**Comment by bogdandrutu** [comment]
PR blocked by this https://github.com/open-telemetry/opentelemetry-collector/pull/3066

**Comment by bogdandrutu** [comment]
To upgrade prometheus `go get github.com/prometheus/prometheus@main` but will cause compilation issues because of breaking changes

**Comment by rakyll** [comment]
Sending a PR soon.
