### ISSUE TITLE
Refactor: lots of boilerplate code in extension implementations 

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#308]
After coding the 3 core extensions (health-check, pprof, zPages) it become clear that the code for them is very similar and can be refactored to reduced code repetition. The one that is slightly different is the health-check that is implemented using a package for Jaeger,  having an OTelSvc implementation for health-check (#307) can help having it using the same code pattern.

**Comment by bogdandrutu** [comment]
Obsolete, we have extensionhelper
