### ISSUE TITLE
Test: use dynamic endpoint/port even when reading config files

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#309]
Some tests, eg.: service_test.go, load configuration from an yaml file. Currently this forces the usage of fixed endpoint/ports which can be problematic in certain test environments that already use these ports (or if a system running the test also collects telemetry data). It will be helpful to have place holders that will trigger the replacement of hard coded endpoint/ports from the yaml.

**Comment by bogdandrutu** [comment]
you can use environment variables now https://github.com/open-telemetry/opentelemetry-service/pull/334 :)
