### ISSUE TITLE
Triager role request for @alolita

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3096]
Filing a formal request to request triager role for @alolita.

Reason for request: In my discussions with @bogdandrutu on the path forward to achieve 1.0 stability for the Collector and collector-contrib components and beyond, he suggested I help triage and prioritize P0, P1 and other issues and keep the Collector milestone backlogs current with development progress.

I participate very actively on the Collector, Spec and Metrics SIGS and fulfill all requirements for a triager role as stated in https://github.com/open-telemetry/community/blob/main/community-membership.md

@bogdandrutu please add me as a triager for the Collector and collector-contrib.

**Comment by SergeyKanzhelev** [comment]
Transferred to collector repo as it is for collector maintainers to approve
