### ISSUE TITLE
Stateful Collectors

### ISSUE THREAD

**Issue by tdinucci** [open-telemetry/opentelemetry-collector#3099]
**Is your feature request related to a problem? Please describe.**

When multiple Collectors are in play there is no great way perform operations which require knowledge of a specific telemetry stream.  This makes it hard to do the following:

* Perform tail-based sampling on traces
* Aggregate metrics
* Group logs so that they may be written efficiently to object stores
* etc.

**Describe the solution you'd like**

If **OpenTelemetry Collector WAL** (https://docs.google.com/document/d/1Y4vNthCGdYI61ezeAzL5dXWgiZ73y9eSjIDitk3zXsU) comes to fruition then we could obviously have more faith that if data is sent to a specific Collector that it will not be lost.  This opens some interesting doors:

* If Collectors are reliable then there would be limited risk in sending all data for a given telemetry stream to a specific Collector
* If a single Collector sees all data for a telemetry stream then it becomes possible to perform operations like those mentioned in the problem statement above

Ideally this could be achieved with OTel components alone, i.e. no additional dependencies.

Glossing over all of the complexity involved (not least the fact that a disk a WAL is written to could fail) this functionality could be delivered by a hash-ring of Collectors, where each Collector handles a specific subset of the telemetry data.

**Describe alternatives you've considered**

An external data store could be used as a short term buffer for all telemetry data.  Collectors could then read from this store and they would have access to all data for a particular telemetry stream covering a period of time.

Multiple types of data store could obviously be supported.  The major downsides to this approach however are operational complexity and cost.

**Additional context**

I understand that this is probably low on the list of priorities due to there being many more fundamental features still to be developed.  If this is something you would consider a contribution for, in terms of design and/or development I would be happy to discuss.

**Comment by bogdandrutu** [comment]
I would actually suggest to use something like "Kafka" receiver/exporter to persist the state and do routing.

**Comment by tdinucci** [comment]
Thanks @bogdandrutu, does this mean there are no plans to support something like this natively in OTel?

Kafka would obviously fit the requirement but it comes with quite a bit of additional overhead.

Are the points I raised in the problem statement not common requirements?

**Comment by danielgblanco** [comment]
Regarding tail-sampling (putting away other types of use cases for stateful collectors) there was a discussion on https://github.com/open-telemetry/opentelemetry-collector/issues/407 proposing hashrings as an option but it seems the `groupbytrace` processor combined with other sampling processors on two layers of collectors was a preferred option.

There is also some work proposed to deprecate tail-based sampling in favour of those processors in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1797

I think these work well for probabilistic or attribute sampling, and rate limiting, but not sure how that could work for Gaussian sampling for instance, as each collector would only see a subset of data. Having a central cache or a way to communicate short lived latency and error distributions for a particular span/service would make advanced tail sampling a possibility.

**Comment by bogdandrutu** [comment]
@tdinucci 

>Kafka would obviously fit the requirement but it comes with quite a bit of additional overhead.

I would love to understand the "additional overhead". I think writing to the disk vs writing to Kafka should be quite similar overhead (same order of magnitude). If possible to make a comparison it would be great.

> does this mean there are no plans to support something like this natively in OTel?

No I am saying that we should try to do data driven decisions, and if the WAL solution is significant better we should invest more into that. The simple WAL (just to ensure no data lost) will be supported anyway because we committed on that (when someone has time to write it).

**Comment by tdinucci** [comment]
The "additional overhead" I was referring to was more in relation to operational complexity and cost.  

Obviously running OTel components that are stateful and reliable would end up being complex and expensive too. However, I would like to think it would be simpler and cheaper than running both OTel and Kafka together.

I understand your position though and how you need more than this ticket to decide whether to tackle such an undertaking.

**Comment by bogdandrutu** [comment]
@tdinucci I would like to see a bit more of a diagram/high-level design of what you have in mind. Or work with someone to make that. It would be interesting to see what alternative (rather than Kafka) we have and make a decision.

I want also to say that please don't spend more than 1/2 day on this, since it is just a preliminary discussion :)

**Comment by tdinucci** [comment]
@bogdandrutu - here's a quick HLD with what's in my mind.

## Collector ring

A number of Collectors would form a hash ring and communicate between themselves to route data that is sent to the ring.  This means that a dumb load balancer can sit in front of the ring and blindly send data to an arbitrary Collector.

The main benefits of a hash ring here over an "intelligent" load balancer is:
* rings are more tolerant to changes in the number of servers (esp. useful if using k8s HPA) - https://en.wikipedia.org/wiki/Consistent_hashing#Basic_Technique
* there are fewer complex component types in the architecture

There are a number of things to consider here, leading to differing degrees of complexity, e.g:
* data could be replicated across multiple Collectors in the ring to cater for a single collector going down
* how would the ring react to Collectors being added/removed - e.g. would data just be pushed to final destination or migrate between Collectors
* if Collectors write to a WAL then how would would we handle a Collector going offline for a period of time (taking into account the above points)
* etc.

![image](https://user-images.githubusercontent.com/35197667/119225847-3050e700-bafe-11eb-9888-7687bb1b0741.png)

## Telemetry producers

A "Telemetry producer" would send Spans, logs or metrics to the ring.  In this design a producer is not necessarily a business service.  We want producers to be as dumb as possible.

### Trace producers

The OTel SDK could simply route Spans to the dumb LB in front of the Collector ring.

![image](https://user-images.githubusercontent.com/35197667/119225865-4363b700-bafe-11eb-92d2-6e940b9d79c4.png)

### Metric producers

Something would obtain metrics from services and push these to the ring.  

The thing that pushes data to the ring may be:
* Prometheus instance(s) using remote-write
* an OTel receiver that scrapes services for Prom metrics 
* something dumb that services push their metrics to - in this case it could be argued though that services push straight to the ring
* etc.

![image](https://user-images.githubusercontent.com/35197667/119225885-54142d00-bafe-11eb-80b2-c1d853424377.png)

### Log producers

Something would obtain logs from services and push these to the ring.  

The thing that pushes data to the ring may be:
* something like FluentBit that reads from stdout or tails files 
* something dumb that services push their logs to - in this case it could be argued though that services push straight to the ring
* etc.

![image](https://user-images.githubusercontent.com/35197667/119225903-62fadf80-bafe-11eb-9693-60e159e61520.png)
