### ISSUE TITLE
Exporter for New Relic

### ISSUE THREAD

**Issue by marcosflobo** [open-telemetry/opentelemetry-collector#3103]
**Is your feature request related to a problem? Please describe.**
No, just lack of functionality

**Describe the solution you'd like**
OpenTelemetry is growing and growing and there are several important backends where the traces, metrics and logs can be exported. New Relic is one of them.

This Feature Request is about to implement an Exporter for sending data to New Relic, like is implemented already for Jaeger (for example)

**Additional context**
New Relic is one of the most important software systems for observability and many companies are using it. Having an exporter for New Relic would empower the adoption of OpenTelemetry.

**Comment by mx-psi** [comment]
@marcosflobo vendor exporters live in the https://github.com/open-telemetry/opentelemetry-collector-contrib repo, I think you can find the exporter you are looking for there

**Comment by bogdandrutu** [comment]
Already supported https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/newrelicexporter
