### ISSUE TITLE
Prometheusremotewrite exporter should use "pdata" not internal protos

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3108]
See https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L106

We should not depend on the internal representation in any component.

**Comment by bogdandrutu** [comment]
Assigned to @alolita for triage

**Comment by sincejune** [comment]
I think I can take it.

**Comment by sincejune** [comment]
I think I can take it.

**Comment by bogdandrutu** [comment]
@sincejune go for it, waiting for a PR :)

**Comment by alolita** [comment]
@sincejune do you have bandwidth to submit a PR? else I will assign to another engineer? Please let us know.

**Comment by sincejune** [comment]
@alolita sorry, I was fighting with the unit tests under `Prometheusremotewrite` exporter. I think I can raise a PR within 2 days :)

**Comment by bogdandrutu** [comment]
This is important for phase one because it blocks https://github.com/open-telemetry/opentelemetry-collector/issues/3104
