### ISSUE TITLE
Batch Processor send_batch_max_size 

### ISSUE THREAD

**Issue by kisieland** [open-telemetry/opentelemetry-collector#3119]
**Describe the bug**
The main issues I would like to summarise here is connected to how the `send_batch_max_size` and `send_batch_size` flags interact.
Currently `processItem` function does something like:
```
if bp.sendBatchMaxSize > 0 {
  itemCount := bp.batch.itemCount()
  if itemCount+uint32(td.MetricCount()) > bp.sendBatchMaxSize {
  tdRemainSize := splitMetrics(int(bp.sendBatchSize-itemCount), td)
  item = tdRemainSize
  // put td back to the queue
}

bp.batch.add(item)
if bp.batch.itemCount() >= bp.sendBatchSize {
  // send data and clear batch
}
```
Note that this checks if batch after adding new data is bigger than `sendBatchMaxSize`, but when splitting uses `sendBatchSize` to compute remaining space. 
In effect (when `sendBatchSize > sendBatchMaxSize`) batch sent can be bigger than `sendBatchMaxSize`.
If you look at the latter part of the code it shows that the batch is sent only when it is bigger than `sendBatchSize`.
(For the simplicity I did not cover timeouts).

I would expect to batch be send as soon as size of `sendBatchMaxSize` is reached. Possible fix is to set those fields to the same values. I believe this should be at least mentioned in the Readme.

The original issue that brought me here is the fact that when configured in a way that `sendBatchSize` is much bigger than `sendBatchMaxSize`. Then the batch processor is using a lot of CPU (about 50x more than normally). 
I made some profiling and it spends majority of the time on scheduling and creating gorutines in `processItem`.
I will update the bug once I find some more information about the source of this CPU usage.

**What version did you use?**
Version: `v0.23.0`

**What config did you use?**
Config:
```
processors:
  batch:
    send_batch_max_size: 200
    timeout: 10s
```

**Comment by bogdandrutu** [comment]
There were some fixes related to this in the latest release, but we still have the problem if the values are reversed. Maybe that should be a validation in the config to not allow that

**Comment by bogdandrutu** [comment]
@kisieland I closed this since the main issue is not resolved. If you want to still improve performance please open an issue for that
