### ISSUE TITLE
Own collector's logs to file

### ISSUE THREAD

**Issue by heruv1m** [open-telemetry/opentelemetry-collector#3140]
Is there someway to write own collectors logs to file?
I mean not exporter logs, but service. Like this
`service/service.go:411	Starting OpenTelemetry Collector...	{"Version": "v0.20.0", "GitHash": "a10a1a7a", "NumCPU": 8}`

**Comment by jrcamp** [comment]
No, this is usually handled by whatever is running the collector (k8s, docker, systemd, etc.)
