### ISSUE TITLE
Rename service.Application to service.Server

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#3175]
The collector service server is currently named Application. In Otel, "application" has a significance to refer to the user applications to instrument. We might rename it to Server which would be more representative.

**Comment by rakyll** [comment]
Or why don't we call it Collector?

**Comment by eddyleelin** [comment]
Sorry for the newbie question, but would this be a breaking fix? It seems like it would be a rather straightforward fix of changing variable names, so I could look into it!

**Comment by bogdandrutu** [comment]
@eddyleelin it is, but we are allowed to do that in order to cleanup the code in this phase of the project.

**Comment by eddyleelin** [comment]
Great! Thanks for the response. I could try to take this one on then! @bogdandrutu

**Comment by bogdandrutu** [comment]
We renamed to service.Collector.
