### ISSUE TITLE
[Tracking Issue for Design Proposals] Refactor processors in core (Span, Attributes, Filter, etc.)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3185]
Right now to change span names we have the "SpanProcessor" and to change the span Attributes we have AttributesProcessor which also changes LogRecord attributes but does not change Resource attributes where we have the ResourceProcessor for that (a.k.a a complete mess).

We need to have a better overall design of what processors we offer:
1. One processor to mutate Span properties - name, attributes, etc.
2. One processor to mutate LogRecords properties - name, body, attributes, etc.
2. One processor to mutate Metrics properties - name, maybe attributes, maybe unit transformation, etc.
3. One processor that mutates Resource. Should this be just a library that is included in the first two?
4. etc.

So what we need to see first:
1. High-level description of the processors that we want to offer and their capabilities.
2. Need to investigate how the "matching/filtering" (which spans/logs/metrics do I apply the mutations) config looks like.
3. Need to investigate how a mutation config looks like.

/cc @punya @bhautikpip @hossain-rayhan @alolita  related to the other discussion.

**Comment by hossain-rayhan** [comment]
[wip] design [doc](https://docs.google.com/document/d/1yCodswsxkfzD08pbOASd-DdaOs_7v2Uho5lT4lf0LmA/edit#heading=h.3ylj5d126vrq). Feel free to modify and add comment.

**Comment by mxiamxia** [comment]
Proposed a design on refactoring the current processors for mutating trace, metric and log data points. 
[OTel Core Data Mutation Processors Design](https://docs.google.com/document/d/1SxxEOU_qWOAGVHs-we4Oy9nM5TuVwB3ymI5i8zHB7K4/edit?usp=sharing)

**Comment by bogdandrutu** [comment]
Based on #3474 this is no longer a P0 for core, since all the affected components are moved to contrib.

**Comment by mxiamxia** [comment]
The refactored processors will introduce the new configurations which have the breaking changes to the existing OTel Collector customers. We’ll need to discuss the new processors migration options for reducing the breaking changes impact. I will try to cover it in OTel processor enhancement proposal.

**Comment by mxiamxia** [comment]
Made some major updates on [OTel processors redesign Doc v2](https://docs.google.com/document/d/1UNzMG1LBUWpiMiFn1PX4OPVVQsk6EneISbtR4cdBm4Y/edit?usp=sharing)

Please help to review.
