### ISSUE TITLE
Add log capability to probabilisticsamplerprocessor for sample down the trace_flags

### ISSUE THREAD

**Issue by alexvanboxel** [open-telemetry/opentelemetry-collector#3192]
**Is your feature request related to a problem?**
Consider the following example. You have instrumented a legacy app that is not HA and has long startup times with auto instrumentation (example with opentelemetry-java-instrumentation), changing the sampling percentage needs a restart that is in some cases unacceptable.  Switching to 100% sampling in de traced process and then using the `probabilisticsamplerprocessor` in the collector to sample down the number of spans is a possibility. 

But as the sampling is set to **100%** in the process and the logs that the process produces use logger instrumentation (eg. Logger MDC auto-instrumentation) that will inject the trace_id, span_id, and trace_flags... the `trace_flags` set to `0x01`. But because the collector is now sampling down the traces, there is an indiscrepancy between the `trace_flags` and the traces that are captured.

**Describe the solution you'd like**
Adding the capability to `probabilisticsamplerprocessor` to also remove the bit in the `trace_flags` from the logs with the same configuration is a solution to make the `trace_flags` again consistent with the collected traces.

**Comment by alexvanboxel** [comment]
This issue can be assigned to me, I would be glad to implement this.

**Comment by bogdandrutu** [comment]
@alexvanboxel happy to assign, but need to understand "logs" vs "spans". I feel I got confused in the description

**Comment by alolita** [comment]
@alexvanboxel can you give us an update - are you working on this :-)
