### ISSUE TITLE
can opentelemetry buffer data? like buffer timeseries before sending it?

### ISSUE THREAD

**Issue by SkrPaoWang** [open-telemetry/opentelemetry-collector#3194]

**Comment by SkrPaoWang** [comment]
Looks like opentelemetry only buffers data in memory. What is the default time buffer data can be stored in memory?

**Comment by pmm-sumo** [comment]
@SkrPaoWang the size of the buffer is currently [controlled using number of batches](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#configuration)

Related issue: https://github.com/open-telemetry/opentelemetry-collector/issues/2285

**Comment by pmm-sumo** [comment]
Also, for Prometheus remote write exporter specifically, there's a [PR open with WAL support](https://github.com/open-telemetry/opentelemetry-collector/pull/3017)

**Comment by SkrPaoWang** [comment]
does otlp-collector support write to persistant volume, (writing to the disk)?

**Comment by rakyll** [comment]
@SkrPaoWang, if you are asking this question in the context of WAL, the collector is aiming to implement a WAL write the intermediate buffers to persistent disk.

If you are asking about this in the context of exporting data to persistent disk, you have the option of writing to files, see https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/fileexporter.

**Comment by alolita** [comment]
@SkrPaoWang can you provide more context for your question?
