### ISSUE TITLE
Error stopping otel-collector on windows

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector#3217]
**Describe the bug**
It's definitely not a big deal, but when you stop otel-collector on windows, there is an error related to /dev/stderr not implemented on windows.

```
[...]
Stopping extensions...
Shutdown complete.
errors occurred while shutting down the service: failed to shutdown service: failed to shutdown pipelines: failed to shutdown exporters: sync /dev/stderr: The handle is invalid.
```

**Steps to reproduce**
Run otel-collector and interrupt it.

**What did you expect to see?**
No error

**What version did you use?**
0.25

**Environment**
Windows server 2019

**Comment by IrisTuntun** [comment]
This should have been resolved in 0.27 by #2994 already.
