### ISSUE TITLE
Add a GitHub Actions workflow to check for API compatibility

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3220]
This issue is related to preparing for the upcoming 1.0 GA release and is related to issue #2545 

We need to add a GitHub Action that compares the PR with head and adds a comment or fails if changes are identified.

**Comment by bryanuribe** [comment]
Would I be able to pick this up?
cc: @alolita

**Comment by alolita** [comment]
Assigned to you @bryanuribe

**Comment by alolita** [comment]
Completed.
