### ISSUE TITLE
Transform `goldendataset` for traces to not depend on protos.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3229]
Right now the generator generates proto structs instead of `pdata` structs, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/internal/goldendataset/span_generator.go#L50 which should return `pdata.Span` in this case.

**Comment by IrisTuntun** [comment]
Hi, can I take this issue?

**Comment by bogdandrutu** [comment]
Completely fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/3377
