### ISSUE TITLE
TestBallastMemory - Intermittent test failure

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#3233]
The test TestBallastMemory failed during PR #3128. Unfortunately, the test does not specify what's the memory consumption, only the limit.

```
=== RUN   TestBallastMemory
make: *** [Makefile:60: testbed-loadtest] Error 1
2021/05/18 21:40:40 Starting Agent (/home/runner/work/opentelemetry-collector/opentelemetry-collector/bin/otelcol_linux_amd64)
2021/05/18 21:40:40 Writing Agent log to /home/runner/work/opentelemetry-collector/opentelemetry-collector/testbed/tests/results/TestBallastMemory/agent.log
2021/05/18 21:40:40 Agent running, pid=7649
2021/05/18 21:40:40 Stopped generator. Sent:         0 items
2021/05/18 21:40:40 Gracefully terminating Agent pid=7649, sending SIGTEM...
2021/05/18 21:40:40 Stopping process monitor.
2021/05/18 21:40:40 Agent process stopped, exit code=0
2021/05/18 21:40:40 Starting Agent (/home/runner/work/opentelemetry-collector/opentelemetry-collector/bin/otelcol_linux_amd64)
2021/05/18 21:40:40 Writing Agent log to /home/runner/work/opentelemetry-collector/opentelemetry-collector/testbed/tests/results/TestBallastMemory/agent.log
2021/05/18 21:40:40 Agent running, pid=7658
    e2e_test.go:88: 
        	Error Trace:	e2e_test.go:88
        	Error:      	Should be true
        	Test:       	TestBallastMemory
        	Messages:   	RSS must be less than or equal to 70
2021/05/18 21:40:40 Stopped generator. Sent:         0 items
2021/05/18 21:40:40 Gracefully terminating Agent pid=7658, sending SIGTEM...
2021/05/18 21:40:40 Stopping process monitor.
2021/05/18 21:40:40 Agent process stopped, exit code=0
2021/05/18 21:40:40 Starting Agent (/home/runner/work/opentelemetry-collector/opentelemetry-collector/bin/otelcol_linux_amd64)
2021/05/18 21:40:40 Writing Agent log to /home/runner/work/opentelemetry-collector/opentelemetry-collector/testbed/tests/results/TestBallastMemory/agent.log
2021/05/18 21:40:40 Agent running, pid=7666
2021/05/18 21:40:40 Stopped generator. Sent:         0 items
2021/05/18 21:40:40 Gracefully terminating Agent pid=7666, sending SIGTEM...
2021/05/18 21:40:40 Stopping process monitor.
2021/05/18 21:40:40 Agent process stopped, exit code=0
--- FAIL: TestBallastMemory (0.24s)
```

**Comment by pavankrish123** [comment]
Also happening in #3214 as well - think the issue is independent.

**Comment by jpkrohling** [comment]
#3247 failed with:

```
    assertion_compare.go:342: 
        	Error Trace:	e2e_test.go:87
        	Error:      	"74" is not less than or equal to "70"
```

**Comment by jpkrohling** [comment]
And again:

```
    assertion_compare.go:342: 
        	Error Trace:	e2e_test.go:87
        	Error:      	"71" is not less than or equal to "70"
        	Test:       	TestBallastMemory
        	Messages:   	[]
```

@owais, looks like you worked on this before, so I wanted to ask you this: should the test be more lenient with the limits, or should the underlying code be changed so that its internal limits are some percentage points lower than what the user set?

**Comment by owais** [comment]
IIRC, I think it checks that VMS is greater than specified ballast size but actual RSS is not affected. The failures suggest that the baseline for actual memory used by the collector has changed so I guess we need to either find the regression or increase the limit. The number aren't big enough to suggest a regression though. I'd verify the expectation for pipelines without ballast and use same numbers. Another issue with ballast is that it's behaviour is more of an approximation depending on Go's internal optimizations instead of being a deterministic behavior. So I think making the numbers a bit lenient while still ensuring that the specified ballast does not result in increased RSS by the same amount is good enough for this test.

**Comment by jpkrohling** [comment]
> So I think making the numbers a bit lenient while still ensuring that the specified ballast does not result in increased RSS by the same amount is good enough for this test.

Alright, I'll change the test so that it accepts up to 10% more than what's specified as limit.
