### ISSUE TITLE
Automate doc publishing to opentelemetry.io

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#3234]
We now have a manually triggered github action [doc-update](https://github.com/open-telemetry/opentelemetry-collector/actions/workflows/docs-update.yml) which publishes the documentation from this repo to opentelemetry.io website repo (creates a PR there).

It would be nice to automate triggering of doc-update action as part of release process.

**Comment by tigrannajaryan** [comment]
FYI, @open-telemetry/collector-approvers

**Comment by cole-easton** [comment]
I would like to take this issue.
