### ISSUE TITLE
Hostmetrics process.memory.* metadata should be gauge

### ISSUE THREAD

**Issue by tmodelsk** [open-telemetry/opentelemetry-collector#3266]
**Describe the bug**
Hostmetrics: 
- process.memory.physical_usage
- process.memory.virtual_usage 

metric types are defined in metadata  as _**int sum cumulative (AggregationTemporalityCumulative)**_, 
but in reality metrics are scraped as gauge. 
Metrics type in metadata should be _**int gauge**_ - they are already scraped as int gauge & they're useful as gauge, 
 MiB/s ( _int sum cumulative / AggregationTemporalityCumulative_ ) is not very convenient to use for memory monitoring.

**Steps to reproduce**
Metrics pipeline as simple as: hostmetrics receiver -> googlecloudexporter

**What did you expect to see?**
From process.memory.* metrics I expect to see use usage of memory (in bytes, megabytes etc) , not strange MiB/s .

**What did you see instead?**
With googlecloudexporter & GPC monitoring I see MiB/s . 

**What version did you use?**
v0.24

**Additional context**
Pull request with fix in progress , todo put link here

**Comment by bogdandrutu** [comment]
They are correctly scraped as int **non-monotonic** cumulative sum, which I think the `googlecloudexporter` should treat as gauge.

/cc @punya @jsuereth

**Comment by bogdandrutu** [comment]
Found a translation bug, opened the PR and waiting for review to merge. That will solve your issue. Thank you for reporting this.
