### ISSUE TITLE
Plan to revert the revert PR#3276

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3282]
In order to make this possible let's follow the next plan:

* Change all components to call ToDialOptions/ToClient in Start (no change on the APIs but only where it is called). Needs to happen in core and contrib.
* Re-merge what is left in the reverted PR.

/cc @pavankrish123

**Comment by jpkrohling** [comment]
I see that quite a few about this has been done already, with PRs open. The second part is missing but depends on the first.

**Comment by pavankrish123** [comment]
Once #3321 is merged - the upcoming changes will update the APIs `ToClient()` and `ToDialOptions()` to `ToClient(ext map[config.ComponentID]component.Extension)` and `ToDialOptions(ext map[config.ComponentID]component.Extension)`.

@bogdandrutu  The `ext` to these APIs we are proposing is a mandatory argument - just wanted to confirm if you are ok with it as well. Can make it optional as well.

@gramidt let me know if all the components are prepared  - I will push the changes to APIs in the next PR.

**Comment by gramidt** [comment]
@pavankrish123 - The latest component needing to be merged as part of #3507 is the Splunk SignalFX exporter. Once that has been merged, contrib should be good to go.

**Comment by pavankrish123** [comment]
Thanks @gramidt let me know. I have started  preparing the changes 

Pavan

**Comment by gramidt** [comment]
@pavankrish123 - The final PR in contrib has been merged.

**Comment by pavankrish123** [comment]
Thanks @gramidt waiting for the above pr to be merged. Will push changes to the api changes after the merge

**Comment by pavankrish123** [comment]
Can close this issue now.
