### ISSUE TITLE
Where should BuildInfo live?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3286]
Right now `BuildInfo` is defined in the "component", is it the right place?

This issue is just to agree if this is the right place to have the struct `BuildInfo`

**Comment by rakyll** [comment]
I guess we can't put this into service due to circular dependencies. component is probably an ok place. If not, a "build" package might be introduced.

**Comment by alolita** [comment]
What's the final decision here?

**Comment by bogdandrutu** [comment]
Seems that we can have this in the component.
