### ISSUE TITLE
how the opentelemetry exporter is designed to guarantee security (authentication & authorization) when collector exports data to backend?

### ISSUE THREAD

**Issue by SkrPaoWang** [open-telemetry/opentelemetry-collector#3292]
how the opentelemetry exporter is designed to guarantee security (authentication & authorization) when collector exports data to backend?

**Comment by SkrPaoWang** [comment]
Anyone here?

**Comment by bogdandrutu** [comment]
It is up to the backend exporter implementation to design/define that. For example some backends use https connection + token based auth, some use different mechanism. The collector is not responsible to define how this should happen, is up to the backend to decide. If you have a backend in mind we can ask the question to the people responsible for that.

**Comment by rakyll** [comment]
I think this question is answered, we can close this issue. Please reopen if you have a specific ask.
