### ISSUE TITLE
Change obsreport helpers for scraper to use the same pattern as Processor/Exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3313]
See https://github.com/open-telemetry/opentelemetry-collector/issues/2649 for same thing that was done for Receiver

**Comment by bogdandrutu** [comment]
@humivo are you willing to do this as well?

**Comment by humivo** [comment]
> @humivo are you willing to do this as well?

I would be open to doing this one as well
