### ISSUE TITLE
docker images for arm64 

### ISSUE THREAD

**Issue by johanneswuerbach** [open-telemetry/opentelemetry-collector#3331]
Published docker images under https://hub.docker.com/r/otel/opentelemetry-collector/tags?page=1&ordering=last_updated for arm64.

**Describe the solution you'd like**

Publish multi-arch docker images for arm64 similar to prometheus https://hub.docker.com/r/prom/prometheus/tags?page=1&ordering=last_updated 

**Describe alternatives you've considered**

Build custom images locally, but that makes testing on none amd64 architectures more challenging, e.g. the new M1 macs.

**Comment by gramidt** [comment]
Hi @johanneswuerbach!

This is an excellent recommendation! I had actually started this work a couple months ago, but ultimately decided to halt on it until we have finished our migration from CircleCI to GitHub Actions. This migration is still underway and there are a couple PRs being reviewed that will help get us most of the way there. Once this is complete, I will be picking my old PR back up ( https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2397 ) and implementing it into both the core and contrib collector pipelines.
