### ISSUE TITLE
Log the opentelemetry-proto version

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#3345]
**Is your feature request related to a problem? Please describe.**

To my best knowledge, currently there's no way to tell which version of [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto/releases) was used in a given OpenTelemetry Collector build. Such information is also not tracked in [CHANGELOG.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md) (the last update is about v0.6.0). 

**Describe the solution you'd like**

Perhaps we could do either of the following:

1. Log the OTLP version when collector starts, e.g. by adding one more tag here:
`2021-06-01T09:56:46.460+0200	info	service/application.go:262	Starting otelcol...	{"Version": "v0.27.0-29-gbe3e40d4", "NumCPU": 16, "OTLPVersion":"v0.8.0-abcd1234"}`
2. Update the CHANGELOG.md with the current (or changed) proto version

**Comment by jefchien** [comment]
I'd like to make this change. I believe I can pull the version from the submodule in a similar manner to the VERSION in the makefile.
