### ISSUE TITLE
arm64 rpms will not install on AWS Graviton / Amazon Linux 2 machines

### ISSUE THREAD

**Issue by cprice404-aws** [open-telemetry/opentelemetry-collector#3346]
**Describe the bug**

The arm64 RPMs from the "release" page will not install on AWS Graviton instances running Amazon Linux 2.

**Steps to reproduce**

1. Create an AWS EC2 instance using the latest Amazon Linux 2.  Choose an instance type with a `g` to use the latest generation of instances (Graviton); for example `t4g.micro`.
2. Follow the instructions on the [Getting Started doc](https://opentelemetry.io/docs/collector/getting-started/#linux-packaging) to download and attempt to install the `arm64` RPM:

    wget https://github.com/open-telemetry/opentelemetry-collector/releases/download/v0.27.0/otel-collector-0.27.0-1.arm64.rpm
    sudo rpm -ivh ./otel-collector-0.27.0-1.arm64.rpm

This results in the following error message:

    package otel-collector-0.27.0-1.arm64 is intended for a different architecture

**What did you expect to see?**

Expected the rpm to install successfully; AL2 is mostly redhat compatible and the arm64 build should theoretically be binary compatible.

**What did you see instead?**

Error: `package otel-collector-0.27.0-1.arm64 is intended for a different architecture`

**What version did you use?**

v0.27.0

**What config did you use?**

N/A, did not get far enough

**Environment**
OS: Amazon Linux 2 on EC2 t4g.micro.

**Additional context**

**Comment by rakyll** [comment]
cc @mxiamxia

**Comment by bogdandrutu** [comment]
Please reopen if the problem is still there, we were able to run it.
