### ISSUE TITLE
Triager role request for @punya

### ISSUE THREAD

**Issue by punya** [open-telemetry/opentelemetry-collector#3358]
Formal request to grant triager scope to @punya.

Reason for request: similar to #3096, I can work together with @alolita to triage issues -- assign a priority that consistent with our overall development process and help focus the community's attention to keep us on track for 1.0.

I participate in the Collector and Go SIGs and fulfill [the requirements for a triager role](https://github.com/open-telemetry/community/blob/main/community-membership.md).

Edit: this request is intended to cover both collector and collector-contrib.

**Comment by alolita** [comment]
@tigrannajaryan @bogdandrutu please approve when you have a chance.

**Comment by tigrannajaryan** [comment]
SGTM

**Comment by bogdandrutu** [comment]
SGTM, please create a PR

**Comment by punya** [comment]
@bogdandrutu I've created the PRs. Please add me to https://github.com/orgs/open-telemetry/teams/collector-triagers and https://github.com/orgs/open-telemetry/teams/collector-contrib-triagers in addition to merging the PRs.

**Comment by tigrannajaryan** [comment]
> @bogdandrutu I've created the PRs. Please add me to https://github.com/orgs/open-telemetry/teams/collector-triagers and https://github.com/orgs/open-telemetry/teams/collector-contrib-triagers in addition to merging the PRs.

Done.
