### ISSUE TITLE
Permanently disable port 55680 in Collector version 0.30.0

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3368]
@mxiamxia has removed all the legacy port(55680) mentions across the OpenTelemetry repos. The port will be disabled in OTel Collector v0.30.0 per the discussion in https://github.com/open-telemetry/opentelemetry-collector/pull/3256#discussion_r638380853

**Comment by alolita** [comment]
@bogdandrutu PR #3101 was closed. What needs to be done here? Let us know so that @mxiamxia can resolve this.

**Comment by mxiamxia** [comment]
From the previous discussion, we need some baking time before we'll going to remove the old gRPC port(55680). I think now is a good time to remove it. I also want to confirm if we also remove legacy HTTP port(55681) as well? @bogdandrutu @alolita
