### ISSUE TITLE
Support for a generic metrics exporter for the collector's own telemetry

### ISSUE THREAD

**Issue by irisgve** [open-telemetry/opentelemetry-collector#3371]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to collect the collector's obsreport metrics is through a prometheus exporter (pull-based). Looks like this is currently hardcoded in https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/telemetry.go#L78. Are there any plans to support other metrics exporters for self-telemetry? Our use-case is that we are doing global aggregations somewhere in our pipeline and thus cumulative metric types i.e. Prometheus counters are trickier to support so being able to configure which metrics exporter we can use for self-telemetry would be ideal.

**Describe the solution you'd like**
Ability to configure a metrics exporter for self-telemetry metrics

**Comment by jrcamp** [comment]
Is this the same as #1093?

**Comment by irisgve** [comment]
Yes thanks for pointing that out! I'll close this one.
