### ISSUE TITLE
GRPC interceptor or wrapper

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector#3412]
I would like like to be able to add a GRPC interceptor to view GRPC requests/responses in much the same way the HTTPClientSettings allows me to wrap all requests/responses with a custom RoundTripper.  The use case I have in mind is to allow for more detailed debug logging.

**Comment by davidmirza408** [comment]
I would appreciate a response to this request.  It is needed so that we can properly log GRPC request/response and to be able to inject a random trace header for each request.

**Comment by bogdandrutu** [comment]
I don't have a solution, looking for proposals

**Comment by davidmirza408** [comment]
In the HTTPClientSettings used to configure the http exporter there is a field called CustomRoundTripper that allows us to wrap the OT round tripper with a custom round tripper.  I think something similar would work for GRPC.  We could add a GRPCInterceptor setting to GRPCClientSettings.
