### ISSUE TITLE
Move storage extension to core

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#3424]
**Is your feature request related to a problem? Please describe.**
OpenTelemetry Collector Contrib includes a [storage](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage) extension, which is currently used by [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver). 

It was identified that the extension could be useful for other purposes, such as persistent buffering ([#2285](https://github.com/open-telemetry/opentelemetry-collector/issues/2285))

First, we can start with moving the interface and eventually the extension code could be fully moved

**Comment by bogdandrutu** [comment]
This is done correct?
