### ISSUE TITLE
Make Application's telemetry configurable

### ISSUE THREAD

**Issue by mapno** [open-telemetry/opentelemetry-collector#3436]
**Is your feature request related to a problem? Please describe.**

The `Application`'s telemetry uses the Prometheus exporter from [OpenCensus](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus) by default. Before, one could configure the telemetry manually, and therefore the exporter itself. But that is no longer viable since the `obsereport` and `obsmetrics` pkgs were moved to `/internal` and made [private](https://github.com/open-telemetry/opentelemetry-collector/commit/f72eab07be398c6e07635f5844d3098056ac067a#diff-c144f83b4550587eaeb612c165176a879378b7d7ed7991c5d48c96e6d7688689).

This can be of particular interest when running multiple `Application`'s in a single process. We've found that a good way of differentiating app's metrics is by attaching custom labels to each instance.

**Describe the solution you'd like**

As per this [comment](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.28.0/service/telemetry.go#L78), the ideal solution would be using a generic metrics exporter and making it configurable via the app's settings.

**Describe alternatives you've considered**

An alternative is adding configuration for the Prometheus exporter in the app's settings. As an example, [here](https://github.com/mapno/opentelemetry-collector/commit/42278359acbfea04ec254c1f15836bd51984c534) i'm passing a prom registry to the exporter.

**Comment by dashpole** [comment]
Could we make SelfObs a receiver, and use the metrics and trace [opencensus bridges](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus) to translate from OpenCensus?

You would then be able to achieve the current behavior by adding a pipeline with the self obs receiver and a prometheus exporter.

**Comment by mapno** [comment]
Hi, sorry what is the `SelfObs` receiver? I wasn't able to find it.

**Comment by dashpole** [comment]
I was suggesting we create a new receiver out of the current endpoint

**Comment by bogdandrutu** [comment]
Assign to @bogdandrutu for better understanding what are (if any) the breaking changes that we need for this.

**Comment by alolita** [comment]
What are your findings on this issue? @bogdandrutu Can we defer to after tracing stability release?
