### ISSUE TITLE
OpenTelemetry Collector msi is not installing in windows 10

### ISSUE THREAD

**Issue by kuldeepy** [open-telemetry/opentelemetry-collector#3454]
**Describe the bug**
OpenTelemetry Collector msi is not installing giving error -
Product: Open Telemetry Collector -- Error 1923. Service 'Open Telemetry Collector' (otelcol) could not be installed.  Verify that you have sufficient privileges to install system services.

**Steps to reproduce**
Download  otel-collector-0.28.0-amd64.msi version v0.28.0 Beta
After download run the msi installer 

**What did you expect to see?**
I expect that otel-collector msi run without any error and make local otel-collector set up and running.

**What did you see instead?**
Instead of that is giving error - Product: OpenTelemetry Collector -- Error 1923. Service 'OpenTelemetry Collector' (otelcol) could not be installed.  Verify that you have sufficient privileges to install system services.

**What version did you use?**
Version: v0.28.0 Beta

**What config did you use?**
Config: Until installer installed successfully, I am not able to see the config file.

**Environment**
OS: Windows 10
Compiler(if manually compiled): not compiled manually

**Additional context**
Try to setup Open Telemetry Collector in windows 10 to collect the logs.
![Error](https://user-images.githubusercontent.com/7345515/122242631-1af29100-cee1-11eb-985a-b1daabd50d32.PNG)

**Comment by rushirg** [comment]
The [latest release](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/latest) v0.38.0 MSI package works! 
_(Note: it automatically starts the service with default config)_

**Comment by codeboten** [comment]
Closing as resolved
