### ISSUE TITLE
Remove disable/enable from components

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#347]
Currently we do have two ways to control if a component is disabled/enabled:
1. Via the `disabled` property
1. If the component is present in a pipeline/extension list.

I would suggest that we keep only the second option to control if the component is enabled/disabled.

**Comment by tigrannajaryan** [comment]
@pjanotti please comment. We need to settle this before Beta release.

**Comment by pjanotti** [comment]
SGTM. The only possible call for this is to keep configuration and quickly disable something but with VCS and a good text editor it is trivial to workaround that.

**Comment by ringerc** [comment]
@pjanotti 

> SGTM. The only possible use for disabled is to keep configuration and quickly disable something but with VCS and a good text editor it is trivial to workaround that.

It was possible to enable/disable using env-var substitution using this property, but isn't very practical to do so with e.g. the otel operator by adding/removing from the pipelines component list.
