### ISSUE TITLE
otlp exporter - per_rpc_auth is not wokring

### ISSUE THREAD

**Issue by AJ-54** [open-telemetry/opentelemetry-collector#3472]
**Describe the bug**
When using otlp as exporter and defining `per_rpc_auth` it throws the error
```
2021-06-21T12:02:59.202+0530    info    service/application.go:262      Starting otelcol...     {"Version": "v0.28.0", "NumCPU": 2}
2021-06-21T12:02:59.204+0530    info    service/application.go:170      Setting up own telemetry...
2021-06-21T12:02:59.207+0530    info    service/telemetry.go:99 Serving Prometheus metrics      {"address": ":8888", "level": 0, "service.instance.id": "ead14f1c-86e9-4b17-8894-db32ebae3e2d"}
2021-06-21T12:02:59.210+0530    info    service/application.go:205      Loading configuration...
Error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:

* '' has invalid keys: per_rpc_auth
2021/06/21 12:02:59 application run finished with error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:

* '' has invalid keys: per_rpc_auth
```

**Steps to reproduce**
Here is the `config.yaml`
```
exporters:
  otlp:
    endpoint: localhost:8080
    insecure: true
    per_rpc_auth:
      auth_type: bearer
      bearer_token: "some-token"
    compression: gzip
  logging:
    loglevel: "debug"

service:
  pipelines:
    logs:
      exporters:
      - otlp
 ```
 Just running `.\otelcol_windows_amd64.exe --config config.yaml` will throw the error as described above.

**What did you expect to see?**
otlp exporter running without any errors

**What did you see instead?**
Error

**What version did you use?**
Version: v0.28.0

**Environment**
OS: Windows 10
Compiler(if manually compiled): No, took it from release

**Comment by pavankrish123** [comment]
The `per_rpc_auth` feature has been recently moved to become an extension. The auth needs to be set up as an extension, please find the instructions here https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/bearertokenauthextension.

**Comment by AJ-54** [comment]
Thank You @pavankrish123, I would like to update the docs [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md) so everyone can know it is now moved inside the extension.

**Comment by tigrannajaryan** [comment]
@AJ-54 Can we close this now that https://github.com/open-telemetry/opentelemetry-collector/pull/3477 is merged?

**Comment by AJ-54** [comment]
> @AJ-54 Can we close this now that https://github.com/open-telemetry/opentelemetry-collector/pull/3477 is merged?

Yes, sure!
