### ISSUE TITLE
Application's telemetry configuration

### ISSUE THREAD

**Issue by mapno** [open-telemetry/opentelemetry-collector#3482]
**Is your feature request related to a problem? Please describe.**

Follow-up issue from https://github.com/open-telemetry/opentelemetry-collector/issues/3436

After discussion in the Collector community meeting, we want to explore new designs and alternative solutions for the following topics:

- Telemetry configuration: `Application` has different telemetry components such as a logger, exporter for metrics, etc. Configuration for them is varied, some parts are available through flags, other are hardcoded in code. We want to explore how this configuration should be defined.
-  Building of custom components: Currently, a set of custom components are used for telemetry - such as a zap logger and a prometheus exporter for metrics. One long term goal exists to switch this components to OTel, while still making possible the usage of custom components. For that, we need to explore how these components should be built.

**Describe the solution you'd like**

One possible solution for the configuration is to move it to the `Application`'s YAML config file. The YAML file is the main source of the configuration for the application's components. Removing other options would bring more consistency.

**Comment by alolita** [comment]
@Aneurysm9 - any. updates?

**Comment by bogdandrutu** [comment]
Telemetry can now be configured in the main config file.
