### ISSUE TITLE
Possible race condition in reloading

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#3489]
I was looking at the [reloading code](https://github.com/open-telemetry/opentelemetry-collector/blob/9d5a51ef7d11e4a4afba8ab8c76786d9a20335a6/service/collector.go#L244) in the collector. Looks like `reloadService` is called from this goroutine which then sets `col.service` to a new value. `col.service` is [read in other goroutines](https://github.com/open-telemetry/opentelemetry-collector/blob/9d5a51ef7d11e4a4afba8ab8c76786d9a20335a6/service/collector.go#L301) but I don't see any sort of locking. It seems you could have a dirty read of `col.service` on shutdown (if it was reloaded in a different goroutine). Or is there anything preventing shutdown from being called in the middle of reloading?

Also https://github.com/open-telemetry/opentelemetry-collector/blob/9d5a51ef7d11e4a4afba8ab8c76786d9a20335a6/service/collector.go#L253 return value isn't logged, unsure how often it's useful.

**Comment by rakyll** [comment]
@jrcamp Can you contribute a test case so we can confirm whether there is a race or not?

I spent an hour figuring out how reloadService is triggered. Watchable is not very well documented and the only real life implementation I came across was  https://github.com/signalfx/splunk-otel-collector/tree/960ca936f8d0bd0d33258a1baa102ff40caa2495/internal/configprovider.

**Comment by jrcamp** [comment]
@rakyll is there a good way in Go to do this given it relies on a certain order of execution? ie can you prove nondeterministic execution?

**Comment by dashpole** [comment]
Is it possible to write a unit test for it?  Then we could check for races with `-race`
