### ISSUE TITLE
Allow service.Collector users to implement custom graceful shutdown 

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#3490]
Currently, service.Collector is handling the signal management and implementing a graceful shutdown. This is a problem for collectors that want to wire their own signal handling in cases they want to add custom logic and/or have resources other than the service.Collector to shutdown.

Make the current behavior optional by introducing a collector setting:

```
type CollectorSettings struct {
	// Factories component factories.
	Factories component.Factories

	// BuildInfo provides application start information.
	BuildInfo component.BuildInfo

	// ParserProvider provides the configuration's Parser.
	// If it is not provided a default provider is used. The default provider loads the configuration
	// from a config file define by the --config command line flag and overrides component's configuration
	// properties supplied via --set command line flag.
	ParserProvider parserprovider.ParserProvider

        // EnableGracefulShutdown will automatically shutdown the Collector on SIGINT and SIGTERM.
        EnableGracefulShutdown bool

	// LoggingOptions provides a way to change behavior of zap logging.
	LoggingOptions []zap.Option
}
```

If disabled, users can handle signals themselves and call Collector.Shutdown.

**Comment by jrcamp** [comment]
Perhaps `service.Collector` needs to be made more libraryish and things like signal handling should be done inside a `main.go` that consumers that are wrapping the collector aren't required to use.

**Comment by rakyll** [comment]
@jrcamp That's the convention in Go. Signal handling is left to the main. I'd suggest us main package doing the wiring.

**Comment by Caesurus** [comment]
Sorry to have to ask, how do i set `DisableGracefulShutdown` to true via the commandline. I understand how to do so programmatically, but doing so via the configuration file is alluding me.
