### ISSUE TITLE
Allow ServerNameOverride for gRPC exporters

### ISSUE THREAD

**Issue by backjo** [open-telemetry/opentelemetry-collector#351]
gRPC client channels allow a `ServerNameOverride` to be specified, which overrides the hostname to be checked during TLS handshakes. This should be able to be configured through the exporter configuration for any gRPC exporter

**Comment by pavolloffay** [comment]
This seems to be done https://github.com/open-telemetry/opentelemetry-collector/blob/75938b9ffb6bee75a80e11966e1b224ccc7673ea/config/configgrpc/configgrpc.go#L82
