### ISSUE TITLE
Rename OpenTelemetry Service to OpenTelemetry Collector

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#352]
We heard several times that the name "Service" is confusing, is too generic and does reflect well the intent. After discussing with maintainers and other OpenTelemetry community members we decided to rename the "Service" to "Collector" since we believe it better reflects the purpose and is more distinct.

What needs to be done:
- [x] Rename all references to Service to Collector in the source code, documentation and examples.
- [x] Rename binary from `otelsvc` to `otelcol`.
- [x] Update documentation where it references to "Collector" as deployment mode to "Standalone" as a deployment mode.
- [x] Rename this `opentelemetry-service` repo to `opentelemetry-collector`.
- [x] Update source code imports to point to `github.com/open-telemetry/opentelemetry-collector` instead of `github.com/open-telemetry/opentelemetry-service`.
- [x] Announce publicly that repo was renamed so that 3rd party packages who depend on us can update the their dependencies.
- [x] Update dependencies in `opentelemetry-service-contrib`.
- [ ] Rename repo `opentelemetry-service-contrib` to `opentelemetry-collector-contrib`.

**Comment by pjanotti** [comment]
The last remaining task is tracked via an issue on the contrib repo: https://github.com/open-telemetry/opentelemetry-service-contrib/issues/23 for the collector itself all issues are done, closing this issue.
