### ISSUE TITLE
Rename logging exporter to 'stdout' or 'debug' exporter in Collector

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3524]
The logging exporter should be renamed to stdout to represent its function. The current name 'logging' is misleading since this is a stdout exporter used mainly for debugging purposes.

Other similar examples of such an exporter can be found in the Go SDK. See https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/stdout

**Comment by alolita** [comment]
Related to #3474

**Comment by bogdandrutu** [comment]
The main difference is that we actually write to the Collector's own logger not to stdout.

**Comment by sincejune** [comment]
Do we still need to rename the `logging` exporter? I think I can take it if the answer is yes.

**Comment by rakyll** [comment]
I think "debug" is a better name, there is another thread where they are discussions not to write to stdout but to stderr, or give users options.

**Comment by alolita** [comment]
Action Item: @alolita will reach out to other Go community members to comment on this issue.

**Comment by alolita** [comment]
@open-telemetry/go-approvers can you please comment on your preference for this renaming of the existing logger exporter to debug exporter?

**Comment by MrAlias** [comment]
I would recommend not renaming to `stdout`, we have preserved this name in OTel-go for continuity, but realized that since we provide configuration for where the output can go (i.e. not STDOUT) it is a poor name.

I think `debug` is a good name if a rename is desired.

**Comment by alolita** [comment]
@bogdandrutu can we review and merge the outstanding PR and complete this task? Please advise.

**Comment by alolita** [comment]
@bogdandrutu @tigrannajaryan can you please review and merge this change? There are no objections so far from the community.

**Comment by tigrannajaryan** [comment]
I posted my objection here https://github.com/open-telemetry/opentelemetry-collector/pull/3609#pullrequestreview-705486043 

I don't see any new information to change my opinion.

**Comment by alolita** [comment]
@tigrannajaryan this issue was discussed in the Collector SIG and it was agreed upon by the community present there to change to 'debug' for long term maintainability.

**Comment by pellared** [comment]
Personally, I do not find `debug` really better than `logging`. The same term could be used e.g. as a logging level. I imagine that it can be misleading as well: "debug the collector" may mean to use Delve as well as setting a debug exporter... Maybe `internalLogger`?

Moreover, it is a breaking change that should be avoided and I do not see any strong reason to do it. I do not see confidence or any strong opinions to change the name. I feel that changing the name can cause more harm than benefits.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan this issue was discussed in the Collector SIG and it was agreed upon by the community present there to change to 'debug' for long term maintainability.

@alolita What was the community's justification? I it would be nice to capture it here for posterity. For now I don't see how "logging" is more difficult to maintain than "debug", but probably there are other reasons in favour of the change which I am not aware of.

I definitely do not mind changing if there is a reasonable justification, but I don't see that justification so far. :-)

One argument we should probably use is consistency with SDKs. 

Unfortunately the SDKs already are inconsistent:
- Java SDK uses "logging": https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/logging
- Go SDK uses "stdout": https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/stdout

It may be worth bringing this up in the maintainers or specification SIG and seek for a consistent naming across all language SDKs and Collector. I will be happy to go with whatever consistent name we choose, I don't have a strong preference for a particular name.

**Comment by alolita** [comment]
@tigrannajaryan responding to your questions:

Community feedback so far has been:
* Using good practice for Go which is stdout
* Removing confusion for users since 'logging' is confusing given the project also supports 'logs'
* Community members voicing 'debug' as a good option

Why not set an example for the Collector for being consistent on naming conventions and help avoid user misunderstanding of the logging component usage :-) I like the idea of discussing this in the maintainers meeting - will add to agenda.

**Comment by alolita** [comment]
@tigrannajaryan @bogdandrutu let's deprioritize this change if you are not in agreement as maintainers. Please advise. Ty!

**Comment by tigrannajaryan** [comment]
I submitted an issue on the spec: https://github.com/open-telemetry/opentelemetry-specification/issues/1931
Will also add to Maintainer's SIG agenda.

**Comment by tigrannajaryan** [comment]
Maintainer's SIG decided that there it is hard to come up with a consistent name given different naming conventions in different languages. Since we do not expect consistency I believe the name we have is as good as we can have. 

I am closing this issue. Feel free to reopen if you have other arguments.
