### ISSUE TITLE
Fix concurrency handling when data is fanned out

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#353]
`traceFanOutConnector` and `metricsFanOutConnector` currently simply pass the pointer to `TraceData` or `MetricsData`. 

This can cause problems when the data is fed into multiple pipelines and is concurrently processed and modified by processors.

Fan out connectors needs to create clones of data before and pass a pointer to a clone to each consumer that is connected (except one - which can use the original).

Alternatively implement Copy-On-Write for data and clone it on first write. This is more complex but may result in better performance (need measurement).

This is needed both for fanout connectors used when the same receiver feeds data to multiple pipelines (which is somewhat rare use case) and also when we have multiple exporters connected to the same pipeline (exporters may modify data).

**Comment by songy23** [comment]
Fixed by #367.
