### ISSUE TITLE
Update Collector to OTLP 0.8.0

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3534]
This is the umbrella issue which will have several items detailing tasks that need to be completed to update the Collector to OTLP version 0.8.0. Stay tuned.

https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.8.0

Roadmap:

- [x] Implement all naming changes in model/pdata/metrics.
- [x] Upgrade proto submodule to 0.8.0 without doing any translation. This may require changing pdata since some protos changed the value to oneof.
  - [x] If change to large, split into multiple upgrades to intermediate steps.
- [x] Implement required translation (as an example https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L514).
- [x] Re-enable staticcheck in pdata/metrics*.go
- [x] Remove primitiveAsDoubleField

**Comment by codeboten** [comment]
Would be happy to help with this if no one's started on it.

**Comment by codeboten** [comment]
@bogdandrutu I believe everything on the checklist is completed except the removal of LabelSet, should that item be part of the upgrade to OTLP v0.9.0?
