### ISSUE TITLE
Evaluate and implement service discovery for general use in the Collector 

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3538]
Separate service discovery logic from the Prometheus receiver for general use in the Collector.

- [ ] Evaluate whether Go SDK implementation can be reused.
- [ ] Design
- [ ] Implementation
- [ ] Testing

**Comment by alolita** [comment]
@jrcamp can you please post your evaluation results on this issue when you have them.

**Comment by dashpole** [comment]
Speaking from Google's experience, one of the benefits of this would be lower memory usage, since the imports in github.com/prometheus/prometheus/discovery/install/install.go increase the size of the binary, and its memory used.  In our case, we ended up hacking around this to remove unneeded service discovery integrations, but having service discovery be separated from the receiver would be a good thing for performance as well

**Comment by alolita** [comment]
@jrcamp can you please share your evaluation so far. 

@odeke-em would be good to get your comments here. 

@dashpole can you provide more context on your service discovery implementation.

**Comment by odeke-em** [comment]
Thank you @alolita! @jrcamp could please state the problem statement and then what you'd like to get done so we can chime in if needed?

**Comment by dashpole** [comment]
It essentially amounts to deleting imports from [prometheus/prometheus/discovery/install/install.go](https://github.com/prometheus/prometheus/blob/main/discovery/install/install.go) prior to building.  If the collector wanted to remove some of them, it would just need to replace the [import here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/prometheusreceiver/factory.go#L21) with a smaller list of imported service discovery implementations.  But i'm not sure if that is desirable, as this would remove those service discovery implementations for everyone.  They could, of course, re-add them in their custom builds of the collector, but the community build would be lack the ones we removed.

**Comment by jrcamp** [comment]
Prometheus has a component called [service discovery](https://github.com/prometheus/prometheus/blob/main/discovery/README.md) that can discover targets from Kubernetes, zookeeper, and many more sources. It is heavily tied to the Prometheus data model. From the docs:

> For example for EC2 tags, there would be __meta_ec2_tag_Description=mydescription for the Description tag. Labelnames may only contain [_a-zA-Z0-9], sanitize by replacing with underscores as needed.

The metadata is completely flattened and sanitized to conform to Prometheus’ model. The OpenTelemetry data model can accommodate more complex types. I don't think it's possible to reuse Prometheus discovery code without refactoring it first into some neutral non-Prometheus data model. That would be quite an undertaking. Additionally Prometheus is built around the notion that it knows exactly what data format will be scraped (usually expfmt). However with OpenTelemetry expfmt is only one of the formats we support in addition to scraping custom formats (e.g. a redis server with `INFO` output).

While I think it's worth looking it as an example I don't think there's anything there to directly leverage.

**Comment by alolita** [comment]
@jrcamp do you have an update or a design that you would like to share with us?

**Comment by mtwo** [comment]
Do we actually need this for GA, or could we add it later? My sense is that it isn't a blocker ...

**Comment by alolita** [comment]
My understanding is this isn't a blocker for metrics GA. It's a nice to have not a must-have.
