### ISSUE TITLE
Multiple Configuration File Support 

### ISSUE THREAD

**Issue by Aditya-Gollapudi** [open-telemetry/opentelemetry-collector#3544]
Continuation of this prior ticket: https://github.com/open-telemetry/opentelemetry-collector/issues/2701
Discussed at the 6/23 SIG Meeting
Design Doc: https://docs.google.com/document/d/1G7fX1xVk7T7KsCowJ-xkkNzqrWucRdyHveQqYbQ3WdA/edit#heading=h.mnb3vev0pb9q

We would like to support this feature as it will not only allow for users to simplify the complexity of their own configurations but it will allow Cloud Providers to provide users with a large default config file folder from which they can easily include their own small file to add on small customization or modify a single file in the folder rather than trying to understand the whole configuration.

The solution will need to have the following functionality:
- Each partial file submitted must be allowed to contain multiple kinds of components 
- Partial files should be able to reference components defined in other partial files
- Error attribution should remain clear

In order to implement this we suggest the following overall strategy
- We continue to accept a single file from the command line, the file submitted at the command line may (but doesn't need to) have an include section at the top. If it doesn't this is equivalent to just submitting a normal config file. Therefore this change isn't breaking
- We use Koanf to load each of the included sources and then use Koanf's cut functionality to break each section up into components, then merge them with Koanf's mergeAt. Using Koanf's unmarshall into map functionality we will keep track of while file each component came from allowing for error attribution and the detection of duplicate components
- For now we will not allow includes in anything other than the file that is directly submitted for simplicity of error attribution but are open to changing this if desired

**Issues**
- How will the included files be specified
- Will we allow nested includes e.g. file1 includes file2, file2 includes file3
- Will customers be able to set file-specific flags e.g. merging rules

**Comment by ttomsu** [comment]
Friendly ping - Has there been any movement on this recently?

**Comment by codeboten** [comment]
@bogdandrutu is this issue closed by https://github.com/open-telemetry/opentelemetry-collector/pull/4727?
