### ISSUE TITLE
OTel Receiver for Webhook

### ISSUE THREAD

**Issue by DDSharma1** [open-telemetry/opentelemetry-collector#3545]
**Is your feature request related to a problem? Please describe.**
Many a times the telemetry data comes in the form of webhooks (subscription based). Some of the sources that I have dealt with lately include AWS Firehose and Zoom. Currently, I don't see an option to consume a webhook in OTel Collector. Has it been considered in past and discarded?

**Describe the solution you'd like**
I 'd like to enable an endpoint on OTel Collector to consume the telemetry coming in via Webhook and enrich it before pushing it to a desired destination via OTel Exporters.  All webhooks use some sort of authentication. A popular authentication model is OAuth2. It will be good to have this feature be part of OTel. 

**Describe alternatives you've considered**
Some of the destinations offer a webhook consumption service e.g. Splunk HTTP Event Collector. But the challenge is that you don't have the flexibility of enriching and filtering the data before putting it to rest. OTel Collector in this case will provide the enrichment and filtering layer.

**Comment by bogdandrutu** [comment]
@alolita is this something in case of `AWS Firehose` that they can actually speak OTLP?

**Comment by alolita** [comment]
@bogdandrutu will take a look at this requirement and respond on this issue.
