### ISSUE TITLE
OTLP HTTP Receiver Endpoints Give 404

### ISSUE THREAD

**Issue by blakeroberts-wk** [open-telemetry/opentelemetry-collector#3582]
**Describe the bug**
All the otlp http receiver endpoints give 404s with example local config.

**Steps to reproduce**
```bash
# start the collector running default local config (no modifications)
$ make run

# try to curl the traces endpoint
$ curl -X POST 0.0.0.0:55681/v1/traces
404 page not found
```

**What did you expect to see?**
I tested both `v0.27.0` and `v0.28.0`
```
$ curl -X POST 0.0.0.0:55681/v1/traces
{

}
```

**What did you see instead?**
This is what you see starting with `v0.29.0`
```
404 page not found
```

**What version did you use?**
Version: `v0.29.0`

**What config did you use?**
Config: https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/local/otel-config.yaml

**Environment**
OS: macOS Big Sur version 11.2.3
Compiler(if manually compiled): `go version go1.16.5 darwin/amd64`

**Additional context**
I found this while upgrading a custom build I'm working on. I have a stable build using `v0.27.0`, but cannot upgrade to `v0.29.0` due to this issue.

**Comment by bogdandrutu** [comment]
Duplicate, same as https://github.com/open-telemetry/opentelemetry-collector/issues/3540 

You need to include the "Content-Type" if you do a curl request.
