### ISSUE TITLE
 Config: validate consistent use of separators (- vs _)

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#359]
In #321 we are going to make it consistent, we could validate that all `mapstructure:"xyz"` are using the proper separator. Add same validation to contrib repo and mention it on guidelintes to write components. Even if it is not perfect it should catch the typical mistakes in this regard.

**Comment by pjanotti** [comment]
After some conversation with @owais last week I'm thinking that perhaps a runtime validation is actually better: the same rule can be enforced for any project depending on OTelSvc so even if they don't use same build targets we can still enforce the consistency for rules like the consistent use of separators for yaml tags.

**Comment by pjanotti** [comment]
Adding to beta milestone since I think that can trip many if we are not consistent in this regard.

**Comment by pjanotti** [comment]
I'm going to start to work on this one. The plan is to enforce it via a runtime check (per comment above) using reflection when the configuration is loaded. I am changing the issue title to reflect that.

@ccaraman @tigrannajaryan @songy23 @bogdandrutu lmk if you have any Qs about it

**Comment by tigrannajaryan** [comment]
@pjanotti we should do this. However, it does not necessarily have to happen for Alpha v0.2. We can postpone this until next release to save time (we are tight for Alpha v0.2 release).

**Comment by pjanotti** [comment]
Agreed, removing from Alpha v0.2 together with a few others.
