### ISSUE TITLE
The LongCounters remains 0, when otel as receiver & promotheus as metric-exporter is configured. The same Counter with Double data-type works fine.

### ISSUE THREAD

**Issue by sonika-gautami** [open-telemetry/opentelemetry-collector#3602]
I'm using opentelemetry-collector 0.29.0 (latest tag ofo tel/opentelemetry-collector) with otlp with grpc protocol as Receiver, prometheus as Exporter for Metrics.
To send metrics data to otel-collector, I'm using java-instrumentation java-agent jar of version v1.3.1 opentelemetry-javaagent-all.jar.
I've added custom-metrics, one with longCounterBuilder & other with doubleCounterBuilder(bold text below) for same Metric.
longCounter remains 0, while doubleCounter works fine. Also, the auto-generated jvm specific counters remains 0.

```
REQ: <otel-collector-prometheus-endpoint>/metrics
RES: 
# HELP ana_info_req 
# TYPE ana_info_req counter
ana_info_req{app="nwdaf-app"} 0
# HELP ana_info_req2 
# TYPE ana_info_req2 counter
**ana_info_req2{app="nwdaf-app"} 1**
# HELP queueSize The number of spans queued
# TYPE queueSize gauge
queueSize{app="nwdaf-app"} 0
# HELP runtime_jvm_gc_count The number of collections that have occurred for a given JVM garbage collector.
# TYPE runtime_jvm_gc_count counter
runtime_jvm_gc_count{app="nwdaf-app"} 0
# HELP runtime_jvm_gc_time Time spent in a given JVM garbage collector in milliseconds.
# TYPE runtime_jvm_gc_time counter
runtime_jvm_gc_time{app="nwdaf-app"} 0
# HELP runtime_jvm_memory_area Bytes of a given JVM memory area.
# TYPE runtime_jvm_memory_area gauge
runtime_jvm_memory_area{app="nwdaf-app"} 0
# HELP runtime_jvm_memory_pool Bytes of a given JVM memory pool.
# TYPE runtime_jvm_memory_pool gauge
runtime_jvm_memory_pool{app="nwdaf-app"} 0

```

1] If I use in java-agent prometheus as exporter instead via otel-collector, above all metrics values are fine (not-zero).
2] I've also tried remote debugging java-agent for instrumenting, it sends values to collector fine. If needed I can provide one captured ExportMetricsServiceRequest json which is being sent by java-agent.
3] I tried to debug issue by adding Logging as Exporter. Here, I noticed all longCounter as DataType: DoubleSum.

**Comment by bogdandrutu** [comment]
@jkwatson what version of OTLP does that java-agent use?

**Comment by bogdandrutu** [comment]
@sonika-gautami if they use OTLP 0.8.0 or newer unfortunately we will still have this bug until 0.31 :( unless you will be willing to use a non-tag version. We are actively working on the switch to 0.8.0.

**Comment by jkwatson** [comment]
> @jkwatson what version of OTLP does that java-agent use?

As of java release 1.3.0 we are on OTLP v0.9.0

**Comment by sonika-gautami** [comment]
@bogdandrutu It should be fine for me to use non-tag version, please point me to branch/repo link.

**Comment by bogdandrutu** [comment]
@sonika-gautami not yet available, probably in few days :(

**Comment by sonika-gautami** [comment]
I'll continue with doubleCounter :)

**Comment by bogdandrutu** [comment]
@sonika-gautami can you give a try with the binary built from head?

**Comment by sonika-gautami** [comment]
@bogdandrutu I tried from Head, The longCounters are working fine; Also the auto-instrumentation metrics of jvm are also working. Thanks a lot !!

`# HELP nwdaf_noti_invokes 
# TYPE nwdaf_noti_invokes counter
nwdaf_noti_invokes{app="nwdaf-app"} 4
# HELP nwdaf_noti_invokes2 
# TYPE nwdaf_noti_invokes2 counter
nwdaf_noti_invokes2{app="nwdaf-app"} 4
....
runtime_jvm_gc_count{app="nwdaf-app"} 121
# HELP runtime_jvm_gc_time Time spent in a given JVM garbage collector in milliseconds.
# TYPE runtime_jvm_gc_time counter
runtime_jvm_gc_time{app="nwdaf-app"} 996
# HELP runtime_jvm_memory_area Bytes of a given JVM memory area.
# TYPE runtime_jvm_memory_area gauge
runtime_jvm_memory_area{app="nwdaf-app"} 2.70212432e+08
# HELP runtime_jvm_memory_pool Bytes of a given JVM memory pool.
# TYPE runtime_jvm_memory_pool gauge
runtime_jvm_memory_pool{app="nwdaf-app"} 1.13389976e+08`

**Comment by alolita** [comment]
@sonika-gautami Closing this issue since your problem seems to be resolved.
