### ISSUE TITLE
Get an official dedicated port for otlp/http

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3617]

**Comment by rakyll** [comment]
What about one of the following? Neither are not used by any other protocols.

```
6119 and 6120
O11Y

6835 and 6836
OTEL
```

**Comment by bogdandrutu** [comment]
We have "4317" for gRPC, is "4318" available?

**Comment by dyladan** [comment]
For what it's worth there are already documented ports in both the collector docs and the specification, but they don't match

>The specification says the default OTLP/HTTP port is 4317 [[link](https://github.com/open-telemetry/opentelemetry-specification/blob/faae76d4c936143e5a163ea4ab45b007486cda4f/specification/protocol/otlp.md#otlphttp-default-port)]
>
>The collector itself defaults to port 55681 [[code link](https://github.com/open-telemetry/opentelemetry-collector/blob/7e7ee8fb3a4b9535788ce484bfca1d27786433ab/receiver/otlpreceiver/factory.go#L34)] [[docs link](https://github.com/open-telemetry/opentelemetry-collector/blob/7e7ee8fb3a4b9535788ce484bfca1d27786433ab/receiver/otlpreceiver)]

_originally posted [as a specification issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1816)_

**Comment by rakyll** [comment]
What's the status on this issue? We need to set this before collector is announced to be stable.
