### ISSUE TITLE
Create a list of OpenTelemetry distributions

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#3620]
We need a wiki page (https://github.com/open-telemetry/opentelemetry-collector/wiki) for the community to list the OpenTelemetry distros. When we deprecate components or behavior in the core, we can use the list to be able to communicate the change. 

We can additionally also create a mailing list to send out announcement emails to distro maintainers. 

I don't have a privileges to create Wiki pages but am happy to curate an initial list if someone creates a page.

**Comment by atoulme** [comment]
I think we will go a different way on this. Closing for now.
