### ISSUE TITLE
Memory of agent cannot released

### ISSUE THREAD

**Issue by FreeZhang61** [open-telemetry/opentelemetry-collector#3635]
I've be received a alarm that the memory usage was more than the threshold in the evening,  Prometheus report the memory was unnormal

 as is shown:
![Screenshot 2021-07-16 at 3 11 14 PM](https://user-images.githubusercontent.com/19244981/125907280-4146e507-f550-44a9-97c4-582312bfb6d2.png)

The hightest  memory of agent was more than 800M and it was killed by OS. 

What kind of situation will cause the memory to rise ?

**Comment by alolita** [comment]
@FreeZhang61 Can you provide more details about your setup and configuration? Which Prometheus component were you using?

**Comment by atoulme** [comment]
Closing as old. Please try with a more recent release and report config and findings.
