### ISSUE TITLE
Move scrapererror to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3641]
Move [scrapererror](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/scrapererror) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
Not needed
