### ISSUE TITLE
Move scraperhelper to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3642]
Move [scraperhelper](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/scraperhelper) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
not needed
