### ISSUE TITLE
Move config/configgrpc to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3655]
Move [config/configgrpc](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configgrpc) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
Cannot be moved
