### ISSUE TITLE
Move config/confighttp to collector-config

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3656]
Move [config/confighttp](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
Cannot be moved
