### ISSUE TITLE
Move config/configloader to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3657]
Move [config/configloader](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/configloader) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
This cannot be moved, since "service" depends on this.
