### ISSUE TITLE
Move config/confignet to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3658]
Move [config/confignet](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confignet) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
Cannot be moved
