### ISSUE TITLE
Update examples to use OpenTelemetry configuration

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#366]
Example configs are outdated and reference opencensus notation instead of opentelemtry 
ex: https://github.com/open-telemetry/opentelemetry-service/blob/master/examples/k8s.yaml#L72-L101

Need to ensure the demo using the configurations doc is correct 
https://github.com/open-telemetry/opentelemetry-service/tree/master/examples/demo 
and the landing page readme.
https://github.com/open-telemetry/opentelemetry-service#kubernetes
https://github.com/open-telemetry/opentelemetry-service#standalone

**Comment by huikang** [comment]
@ccaraman qq: is the image used in the k8s.yaml the latest opentelemetry-collector release?
The image name indicates it is opencensus-collector. Thanks.

https://github.com/open-telemetry/opentelemetry-collector/blob/7486dae93d427844c43e5edf49f859ef4b730bb5/examples/k8s.yaml#L153

**Comment by ccaraman** [comment]
@huikang  good catch - yeah that is the opencensus code and not the otel release. I know we don't know who owns the current open telemetry docker, tracked by issue #281 . 
Omnition is publishing a docker image at https://hub.docker.com/r/omnition/opentelemetry-collector/tags that should be updated alongside with the other issues mentioned.
