### ISSUE TITLE
Move config/internal/configsource to collector-contrib

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#3664]
Move [config/internal/configsource](https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/internal/configsource) to [collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) until reviewed and verified as stable.

- [ ] Move
- [ ] Review
- [ ] Verify as stable

Part of #3474

**Comment by bogdandrutu** [comment]
This is used internally in the Service, cannot be moved. Implementation of the interfaces may be moved.
