### ISSUE TITLE
CLI for multiple configs in OTEL collector

### ISSUE THREAD

**Issue by Aditya-Gollapudi** [open-telemetry/opentelemetry-collector#3681]
**Is your feature request related to a problem? Please describe.**
Customers who wish to use the merge feature in Paolo's config source code will need to create a local file to specify the config source they plan on using. This is difficult on some systems so a way to do it strictly from the command line is preferred.

**Describe the solution you'd like**
We propose a new flag "--remote-config" which along with a URL can be submitted (possibly multiple times) which will then gather the various configs (including some potentially local ones) and merge them together

**Describe alternatives you've considered**
While this could be achieved by including a default config file in a distro and then abusing the existing --set flag this is an extremely inelegant solution that is unfriendly to customers

**Additional context**
Design Doc: https://docs.google.com/document/d/1XlDpS8-a4Ds6uoe6C6WgO8mCpDaQNufcHSEmBpiCdI0/edit

**Comment by bogdandrutu** [comment]
The default collector instance does not offer this yet, but you can offer this in your distribution.

**Comment by codeboten** [comment]
@bogdandrutu this is currently supported using schemes and config providers correct?

**Comment by bogdandrutu** [comment]
Closing, since this is supported right now via the map providers.
