### ISSUE TITLE
Benchmark passing of TraceData and MetricsData by value

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#369]
ConsumeTraceData and ConsumeMetricsData accept the structs by value. The struct are 8 and 4 words each and it is likely more efficient to pass them by pointer. Need to benchmark a typical (?) case and if the difference is non-neglible change to pass by pointer.

NOTE: double check that these structs are heap allocated in our codebase, otherwise we will introduce unnecessary allocation.

**Comment by bogdandrutu** [comment]
Passing by pointer will force a heap allocation I think, I am not a go expert.

**Comment by tigrannajaryan** [comment]
@bogdandrutu yes, that's correct, however I believe they are already heap allocated in majority of cases in our codebase, but for some reason we copy the struct instead of passing the value. I will add a note to double check this.

**Comment by bogdandrutu** [comment]
In Go you don't really know when something is heap allocated or not. It is up to the compiler to decide that so by returning a pointer we don't necessary heap allocate (again small knowledge about Go).

**Comment by tigrannajaryan** [comment]
True, it is not part of the spec. However, in practice Go compiler performs escape analysis and everything that escapes the function by pointer is heap allocated. If it stays local (does not escape) taking the pointer doesn't normally migrate it from stack to heap.
This is of course all implementation specific but that is the current Go compiler behavior.

**Comment by tigrannajaryan** [comment]
This is Go's official position on the topic (from https://golang.org/doc/faq#stack_or_heap):

> ### How do I know whether a variable is allocated on the heap or the stack?
> 
> From a correctness standpoint, you don't need to know. Each variable in Go exists as long as there are references to it. The storage location chosen by the implementation is irrelevant to the semantics of the language.
> 
> The storage location does have an effect on writing efficient programs. When possible, the Go compilers will allocate variables that are local to a function in that function's stack frame. However, if the compiler cannot prove that the variable is not referenced after the function returns, then the compiler must allocate the variable on the garbage-collected heap to avoid dangling pointer errors. Also, if a local variable is very large, it might make more sense to store it on the heap rather than the stack.
> 
> In the current compilers, if a variable has its address taken, that variable is a candidate for allocation on the heap. However, a basic escape analysis recognizes some cases when such variables will not live past the return from the function and can reside on the stack.

**Comment by bogdandrutu** [comment]
Obsolete, we transition to the new data model.
