### ISSUE TITLE
Receiver must not pass long-lived Resource and Node as a shared objects to processors

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#370]
Some receivers (e.g. OC) send the resource (and node) once and the receiver keeps a pointer to it and adds to all arriving data for which resource is not set. If the processor/exporter  modifies it, then all further data from the receiver will have that modified resource.

The solution for that is for receiver to clone the Resource before passing to fanout connector.

**Comment by bogdandrutu** [comment]
This is something that we cannot afford in a low-cpu usage deployments. We should not put this kind of limitations, and rather make a restriction on the consumers to treat every object as immutable and do copy-on-write.

**Comment by tigrannajaryan** [comment]
We can use the same "intent declaration" to decide if cloning is necessary or not. Proposal is here: https://github.com/open-telemetry/opentelemetry-service/issues/372

Note that a processor that correctly implements copy-on-write can safely report that it does not intend to modify the data, so we will not do cloning. In that case we will have best of both approaches: no cloning, shared data, copy-on-write and processor clearly declared its intent to not modify its input data.
