### ISSUE TITLE
Publish OTLP version mapping to collector version

### ISSUE THREAD

**Issue by vishiy** [open-telemetry/opentelemetry-collector#3736]
**Describe the solution you'd like**
It takes a while to figure the OTLP version used by collector. For example we moved to 0.8.0 OTLP few weeks back and out OTLP server needs to be ensured we are in the same version due to breaking changes. Though there will be less breaking changes as this matures, it will be useful to have a table of collector releases mapping to OTLP version(s) to refer.  

This could also be used by receivers as appropriate. ex;- prometheus receiver --> prometheus version dependency --> collector version - see related -

https://github.com/open-telemetry/wg-prometheus/issues/61
https://github.com/open-telemetry/opentelemetry-collector/issues/3732

**Comment by alolita** [comment]
@vishiy fwiw the Prometheus remote write exporter has implemented similar version info being conveyed as part of the user agent header. Take a look and let's discuss if a similar implementation can be added to the receiver.
