### ISSUE TITLE
How to sample based on attribute?

### ISSUE THREAD

**Issue by gionapaolini** [open-telemetry/opentelemetry-collector#3760]
I'm looking for a processor similar to the probabilistic_sampler in which I make the sampling decision based on the attribute of the span (error=true).
At first I thought I could use Span or Attribute processors, but those don't do any sampling decision.
Is there any way I can achieve this?

**Comment by bogdandrutu** [comment]
Removing the bug label since this is at most a feature request

**Comment by jpkrohling** [comment]
Take a look at the tail-based sampler: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor .  Is this what you want?

**Comment by gionapaolini** [comment]
> Take a look at the tail-based sampler: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor . Is this what you want?

I trying to do probabilistic sampling but always trace an error. 
I used that initially, but I'm not sure I understand how the rate_limiting works. It was giving me inconsistent results.

Then since I saw the plan to deprecate it, I tried using 2 pipelines: groupbytrace + probabilistic sampler, but I was missing a specific processor to only filter based on attributes.

But I think I will try the same approach with tail-based + probabilistic sampler, and in the tail-based config I only leave the filter by attribute policy. Is this a good approach for my scenario ?

**Comment by jpkrohling** [comment]
>but I was missing a specific processor to only filter based on attributes

If we do end up deprecating the tail-based sampler (we are not sure yet we will), we'll split out the policy part of it, making it part of another processor.

> But I think I will try the same approach with tail-based + probabilistic sampler, and in the tail-based config I only leave the filter by attribute policy. Is this a good approach for my scenario ?

It will work. I'm just a bit surprised that you want only a percentage of your error traces. Do you have that many traces with errors in them?

**Comment by gionapaolini** [comment]
No I meant normal probabilistic sampling, but if the trace contains an error then always log it. (common scenario I believe)
At first I was having some weird behavior when using a very low spans_per_second (probably due to my lack of understanding of the mechanism)

Now I'm using only a single pipeline with:

```
tail_sampling:
    decision_wait: 5s
    num_traces: 1000
    expected_new_traces_per_sec: 1000
    policies:
      [
          {
            name: test-policy-4,
            type: status_code,
            status_code: {status_codes: [ERROR]}
          },
          {
            name: test-policy-7,
            type: rate_limiting,
            rate_limiting: {spans_per_second: 35}
         }
      ]
```
And it gives me the expected results. Apologize for causing confusion, will close the issue for now
