### ISSUE TITLE
when start collector, a Prometheus metrics  service automatically started, can this start be disabled?

### ISSUE THREAD

**Issue by chengtangzheng2021** [open-telemetry/opentelemetry-collector#3871]
## Important (read before submitting)
We are currently preparing for the upcoming 1.0 GA release. Feature requests that are not aligned with
the current roadmap https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/roadmap.md
and are not aimed at stabilizing and preparing the Collector for the release will not be prioritized.

_Delete this paragraph before submitting._

**Is your feature request related to a problem? Please describe.**
when start the otel collector got message of:
 service/telemetry.go:99 Serving Prometheus metrics      {"address": ":8888", "level": 0, "service.instance.id":
If not use Prometheus receiver, the Prometheus service is not needed? if it is not needed, how to disable its start?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by bogdandrutu** [comment]
Right now, no. Soon it will be possible :)

**Comment by txomon** [comment]
Just in case the reason for this feature from our side is that when using the collector as an Agent, deployed as a sidecar, the hardcoded prometheus port of the Agent will interfere with the prometheus port of the application
