### ISSUE TITLE
Getting Started: There is no demo dir or docker-compose.yaml file

### ISSUE THREAD

**Issue by qingvincentyin** [open-telemetry/opentelemetry-collector#3916]
https://opentelemetry.io/docs/collector/getting-started/#demo
excerpt:
```
$ git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd opentelemetry-collector/examples/demo; \
    docker-compose up -d
```

That command is apparently expecting a file `./opentelemetry-collector/examples/demo/docker-compose.yaml`.

But there is no `demo` subdirectory. And there's no `docker-compose.yaml` anywhere in that entire repo.

**Comment by bogdandrutu** [comment]
Fixed.

**Comment by bogdandrutu** [comment]
Was moved to contrib, website updated
