### ISSUE TITLE
Allow Factories to support new signals

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3921]
The current Factory implementation for Receiver, Exporter do not allow new signals because interfaces cannot be extended:
1. Apply same model as https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/processor.go#L117
  - There are few options: we do the simplest with a Base struct in the package OR force everyone to use the helpers (by making the internal method part of an interface in the internal package). At this point probably the simplest option is the best. 
2. Use optional interfaces - this is a larger change (tried it once) because lots of tests are using the interfaces.

Requirement: Solution needs to be applied to all Factory interfaces.

**Comment by alolita** [comment]
@Aneurysm9 please take a look and file a PR :-)

**Comment by mx-psi** [comment]
I would be happy to take this one if @Aneurysm9 is busy

**Comment by mx-psi** [comment]
Decided to give it a try since it was easy to do; happy to close if work was already being done here
