### ISSUE TITLE
Rename `configparser.Parser` to `configmap.ConfigMap`?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3923]
The current `configparser.Parser` name does not sound very good. This struct does not do anything like parsing or unmarshaling since we have interfaces to parse the config from different sources and to Unmarshal it. Hence `ConfigMap` sounds like a better name.

**Comment by alolita** [comment]
+1 on renaming to ConfigMap since the usage is clearer than Parser.

@open-telemetry/collector-approvers please provide your opinion on this change. Ty!
