### ISSUE TITLE
Find the right place/name for current `ParserProvider` and relationship with `ConfigSource`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3924]
Ideally these 2 interfaces should be just one, conceptually they provide parts of the configuration (or full configuration).
1. The current path of the `ParserProvider` in service seems to be inconsistent with the rest of the configuration interfaces.
2. Try to unify the interfaces.

**Comment by alolita** [comment]
@Aneurysm9 can you please take a look and file a PR :-)

**Comment by codeboten** [comment]
Is this still an issue, if so please update the title/description with more information and I'd be happy to help resolve it.

**Comment by tigrannajaryan** [comment]
@codeboten this is definitely still necessary. See one possible desirable way to use the full-config provider and and value-config providers: https://github.com/open-telemetry/opentelemetry-collector/issues/4190

I am also looking for feedback on https://github.com/open-telemetry/opentelemetry-collector/issues/4190 from user experience perspective, if you have any thoughts.

Please let me know if you plan to take this, if not then I will see if I can find time to take it.

**Comment by alolita** [comment]
@codeboten can you work with @Aneurysm9 on this since he is looking at this and has been discussing with Bogdan.

**Comment by bogdandrutu** [comment]
This is done, the name is consolidated as `config.MapProvider`
