### ISSUE TITLE
Revisit the newly added APIs `pdata.AttributeValueToString` and `pdata.AttributeMapToMap`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3926]
1. Should they be funcs on the `pdata.AttributeValue.AsString()` and `pdata.AttributeMap.AsMap()`?
2. Can we make `pdata.AttributeMapToMap` consistent with `pdata.AttributeMap.InitFromMap()` when it comes to the returned type?
3. Can we change `pdata.AttributeMap.InitFromMap()` to a constructor func -> `pdata.NewAttributeMapFromMap()` to be consistent with trace ids, timestamp, etc.?

**Comment by codeboten** [comment]
I'm happy to take this on!

**Comment by alolita** [comment]
@bogdandrutu can you review #3939 please
