### ISSUE TITLE
[From 3474]: Remove defaultcomponents from core (probably make it internal for tests).

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3927]

**Comment by alolita** [comment]
@alexperez52 can you take a look and file a PR? ty!

**Comment by alexperez52** [comment]
> @alexperez52 can you take a look and file a PR? ty!

Gladly !

**Comment by JamesJHPark** [comment]
@alolita - Please assign me this issue

**Comment by alolita** [comment]
Hi @JamesJHPark assigned!

**Comment by alolita** [comment]
Completed.

**Comment by bogdandrutu** [comment]
@alolita this is not completed, there are still usages of the defaultcomponents package in contrib, and the package still exists. Please help finishing this.

**Comment by alolita** [comment]
@JamesJHPark can you take a look?

**Comment by jpkrohling** [comment]
We should now have a contrib distribution there so that the path is clear to start doing the same for contrib that was done for core in an earlier PR.

**Comment by atoulme** [comment]
Can we close this issue?
