### ISSUE TITLE
[From 3474]: Remove cmd/otelcol no longer needed.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3928]

**Comment by alolita** [comment]
@erichsueh3 can you please take a look and file a PR - ty!

**Comment by bogdandrutu** [comment]
One small caveat is that it will make testing locally harder, but probably we can use the builder tool to replace the cmd.

**Comment by alolita** [comment]
@codeboten @Aneurysm9 @anuraaga can you please review? Should be a quick one. Thx.

**Comment by alolita** [comment]
@erichsueh3 can you use the builder tool (chat w @Aneurysm9) to replace instead of remove cmd.

**Comment by erichsueh3** [comment]
Hi @bogdandrutu, just wanted to clarify what you're looking for from this issue and what you mean by using the builder tool to replace the cmd. Does #3992 approach this issue correctly? If not, what modifications are needed?

**Comment by bogdandrutu** [comment]
We need to still have a make rule that generates the binary and the docker for local debugging, but we should use the builder instead of the hand written main file

**Comment by erichsueh3** [comment]
@bogdandrutu, are there any more changes that need to be made?

**Comment by sincejune** [comment]
QQ: Previously, I can debug the collector with `Goland`. Is there any good alternative after `cmd/otelcol` was removed?

**Comment by bogdandrutu** [comment]
Run `make run`

**Comment by jpkrohling** [comment]
To expand on @bogdandrutu's previous message: running `make run` will also generate the sources, including the `main.go` that is the program's entrypoint.
