### ISSUE TITLE
Review `pdata.AnyArray.AppendEmpty()`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3930]
Currently this func makes things hard to use (or at least that's how I see them), see usage examples for primitives and also for Arrays/Maps.
1. We can change this to have `AppendString(str String)` and for all primitives. Then we can have for arrays/maps something like:
```golang
aMap := arr.AppendMap()
aMap.UpsertString(...)
```
2. We can ignore this, but only maybe change the name to `AppendNull()` so at least matches with what is happening since we named the AttributeValue null not empty? Or change the null to empty in AttributeValue?
3. Ignore completely this issue?

Needs some due diligence before making the final decision

**Comment by alolita** [comment]
Hi @Aneurysm9 can you please take a look and file a PR :-)

**Comment by bogdandrutu** [comment]
Moving to RC1 since ongoing discussion in the proto repo.
