### ISSUE TITLE
Pass Tracer/Meter Provider to http/grpc configs to record metrics

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3931]
Similar to https://github.com/open-telemetry/opentelemetry-collector/issues/3922 need to pass these providers to `configgrpc` / `confighttp` funcs that need to install the otel plugins.

**Comment by alolita** [comment]
@codeboten can you please take a look and file a PR?

**Comment by bogdandrutu** [comment]
@codeboten don't want to block the #3984, we should think if a better name is just "TelemetrySettings".
