### ISSUE TITLE
Broken links on opentelemetry-collector/processor/README.md

### ISSUE THREAD

**Issue by tmorrisonsfx** [open-telemetry/opentelemetry-collector#3958]
**Describe the bug**
404 page errors when clicking on some links under `Supported processors (sorted alphabetically):` on https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/README.md.

**What did you expect to see?**
I expected to go to the pages for those processors.

**What did you see instead?**
GitHub 404 error pages

**Additional context**
Are there new links for this information? If so, please add them, or remove the links that no longer work.

**Comment by suddendust** [comment]
I think this would have been removed after [this](https://github.com/open-telemetry/opentelemetry-collector/pull/3891) PR got merged.
