### ISSUE TITLE
receiver: add OpenCensus-PHP-Daemon

### ISSUE THREAD

**Issue by odeke-em** [open-telemetry/opentelemetry-collector#396]
Last year, we designed a daemon that'd receive stats from individual PHP processes and then apply aggregations on them before forwarding them to the agent as per https://docs.google.com/document/d/1CRiRq_wpzOuG9VKM_eaImcrS12Iie2V7LePnH9AwclU/ and it receives data via a UNIX Domain Socket. The daemon is currently present at https://github.com/census-instrumentation/opencensus-php/tree/1327147dc2ea99c06df01db4daa8c4ab2656514d/daemon.

That requires OpenCensus-PHP users to deploy that local daemon which is an extra tack on and not too flexible for OpenCensus-PHP users. This issue is a feature request for us to move that daemon as a receiver to the agent. I'll work on moving that here and linking it directly to the agent.

/cc @greggdonovan

**Comment by subnova** [comment]
The OpenCensus PHP daemon used a custom protocol between the PHP application and the daemon. If we expose the OpenCensus receiver on a UDS then we can use the JSON representation of the OpenCensus Protobuf and remove both the custom receiver code and use the standard protocol.

This same approach will work when we have an OpenTelemetry Protobuf representation.

**Comment by tigrannajaryan** [comment]
Is this still needed now that we have OpenTelemetry protobufs?

**Comment by rakyll** [comment]
Was this a PHP-specific request or a general request to be able to export metrics from short-lived processes so they can flush out individual metrics quickly and something aggregates them rather than reporting it one by one?

**Comment by alolita** [comment]
@odeke-em is this still needed given we're using protobuf now? Please close the issue if no longer relevant.

**Comment by odeke-em** [comment]
>Was this a PHP-specific request or a general request to be able to export metrics from short-lived processes so they can flush out individual metrics quickly and something aggregates them rather than reporting it one by one?

@rakyll it was for PHP but the solution indeed was to export metrics from short-lived processes!

>Is this still needed now that we have OpenTelemetry protobufs?
>@odeke-em is this still needed given we're using protobuf now? Please close the issue if no longer relevant.

@tigrannajaryan @alolita it wasn't about Protobufs though, but more for a daemon that'll allow isolated/short lived processes to send telemetry that'll be aggregated by delegation by the daemon The demand for it clearly isn't high so I shall close this otherwise. Thank you all!
