### ISSUE TITLE
max_recv_msg_size_mib is not set correctly

### ISSUE THREAD

**Issue by Doms61** [open-telemetry/opentelemetry-collector#3963]
**Describe the bug**
The property of "max_recv_msg_size_mib" for otlp receivers isn't set correctly. 

**Steps to reproduce**
Send a message which create a trace larger than the initial 4MB.

**What did you expect to see?**
All the spans correctly represented in jaeger.

**What did you see instead?**
Teared up traces/spans in jaeger and a log in otels terminal saying:
 `ResourceExhausted desc = grpc: received message larger than max (4576117 vs. 4194304)`

**What version did you use?**
otelcol version: [0.33.0
](https://hub.docker.com/layers/otel/opentelemetry-collector/0.33.0/images/sha256-c77b0addce02b287215a84e3966a62ae3bf36f2ff7be8401d76984a2d56da4ac?context=explore)also tried with [0.32.0](https://hub.docker.com/layers/otel/opentelemetry-collector/0.32.0/images/sha256-a1af818b9bb6c047433a6ff86a6cec1e63f7d67db17f3e2d0f132e6172768aae?context=explore)

**What config did you use?**
![image](https://user-images.githubusercontent.com/17786096/131826685-7b9e7373-f049-4b3c-ad6d-005a2c079f18.png)

**Environment**
> Docker
`docker run -p 4317:4317 -v "C:/.../otel/otel-config.yml":/otel-config.yml --name otelcol otel/opentelemetry-collector --config /otel-config.yml`

**Additional context**
I was referencing the [following issue](https://github.com/grafana/tempo/issues/860) for solving this, however their solution did not worked for me. And the same would apply for [this](https://github.com/open-telemetry/opentelemetry-collector/blob/03c7bf98f7edf6e578aac303e4d8b767f117541e/receiver/otlpreceiver/testdata/config.yaml).

**Comment by bogdandrutu** [comment]
@Doms61 thanks for filing this issue, unfortunately I cannot reproduce this, see also a unit-test to prove https://github.com/open-telemetry/opentelemetry-collector/pull/3968

Also based on the issue linked seems that is working for the others as well.

I can see something different, you are using windows, but that should not be a problem since you use a docker image....

How can we make progress on this? Any help for me to reproduce this would be appreciated.

**Comment by Doms61** [comment]
@bogdandrutu Thanks for looking into it. 
Yes, that is what bugged me the most, that seemingly it worked for everyone, except me. 

Well, I can think only of one think, and thats, I am running it incorrectly, or connecting to it incorrectly.

I can describe the whole process what I am starting and running, 
at first I am starting up jaeger with version [1.22](https://github.com/jaegertracing/jaeger/releases/tag/v1.22.0)
note: with jaeger-all-in-one on windows... if anywhere this is the issue
next I am starting opentelemetry-collector as described in the issue, with docker 
then starting up my app which basically receives some grpc requests processes them in a way and then returns a response and creates a trace with spans of each operation. pushed to jaeger. This is the custom config for our application 
![image](https://user-images.githubusercontent.com/17786096/131970730-69681681-652d-461a-b207-da8a93a38ec1.png)
and lastly, I am just sending the grpc requests from a different app, which also receives the responses

**Comment by bogdandrutu** [comment]
Now I think I have an idea :)

Which component does print the error? Is that the otel collector? I think the problem is not in the OTLP grpc communication between your client and otel-collector but in the grpc communication between otel-collector and jaeger backend. Does Jaeger have a similar property for their server? If yes consider to make that 100MB as well, if not consider to add the "batch" processor in the collector and enforce smaller batches to be sent to the exporter.

**Comment by Doms61** [comment]
Yes, the error is thrown from the otel collector.
I have just tried to add the "batch" processor, it still gives the same error.
![image](https://user-images.githubusercontent.com/17786096/131984153-a2bd83ec-b854-4503-ad93-4950cff3e8e8.png)
and the config looks like this:
![image](https://user-images.githubusercontent.com/17786096/131984415-308d86b7-23af-4dd4-a391-98145424c733.png)
note: I've tried with the size of 10_000 and 100_000 both scenarios resulted in the same outcome

**Comment by bogdandrutu** [comment]
The size in the grpc should be kept as 100, reduce the batch size to 1000 or even better 500. Again the error you get is not on the Otel collector grpc server but from the Jaeger grpc server.

**Comment by Doms61** [comment]
So the it somehow helped, however, reducing it down to 20 (22 is the most, I can do) 
![image](https://user-images.githubusercontent.com/17786096/132102794-a299f946-dfed-4048-bd8d-498744ebb233.png)

So, now I am just a bit curious, as to what downside will it have , to send each time 20 spans, when  the whole trace could have lot more. True, in our case it's up 90-100 . But performance wise could it have a large impact, or not really?

**Comment by jpkrohling** [comment]
It was added recently and should be available in 1.26, to be released soon.

**Comment by bogdandrutu** [comment]
@jpkrohling @Doms61 apparently 1.26 was released yesterday. So you should set that property on the Jaeger side and will be good.

I will close this, sine it is not a bug on our side.

**Comment by Doms61** [comment]
@bogdandrutu @jpkrohling thanks a lot, I will try it :)
