### ISSUE TITLE
AttributeValueBytes not checked in AttributeValue.Equal

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3995]

**Comment by codeboten** [comment]
Based on the title, I believe this is already done here:
https://github.com/open-telemetry/opentelemetry-collector/blob/72173fc5582933ec60748f8e1e65ea53fb0d7dfa/model/pdata/common.go#L373-L374
and tested here:
https://github.com/open-telemetry/opentelemetry-collector/blob/72173fc5582933ec60748f8e1e65ea53fb0d7dfa/model/pdata/common_test.go#L224-L232

Am I missing something?
