### ISSUE TITLE
Remove the AttributeMessageType for the moment

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3998]
See https://github.com/open-telemetry/opentelemetry-specification/commit/32ca5a72cb4c67084b92101f8abceee7ca35dee0#diff-a1d57f18f9d6d3b184ec51dbab905a6124f81afcd338c754cc9c203231c15859 where the proper semantic convention was added.

Not sure what the generated name will be but probably needs an update.

**Comment by hyunuk** [comment]
@Aneurysm9 Can you please assign me this issue? Thank you :D

**Comment by Aneurysm9** [comment]
This attribute is used in the following places in contrib:

```
internal/coreinternal/goldendataset/span_generator.go
exporter/awsxrayexporter/internal/translator/http.go
exporter/awsxrayexporter/internal/translator/segment_test.go
pkg/translator/opencensus/oc_to_traces.go
pkg/translator/opencensus/traces_to_oc.go
```

**Comment by bogdandrutu** [comment]
It is used, for the moment let's just hardcode there.

**Comment by Aneurysm9** [comment]
> It is used, for the moment let's just hardcode there.

Yup, that's the plan.  PRs inbound shortly.
