### ISSUE TITLE
Remove non-standard, not defined AttributeHTTPStatusText

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#3999]
Only "http.status_code" is defined.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/http.yaml#L43

**Comment by Aneurysm9** [comment]
This will impact the following components in contrib:

```
processor/probabilisticsamplerprocessor/probabilisticsampler_test.go
internal/coreinternal/goldendataset/span_generator.go
receiver/splunkhecreceiver/receiver.go
receiver/signalfxreceiver/receiver.go
exporter/awsxrayexporter/internal/translator/cause_test.go
exporter/awsxrayexporter/internal/translator/cause.go
exporter/awsxrayexporter/internal/translator/segment_test.go
exporter/azuremonitorexporter/conventions_test.go
exporter/azuremonitorexporter/conventions.go
exporter/datadogexporter/translate_traces.go
exporter/datadogexporter/translate_traces_test.go
```

Does this attribute need to be added to the semantic conventions spec?

**Comment by erichsueh3** [comment]
@Aneurysm9 can you assign me this issue? Thanks!

**Comment by bogdandrutu** [comment]
@Aneurysm9 not sure we can wait until then. Let's remove it for the moment and hardcode where is used for the moment. Maybe follow a tracking issue to define in specs and replace the hardcode
