### ISSUE TITLE
[Upcoming Release] Tracing Stability Requirements in Collector Core

### ISSUE THREAD

**Issue by alolita** [open-telemetry/opentelemetry-collector#4024]
Noting from discussion with @bogdandrutu, the three foundational stability requirements for the Collector core to be declared stable are:

- [x]  Ensure OTLP protocol is stable for traces
- [x] Tracing end-to-end feature including receiver ingesting OTLP data and exporting OTLP data is stable
- [ ] Configurations related to OTLP is stable in core - see https://github.com/open-telemetry/opentelemetry-collector/milestone/21

**Comment by bogdandrutu** [comment]
The remaining work is tracked in a separate milestone.
