### ISSUE TITLE
Cleanup after PR #3274

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4025]
1. Move persistent_queue in exporterhelper/internal similar to the current queue
2. Remove the configuration for persistent queue https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/queued_retry.go if not built with the unstable.

**Comment by tigrannajaryan** [comment]
@pmm-sumo can you take this, please?

**Comment by pmm-sumo** [comment]
> @pmm-sumo can you take this, please?

Of course, starting working on it @tigrannajaryan @bogdandrutu

**Comment by bogdandrutu** [comment]
Hey can we do the config change asap

**Comment by bogdandrutu** [comment]
@alolita we need this cleanup for config

**Comment by pmm-sumo** [comment]
> Hey can we do the config change asap

Apologies for the delay, I am preparing the separate PR's right now, should have the first one in ~1h or so
