### ISSUE TITLE
otel agent configuration does not in example/demo

### ISSUE THREAD

**Issue by huikang** [open-telemetry/opentelemetry-collector#403]
The configuration uses localhost, which does not accept traffic in the docker compose deployment

https://github.com/open-telemetry/opentelemetry-collector/blob/7486dae93d427844c43e5edf49f859ef4b730bb5/examples/demo/otel-agent-config.yaml#L7

**Comment by pjanotti** [comment]
Just for the record that the jaeger thrift receiver extracts the port from the endpoint and opens all net interfaces, this should be fixed per related issue #158
