### ISSUE TITLE
Cleanup `obsreporttest` package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4038]
* Avoid depending on `testing.T` and return errors.
* Prepare for when the switch to `TelemetrySettings` and MeterProvider will happen. The `SetupRecordedMetricsTest` need to return an `TelemetrySettings` + the exporters so that the checks will work with Otel.
* We can also consider to remove (hide) this package until the transition to Otel is completed.

**Comment by codeboten** [comment]
I can help with this.

**Comment by codeboten** [comment]
> We can also consider to remove (hide) this package until the transition to Otel is completed.
@bogdandrutu are you proposing we move the package to `internal` or just hide all the public methods?
