### ISSUE TITLE
obsreport.ExporterSettings missing `ExporterCreateSettings` field potentially causes segfault

### ISSUE THREAD

**Issue by Frefreak** [open-telemetry/opentelemetry-collector#4046]
After upgrading version, third-party exporter may still use the old way to create an exporter without noticing this change (note the absence of `ExporterCreateSettings`)
```go
		obsrep: obsreport.NewExporter(obsreport.ExporterSettings{
			Level:      configtelemetry.LevelNormal,
			ExporterID: conf.ID(),
			//ExporterCreateSettings: params,
		}),

```
and then in [obsreport_exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/obsreport/obsreport_exporter.go#L53) this may results in a nil pointer access.
This kind of feels like a breaking change and maybe should be mentioned in the CHANGELOG?

**Comment by bogdandrutu** [comment]
Sorry for missing this, I think at this point is useless to do anything, but you definitely are correct.
