### ISSUE TITLE
Move extension/storage to extension/experimental/storageextension

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#4059]
The package is experimental and is not following the package naming conventions of the extension packages.

**Comment by JamesJHPark** [comment]
@alolita - Please assign me this issue

**Comment by bogdandrutu** [comment]
@rakyll there is a difference between storage and a real extension. The storage is just an interface that other extensions are supposed to implement. Probably we should still use the naming conventions but wanted to point that out.
