### ISSUE TITLE
Tail Sampling - Implement Composite Policy

### ISSUE THREAD

**Issue by vikrambe** [open-telemetry/opentelemetry-collector#413]
Tail Sampling - Implement Composite Policy

**Comment by tigrannajaryan** [comment]
@vikrambe please add a link to the design doc. Feel free to copy it and modify as you see fit. You can ping maintainers here to have a look at the design doc and review/comment.

**Comment by vikrambe** [comment]
Design Document here https://docs.google.com/document/d/10wpIv3TtXgOik05smHm3nYeBX48Bj76TCMxPy8e1NZw/edit#heading=h.ecy5l2puwtp4

**Comment by tigrannajaryan** [comment]
@open-telemetry/collector-maintainers please review the design doc posted above.

**Comment by bogdandrutu** [comment]
Obsolete, tailbasesampling is no longer supported in code
