### ISSUE TITLE
Missing docker image for v0.36.0

### ISSUE THREAD

**Issue by F21** [open-telemetry/opentelemetry-collector#4141]
It seems that the docker image for `v0.36.0` is missing on docker hub: https://hub.docker.com/r/otel/opentelemetry-collector/tags?page=1&ordering=last_updated

Can the `v0.36.0` image be built so that it can be pulled from docker hub?

**Comment by codeboten** [comment]
I believe this is now fixed with the release here https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.36.0, please re-open if that's not the case.
