### ISSUE TITLE
collector not being able to send traces to zipkin. Getting a "connection reset by peer exception"

### ISSUE THREAD

**Issue by pranta** [open-telemetry/opentelemetry-collector#4155]
The opentelemetry collector is  not being able to send traces to zipkin. Getting a "connection reset by peer exception"

Collector config and log files attached.

Zipkin log file is also attached.

[zipkin.log](https://github.com/open-telemetry/opentelemetry-collector/files/7269022/zipkin.log)
[collector.log](https://github.com/open-telemetry/opentelemetry-collector/files/7269023/collector.log)
[collector.yml.txt](https://github.com/open-telemetry/opentelemetry-collector/files/7269026/collector.yml.txt)

**Comment by bogdandrutu** [comment]
We don't support sending to "v1" API, you must use the "v2" API

**Comment by pranta** [comment]
I tried v2 first and that didn't work as well - then tried v1 just in case.

**Comment by pranta** [comment]
Any ideas, guys?

**Comment by bogdandrutu** [comment]
The error says that path does not exists, based on https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md your endpoint should be `"http://127.0.0.1:9411/api/v2/spans"` and NOT `"http://127.0.0.1:9411/zipkin/api/v2/spans"` as you have.

**Comment by pranta** [comment]
Thanks @bogdandrutu  - that fixed it. Not sure how zipkin got in there. Probably confused with the UI url to see traces.
