### ISSUE TITLE
Include semantic failure codes in Receiver error messages as diagnostic log events

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-collector#4156]
For easy-filtering purposes, it'd be ideal to include HTTP (or gRPC) like status codes in failure logs that can help easily diagnose common failure scenarios.

This is highly applicable to receivers like `mysql`, `redis`, etc. where a connection is made to an underlying application and extracts metrics, logs or traces.

Specifically, we should be able to identify the following scenarios:

- UNAUTHENTICATED or PERMISSION_DENIED when connecting to the underlying resource
- UNABLE_TO_CONNECT as a generic fallback when we are unable to find the underlying resource (e.g. connection failure, file not found)
- INVALID_ARGUMENT, VERSION_MIMSATCH or some other identifier if the receiver gets data it did not expect (e.g. it issues a MySQL request for metrics and recevies unexpected data and logs this).

The goal would be to help quickly identify (via semantic IDs or log-attributes) issues in the collector itself so users can correct configuration.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5071 for an example usage and discussion.

Regarding @bogdandrutu's point on Go err, this is *not quite* the same as deciding to return err in the message. a Diagnostic log event could be created when the method is not considered to have failed.

**Comment by bogdandrutu** [comment]
@jsuereth looking at the example PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5071 I feel the right way is actually to create an "error" (user will forget to log the way you have it there, also "status_code" used there will definitely not be consistent).

We have to options:
1. Define "zap.Fields" for all the codes and expect that to be used when logging. I actually think components should not do that "intensive" logging, but maybe that is just my opinion. Why not adding these codes to the return error? Then if we log the error we get the information, but we also get it in the caller and we can check for the code to maybe do retries etc.
2. Define a "error { status_code, err }" that encapsulates an error and the status code associated with that. I think this is nicer, but looking for feedback.
