### ISSUE TITLE
gRPC balancing doesn't work with exporter

### ISSUE THREAD

**Issue by heruv1m** [open-telemetry/opentelemetry-collector#4179]
I have configuration as [documentation](https://github.com/grpc/grpc/blob/master/doc/naming.md) says
`exporters:
  jaeger:
    endpoint: "ipv4:firstHost:14250,secondHost:14250"
    balancer_name: "round_robin"`

Collector produces error.
How I can configure collector to balance exporter for sending requests in different backends?

> info    exporterhelper/queued_retry.go:276      Exporting failed. Will retry the request after interval.        {"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing dial tcp: address ipv4:firstHost:14250,secondHost:14250: too many colons in address\"", "interval": "30.456378855s"}

**Comment by Legion2** [comment]
in the official documentation at https://opentelemetry.io/docs/collector/configuration/#exporters in the example:
```yaml
...
  jaeger:
    endpoint: "http://jaeger-all-in-one:14250"
    tls:
      insecure: true
...
```
the protocol is part of the endpoint url resulting in `address http://jaeger-all-in-one:14250: too many colons in address` errors. Could you please update the documentation.
