### ISSUE TITLE
HistogramDataPoint should make defensive copies of slices

### ISSUE THREAD

**Issue by keep94** [open-telemetry/opentelemetry-collector#4181]
**Is your feature request related to a problem? Please describe.**
Setters of HistogramDataPoint that take slices and getter methods of HistogramDataPoint that return slices don't make defensive copies of those slices.  For instance if I call h.SetBucketCounts(counts), and I later want to change the counts slice, I can't change it without also changing internal state in my HistogramDataPoint object, h.  Likewise if I call counts := h.GetBucketCounts() and then I modify counts, then I've just modified internal state in h too.

**Describe the solution you'd like**
When a HistogramDataPoint method returns a slice, it shouldn't return the slice stored in the HistogramDataPoint. Instead
it should return a copy of the stored slice.  When a HistogramDataPoint setter method accepts a slice, it should store a copy of it, not the same slice from the caller. Otherwise the caller can accidentally change internal state of the HistogramDataPoint object.

**Comment by bogdandrutu** [comment]
Also we should look into all the places were we return a slice.

**Comment by bogdandrutu** [comment]
@dmitryax can you investigate all the places where we return "slices" of primitives (double, byte, etc.) in pdata?

**Comment by bogdandrutu** [comment]
@dmitryax should this be closed since you started the other issue?
