### ISSUE TITLE
OTLP exporter doesn't retry traces anymore once the export queue is full

### ISSUE THREAD

**Issue by VineethReddy02** [open-telemetry/opentelemetry-collector#4194]
**Describe the bug**
When the OTLP backend isn't accepting anymore traces for XYZ reasons. The otelcol keeps retries to send the traces. Once the retry queue is full. Otelcol silently just logs the errors even when the backend is available now. 
```
2021-10-08T12:34:00.961Z        INFO    loggingexporter/logging_exporter.go:41  TracesExporter  {"#spans": 15}
2021-10-08T12:34:00.961Z        warn    batchprocessor/batch_processor.go:184   Sender failed   {"kind": "processor", "name": "batch", "error": "sending_queue is full"}
```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Receive OTLP traces and export them to the backend that isn't available. 

**What did you expect to see?**
Better user experience, when this kind of error occurs. Maybe a better retrying mechanism would be great like retrying irrespective of queue size or dropping the oldest traces in the queue. 

**What did you see instead?**
 The collector doesn't send traces anymore once the retry queue is full. 

**What version did you use?**
`0.31.0`

**What config did you use?**
OTLP receiver and exporter

**Comment by bogdandrutu** [comment]
Inactive issue, closing seems to be fixed in the 0.31.0
