### ISSUE TITLE
Document how component developers can add metrics to their code

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4198]
Once the move from OC to OpenTelemetry SDK happens (#816), we need to enhance the contributing guideline with information on how component developers can add metrics to their own code. As part of this task, it should be evaluated whether it makes sense to add similar docs to the collector's documentation on the website.

**Comment by tigrannajaryan** [comment]
@djaglowski FYI.

**Comment by bogdandrutu** [comment]
@jpkrohling we already expose "MeterProvider" in the CreateParams (I know is a no-op) so components can start using that (will be some time until we will enable them though).

**Comment by jpkrohling** [comment]
This is at the top of my todo and will work on it soon.

**Comment by jpkrohling** [comment]
I created a PR as a first step towards defining the pattern we want to recommend to component developers.

**Comment by shubhanshus** [comment]
> I created a PR as a first step towards defining the pattern we want to recommend to component developers. I would like to ask everyone in this thread to take a look at it and share their thoughts.

@jpkrohling Do you mind sharing the PR link again? I can't seem to find the PR which talks about adding metrics to a component. I do see PR on checklist for components but can't find one which talks about adding more metrics.

**Comment by jpkrohling** [comment]
The PR I mentioned was a WIP to start a discussion but was ultimately closed. You can look at components like the load balancing exporter for an example of how to add metrics to a component, but we do not have official guidelines yet, as we are blocked by the availability of the OpenTelemetry Go SDK.
