### ISSUE TITLE
Document best practice configuration for memory limiter with ballast

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#4201]
**Is your feature request related to a problem? Please describe.**

The memory limiter readme https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md mentions that the ballast should be around 1/3 to 1/2 of the memory allocated to the collector. However it does not say if there is any relation between ballast and memory limiter

The helm chart sets `limit_percentage` to `80%` of the total memory, `spike_limit_percentage` to `25%` and ballast to `40%`.
This means that the GC runs roughly at the same time when the memory limiter kicks in. https://github.com/open-telemetry/opentelemetry-helm-charts cc) @dmitryax 

**Describe the solution you'd like**

Documentation that clarifies the relation between ballast and memory limiter setting.

**Describe alternatives you've considered**

Use what the https://github.com/open-telemetry/opentelemetry-helm-charts does.

**Additional context**

**Comment by atoulme** [comment]
See #8343 for next steps on this issue. We will likely move to remove the memory_ballast extension.
