### ISSUE TITLE
Capability to update otel configuration dynamically at runtime

### ISSUE THREAD

**Issue by squaw077** [open-telemetry/opentelemetry-collector#4205]
**Is your feature request related to a problem? Please describe.**
Need capability to update otel collector's configuration at runtime. In particular, need capability to add/remove exporters while collector is running.

**Describe the solution you'd like**
Solution in the form of api in otel collector that would allow to change configuration (add/remove exporters) remotely at runtime. Simple solution could be api that would allow to reload otel's collector configuration from file at runtime.

**Describe alternatives you've considered**
-Brute force solution involving restart of otel collector every time configuration changes.
-Building custom otel extension which will monitor configuration changes and apply those changes as they arrive

**Comment by bogdandrutu** [comment]
What distribution do you use? If you are talking about your own distro then this is already available

**Comment by bogdandrutu** [comment]
If you have a daemon already you can shutdown and start again the collector with the new file since that is what we do anyway internally.

**Comment by bogdandrutu** [comment]
Closing this because we will fix the file watch then you will be able to simply update the file.

**Comment by squaw077** [comment]
Just wanted to confirm if this feature has already been implemented. If so, please confirm which build it can be found in. Otherwise, please advise when are you planning to implement it.

**Comment by cforce** [comment]
@bogdandrutu  You closed the ticket but am also puzzled as well as @squaw077 if and how this feature is implemented and searching for an proper example  how to use properly. Would you be so kind and answer this questions, tx for support.

**Comment by spencerwilson** [comment]
@cforce , another link for your collection: https://github.com/open-telemetry/opentelemetry-collector/pull/6000, which was released in [v0.65.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.65.0). I've not tested it so YMMV.

**Comment by JellinekSara** [comment]
I would also be glad if someone could help me understand if there are any features that supports configuration updates at runtime. Let it be a watcher or some callable endpoint, but I'm really missing this feature and have no idea how to get the service read my updated configs.

**Comment by gongcon** [comment]
Same asking here. Sending SIGHUP to the process causes it restarting internally. From the log I can see the service shutdown and restart. Although the restart time is short, it still causes issue in our high traffic environment.

**Comment by rohang98** [comment]
I'm also wondering about the same capability. Can we reopen this ticket?

**Comment by cforce** [comment]
Check the opamp docs and opam extension for collector in control project. 
There are two options available:
a.) opamp extension in collector connect directly to omap server on another host also let you remote configure the cfg almost real time but opamp extension might restart the collector itself. It could be dangerous if something goes south and collector does not come back properly connected to the opamp backend again to give back con to to fix the buggy cfg
b.) The opamp extension of the collector connect to a same host or same cluster(k8) supervisor (also hosted in collector contrib project) as realy to the opmap backend. The supervisor as its name supervisees the collector by health during and after the restart  which ts executed with pri9viledge by the supervisor as well. This gives the solution the advantage to recover and also continuously monitor the monitor from an "safe position" whatever goes south go stay in the driver seat, even to replace the binary of the collector

**Comment by gongcon** [comment]
Based on the doc, opamp is not for production yet (60% progress). @cforce, you mentioned that "opamp extension might restart the collector itself". Isn't this what we are trying to avoid? The major issue for us is the tail sampling process losses all in-memory traces when the collector restarts. Ideally, it support a hot config swap like what Refinery does.

**Comment by cforce** [comment]
Then you shall add the tail sampling  need as supervisor/opamp requirement . by a new feature request with the components supervisor/opamp extension tagged.
If you are right its indeed a limitation of the opamp concept which shall be tackled.

**Comment by mithunbelur** [comment]
I am facing the same issue. Otel collector is bundled with our own daemon/container.
Is there a way or pointers in the code to add/delete receiver configs and udpate the pipeline to use/remove this new receiver.
Or Is there a way to just add new pipeline with new set of receivers without touching other pipelines?
Both SIGHUP/ or calling otelcollector.Shutdown() followed by otelcollector.Run () does restart the existing pipeliens and their components.
