### ISSUE TITLE
Turn expand map provider into envexpand map provider

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/opentelemetry-collector#4222]
## Description
While trying to debug a breaking change it was hard for me to figure out there was a struct that would expand env vars as in https://github.com/open-telemetry/opentelemetry-collector/pull/4146/files#diff-0cbd9b3909b072d06aaaa01873e3543a0f20146f7c55fd7837e65bd488b91047R38. I think for discoverability and readability matters we could rename it to envexpand and turn `NewExpandMapProvider` into `NewEnvExpandMapProvider`.

Related to https://github.com/open-telemetry/opentelemetry-collector/pull/4098#issuecomment-947457653

cc @bogdandrutu

**Comment by bogdandrutu** [comment]
I am a bit confused about the comments/issue. Is this https://github.com/open-telemetry/opentelemetry-collector/pull/4098#issuecomment-947457653 still an issue? Where do you pass envvars and is not working?
