### ISSUE TITLE
Choose or design a management protocol

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4225]
We want to have an open agent management protocol that can be used by OpenTelemetry Collector as well as any other agent that requires similar management capabilities (including other open-source and closed-source agents).

The protocol should have the following characteristics:

- Open. The specification should be openly available for anyone to implement.

- Vendor-neutral and project-neutral. It needs to be highly suitable for any data collection agent, not just OpenTelemetry Collector.

- Composable. Cohesive set of rich capabilities to cater to a variety of agent needs, but allow implementations to choose a subset that they want to support.

- Frugal. Should have minimal requirements to the underlying infrastructure, capabilities-wise. It should not place requirements that are difficult to fulfil. Should work with all cloud providers, load balancers and other networking equipment, should be standards-based to be usable with widely available troubleshooting and supporting tools.
 
- Efficient. It should be possible to easily manage a fleet composed of millions of agents without having excessive requirements for the management infrastructure and servers.

- Flexible. The protocol should be flexible enough to allow implementations to choose from a spectrum of management sophistication, from the simplest solution that just give the same configuration to every agent to complex management tools with UIs, access control, group policies, etc.

- Secure. Should be secure itself (encrypted, resilient to bad data, excessive loads, etc), but also enable and encourage participants to operate securely.

**Comment by sl1316** [comment]
@tigrannajaryan can you share the draft if there is any? We are interested in the collector management for both "run as agent" and "run as collector" and may contribute to it if possible

**Comment by tigrannajaryan** [comment]
@sl1316 see https://github.com/open-telemetry/opamp-spec repo for protocol spec work and https://github.com/open-telemetry/opamp-go for Go implementation.

**Comment by tigrannajaryan** [comment]
Closing this since protocol has its own repo now.
