### ISSUE TITLE
Unclear how to use WatchableMapProvider to work for more than once

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4236]
I tried creating a custom MapProvider which is also a WatchableMapProvider.

The MapProvider parts works as expected. At the startup the MapProvider.Get() method is called and when it returns a Map the config is correctly loaded from that map.

After that the service calls WatchableMapProvider.WatchForUpdate() as expected, which my implementation blocks until it has something new. When that new config is available WatchForUpdate() returns with nil error. 

The service then calls MapProvider.Close() because it is shutting down and then immediately calls MapProvider.Get() because it is starting.

At this point it is not clear what should Get() return because Close() was called. Why is Close() called? What's the purpose of that? Is it expected that Get() will be called after Close().

Finally, after the Get() call returns WatchForUpdate() is called again.

So, essentially this is the sequence of the calls I see from the service:
1. Get()
1. WatchForUpdates() // Blocks until there is something new.
1. Close()
1. Get()
1. WatchForUpdates() // Returns ErrSessionClosed because Close() was called.

It seems like either Close() should not be called here or there must be a corresponding Open() call before the next Get() happens.

The intended usage is unclear.

If I don't actually close my MapProvider and clear the resources in the Close() call then there is no other place to do it.

I think instead we should see this:

1. The Service starts.
1. MapProvider.Get() is called
1. WatchableMapProvider.WatchForUpdates() is called // Blocks until there is something new.
1. The Service restarts.
1. MapProvider.Get() is called
1. WatchableMapProvider.WatchForUpdates() is called // Blocks until there is something new.
1. ... previous 3 steps repeated 0-N times.
1. The Service is stopped for the last time.
1. MapProvider.Close() is called
1. Previously blocked WatchableMapProvider.WatchForUpdates() returns with ErrSessionClosed
1. TheService process exits.

**Comment by bogdandrutu** [comment]
One of the solution I had in mind (did not get enough attention) is https://github.com/open-telemetry/opentelemetry-collector/pull/4029. So you "retrieve" an object that contains some parts of the config and that object is watchable.

**Comment by tigrannajaryan** [comment]
Solved by https://github.com/open-telemetry/opentelemetry-collector/pull/4270

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/4270 does't fully solve this. The Watchable capability is not propagated through `expandMapProvider` and `mergeMapProvider` so even if the nested `fileMapProvider` is Watchable it doesn't work.

Perhaps the `expandMapProvider` and `mergeMapProvider` need to be refactored to pass through "watchability" or some other solution is needed.

**Comment by bogdandrutu** [comment]
Unrelated with the initial issue. Consider to open separate issue for that.
