### ISSUE TITLE
How to generate collector own metrics 

### ISSUE THREAD

**Issue by goswamisandeep** [open-telemetry/opentelemetry-collector#4244]
**Describe the bug**
We want to create a pipeline with inbuilt and our own custom processors/receievrs/exporters . We want to generate collector metrics too as indicated in https://github.com/open-telemetry/opentelemetry-collector/blob/1e5cd148fded7766540ac6bb1a1690901b4ae0b4/docs/observability.md#what-needs-observation . But there are no examples . Please let us know 

**Steps to reproduce**
N/A

**What did you expect to see?**
collector own metrics getting generated .

**What did you see instead?**
Vague documentation with no examples

**What version did you use?**
Version: (e.g., `v0.37.0')

**What config did you use?**
NA
**Environment**
NA

**Additional context**
Help Wanted

**Comment by adirmatzkin** [comment]
Is this even a thing ? I haven't found anything more than what @goswamisandeep mentioned...
How can you monitor / observe the collector ? 
The shoemaker's children go barefoot :(
