### ISSUE TITLE
feature request: compatibility between published Go types to collector's own types

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-collector#4254]
Right now it's not easily possible to covert data that was constructed using published Go types ([`go.opentelemetry.io/proto/otlp`](https://pkg.go.dev/go.opentelemetry.io/proto/otlp)) and the internal version of the same ([`go.opentelemetry.io/collector/model`](https://pkg.go.dev/go.opentelemetry.io/collector/model)). This makes it very complicated for someone to build a collector component externally, e.g. they need to fork the collector repo or do other tricks, like marshalling and unmarshalling. Some types can be constructed using exported helpers, but it's hard to work with those and many fields are not settable.

**Comment by bogdandrutu** [comment]
This is intentionally, and encourage to construct use directly the `go.opentelemetry.io/collector/model/pdata` instead of `go.opentelemetry.io/proto/otlp`

**Comment by bogdandrutu** [comment]
Alternative you can "Marshal" the go "otlp" and unmarshal as "pdata"

**Comment by errordeveloper** [comment]
> This is intentionally, and encourage to construct use directly the `go.opentelemetry.io/collector/model/pdata` instead of `go.opentelemetry.io/proto/otlp`

I found it very limited and unintuitive to use.

**Comment by errordeveloper** [comment]
> Alternative you can "Marshal" the go "otlp" and unmarshal as "pdata"

Sure, if you don't care about performance...

**Comment by bogdandrutu** [comment]
" many fields are not settable." all the fields are settable, we are actually using them to construct everything.

**Comment by errordeveloper** [comment]
I've tried, and couldn't rewrite this code: https://github.com/cilium/hubble-otel/blob/acc3a282a62b35fa432b1d47200904082fbaf797/common/common.go#L178

**Comment by errordeveloper** [comment]
@bogdandrutu this illustrates what I am actually referring to:

https://github.com/open-telemetry/opentelemetry-collector/blob/db6d31e9acc546e043b7b5564377bd76998e74bd/model/pdata/generated_trace.go#L179-L184

The thing is that Inside the collector you can set any fields you like cause internal structs can still be accessed, but not in another project... You see what I'm saying now?

**Comment by bogdandrutu** [comment]
@errordeveloper no I don't see what you are trying to say. If you need to create a new "ResourceSpans" you do from top to bottom:

```
td := pdata.NewTraces()
rs := td.ResourceSpans().AppendEmpty()
```

vs

```
rs := pdata.NewResourceSpans()
pdata.NewTraces().Append(rs) // or Set.
```

This is optimal to reduce the amount of allocations, as well as avoid common mistakes as "sharing" the same object between multiple data objects.
