### ISSUE TITLE
Allow to revert configuration updates on fatal errors

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4264]
Currently when an error happens during component startup it is reported via `Host.ReportFatalError()` which results in terminating the Collector.

This can happen for example if the component attempts to start asynchronously and discovers that it cannot listen on a port or for some other reason the configuration may be incorrect and start can fail.

The current behavior is completely justified since we want the startup problems to be immediately visible to the user so that they can fix it.

However, assuming that we implement remote configuration capabilities this behavior is highly undesirable _if_ configuration changes are coming from remote sources. It is possible that a bad configuration is pushed from a remote source. In this case the desirable behavior is to detect that it is a bad configuration and revert back to the last known good configuration (and report the failure to the remote source if such reporting is possible).

This is currently impossible to implement. The Collector process terminates immediately when ReportFatalError() is called.

One possible solution to this is to allow overriding the default behavor of ReportFatalError(). When used with local config file it behave as it does currently. When used with remote config sources it may be overridden to report the error back to the configuration source (or ConfigProvider) which can then revert the config changes.

One deficiency of the proposed solution is that ReportFatalError() may be called because of a truly fatal error and not because of configuration errors. If we believe that this is possible we may want to add an option to ReportFatalError() so that the caller provides more information about the nature of the failure and the Collector then can behave differently for the configuration failures vs other fatal errors.

Thoughts and other proposals are welcome. It is not entirely clear to me yet how we solve this correctly.

**Comment by bogdandrutu** [comment]
Will not fix inside the collector. The "supervisor" can do this, the collector config logic will not support this behavior.
