### ISSUE TITLE
Make Collector instance ID available to config.MapProvider 

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4272]
The Collector currently generates a random instance ID in colTelemetry.initOnce() and uses the the value as the "service.instance.id" attribute in the reported telemetry. This is good and is expected.

Unfortunately this value doesn't seem to be accessible anywhere. In particular config.MapProvider needs the instance ID to report it to the management server to fetch the configuration for the particular Collector instance. See [Remote Configuration Proposal](https://github.com/open-telemetry/opentelemetry-collector/issues/2374) for description of how the instance id can be used.

Maybe we need to make the instance ID available to config.MapProvider by some means. Perhaps it can be a readable property of the Host and Host is passed as a parameter to config.MapProvider.Get(). Note that config.MapProvider is created very early, before colTelemetry.initOnce() is called, so it is not good enough to make instance ID a public property of the `Collector`. It is too late, by the time `Collector` is created `config.MapProvider` should be created already.

**Comment by tigrannajaryan** [comment]
This should be likely replaced by https://github.com/open-telemetry/opentelemetry-collector/issues/5398 instead.

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector/issues/5398 is done
