### ISSUE TITLE
Produce releases from this repo

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#4276]
Once the collector builder #4275 is moved into the core repo, the [releases repository](https://github.com/open-telemetry/opentelemetry-collector-releases/) is no longer necessary. This issue tracks moving the functionality from that repo into the core repo.

**Comment by jpkrohling** [comment]
> in that case I wonder if it makes sense to continue having a separate repo to track releases

The original plan was to have all distributions being built from there, potentially having more distributions in the future ("sidecar" comes to mind). Right now, we have only the core distribution being generated there, which is indeed odd.
