### ISSUE TITLE
Improve `go mod download` retry to test for transient failures

### ISSUE THREAD

**Issue by eroteme** [open-telemetry/opentelemetry-collector#4313]
A basic retry for the `go mod download` exec has been added but this could be improved by trying to capture if the download is a transient error and if it should retry.

**Comment by sakshi1215** [comment]
@jpkrohling @dmitryax As far as I was able to get from the issue, this issue wants us to add a retry+wait logic over here https://github.com/open-telemetry/opentelemetry-collector/blob/139cd3db7139c45d84edf9cac877bfa8d0ab84ab/Makefile.Common#L52 ? If yes, can I get assigned to this issue?

**Comment by dmitryax** [comment]
@sakshi1215, assigned

**Comment by atoulme** [comment]
Is this issue still occurring? Is it still being worked on? I advise closing as not planned after 2 weeks unless there is an update.

**Comment by jpkrohling** [comment]
> Is this issue still occurring?

Likely, but I haven't heard anything about this recently.

> Is it still being worked on? I

No.

**Comment by andrzej-stencel** [comment]
Closing as not planned as there has been no update for the last couple weeks.
