### ISSUE TITLE
Sort out the release process for the builder

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4314]
The builder is currently using goreleaser to manage the binaries we want to generate. With the move to this repository, we need now a feature that is available only in the "Pro" version. I think it's worth it and would like to ask the maintainers whether I have the green light to request a budget from the CNCF to expense it.

@open-telemetry/collector-maintainers, could you please give a 👍🏽 or 👎🏽 ? If the consensus is to not use goreleaser, then we'll need to invest engineering time to create build scripts that generate the binaries we had for the builder before:

![image](https://user-images.githubusercontent.com/13387/139434003-21d792bf-f9be-454b-afc6-b0a9539af1ff.png)

**Comment by jpkrohling** [comment]
ping @open-telemetry/collector-maintainers

**Comment by bogdandrutu** [comment]
I am fine to use goreleaser, do what you have to do to simplify our life :)

Also let me know if I need to setup anything in the repo.

**Comment by jpkrohling** [comment]
All I need is a secret with `GORELEASER_KEY` :-)
