### ISSUE TITLE
setting `service::telemetry::logs` to debug is ineffective

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-collector#4328]
I've tried setting `service::telemetry::logs` to `DEBUG` and `debug`, but it's not enabling debug logs. The config value does get parsed for sure, as something like `debugz` throws a fatal error.

**Comment by floyola** [comment]
Which version are you using?
I had the same problem with the 0.36.0
I upgraded it to the 0.38.0 and now it works :)

**Comment by errordeveloper** [comment]
I'm using a custom collector based on 0.38.0. If this was broken in 0.36.0, would be good to know what commit fixed it...

**Comment by codeboten** [comment]
@errordeveloper is it possible for you to paste the errors you're seeing emitted when enabling the `--set=service.telemetry.logs.level=debug` option?

**Comment by errordeveloper** [comment]
> @errordeveloper is it possible for you to paste the errors you're seeing emitted when enabling the `--set=service.telemetry.logs.level=debug` option? 

I don't see any errors, just info messages and no debug messages.
But, I have only set it via config, should I try setting it this way? I wouldn't expect it to be any different, but perhaps there is a bug... Hm.

**Comment by codeboten** [comment]
> > @errordeveloper is it possible for you to paste the errors you're seeing emitted when enabling the `--set=service.telemetry.logs.level=debug` option?
> 
> I don't see any errors, just info messages and no debug messages. But, I have only set it via config, should I try setting it this way? I wouldn't expect it to be any different, but perhaps there is a bug... Hm.

Ah I see, I misread the last part of the issue description. What information are you looking for specifically?

I remember finding that the `service::telemetry::logs` setting not allowing me to see debug information about traces/metrics/logs being emitted was confusing at first. Then I realized that it made sense to use a logging exporter instead.

**Comment by errordeveloper** [comment]
> > > @errordeveloper is it possible for you to paste the errors you're seeing emitted when enabling the `--set=service.telemetry.logs.level=debug` option?
> > 
> > I don't see any errors, just info messages and no debug messages. But, I have only set it via config, should I try setting it this way? I wouldn't expect it to be any different, but perhaps there is a bug... Hm.
> 
> Ah I see, I misread the last part of the issue description. What information are you looking for specifically?

I just want to see debug logs from a receiver that I wrote, and from other receivers I am debugging. That's what '--log-level' flag did previously.

> I remember finding that the `service::telemetry::logs` setting not allowing me to see debug information about traces/metrics/logs being emitted was confusing at first. Then I realized that it made sense to use a logging exporter instead.

Ok, I think this is very very misleading, if that is what's going on. I also got fairly confused when I read somewhere in the code that value is supposed to be 'detailed', but I am not sure what that was meant for, as the struct actually maps to 'zap.LogLevel' type.

**Comment by errordeveloper** [comment]
> @errordeveloper couple of questions:
> 
> * Did you also set the deprecated flags?

It's not recognised in 0.38.0, and in 0.37.0 it was already ineffective.
 
> * Can you show me the full `service::telemetry::logs` section?

https://github.com/cilium/hubble-otel/blob/d0e1ec99a31c457166d178199449a50f88631f43/testdata/collector-with-tls.yaml#L36-L39

> * Does it work for you now in 0.38.0?

No.

**Comment by bogdandrutu** [comment]
Do you use the windows service? Where do you run this?

**Comment by errordeveloper** [comment]
I run this in a container on Linux.

**Comment by RedlineTriad** [comment]
I also have the problem that even after setting the `service:telemetry:logs:level` to debug I still can't get the output from: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/db83dbb40f947daced9e1010a2e39d218049e88f/exporter/lokiexporter/exporter.go#L184

```yml
service:
  telemetry:
    logs:
      level: "debug"
```
Maybe I am doing something wrong but I didn't find anything in: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md

**Comment by verysonglaa** [comment]
I got the same problem in 0.41.0.
I just want to see the debug logs from a custom exporter.

**Comment by ronakk-google** [comment]
Do we have any workaround for this?
