### ISSUE TITLE
Add timeout to confignet

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector#4331]
**Is your feature request related to a problem? Please describe.**
When dialing, there should be a configurable timeout in these configs. Without these, no timeout is used and depending on the protocol and OS, may take a large amount of time to timeout or not timeout at all.

**Describe the solution you'd like**
Add a `timeout` parameter and use it with net.DialTimeout, allowing a configurable timeout when dialing.

**Comment by TylerHelmuth** [comment]
Please assign this to me
