### ISSUE TITLE
Ensure OTLP receiver handles consume errors correctly

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4335]
See the [requirements for receivers here](https://github.com/open-telemetry/opentelemetry-collector/blob/b2961b799e2c1ec128f0539764af1fa10c839e04/receiver/doc.go#L21).

OTLP/HTTP receiver needs to:
- Return [429 or 503 responses](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-throttling) on non-permanent errors.
- Return [400 response](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#bad-data) on permanent errors.

OTLP/gRCP receiver needs to:
- Return [Unavailable](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-throttling) on non-permanent errors.
- Return [InvalidArgument](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#failures) response on permanent errors.

**Comment by pmm-sumo** [comment]
I think this issue might cover the idea for using gRPC error codes to have a more detailed description of cause of error returned to the client discussed during the Collector SIG today (in the context of backpressure handling). I'm not creating a new one. Let me know if you think otherwise

**Comment by tigrannajaryan** [comment]
@VihasMakwana sure, it would be great if you can work on this.

Please make sure you read the latest OTLP spec to make sure your implementation matches it: https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md

You can also use [receiver contract checker](https://github.com/open-telemetry/opentelemetry-collector/blob/50c94c941969c8990a6bae3a247c18ea81037977/receiver/receivertest/contract_checker.go#L70) to test the behavior.

**Comment by VihasMakwana** [comment]
Ok, for testing, does the above contract checker cover the scenarios for network-based receivers? 
for otlp/http we just return 503/400 response. I think we also need a test suite that implements retry from the client side?

**Comment by tigrannajaryan** [comment]
> I think we also need a test suite that implements retry from the client side?

Yes, need a client that implements the retries correctly and use it in the test. I think having that you can then use the contract checker to verify that otlp sender+otlp receiver combo reacts correctly to the errors it receives from the pipeline.

**Comment by atoulme** [comment]
At the very least please add coverage for your code changes to help maintain this code moving forward.

**Comment by mx-psi** [comment]
Did #8080 fix this?

**Comment by VihasMakwana** [comment]
@mx-psi Yes, i think we can fix this.

**Comment by mx-psi** [comment]
Thanks for confirming!
