### ISSUE TITLE
Define semantic convention constants

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#435]
There are at least 2 pending PRs that define these conventions individually. There is a clear need for defining this and the best place to do it is in this repo so that it can be used by all components.

I suggest that the conventions are defined in a new `translator/conventions/opentelemetry.go` file.

Conventions to be defined: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-semantic-conventions.md

**Comment by kbrockhoff** [comment]
I am working on this.
