### ISSUE TITLE
Need for Batch processor to back propagate the error to the preceding component

### ISSUE THREAD

**Issue by neelayu** [open-telemetry/opentelemetry-collector#4352]
**Is your feature request related to a problem? Please describe.**
The batch processor doesn't propagate the error back to the preceding component, in case the Consume*() throws an error. I believe this could be due to the limitations of the code design(using go routines).
But it would be a nice to have feature, being consistent with other processors.

**Describe alternatives you've considered**
Probably return the error from [here](https://github.com/open-telemetry/opentelemetry-collector/blob/c24dfeb047a8d0ca4c5a210c305be8ea80c10994/processor/batchprocessor/batch_processor.go#L184)

**Additional context**
NA

**Comment by bogdandrutu** [comment]
It is impossible to do that unless you make the Consume* method on the batch itself blocking for the "timeout" period which you don't want.
