### ISSUE TITLE
OpenTelemetry Collector Builder is no longer available as a downloadable asset

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/opentelemetry-collector#4359]
Since the move of [the OpenTelemetry Collector Builder repository](https://github.com/open-telemetry/opentelemetry-collector-builder) to the main **OpenTelemetry Collector** repository, the compiled binaries are no longer available for download.

**Previously**: [v0.37.0 of the Collector Builder released assets with compiled binaries](https://github.com/open-telemetry/opentelemetry-collector-builder/releases/tag/v0.37.0)

**Now**: [v0.38.0 of OpenTelemetry Collector released assets have source code only](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.38.0)

It is expected to be able to download the compiled binaries of the Collector Builder to create a Collector, without having to build the builder itself.

**Comment by tigrannajaryan** [comment]
@jpkrohling will you be able to take this?

**Comment by jpkrohling** [comment]
> It is expected to be able to download the compiled binaries of the Collector Builder to create a Collector, without having to build the builder itself.

That's absolutely correct and should be fixed by 0.39.0. The 0.38.0 release happened while we were doing the move, and one of the last pending items is indeed about integrating the builder in the release process (#4314). Do you need the builder at 0.38.0 for some reason, or can you wait for 0.39.0, which should be available in less than two weeks?

**Comment by bertysentry** [comment]
@jpkrohling Don't worry about it, I will use version 0.37.0 in the meantime. Thank you for your answer! 😊

**Comment by jpkrohling** [comment]
Alright, I'll close this one here then, as work on the release is being tracked by #4314 already.
