### ISSUE TITLE
Fallback values for $ENV in config.yaml

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#4384]
**Is your feature request related to a problem? Please describe.**

In cases where config.yml relies on environment variables (example)

```yaml
oauth2client:
    client_id: "${CLIENT_ID}"
```

it would be nice to have some way to specify fall back environment var if the env variable is not set instead of evaluating to blank string. Something in lines of 

```yaml
oauth2client:
    client_id: "${CLIENT_ID:<default-id>}"
```

**Comment by bogdandrutu** [comment]
This issue does not have enough requests to justify extra dependencies and logic.
