### ISSUE TITLE
Builder usage instructions are not working

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#4390]
**Describe the bug**

Seems there are several issues with builder instructions:
* There are no recent releases of the builder (going to be fixed with https://github.com/open-telemetry/opentelemetry-collector/issues/4314 )
* Installing the builder (as in the [example](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder#tldr)) fails: 
```
GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder
go install: go.opentelemetry.io/collector/cmd/builder@v0.38.0: 
module go.opentelemetry.io/collector@v0.38.0 found, but does 
not contain package go.opentelemetry.io/collector/cmd/builder
```

**What version did you use?**
`v0.38.0`

**Comment by codeboten** [comment]
@pmm-sumo I just tested the installation via `go install` and was able to run them w/ `v0.39.0`, can you confirm?
