### ISSUE TITLE
`configmapprovider.File` does not watch for file changes

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4397]
Related bugs that will be closed:
* https://github.com/open-telemetry/opentelemetry-collector/issues/4205 - when this gets fixed the "daemon" can simply change the file.

**Comment by sincejune** [comment]
@bogdandrutu can I take on this?

**Comment by bogdandrutu** [comment]
@sincejune I think @tigrannajaryan is working on this, I will let him say if ok

**Comment by tigrannajaryan** [comment]
@sincejune please feel free to take.

**Comment by tigrannajaryan** [comment]
@sincejune I assume you will use some sort of [inotify](https://pkg.go.dev/k8s.io/utils/inotify) to watch for file changes. If not let's discuss before you start.

Other capabilities I would expect:
- Have a timeout to wait for all file changes to complete before reloading happens.
- Do not reload if the file is not a valid YAML.
- Log the watching/reloading process.

**Comment by tigrannajaryan** [comment]
@sincejune it appears there is a draft PR https://github.com/open-telemetry/opentelemetry-collector/pull/4454 from @vjsamuel. Perhaps you can review that one.
