### ISSUE TITLE
Exporting to Zipkin doesn't work

### ISSUE THREAD

**Issue by DanBoSlice** [open-telemetry/opentelemetry-collector#441]
I started the collector with Zipkin configured as an exporter (Zipkin is already running):
```exporters:
  zipkin:
    url: "http://localhost:9411/api/v2/spans"
```

The log shows:
`{"level":"info","ts":1575044337.1697915,"caller":"builder/exporters_builder.go:79","msg":"Exporter is starting...","exporter":"zipkin"}`
`{"level":"info","ts":1575044337.169811,"caller":"builder/exporters_builder.go:84","msg":"Exporter started.","exporter":"zipkin"}`

Now I use Postman (for testing purposes) to send a trace to the OT Collector (Endpoint http://localhost:55678/v1/trace). The log shows:
`{"level":"info","ts":1575044727.188551,"caller":"loggingexporter/logging_exporter.go:36","msg":"TraceExporter","type":"logging","name":"logging","#spans":1}`

If Zipkin isn't running when I am sending traces to the collector the log correctly reports that as well:
`{"level":"info","ts":1575044662.5672855,"caller":"loggingexporter/logging_exporter.go:36","msg":"TraceExporter","type":"logging","name":"logging","#spans":1}`
`2019/11/29 17:24:23 failed to send the request: Post http://localhost:9411/api/v2/spans: dial tcp 127.0.0.1:9411: connect: connection refused`

However, even with Zipkin running and no error being logged in the OT collector I don't see any traces in the Zipkin UI, even after waiting for 30 minutes.

Am I missing something?

**Comment by huikang** [comment]
Hi, @DanBoSlice , did you add `zipkin` to the exporters in the pipeline section?

https://github.com/open-telemetry/opentelemetry-collector/blob/28e76223b09962006ad629b593d8d492e0395592/examples/demo/otel-collector-config.yaml#L42

**Comment by DanBoSlice** [comment]
@huikang Thanks for the response.

I just checked and Zipkin is included in the pipeline exporters. In fact, I used this demo config file and only adjusted the Zipkin URL and set logging to debug.

**Comment by pjanotti** [comment]
Hi @DanBoSlice could you please share the config file that you are using? There was a bug (fixed yesterday) that was preventing the queued_retry processor of logging error messages, but I'm not sure if you were using it in your config (we recommend to use it as your retry mechanism).

**Comment by DanBoSlice** [comment]
Hi @pjanotti,

I attached my config file (as a txt because Github does not allow yaml files as attachments):

[otel-conf.txt](https://github.com/open-telemetry/opentelemetry-collector/files/3941041/otel-conf.txt)

**Comment by huikang** [comment]
Your file seems copied from the collector's config under example folder. One notice I noticed is that you did not specify `format: proto`.

**Comment by DanBoSlice** [comment]
@huikang thanks, you're right. I just added it back into my config file. However the traces still don't show up in Zipkin.

Strangely enough, it seems like the trace is being exported:

```{"level":"info","ts":1576075019.1968594,"caller":"loggingexporter/logging_exporter.go:36","msg":"TraceExporter","type":"logging","name":"logging","#spans":1}```

**Comment by flands** [comment]
@DanBoSlice were you able to get this working?

**Comment by DanBoSlice** [comment]
Hi, I actually haven't put any work into the project for the last few weeks.
I noticed one bug I had. I send the trace and span ids as strings to the collector. In some configuration I was able to get a warning from the collector that apparently the need to be arrays of numbers (/bytes). Is there a documentation somewhere including an example request? I just tried it again with strings and didn't get the warning anymore. Also the requests returns a 200 OK, so that is a little confusing.

In my old configuration I was able to fix the request so that there were no warnings shown. Still I got no result in zipkin (despite the log message telling that the spans were exported).

So unfortunately I still have the problem. Hopefully this input helps.

**Comment by flands** [comment]
It should be based on the data model here (also includes an example): https://zipkin.io/pages/data_model.html. Beyond that, translation information can be found here: https://github.com/open-telemetry/opentelemetry-collector/tree/master/translator/trace/zipkin

**Comment by tigrannajaryan** [comment]
Closing as there is no further information. Feel free to reopen if the bug still exists.
