### ISSUE TITLE
Add ServerAuthenticator interfaces for HTTP receivers.

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#4440]
**Is your feature request related to a problem? Please describe.**

`configauth.ServerAuthenthenticator` interface at the moment only includes methods to implement gRPC receiver side authentication. HTTP methods should be included in the interface for parity. 

**Describe the solution you'd like**

Something like .... `RoundTripper(base http.RoundTripper) (http.RoundTripper, error)` 

```go

type ServerAuthenticator interface {
	component.Extension

	Authenticate(ctx context.Context, headers map[string][]string) (context.Context, error)

	GRPCUnaryServerInterceptor(ctx context.Context, req interface{}, srvInfo *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error)

	GRPCStreamServerInterceptor(srv interface{}, stream grpc.ServerStream, srvInfo *grpc.StreamServerInfo, handler grpc.StreamHandler) error
}

        
	// New RoundTripper returns a RoundTripper that can be used to authenticate HTTP requests.
	RoundTripper(base http.RoundTripper) (http.RoundTripper, error)

```

**Comment by panthamm** [comment]
We have seen client settings, but server settings are not available
**Client Settings**: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go line number 60
type HTTPClientSettings struct {
…
        // Auth configuration for outgoing HTTP calls.
          Auth *configauth.Authentication `mapstructure:"auth,omitempty"`
  …
}

**Server settings**: We don’t see Auth *configauth.Authentication `mapstructure:"auth,omitempty"` in type HTTPServerSettings struct { … } https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go line number 133
(for reference code available for GRPC - https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/configgrpc.go line number 162)

**Comment by bzhang1670** [comment]
Hey @jpkrohling I can pick up this ticket. cc: @pavankrish123
