### ISSUE TITLE
Pass TelemetrySettings to confighttp.ToClient and add otel instrumentation

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#4449]
Follow up to https://github.com/open-telemetry/opentelemetry-collector/issues/4424, we should provide the same instrumentation for http client as for grpc clients. As such, we need to pass in TelemetrySettings to `ToClient` and also instrument the http client with otelhttp instrumentation.

**Comment by Sprakhar97** [comment]
@codeboten @bogdandrutu I would like to work on this issue.

**Comment by jpkrohling** [comment]
Go ahead, @Sprakhar97
