### ISSUE TITLE
Jaeger reciever ignores "disabled" configuration setting

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#445]
Try the following receiver configuration:
```yaml
receiver
  jaeger:
    protocols:
      grpc:
        disabled: true
```
Jaeger receiver ignores "disabled" configuration setting and starts grpc server on the default port. Same bug exists for other Jaeger protocols.

Culprit is code which checks that port is 0 and assigns the default port: https://github.com/open-telemetry/opentelemetry-collector/blob/419ed61e5bac03caec1bf67bda09b5519bec9918/receiver/jaegerreceiver/trace_receiver.go#L133

However earlier code initializes the port to 0 when the corresponding protocol is disabled.

The net result is the protocol is not disabled and starts on the default port.

**Comment by huikang** [comment]
Hi, @tigrannajaryan , I'd like to give it a shot. My initial thought is to add additional field to extend 

https://github.com/open-telemetry/opentelemetry-collector/blob/8739948139e0e7818ae18b49819beeef06d56086/receiver/jaegerreceiver/trace_receiver.go#L56

by adding new fields like `CollectorGRPCDisabled`, `CollectorHTTPDisabled`. These fields will be set during initialization 

https://github.com/open-telemetry/opentelemetry-collector/blob/8739948139e0e7818ae18b49819beeef06d56086/receiver/jaegerreceiver/factory.go#L115

Then we can determine if the corresponding server should be started or not. What do you think? Thanks.

**Comment by joe-elliott** [comment]
This is related to #158 which I was planning on taking up after #448 is merged.

I recently added these helper methods for the agent protocols:
https://github.com/open-telemetry/opentelemetry-collector/blob/419ed61e5bac03caec1bf67bda09b5519bec9918/receiver/jaegerreceiver/trace_receiver.go#L171

and was intending to change the collector protocols to have a similar "is enabled" function.

**Comment by huikang** [comment]
Got you. @joe-elliott , thanks for clarifying
