### ISSUE TITLE
Memory limiter: Support cgroups v2 and its unified hierarchy

### ISSUE THREAD

**Issue by rcrowe** [open-telemetry/opentelemetry-collector#4457]
**Describe the bug**

Using percentage-based memory limiter config on a system that does not support cgroups v1 leads to the confusing error message [memSpikeLimit must be smaller than memAllocLimit](https://github.com/open-telemetry/opentelemetry-collector/blob/e23c9d0a01834a64162acb1677b7d69aa5be46f5/processor/memorylimiterprocessor/memorylimiter.go#L52-L53).

We pin our collector version we run and suddenly it started erroring with the above error. It turns out the environment underneath the k8s cluster had the version of [flatcar](https://www.flatcar-linux.org/) upgraded, which moved to cgroups v2.

[go.opentelemetry.io/collector/internal/cgroups](https://github.com/open-telemetry/opentelemetry-collector/blob/main/internal/cgroups/doc.go#L39) took it's code originally from [uber-go/automaxprocs](https://github.com/uber-go/automaxprocs/issues/21) which has a long standing issue of adding support for cgroups v2.

I've put this as a bug because I found it non-clear with the error message and getting to the source of the problem, but I guess adding support for cgroups v2 as a feature request.

**Steps to reproduce**

- Run a system with cgroups v2
- Add a new memory limiter processor
- Set % based limits `limit_percentage` & `spike_limit_percentage`

**What did you expect to see?**

- Ideally, it works with cgroups v2 which has been around for a while
- Error that the total memory could not be retrieved

**What did you see instead?**

```
Error: cannot build pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "metrics": memSpikeLimit must be smaller than memAllocLimit
2021/11/17 14:36:03 collector server run finished with error: cannot build pipelines: cannot build pipelines: error creating processor "memory_limiter" in pipeline "metrics": memSpikeLimit must be smaller than memAllocLimit
```

**What version did you use?**

v0.29.0

**What config did you use?**

```
processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
```

**Environment**

k8s
https://www.flatcar-linux.org/releases/#release-2983.2.0

**Comment by bogdandrutu** [comment]
@dashpole @mxiamxia you know more about this than me, can you answer?

**Comment by dashpole** [comment]
For cgroups v2, I think we need to be checking `memory.max` instead of `memory.limit_in_bytes` in  [MemoryQuota()](https://github.com/open-telemetry/opentelemetry-collector/blob/e23c9d0a01834a64162acb1677b7d69aa5be46f5/internal/cgroups/cgroups.go#L112).  We can do something like runc does here: https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/utils.go#L34 to check to see if cgroups v2 is enabled.

**Comment by emadolsky** [comment]
I have already implemented the cpuQuota for automaxprocs in this PR: https://github.com/uber-go/automaxprocs/pull/44

If you think it is a good idea to implement the same in here, I can spend my time on it.

**Comment by bogdandrutu** [comment]
@dashpole as an expert you make the call if that is the right thing to do, I just trust you on this :)

**Comment by dashpole** [comment]
@emadolsky that would be very helpful.  As a note, the [MemoryQuota()](https://github.com/open-telemetry/opentelemetry-collector/blob/e23c9d0a01834a64162acb1677b7d69aa5be46f5/internal/cgroups/cgroups.go#L112) function doesn't exist in https://github.com/uber-go/automaxprocs, so you will have to make some additional changes there.

**Comment by emadolsky** [comment]
This issue can be closed, I guess.
