### ISSUE TITLE
Return an error on `config.Map.Set`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#4467]
seems there's at least a couple of calls that could trigger an error in this func with `Load` just above this line, I would be in favour of returning an error from Set

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector/pull/4462#discussion_r753349403_

**Comment by jpkrohling** [comment]
Looks like a good first issue?

**Comment by mx-psi** [comment]
@jpkrohling yes, I think this should also be required for GA since it's a breaking change

**Comment by shree007** [comment]
@jpkrohling I can work on it.

**Comment by shree007** [comment]
@jpkrohling  I will take a look into it.

**Comment by bogdandrutu** [comment]
@mx-psi I understand the current implementation of "Set" may do this, but I am not sure conceptually when a "Set" func would return an error if you were implementing this?

**Comment by bogdandrutu** [comment]
The error on `Merge` is if for one key we change the type, maybe we should document the same. Then it may make sense :)

**Comment by mx-psi** [comment]
That would make sense to me, yes. @shree007, what do you think?

**Comment by shree007** [comment]
As I see there is following two things
1. Create proper documentation to prevent passing the heterogenous type
parameter in map.

2. Since issue is also producible so i would say better to handle it as
well, in case we skip the fact that "map type parameter should not be
different" while reviewing the PR in future.

This is what I am thinking.
Thanks

**Comment by mx-psi** [comment]
Sounds reasonable to me

**Comment by shree007** [comment]
@bogdandrutu If nobody is using then I can proceed for code cleanup
cc: @mx-psi  @jpkrohling

**Comment by bogdandrutu** [comment]
@shree007 let's craft a PR.

**Comment by shree007** [comment]
Ok, I will do that.

**Comment by mx-psi** [comment]
We make use of `Set` on the Datadog Agent OTLP endpoint, to transform a Viper map into a `config.Map`. I think it's safe to remove and we could take a different approach and avoid using `Set`.

**Comment by shree007** [comment]
@bogdandrutu Before removing I am checking and found that  there are two places where its being used
https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configmapprovider/expand.go#L30
https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/internal/configsource/manager.go#L212
Should I still proceed to craft the PR for removing ?
Please let me know thanks
