### ISSUE TITLE
Find a better way to instrument the collector with the GCP Go Profiler 

### ISSUE THREAD

**Issue by gravelg** [open-telemetry/opentelemetry-collector#4469]
**Is your feature request related to a problem? Please describe.**
We currently use a custom `cmd/otelcol/main.go` file for our collector deployment, in order to configure the GCP Go profiler and our in-house crash collection tool. We have several custom exporters/receivers that are developed in-house and having these tools are essential to our ability to debug issues. 

With the move to use the builder to generate the binary for the collector, this pattern seems to be trickier to execute, possibly necessitating modification of the go templates that the builder uses.

**Describe the solution you'd like**
Needing to essentially copy the `main.go` from the collector into our local repository is an inelegant solution to this problem but I am not sure there is another way around it.

**Comment by bogdandrutu** [comment]
@gravelg we no longer have a "main" file, we do rely on the builder tool to generate that file. Is that solution acceptable to you?

**Comment by gravelg** [comment]
Hey @bogdandrutu, the issue we are facing is that the builder tool does not easily allow us to instrument the collector with the GCP profiler anymore. [Here](https://cloud.google.com/profiler/docs/profiling-go) is some info on how it works. Right now, we just have a copy of the main.go in our project and we add the profiler code in there. With the builder, since the main.go has effectively been turned into templates, we can't do this anymore.

**Comment by jpkrohling** [comment]
I see this issue as a feature request for the builder to support customization of the bootstrap code. Perhaps we need a change to the collector as well, to allow this? I need to think about what would be a clean solution for this, but I'm open to suggestions.

**Comment by jpkrohling** [comment]
@bogdandrutu, I think we touched on this topic recently when discussing the config providers. Should the collector support a mechanism to execute callbacks before starting the service?
