### ISSUE TITLE
Use PingService in gRPC tests

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4474]
As part of #4423, I started using a PingService that provides unary and stream RPCs. Other tests in the same file are using OTLP gRPC, touching only the unary features. To avoid using two different services for that suite, it would be better to use only the PingService.

**Comment by bogdandrutu** [comment]
Based on https://github.com/open-telemetry/opentelemetry-collector/pull/4423#pullrequestreview-825106487 I am closing this issue.
