### ISSUE TITLE
Release the operator v0.40.0

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4483]

**Comment by jpkrohling** [comment]
@VineethReddy02, @pavolloffay, @yuriolisa, who'd want to take care of the operator v0.40.0?

**Comment by yuriolisa** [comment]
I'd like to take care.

**Comment by yuriolisa** [comment]
Just finished the PR.
https://github.com/open-telemetry/opentelemetry-operator/pull/585
