### ISSUE TITLE
Enable gRPC and HTTP OTLP receivers by default when not specified

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector#4493]
Currently, `protocols` is required when enabling a OTLP receiver

```
receivers:
  otlp:
    protocols:
      grpc:
      http:
```

It seems like reasonable behavior to enable both by default, especially given the spec language that SDKs can choose between gRPC or HTTP

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specify-protocol

```
receivers:
  otlp:
```

Enabling both protocols with their default (and legacy) ports on `0.0.0.0` is a better experience.

**Comment by bogdandrutu** [comment]
I feel like this is a nice change for default, but on the other hand I feel is very confusing for users that want to change that.
