### ISSUE TITLE
Collecting meta data

### ISSUE THREAD

**Issue by DanBoSlice** [open-telemetry/opentelemetry-collector#452]
Hi everyone,

I know the OpenTelemetry Collector currently supports metrics and traces. I have a use-case in which I additionally want to collect all loaded (Java) classes of an application. Most of the classes will already be loaded at application start-up. However, in my use-case I am instrumenting a web application, so there might be some classes that only get loaded at a later point in time (for example when an endpoint is used for the first time).
This is neither a metric nor a trace but rather some type of metadata.
What is the best practice to collect such metadata? Are there any plans to support this directly in the future?

**Comment by tigrannajaryan** [comment]
There are currently no plans to add a generic "any" data collection capabilities. There is an intent to add logs/events as another data type some time in the future but that work is not yet started and will likely happen as part of the initiative to add logs/events to OpenTelemetry as a whole.

As for the specific use-case described in this issue I would advise to implement an extension that can be compiled with Collector (if it needs to be in the Collector). Custom functionality like that is recommended to be a custom build based on the Collector but not in this Collector repo. If the extension implements a popular feature that the community needs it can be considered to be added to the [contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/).

**Comment by tigrannajaryan** [comment]
Closing since the question is answered. Feel free to reopen if further discussion is needed.
