### ISSUE TITLE
Allow "configauth" interfaces to be extended

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4534]
The current design of the `configauth` interfaces do not allow extending them in the future (only using optional implemented interfaces is allowed). Should we do similar things like in `component`?

- [x] #4556
- [x] #4557

**Comment by jpkrohling** [comment]
I created two items to track the implementation of the two authenticator types and sent in a PR with a proposal. @bogdandrutu, could you check whether this is what you had in mind? #4558

**Comment by jpkrohling** [comment]
This might need to be done after #4582, perhaps this won't even be needed after that.

**Comment by atoulme** [comment]
Closing as complete. Please reopen if more work is needed.
