### ISSUE TITLE
Reconsider removing function signatures from auth interfaces

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4535]
This is ready again. @bogdandrutu, there's still one point pending, about storing the `HTTPInterceptorFunc` signature in a type to be used by things like structs within authenticators and tests. If you agree, I would merge this and open an issue to discuss this pattern.

_Originally posted by @jpkrohling in https://github.com/open-telemetry/opentelemetry-collector/issues/4506#issuecomment-990791254_

**Comment by bogdandrutu** [comment]
@jpkrohling can this be closed?

**Comment by jpkrohling** [comment]
We still have this in the server interceptors, but I think this one is fine:

https://github.com/open-telemetry/opentelemetry-collector/blob/51fcb65f02055638f223c6abd3d6d2d644c696db/config/configauth/serverauth.go#L42-L44

If you are OK in keeping, this can be closed, as the original comment was about the HTTP one, which was indeed removed already.

**Comment by bogdandrutu** [comment]
The AuthFunc is fine, my whole comments were about having the other helpers/customizations. Anyway all good.
