### ISSUE TITLE
Improve test times

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector#4543]
**Is your feature request related to a problem? Please describe.**
Currently running the tests take a decent amount of which slows down the ability to get fast feedback on trying to contribute back to the project.

**Describe the solution you'd like**
I have a few ideas on how we can improve test times:

- Allow for more tests to be run in parallel 
- Include the use of a virtual clock for time dependant test cases

**Describe alternatives you've considered**
I have honestly don't have any other considerations beyond let it be, so I would love to hear if others have any other ideas on this?

Perhaps skipping integration tests locally and adding them within CI?

**Comment by jpkrohling** [comment]
Despite faster feedback, one thing that bothers me with our CI is that we have tons and tons of tests for every single PR, including doc changes. We discussed a few things in the past, including

- storing the build and test cache into the job cache, so that we only get tests for code that has changed
- not running bulky tests (load tests?) for every PR, but rather, on nightly builds
- decide what to test based on which files got changed

I think the word "bazel" has been mentioned a few times, some jokingly, some not.

**Comment by MovieStoreGuy** [comment]
> storing the build and test cache into the job cache, so that we only get tests for code that has changed

That I am not sure how best to do, been stuck with Bitbucket pipelines for so long that all other CIs have faded away in my mind. Though, I really like this approach since it would make contributions easier. Anecdotally, I find this more of an issue within the contrib repo as opposed to the collector but having them as part of both repos would be awesome.

> not running bulky tests (load tests?) for every PR, but rather, on nightly builds

We can move these to be like "release" testing? I am sure this would have some negative affects but I imagine it would be more useful to those consuming the releases instead of bleeding edge so to speak.

> decide what to test based on which files got changed

I mean, could be down with some git diff magic in the makefile but then I worry when that is a component shared among other directories that may not get tested.

> I think the word "bazel" has been mentioned a few times, some jokingly, some not.

I have never used bazel before so I am not sure on how good or bad it is but I am happy to take a gander at it.

I know that @codeboten has spent some time fixing up some of the CI over time, so I imagine they may have some ideas.

**Comment by chenzhihao** [comment]
Regarding allowing for more tests to be run in parallel, I'm not sure if that will really help.

Golang run tests from different packages in parallel already. We probably are pretty much already taking the most advantage of the CI/CD's computing resource.

**Comment by MovieStoreGuy** [comment]
I actually wasn't aware that packages we started roughly the same as one another, that is cool to know :D 

The one thing I have noticed that the packages within the collector are "wide", meaning there is a lot of tests that make up those packages and those are run sequentially to my understand when `go test` is run in list mode. 

Allowing more of those to run in parallel would mean that we are not artificially setting Amdahl's law and `go test` can manage how many tests are run in parallel by default (or set by a flag.)

I don't see any harm of allowing more tests to be run in parallel by default considering that the observed performance gain has not decreased, furthermore, it has also uncovered some parts that are not safe to use concurrently.

**Comment by jpkrohling** [comment]
> Though, I really like this approach since it would make contributions easier

GitHub Actions does provide a caching action already that we could make use of (and probably are already for other things). I'm sure someone already wrote a blog post about it too, focusing on Go :-)

> We can move these to be like "release" testing?

That's too late, IMO. A nightly build would really be my preference, with the option of manually starting them. We could then manually start right before the release.

References: 
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#manual-events

> I mean, could be down with some git diff magic in the makefile but then I worry when that is a component shared among other directories that may not get tested.

GitHub Actions can be executed based on the paths that are touched by a PR:

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths

Perhaps each component in contrib should have its own workflow, defining when it should be part of the build? For core, it might not make much sense.

> I have never used bazel before so I am not sure on how good or bad it is but I am happy to take a gander at it.

Let's see if we can do it without bazel :-) Thanks for your thought and actions on this, @MovieStoreGuy!

**Comment by bogdandrutu** [comment]
> Perhaps each component in contrib should have its own workflow, defining when it should be part of the build? For core, it might not make much sense.

Are we re-designing `bazel`?

**Comment by MovieStoreGuy** [comment]
Hehehe, potentially.

I am not too familiar with bazel but I do want some faster feedback loops for the project.

**Comment by jpkrohling** [comment]
>Are we re-designing bazel?

Bazel is a bit more than just selectively running specific tests, which is the only problem we are trying to solve as part of this issue.

**Comment by bogdandrutu** [comment]
One of the bazel most important feature is to ensure reproductive builds which then allows you to only rebuild things that changed. So essentially builds/tests only the minimum things that are affected by your change.

It may do more than that, but that is the major feature that they tried to sell.
