### ISSUE TITLE
Change batch processor to take client info into consideration

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4544]
Currently, the client info is propagated down from receivers to other components as part of the incoming context. Some processors, like the batch, discard the context, building a new one. This issue is to add the possibility to group data points by client characteristics at the batch processor.

**Comment by graemechristie** [comment]
Is there any progress on this ? Currently we cannot use the batch processor with the routing or header setter processors ... this seems a pretty essential feature for any scenarios involving headers or attributes ?

**Comment by jpkrohling** [comment]
There hasn't been any progress on this yet.

**Comment by jdgeisler** [comment]
We are also wondering if there are any plans for this on the roadmap? 

For Tempo, we are looking to dynamically set the tenant from a header or attribute like we do with Loki using the attribute hints, but without the batch processor the current solution with the headers_setter extension is not working well at scale.

**Comment by jmacd** [comment]
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/4646?

**Comment by AlexDHoffer** [comment]
We would also really like this feature! It really impacts scalability

**Comment by jpkrohling** [comment]
I understand this is only waiting on a maintainer to push the button. 

cc @open-telemetry/collector-maintainers

**Comment by atoulme** [comment]
#7578 is merged, can this issue be marked as completed?

**Comment by Yangningli** [comment]
The receiver adds label with key node_identifier_host_name to the collected data samples, and its value is from net.host.name (or host.name for some OTLP versions) resource attributes defined in OpenTelemetry proto, for identification of the metric data.
the question: how to configuration "node_identifier_host_name"  receiver in OpenTelemetry Collector?
