### ISSUE TITLE
[Builder] Add ability to pass in custom Config Map Provier and ConfigUnmarshallar in main.go.tmpl

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#4548]
**Is your feature request related to a problem? Please describe.**

In cases where we would like to have custom ConfigmapProvider and ConfigUnMarshaller other than the default ones, we have to edit main.go - [specially this line](https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/builder/internal/builder/templates/main.go.tmpl#L27) to something like 

```go

	if err := run(service.CollectorSettings{BuildInfo: info, Factories: factories, ConfigMapProvider: CustomProvider}); err != nil {
		log.Fatal(err)
	}
```

**Describe the solution you'd like**
We can approach this in 2 possible ways 

1. open option in builder to read and parse any custom templates and use them instead of the ones baked into the binary. This option allows users to allow other custom logic as well. 
2. Embed the template strings for configMap and configMarshaller as well in main.go as this is the most common use case 

@jpkrohling please let me know WDYT?

**Comment by jpkrohling** [comment]
I'll add this to my queue and will provide feedback soon.

**Comment by jpkrohling** [comment]
There was a discussion about this during the latest SIG call. @pmm-sumo committed to creating a proposal for handling this at the collector-level. I'm closing this for now, but feel free to reopen if the builder turns to be the right place for this.

**Comment by pavankrish123** [comment]
Thanks @pmm-sumo @jpkrohling - Is there a issue logged somewhere to keep an eye on the proposal?

**Comment by pmm-sumo** [comment]
Hi Pavan, I will open one with more details and link here

W dniu czw., 16.12.2021 o 23:36 Pavan Krishna ***@***.***>
napisał(a):

**Comment by pmm-sumo** [comment]
@pavankrish123 I opened the issue here: https://github.com/open-telemetry/opentelemetry-collector/issues/4567 - I think we should allow to provide custom providers in the builder actually (and add few more ones)
