### ISSUE TITLE
Global sampling service telemetry logging configuration options

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector#4554]
**Is your feature request related to a problem? Please describe.**
Some components use warn and info level statements for paths that can be hit frequently, like the batch processor when configured with a small sending queue: https://github.com/open-telemetry/opentelemetry-collector/blob/9d3a8a4608a7dbd9f787867226a78356ace9b5e4/processor/batchprocessor/batch_processor.go#L185. This can lead to collectors logging hundreds or thousands of messages a second, much of which is redundant information.

**Describe the solution you'd like**
The `ServiceTelemetryLogs` config should provide zap sampling `initial` and `thereafter` fields that are used when instantiating all component loggers, with defaults equivalent to disabling:

```
    sampling_initial: 1
    sampling_thereafter: 1
```

**Describe alternatives you've considered**
Given the nature of zap logger usage in components I'm not sure of an alternative sampling approach within the collector process, or another course other than setting an arbitrarily high log level and missing important statements, or making valid warning/info scenarios have a lower log level (to same effect or no change with low enough configured log level).

**Additional context**
Would potentially resolve https://github.com/open-telemetry/opentelemetry-collector/issues/1061

**Comment by tigrannajaryan** [comment]
> On a quick pass I'm not seeing where the batch processor uses a sampling config

AFAIK, it doesn't. queued_retry does.

I think it is a good idea to have a general sampling for all logs (at least configurable).

Ideally I would prefer that components are given 2 loggers: one to use during startup which will not be sampled (or will have higher sampling thresholds) to make sure all critical messages during startup are printed, and another logger to be used after startup to make sure long-running processes don't generate huge volumes of logs.
