### ISSUE TITLE
Implement default client authenticators, where functions can be overridden

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4557]

**Comment by jpkrohling** [comment]
@MovieStoreGuy, would you like to work on this? If you are interested, start only after the gRPC one is merged, as it should serve as the model for this.

**Comment by MovieStoreGuy** [comment]
> @MovieStoreGuy, would you like to work on this? If you are interested, start only after the gRPC one is merged, as it should serve as the model for this.

I am interested, for sure :D 
Do you have a link to the gRPC branch?

**Comment by jpkrohling** [comment]
Hold on a bit on this, there was a change in plans for this. See #4582 for more info.

**Comment by jpkrohling** [comment]
@MovieStoreGuy, the PR #4558 was merged and can be used as a model for this one here. Would you like to work on it?

**Comment by jpkrohling** [comment]
@MovieStoreGuy, are you still interested in this one? I have it on my queue and can start working on it right away if you have enough on your queue.

**Comment by MovieStoreGuy** [comment]
Sorry, had completely missed this. I can add it to my queue of work :)

**Comment by jpkrohling** [comment]
Don't worry. I had this also on my queue and ended up sending #4837 for it.
