### ISSUE TITLE
Refactor: remove `Name()` where appropriate

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#456]
We have the `Name() string` receiver as a leftover of some interface, however, these are not being used anymore. If there is the need to get the name it should come the `Name()` from the `NamedEntity`.

**Comment by huikang** [comment]
@pjanotti , if no one has taken this, please assign it to me. Thanks.

**Comment by tigrannajaryan** [comment]
@huikang Assigned to you, thanks.
