### ISSUE TITLE
Support more config sources

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#4567]
**Background**

A collector must be provided with a configuration to run (there's no default one). For this purpose, CollectorSettings includes [ConfigMapProvider](https://github.com/open-telemetry/opentelemetry-collector/blob/6888ffc9d7e3a3b0f669572025a64dd4730ac37f/service/settings.go#L62-L67) which allows to access te settings via [Provider](https://github.com/open-telemetry/opentelemetry-collector/blob/6888ffc9d7e3a3b0f669572025a64dd4730ac37f/config/configmapprovider/provider.go#L23-L51) interface.

Typically, the collector is run with a [default config map provider](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/command.go#L33-L35). It reads the config from the file (provided as a required `--config <filename>` argument) and optional `--set ...` which be also used to set arbitrary config params.

AWS OTel Collector is providing a custom provider, which extends it with a capability to read config from a preset environment variable (in its case, `ADT_CONFIG_CONTENT`), which, if found, is expanded into a full config map.

Currently, it's not possible to provide a custom config map provider via OpenTelemetry Collector Builder (which is mentioned in #4548)

**Describe the solution you'd like**

The default config map provider could be extended with an ability to specify other sources of config than the file. E.g.:

* `--config env:SOME_ENV_VARIABLE` - the config would be taken from `SOME_ENV_VARIABLE`, similarly as in case of AWS OTel Collector
* `--config https://example.com/some_config.yaml` - the config could be retrieved via a GET request (possible additional capabilities would be required here, like header with a token, etc.)
* ... 

Separate providers for each config source type could be created, which could be routed basing on the string identifying the source. 

Possibly, the providers could be registered in a way that would make it easier to interact with when using OpenTelemetry Collector Builder (e.g. could be provided by additional argument to the builder)

**Comment by pmm-sumo** [comment]
@tigrannajaryan @jpkrohling I recall that there were some more ideas mentioned during the SIG. Perhaps just adding an additional set of Provider implementations (for env variable, http source, etc.) and some way to route to them accordingly might be sufficient though?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan @jpkrohling I recall that there were some more ideas mentioned during the SIG. Perhaps just adding an additional set of Provider implementations (for env variable, http source, etc.) and some way to route to them accordingly might be sufficient though?

@bogdandrutu is looking into this. He should be able to provide more details.

**Comment by sl1316** [comment]
+1 on this. 
it's very useful to provide the mechanism to fetch the config update from remote resource like a config center.
One suggestions: should we consider how those configs take effect? should the pipeline be reloaded or just change the behavior without terminating? I guess the previous one is easier to implement but needs to be integrated with graceful shutdown to avoid data loss since the in-memory data are wiped.

**Comment by bogdandrutu** [comment]
@pmm-sumo  `--config env:SOME_ENV_VARIABLE` support for this was added in https://github.com/open-telemetry/opentelemetry-collector/pull/4657 and the whole machinery to allow more providers.

I think this issue should be split between builder support and adding more providers like http/https

**Comment by pavankrish123** [comment]
lopping in @jpkrohling for builder feature to include providers. Please let me know if we need another issue to track that.

**Comment by pmm-sumo** [comment]
Yes, thanks all!
