### ISSUE TITLE
Documentation for the configuration should be easily found on the README

### ISSUE THREAD

**Issue by AWinterman** [open-telemetry/opentelemetry-collector#4611]
**Is your feature request related to a problem? Please describe.**
It is not clear from the readme what the configuration options are for the project. I do not know when landing on the readme which of the links organized in a circle is the right one to click on to find documentation about how to configure the collector.

**Describe the solution you'd like**
A link to the configuration documentation should be front an center when landing on the README

**Comment by shree007** [comment]
@jpkrohling I may work on it.

**Comment by jpkrohling** [comment]
@shree007 it's yours

**Comment by shree007** [comment]
@AWinterman Do you mean to create seprate configuration.md and hyperlink to Readme.md ?
Or I should hyperlink this https://opentelemetry.io/docs/collector/configuration/
Please confirm based on that I will do.

**Comment by AWinterman** [comment]
Probably just a link to the existing.

**Comment by bogdandrutu** [comment]
I think I can close this :) Feel free to re-open if more things are needed.
