### ISSUE TITLE
Support routing consumer

### ISSUE THREAD

**Issue by sl1316** [open-telemetry/opentelemetry-collector#4617]
**Is your feature request related to a problem? Please describe.**
yes. we would like to route the log to different exporters based on the attributes in the log. the agent could collect different type of logs(application.log, service.log, sys.log. k8s.log.etc) and all the logs would flow through the opentelemetry collector to the sharded backend storage(Kafka for now). in other words, we would like to send one type of log to a specific Kafka topic. but the last processor of opentelemtry is fanoutconsumer which pushs logs to all exporters..

**Describe the solution you'd like**
provide an alternative consumer-type which takes an routing rule(say key1->exporter1,key2->exporter2) and route the data to different exporters

**Describe alternatives you've considered**
having a single exporter and put all the routing logic within that exporter, but it feels strange to do all the routing in the exporter and make it heavy

**Comment by jpkrohling** [comment]
Would this solve your use case?

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor

**Comment by sl1316** [comment]
can you shine some light about how the routing processor works? from the pipeline builder [code](https://github.com/open-telemetry/opentelemetry-collector/blob/e080cae46f19a3b30135db1dbe1070d676b1c2ae/service/internal/builder/pipelines_builder.go#L130)
the pipeline is built in the reverse order and the fanoutconsumer is the last one before the exporters.

**Comment by jpkrohling** [comment]
The readme from that processor should have enough info to start some experiments. I'm happy to answer any specific questions you may have though.

**Comment by bogdandrutu** [comment]
Closing this per the response from @jpkrohling
