### ISSUE TITLE
CompressionType shouldn't be in internal/** path.

### ISSUE THREAD

**Issue by hyunuk** [open-telemetry/opentelemetry-collector#4627]
**Is your feature request related to a problem? Please describe.**

There is a problem with this, similar in http case. We are exposing publicly an "internal" type (under internal/** path). We need to move `middleware.CompressionType` in a public package. We can do this in a separate PR, but I want you to have a tracking issue.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/4624#discussion_r777778018_

**Describe the solution you'd like**

Since every code in `internal/middleware/compression.go` is for `config/confighttp.go`, except `CompressionType`, move the code from `internal/middleware/compression.go` to `config/confighttp.go` and delete this file. `config/configgrpc.go` will refer `confighttp` for `CompressionType` after this change is applied.

**Describe alternatives you've considered**

`config` package also has an internal folder, so move this to the `config/internal`.

**Comment by bogdandrutu** [comment]
> Since every code in internal/middleware/compression.go is for config/confighttp.go, except CompressionType, move the code from internal/middleware/compression.go to config/confighttp.go and delete this file. config/configgrpc.go will refer confighttp for CompressionType after this change is applied.

Only that type needs to be public, the rest of the code MUST NOT be public unless in an internal.

Alternatively we can have a `configcompression` small package for this.

**Comment by hyunuk** [comment]
Completed.
