### ISSUE TITLE
Replace path.Join method with filepath.Join method

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#4633]
As per @bogdandrutu's [comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6480#issuecomment-1005016589), we should follow the same pattern in the core repo.

**Comment by shree007** [comment]
@jpkrohling  @codeboten I may work on it.

**Comment by jpkrohling** [comment]
Go ahead.
