### ISSUE TITLE
Do we need all binaries for the builder?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4655]
Right now, it looks like we build a lot of binaries for the collector builder, see https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.42.0

Also the name seems to be "ocb" which may lead to confusion like "ocd", would prefer to avoid these kind of correlations.

**Comment by jpkrohling** [comment]
Which ones would you keep/remove?

I'm also not happy with ocb, will think about an alternative.

**Comment by bogdandrutu** [comment]
@jpkrohling to be honest, not sure if we need any... But I may be wrong... Probably the docker image is good enough?

**Comment by jpkrohling** [comment]
Container is painful for linux users when the container needs to write stuff outside of the container, like the host file system. It causes all sorts of permission/selinux/apparmor issues.

How about we just remove the Windows and Linux ARM builds?

**Comment by bogdandrutu** [comment]
I think is a good start. Do we have some analytics in terms of number of downloads? I think majority of the users will do `go install ...`

**Comment by jpkrohling** [comment]
Indeed, it's there in the TL;DR part, but the installation instructions do tell people to download the binary for their platforms. Installing via `go install` won't get them a stable release and the build info won't be available either.

I don't think github provides any sort of statistics, but I'd love to be wrong.

**Comment by cpanato** [comment]
this is supposed to run only on Linux? otherwise the other binaries we should keep
also, if this should run on Linux we can add the other platforms.

but GitHub does not offer the download statistics :(

**Comment by jpkrohling** [comment]
It should run on Mac and Windows as well, but I think we need only the following:

- Linux amd64
- Windows amd64
- Mac amd64
- Mac arm64 (as I understand the new processors to be based on)

**Comment by cpanato** [comment]
good, can i take this? @jpkrohling

**Comment by yurishkuro** [comment]
If history of Jaeger teaches anything it's that people want more binaries (more platforms), not less. What's the issue with publishing extra ones? If this slows down CI then you could only build other platforms during the release.

**Comment by jpkrohling** [comment]
That's true, although Jaeger is intended to be running as a daemon on servers, which can have a bigger variety of target platforms. The builder is supposed to run on dev's machine or CI environment, so, relevant to a smaller variety of platforms. If we don't have users on those platforms/OSes, I would rather remove them and add them back based on actual user demand, than have them available and in an unknown state.
