### ISSUE TITLE
support customized configsource

### ISSUE THREAD

**Issue by sl1316** [open-telemetry/opentelemetry-collector#4660]
**Is your feature request related to a problem? Please describe.**
we want to load the config dynamically and reload the program after that. it looks like opentelemetry already has an interface for [customized config source
](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/experimental/configsource/component.go)
but it seems it's not integrated with the collector yet and currently system only uses the configprovider(file or properties based)

**Describe the solution you'd like**
give some instrument about how to integrate customized configsource into the collector.(perhaps with the configprovider). we could contribute back to the community since we have the need

**Comment by bogdandrutu** [comment]
Do you want to build your own distribution? Do you use the builder for that?

**Comment by sl1316** [comment]
@bogdandrutu can you shine some line about the builder thing?
and should I put my change under the [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) lib?

**Comment by bogdandrutu** [comment]
https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder

**Comment by sl1316** [comment]
@bogdandrutu just to clarify,  I am exploring how to support dynamic config loading and want to get some ideas about why we have two places to load the config --- configsource vs the configprovider. and the configsource is not used now so I am not sure if it's kept as a possibility for the future and just dead code.

**Comment by bogdandrutu** [comment]
MapProvider is fully integrated, and support for custom MapProvider was added already. You can write a "remote map provider" and using `service.NewConfigProvider` pass it there to be able to achieve this.

Please re-open this PR if more things are needed.
