### ISSUE TITLE
Return HTTP 405 or 415 status codes instead of 404 where appropriate in HTTP collector

### ISSUE THREAD

**Issue by davechallis** [open-telemetry/opentelemetry-collector#4661]
**Is your feature request related to a problem? Please describe.**

The HTTP collector returns a 404 response for resources that do exist, but are accessed without the correct content type.

This makes it harder to figure out why their requests aren't working. I encountered this when using the correct path for requests to the collector, but was getting a 404 response due to missing `content-type` header. This made it look like the resource itself did not exist.

For example:
```shell
$ docker run --rm -ti -p 4318:4318 otel/opentelemetry-collector
```

then in another terminal:
```shell
$ curl -i -XPOST -d '{}' http://localhost:4318/v1/traces
404 page not found

$ curl -i -XPATCH -d '{}' http://localhost:4318/v1/traces
404 page not found
```

**Describe the solution you'd like**

For the 1st request above, returning a [415 Unsupported Media Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415) would have been more useful, indicating that the requested resource exists and that the POST method was ok, but that there was an issue with the payload being sent.

For the 2nd request, returning a [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/web/http/status/405) would have helped indicate that the `/v1/traces` path was correct, but that my client was using the wrong HTTP method.

This would then result in more specific 4xx errors that help clients to fix their requests, e.g.:

```shell
$ curl -i -XPOST -d '{}' http://localhost:4318/v1/traces
415 unsupported media type, supported: [application/json]

$ curl -i -XPATCH -d '{}' http://localhost:4318/v1/traces
405 method not allowed, supported: [GET, POST]

$ curl -i -XPOST -d '{}' -H "content-type: application/json" http://localhost:4318/some/incorrect/path
404 page not found
```

**Comment by jpkrohling** [comment]
Would you be open to sending a PR for this?

**Comment by davechallis** [comment]
Sure, should have some spare time at the end of this week, will take a look into it then.

**Comment by JosephWoodward** [comment]
@davechallis I'm happy to pick this one up if you don't find the time.

**Comment by davechallis** [comment]
@JosephWoodward sure, go for it, I ended up having a busy week and was unable to look into this.

**Comment by JosephWoodward** [comment]
@davechallis Okay, thanks.

@jpkrohling Feel free to assign this one to me.

**Comment by JosephWoodward** [comment]
Just a reminder that this issue can now be closed.
