### ISSUE TITLE
Replace "configmapprovider.Retrieved" with returning config.Map and closeFunc?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4665]
This idea was considered initially, but because the "Watcher" was an optional interface (not a func passed as argument) it couldn't be implemented in a nice way. Now that we changed the way the "watcher" is passed we can simplify the Provider interface.

**Current:**
```
type Provider interface {
	Retrieve(ctx context.Context, location string, watcher WatcherFunc) (Retrieved, error)
	Shutdown(ctx context.Context) error
}

type Retrieved interface {
	Get(ctx context.Context) (*config.Map, error)

	Close(ctx context.Context) error
}
```

**After:**
```
type Provider interface {
	// CloseFunc can be replaced with Done/DoneFunc/StopWatchFunc.
	Retrieve(ctx context.Context, location string, watcher WatcherFunc) (*config.Map, CloseFunc, error)  
	Shutdown(ctx context.Context) error
}
```

I believe this is what @Aneurysm9 confusion/idea was, but I cannot speak for them.

**Comment by Aneurysm9** [comment]
This is somewhat more like what I'd expect, but it's also not clear to me why the `Retrieved` needed to be closed and then obtained again.  Or, in this new model, why invoking `watcher` should cause `CloseFunc` to be invoked and then `Retrieve`.  If the provider knows that the configuration has changed, can it provide the new configuration directly to `watcher`?

**Comment by bogdandrutu** [comment]
@Aneurysm9 not really, because we may have multiple Providers, and if one of them discover (watches) a change we need to stop watching for changes in the other ones and retrieve the whole config again. The reason to retrieve the entire config and not just the one that trigger the watcher (a simple solution would be to keep the result of all the retrieves and redo the operations, but cannot happen this way, see next) is because if we want to support the "embedded configs" (allow users to have in their config files "receiver::awsxray::token::${voltdb:path/to/my/token}" the changed config may not need some of the retrieved values, so keeping a watcher will be useless.

**Comment by bogdandrutu** [comment]
Resolved. `Retrieved` is a struct now.
