### ISSUE TITLE
Build info flag

### ISSUE THREAD

**Issue by fld-opensource** [open-telemetry/opentelemetry-collector#4671]
When using the stock collector, a custom build, it would nice to have something like a --build-info, it would output pretty version of the  manifest (yaml config) used for the build. I would then be easy to see what receivers, exporters, processor etc ... we have built in.

**Comment by jpkrohling** [comment]
@esnible, this is similar to the PR you sent recently. Do you think this would have helped you debug problems with missing components?

**Comment by esnible** [comment]
@jpkrohling Yes, I believe it would be valuable to be able to find out what components are compiled in.
Doing this as a flag is OK.  I'd rather ALWAYS see this information.  Often I have the collector running on a pod I can't `exec` into, and I don't know what it offers.  There isn't much of a downside towards always logging or printing this information.

It might also be good to include commit/version in the info output, perhaps using the technique of https://belief-driven-design.com/build-time-variables-in-go-51439b26ef9/ , for both opentelementry-collector and -contrib.

**Comment by jpkrohling** [comment]
We do have the commit/version already as part of the bootstrap logs and I agree it should definitely be part of the build info command.

**Comment by cuichenli** [comment]
i would like to work on this if it is ok.

**Comment by jpkrohling** [comment]
@bogdandrutu, @tigrannajaryan, is this something that would be accepted?

**Comment by bogdandrutu** [comment]
Happy to support this, but we need to look into:
1. Avoid having multiple ways of printing same thing, right now we already have "--version" flag.
2. Define what format to use (yaml, json, free text)?

**Comment by tigrannajaryan** [comment]
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/5438

**Comment by Chinwendu20** [comment]
Hi @cuichenli, are you still working on this? I will like to take this up

**Comment by cuichenli** [comment]
Hi @Chinwendu20 , no, I am not working on this.

**Comment by Chinwendu20** [comment]
Okay thanks, I would work on this. I just want to clarify that by a stock collector you mean, a custom built collector distribution. @fld-opensource

**Comment by tigrannajaryan** [comment]
>Define what format to use (yaml, json, free text)?

I would definitely prefer this to be in a machine-readable format. Something like yaml is probably best since we can make it both reasonably human-readable and can also use for programmatic use-cases [like this](https://github.com/open-telemetry/opentelemetry-collector/issues/5438).

**Comment by Chinwendu20** [comment]
Hello @jpkrohling please could you point me to the bootstrap logs that you speak of?  Does it mean that after the distribution is creation, there is a place the YAML config for generating it is stored?

> We do have the commit/version already as part of the bootstrap logs and I agree it should definitely be part of the build info command.

**Comment by Chinwendu20** [comment]
Is this a correct visual representation of what the build-info flag should ouput?

![image](https://user-images.githubusercontent.com/59079323/195627338-8b64f24b-d80b-4b7c-a953-17e7f7ba3e7e.png)

**Comment by jpkrohling** [comment]
If you can generate a builder manifest like that, it would be great, but I don't think it's easily doable. It would already be useful to print out the list of components available, plus the version of the distribution. To get the version of the distribution, take a look at the output printed in the logs when starting the collector: there's already the build version there. When you find where this is printed, you'll find where the version information is stored.

**Comment by Chinwendu20** [comment]
Thanks for this @jpkrohling on it now

**Comment by Chinwendu20** [comment]
Hi, please I noticed something about the flag, it is always, true. i am fixing that now

**Comment by Chinwendu20** [comment]
Hello, all please I am in the process of writing a test for my PR but am getting this error from the existing test, any suggestions please? I have reverted to the previous state the collector test was before my commits. Yet I still see this:
` collector_test.go:585: 
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present
    collector_test.go:585: 
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present
    collector_test.go:585:
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present
    collector_test.go:585:
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present
    collector_test.go:585:
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present
    collector_test.go:585:
                Error Trace:    C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_test.go:585
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:392
                                                        C:\Users\Chinwendum\devenvironment\collector-core-add-dry-run-flag-validate-all-fields\service\collector_te
st.go:405
                Error:          Should NOT be empty, but was
                Test:           TestCollectorStartWithOpenCensusMetrics/override_service.version
                Messages:       mandatory label "service_instance_id" not present











Message otel-collector








`
