### ISSUE TITLE
Replace global configtelemetry.UseOpenTelemetryForInternalMetrics with a featuregate

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4694]
The definition of the variable is [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtelemetry/configtelemetry.go#L39).

This was intended to be one of the first usage of the `featuregate` package, but we did not finish that.

**Comment by shree007** [comment]
@bogdandrutu I may work on it

**Comment by bogdandrutu** [comment]
you "may" or you "will" :) ?

**Comment by shree007** [comment]
> you "may" or you "will" :) ?

I mean please assign to me, I will work on it.

**Comment by splunkericl** [comment]
Hey @shree007 , have you made any progress on this? If not we will be willing to take over the work as we run into the same issue.

**Comment by shree007** [comment]
Unfortunetly I could not look into it. You may proceed.
