### ISSUE TITLE
No validations in otlphttpexporter

### ISSUE THREAD

**Issue by anupamdalmia10** [open-telemetry/opentelemetry-collector#4709]
**Describe the bug**

Validate method does not evaluate the given config for the exporter.
https://github.com/open-telemetry/opentelemetry-collector/blob/04baaae533dc2fea3bfddce1df1c72c3d0694042/exporter/otlphttpexporter/config.go#L42

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

When collector is started with no value for endpoint in config.yaml for otlphttpexporter, collector crashes saying either endpoint or traces_endpoint (for traces pipeline) must be defined. Similar behaviour is observed for metrics and logs pipeline.

**What did you expect to see?**
A clear and concise description of what you expected to see.

These checks should be performed in Validate method, instead they are being done in factory.go in composeSignalURL method.
https://github.com/open-telemetry/opentelemetry-collector/blob/04baaae533dc2fea3bfddce1df1c72c3d0694042/exporter/otlphttpexporter/factory.go#L60

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

![image](https://user-images.githubusercontent.com/14874665/150136008-c34ddd84-9afe-4409-8276-40d03039ca2b.png)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by jpkrohling** [comment]
Good catch. The OTLP exporter was done before we had `Validate` and never changed to use it. Would you be open to send a PR doing this work?

**Comment by anupamdalmia10** [comment]
Sure, will raise a PR soon!

**Comment by JosephWoodward** [comment]
@anupamdalmia10 I'm happy to take this one off your hands if you find you don't have the time?

**Comment by anupamdalmia10** [comment]
@JosephWoodward, sure
I'll share my findings though, at the point where this Validate gets called, we do not have information about in which pipeline will be using this exporter.
So the only validation I could think of adding in this validation function is to check if everything(endpoint, traces_endpoint, metrics_endpoint, logs_endpoint) is blank. Not sure if we want to add this here. As this will also be evaluated when pipelines are being built.

@jpkrohling , comments?

**Comment by jpkrohling** [comment]
We can still validate that there is at least one endpoint being specified.

**Comment by anupamdalmia10** [comment]
Raised PR for this: https://github.com/open-telemetry/opentelemetry-collector/pull/4860
