### ISSUE TITLE
[Proposal]: Consider to remove `PipelineWatcher` and replace with a status on the Host?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4718]
Right now only "Extensions" can implement the [`PipelineWatcher`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/extension.go#L34), it may be good to probably expose the "State" of the host under the [`Host`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/host.go) interface. This will enable all the components to have access to the current state, and will still satisfy the need of knowing the current state.

Right now in core/contrib this is used only by the healthcheck extension, and it does not need a push notification, it needs only the current state.

Alternatively, if a pushed based mechanism is necessary, may not be bad to allow components to register themself to the Host (using a similar interface `PipelineWatcher`). This way every component can do that.

Last alternative is to simply extend the current design of `PipelineWatcher` to all the components.

**Comment by Aneurysm9** [comment]
Do we have a sense for what situations might require a component to know the host state beyond the existing start and shutdown invocations?  It seems like adding a `State() HostState` method is probably simplest, but if we know of uses for push notification of state changes then extending `PipelineWatcher` becomes more attractive.

**Comment by bogdandrutu** [comment]
So far, based on all the implementations I know, only the healthcheck uses that.

**Comment by jpkrohling** [comment]
If only the health check extension uses this and we don't have a concrete use for it outside of that, why do we need to touch this at all?

**Comment by bogdandrutu** [comment]
> If only the health check extension uses this and we don't have a concrete use for it outside of that, why do we need to touch this at all?

Because that is an over engineering of some "potential" use-case, that we never proven to be needed. So the main reasons are:
1. As defined right now this feature will be very hard to be extended to all components.
2. If we just expose a "Host.State()" we simplify the usage, and simplify our public surface.

**Comment by bogdandrutu** [comment]
On top of that we already have an API to get state https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L102 :)

**Comment by bogdandrutu** [comment]
Another reason is that we may want to support "reloading" of partial configs or some components and will unclear about the story when to/or not notify an extension.

So the proposed solution simplifies a lot all the logic.

**Comment by bogdandrutu** [comment]
So, to summarize because I feel like I did not do a good job (I put ideas across multiple comments): We already expose that API on the Collector struct (not on the Host interface), and that API is enough for the extension. If we just make sure that the HOST as well expose that API, then we don't need the PipelineWatcher, and if we find a reason in the future (which I doubt) we can think of the right API then.

**Comment by jpkrohling** [comment]
Alright, let's start by deprecating it then and seeing if any downstream distributions are getting affected.
