### ISSUE TITLE
Convert remaining use of 'url' to 'endpoint'

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#472]
The standard within the collector is to use 'endpoint' to specify the URL and 'endpoint' is apart of the common receiver and exporting config settings.  

The following components are still using 'url': 
* Zipkin Exporter https://github.com/open-telemetry/opentelemetry-collector/blob/d0d7f138d035a7f45250489dda88abc2fe01274c/exporter/zipkinexporter/config.go#L27
* Jaeger Thrift HTTP Exporter https://github.com/open-telemetry/opentelemetry-collector/blob/dc6b290e3cfb0405d7df4ded435ec69e4b7594be/exporter/jaeger/jaegerthrifthttpexporter/config.go#L29

**Comment by bogdandrutu** [comment]
I think this is done.
