### ISSUE TITLE
Access to Host in authInterceptor

### ISSUE THREAD

**Issue by orloffv** [open-telemetry/opentelemetry-collector#4722]
I use auth interceptor https://github.com/open-telemetry/opentelemetry-collector/blob/04baaae533dc2fea3bfddce1df1c72c3d0694042/config/confighttp/confighttp.go#L333
and i want to get Host inside, but in go(https://pkg.go.dev/net/http#Request) Host property stay separately, not inside header.
Do you have some idea, how to get Host inside auth interceptor?
My idea is add some proxy before collector(like nginx) and add new header like that:
```
X-SMTH-Host: Host;
```

**Comment by jpkrohling** [comment]
We recently had a PR where regular headers were added as attributes to the client.Info:

https://github.com/open-telemetry/opentelemetry-collector/blob/459f1566475f572a9655a1c1c16185aa62e9c3c7/config/confighttp/clientinfohandler.go#L42-L58

Perhaps this code here could store the headers in a var, and enhance it with the host information before calling `client.FromMetadata`? Would you be open to trying it out?

**Comment by orloffv** [comment]
@jpkrohling I understand correctly, you are suggesting that I can try add the code to save the Host in this place?
or i can check, maybe Host already save?

**Comment by jpkrohling** [comment]
> you are suggesting that I can try add the code to save the Host in this place?

Yes :-)

**Comment by orloffv** [comment]
@jpkrohling
```client.FromMetadata``` it's mistake? you mean ```client.FromContext```

**Comment by orloffv** [comment]
@jpkrohling Can you check my pr? https://github.com/open-telemetry/opentelemetry-collector/pull/4736

**Comment by jpkrohling** [comment]
Thank you for the PR!

**Comment by orloffv** [comment]
merged

**Comment by orloffv** [comment]
@jpkrohling oh LOL!

```contextWithClient``` call inside ```ServeHTTP```

https://github.com/open-telemetry/opentelemetry-collector/blob/da91c56fe91999e93621756b87b082e156ef00da/config/confighttp/clientinfohandler.go#L44-L63

https://github.com/open-telemetry/opentelemetry-collector/blob/da91c56fe91999e93621756b87b082e156ef00da/config/confighttp/clientinfohandler.go#L37-L40


```ServeHTTP``` calls after authenticate method :( 

https://github.com/open-telemetry/opentelemetry-collector/blob/04baaae533dc2fea3bfddce1df1c72c3d0694042/config/confighttp/confighttp.go#L331-L341

**Comment by jpkrohling** [comment]
True, sorry for not catching that before myself. Perhaps

**Comment by orloffv** [comment]
Revert pr - https://github.com/open-telemetry/opentelemetry-collector/pull/4769

**Comment by orloffv** [comment]
@jpkrohling got it https://github.com/open-telemetry/opentelemetry-collector/pull/4770
