### ISSUE TITLE
json logs

### ISSUE THREAD

**Issue by irl-segfault** [open-telemetry/opentelemetry-collector#4740]
Any way to configure the collector to emit it's own logs in JSON format?  Currently it's in a format like

```2022-01-24T22:55:34.988Z	info	otlpreceiver/otlp.go:75	Starting GRPC server on endpoint 0.0.0.0:55680	{"kind": "receiver", "name": "otlp"}```

Would love to emit this as structured json if possible.  Would you be open to such a PR?

**Comment by jpkrohling** [comment]
Our docs could be better here, but could you try this?

```yaml
service:
  telemetry:
    logs:
      encoding: json
```

This would go in your config.yaml and should produce this:

```json
{"level":"info","ts":1643117364.796594,"caller":"builder/exporters_builder.go:255","msg":"Exporter was built.","kind":"exporter","name":"jaeger"}
{"level":"info","ts":1643117364.7966652,"caller":"builder/pipelines_builder.go:223","msg":"Pipeline was built.","name":"pipeline","name":"traces"}
{"level":"info","ts":1643117364.796712,"caller":"builder/receivers_builder.go:226","msg":"Receiver was built.","kind":"receiver","name":"otlp","datatype":"traces"}
{"level":"info","ts":1643117364.796742,"caller":"service/service.go:82","msg":"Starting extensions..."}
{"level":"info","ts":1643117364.7967606,"caller":"service/service.go:87","msg":"Starting exporters..."}
{"level":"info","ts":1643117364.7967749,"caller":"builder/exporters_builder.go:40","msg":"Exporter is starting...","kind":"exporter","name":"jaeger"}

```

**Comment by sl1316** [comment]
could the opentelemetry log model support json logs as well?

**Comment by jpkrohling** [comment]
@sl1316, you should probably ask that on the repository you linked.

**Comment by sl1316** [comment]
> @sl1316, you should probably ask that on the repository you linked.

gotcha. thank you for the info

**Comment by sideeffffect** [comment]
I see that the JSON key for the message is `"msg"`. Can it be changed to `"message"`? How could I do that?
It would help with compatibility with GCP: https://cloud.google.com/logging/docs/structured-logging#special-payload-fields
