### ISSUE TITLE
1.0 Release tracking

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#4752]
This issue is for tracking progress towards reaching OTel Collector Core stability.

The proposed approach is to split Collector packages into more modules which can be gradually declared 1.0 with multimod tool. The plan on how to break down Collector packages into modules that have minimal dependencies on each other is in progress.

Currently we are working towards bringing `model` module to 1.0 which is tracked under this milestone: https://github.com/open-telemetry/opentelemetry-collector/milestone/24

**Comment by dmitryax** [comment]
@pavolloffay https://github.com/open-telemetry/opentelemetry-collector/milestone/24 is pretty close to be done. We will release model 1.0 first, then will be working on other modules

**Comment by Mario-Hofstaetter** [comment]
Dear all, milestone https://github.com/open-telemetry/opentelemetry-collector/milestone/24 looks finished.

Is there any roadmap when to expect a stable `1.0` release of OTELCOL and contrib?
Releases are currently coming at a high cadence, few are worth rolling out in our case.

**Comment by dmitryax** [comment]
> Is there any roadmap when to expect a stable 1.0 release of OTELCOL and contrib?

We are actively working on this, but there is limited capacity. `pdata 1.0` will be likely released as part of the next release, `component 1.0` is in progress and will be released soon after that. Other parts of the collector will go next. No specific timeline beyond that.

> Releases are currently coming at a high cadence, few are worth rolling out in our case.

This is expected, we need to run through a lot of changes to stabilize the API for 1.0.

**Comment by Mario-Hofstaetter** [comment]
Thanks for the quick response @dmitryax 

> This is expected, we need to run through a lot of changes to stabilize the API for 1.0.

From a otelcol _user_ perspective, how many breaking changes are expected regarding operating otelcol?
e.g. breaking changes in `yaml` config of components, ...

I guess.. until its stable _anything_ may change?

**Comment by dmitryax** [comment]
> From a otelcol user perspective, how many breaking changes are expected regarding operating otelcol?
e.g. breaking changes in yaml config of components, ...

Breaking changes for 1.0 release are mostly applied to developer API. User API stability is defined for each component independently, e.g. https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter is stable for metrics and traces and beta for logs. It means that no breaking changes are expected there. See https://github.com/open-telemetry/opentelemetry-collector#stability-levels

**Comment by codeboten** [comment]
Closing this issue in favour of https://github.com/open-telemetry/opentelemetry-collector/issues/9375
