### ISSUE TITLE
Efficient way of removing multiple keys from AttributeMap

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector#4756]
Currently `AttributeMap` only has `Delete`, which will cause an array truncation every time it's called (I think). It would be good if we can only have such an operation happen once when deleting multiple keys. In Java, we added `removeIf` which accepts a function executed against all keys, perhaps something like that could be implemented here.

**Comment by bogdandrutu** [comment]
We also have "RemoveIf" for slices (see one example https://pkg.go.dev/go.opentelemetry.io/collector/model@v0.43.1/pdata#AttributeValueSlice.RemoveIf) with same signature so we can consider that.

**Comment by bogdandrutu** [comment]
@dashpole you can take this one if you want.
