### ISSUE TITLE
Ability to include peer endpoint in request client.Info

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4758]
https://github.com/open-telemetry/opentelemetry-collector/pull/4547 added request headers to client.Info. This is good. I would also like to see peer endpoint information in the client.Info, i.e. the ip address and port number of the connecting client.

The use case for this is the following.

I would like to write a processor which looks up the peer endpoint information and if it is coming from a localhost finds the process associated with port number. After identifying the originating process the processor enriches the telemetry coming from that process by process attributes according to Otel [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/process.md) (e.g. process id, command line, etc).

This would be the functional equivalent of [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor), but for local senders.

**Comment by jpkrohling** [comment]
The client.Info has IP address information already, and for gRPC, I think this might indeed include the port number already:

https://github.com/open-telemetry/opentelemetry-collector/blob/32301d929b413918efeefc1d9a1165b03ac71988/client/client.go#L100-L103

**Comment by tigrannajaryan** [comment]
I think you are right. I didn't realize that the port may be already there. I will check and close this.

**Comment by tigrannajaryan** [comment]
Looks like it does, both for TCP and for UDP: https://pkg.go.dev/net#TCPAddr.Port

We are good, the port is already available. Closing.
