### ISSUE TITLE
Handle tracestate sampled flags on probabilistic sampler

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#476]
The probabilistic sampler should also handle the `sampled` flags from tracestate. 

Some refs:
https://w3c.github.io/trace-context/#trace-flags
https://github.com/w3c/trace-context

**Comment by huikang** [comment]
@pjanotti , please assign this to me if no one has taken it. Thanks.

**Comment by pjanotti** [comment]
Assigned @huikang. Let's know if any question about implementing it.

**Comment by huikang** [comment]
@pjanotti , could you help to take a look at the following pseudo code? The basic idea is to have a new function `parseSpanTracestateSampled` that inspects the `sampled` entry in the span's trace state. If the span is not sampled, then we move to the next span. I am not certain that if there is no `sampled`, shall we consider the span is sampled or not (the following code sets the default as sampled)?


```go
func (tsp *tracesamplerprocessor) ConsumeTraceData(ctx context.Context, td consumerdata.TraceData) error {
    for _, span := range td.Spans {
        if !parseSpanTracestateSampled(span) {
            continue
        }
        
        samplingPriority := parseSpanSamplingPriority(span)        
    }
}
// parseSpanTracestateSampled return true by default
func parseSpanTracestateSampled(span *tracepb.Span) int {
    tracestateEntries := span.GetTracestate().GetEntries()
    if tracestateEntries == nil {
        return 1
    }

    for k, v := range tracestateEntries {
        if k == "sampled" {
            return v
        }
    }
    return 1
}
```

**Comment by SergeyKanzhelev** [comment]
@pjanotti I'm not sure if `sampled` will ever be a key in `tracestate`.  Perhaps we need a separate field in proto to carry this information.

CC: @bogdandrutu @lmolkova

**Comment by pjanotti** [comment]
@huikang let's put this on hold until the question about `sampled` is clarified.

**Comment by bogdandrutu** [comment]
w3c does not define any key in the tracestate, and we will not support this unless otel or w3c defines a spec
