### ISSUE TITLE
Support for user defined flags and runtime config provider based on flags

### ISSUE THREAD

**Issue by neelayu** [open-telemetry/opentelemetry-collector#4761]
**Is your feature request related to a problem? Please describe.**
In custom downstream distributions of OpenTelemetry Collector, sometimes it is required to define additional flags and based on the subset of those flags, we need to construct a ConfigProvider.

**Describe the solution you'd like**
Adding support for user flags and deferring the fetching of ConfigProvider until flags are parsed.

**Describe alternatives you've considered**
Using a new instance of flagset does work to some extent, but it still conflicts with collector flags like `--config`, `--set`.

**Additional context**
For eg- I believe the [Splunk Otel Distribution](https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/main.go) has a custom flag, which they have to remove to ensure it doesn't conflict with the collector flags. We also have use cases of our own, where in we parse flags and set env vars based on that, and create ConfigProvider for the same.

**Comment by neelayu** [comment]
If we have decent positive responses for this, I can this up task.

**Comment by jpkrohling** [comment]
We went the exact opposite direction, moving most flags into the configuration file. @bogdandrutu can share more details about the reasoning.

**Comment by neelayu** [comment]
Is is already part of any release? @jpkrohling 
Would it solve the problem of writing custom config providers and passing that to the `CollectorSettings` based on the flags?

**Comment by jpkrohling** [comment]
Sorry, I misread what you wrote: "runtime config provider" -- I missed the provider part. We did move some runtime config from flags to the config file, like the telemetry settings, but you clearly had something else in mind.

**Comment by Aneurysm9** [comment]
Do downstream distributions not have this ability today?  The [`service.NewConfigProvider()` function](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/config_provider.go#L103-L118) can be used to construct a new provider based on whatever logic is appropriate to the service instance.  It might be useful to expose the `FlagSet` used by `service.flags()` to make it easier to build on, but there's not a lot going on there.

If you have specific use cases that you could flesh out I think that would be very helpful to us as we try to solidify the design of the config expansion/inclusion logic.  Generally, though, I think the expectation is going to be that as much as possible moves into the config system and away from using CLI flags.  The `--set` flag can always be used as a last resort for setting values from the CLI.  The difficulty comes in where there are options that would affect the configuration system itself.  

I think it might be useful to have a two-stage system where a local configuration file can either define a collector config or it can define the sources a collector config can be assembled from and how to assemble one.  But, without concrete use cases detailing how and why such a system is needed, we'll take the simplest possible approach.

**Comment by bogdandrutu** [comment]
Also on top of that, you can always use the "Collector" as a library, and not have to deal with any flag. Essentially you can create your own "cobra.Command" as what "NewCommand" does.

**Comment by bogdandrutu** [comment]
Here is a proof that we can build anything https://github.com/open-telemetry/opentelemetry-collector/pull/4786. We should probably consider to do this separation anyway and provide the library as default.

**Comment by neelayu** [comment]
> Essentially you can create your own "cobra.Command" as what "NewCommand" does.

This is indeed a good approach which can solve the problem. Although we would want to avoid rewriting the code. In addition, the existing flag set is not exposed outside, how to access `--set` flag which is needed to pass to overwrite properties converter?

**Comment by bogdandrutu** [comment]
Closing this since the custom command is ok.
