### ISSUE TITLE
[pdata] Consider renaming NumberDataPoint/Exemplar.Type methods to ValueType

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#4781]
Should we consider renaming [NumberDataPoint/Exemplar.Type methods](https://github.com/open-telemetry/opentelemetry-collector/blob/bb8dbc1a0cfc033901dde1f298423d503ae7c77e/model/pdata/metrics.go#L332-L352) to `ValueType` for consistency with `DataType`? 

`NumberDataPoint/Exemplar` is not like `AttributeValue`, it does have other fields, so it's rather a type of a value field not type of the whole `NumberDataPoint/Exemplar` object

@bogdandrutu @codeboten WDYT?

**Comment by codeboten** [comment]
This makes sense to me. +1 for consistency
