### ISSUE TITLE
Dive deep OTel collector state when CPU throttled

### ISSUE THREAD

**Issue by yimipeng** [open-telemetry/opentelemetry-collector#4812]
Hi OpenTelemetry community,

Appreciate your time in advance. This is from a customer of opentelemetry. Copy question "https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7398" here per @sethAmazon suggestion to dive deep one OpenTelemetry Collector's resource consumption logic:

if CPU is throttled in instance, what's the expected OTel collector status? Will it enter in idle or other state. And what's the expected resource consumption(Mem etc.) from OTel collector in that situation.
Want to understand the logic there because this is a critical use case for one of our product.

Happy to chat and learn more from your experience and knowledge. Appreciate all the valuable inputs in advance.

Thanks.

**Comment by bogdandrutu** [comment]
@sethAmazon @yimipeng I think the answer to this is very environmental specific, and from OpenTelemetry collector, we should not be very opinionated about this, but work to support the best we can every environment.

I believe that we should offer tools/plugins to customize this, but knowing when the "instance is throttled" is specific to the environment runs (also only some environments support this). So probably we should look into building an "extension" that is capable of determining environmental things like this, and inform the "Host" about these kind of things.

@sethAmazon do you want to own this story?

**Comment by yimipeng** [comment]
@bogdandrutu Thanks for the reply! I hear you. I might want to make the question more generic just make sure I describe my question clear: does OTel Collector has any reserved/minimum Mem. consumption in its code logic when facing zero CPU resource scenario? Will OTel Collector up and run at that scenario? Appreciate your inputs in advance.
