### ISSUE TITLE
[feature request] performance: otlp http json support jsoniter/sonic for better performance

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector#4817]
**Is your feature request related to a problem? Please describe.**
I foud collector (which use otlp http json) cpu profile cost largely in [json unmarshal](https://github.com/open-telemetry/opentelemetry-collector/blob/main/model/otlp/json_marshaler.go#L42), I know protobuf have better preformance but json is more frendly to frontend.
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/7621241/158015626-9387b71a-1520-4f90-8238-e378b35c5148.png">
**Describe the solution you'd like**
Could we have a better performance via [jsoniter](https://github.com/json-iterator/go) or [sonic](https://github.com/bytedance/sonic)? 
Like prometheus/loki/elastic-apm project does. 
https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L196
https://github.com/grafana/loki/blob/main/pkg/storage/chunk/json_helpers.go#L13
https://github.com/elastic/apm-server/blob/master/model/modeldecoder/nullable/nullable.go#L30
If the feature request is reasonable, I think we could add config field to oltpreceiver to choose another unmarshaller, or just make a new component.
**Describe alternatives you've considered**

**Additional context**

**Comment by alolita** [comment]
@open-telemetry/collector-maintainers this is related to OTLP receiver perf - please comment.

**Comment by tigrannajaryan** [comment]
I think better performance is always welcome, however given that OTLP/JSON is unstable I would prefer personally not to spend time on improving the performance just yet. I don't mind if someone else wants to work on this.

**Comment by hanjm** [comment]
Hi @sethAmazon @tigrannajaryan , I submit PR #4986 to implement unmarshal traces with `jsoniter` for better performance in the OTLP HTTP JSON case.

**Comment by atingchen** [comment]
Hi @sethAmazon @tigrannajaryan , I submit PR   https://github.com/open-telemetry/opentelemetry-collector/pull/5433 to implement unmarshal metrics with jsoniter for better performance in the OTLP HTTP JSON case.
