### ISSUE TITLE
[pdata] Consider renaming AttributeValue to AnyValue

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#4818]
`pdata.AttributeValue` is a wrapper over `opentelemetry.proto.common.v1.AnyValue` type. It's not exclusively used with `pdata.AttributeMap`, `pdata.LogRecord.Body` also [uses it](https://github.com/open-telemetry/opentelemetry-collector/blob/77352783e6965dc69b15c5e1fba523ac97954fbc/model/pdata/generated_log.go#L653-L655), [proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L135). So it's a bit confusing why Log record body has a value of AttributeValue type. 

The proposal is to rename `AttributeValue` type to `AnyValue` which matches the proto field type.

**Comment by bogdandrutu** [comment]
This is done correct? Feel free to reopen if that is not the case.
