### ISSUE TITLE
Add E2E test for Zipkin format

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#482]
This requires DataSender and DataReceiver for the testbed.

See how it is done for other formats here: https://github.com/open-telemetry/opentelemetry-collector/blob/master/testbed/testbed/senders.go and https://github.com/open-telemetry/opentelemetry-collector/blob/master/testbed/testbed/receivers.go

The new format needs to be enabled in https://github.com/open-telemetry/opentelemetry-collector/blob/master/testbed/tests/trace_test.go

**Comment by tigrannajaryan** [comment]
@mrumian-sumo feel free to work on this. Github does not let me assign this to you for some reason.

**Comment by tigrannajaryan** [comment]
@mat-rumian

**Comment by bogdandrutu** [comment]
@mat-rumian you need to write something here so I can assign the issue to you :)

**Comment by mat-rumian** [comment]
Hello :)

**Comment by kbrockhoff** [comment]
Correctness tests for Zipkin receiver and exporter are included in PR #1062
