### ISSUE TITLE
Queued retry: identify chunk with unique ID

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#4821]
**Is your feature request related to a problem? Please describe.**
When an exporter fails to export, a queued retry may happen. However, retries are not identified with a unique ID, so they are difficult to track.

**Describe the solution you'd like**
Add a unique identifier to queued retries.

**Describe alternatives you've considered**
None

**Comment by bogdandrutu** [comment]
Is this for "logging" perspective? Where do you need to identify them?

**Comment by atoulme** [comment]
Yes, for logging. In error messages and logs coming out of the otel collector, we want to see what chunk is being retried and dropped.

**Comment by atoulme** [comment]
Closing as this is no longer needed for me, folks can reopen or chime in if they wish to see work take place.
