### ISSUE TITLE
Implement graceful shutdown with pipeline draining

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#483]
Currently when shutting down any data that is in the pipeline is lost. We need to drain the pipeline during shutdown. First we need to shutdown receivers, then processors (and implement draining in processors that stores data), then exporters.

**Comment by joe-elliott** [comment]
I may be misunderstanding the need, but except for the processors this appears to be done:

https://github.com/open-telemetry/opentelemetry-collector/blob/b468dee9e0a514db4dab82f6cf7554be539533c9/service/service.go#L304-L317

**Comment by tigrannajaryan** [comment]
>except for the processors

Yes, this is the missing part. Processors support partially coming in https://github.com/open-telemetry/opentelemetry-collector/pull/488

We still need to implement draining in processors (particularly in batch and queue).

**Comment by jan25** [comment]
Hi! Can i work on this?

After quick look at queued_processor, this is a rough idea to fix - On shutdown have a deadline of 5s or until queue is emptied(whichever happens first). Also, We can have stats on how many spans were flushed and dropped during shutdown process. WDYT?

I see there is `Stop()` in queued_processor, any hints where is that used?

Similar idea can be applied to batch_processor too.

**Comment by tigrannajaryan** [comment]
@jan25 do you still want to work on this?

We will need to drain the pipeline by first stopping receivers, then stopping processors in the right order, then stop exporters. When stopping we will need to wait for up to certain max time, you are right. It needs to be done for all components, not just certain processors.

**Comment by jan25** [comment]
@tigrannajaryan Sure, I'll start the work and open a PR soon

**Comment by tigrannajaryan** [comment]
@jan25 I will remove this from 1.0 milestone, since it is not a must-have, but feel free to work on it. We will accept it when it is ready.

**Comment by kamalmarhubi** [comment]
Is there a suggested workaround to avoid dropping messages during collector upgrades?

**Comment by kamalmarhubi** [comment]
@tigrannajaryan Is there a suggested workaround to avoid dropping messages during collector upgrades?

**Comment by tigrannajaryan** [comment]
There is no known workaround.

**Comment by kamalmarhubi** [comment]
@tigrannajaryan in that case, I feel like this should be added back to the GA milestone? Dropping things on the floor during upgrades is not great...

**Comment by tigrannajaryan** [comment]
@kamalmarhubi Help is wanted on this one. If there are contributors who can submit a PR before GA, we will be happy to review it.

**Comment by bogdandrutu** [comment]
I think this is done correct?

**Comment by clintonb** [comment]
Is graceful shutdown actually implemented/supported? The docs say it is not: https://github.com/open-telemetry/opentelemetry-collector/blob/ba4ab802214f1c812f22f8c1ce9503a02a2a4984/CONTRIBUTING.md#L493-L500

**Comment by bradmac-ats** [comment]
> Is graceful shutdown actually implemented/supported? The docs say it is not:
> 
> https://github.com/open-telemetry/opentelemetry-collector/blob/ba4ab802214f1c812f22f8c1ce9503a02a2a4984/CONTRIBUTING.md#L493-L500

These docs seem to indicate that it has been implemented: https://pkg.go.dev/go.opentelemetry.io/collector/otelcol#CollectorSettings

**Comment by prdoyle** [comment]
Docs still say graceful shutdown is not implemented:
https://github.com/open-telemetry/opentelemetry-collector/blob/2854c982703e3832ff2866e3a8fd3ed9c904fca4/docs/coding-guidelines.md?plain=1#L387-L394
