### ISSUE TITLE
Add pipeline metrics (internal)

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#484]
See our Observability goals: https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/observability.md

**Comment by chenzhihao** [comment]
@tigrannajaryan that would awesome to have the internal metrics in the collector. We are also considering adding some custom metrics in our customised collector processor/exporter.

Is there anything specifically that we can help with?
