### ISSUE TITLE
Introduce a rotation of release managers

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4882]
A release manager is the person responsible for a specific release. While the manager might request help from other folks, they are the ultimate responsible for the success of a release.

In order to have more people comfortable with the release process, and in order to decrease the burden on a small number of volunteers, I propose establishing a formal policy to have all core approvers to be release managers from time to time. The PR #4881 introduces a table with the future releases, and I propose to enhance it with the name of the release managers responsible for each future release. The table is updated at every release, with the current manager adding themselves to the bottom of the table, removing themselves from the top of the table.

The current list of @open-telemetry/collector-approvers is comprised of @Aneurysm9, @bogdandrutu, @codeboten, @dmitryax, @jpkrohling, and @tigrannajaryan. 

The initial proposal is then:

| Date       | Version | Release manager |
|------------|---------|-----------------|
| 2022-01-25 | v0.43.0 | @codeboten      |
| 2022-02-03 | v0.44.0 | @bogdandrutu    |
| 2022-02-17 | v0.45.0 | @jpkrohling     |
| 2022-03-02 | v0.46.0 | @jpkrohling     |
| 2022-03-16 | v0.47.0 | @Aneurysm9      |
| 2022-03-30 | v0.48.0 | @tigrannajaryan |
| 2022-04-13 | v0.49.0 | @dmitryax       |
| 2022-04-27 | v0.50.0 | @codeboten      |

**Comment by tigrannajaryan** [comment]
Please put me on 0.48.0. I will be on PTO on 2022-03-16.

**Comment by codeboten** [comment]
Thanks for proposing this, it looks good to me.

**Comment by bogdandrutu** [comment]
Let's keep this in a md file for posterity :)

**Comment by jpkrohling** [comment]
I'll sync it with the release doc.
