### ISSUE TITLE
does otlpreceiver support http header`X-Forwarded-For`?

### ISSUE THREAD

**Issue by qingbozhang** [open-telemetry/opentelemetry-collector#4901]
I send traces data from web to otlpreceiver http port 55681, the http request header has `X-Forwarded-For` attribute. but the receiver not auto append `http.client_ip` attribute to traces spans.
how I add client ip?
version: `[v0.44.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.44.0)`

**Comment by jpkrohling** [comment]
On the receiver configuration, you have to enable the include_metadata attribute:

https://github.com/open-telemetry/opentelemetry-collector/blob/4998703dadd19fa91a88eabf7ccc68d728bee3fd/config/confighttp/confighttp.go#L220-L222

This doesn't seem to be documented, would you mind opening a PR documenting it?

**Comment by Lola-Hector-Bianca-Hewie** [comment]
I'm actually having a similar problem.  I have enabled include_metadata in the yaml configuration file for otlp http protocol (see snippet below) which is running version 0.45.0 of the collector, but I do not set the http.client_ip address being set.  I've included a wireshark snippet where you can see the X-Forwared-For from the reverse proxy.

- Yaml receiver snippet:
receivers:

  # Data sources: traces
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        cors:
          allowed_origins:
            - "http://localhost*"
        include_metadata: true
  # Data sources: traces
  zipkin:

- Wireshark snippet:
...
Hypertext Transfer Protocol
    POST /v1/traces HTTP/1.1\r\n
    Connection: Keep-Alive\r\n
    Content-Type: application/json\r\n
    Accept: application/json\r\n
    Accept-Encoding: gzip, deflate, br\r\n
    Accept-Language: en-GB,en;q=0.9\r\n
    Host: localhost:55681\r\n
    Max-Forwards: 10\r\n
    Referer: https://everi.lola-hector-bianca-hewie.co.uk:60666/pitxpress-app/index.html\r\n
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15\r\n
    origin: https://everi.lola-hector-bianca-hewie.co.uk:60666\r\n
    X-Original-URL: /open-telemetry/traces\r\n
    X-Forwarded-For: 172.26.67.55:62183\r\n
    X-ARR-SSL: 2048|256|C=GB, S=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA|CN=*.lola-hector-bianca-hewie.co.uk\r\n
    X-ARR-LOG-ID: ad875c08-8017-4470-b124-4c4e283592da\r\n
    Content-Length: 12439\r\n
        [Content length: 12439]
    \r\n
    [Full request URI: http://localhost:55681/v1/traces]
    [HTTP request 1/1]
    [Response in frame: 55]
    File Data: 12439 bytes
JavaScript Object Notation: application/json
    Object

**Comment by qingbozhang** [comment]
I enabled `include_metadata`, but I can't find `http.client_ip` at downstream consumers. 
below is my receivers config. 

```yaml
receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - "http://localhost*"
          allowed_headers: 
            - "*"
```

**Comment by jpkrohling** [comment]
Sorry, my information was incomplete. We do need an example, and I'm not sure we have all the pieces at this moment, but you need to enable this and use the attribute processor with a "from_context" setting: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor#attributes-processor

**Comment by Lola-Hector-Bianca-Hewie** [comment]
Thanks, that was the missing link.  We didn't need the allowed_headers in the end.  Final snippet from the yaml file is below.  Thanks for all the help

<pre>
receivers:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        cors:
          allowed_origins:
            - "http://localhost*"
        include_metadata: true
  zipkin:
exporters:
  jaeger:
    endpoint: "jaeger-Development:14250"
    tls:
      insecure: true
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
processors:
  attributes/rp:
    actions:
      - key: http.client_id
        from_context: X-Forwarded-For
        action: upsert
  batch:
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [pprof, zpages, health_check]
  pipelines:  
    traces:
      receivers: [otlp, zipkin]
      exporters: [jaeger, logging]
</pre>

**Comment by jpkrohling** [comment]
Would you mind adding appropriate documentation here: https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp

**Comment by qingbozhang** [comment]
Thanks for all the help. OK I'll opening a PR documentation it

**Comment by Lola-Hector-Bianca-Hewie** [comment]
So, it occurred to me last night this solution wasn't really going to work as X-Forwarded-For header can have multiple IP addresses seperated by comma followed by a space (see https://en.wikipedia.org/wiki/X-Forwarded-For) if multiple proxy servers and/or load balancers are in use.  To handle this I have changed the solution to below which will note both X-Forwarded-For, but should only set http.client_id to the first IP address from the header.  

<pre>
receivers:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        cors:
          allowed_origins:
            - "http://localhost*"
        include_metadata: true
  zipkin:

exporters:
  jaeger:
    endpoint: "jaeger-Development:14250"
    tls:
      insecure: true

  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  attributes/rp:
    actions:
      # Note the X-Forwarded-For header.
      - key: http.x_forwarded_for
        from_context: X-Forwarded-For
        action: upsert
      # Extract the client IP address from X-Forwarded-For, note cannot use colon in key name so storing in placeholder http_client_id.
      - key: http.x_forwarded_for
        pattern: ^(?P<http_client_id>.*),*
        action: extract
      # Turn the captured client IP address from placeholder into the standard attribute format http.client_id.
      - key: http.client_id
        from_attribute: http_client_id
        action: upsert
      # Remove placeholder http_client_id.
      - key: http_client_id
        action: delete
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:  
    traces:
      receivers: [otlp, zipkin]
      exporters: [jaeger, logging]
      processors: [attributes/rp, batch]
</pre>

**Comment by Lola-Hector-Bianca-Hewie** [comment]
That was something we were debating about this morning before we came to this solution.  For us to simplify the elastic search queries having the http.client_id value stored in the database in a consistent manner regardless of multiple proxy servers, routers, load balancers (or even none in simple setups) was more important to simplify diagnostics and support, but I can certainly see why you would take your suggested approach.

**Comment by Lola-Hector-Bianca-Hewie** [comment]
Well, just noticed that I specified http.client_id and NOT http.client_ip which is the standard.  Corrected the example above, but here it is again below:

<pre>
receivers:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        cors:
          allowed_origins:
            - "http://localhost*"
        include_metadata: true
  zipkin:

exporters:
  jaeger:
    endpoint: "jaeger-Development:14250"
    tls:
      insecure: true

  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

processors:
  attributes/rp:
    actions:
      # Note the X-Forwarded-For header.
      - key: http.x_forwarded_for
        from_context: X-Forwarded-For
        action: upsert
      # Extract the client IP address from X-Forwarded-For, note cannot use colon in key name so storing in placeholder http_client_ip.
      - key: http.x_forwarded_for
        pattern: ^(?P.*),*
        action: extract
      # Turn the captured client IP address from placeholder into the standard attribute format http.client_ip.
      - key: http.client_ip
        from_attribute: http_client_ip
        action: upsert
      # Remove placeholder http_client_ip.
      - key: http_client_ip
        action: delete
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:  
    traces:
      receivers: [otlp, zipkin]
      exporters: [jaeger, logging]
      processors: [attributes/rp, batch]

**Comment by SaschaBrechmannVHV** [comment]
> pattern: ^(?P.*),*

The pattern was wrong. Should be:
`pattern: ^(?P<http_client_ip>[\w-.]+).*`
The named pattern was missing.

Regards, Sascha
