### ISSUE TITLE
`componenttest.NewNop[Exporter|Processor|etc.]Factory` do not respect contribution guideline

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#4906]
They return a global unique instance instead of creating new instance, see related comment https://github.com/open-telemetry/opentelemetry-collector/pull/4899#discussion_r811568953

**Comment by jpkrohling** [comment]
Should this be closed:

**Comment by Haleygo** [comment]
@bogdandrutu  I'd like to work on it :) Is that ok?
I will remake those New.. func under /componenttest, let them return new instance instead of using global instance.
/assign
