### ISSUE TITLE
AddOpenTelemetryMetrics - Not returning all information

### ISSUE THREAD

**Issue by thecoolworld** [open-telemetry/opentelemetry-collector#4907]
Hello All,
I am new to Open Telemetry and am trying to use AddOpenTelemetryMetrics in my .Net core Service. I noticed that only the below attributes are returned. I would also need http.target & http.url so I can have those information too.. This will help in identifying the target and the URL. AddOpenTelemetryTracing gives this information my default. Is there anyway to get this information. Do you have plans to add this in future.

"attributes": [
                                            {
                                                "key": "http.flavor",
                                                "value": {
                                                    "stringValue": "HTTP/2"
                                                }
                                            },
                                            {
                                                "key": "http.method",
                                                "value": {
                                                    "stringValue": "GET"
                                                }
                                            },
                                            {
                                                "key": "http.scheme",
                                                "value": {
                                                    "stringValue": "https"
                                                }
                                            },
                                            {
                                                "key": "http.status_code",
                                                "value": {
                                                    "intValue": "302"
                                                }
                                            }
                                        ],

**Comment by bogdandrutu** [comment]
@reyang @lmolkova is this related to dotnet? Never seen `AddOpenTelemetryMetrics` before, maybe some dotnet specific.

**Comment by reyang** [comment]
@bogdandrutu seems to be the case, it is a helper for dependency injection https://github.com/open-telemetry/opentelemetry-dotnet/blob/a2c1b6e69ea64322cc64d71f1066fa566d099e96/src/OpenTelemetry.Extensions.Hosting/OpenTelemetryServicesExtensions.cs#L64

I would suggest to either transfer this issue to the OpenTelemetry .NET repo, or close the issue and ask @thecoolworld to create a new one in the OpenTelemetry .NET repo.

**Comment by thecoolworld** [comment]
Thanks for the reply.. Yes, this is .net specific. I will close this and will create one in OpenTelemetry .NET repo.
