### ISSUE TITLE
How to change port `:8888` on which metrics are exposed ?

### ISSUE THREAD

**Issue by midnightexigent** [open-telemetry/opentelemetry-collector#4910]
[Troubleshooting](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics) suggests setting `--metrics-addr` but no such argument is exposed. 

Is there any way I can achieve that, even with the builder ?

**Comment by midnightexigent** [comment]
reading the code, I found that there is the `service.telemetry.metrics.address` parameter which is nowhere to be seen in the [docs](https://opentelemetry.io/docs/collector/configuration/#service)

**Comment by mx-psi** [comment]
@midnightexigent maybe you can do a PR to update the documentation? This was mentioned in #4695 but we forgot to update the docs

**Comment by midnightexigent** [comment]
sure I can #4923

**Comment by bogdandrutu** [comment]
@midnightexigent also the recommended way is to do this in your config.yaml file, so no need of using a flag:

```yaml
service:
  telemetry:
    metrics:
      adress: ":1234"
```

**Comment by midnightexigent** [comment]
I am aware of that, IMO that also should be updated in the `opentelemetry.io` website docs

Also, there is a comment in the code indicating that it might be removed

https://github.com/open-telemetry/opentelemetry-collector/blob/4998703dadd19fa91a88eabf7ccc68d728bee3fd/config/service.go#L99-L101
