### ISSUE TITLE
Fails to push trace data to jaeger

### ISSUE THREAD

**Issue by achakrab** [open-telemetry/opentelemetry-collector#4913]
**Describe the bug**
Got the following error when pushing a trace data  to jaeger via otlp receiver:
collector_1          | 2022-02-23T17:35:44.543Z	info	exporterhelper/queued_retry.go:325	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:14250: connect: connection refused\"", "interval": "21.427916177s"}
collector_1          | 2022-02-23T17:36:05.971Z	debug	jaegerexporter@v0.35.0/exporter.go:113	failed to push trace data to Jaeger	{"kind": "exporter", "name": "jaeger", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:14250: connect: connection refused\""}
collector_1          | 2022-02-23T17:36:05.971Z	error	exporterhelper/queued_retry.go:304	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "name": "jaeger", "error": "max elapsed time expired failed to push trace data via Jaeger exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:14250: connect: connection refused\"", "dropped_items": 1}
collector_1          | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
collector_1          | 	go.opentelemetry.io/collector@v0.35.0/exporter/exporterhelper/queued_retry.go:304
collector_1          | go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
collector_1          | 	go.opentelemetry.io/collector@v0.35.0/exporter/exporterhelper/traces.go:116
collector_1          | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
collector_1          | 	go.opentelemetry.io/collector@v0.35.0/exporter/exporterhelper/queued_retry.go:155
collector_1          | go.opentelemetry.io/collector/exporter/exporterhelper/internal.ConsumerFunc.Consume
collector_1          | 	go.opentelemetry.io/collector@v0.35.0/exporter/exporterhelper/internal/bounded_queue.go:103
collector_1          | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BoundedQueue).StartConsumersWithFactory.func1
collector_1          | 	go.opentelemetry.io/collector@v0.35.0/exporter/exporterhelper/internal/bounded_queue.go:82

This was the initial state of the  collector and jaeger after starting the service:

jaeger-all-in-one_1  | {"level":"info","ts":1645655517.3581953,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc0004e1340, {IDLE connection error: desc = \"transport: Error while dialing dial tcp :16685: connect: connection refused\"}","system":"grpc","grpc_log":true}
jaeger-all-in-one_1  | {"level":"info","ts":1645655517.3583055,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to IDLE","system":"grpc","grpc_log":true}
collector_1          | 2022-02-23T22:31:57.763Z	info	jaegerexporter@v0.35.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "name": "jaeger", "state": "TRANSIENT_FAILURE"}

**Steps to reproduce**
setup the pipeline:
file: collector-config.yaml
-----------------------
receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"  # 4318 default for http
  zipkin:

processors:

exporters:
  jaeger:
    endpoint: "0.0.0.0:14250"
    insecure: true
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]

file: docker-compose.yaml
--------------------------------
version: "3" 
services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yaml:/etc/otelcol/collector-config.yaml
    ports:
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"
      - "4318:4318"
    depends_on:
      - jaeger-all-in-one

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    command: ["--log-level=DEBUG"]
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

now start the pipeline: docker-compose up
curl -iv -H "Content-Type: application/json" http://0.0.0.0:4318/v1/traces  -d @encoded-proto.json

file: encoded-proto.json
--------------------------
{
  "resourceSpans": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "otlp-receiver-otel-pipeline"
            }
          }
        ]
      },
      "instrumentationLibrarySpans": [
        {
          "spans": [
            {
              "traceId": "71699b6fe85982c7c8995ea3d9c95df2",
              "spanId": "3c191d03fa8be065",
              "name": "test-span",
              "kind": 1,
              "droppedAttributesCount": 0,
              "events": [],
              "droppedEventsCount": 0,
              "status": {
                "code": 1
              }
            }
          ],
          "instrumentationLibrary": {
            "name": "local-curl-example"
          }
        }
      ]
    }
  ]
 }

**What did you expect to see?**
I expected to see the trace passed to jaeger via http connection on port 14250 (or, 14268).

**What did you see instead?**
 connection refused when passing the trace:
failed to push trace data to Jaeger	{"kind": "exporter", "name": "jaeger", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:14250: connect: connection refused\""}

**What version did you use?**
version 0.45.0

**What config did you use?**
Config:  given above.

**Environment**
OS:  "Ubuntu 20.04" 

**Additional context**

**Comment by achakrab** [comment]
Setting the jaeger endpoint, as  "endpoint: jaeger-all-in-one:14250" removed the connection error.  The trace is sent to the jaeger now:

jaeger-all-in-one_1  | {"level":"debug","ts":1645750733.170046,"caller":"app/span_processor.go:152","msg":"Span written to the storage by the collector","trace-id":"71699b6fe85982c7c8995ea3d9c95df2","span-id":"3c191d03fa8be065"}

But, the trace sent to jaeger is not show in the jaeger UI  against the service (when I click "search" on top, the select the service from the drown-down menu, then "Find Traces"  button the UI screen).  The trace can only be looked up by entering into the search box on the top. 

It seems the UI did not incorporate the trace properly. Is there any workaround for that?

**Comment by achakrab** [comment]
The traces were missing because of the start time of the traces, which dates back in time.  Lookback time is not the load time of the traces (it is rather the start timestamp of the traces). Setting the "custom time range" that includes the start time of the traces solved it. 
This was a configuration issue.

**Comment by vellskrad** [comment]
So, was the bug resolved or closed due to lack of responses?
