### ISSUE TITLE
Simplify the release process

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#4944]
As discussed in March 2 SIG call, it would be good for maintainers to reduce the amount of work needed to release. This issue is to track ideas for how to accomplish this.

**Comment by bogdandrutu** [comment]
We should have a github action that does most of the manual work that we have to do.

**Comment by mx-psi** [comment]
I think a good first step would be to have a single `make` subcommand on core and contrib to handle all individual changes for the prep PRs. Also, I left some TODOs here https://github.com/open-telemetry/opentelemetry-collector/issues/5013#issuecomment-1070821922 to make the release process smoother/make us able to catch errors sooner.
