### ISSUE TITLE
Collector Run should exit quickly if shutdown was called prior

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector#4946]
**Describe the bug**
Currently if `Shutdown` is called before `Run` all [this](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L227-L251) startup code runs before `runAndWaitForShutdownEvent` which will then process the shutdown. 

**Steps to reproduce**
1. Created collector
2. Call `Shutdown`
3. Call `Run`

**What did you expect to see?**
Collector not attempt to run startup/configure code and exit early.

**What did you see instead?**
Startup code was run then exited.

**What version did you use?**
Version: v0.45.0

**What config did you use?**
Config: any valid config

**Environment**
OS: MacOS 12.2
Compiler(if manually compiled): go 1.17.6

**Additional context**
Action item from #4878

**Comment by dmitryax** [comment]
cc @djaglowski

**Comment by Chinwendu20** [comment]
Could you please assign this to me?

**Comment by Chinwendu20** [comment]
According to the code comments, run should not be called after shutdown

![image](https://user-images.githubusercontent.com/59079323/194839835-62fae9f5-123a-4ad2-b201-244292f205a4.png)

**Comment by cpheps** [comment]
@Chinwendu20 This ticket is to basically make a short circuit path in `Run` where if a given instance of a Collector is `Shutdown` then subsequent calls to run should detect this and exit quickly. There's a lot of logic that happens in `Run` before it would detect that it was already shut down.

I think there's a valid question on if `Run` should return and error if it's used after `Shutdown` is called. I believe it should as it would provide helpful context for the caller as to why didn't execute properly.

**Comment by cpheps** [comment]
@dmitryax Can you assign @Chinwendu20 to this issue please?

**Comment by jpkrohling** [comment]
>  Collector not attempt to run startup/configure code and exit early.

Is this even what we want? I was under the impression that we _should_ be able to stop/start the collector whenever we wanted. 

@tigrannajaryan, I'm pretty sure I got this from you a few years ago :-) Do you think that's still valid to this day?

**Comment by cpheps** [comment]
@jpkrohling I was under the impression you could start multiple instance of the collector per process but not a single instance over and over. This would make sure a single instance exits early rather than doing a full startup before closing.

**Comment by atoulme** [comment]
The comment on `Run` now says:
```
// Consecutive calls to Run are not allowed, Run shouldn't be called once a collector is shut down.
```
See https://github.com/open-telemetry/opentelemetry-collector/blob/ecd837e5969bb06a4930cea240250bc4f82a47df/otelcol/collector.go#L227

I believe this means the use case you describe is not supported. I propose to close this issue as not planned, please comment or reopen the issue if you disagree.
