### ISSUE TITLE
Missing invalid log-level validation in logging exporter

### ISSUE THREAD

**Issue by khyatigandhi6** [open-telemetry/opentelemetry-collector#4950]
**Describe the bug**

Validate method of logging exporter does not check for invalid log-level passed in the configuration.
https://github.com/open-telemetry/opentelemetry-collector/blob/322d0aafd4944d622e2b8a0ebfed7fbccbe05e26/exporter/loggingexporter/config.go#L40

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

If we pass invalid log-level, let's say : _errors_ (error is a valid value), in logging exporter in config file, collector crashes saying that 
> error creating logging exporter: unrecognized level: \"errors\"

**What did you expect to see?**
A clear and concise description of what you expected to see.

This check should be performed in Validate method.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

Sample config.yaml snippet:
```
logging:
  logLevel: errors
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by bogdandrutu** [comment]
The check is performed during the `Unmarshal` since "Level" is an enum, and `errors` is not one of the possible values. I am confused what would change for you if we check in `Validate`

**Comment by khyatigandhi6** [comment]
@bogdandrutu If we also put that check in `Validate` function, we can validate the config before starting collector just like doing `dry-run`.

**Comment by bogdandrutu** [comment]
We do that anyway, because Validate is called after unmarshal.

**Comment by bogdandrutu** [comment]
Closing since I believe that the validation is part of "unmarshaling" which happens before Validation, so a --dry-run can be implemented.
