### ISSUE TITLE
Document and provide a way to disable global state modification by Collector

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#4971]
**Is your feature request related to a problem? Please describe.**

On initialization, the Collector modifies global state from external dependencies in a number of ways; for example (probably not an exhaustive list!):

- Modify the global gRPC logger https://github.com/open-telemetry/opentelemetry-collector/blob/52f866991b4bf4c07b371c043da03cb765b76bc2/service/internal/telemetrylogs/logger.go#L76
- Modify the global meter provider when using the OTel metrics feature flag https://github.com/open-telemetry/opentelemetry-collector/blob/f980c9ef25b1110288ab1b0a297419ec83b541a1/service/telemetry.go#L213 
- Modify the global trace provider https://github.com/open-telemetry/opentelemetry-collector/blob/52f866991b4bf4c07b371c043da03cb765b76bc2/service/collector.go#L215

All of these provide useful features, but it makes it difficult to use the Collector as a library: in the grpc logger example in particular, it can lead to data races since the logger access is not atomic, in the global providers it may interact in unexpected ways with other parts of a codebase.

 **Describe the solution you'd like**

The Collector's documentation will explicitly state any global state modifications of externally accessible structs. It also provides an option to disable these modifications. In the cases listed above, something like #4970 would work, since it could be the telemetry provider's responsibility to modify global telemetry state.

**Comment by dmitryax** [comment]
@mx-psi will you be able to work on this one?

**Comment by mx-psi** [comment]
Sure :)

**Comment by bogdandrutu** [comment]
Removed https://github.com/open-telemetry/opentelemetry-collector/pull/5138

**Comment by mx-psi** [comment]
👍 will focus just on the gRPC logger then
