### ISSUE TITLE
incorrect memory limit with cgroup v1

### ISSUE THREAD

**Issue by Nicholaswang** [open-telemetry/opentelemetry-collector#4972]
when using limit_percentage for memory_limiter, it can get an incorrect limit value since the `memory.limit_in_bytes` is set to unlimited, and it get the memory limit of the container node:
![企业微信截图_1646753927335](https://user-images.githubusercontent.com/3916488/157275263-818113d2-5763-4e67-a2ae-a56fc52ab958.png)

the reason is: 
![image](https://user-images.githubusercontent.com/3916488/157274199-b49582a3-35b0-40ea-8d5c-eeb0703f03f5.png)

`memory.limit_in_bytes` is not always reporting the correct cgroup memory limit since it's always set to unlimited in a lot of conditions.
as the above snapshot showed, `hierarchical_memory_limit` is more accurate. 

**Steps to reproduce**
get a container with memory.limit_in_bytes unset.

**Comment by bogdandrutu** [comment]
@dashpole you are our cgroup expert :) can you take a look please?
