### ISSUE TITLE
Consider moving configauth to extension package

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4996]
Perhaps not everything should be moved, but some behavior could certainly be moved to another package.

Original comment:
I've always been confused about the package choice for this extension. It is very strange to have an extension defined in the `config` sub-package instead of a sub-package in `extension`. I think we should fix this.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/4837#pullrequestreview-887673150_

**Comment by jpkrohling** [comment]
I won't be able to look at this one in detail for the next two months. I'm therefore unassigning this. This is now up for grabs. If nothing happens in two months, I might be able to take a look again.

**Comment by fatsheep9146** [comment]
I read all PRs related to this issue. I think the whole configauth package should be moved to extension package, for example `extension/authextension`.  Do I understand this correctly? If it's ok I'd love to help with this :) @jpkrohling @bogdandrutu @dmitryax

**Comment by Chinwendu20** [comment]
Hello is this still valid? Can I work on this?

**Comment by fatsheep9146** [comment]
> Hello is this still valid? Can I work on this?

Sorry, I'm still working on this. =D

**Comment by fatsheep9146** [comment]
I think the whole moving actions can be split into three steps.
1. defines new package `configauth` in the `extensions` directory, but for each exported type (for example `Authentication`), is only the alias of the homonymous one in the `config` directory, for example:

```go

import "go.opentelemetry.io/collector/config/configauth"

type Authentication = configauth.Authentication

```

2. change all package or module which imports `config/configauth` to `extension/configauth`, for example configgrpc.go in `config/configgrpc`, change from 

```go
import "go.opentelemetry.io/collector/config/configauth"
``` 
to 

```go
import "go.opentelemetry.io/collector/extension/configauth"
```

3. move all codes from `config/configauth` to  `extension/configauth`, and remove `config/configauth` package.

@jpkrohling @bogdandrutu @dmitryax 

Do you think this is right?

**Comment by fatsheep9146** [comment]
@jpkrohling @bogdandrutu @mx-psi 
Could you help reopen this pr, since I only completed the first step, there are still some other works wait to be done, such as deprecate the old type.
