### ISSUE TITLE
Efficient connection management in OpenCensus receiver for transient processes

### ISSUE THREAD

**Issue by subnova** [open-telemetry/opentelemetry-collector#501]
The recommended approach for sending trace data to the OpenCensus receiver is to maintain a persistent TCP connection. This isn't always possible as the process may be transient: either because it is short lived or because the execution environment does not retain state between executions, e.g. PHP.

Allowing the OpenCensus receiver to listen on a unix domain socket reduces the connection setup cost (in comparison to TCP) that must be regularly repeated for these scenarios.

**Comment by flands** [comment]
@subnova is this addressed now?

**Comment by bogdandrutu** [comment]
Please reopen if this is not addressed.
