### ISSUE TITLE
Research and Implement a Rate Limited Logger

### ISSUE THREAD

**Issue by joe-elliott** [open-telemetry/opentelemetry-collector#502]
The OpenTelemetry Collector is a high performance application designed to handle hundreds to thousands of spans per second.  The dangers of logging in the "hot path" are summed up in the contributing readme:

https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#logging

As such a "rate limited" logger would be ideal.  The logger would detect high volumes of exact or similar logs and choose to only output a small subset of the total.  This would reduce the danger of logging in the hotpath and give developers a tool to deliver high volume, important information to the operator of the otel collector without requiring custom code.

This issue exists to discuss the design and implementation of this logger.

cc @tigrannajaryan This issue was created from our discussions in the Otel Collector SIG.

**Comment by tigrannajaryan** [comment]
Related or dup of https://github.com/open-telemetry/opentelemetry-collector/issues/94

**Comment by joe-elliott** [comment]
Agree it's a dupe.  Closing.
