### ISSUE TITLE
Split otlp/otlpgrpc

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5027]
Decision was made to split the pdata package into multiple per signal packages, see https://github.com/open-telemetry/opentelemetry-collector/issues/4832.

As a followup we need to split the `otlp` and `otlpgrpc` as well since they are part of the same current module `model`. Here are some options:
1. Extract the current packages into separate module without no other changes.
2. Move everything from `otlp` and `otlpgrpc` into the equivalent signal package decided in #4832.

I personally believe that the 2nd option is cleaner and gives us the "encapsulation" we need.

**Comment by dmitryax** [comment]
Looks like we need to make a decision here to proceed with https://github.com/open-telemetry/opentelemetry-collector/pull/5087.

Currently we have `otlp` and `otlpgrpc` packages under `/model`.  IMO having them under `model` is not much cleaner than merging them into `pdata`. If we go with the 2 approach, we can have the following structure:

```
/pdata
  /ptrace (including trace related API from `pdata/otlp` and `pdata/grpcotlp`
  /pmetric (including metrics related API from `pdata/otlp` and `pdata/grpcotlp`
  /plog (including logs related API from `pdata/otlp` and `pdata/grpcotlp`
/semconv
```

If we go with 1, we need to figure out another structure. I'm thinking of something like this:

```
/model
  /pdata
    /ptrace (including trace related API from `pdata/otlp` and `pdata/grpcotlp`
    /pmetric (including metrics related API from `pdata/otlp` and `pdata/grpcotlp`
    /plog (including logs related API from `pdata/otlp` and `pdata/grpcotlp`
  /semvconv
  /otlp
    /otlptrace
    /otlpmetric
    /otlplog
  /otlpgrpc
    /grpctrace
    /grpcmetric
    /grpclog
```

We can also remove `/model` for this structure and have `pdata`, `otlp`, `otlpgrpc` and `semvconv` at the root level, but this will  require moving `/model/internal` to `/internal`

cc @Aneurysm9 @bogdandrutu @tigrannajaryan , any other ideas?

**Comment by tigrannajaryan** [comment]
From what I understand `otlpgrpc` is currently used by otlp receiver/exporter only. Is this true? If so then why does it need to be a public package? Can we move it to `internal/otlp` or something like that?

**Comment by tigrannajaryan** [comment]
If we move `otlpgrpc` to internal then the only remaining bit is `otlp` which is a tiny package that does not have any dependency that is not already a dependency of `pdata` so I don't mind if `otlp` just gets merged with `pdata`.

It will change the meaning of `pdata` from "internal in-memory representation" to "internal in-memory representation and serialization functions", which I think is fine. It will not bloat the code size of `pdata` in any meaningful way, won't add any other 3rd party dependencies, so I think it does not make `pdata` less useful as an importable library in any significant way.

(I get that maybe we loose in purity of separation of concerns, but again, introducing 3 new packages for `otlp`, each package being a tiny, few lines of code seems excessive and I think adds maintenance burden).

**Comment by mx-psi** [comment]
> From what I understand `otlpgrpc` is currently used by otlp receiver/exporter only. Is this true? If so then why does it need to be a public package? Can we move it to `internal/otlp` or something like that?

[`otlpgrpc` is used by several external dependencies](https://pkg.go.dev/go.opentelemetry.io/collector/model@v0.48.0/otlpgrpc?tab=importedby) (including us, Datadog :) ). I think it's generally useful for writing a gRPC OTLP server, and if this were made private we would want to ensure that there is a workable alternative to it.

**Comment by tigrannajaryan** [comment]
> [`otlpgrpc` is used by several external dependencies](https://pkg.go.dev/go.opentelemetry.io/collector/model@v0.48.0/otlpgrpc?tab=importedby) (including us, Datadog :) ). I think it's generally useful for writing a gRPC OTLP server, and if this were made private we would want to ensure that there is a workable alternative to it.

OK. Looks like it is necessary if one wants to implement OTLP support in their codebase. I retract my proposal to move otlpgrpc to internal.

**Comment by bogdandrutu** [comment]
Also this applies for all packages under `model` which are used by third-party more than anything else. If we have in one package multiple signals then we cannot deal with the experimental signal case that triggered the split of the pdata (if this is not a problem anymore then we should not split pdata), because of that we MUST split these packages as well, and because of that I think it is natural to have them in the same signal package.

**Comment by mx-psi** [comment]
I don't feel very strongly either way, but I find Bogdan's arguments here more convincing, +1 for moving `otlpgrpc` symbols together with the associated signal in `p<signal>`.

**Comment by bogdandrutu** [comment]
> The current pdata as far as I can see has only one dependency "github.com/gogo/protobuf" and that obviously cannot be eliminated, so it is as minimal as it can be.

Not true unless we do way more splitting. Because we need access to the underlying protos, they need to be in the internal together. So you will always depend on the grpc anyway.

**Comment by tigrannajaryan** [comment]
>Not true unless we do way more splitting. Because we need access to the underlying protos, they need to be in the internal together. So you will always depend on the grpc anyway.

@bogdandrutu Can you point me where in the code the current `pdata` implementation depends on grpc (directly or transitively)? I wasn't able to find it.

**Comment by tigrannajaryan** [comment]
>So what I hear from @tigrannajaryan is that the disagreement is about the otlpgrpc not about the current otlp which does not have anyway any extra dependencies.

Yes, that's correct. I am fine with merging `otlp` into `pdata` since it is tiny and has no extra dependencies.

**Comment by tigrannajaryan** [comment]
I thought a bit more about this and changed my mind. Every possible 3rd party that would want to import `pdata` which I can imagine is also already dependent on "google.golang.org/grpc". My desire to avoid making "google.golang.org/grpc" a dependency of `pdata` achieves nothing in terms of the final result from the 3rd part perspective.

So, I am fine with merging `otlpgrpc` into `pdata` as well.

**Comment by dmitryax** [comment]
I also think that `otlp` package fits `pdata` pretty well, but not sure about `otlpgrpc`.

Another option might be:
```
/pdata
  /ptrace
    /ptracegrpc
  /pmetric
    /pmetricgrpc
  /plog
    /ploggrpc
```

This would solve the `google.golang.org/grpc` dependency problem that Tigran mentioned with the lazy module loading.

**Comment by tigrannajaryan** [comment]
> ```
> /pdata
>   /ptrace
>     /ptracegrpc
> ```

Will `ptrace` and `ptracegrpc` be different go modules or one module?

**Comment by dmitryax** [comment]
`ptrace` will be one module with `ptracegrpc` package in it. Clients using `ptrace` only won't get `ptracegrpc` dependancies starting from go 1.17  if I understand [lazy loading](https://go.dev/ref/mod#lazy-loading) correctly

**Comment by bogdandrutu** [comment]
@tigrannajaryan @dmitryax 

`ptracegrpc` is not a good name, since the current `otlpgrpc` contains indeed the grpc stubs, but also the Request/Response objects which are used also by the HTTP protocol.

**Comment by bogdandrutu** [comment]
Maybe consider `ptraceotlp` for what is in the `otlpgrpc` right now?

**Comment by dmitryax** [comment]
> Maybe consider `ptraceotlp` for what is in the `otlpgrpc` right now?

Maybe use `ptraceotlp` for both `otlp` and `otlpgrpc` then?

**Comment by bogdandrutu** [comment]
@tigrannajaryan what does `otlp` stands for? :))))
