### ISSUE TITLE
[CI] Build on 386 architecture

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5031]
We don't build on 386 architecture on CI, but we do release 386 binaries for this distro. This means that if there is an issue like https://github.com/open-telemetry/opentelemetry-collector/issues/5013#issuecomment-1070762107, we don't detect it until potentially the very last step of the release.

We can add builds for Windows 386 and Linux 386 to CI on this repository to catch these build errors sooner.

Edit: As discussed below, this also applies to arm64 and any other OS-architecture pair that we intend to release

**Comment by Aneurysm9** [comment]
Do we need to do the same for ARM?

**Comment by mx-psi** [comment]
> Do we need to do the same for ARM?

Yes, I thought we were doing it already, but maybe we are doing it only on contrib. We should build on every arch-OS combination that we intend to do an official release of.

**Comment by codeboten** [comment]
As discussed at triage on Mar-18, the real problem here is that there's a delta between what we're testing for every build vs what we're releasing.

**Comment by hickeyma** [comment]
@mx-psi Investigating this, it would seem that GitHub actions [hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) only supports the x86_64/AMD64 processor architecture.  [ARM64 Linux issue](https://github.com/actions/virtual-environments/issues/2552) was opened but closed as not supported. The limitation is the [VMs on Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-general#dsv2-series) used for hosted runners.

Workarounds are :
- Using [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). Need to  maintain own runner machines.
- [[multiarch/qemu-user-static](https://github.com/multiarch/qemu-user-static)](https://github.com/multiarch/qemu-user-static). Details [here](https://github.community/t/testing-against-multiple-architectures/17111/7)#5142

**Comment by mx-psi** [comment]
@hickeyma You can cross-compile just by setting the `GOOS=<os value>` and `GOARCH=<arch value>` environment variables, regardless of the host architecture. Since we don't use cgo this should work out of the box without needing to install anything else. You won't be able to run the resulting binaries (or do `go test`) but just for checking that it builds it would be good enough.

**Comment by hickeyma** [comment]
@mx-psi Thanks for the feedback. I mis-read the requirement. That simplifies it.

Pushed #5142 for adding the GitHub actions  job.
