### ISSUE TITLE
Update branch protection

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#5039]
As per the description in https://github.com/open-telemetry/opentelemetry-collector/pull/5037:
> In order to merge this PR, an admin for the repo will need to change the branch protection rules for main to require the build-and-test / unittest (1.18) and build-and-test / unittest (1.17) checks instead of the unittest check.

Assigning @bogdandrutu as I don't know if any other maintainers have access to update branch protection.

**Comment by bogdandrutu** [comment]
Done.

Also any TC members have admin (including @tigrannajaryan) :)
