### ISSUE TITLE
Add link to opentelemetry.io under About section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-collector#5040]
Under the **About** section of this repo (which you can access from the main repo page -- click the gear icon next to the About title):

- Under **Website**, add https://opentelemetry.io

We're looking to do this uniformly for all OTel org repos. 

For example:

> <img width="308" alt="image" src="https://user-images.githubusercontent.com/4140793/159187627-ef6d92af-bb9e-4877-8de2-9d3fb604c8e5.png">

**Comment by bogdandrutu** [comment]
Done.
