### ISSUE TITLE
Create common code for HTTP receivers and exporters

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#505]
Currently there are receivers and exporters, in the core and contrib repo, that are just variations of data formats sent/received over HTTP (eg.: Zipkin, SignalFx, collectd, etc). This creates inconsistencies between very similar components. We should design HTTP receivers and exporters that can be extended to support different formats, handle requests and responses as needed but have a consistent core set of configuration options and observability. This will simplify configurations and will make easier to understand issues with these components.

**Comment by bogdandrutu** [comment]
This is almost done with the new helpers and the new configs.
