### ISSUE TITLE
`HTTPClientSettings.ToClient` is inconsistent with other `To*` config methods

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5061]
`confighttp.HTTPClientSettings.ToClient` takes an id-extension map while `configgrpc.HTTPServerSettings.ToServer` and all the `configrpc.*.To*` methods take a `component.Host`, in all cases to support authentication. 

Ideally all would be consistent by passing `component.Host` to all of them, although I don't want to assume this is the best solution just because it's the most used one.

cc @jpkrohling since this is auth related.

**Comment by bogdandrutu** [comment]
I would vote to make it consistent and use `component.Host`.

**Comment by shree007** [comment]
@jpkrohling  I may work on it.

**Comment by fatsheep9146** [comment]
Is this issue still open?

**Comment by mx-psi** [comment]
> Is this issue still open?

It is, #5083 was closed as stale

**Comment by fatsheep9146** [comment]
> > Is this issue still open?
> 
> It is, #5083 was closed as stale

Could I work on this?

**Comment by mx-psi** [comment]
Assigned :)

**Comment by mx-psi** [comment]
Reopening since we still have to:
1. remove `ToClient` in a future version
2. add it back with the 'correct' argument

**Comment by fatsheep9146** [comment]
> Reopening since we still have to:
> 
> 1. remove `ToClient` in a future version
> 2. add it back with the 'correct' argument

These two works should both be done until at least version v0.56.0?

**Comment by mx-psi** [comment]
@fatsheep9146 Yes, for now we have to wait!

**Comment by mx-psi** [comment]
@fatsheep9146 I think you can continue doing this now!
