### ISSUE TITLE
Support OTLP v0.15.0

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#5063]
Update the proto to the latest release: https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.15.0. There are a few tasks to do here:
- [x] #5071
- [x] https://github.com/open-telemetry/opentelemetry-collector/issues/4258
- [x] #5072
- [x] #5073
- [x] #5074

**Comment by dmitryax** [comment]
Will this include renaming of `pdata.InstrumentationLibrary` or we need another ticket for that?
