### ISSUE TITLE
Question about shutdown the queuedRetrySender

### ISSUE THREAD

**Issue by ralphgj** [open-telemetry/opentelemetry-collector#5110]
Hi! We have a question about shutdown the `queuedRetrySender`.

In https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/queued_retry_inmemory.go#L147 comments, it seems will drain the queue before shutdown the `queuedRetrySender`. 
```
func (qrs *queuedRetrySender) shutdown() {
	// Cleanup queue metrics reporting
	if qrs.cfg.Enabled {
		_ = globalInstruments.queueSize.UpsertEntry(func() int64 {
			return int64(0)
		}, metricdata.NewLabelValue(qrs.fullName))
	}

	// First Stop the retry goroutines, so that unblocks the queue numWorkers.
	close(qrs.retryStopCh)

	// Stop the queued sender, this will drain the queue and will call the retry (which is stopped) that will only
	// try once every request.
	if qrs.queue != nil {
		qrs.queue.Stop()
	}
}
```
But in https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/internal/bounded_memory_queue.go#L83, while the `select` run into the `case <-q.stopCh`, it will return and then the items in queue will not be consumed by `itemConsumer`. Are we understand correctly or missing some key points？
```
func (q *boundedMemoryQueue) StartConsumers(num int, callback func(item interface{})) {
	factory := func() consumer {
		return consumerFunc(callback)
	}
	q.workers = num
	q.factory = factory
	var startWG sync.WaitGroup
	for i := 0; i < q.workers; i++ {
		q.stopWG.Add(1)
		startWG.Add(1)
		go func() {
			startWG.Done()
			defer q.stopWG.Done()
			itemConsumer := q.factory()
			queue := *q.items
			for {
				select {
				case item, ok := <-queue:
					if ok {
						q.size.Sub(1)
						itemConsumer.consume(item)
					} else {
						// channel closed, finish worker
						return
					}
				case <-q.stopCh:
					// the whole queue is closing, finish worker
					return
				}
			}
		}()
	}
	startWG.Wait()
}
```

_Originally posted by @ralphgj in https://github.com/open-telemetry/opentelemetry-collector/discussions/5088_

**Comment by bogdandrutu** [comment]
I think you are correct. Would be good to have a test for this, and take it from there and fix the problem. The solution is simple we should make sure we consume all items on the "stop" case.

**Comment by TylerHelmuth** [comment]
I can take a look at this.
