### ISSUE TITLE
Investigate link checker, after upgrade tests are passing

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5118]
Since we upgraded to latest gaurav-nelson/github-action-markdown-link-check@1.0.14 (from 1.0.13) every time we change something in a md file with links we fail the link check, see:
https://github.com/open-telemetry/opentelemetry-collector/runs/5755269731?check_suite_focus=true

Something that may be related https://github.com/open-telemetry/opentelemetry-specification/pull/2426.

**Comment by petertamuk** [comment]
Hello, I'm new to contributing and would like to look in to this issue if that's alright. 

Taking a look over at github-action-markdown-link-check it appears the owner has move v1.0.14 to a per-release version and labelled v1.0.13 as the latest.  Issue: [127](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/127)

I believe the actions for this issue would simply involve updating [check-lints.yaml L19](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/check-links.yaml#L19) to v1.0.13. Does that sound correct?

**Comment by bogdandrutu** [comment]
Indeed seem to be lots of errors... But our errors seem to be for internal references, which I am confident should work. All dead links are internal:

```
FILE: docs/release.md
  [✖] #releasing-opentelemetry-collector → Status: [40](https://github.com/open-telemetry/opentelemetry-collector/runs/5755269731?check_suite_focus=true#step:4:40)4
  [✖] #releasing-opentelemetry-collector-contrib → Status: 404
  [✖] #producing-the-artifacts → Status: 404
  [✖] #release-schedule → Status: 404

  16 links checked.

  ERROR: 4 dead links found!
  [✖] #releasing-opentelemetry-collector → Status: 404
  [✖] #releasing-opentelemetry-collector-contrib → Status: 404
  [✖] #producing-the-artifacts → Status: 404
  [✖] #release-schedule → Status: 404
```

**Comment by TylerHelmuth** [comment]
I think that @petertamuk is right that the issue is with v1.0.14.  I think until github-action-markdown-link-check is [updated to use markdown-lint-check v3.10.0](https://github.com/gaurav-nelson/github-action-markdown-link-check/pull/129) we should revert back to v1.0.13, which is what the maintainers of the action recommend.
