### ISSUE TITLE
Tutorials to help developers learn the Collector's concepts and how to build components for it

### ISSUE THREAD

**Issue by rquedas** [open-telemetry/opentelemetry-collector#5134]
**Is your feature request related to a problem? Please describe.**

OpenTelemetry is a great gateway to enable observability for any type of systems, and the Collector plays a major role in helping transforming and processing the telemetry from these systems into the OTel world.

Unfortunately there is very little content/material develop to help developers understand how to build Collector components.

**Describe the solution you'd like**
I would like to have a repo structure with tutorials to help describe the concepts and provide sample code to help people understand the concepts and APIs involved in creating collector's components.

**Describe alternatives you've considered**
I have considered creating video tutorials for it, but that would require a higher level of effort that may not add value.

**Additional context**
I have created a repo to represent what I believe is a good starting point for it and if accepted I would like to contribute it and keep building and maintaining the tutorials for the collector moving forward.

[Trace Receiver Tutorial](https://github.com/rquedas/otel4devs/tree/main/collector/receiver/trace-receiver)

**Comment by jpkrohling** [comment]
I have written a couple of blog posts on the matter, but haven't converted them into official documentation pages because those have to be accurate and up-to-date, which is difficult to have on a fast-moving project like the collector. Given the API is almost stable, it might indeed be time to have those guides.

For reference, here are the (outdated) blog posts I mentioned:

https://medium.com/opentelemetry/extending-the-opentelemetry-collector-with-your-own-components-64c10cf675db
https://medium.com/opentelemetry/building-your-own-opentelemetry-collector-distribution-42337e994b63

**Comment by rquedas** [comment]
> I have written a couple of blog posts on the matter, but haven't converted them into official documentation pages because those have to be accurate and up-to-date, which is difficult to have on a fast-moving project like the collector. Given the API is almost stable, it might indeed be time to have those guides.
> 
> For reference, here are the (outdated) blog posts I mentioned:
> 
> https://medium.com/opentelemetry/extending-the-opentelemetry-collector-with-your-own-components-64c10cf675db https://medium.com/opentelemetry/building-your-own-opentelemetry-collector-distribution-42337e994b63

yup, I wouldn't have done the work I did without reading those! So, thank you!

@alolita suggested I would submit it for the registry, but after chatting with @austinlparker it seems that docs or blogs would be the right place.

**Comment by rquedas** [comment]
> Wherever you decide to publish it, do let me know. I'd be interested in reviewing it.

Abolutely! You can review it here: [Building a Trace Receiver](https://github.com/rquedas/otel4devs/tree/main/collector/receiver/trace-receiver)

**Comment by bogdandrutu** [comment]
Assign to @jpkrohling to coordinate this.

**Comment by jpkrohling** [comment]
@rquedas, I started looking into the tutorial, but it would be easier for me to review it once you submitted it as a PR to the website. This way, other folks can review different aspects of your content, like the grammar.

**Comment by rquedas** [comment]
> @rquedas, I started looking into the tutorial, but it would be easier for me to review it once you submitted it as a PR to the website. This way, other folks can review different aspects of your content, like the grammar.

cool, here is the PR: Adding a howto for building a trace receiver #1288
