### ISSUE TITLE
[pdata] Consider removing wrapping for Span/TraceID

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5137]
Originally posted [here](https://github.com/open-telemetry/opentelemetry-collector/pull/5087#discussion_r840795893) by @bogdandrutu 

> Crazy consideration/idea. Can we remove them and replace with a [8]byte and [16]byte for the APIs in span/exemplar/etc.?

**Comment by dmitryax** [comment]
@bogdandrutu it sounds reasonable. Do you remember why they were wrapped? It doesn't look like it help to restrict direct access to the bytes.

**Comment by bogdandrutu** [comment]
Yes, for helpers like "IsValid".

**Comment by bogdandrutu** [comment]
Also to allow us in the future to change that. But that ship I think is sailed since we say in specs and protocol that we are w3c compatible :)

**Comment by Aneurysm9** [comment]
In the [Go SDK we use a type](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/trace.go#L49) on top of `[16]byte` rather than a struct, which allows `IsValid` and marshaling methods, but also allows simple conversion to/from a `[16]byte`.

**Comment by bogdandrutu** [comment]
@Aneurysm9 we are now debating mostly if a struct / type alias is needed (not the diff between type alias and struct). The reason for this discussion is because if we need it (since it is shared by trace/metrics/logs).

Also please consider for future to provide arguments independent of decisions in go-sdk. This project is not based on that project or does not need to follow that project decisions. (e.g. `A type alias is better since provides simple conversion to/from a [16]byte`)

**Comment by Aneurysm9** [comment]
I was providing relevant context from a related project that had to make similar decisions.  While I can understand and appreciate that the collector is not bound by the decisions made by the Go SDK, it would be folly to ignore the experience.  

In this case I think the relevant takeaway is that using a type definition (not a type alias) allows implementing additional helper methods, which was called out as the reason why the types were wrapped in the first place.  I was pointing out that it is possible to get both the helpers and the simple conversion, while type aliasing would only ease conversion.

**Comment by bogdandrutu** [comment]
>  I was pointing out that it is possible to get both the helpers and the simple conversion, while type aliasing would only ease conversion.

Good point.

But this is not the problem we are having. The "problem" is that if this exists in any form (type alias, type definition, struct) where should it be, it seems to be trace specific but all the other signals depend on it, so will have a cross signals dependency here. The idea was can we remove the helper (type alias, type definition, struct) and use simple `[X]byte`?

**Comment by Aneurysm9** [comment]
I believe that the helper methods provide value and I would not want to see them re-implemented everywhere they're needed.  If the type definitions live in either the common or trace packages they will be in a stable location.  While they may be referenced by unstable signals, that should be fine as long as the dependency flows in the direction of stability.

**Comment by bogdandrutu** [comment]
@Aneurysm9 Got your point, your vote is -1 on the proposal. Consider to add that as a reaction to the description. You also mentioned some improvements, which we may want to consider separately.

**Comment by bogdandrutu** [comment]
@open-telemetry/collector-approvers please add your thoughts and +/-1 for the issue.

**Comment by tigrannajaryan** [comment]
What's the argument for removing the wrapping? Absent such arguments I am in favour of keeping the status quo, which is: nicely encapsulated data type which benefits from strong typing where you can't accidentally mix it with some other [8]byte or [16]byte somewhere.

**Comment by bogdandrutu** [comment]
@tigrannajaryan the idea came as part of the confusion of where the trace/span ID should live: https://github.com/open-telemetry/opentelemetry-collector/pull/5087#discussion_r840701857

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan the idea came as part of the confusion of where the trace/span ID should live: [#5087 (comment)](https://github.com/open-telemetry/opentelemetry-collector/pull/5087#discussion_r840701857)

I think `pcommon` is a good place.

**Comment by dmitryax** [comment]
Ok sounds like we have enough feedback to keep the wrapping in `pcommon`. I'm closing the issue then
