### ISSUE TITLE
Allow for use of Environment Variables inside of the Collector Configuration

### ISSUE THREAD

**Issue by Beardface123** [open-telemetry/opentelemetry-collector#5139]
**Is your feature request related to a problem? Please describe.**
When using the collector for Prometheus metrics as a Kubernetes deployment and using a Configmap to store the configuration, one of my external labels needs to differ between each deployment replica.   This would be much easier if the collector were able to expand environment variables in the configuration

**Describe the solution you'd like**
Adopt a similar feature flag as [this one in Prometheus](https://prometheus.io/docs/prometheus/latest/feature_flags/#expand-environment-variables-in-external-labels) 

**Describe alternatives you've considered**
Currently we're looking into the Operator, or perhaps mapping each different replica to a separate configmap (which isn't ideal)

**Comment by Aneurysm9** [comment]
[This is supported.](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables)

**Comment by bogdandrutu** [comment]
This can be closed per @Aneurysm9 comment
