### ISSUE TITLE
Persistent queue concurrent database compaction 

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#5159]
**Is your feature request related to a problem? Please describe.**

As discussed on [CNCF Slack](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1649164777465889), it was observed that after persistent queue grows, the space is not reclaimed automatically after draining. This is due to how bbolt (used underneath) operates and is [a known limitation](https://github.com/etcd-io/bbolt/issues/288). As a workaround, a compaction might be used (which was [added already](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7766)) but it can be safely done only when the underlying bbolt database is not being used (e.g. on startup).

**Describe the solution you'd like**
It would be welcome the collector to manage the persistent queue in a smarter way. Perhaps rotate the databases underneath and after one of them is drained, compact it and rotate again

**Describe alternatives you've considered**
Any other idea is welcome

**Comment by pmm-sumo** [comment]
FYI, @swiatekm-sumo was doing some research and it seems that doing a blocking compaction is very fast most of the time (he got even just ~100ms for 10GB file). We're going to make some more tests on that but it would be relatively simple solution to the problem, if feasible

**Comment by swiatekm-sumo** [comment]
Compaction in bbolt is pretty much just copying all the key-value pairs from the source DB to a new one, so the cost is proportional to the total size of the data (bbolt uses a B-tree), and doesn't depend on the size of the freelist (the total size of the database file). So as long as we make sure to only compact with a small amount of data in the queue, doing a stop-the-world compaction should be good enough. We still need to test it on slower disks (will try on AWS EBS volumes sometime this week), but it would be nice to not have to mess around with binlogs and rotating the DBs.

**Comment by djaglowski** [comment]
Nice results.

**Comment by swiatekm-sumo** [comment]
@overmeulen see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9327 for a proposed mechanism. In essence, compaction is most useful for queues (which can grow and shrink rapidly), and its cost is proportional to the size of the data. And so we compact if the size of the data is below a threshold (ideally a low value in the order of 10s of Mbs) and the file size is above a different threshold (to avoid compacting too often). 

There isn't much point in compacting storage with a significant amount of data in it, as it's going to be expensive, and a queue is likely to go down to 0 quickly anyway.

**Comment by pmm-sumo** [comment]
@overmeulen I provided some [explanation on how this works in the README](https://github.com/pmm-sumo/opentelemetry-collector-contrib/tree/filestorage/online-compaction/extension/storage/filestorage#rebound-online-compaction)

**Comment by swiatekm-sumo** [comment]
@pmm-sumo I think we can close this? The resolution is for the storage to take care of this, right now. Or should we wait until compaction is enabled by default in the file storage extension? @djaglowski

**Comment by djaglowski** [comment]
@swiatekm-sumo, we can have a new issue if there is a proposal to enable by default.
