### ISSUE TITLE
pdata representation of time obscures empty timestamps

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#5166]
**Describe the bug**

The log [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-timestamp) specifies that the `Timestamp` field should be empty in some cases. However, the `pdata` representation of time obscures empty timestamps, making it difficult to correctly assess whether the field is actually empty or not.

**Steps to reproduce**

```go
func TestTimeIsZero(t *testing.T) {
	var timestamp time.Time
	pdataTimestamp := pdata.NewTimestampFromTime(timestamp)
	t.Log(pdataTimestamp) // "1754-08-30 22:43:41.128654848 +0000 UTC"

	// PASS - Workaround works
	require.True(t, pdataTimestamp.AsTime().Before(time.Unix(0, 0)))

	// FAIL - Should evaluate to true, but doesn't
	require.True(t, pdataTimestamp.AsTime().IsZero(), "time is not zero")
}
```

**What did you expect to see?**

There should be a way to test whether the timestamp is empty. 

Probably, either `pdata.Timestamp.AsTime().IsZero()` should work accurately, or at least a `pdata.Timestamp.IsZero()` function should be available.

**Comment by bogdandrutu** [comment]
@djaglowski see also https://github.com/open-telemetry/opentelemetry-collector/issues/5102

**Comment by djaglowski** [comment]
Closing, as #5102 appears to request the same functionality.
