### ISSUE TITLE
Use interface logger instead of zap

### ISSUE THREAD

**Issue by jmichalak-fluxninja** [open-telemetry/opentelemetry-collector#5194]
**Is your feature request related to a problem? Please describe.**
Currently I use zerolog with custom configuration for logging in my application. `opentelemetry-collector` uses a hardcoded zap, so to have a consistent logging format, I would need to keep two configs for each library.

**Describe the solution you'd like**
It would be great if this library used a logger interface and zap could be a default logging library, but one could swap it with e.g. zerolog/logrus.

**Describe alternatives you've considered**
Another alternative to have consistent logging is to create an adapter and use `replace <...>` in go.mod, but this is boilerplate work and adds complexity.

**Comment by mx-psi** [comment]
Still boilerplatey but you can write a custom `zap.Core` and use [`WrapCore`](https://pkg.go.dev/go.uber.org/zap#WrapCore) to wrap your zerolog logger into a `zap.Logger`. 

If using `service.Collector` you can pass this option via [`service.CollectorSettings.LoggingOptions`](https://pkg.go.dev/go.opentelemetry.io/collector@v0.48.0/service#CollectorSettings). We [do this on Windows](https://github.com/open-telemetry/opentelemetry-collector/blob/8eb68f40028df449463c79367a538a2b0ee8d887/service/collector_windows.go#L169) if you want an example.

**Comment by jmichalak-fluxninja** [comment]
Thanks, that was very helpful. But I hope I'll see more flexible approach at some point ;)

**Comment by mx-psi** [comment]
> Thanks, that was very helpful. But I hope I'll see more flexible approach at some point ;)

What kinds of things can't you do with `WrapCore` that you wish you could?

**Comment by mx-psi** [comment]
I am going to close this as wontfix because I believe using `WrapCore` as documented on my comment above (https://github.com/open-telemetry/opentelemetry-collector/issues/5194#issuecomment-1096798530) is as flexible as we can be. If you disagree, please provide an example of something you can't do with `WrapCore` but would like to do so we can discuss something concrete.
