### ISSUE TITLE
[exporter/exporterhelper] allow to specify max queue size in bytes

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#5213]
**Is your feature request related to a problem? Please describe.**
Currently it's possible to specify the maximum size of the queue (both memory-backed and persistent) in number of batches. It would be useful to specify max size in bytes (especially for the persistent queue)

**Describe the solution you'd like**

We could add another parameter, which could be used to describe the maximum size in bytes. To avoid confusing the queue size limit in number of batches vs number of bytes, perhaps `queue_size` could be deprecated (and used as an alternative for one of the new parameters). Then we could have `queues_size_batches` and `queue_size_bytes` or so (other suggestions welcome).

When both of them are specified, hitting any would cause dropping data

**Comment by pmm-sumo** [comment]
This can be assigned to me

**Comment by jpkrohling** [comment]
Jaeger has something like that and I think there is a performance penalty in collecting the model's byte size. If that's the case here as well, I'd recommend collecting the size in an opt-in manner.

**Comment by pmm-sumo** [comment]
> Jaeger has something like that and I think there is a performance penalty in collecting the model's byte size. If that's the case here as well, I'd recommend collecting the size in an opt-in manner.

This will be not really the case (at least for the persistent one) since we are marshalling the stored items, which means we have number of bytes practically already available :)
