### ISSUE TITLE
tracer : handleTrace func() pass header to ctx

### ISSUE THREAD

**Issue by liguozhong** [open-telemetry/opentelemetry-collector#5216]
fix tempo issue.
https://github.com/grafana/tempo/issues/495
 https://github.com/grafana/tempo/issues/1381

vendor/go.opentelemetry.io/collector/receiver/otlpreceiver/otlphttp.go:47
![image](https://user-images.githubusercontent.com/9583245/163338052-31f95abd-ddb9-45a4-8a01-b86e650523fd.png)

tempo interface
![image](https://user-images.githubusercontent.com/9583245/163308217-6dd36818-b528-4173-8860-9255c642bf5a.png)

**Comment by bogdandrutu** [comment]
@liguozhong please mention the version you use of the collector module?

**Comment by bogdandrutu** [comment]
@liguozhong seems that you use a version from 2y ago:

1. https://github.com/grafana/tempo/blob/main/go.mod#L243
2. https://github.com/grafana/opentelemetry-collector

Based on this, I think you should first get closer to our current version, because we will not support something that is that old.
