### ISSUE TITLE
Inconsistent `Set[Traces|Metrics|Logs]` on Request objects

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5230]
All pdata structs do not allow to "set" mutable objects, to avoid race conditions and concurrency issues, but allows copy or move. The current "otlp.Request" struct for all signals is the only place where we have this.

I propose to fix this inconsistency, and here are some options:

1. "Wrapping": Replace SetTraces with a `NewRequestFrom[Traces|Logs|Metrics]` (other ideas `WrapRequest`), and document that it "wraps" the given object. Which means changes to `Request.Traces()` will be reflected in the initial `Traces` struct.
2. "Moving": Remove the current `SetTraces` API and force users to call `td.MoveTo(Request.Traces())`, a.k.a. move the given `Traces` to the request. This makes for example the current OTLP exporter to need to "mutate" data since it "moves" the original data. This is very cheap operation if and only if no other exporter installed on the same pipeline, otherwise this will force a copy of the original data (each exporter will receive its own copy).

From performance perspective, I kind of like the "wrapping" option, and I think would make sense to our users, as long as we document that the Request is a wrapper on top of the signal data, and changes are reflected to the underlying data.

**Comment by dmitryax** [comment]
I would also prefer `NewRequestFrom[Traces|Logs|Metrics]` (1). This problem doesn't seem to be something that justifies making otlp exporter mutable.
