### ISSUE TITLE
Docs incorrectly state that exporters must not mutate incoming pdata

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector#5232]
[The README in the exporter package](https://github.com/open-telemetry/opentelemetry-collector/blob/cdd11e7228ea646dd6df9094ea7062f03563046a/exporter/README.md#data-ownership) states that exporters will share data ownership of pdata.* with other exporters, but this is not actually the case.

If the exporter signals that it mutates data via its Capabilities, a copy is actually passed to the exporter, which was implemented in #4037. The documentation should be updated to reflect this.

**Comment by bogdandrutu** [comment]
@BinaryFissionGames you are correct. we should fix that.

**Comment by xyq175com** [comment]
Hi @BinaryFissionGames, should we change this from “When multiple exporters are configured to send the same data (e.g. by configuring multiple exporters for the same pipeline) the exporters will have a shared access to the data.” to "**When multiple exporters are configured to send the same data (e.g. by configuring multiple exporters for the same pipeline) the exporters will have a shared access to the data.If the exporter signals that it mutates data via its Capabilities, a copy is actually passed to the exporter**"?

**Comment by BinaryFissionGames** [comment]
@xyq175com Yes, that is accurate.

**Comment by xyq175com** [comment]
@BinaryFissionGames  thank you, I will work on this and submit PR later。

**Comment by BinaryFissionGames** [comment]
Thanks @xyq175com!

**Comment by matej-g** [comment]
FYI, I think there's still a mistake in the doc. It states that the exporter will receive a copy if the mutation is declared in its capabilities. But in the same breath, the next sentence claims the exporter need to make a copy itself. I believe this is a leftover from previous version and should be removed?
