### ISSUE TITLE
Collector Stopping Due to Context Cancel is Noisy

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector#5242]
**Describe the bug**
In the collector when context passed into `Run` is cancelled the collector logs and error message [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L182). When the context is from a `signal.NotifyContext` call it gives the user an error log and stack trace. This can cause the user to think there is something wrong when the collector correctly shut down.

Example of error log:

```
2022-04-20T14:25:06.545-0400	error	service/collector.go:182	Context done, terminating process	{"error": "context canceled"}
go.opentelemetry.io/collector/service.(*Collector).runAndWaitForShutdownEvent
	/home/otel/go/pkg/mod/go.opentelemetry.io/collector@v0.49.0/service/collector.go:182
go.opentelemetry.io/collector/service.(*Collector).Run
	/home/otel/go/pkg/mod/go.opentelemetry.io/collector@v0.49.0/service/collector.go:255
main.runInteractive
	/home/otel/git/observiq-otel-collector/cmd/collector/main.go:51
main.run
	/home/otel/git/observiq-otel-collector/cmd/collector/main_others.go:27
main.main
	/home/otel/git/observiq-otel-collector/cmd/collector/main.go:40
runtime.main
	/usr/local/go/src/runtime/proc.go:250
```

**Steps to reproduce**

1. Pass a context from `signal.NotifyContext` into the collector.
2. Let the program run for a bit then SIGTERM it and observe the error log.

**What did you expect to see?**
A more graceful shutdown message that doesn't print a stack trace. Likely just changing the log level to a debug log. Maybe print and error 

**What did you see instead?**
Error log with a stack trace

**What version did you use?**
Version: `v0.49.0`

**Config**
Any configuration works. `DisableGracefulShutdown` must be set to `true` so the wrapping program can intercept the signals.

**Additional context**

I believe we should reduce the log level of exiting due to a context. If we want to error maybe only do so on a `context.DeadlineExceeded` error.

**Comment by bogdandrutu** [comment]
Don't think is a bug, but is a good feature request ¯\_(ツ)_/¯
