### ISSUE TITLE
Zipkin to Jaeger Span translation error flag not set

### ISSUE THREAD

**Issue by vikrambe** [open-telemetry/opentelemetry-collector#526]
**Problem** : JaegerUI isnt highlighting spans with error status when zipkin traces are received by otelcol and exported as jaeger spans.
**Why is this happening ?**
JaegerUI depends on Jaeger Span Model : Where "error" tag of "Bool" type is set by the jaeger collector upon receiving zipkin span with error status code. 

Issue : OtelCol translation from zipkin model to jaeger model sets error tag as string and not as bool  during the translation.

**Input [Zipkin Span]**
  {
    "traceId": "631ef3c9f9250805",
    "id": "631ef3c9f9250805",
    "kind": "SERVER",
    "name": "http:/one",
    "timestamp": 1580830219488000,
    "duration": 29312,
    "localEndpoint": {
      "serviceName": "foo-service",
      "ipv4": "192.168.1.8",
      "port": 9001
    },
    "tags": {
      **_"error": "Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException: 500 null",_**
      "http.host": "localhost",
      "http.method": "GET",
      "http.path": "/one",
      "http.status_code": "200",
      "http.url": "http://localhost:9001/one",
      "mvc.controller.class": "FooController",
      "mvc.controller.method": "one",
      "spring.instance_id": "192.168.1.8:order-service-sleuth:9001"
    }
  }
 
**Actual [Otel Translated Jaeger Span - where error tag is still string]**
{
    "traceIdLow": 6186857723629179000,
    "traceIdHigh": 0,
    "spanId": 6186857723629179000,
    "parentSpanId": 0,
    "operationName": "http:/one",
    "flags": 0,
    "startTime": 1580830930191000,
    "duration": 108645,
    "tags": [
      {
        "key": "http.status_code",
        "vType": "STRING",
        "vStr": "200"
      },
      {
        "key": "spring.instance_id",
        "vType": "STRING",
        "vStr": "192.168.1.8:order-service-sleuth:9001"
      },
      {
        "key": "http.method",
        "vType": "STRING",
        "vStr": "GET"
      },
      {
        "key": "http.path",
        "vType": "STRING",
        "vStr": "/one"
      },
      {
        "key": "port",
        "vType": "STRING",
        "vStr": "9001"
      },
      {
        "key": "http.url",
        "vType": "STRING",
        "vStr": "http://localhost:9001/one"
      },
      {
        "key": "mvc.controller.class",
        "vType": "STRING",
        "vStr": "FooController"
      },
      {
        "key": "mvc.controller.method",
        "vType": "STRING",
        "vStr": "one"
      },
      **{
        "key": "error",
        "vType": "STRING",
        "vStr": "Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException: 500 null"
      }**,
      {
        "key": "http.host",
        "vType": "STRING",
        "vStr": "localhost"
      },
      {
        "key": "ipv4",
        "vType": "STRING",
        "vStr": "192.168.1.8"
      },
      {
        "key": "span.kind",
        "vType": "STRING",
        "vStr": "server"
      },
      {
        "key": "status.code",
        "vType": "LONG",
        "vLong": 2
      }
    ]
  }

**Expected [JagerSpan where error type is changed to bool and its value is set as errorMessage]**
{
    "traceIdLow": 8380789575664951000,
    "traceIdHigh": 0,
    "spanId": 8380789575664951000,
    "parentSpanId": 0,
    "operationName": "http:/one",
    "flags": 0,
    "startTime": 1580830714594000,
    "duration": 79701,
    "tags": [
      {
        "key": "http.url",
        "vType": "STRING",
        "vStr": "http://localhost:9001/one"
      },
      {
        "key": "mvc.controller.class",
        "vType": "STRING",
        "vStr": "FooController"
      },
      {
        "key": "mvc.controller.method",
        "vType": "STRING",
        "vStr": "one"
      },
      **{
        "key": "error",
        "vType": "BOOL",
        "vBool": true
      },
      {
        "key": "errorMessage",
        "vType": "STRING",
        "vStr": "Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException: 500 null"
      },**
      {
        "key": "http.method",
        "vType": "STRING",
        "vStr": "GET"
      },
      {
        "key": "http.host",
        "vType": "STRING",
        "vStr": "localhost"
      },
      {
        "key": "http.path",
        "vType": "STRING",
        "vStr": "/one"
      },
      {
        "key": "ipv4",
        "vType": "STRING",
        "vStr": "192.168.1.8"
      },
      {
        "key": "port",
        "vType": "STRING",
        "vStr": "9001"
      },
      {
        "key": "spring.instance_id",
        "vType": "STRING",
        "vStr": "192.168.1.8:order-service-sleuth:9001"
      },
      {
        "key": "http.status_code",
        "vType": "STRING",
        "vStr": "200"
      },
      {
        "key": "span.kind",
        "vType": "STRING",
        "vStr": "server"
      },
      {
        "key": "status.code",
        "vType": "LONG",
        "vLong": 2
      }
    ]
  }

**Comment by pjanotti** [comment]
@vikrambe could you please provide some more info?

**Comment by vikrambe** [comment]
> @vikrambe could you please provide some more info?

@pjanotti JaegerUI relies on error flag [i.e. bool value] to color code the spans with error. 
Zipkin spans [i.e. with error string set] when received and get converted to OC model, error continues to be stringType holding error message. When JaegerExporter converts from OC model to jaeger model error is shipped as string to jaeger and not as bool. This leads the UI to not highlight error spans in red color.

The fix would be to add additional tag to carry errorMessage and set error as bool.

**Comment by tigrannajaryan** [comment]
@vikrambe please update the description of this issue. Provide full details about what you intend to change in Zipkin translation. Translation code is highly sensitive and changes will only be accepted after considering all aspects and ensuring it does not break existing functionality.

**Comment by vikrambe** [comment]
> @vikrambe please update the description of this issue. Provide full details about what you intend to change in Zipkin translation. Translation code is highly sensitive and changes will only be accepted after considering all aspects and ensuring it does not break existing functionality.

@tigrannajaryan Please go through the description and let me know your thoughts on the same.
