### ISSUE TITLE
[pdata] Defensive setters/getters for primitive value slices

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5263]
This is generalized issue made from https://github.com/open-telemetry/opentelemetry-collector/issues/4181.

We have the following setters accepting slices of primitive types (with similar getters) that take the value as is without using defensive copying:

```
Value.SetBytesVal(bv []byte)
HistogramDataPoint.SetBucketCounts(v []uint64)
HistogramDataPoint.SetExplicitBounds(v []float64)
```

We need to make at least the setters to use defensive copies of the slices passed as arguments, so any change to the value slice that used as the argument to the setter doesn't affect stored value.

An open question if we should do the same for getters and return copies instead of the stored values.

UPD:

The decision was made to wrap primitive slices into another structure like `ImmutableUInt64Slice`. In order to update all the methods working directly with primitive slices in a backward compatible way, we are going to make several changes across multiple OTel Collector releases:

**0.51.0**: Prefix all the methods working with primitive slices with `M` by introducing new methods and deprecating old ones.
**0.52.0**: Remove methods that are not prefixed with `M`.
**0.53.0**: Introduce methods that are not prefixed with `M` back, but now working with new immutable slice structs
**0.54.0**: Remove methods prefixed with `M`.

**Comment by dmitryax** [comment]
> An open question if we should do the same for getters and return copies instead of the stored values.

If we don't do the same for getters, we introduce another way to mutate the slices. And doing it that way may cause some subtle bugs. E.g. if exporter uses one of these getters and then changes the returned value, it makes the exporter mutating which is hard to track in this scenario, and this can also happen accidentally.

I vote for using defensive copying for getters as well setters. It makes it easier to track pdata mutations.

**Comment by dmitryax** [comment]
@open-telemetry/collector-approvers please share your opinions

**Comment by tigrannajaryan** [comment]
We can try "moving" setters to avoid the copying performance impact (bytes can be potentially large):
```go
Value.SetBytesVal(bv *[]byte) {
  target = *bv
  *bv = nil
}
```
If the caller needs to hold a copy for some reason they can make copy before the call.

Not very idiomatic, I know.

Probably unnecessary for histograms since the bucket is cannot be very large (I think?)

**Comment by dmitryax** [comment]
@tigrannajaryan I think that's ok to use for setter, but what about getters?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan I think that's ok to use for setter, but what about getters?

We can define our ImmutableByteSlice data type and return it from getters. It complicates working with slices though. It will make impossible to use index operator (which we probably never do). ImmutableByteSlice can have methods with everything that we need to do with the byte slice (we use it very rarely in our codebase).

Don't know if we want to do this. May be too much complication.

**Comment by dmitryax** [comment]
> We can define our ImmutableByteSlice data type and return it from getters. It complicates working with slices though. It will make impossible to use index operator (which we probably never do). ImmutableByteSlice can have methods with everything that we need to do with the byte slice (we use it very rarely in our codebase).

The only place where `ImmutableByteSlice` can be used after that is probably `Value.SetBytesVal`. In other cases the value needs to be passed somewhere else where `[]byte` type is expected, so we still need to get a copy of `[]bytes` type from `ImmutableByteSlice`. 

So I'm not sure if introducing `ImmutableByteSlice` just to support a use case of copying from one `Value` to another justifies the added complexity.

There are only few usages core/contrib, all of them rely on the following two core functions:
- `Value.asRaw()`: the bytes are converted into `interface{}`. We have has to use a copy here.
- `Value.AsString()`: we don't need a copy here, we can use another internal method that returns the bytes value as is.

**Comment by dmitryax** [comment]
@bogdandrutu raised another benefit of using `Immutable...Slice` wrapper: `CopyTo` functionality won't need to do any copy and can reuse underlying array. So probably it can justify additional complexity. 

I can submit a PR and we'll see how it looks.

**Comment by tigrannajaryan** [comment]
I think I also saw code somewhere that takes Bytes() and converts to JSON string. This can become a method on ImmutableByteSlice and avoid the extra copy.

**Comment by dmitryax** [comment]
@gbbr yes, it's on track. the schedule for this change is posted in the description
