### ISSUE TITLE
Opentelemetry: How to increase instrument for exceeded the maximum allowed accumulations (2000) as its Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR

### ISSUE THREAD

**Issue by ssuparna2010** [open-telemetry/opentelemetry-collector#5303]
**Describe the bug**
When we run bulk load metrics are Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR. and getting instrument for exceeded the maximum allowed accumulations (2000)

**Steps to reproduce**
When we run bulk load metrics are Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR. and getting instrument for exceeded the maximum allowed accumulations (2000)

**What did you expect to see?**
we need metrics to export to prometheus

**What did you see instead?**
getting many exception
2022-05-02 16:24:04,817 SEVERE [io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR
2022-05-02 16:27:57,974 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0236: Suspending server with no timeout.
2022-05-02 16:27:58,004 WARNING [io.opentelemetry.sdk.metrics.internal.state.AsynchronousMetricStorage] (Thread-251) Instrument Temn_Transact_Jbc_Cache.hit has exceeded the maximum allowed accumulations (2000).
2022-05-02 16:27:58,018 WARNING [io.opentelemetry.sdk.metrics.internal.state.AsynchronousMetricStorage] (Thread-251) Instrument Temn_Transact_Jbc_Cache.stats has exceeded the maximum allowed accumulations (2000).
2022-05-02 16:27:58,031 WARNING [io.opentelemetry.sdk.metrics.internal.state.AsynchronousMetricStorage] (Thread-251) Instrument Temn_Transact_Jbc_Cache.miss has exceeded the maximum allowed accumulations (2000).
2022-05-02 16:27:58,313 SEVERE [io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter] (OkHttp http://localhost:4317/...) Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR

**What version did you use?**
Version: [temn-otel:0.47.0
otel libraries v0.10.0

**What config did you use?**
Config:yaml config file

"receivers:
  otlp:
    protocols:
      grpc: # Listening on port 4317
      http: # Listening on port 4318

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:      

processors:
  batch: 
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
    
extensions:
  zpages:
    endpoint: "0.0.0.0:55679"
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 683
  health_check: 
  pprof: 
  
exporters:
  # Data pipelines: traces, metrics, logs
  logging:
    loglevel: debug
  
  # Data pipelines: traces
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  
  # Data pipelines: metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    #namespace: "default"
    
  # Data pipelines: traces, metrics, logs
  influxdb:
    endpoint: http://influxdb:8086
    timeout: 500ms
    org: Temenos
    bucket: TemnBucket
    token: MyVerySecretToken
    metrics_schema: telegraf-prometheus-v1

    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
   
  splunk_hec:
    # Splunk HTTP Event Collector token.
    token: "00000000-0000-0000-0000-0000000000000"
    # URL to a Splunk instance to send data to.
    endpoint: "https://splunk:8088/services/collector"
    # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
    source: "otel"
    # Optional Splunk source type: https://docs.splunk.com/Splexicon:Sourcetype
    sourcetype: "otel"
    # Splunk index, optional name of the Splunk index targeted.
    index: "metrics"
    # Maximum HTTP connections to use simultaneously when sending data. Defaults to 100.
    max_connections: 200
    # Whether to disable gzip compression over HTTP. Defaults to false.
    disable_compression: false
    # HTTP timeout when sending data. Defaults to 10s.
    timeout: 10s
    tls:
      # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
      insecure_skip_verify: true

  otlp:
    endpoint: 'http://someotlp.target.com:4317' # Replace with a real endpoint.
    tls:
      insecure: true
      
service:
  extensions: [zpages, memory_ballast]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [jaeger, influxdb]
    metrics:
      receivers: [otlp,hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheus, influxdb]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, influxdb]

"

**Comment by jack-berg** [comment]
This error is produced by the otel java SDK due to exceeding the fixed cardinality ceiling. Its currently not possible to record measurements for more than 2000 distinct sets of attributes to a particular instrument. The answer is to reduce the cardinality of your instruments by excluding attributes with high cardinality values.

This is definitely not an issue with the collector and should be closed.
