### ISSUE TITLE
[pdata] Inconsistently exported AsRaw methods

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5310]
Currently only `Map` has exported `AsRaw` method and `NewMapFromRaw` function. Very similar `Slice` structure has the same but not exported functions: `asRaw` and `newSliceFromRaw`. Another structure that has the same unexported functions is `Value`.

I propose to expose at least `Slice.AsRaw()` and `NewSliceFromRaw` for consistency with `Map`. Not sure about `Value`, probably we can keep it can stay unexported until there is a need.

**Comment by bogdandrutu** [comment]
do you also need a fromRaw for the slice?

**Comment by dmitryax** [comment]
Right. I missed that. Updated the issue description and the PR
