### ISSUE TITLE
`http` receiver drops JSON requests with extra keys 

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-collector#5312]
**Describe the bug**
JSON requests with extra keys are dropped by the `http` receiver. This can cause older collectors to not work with newer exporters in case new optional fields are added (as suggested in https://github.com/open-telemetry/oteps/pull/201) or renamed. 

The suggested workaround for the renamed `instrumentationLibraryMetrics` was to double-publish the same data (see [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L72-L76)). However, since to requests with extra keys (in this case `scopeMetrics`) are dropped, it is not possible to use newer JSON exporters that implement this spec with collector versions older than `0.48`. 

To prevent this in the future, it might make sense to allow extra keys in the request payload.

**Steps to reproduce**

1. Create a file `request-with-extra-key.json` and add the following:

```json
{
    "resourceMetrics": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "basic-metric-service"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "scopeMetrics": [
                {
                    "metrics": [
                        {
                            "description": "Example of a Counter",
                            "name": "requests",
                            "sum": {
                                "aggregationTemporality": 2,
                                "dataPoints": [
                                    {
                                        "asDouble": 1,
                                        "attributes": [],
                                        "startTimeUnixNano": 1651578664709780000,
                                        "timeUnixNano": 1651578666712823600
                                    }
                                ],
                                "isMonotonic": true
                            },
                            "unit": "1"
                        }
                    ],
                    "scope": {
                        "name": "example-exporter-collector",
                        "version": "",
                        "extraKey": "value"
                    }
                }
            ]
        }
    ]
}
```

This JSON has an key `extraKey` in the `scope`. Simulating what would happen if an optional field would be added in a future version of [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto).

2. Send the request to a collector
`curl -X POST -H "Content-Type: application/json" -d @request-with-extra-key.json -i localhost:4318/v1/metrics`

**What did you expect to see?**
A `200` response and metrics being processed and `extraKey` in scope being dropped (and possibly a log message).

**What did you see instead?**
A `400 Bad Request` response with
`{"code":3,"message":"unknown field \"extraKey\" in v1.InstrumentationScope"}`

**What version did you use?**
`v0.50.0`

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]

```

**Environment**
OS: Ubuntu 20.04

**Additional context**

This is something that came up while [updating the JSON Exporter in the OpenTelemetry JS repo](https://github.com/open-telemetry/opentelemetry-js/pull/2929#discussion_r860846247). Here, we cannot improve compatibility by implementing the suggestions from the [spec](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L72-L76), as the resulting requests would just be dropped by collectors older than `0.48`. The suggested double publishing will only work with `0.48` and up.

I also created [this gist](https://gist.github.com/pichlermarc/672fa99d48e15afb4a671f97d5674ff0) with an a few example payloads to play around with.

**Comment by dyladan** [comment]
The spec suggestion was to send both keys, but maybe it should be just an opt-in feature to send old keys? Or a target collector version as an option? but that would be very difficult to maintain

**Comment by dyladan** [comment]
I'll work on this

**Comment by pichlermarc** [comment]
The same thing happened with `min` and `max` that were recently added to the Histogram data point. When sending `min` and `max` the whole request is dropped collector versions <0.52.

**Comment by gespi1** [comment]
@pichlermarc thank you for this post! saved me tons of time
