### ISSUE TITLE
[Otlpexporter] Support path in endpoint

### ISSUE THREAD

**Issue by danhngo-lx** [open-telemetry/opentelemetry-collector#5319]
**Is your feature request related to a problem? Please describe.**
Hello, I wonder if it is possible to specify a path in the endpoint of otlp exporter, like this:

```
exporters:
  otlp:
    endpoint: my-example-endpoint.com:443/custom/path
```

At the moment when I try to do so, I get the following error:

```
info    exporterhelper/queued_retry.go:276      Exporting failed. Will retry the request after interval.        {"component_kind": "exporter", "component_type": "otlp", "component_name": "otlp", "error": "failed to push trace data via OTLP exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address tcp/443/custom/path: unknown port\"", "interval": "5.52330144s"}
```

**Describe the solution you'd like**
Support path in the endpoint of otlp exporter if possible

**Additional context**
I'm using Istio and looking for a way to publish traces from opentelemtry collector to a public endpoint. I would like to use an existing domain with a different path for this endpoint.

**Comment by bogdandrutu** [comment]
A bit confused on how that will work. The `otlp` exporter uses `gRPC` which comes with some "path" requirements already, so how would that combine with the given `path` from the endpoint?

For the `http` exporter, you can `otlphttp` which has capability of customizing the path for traces/metrics/logs endpoints, see `traces_endpoint` in https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
