### ISSUE TITLE
[Metrics]Support max/min value with  HistogramDataPoint

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-collector#5320]
` opentelemetry-proto  v0.17.0 `  HistogramDataPoint add max/min ， java sdk  is using. 
![image](https://user-images.githubusercontent.com/11512994/167239592-05930ae0-d489-4c84-9bc5-880dd76493a4.png)

[_link_]( https://github.com/open-telemetry/opentelemetry-proto/blob/v0.17.0/opentelemetry/proto/metrics/v1/metrics.proto).
 opentelemetry-collector is supporting now?

**Comment by bogdandrutu** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/5399
