### ISSUE TITLE
Does `confighttp` based HTTP server generate metrics like number of incoming requests?

### ISSUE THREAD

**Issue by neelayu** [open-telemetry/opentelemetry-collector#5327]
I am trying to explore if receivers built on top using `confighttp.HTTPServerSettings` generate useful metrics such as num of incoming requests, packets not forwarded to the processor(or exporter) etc. From the code I could see that the [`otelhttp`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go#L298) instrumentation is used. However  the `/metrics` endpoint on `service.telemetry.metrics.address=:8888` endpoint reports no metrics(empty page) if we use `telemetry.useOtelForInternalMetrics` feature flag and basic obs views(exporter and processor metrics) otherwise.

Can anyone tell me if its the correct way to observe the collector? 
Thanks

**Comment by jpkrohling** [comment]
I know how it sounds, but the collector has limited self-observability capabilities. It should start changing once the Go SDK has the features we need. See #4198.
