### ISSUE TITLE
Change all structs with public members before stability

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5358]
[Here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/telemetry.go#L25) is an example of a struct `TelemetrySettings` that seem to be very easy to use. The problem with this is that we cannot add any new member in this struct, or change the order of the members, after 1.0.

**Why?**

The reason is because if someone uses initialization without "named arguments", e.g. `tel := component.TelemetrySettings{nil, nil, nil, 0}`, this will break if we change order or if we add a new member to the struct.

**Solution 1**

Use getter/setter for all these structs instead of public members. We can provide a constructor, witch can be extended with a variadic option pattern when we need to extend, or overload with a different constructor (different name).

**Solution 2**

Not 100% sure this works for all the cases, but embedding a blank internal field may work:

```golang
type noinit [0]func()

type TelemetrySettings struct {
	_ noinit

	// Logger that the factory can use during creation and can pass to the created
	// component to be used later as well.
	Logger *zap.Logger

	// TracerProvider that the factory can pass to other instrumented third-party libraries.
	TracerProvider trace.TracerProvider

	// MeterProvider that the factory can pass to other instrumented third-party libraries.
	MeterProvider metric.MeterProvider

	// MetricsLevel controls the level of detail for metrics emitted by the collector.
	// Experimental: *NOTE* this field is experimental and may be changed or removed.
	MetricsLevel configtelemetry.Level
}
```

Here are the results:
1. `var telemetry = TelemetrySettings{nil, nil, nil, nil, 1}` -> `../../component/telemetry.go:45:35: cannot use nil as noinit value in struct literal`
2. `var telemetry = TelemetrySettings{nil, nil, nil, 1}` -> 
`../../component/telemetry.go:45:35: cannot use nil as noinit value in struct literal
../../component/telemetry.go:45:50: cannot use 1 (constant of type int) as type metric.MeterProvider in struct literal:
        int does not implement metric.MeterProvider (missing Meter method)
../../component/telemetry.go:45:51: too few values in struct literal`
3. `var telemetry = TelemetrySettings{noinit{}, nil, nil, nil, 1}` -> everything works, but `noinit` is private so external users cannot do this.

@open-telemetry/collector-approvers please add your preference and thoughts, I do believe that it is a MUST to not keep the current state.

**Comment by dmitryax** [comment]
It looks like we are trying to go beyond [go1 stability guarantees](https://go.dev/doc/go1compat) here. They have this particular exception:

> Struct literals. For the addition of features in later point releases, it may be necessary to add fields to exported structs in the API. Code that uses unkeyed struct literals (such as pkg.T{3, "x"}) to create values of these types would fail to compile after such a change. However, code that uses keyed literals (pkg.T{A: 3, B: "x"}) will continue to compile after such a change. We will update such data structures in a way that allows keyed struct literals to remain compatible, although unkeyed literals may fail to compile. (There are also more intricate cases involving nested data structures or interfaces, but they have the same resolution.) We therefore recommend that composite literals whose type is defined in a separate package should use the keyed notation.

Also AFIAK unkeyed struct literals are usually failing to pass linters and generally discouraged.  

Another potential breaking change can be caused by adding another struct member when downstream embeds our struct along with another struct that already has a field with the same name. But this issue can also be caused by adding another method to a struct. It doesn't seem right to avoid adding new methods because of that.

I believe we should clearly define stability guarantees for 1.0, probably just sticking to what's provided by go1.

**Comment by bogdandrutu** [comment]
I am fine to do nothing if we allow adding new fields and reordering in this structs. I think we need to clarify in our versioning doc

**Comment by bogdandrutu** [comment]
@dmitryax can you add this to the "versioning" doc that we have?
