### ISSUE TITLE
Failing to get docker image for demo

### ISSUE THREAD

**Issue by hectorhdzg** [open-telemetry/opentelemetry-collector#536]
Pulling collector (otelcol:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling collector (otelcol:latest)...
ERROR: pull access denied for otelcol, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Let me know if the image is somewhere else now or if I need special permissions to access it, currently working on OT Python exporter so it will be good to be able to run this

**Comment by pjanotti** [comment]
Hi @hectorhdzg - the demo as described at https://github.com/open-telemetry/opentelemetry-collector/tree/master/examples/demo use a locally built image of the service. If you want to run against the public image use omnition/opentelemetry-collector:latest - that matches this release https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.2.3

**Comment by hectorhdzg** [comment]
Getting following error with public image(omnition/opentelemetry-collector:latest):

Creating network "ot_default" with the default driver
Creating ot_zipkin-all-in-one_1 ... done
Creating ot_collector_1         ... error

ERROR: for ot_collector_1  Cannot create container for service collector: status code not OK but 500: {"Message":"Unhandled exception: Drive has not been shared"}

ERROR: for collector  Cannot create container for service collector: status code not OK but 500: {"Message":"Unhandled exception: Drive has not been shared"}

I will give a try with locally built image as well

**Comment by hectorhdzg** [comment]
Getting following error when running demo in Ubuntu

COMPONENT=otelcol make docker-component
make[1]: Entering directory '/home/hectorh/Desktop/opentelemetry-collector-master'
GOOS=linux make otelcol
make[2]: Entering directory '/home/hectorh/Desktop/opentelemetry-collector-master'
fatal: not a git repository (or any of the parent directories): .git
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/linux/otelcol -ldflags "-X github.com/open-telemetry/opentelemetry-collector/internal/version.GitHash= " ./cmd/otelcol
# github.com/open-telemetry/opentelemetry-collector/cmd/otelcol
unexpected fault address 0x7f709c9fc000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f709c9fc000 pc=0x45b937]

goroutine 1 [running]:
runtime.throw(0x690f25, 0x5)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc024086fa8 sp=0xc024086f78 pc=0x42dc32
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc024086fd8 sp=0xc024086fa8 pc=0x442bd5
runtime.memmove(0x7f709c9fbf60, 0x7f70a8f1f4de, 0xc8)
	/usr/local/go/src/runtime/memmove_amd64.s:242 +0x287 fp=0xc024086fe0 sp=0xc024086fd8 pc=0x45b937
cmd/link/internal/ld.(*OutBuf).Write(0xc0000828c0, 0x7f70a8f1f4de, 0xc8, 0xc8, 0x1, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/outbuf.go:65 +0xa0 fp=0xc024087030 sp=0xc024086fe0 pc=0x5ac550
cmd/link/internal/ld.(*OutBuf).WriteSym(0xc0000828c0, 0xc012934a90)
	/usr/local/go/src/cmd/link/internal/ld/outbuf.go:159 +0x6c fp=0xc024087080 sp=0xc024087030 pc=0x5acd1c
cmd/link/internal/ld.blk(0xc0000828c0, 0xc023850000, 0x113bc, 0x1a550, 0x11a2f60, 0x194732a, 0xc038b5448e, 0x1, 0x1)
	/usr/local/go/src/cmd/link/internal/ld/data.go:786 +0x10f fp=0xc024087150 sp=0xc024087080 pc=0x55999f
cmd/link/internal/ld.CodeblkPad(0xc0006e6000, 0x401000, 0x194732a, 0xc038b5448e, 0x1, 0x1)
	/usr/local/go/src/cmd/link/internal/ld/data.go:700 +0xbb fp=0xc024087260 sp=0xc024087150 pc=0x55908b
cmd/link/internal/amd64.asmb(0xc0006e6000)
	/usr/local/go/src/cmd/link/internal/amd64/asm.go:677 +0xe2 fp=0xc0240872d0 sp=0xc024087260 pc=0x5d1c32
cmd/link/internal/ld.Main(0x84bdc0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x69ac6c, 0x1b, 0x697753, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:262 +0xd5d fp=0xc024087428 sp=0xc0240872d0 pc=0x5ab59d
main.main()
	/usr/local/go/src/cmd/link/main.go:65 +0x1d6 fp=0xc024087f60 sp=0xc024087428 pc=0x614606
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc024087fe0 sp=0xc024087f60 pc=0x42f5ce
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc024087fe8 sp=0xc024087fe0 pc=0x45a501
Makefile:105: recipe for target 'otelcol' failed
make[2]: *** [otelcol] Error 2
make[2]: Leaving directory '/home/hectorh/Desktop/opentelemetry-collector-master'
Makefile:109: recipe for target 'docker-component' failed
make[1]: *** [docker-component] Error 2
make[1]: Leaving directory '/home/hectorh/Desktop/opentelemetry-collector-master'
Makefile:122: recipe for target 'docker-otelcol' failed
make: *** [docker-otelcol] Error 2

**Comment by hectorhdzg** [comment]
It would be great to have a stable docker image to use for demo/samples purposes

**Comment by pjanotti** [comment]
Hi @hectorhdzg error `{"Message":"Unhandled exception: Drive has not been shared"}` is related to docker not to the image. The second one seems a setup error and some of the tools used in the build is broken. That said perhaps having a way to run the demo without a local build is a good idea.

**Comment by hectorhdzg** [comment]
Thanks after updating docker to share C drive official image works fine, it would be good to add this somewhere more discoverable

**Comment by pjanotti** [comment]
@hectorhdzg ptal at the PR above, especially README.
