### ISSUE TITLE
How to consume metrics from OTLP-HTTP exporter

### ISSUE THREAD

**Issue by jvaesteves** [open-telemetry/opentelemetry-collector#5360]
I have been trying to deploy a web application in Python for to consume metrics from a OLTP Collector (with GZIP compression disabled), but unfortunately I'm always receiving the metrics in a format that I can't decode on the server. Here is a snippet example of this consumer:

```python
from protobuf_decoder.protobuf_decoder import Parser
from fastapi import FastAPI, Request

app = FastAPI()


@app.post("/v1/metrics")
async def get_body(request: Request):
    body = await request.body()
    print(Parser().parse(body))
```

I have already tried the following:

1. Just use the Protobuf Parser on the snippet (TypeError: cannot use a string pattern on a bytes-like object)
2. Decode the request body byte to a UTF-8 string (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 1: invalid continuation byte)
3. Re-enable GZIP compression and decompressing directly in the app (same errors decribed in 1 and 2)

With that, I have the following questions:

- Can I export the metrics using OTLP-HTTP in JSON instead of Protobuf?
- If not, how can I properly consume the metrics exported? If I need to use a schema to properly decode the messages, them what is it structure? (I looked in the Collectors project, but due to my limited knowledge of Golang I did not find it)
- Is the default encoding different than UTF-8?

**Comment by jvaesteves** [comment]
https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto

**Comment by andre-cavalheiro** [comment]
Hey there, funny enough I am having the exact same problem as you (I am even using fastAPI as well ahahaha).

Could you elaborate a bit more about whether & how you were able to overcome this? I had also arrived at the `metrics.probo` file, but I'm still having a hard time decoding.

I would greatly appreciate any help (Por favor 🙂)


.

**Comment by andre-cavalheiro** [comment]
Finally got it to work. Just for anyone that finds this, here is how to do it:

You need to generate the protobuffer's python specific data-model, you can see how to do that here: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto

If you follow those instructions you'll get a folder with python files in it defining different classes. You'll need to adpat this for your use-case but for example, for decoding metric-exporters to your endpoint simply import the class associated with it and than use that class to decode the request's body as such:

```
from opentelemetry.proto.metrics.v1 import metrics_pb2

body = await request.body()
data = metrics_pb2.MetricsData.FromString(body)
for m in data.resource_metrics:
    print(f'resource_attributes count: {len(m.resource.attributes)}')
    print(f'scope_metrics count: {len(m.scope_metrics)}')

```

Hope this helps!
