### ISSUE TITLE
Merge include/exclude logic from span package

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#539]
With https://github.com/open-telemetry/opentelemetry-collector/pull/537 the config for include and exclude are under object. This issue tracks having the Matcher object(or some logical name) that checks both the include and exclude properties for the processors. It would remove functions like https://github.com/open-telemetry/opentelemetry-collector/blob/328ad6d22b37f02e8079d0e896cfc3e188263b61/processor/attributesprocessor/attributes.go#L203

**Comment by flands** [comment]
@ccaraman @dmitryax is this still relevant?

**Comment by bogdandrutu** [comment]
This is stale since we are working on the new matching config
