### ISSUE TITLE
run .\otelcol.exe in windows appear Error: invalid map resolver config: no URIs

### ISSUE THREAD

**Issue by stevenlii** [open-telemetry/opentelemetry-collector#5394]
Error: invalid map resolver config: no URIs
2022/05/19 00:43:59 collector server run finished with error: invalid map resolver config: no URIs

run .\otelcol-contrib.exe
2022/05/19 00:43:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/05/19 00:43:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: invalid map resolver config: no URIs
2022/05/19 00:43:37 collector server run finished with error: invalid map resolver config: no URIs

/help

**Comment by bogdandrutu** [comment]
Need to pass a config file `.\otelcol.exe --config=path\to\config.yaml`
