### ISSUE TITLE
Remove AddCollectorVersionTag const

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#5404]
Is [AddCollectorVersionTag](https://github.com/open-telemetry/opentelemetry-collector/blob/c56d20e9e0afccc43179da12f60e24e5729caca9/service/telemetry.go#L49) const necessary?

In theory this is possible to overtime when building, but does anyone really ever do that? Looking at the [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/4140) that introduced it I think  this was done out of abundance of caution (just in case).

I think this can be deleted since it has been the behavior for 8 months now.

**Comment by bogdandrutu** [comment]
if anything a `featuregate` may be more appropriate, but I agree the constant is not good.
