### ISSUE TITLE
Collector downtime when deployed as a daemonset

### ISSUE THREAD

**Issue by dudicoco** [open-telemetry/opentelemetry-collector#5405]
Hi,

When rolling out a daemonset collector, old pods will be removed before new pods are created.
This is not a problem with logs because they are stored in a volume, or with metrics because the datapoints have larger intervals.
However with traces this means that spans will be lost during the rollout since the daemonset endpoint is unavailable until a new pod is up and ready to receive traffic.

What is the suggested solution for this problem when running in production?

**Comment by TylerHelmuth** [comment]
The gap in availability you've pointed out is real, but I don't know of any k8s rollout strategy that would solve the issue. 

The last time I timed it, the rollout for a single pod of the collector was about 10-30 seconds.  Not insignificant, but also not terrible. If losing data in that window is a concern you could try to isolate daemonset updates to low traffic times.

**Comment by dmitryax** [comment]
Instrumentation libraries should be configured (I believe by default) to retry on failure, so spans are buffered during the collector downtime and flushed once it's back.

**Comment by dmitryax** [comment]
@dudicoco I'm closing the issue. Feel free to reopen if any other clarification needed

**Comment by dudicoco** [comment]
@dmitryax I don't think retry solves the problem, a few of reasons come to mind but there might be more:
1. During the down time there could be a high number of pods retrying and keeping the traces within the buffer, this can even be 100 pods for one node, and if they have more than one container which sends traces that's 200 containers. Once the down time is over the daemonset pod will need to handle all of these buffered traces and may have to dump some of them due to the memory limiter.
2. The containers keep the buffer in memory, during the down time this buffer might reach the limit and cause spans to drop.
3. During the downtime there might be a rollout of the application deployment (the client) which would cause the spans that were kept within the buffer to be lost.
4. If there is a problem during the daemonset rollout and the new pod doesn't start properly the downtime could be much longer, this could cause a lot of spans to be lost.

These issues make me wonder why is daemonset even a recommended way to deploy the collector in production where high availability and reliability are needed.
A deployment on the other hand should give you 100% availability during a rollout due to the nature of its rolling update, a statefulset would also give you better availability assuming you have a sufficient amount of replicas.

In comparison, prometheus push gateway and graphite (old, I know) are deployed as deployment/statefulset and both serve a similar purpose as the collector - an endpoint to push telemetry data into:
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway/templates
https://github.com/kiwigrid/helm-charts/tree/master/charts/graphite/templates

**Comment by dmitryax** [comment]
> Once the down time is over the daemonset pod will need to handle all of these buffered traces and may have to dump some of them due to the memory limiter.

If you have 200 containers sending traces to one collector, the collector has to be configured accordingly to have higher memory and CPU reservation to handle such spikes

> The containers keep the buffer in memory, during the down time this buffer might reach the limit and cause spans to drop.

There is such possibility. I believe the buffer configuration on the instrumentation libraries can be adjusted if higher guarantees against drops are needed. This will require more memory tho.

> These issues make me wonder why is daemonset even a recommended way to deploy the collector in production where high availability and reliability are needed. A deployment on the other hand should give you 100% availability during a rollout due to the nature of its rolling update, a statefulset would also give you better availability assuming you have a sufficient amount of replicas.

You're right deployment is a better option if you need to make sure high availability for tracing. Do you see some documentation recommending the deamonset for traces collection?

**Comment by dudicoco** [comment]
@dmitryax daemonset is one of the suggested deployment options here: https://opentelemetry.io/docs/concepts/data-collection/#deployment

In the getting started k8s guide daemonset is defined in the k8s manifest: https://opentelemetry.io/docs/collector/getting-started/#kubernetes

Daemonset is the default deployment option in the official helm charts: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector#default-configuration

**Comment by dmitryax** [comment]
`deamonset` is preferred because it can handle all three telemetry types. To achieve high availability for tracing in "gateway" mode, deployment is preferable. Feel free to submit a PR to add a note to the docs for tracing HA use case

**Comment by besha100** [comment]
@dmitryax @dudicoco Don't you think Daemonset would be better for the case of having OTEL collector as agent with using [Kubernetes Attributes Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md) for the reason mention [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#as-an-agent)
