### ISSUE TITLE
AWS ECS Opentelemetry Collector

### ISSUE THREAD

**Issue by denny6389** [open-telemetry/opentelemetry-collector#5413]
**Describe the question**
Is it possible to setup a collector on aws ECS as a sidecar and export trace data to kafka?

I know there is adot collector which is specifically for aws services but adot collector currently does not support kafka exporter. 

Im already using Opentelemetry operator for EKS, and I made a tracing pipeline: collector as a sidecar -> Kafka -> collector as a deployment.

I want a similar pipeline as above for aws ECS.

Thank you in advance.

**Comment by dmitryax** [comment]
@denny6389 Yes it's possible. I believe you can use [instructions from ADOT repo](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md) just replace the image to https://hub.docker.com/r/otel/opentelemetry-collector-contrib

**Comment by denny6389** [comment]
@dmitryax Thank you for your answer! I should definitely try out. Just one more question, does it have to be **opentelemetry-collector-contrib**? cuz I believe regular opentelemetry-collector already has a kafka exporter.

**Comment by dmitryax** [comment]
Yes, looks like `opentelemetry-collector` should work as well
