### ISSUE TITLE
OpenTelemetry Config Marshaler

### ISSUE THREAD

**Issue by jefchien** [open-telemetry/opentelemetry-collector#5418]
**Is your feature request related to a problem? Please describe.**
New projects transitioning to OpenTelemetry need a way to translate their existing configs to the expected OpenTelemetry format. This can be done programmatically by unmarshaling the existing config and mapping it to the OpenTelemetry config struct. Currently, there isn't an easy way to marshal the OpenTelemetry config struct.

**Describe the solution you'd like**
A config marshaler provided by the OpenTelemetry collector core would go a long way in being able to easily and confidently marshal the config struct into YAML, which can then be written out to a file and used moving forward.

**Describe alternatives you've considered**
I've written my own generic mapstructure encoder to use with a marshaler, but as I've learned, it does not support configs with custom unmarshal/marshal.

**Additional context**
This could also be used in an example provided by @bogdandrutu where it might be useful for users to be able to see what config the collector is actually using during run time. The marshaler would be able to provide YAML that can be written out to an endpoint for the user to see.

**Comment by jefchien** [comment]
https://github.com/open-telemetry/opentelemetry-collector/issues/800 is a similar issue.

**Comment by jefchien** [comment]
Please assign this issue to me.

**Comment by dmitryax** [comment]
Closing as completed in https://github.com/open-telemetry/opentelemetry-collector/pull/5566
