### ISSUE TITLE
Rename the service node name in processor

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-collector#543]
For components like istio proxy, the span service name is derived from the namespace and service name. For traces generated within the service, the service name (without namespace) is set. 
When viewing traces, there will be two separate services:
- One for the istio proxy container
- One for the service container

One way to work around this is to update the service container name to be the namespace and service name. However, this isn't always possible. 

This issue tracks extending the span processor (or creating a new processor) to modify the service name given a value.

**Comment by bogdandrutu** [comment]
This is possible in the resource processor. OTLP contains the service name in the resource. See https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor/resourceprocessor

**Comment by CVirus** [comment]
I'm failing to achieve the above using the resourceprocessor.

Here is what the trace output via the logging exporter looks like(I removed a few things for clarity):
```
Resource labels:
     -> service.name: STRING(my_service.payments)
InstrumentationLibrarySpans #0
InstrumentationLibrary
Span #0
    Trace ID       : 74d06153e2ffd2242e75538b3f511dc7
    Parent ID      :
    ID             : 2e75538b3f511dc7
    Name           : my_service.payments.svc.cluster.local:80/*
    Kind           : SPAN_KIND_SERVER
    Start time     : 2021-08-03 16:41:09.153045 +0000 UTC
    End time       : 2021-08-03 16:41:09.153441 +0000 UTC
Attributes:
     -> istio.canonical_revision: STRING(0.149.0)
     -> istio.mesh_id: STRING(cluster.local)
     -> istio.namespace: STRING(payments)
     -> istio.canonical_service: STRING(my_service)
     -> component: STRING(proxy)
     -> upstream_cluster: STRING(inbound|8000||)
     -> user_agent: STRING(kube-probe/1.20+)
```

Is it possible to set Resource label `service.name` to the span Attribute `istio.canonical_service` using the resourceprocessor?
