### ISSUE TITLE
 Collector docker image custom config

### ISSUE THREAD

**Issue by denny6389** [open-telemetry/opentelemetry-collector#5454]
**Describe the question**
Is there any way to make a custom config file for Opentelemetry collector docker image? I just need a specific receiver and exporter but the default one has too many resources. 

Thank you in advance.

**Comment by mhellsten-ml** [comment]
@denny6389, you can mount your config file at /etc/otel-collector.yaml to override the default one.

**Comment by hickeyma** [comment]
Looking at [Dockerfile](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/Dockerfile#L15), you might need to mount it to `/etc/otel/config.yaml`

**Comment by denny6389** [comment]
I will give it a try. Thank you!!

**Comment by HaroonSaid** [comment]
We use AWS ECR build our local images, using a simple bash script, 
```
docker build --build-arg OTEL_VERSION=$OTEL_VERSION -t tools/opentelemetry-collector:$OTEL_VERSION ./linux
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR
docker tag tools/opentelemetry-collector:$OTEL_VERSION $ECR/tools/opentelemetry-collector:$OTEL_VERSION
docker push $ECR/tools/opentelemetry-collector:$OTEL_VERSION
```
The Dockerfile 
```
ARG OTEL_VERSION
FROM otel/opentelemetry-collector:${OTEL_VERSION}
COPY config.yaml /etc/otel-agent-config.yaml
COPY certs/ca.crt /etc/ca.crt
COPY certs/client.pem /etc/client.pem
COPY certs/client.key /etc/client.key
CMD ["--config=/etc/otel-agent-config.yaml"]
```
