### ISSUE TITLE
Support independent queued-retry per Exporter

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#55]
We need to have such capability on configV2.

**Comment by bogdandrutu** [comment]
hmm, why is that not possible via configuring the piepline accordingly?

Receivers -> MultiProcessor -> Queue1 -> Exporter1
                                              -> Queue2 -> Exporter2

**Comment by tigrannajaryan** [comment]
This is already implemented unless I misunderstand something and you refer to some other capability.

All you need to do is list the same receiver in multiple pipelines. 

See implementation https://github.com/open-telemetry/opentelemetry-service/blob/34ca12fa6144be70d4892b8429141ac753e2e78a/cmd/occollector/app/builder/receivers_builder.go#L246-L274

**Comment by flands** [comment]
This is supported -- closing.
