### ISSUE TITLE
Migrate to CircleCI

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#550]
Contrib repo has been using CircleCI and it has been working quite well. For consistency, we should use the same CI everywhere. This ticket tracks migration of this repo from Travis to CircleCI.

We have circleci config already present in this repo but builds were failing due to some differences when we first tried to migrate. We need to look into the reason for failing builds and complete the migration.

**Comment by lizthegrey** [comment]
Would y'all mind if I helped with this?

**Comment by owais** [comment]
Thanks Liz, that'd be great.

**Comment by lizthegrey** [comment]
Yoink.
