### ISSUE TITLE
Exporting metdata of the collected data

### ISSUE THREAD

**Issue by jainaashish** [open-telemetry/opentelemetry-collector#5531]
Hi

Is there a way to export metadata of the collected data from OpenTelemetry collector? Fo example, for collected metric data, I want to know what is the metric name? associated Tags? timestamp of the data? etc...

Is there already an extension which can help get this metadata? if not, is it possible to build such extension with current features? Appreciate any help or pointers in this regard.

**Comment by jpkrohling** [comment]
Not sure I understand the question. If your workload generates metrics with the OpenTelemetry SDK, sending this as OTLP to the collector, you have all of that already (metric name, tags, ...). Could you please expand on your use case?
