### ISSUE TITLE
Make consumererror a separate module, and include exporterhelper.NewThrottleRetry

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-collector#5550]
**Is your feature request related to a problem? Please describe.**

Context: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/433

I'd like to use consumererror outside of the upstream repositories in our library.

Right now consumererror isn't its own module, so it pulls in more dependencies than needed (which might make breaking changes to core harder).

Second, I think it might make more sense for `exporterhelper.NewThrottleRetry` to live in `consumererror` (maybe NewThrottled?), so that users of `consumererror` don't need to depend on exporterhelper as well.

Third, the google cloud APIs all use GRPC clients, similar to the otlp exporter, and would end up duplicating the retry-handling code: https://github.com/open-telemetry/opentelemetry-collector/blob/772a3755f4e8e132e4a4068d2884ecb3ddbaa48f/exporter/otlpexporter/otlp.go#L131.  It would be nice to make that logic usable as a library (possible also in consumererror) so it can be used by other exporters without duplicating it.

**Comment by bogdandrutu** [comment]
The consumererror as is right now is part of a small package `consumer`.

**Comment by dashpole** [comment]
Do you think it is OK us to take an external dependency on `consumer`?

**Comment by bogdandrutu** [comment]
> Do you think it is OK us to take an external dependency on consumer?

We are working on stabilizing this package as we speak, see https://github.com/open-telemetry/opentelemetry-collector/milestone/31. When that is done for sure, before that I would only recommend if you are a "trusted" client and will not annoy if we still break some of the APIs.

**Comment by bogdandrutu** [comment]
Closing this issue for the "separate module part".
