### ISSUE TITLE
Ability to convert metadata dimension to all lowercase

### ISSUE THREAD

**Issue by zsiebers** [open-telemetry/opentelemetry-collector#5552]
## Important (read before submitting)
We are currently preparing for the upcoming 1.0 GA release. Feature requests that are not aligned with
the current roadmap https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/roadmap.md
and are not aimed at stabilizing and preparing the Collector for the release will not be prioritized.

I would like the ability to convert host.name to all lowercase or upper case letters so that when making a REST to put hosts in maintenance we do not have to ensure the case sensitively matches between the two systems.

**Comment by zsiebers** [comment]
This same request was initially requested in #322 but was closed because it was deemed not urgent.

**Comment by atoulme** [comment]
Please try out the transformprocessor to perform this type of transformation. Closing as inactive ; please reopen if you have further questions.

**Comment by stef-philipsen-tfs** [comment]
I checked the documentation of the transform processor. At [supported functions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md#supported-functions) I found the [ConvertCase converter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#convertcase).


I added this to the configuration in snake_case after looking at the transform processor examples. am trying to do this via the transformprocessor:



``` yaml
 transform:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - convert_case(attributes["host"], "lower")
```

But then I get the following error:
`Error: invalid configuration: processors::transform: unable to parse OTTL statement "convert_case(attributes[\"host\"], \"lower\")": undefined function "convert_case"
2024/05/03 10:44:01 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "convert_case(attributes[\"host\"], \"lower\")": undefined function "convert_case"`

**Comment by dcacenabes** [comment]
> I checked the documentation of the transform processor. At [supported functions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md#supported-functions) I found the [ConvertCase converter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#convertcase).
> 
> I added this to the configuration in snake_case after looking at the transform processor examples. This is my configuration:
> 
> ```yaml
>  transform:
>     error_mode: ignore
>     log_statements:
>       - context: resource
>         statements:
>           - convert_case(attributes["host"], "lower")
> ```
> 
> But then I get the following error: `Error: invalid configuration: processors::transform: unable to parse OTTL statement "convert_case(attributes[\"host\"], \"lower\")": undefined function "convert_case" 2024/05/03 10:44:01 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "convert_case(attributes[\"host\"], \"lower\")": undefined function "convert_case"`
> 
> When I set the host name manually with the set function it works, but to me it looks like the convert_case function is not available here. Shouldn't it be available, since it's mentioned on the page with OTLL functions?

Have you tried:
```
statements:
          - set(attributes["host"], ConvertCase(attributes["host"], "upper"))
```
?

**Comment by stef-philipsen-tfs** [comment]
Hi @dcacenabes,

Thanks a lot for your response, it's working now!

This is the config that works for me:

``` yaml
statements:
  - set(attributes["host"], ConvertCase(attributes["host"], "lower"))
```
