### ISSUE TITLE
Doc: add section about using env vars on config file

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#557]
The collector has this capability but it is not documented, see [expandEnvConfig](https://github.com/open-telemetry/opentelemetry-collector/blob/9778b16b81016d6035b2a9f42cda8dc05d8165b8/config/config.go#L871) and related tests.

**Comment by JingboWangGoogle** [comment]
Just for some clarifications, it is straightforward to see that the capability of using env vars in config files is implemented in the file linked above, and the tests demonstrate the actual usage examples, but it seems unclear to me where exactly I should be adding this section of documentation.

**Comment by nilebox** [comment]
Would also be nice to document recommended workarounds for escaping env var substitution, if possible.
See #1077
