### ISSUE TITLE
Builder tool name is inconsistent

### ISSUE THREAD

**Issue by jpeach** [open-telemetry/opentelemetry-collector#5581]
**Describe the bug**
The builder tool is alternately named `ocb`, `builder` or `opentelemetry-collector-builder`, depending on where you look.

**Steps to reproduce**
Download a release binary, e.g. [ocb_0.54.0_darwin_amd64](https://github.com/open-telemetry/opentelemetry-collector/releases/download/v0.54.0/ocb_0.54.0_darwin_amd64)

```
$ ./ocb_0.54.0_darwin_arm64 --help
OpenTelemetry Collector distribution builder (0.54.0)

Usage:
  builder [flags]
  builder [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  version     Version of opentelemetry-collector-builder

Flags:
      --config string            config file (default is $HOME/.otelcol-builder.yaml)
      --description string       A descriptive name for the OpenTelemetry Collector distribution (default "Custom OpenTelemetry Collector distribution")
      --go string                The Go binary to use during the compilation phase. Default: go from the PATH
  -h, --help                     help for builder
      --module string            The Go module for the new distribution (default "go.opentelemetry.io/collector/cmd/builder")
      --name string              The executable name for the OpenTelemetry Collector distribution (default "otelcol-custom")
      --otelcol-version string   Which version of OpenTelemetry Collector to use as base (default "0.54.0")
      --output-path string       Where to write the resulting files (default "/var/folders/hf/8frlwk6s40j0wj3jpgbq94z00000gp/T/otelcol-distribution2878501842")
      --skip-compilation         Whether builder should only generate go code with no compile of the collector (default false)
      --version string           The version for the OpenTelemetry Collector distribution (default "1.0.0")

Use "builder [command] --help" for more information about a command.
```

**What did you expect to see?**
A consistent name for the builder tool.

**What did you see instead?**
The release process names the tool `ocb`, the subcommand name is `builder` and the version help calls it `opentelemetry-collector-builder`. And I guess the config file implies the tool would be `otelcol-builder`.

**What version did you use?**
Version: 0.54.0

**What config did you use?**
Config: N/A

**Environment**
OS: Darwin
Compiler(if manually compiled): N/A

**Comment by jpkrohling** [comment]
`ocb` stands for `opentelemetry-collector-builder`, so, both versions would work. The others were names we used previously in different contexts, so, it would be OK to replace them by either `ocb` or `opentelemetry-collector-builder`.

**Comment by jpeach** [comment]
@jpkrohling WDYT if I standardize all the names to `otel-builder`?

**Comment by jpeach** [comment]
> It has to be `otelcol-builder` then.

Hmm, I was suggesting `otel-builder` to be symmetric with `otel-collector`, which I thought was the standard binary name, but it looks like the default name is `otelcol-custom`, so maybe this is less standardized than I had thought.

**Comment by jpkrohling** [comment]
> I was suggesting otel-builder to be symmetric with otel-collector

Right, but the builder isn't at the same level as "otel-collector", as it's a tool that builds "otelcol" binaries.

**Comment by jpeach** [comment]
OK, I'll knock up a PR to standardize on `ocb` then 👍
