### ISSUE TITLE
Erroneous error message

### ISSUE THREAD

**Issue by annanay25** [open-telemetry/opentelemetry-collector#561]
Running the collector on master branch, with a misconfigured jaeger receiver port gives the following error right now - 

```
Cannot build receivers: cannot create receiver jaeger: either <nil>, thrift_http, thrift_tchannel, <nil>, or <nil> protocol endpoint with non-zero port must be enabled for jaeger receiver
```

This is a problem with the following line - 

https://github.com/open-telemetry/opentelemetry-collector/blob/0a9e87ff4c8653d86540a0c3eddb58b6f7dd23fb/receiver/jaegerreceiver/factory.go#L199-L210

.. because some variables names have been reused causing loss of scope.

**Comment by ashish-kalbhor** [comment]
Are there any steps to reproduce this @annanay25 ?
