### ISSUE TITLE
Allow builder to use Go build tags/use go command flags

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5612]
It would be useful to have an option in the builder to pass Go build tags, so that we can test the functionality currently behind the `enable_unstable` build tag. We could either have an option to pass the build tags or have an option to pass arbitrary flags to the `go` command.

This would also help in open-telemetry/opentelemetry-collector-contrib/issues/11867 if we want to keep the `make otelcontribcol-unstable` command after switching to use the builder.

**Comment by fatsheep9146** [comment]
I want to help with this, can you assign this to me?
