### ISSUE TITLE
Document `$$` mechanism to escape env var expansion

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-collector#5614]
**Is your feature request related to a problem? Please describe.**

In https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11846 the user was trying to use `"$ConnectionString"` as a Username. The collector automatically interprets `$` as an environment variable expansion. The environment variable was empty, so the `Username` field was interpreted as empty and failed validation. In https://github.com/open-telemetry/opentelemetry-collector/blob/0bc2777111d1f9b385d4776742c5cf5acc8fb3c1/config/internal/configsource/manager.go#L364 there is a codepath to escape this behavior using `$$`, but it is undocumented.

**Describe the solution you'd like**

Document the `$$` environment variable escaping.

**Comment by evan-bradley** [comment]
I'll update the docs to include a note about this behavior.
