### ISSUE TITLE
Log a warning when an environment variable without a value is expanded

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-collector#5615]
Related to #5614 

**Is your feature request related to a problem? Please describe.**

In https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11846 the user was trying to use `"$ConnectionString"` as a Username. The collector automatically interprets `$` as an environment variable expansion. The environment variable was empty, so the `Username` field was interpreted as empty and failed validation. There was nothing logged in the collector to alert this user that their configuration was being mangled by the failed environment expansion.

**Describe the solution you'd like**

When an environment variable expansion has no value, log a warning.

**Comment by dyladan** [comment]
Another possible "fix" for this is to log the full collector config at startup. IIRC this is what telegraf does. This would allow the user to see that their config is messed up.

One major issue with this solution is that you would need to reliably hide secrets while also making it possible to see if an expansion failed. We currently don't have any way to distinguish between expansions that are secret and should be obfuscated in logs and expansions that are not.

**Comment by mx-psi** [comment]
I think we should fail fast instead of logging a warning. This is a breaking change, but I think it's worth it in terms of improved troubleshooting and we can have a feature gate to make the transition smoother. We probably also want to prioritize implementing #5228, which will be useful in this case.

For printing the configuration, we have #5223. If you have ideas on how to reliably hide secrets please participate in the discussion there!

**Comment by dyladan** [comment]
I also think a fail-fast strategy is a good one. I didn't suggest it initially because I didn't know how conservative the collector SIG tends to be about those types of breaks. One possible midway solution is to have a strict mode which would toggle behavior between warn and failure

**Comment by mx-psi** [comment]
> failing to start up when an unknown config key is present which may catch typos in some cases

We already do this by default, so it makes all the more sense to be consistent with environment variables :) If I find some time this week I will try to address this

**Comment by mx-psi** [comment]
I am adding this to the confmap milestone, we need to discuss if we want to change the behavior or if we want to make any changes on the Go API to allow for non fatal errors before reaching 1.0.

**Comment by Aneurysm9** [comment]
Not a fan if the idea of failing if environment expansion encounters an unset value.  That may or may not be an error as a user may wish to use that to add context to a value rather than be the only content of a value.  Logging that a replacement failed makes sense and would be a good addition.

**Comment by mx-psi** [comment]
> [failing if environment expansion encounters an unset value] may or may not be an error as a user may wish to use that to add context to a value rather than be the only content of a value.

Would it be possible to support that through support for setting a default value if unset? (Not sure if we should do that, I am just trying to understand your point here)

**Comment by Aneurysm9** [comment]
> > [failing if environment expansion encounters an unset value] may or may not be an error as a user may wish to use that to add context to a value rather than be the only content of a value.
> 
> Would it be possible to support that through support for setting a default value if unset? (Not sure if we should do that, I am just trying to understand your point here)

Maybe, but in that case I'd argue that the default default value should be an empty string which takes us right back to where we are today.

**Comment by atoulme** [comment]
This was discussed in SIG meeting 3/13 as part of the https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9984 issue review.

**Comment by TylerHelmuth** [comment]
@mx-psi is this closed by https://github.com/open-telemetry/opentelemetry-collector/pull/9837

**Comment by mx-psi** [comment]
@TylerHelmuth No, because the logger is noop. We need to pass a functioning logger, which is still a WIP
