### ISSUE TITLE
Revert change to min TLS version

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#5627]
As I understood it, 1.0 is used as the default version on the server-side. This is *not* what we want here, on a newer server/library: the recommendation for a few years has been already to default to 1.2 as the minimum version, allowing users to use 1.0 or SSLvX only when absolutely needed.

_Originally posted by @jpkrohling in https://github.com/open-telemetry/opentelemetry-collector/pull/5480#discussion_r913230956_

**Comment by atoulme** [comment]
I believe this is now fixed with #5956, can we close this issue?
