### ISSUE TITLE
[Question] Can I use otel to trace the usage for each function call

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/opentelemetry-collector#5636]
There is no question template, so I was using the template of feature request to ask a question here, hope it is OK.

Otel can help me for tracing with spans, but here the question is does otel can provide me some info like which function has the highest usage and which does not? Or even with a order to display the usage of each function calls, this can help the clients to allocate more resources to the APIs which has the highest usage. Is this doable? Thanks!

**Comment by jpkrohling** [comment]
OpenTelemetry itself won't provide you with analysis tools, only with the instrumentation SDK/API and middleware (collector, in this repository). You'd typically send this data to a telemetry backend, which would analyse and display this data in a way that makes sense.

**Comment by gyliu513** [comment]
Thanks @jpkrohling , fair enough, do you have any recommended backend that can help?

**Comment by jpkrohling** [comment]
There are quite a few vendors supporting OpenTelemetry, including my employer. It wouldn't be fair to list one here :-)
