### ISSUE TITLE
Otel Collector on cloud foundry ( PCF )

### ISSUE THREAD

**Issue by dharmaplay** [open-telemetry/opentelemetry-collector#5644]
We have requirement to deploy the otel collector as a service in PCF( pivotal cloud foundry ) to collect telemetry of microservices/applications, like how we deploy in Kubernetes as a agent/gateway, can somebody help me how to proceed with deployment of otel collector in pcf as a agent/gateway?

**Comment by dharmaplay** [comment]
any update on this?

**Comment by jpkrohling** [comment]
Apparently, none of the current maintainers had to do this before. Once you figure this out, we'd welcome your contributions to our docs.

**Comment by atoulme** [comment]
Splunk has a PCF distribution: https://github.com/signalfx/splunk-otel-collector/tree/main/deployments/cloudfoundry

**Comment by atoulme** [comment]
Closing as this is not something that is currently supported by the project. If you would like Splunk to upstream some or all of its PCF artifacts, please open an issue on the repository.
