### ISSUE TITLE
Update the changelog procedure to match contrib

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#5647]
The contrib repo has updated its changelog procedure to reduce friction for PRs / users. This issue is an open question whether or not the core repo should follow the same process.

This would ensure users contributing to both repos have a consistent experience and makes the release process consistent as well.

**Comment by mx-psi** [comment]
I think we should have the same process. The only 'odd' thing in my mind is that the tooling code lives in contrib, if we use it here it may make more sense to move it to somewhere like https://github.com/open-telemetry/opentelemetry-go-build-tools

**Comment by codeboten** [comment]
@mx-psi i was thinking the same, i'll get the code moved to the tools repo.

**Comment by bogdandrutu** [comment]
Does it worth the complicated process since we don't have the conflict problem in this repo?

**Comment by codeboten** [comment]
I'm a fan of having consistent tooling across repos to reduce the amount of work needed at release time. This could help with release automation.

That being said you're right that the conflict that chloggen alleviates isn't a problem in this repo. I defer to other maintainers/approvers to go one way or the other here.

**Comment by mx-psi** [comment]
I also think being consistent is important. I don't feel like this complicates much the process of adding a changelog entry, but maybe there is some issue I am not aware of?
