### ISSUE TITLE
Setting an empty metrics address should fail fast

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5655]
I would expect an empty address [`telemetry::metrics::address`] to return a validation error, instead of silently disabling telemetry. Do you think this is worth an issue?

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector/pull/5642#discussion_r916833143_

**Comment by Chinwendu20** [comment]
Hello, please could I work on this?

**Comment by mx-psi** [comment]
Sure, I assigned this to you @Chinwendu20

**Comment by mx-psi** [comment]
Sorry @Chinwendu20 forgot that there is already a PR for this (#5661)
