### ISSUE TITLE
Make long-term-roadmap up to date

### ISSUE THREAD

**Issue by gyliu513** [open-telemetry/opentelemetry-collector#5671]
**Describe the bug**

In https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/roadmap.md#long-term-roadmap , there are some tasks `In Progress`, but no issue linking, it is difficult to find those task info. Can anyone update the doc a bit to reflect where can I get more info of those tasks via some document links? Thanks!

<img width="933" alt="image" src="https://user-images.githubusercontent.com/4461983/178286319-bcef647a-3717-434d-9675-f9002591dde8.png">

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by atoulme** [comment]
This has been addressed to some extent, with a https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md doc that is more focused on going to GA. Closing as addressed.
