### ISSUE TITLE
Add support to handle 402 and 413 http error code in Otlp exporter

### ISSUE THREAD

**Issue by mcmho** [open-telemetry/opentelemetry-collector#5674]
**Is your feature request related to a problem? Please describe.**
Collector currently does retries 402 and 413 error code.   413 is the error code for PAYLOAD TOO LARGE
 and 402 is for PAYMENT REQUIRED which a user case of this would be when license token is exhausted.  
These error code should be treated as permanent error in the Collector so that they won't get retried. 

**Describe the solution you'd like**
Currently Collector only treats 400 as permanent error.  
```
	if resp.StatusCode == http.StatusBadRequest {
		// Report the failure as permanent if the server thinks the request is malformed.
		return consumererror.NewPermanent(formattedErr)
	}
```
The solution is to add 402 and 413 to the permanent error list.  

**Describe alternatives you've considered**
Tweaking the backend to return a different error code; however, that is a hack.   It is not a permanent solution. 

**Additional context**
it does not makes sense to keep retrying, for example 413, since it will just keep failing the second time and so forth.

**Comment by jpkrohling** [comment]
Sounds reasonable to me.

**Comment by mcmho** [comment]
@jpkrohling ,  can I work on it?

**Comment by mcmho** [comment]
Sorry, for couple attempts, I didn't realize I typed my email address wrong.   Now it is fixed.
