### ISSUE TITLE
Add a homebrew tap release for ocb

### ISSUE THREAD

**Issue by jpeach** [open-telemetry/opentelemetry-collector#5680]
**Is your feature request related to a problem? Please describe.**

Make ocb easier to install and update to the latest release.

**Describe the solution you'd like**

Add a Homebrew tap release for ocb. goreleaser supports [releasing to a tap](https://goreleaser.com/customization/homebrew/), so I don't think the per-release overhead would be much work. We would need a `open-telemetry/homebrew-tap` repository to release into, and possibly some access changes to bot accounts.

I'm happy to help get this done, though I expect to need some maintainer support for github configuration changes.

**Comment by jpkrohling** [comment]
I think @tigrannajaryan (and perhaps @codeboten) holds the keys to bots and similar accounts. They would be the right folks to create and set the right credentials. I would probably help if you could point them exactly what they would need to do (ie, create an account here, generate an API key, add the API key as `BLA_KEY` as secret, ...)

**Comment by tigrannajaryan** [comment]
The TC usually manages secrets. However, we don't have any for homebrew and I don't know what ocb is. If someone takes the responsibility to do the work I can help with secret management.

**Comment by TylerHelmuth** [comment]
@tigrannajaryan ocb == [OpenTelemetry Collector Builder](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder).

I like the idea of adding ocb to homebrew.  If the outcome of the [discussion around whether or not Contrib should really be used in production](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/164) is that it should not, the ocb's importance increases.  Being able to install it via homebrew is a nice option.

**Comment by sakshi1215** [comment]
Can we close this issue @TylerHelmuth @jpeach @jpkrohling since the outcome was to add the release to the core homebrew?
