### ISSUE TITLE
Add support to avoid retries for 431 and 414 HTTP error codes in the OTLP exporter

### ISSUE THREAD

**Issue by digikar** [open-telemetry/opentelemetry-collector#5697]
**Is your feature request related to a problem? Please describe.**
Collector currently does retries for HTTP error codes 414 and 431. This is not necessary since 431 is the HTTP error code for 'Request Header Fields Too Large' and 414 is the HTTP error code for 'URI Too Long' 

These error code should be treated as permanent error in the Collector so that they won't get retried.

**Describe the solution you'd like**
Currently Collector only treats 400 as permanent error.

	if resp.StatusCode == http.StatusBadRequest {
		// Report the failure as permanent if the server thinks the request is malformed.
		return consumererror.NewPermanent(formattedErr)
	}

The solution is to add 431 and 414 to the permanent error list.

**Describe alternatives you've considered**
Currently we have an interceptor to handle this.

**Comment by rahuldimri** [comment]
Hi, Can I work on this issue ?

**Comment by digikar** [comment]
Sure, please fix it. Thanks

**Comment by pavankrish123** [comment]
@jpkrohling @rahuldimri please see the PR  https://github.com/open-telemetry/opentelemetry-collector/pull/5685. 
@[mcmho](https://github.com/mcmho) can you please see if you can pick up the 431 as well. I think it is better to have a set defined explicitly and loop through the list. 

```go 
var PermenantErrors = []http.Error{
     http.BadRequest 
     ....
}

```

**Comment by rahuldimri** [comment]
@pavankrish123 Let me have a look !!

**Comment by jpkrohling** [comment]
Sorry for missing that this was a duplicate! I'll close this in favor of the older issue.
