### ISSUE TITLE
Broken link for https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/receiverhelper

### ISSUE THREAD

**Issue by tmorrisonsfx** [open-telemetry/opentelemetry-collector#5703]
**Describe the bug**
The link to the receiver helper content is broken.

**Steps to reproduce**
1. Go to https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security.md#receivers-and-exporters.
2. Click the link for receiver.

**What did you expect to see?**
Content for the receiver helper function

**What did you see instead?**
A 404 error page
<img width="1512" alt="Screen Shot 2022-07-18 at 7 00 57 PM" src="https://user-images.githubusercontent.com/63747508/179631171-d0a32b83-3a36-4620-b7f8-f99030b60772.png">

**Comment by rahuldimri** [comment]
Can I work on this ?

**Comment by jpkrohling** [comment]
Sure, I don't think there's anyone working on that yet.
