### ISSUE TITLE
Add ocb Docker image

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5712]
**Is your feature request related to a problem? Please describe.**

Per open-telemetry/opentelemetry-collector-releases/pull/164, we want to promote usage of the OpenTelemetry Collector Builder so that people build their own distribution with only the components they use.

We currently only provide the binaries on each release ([example](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.55.0)), but we don't have a Docker image for this, which would ease the use of the builder.

**Describe the solution you'd like**

Provider a Docker image for the builder.

**Describe alternatives you've considered**

Do nothing, if we consider this is not going to get usage.

**Comment by sakshi1215** [comment]
@dmitryax @jpkrohling As far as I could understand, we want to create a Dockerfile & release docker images for the collector builder, can I work on this if this is still relevant?

**Comment by jpkrohling** [comment]
Sure, I think it would be worth the exercise. I'm not convinced this would work seamlessly for some Linux distributions (like Fedora), as selinux would prevent containers from writing to the host's file system, but I might be wrong.

**Comment by frzifus** [comment]
@jpkrohling that should work using the `z` or `Z` mount option like here:
https://github.com/open-telemetry/opentelemetry-go-build-tools/issues/222

**Comment by jackgopack4** [comment]
I see that we have docker images for the official releases, but I'm thinking it might still be useful to have docker images for custom builds; it seems like there's no way to build a custom collector using the [releases distributions](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions) Dockerfiles besides the default contrib, k8s, or core configuration

**Comment by jackgopack4** [comment]
Hi there, i'd like to create another repository under the "otel" organization on DockerHub, I believe it could be called "otel/opentelemetry-collector-builder" or "otel/ocb"; who has the ability to create this? thanks.

**Comment by mx-psi** [comment]
@jackgopack4 I'd guess this would be done through an issue in the [community repository](https://github.com/open-telemetry/community) but we should discuss what name we want first.

**Comment by jackgopack4** [comment]
PRs are up:
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671
https://github.com/open-telemetry/opentelemetry-collector/pull/11234
Will appreciate reviews on either or both! I'm still working on a blurb for opentelemetry.io as well under "building a custom collector" but will likely get to it Monday

**Comment by jackgopack4** [comment]
Hi there, until https://github.com/open-telemetry/opentelemetry-collector-releases/pull/671 is merged into releases, I think this issue should still stay open

**Comment by mx-psi** [comment]
Fixed by open-telemetry/opentelemetry-collector-releases/pull/671
