### ISSUE TITLE
Implement Open Telemetry proto receiver and translator

### ISSUE THREAD

**Issue by owais** [open-telemetry/opentelemetry-collector#574]
The goal is to enable SDK developers and the rest of the community to start developing around the OpenTelemetry proto. We'll need to enable an OpenTelemetry proto receiver and a rudimentary OpenTelemetry to OpenCensus translator to make this happen. The translator does not need to be exhaustive because the in-memory OpenCensus representation of spans will soon be replaced with different representation. We'll have to implement a translator from OpenTelemetry (and other receiver formats) to that representation in a few weeks.

- [x] Implement a receiver for OpenTelemetry protocol (https://github.com/open-telemetry/opentelemetry-proto). Can be similar to OpenCensus receiver but use the new OpenTelemetry proto instead. 
- [x] Implement OpenTelemetry to OpenCensus span translation.  Existing translators: https://github.com/open-telemetry/opentelemetry-collector/tree/master/translator/trace

We will need to support both traces and metrics.

Note that this is also needed for Collector's Beta release, deadline Mar 16, 2020.

**Comment by nilebox** [comment]
I will give it a try.

**Comment by tigrannajaryan** [comment]
@nilebox thanks for offering help. Note that there is already code that can translate from OpenCensus to OTLP: https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/trace/oc_to_otlp.go

This can be used by OTLP exporter (warning: that code has tests but was never run in production, so bugs are likely).

**Comment by nilebox** [comment]
Just to recap the work progress on OTLP receiver:
- [x] OTLP trace translator #582
- [ ] OTLP metric translator #594
- [ ] HTTP/JSON gateway https://github.com/open-telemetry/opentelemetry-proto/pull/110
- [ ] OTLP receiver #577 - blocked by changes above

**Comment by tigrannajaryan** [comment]
All done. Closing.
