### ISSUE TITLE
Failure to export from collector to backend (GO Lambda Layer)

### ISSUE THREAD

**Issue by itaybaror** [open-telemetry/opentelemetry-collector#5742]
I have been attempting to instrument lambdas using the docs on the ADOT website. I have successfully instrumented some python lambdas, where they send the data to the collector, and then exports the data to lightstep (my backend). However when i try to instrument in go, i do see the logs in cloudwatch (i configured the collector to send data to lightstep and to logs) but when it tries to export the data to lightstep (and i have tried other backends) i am usually greeted with some sort of grpc or timeout error, and i do not see the data in the backend. 

I have attached pictures with the errors i receive. Keep in mind that with my working python implementation i am using the same collector config file.

Errors:
<img width="1426" alt="Screen Shot 2022-07-25 at 10 04 16 AM" src="https://user-images.githubusercontent.com/107562167/180797738-5e691af1-5139-40bb-a51b-e9b674b2df10.png">

<img width="1313" alt="Screen Shot 2022-07-25 at 10 12 26 AM" src="https://user-images.githubusercontent.com/107562167/180797956-6ff8b557-ac0a-4b16-82f2-28730b6a7652.png">

My collector config file:
<img width="1051" alt="Screen Shot 2022-07-25 at 10 11 41 AM" src="https://user-images.githubusercontent.com/107562167/180797823-88927d34-3129-4bfd-9d06-9c3cbf2bf4e8.png">

**Comment by fatsheep9146** [comment]
I think the error log is pretty clear.
```
dialing dial tcp 35.222.202.121:443: i/o timeout 
```

Can you check the network configuration of your collector? For example login to the collector's container or machine, and run 
```
ping 35.222.202.121
```
or
```
telnet 35.222.202.121 443
```

**Comment by itaybaror** [comment]
That is not always the error, not it is this:
![Screen Shot 2022-07-26 at 2 40 00 PM](https://user-images.githubusercontent.com/107562167/181085913-3f39066f-324a-4cc9-a737-969917de3aa2.png)

**Comment by bogdandrutu** [comment]
@carlosalberto @jmacd @tedsuo can you look into this?

@itaybaror can you confirm that this was not a transient error on the backend?

**Comment by jangaraj** [comment]
For the record: the same issue in another project - https://github.com/aws-observability/aws-otel-lambda/issues/271#issuecomment-1195804948

**Comment by stephenhong** [comment]
Are there any updates to this issue? I'm experiencing something similar where my lambda functions work fine with otel lambda layers (Java, Node.js, Python) but fails to export traces with the Go lambda layer

**Comment by bogdandrutu** [comment]
@MrAlias any idea?

**Comment by MrAlias** [comment]
Hmm, I'm not 100% sure what the issue is here.

The authentication issue seems relevant. I'm guessing either the network connection is being setup without TLS but the server expects this, or the Lightstep authentication token is somehow blocking the connection.

@MadVikingGod  thoughts?

**Comment by itaybaror** [comment]
@bogdandrutu definitely not an issue with the backend, tried with multiple. Also same configuration file works in python lambdas.

**Comment by bogdandrutu** [comment]
@MadVikingGod @codeboten @paivagustavo any idea?

**Comment by codeboten** [comment]
@itaybaror can you reproduce this issue using the collector outside of the lambda layer? This could at least remove some of the moving pieces here.

**Comment by mx-psi** [comment]
Closing as stale since this is 'waiting for author' and we have not heard back since January. Feel free to comment to reopen :)
