### ISSUE TITLE
HTTP Receiver error

### ISSUE THREAD

**Issue by jinfanzon** [open-telemetry/opentelemetry-collector#5753]
**Describe the bug**
An instrumented java app is throwing an error when trying to use otlp receiver:
`otel.javaagent 2022-07-26 17:23:01:376 +0000] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export metrics. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found`

**Steps to reproduce**
I'm trying to run trace analytics like the following chart/pipeline:
Intrumented java app --> otel collector --> data prepper --> opensearch

In order to achieve this:
+qwe.  I have and up & running OpenSearch cluster
2. I run data prepper (**opensearchproject/opensearch-data-prepper:latest**) with the following config:
![image](https://user-images.githubusercontent.com/5643016/181075607-53e2df8e-10a1-4b2d-8cfb-b7143135c30d.png)
and data-prepper seems to be up and running correctly:
`2022-07-26T17:44:08,052 [main] INFO  com.amazon.dataprepper.plugins.sink.opensearch.OpenSearchSink - Initialized OpenSearch sink
[...]
2022-07-26T17:44:13,376 [main] INFO  com.amazon.dataprepper.plugins.source.oteltrace.OTelTraceSource - Started otel_trace_source on port 21890...
[...]
2022-07-26T17:44:13,460 [main] INFO  com.amazon.dataprepper.pipeline.server.DataPrepperServer - Data Prepper server running at :4900
`
3. I run an otel collector with the following config:
![image](https://user-images.githubusercontent.com/5643016/181077721-28df894d-6cb2-4e4c-804d-35b8523e879f.png)
Where the ip is the ip of the data prepper docker container I can use localhost as well. 
Everything seems to be running correctly:
![image](https://user-images.githubusercontent.com/5643016/181079258-871ab6d7-f6ad-4dc8-9cee-365baff0d78a.png)

4. I instrument a simple [java application](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/java/agent-nr-config) with the following env variables
   - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318/v1/traces
   - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://localhost:4318/v1/logs
   - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://localhost:4318/v1/metrics
   - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
   
But I get the following error:
`[otel.javaagent 2022-07-26 18:25:01:284 +0000] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export metrics. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found`

**What did you expect to see?**
Expect to see spans in OTLP

**What did you see instead?**
404 error message

**What version did you use?**
otel/opentelemetry-collector-contrib:latest
opensearchproject/data-prepper:latest

**What config did you use?**
![image](https://user-images.githubusercontent.com/5643016/181077721-28df894d-6cb2-4e4c-804d-35b8523e879f.png)

**Environment**
OS: CENTOS

**Additional context**
There is a similar issue  #4094. But I tried adding /v1/traces without success

**Comment by bogdandrutu** [comment]
> [otel.javaagent 2022-07-26 18:25:01:284 +0000] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export metrics. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found

Per the error, you are trying to export metrics to the collector, but you have configured only a "traces" pipeline. You need to add an extra pipeline to the config:
```yaml
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp]
      exporters: [otlp, logging]
```

Also, the logging exporter is only for debugging purpose, consider to not run with that in production.

**Comment by bogdandrutu** [comment]
Please consider to reopen the issue, if what I suggested does not fix your issue.

**Comment by jinfanzon** [comment]
Hi @bogdandrutu - Can we please re-open the issue? I've changed what you proposed, and even though i do not get the above error, I now get a "failed to export spans" error:

> [otel.javaagent 2022-08-04 20:25:08:566 +0000] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export spans. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found

Looks like I'm close to solve the issue.

Thanks for the support
