### ISSUE TITLE
Support proxy configuration field in all exporters

### ISSUE THREAD

**Issue by cloudnativestack** [open-telemetry/opentelemetry-collector#5761]
**Is your feature request related to a problem? Please describe.**
We have collectors running in hosts within internal network which does not allow outgoing traffic to backends in public internet. A proxy must be used. However, currently OpenTelemetry collector only supports setting a proxy through HTTP[S]_PROXY environment variable, which is extremely unfriendly for collectors running in physical hosts. Only SREs have the privilege to start/stop/restart collectors and it's very hard to inject environment variables to these processes.

**Describe the solution you'd like**
I would like to field of configuration that can be explicitly set such as:

```
     some_exporter:
         proxy: example.com:1234
```

The config can be added to places like https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper

Each exporter should be able have a separate proxy config and should override proxies set by environment variables.

**Describe alternatives you've considered**
No alternative.

**Additional context**
Some exporters already support proxy, such as awsxray exporter.

**Comment by hrittikhere** [comment]
@jpkrohling saw your LI post. Would love to work on this with help of your guidance if it's still available 🙌

**Comment by jpkrohling** [comment]
Absolutely, ping me on Slack, and I can help you further. But basically, I believe it's just a matter of adding a new config option here:

https://github.com/open-telemetry/opentelemetry-collector/blob/cdbe8e7b8460c6149deab60e1eacec0ba7cd5a13/config/confighttp/confighttp.go#L31

And then add the proxy URL to the transport around here:

https://github.com/open-telemetry/opentelemetry-collector/blob/cdbe8e7b8460c6149deab60e1eacec0ba7cd5a13/config/confighttp/confighttp.go#L126

You can probably set the Proxy attribute of the transport to this:

https://pkg.go.dev/net/http#ProxyURL

**Comment by YashV1729** [comment]
Hey @jpkrohling, I’m interested in this issue. If it has been solved by @hrittikhere thats great 😊. I’m also looking for some good first issues, if you have any recommendations.

**Comment by jpkrohling** [comment]
We do have other good first issues in this repository: https://github.com/open-telemetry/opentelemetry-collector/labels/good%20first%20issue

Feel free to choose one.

**Comment by hrittikhere** [comment]
We can close this as fixed @jpkrohling 👀

**Comment by loicdescotte** [comment]
Hi, It seems there is no documentation about this setting usage

**Comment by jpkrohling** [comment]
@loicdescotte, would you mind opening a PR, and perhaps another issue? Basically, one can set `proxy_url` on any exporters using the confighttp's HTTPClientSettings, like OTLP Exporter. It's to be set at the same level as the endpoint property, and follows the semantics of https://pkg.go.dev/net/http#ProxyURL

**Comment by loicdescotte** [comment]
Hi, I can't open a PR as I won't be able to test it, because I am using AWS Distro for OTEL, that is not using the same semantics for the proxy. I can't open an issue though.
