### ISSUE TITLE
Aggregate multiple Jaeger batches and perform a single call to ConsumerTraceData

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#579]
Currently, multiple Jaeger batches can't be aggregated to make a single call to `ConsumerTraceData` because the legacy internal format (OpenCensus proto) needs a unique service on each call to ConsumerTraceData. When the transition to OTLP is done batches can be aggregate a single call to `ConsumerTraceData`.

More context here: https://github.com/open-telemetry/opentelemetry-collector/pull/578/files#r385288754

**Comment by sandyleo26** [comment]
happy to take a shot at it. Could i have some guidance to get started? Thank you.

**Comment by pjanotti** [comment]
Hi @sandyleo26 thanks for stepping up! This one requires the migration of the internal format to OTLP - I would ping you here when that is done, hopefully, you can still help us with that.

**Comment by sandyleo26** [comment]
@pjanotti cool. yes please let me know what needs to be done, the more specific the better as i'm quite new to this project. thank you
