### ISSUE TITLE
Question: copying serviceName to every span as a tag

### ISSUE THREAD

**Issue by jlsalmon** [open-telemetry/opentelemetry-collector#580]
I'm using `otelcol` to ingest both Jaeger and Zipkin spans, and send them to Honeycomb. However, Honeycomb requires `serviceName` to be set on every individual span.

As I understand it, for Jaeger, the `serviceName` lives at the trace level, inside the `process` struct. For Zipkin, the `serviceName` lives at the span level, but nested in the `localEndpoint` struct (i.e. is not a regular tag).

My question is this: is it possible to use an attribute or span processor to pull out the `serviceName` (from either Jaeger or Zipkin spans) and copy it to every span as a tag?

**Comment by pjanotti** [comment]
The service name is already pulled out from Zipkin. It tries first the local endpoint, failing that it resorts to the remote endpoint, if even that fails it puts a placeholder instead. Is the translation from internal collector format to Honeycomb losing that info? What is the exporter that you are using?

**Comment by pjanotti** [comment]
That ^ said @jlsalmon 
> My question is this: is it possible to use an attribute or span processor to pull out the serviceName (from either Jaeger or Zipkin spans) and copy it to every span as a tag?

If further manipulation is necessary you should be able to do it with the span processor, but I think you should not need that.

**Comment by jlsalmon** [comment]
Thanks @pjanotti - you're right, the service name is flowing correctly. There must have been something amiss elsewhere in my setup.

**Comment by jcchavezs** [comment]
> The service name is already pulled out from Zipkin. It tries first the local endpoint, failing that it resorts to the remote endpoint, if even that fails it puts a placeholder instead. Is the translation from internal collector format to Honeycomb losing that info? What is the exporter that you are using?

I might be lacking context but I am not sure this sounds reasonable. Service name in zipkin world represents the service creating the span, using the remote endpoint name is misleading. I am looking for the code holding this rules but could you please clarify this @pjanotti ?
