### ISSUE TITLE
update CI check to require 1.19 build and remove requirement on 1.17 build

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#5804]

**Comment by bogdandrutu** [comment]
For the moment just remove the need of `go1.17`, will require `go1.19` a bit later, is that ok?

**Comment by codeboten** [comment]
what's your thoughts on delaying? Is it because open PRs will fail unless they're rebased?

**Comment by bogdandrutu** [comment]
Yes, I can enforce that, but also set the "enforce merge branch up to date" which allows maintainers to rebase old PRs?

**Comment by bogdandrutu** [comment]
Done. Found a different option that allows maintainers to update PR branches to main. Now we can merge PRs with the new requirement without asking for rebase.
