### ISSUE TITLE
Add support to handle 404, 405 http error code as permanent errors in OTLP exporter

### ISSUE THREAD

**Issue by varunnayal** [open-telemetry/opentelemetry-collector#5827]
**Is your feature request related to a problem? Please describe.**
Invalid resource path(404) and Invalid HTTP method(405) should not be retried from the OTLP exporter.

**Describe the solution you'd like**
To add `StatusNotFound` and `StatusMethodNotAllowed` in permanent error list.

**Comment by rahuldimri** [comment]
@varunnayal can I work on this ?
