### ISSUE TITLE
Docker image /tmp directory permission denied

### ISSUE THREAD

**Issue by liamawhite** [open-telemetry/opentelemetry-collector#587]
The v0.2.3 image scraping as a Prometheus receiver in Kubernetes generates the following error intermittently:

```sh
{"level":"info","ts":1582912261.8224635,"caller":"service/service.go:167","msg":"Everything is ready. Begin running and processing data."}
W0228 18:04:25.860142       1 reflector.go:302] pkg/mod/k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:98: watch of *v1.Endpoints ended with: too old resource version: 93377425 (93379738)
log: exiting because of error: log: cannot create log: open /tmp/otelcol.otel-collector-5bc5b44ccd-qg2nt.unknownuser.log.WARNING.20200228-180425.1: no such file or directory
```

This causes the container to exit (and restart). The issue seems to be that the `/tmp` directory doesn't exist as the following hack appears to fix the issue:

```Dockerfile
FROM alpine:3.9 as certs
RUN apk --update add ca-certificates
RUN mkdir -m 777 /scratchtmp

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=certs /scratchtmp /tmp
COPY otelcol /
ENTRYPOINT ["/otelcol"]
EXPOSE 55678 55679
```

I say appears to fix as it hasn't occurred since I changed this 3+ hours ago, but the absence of evidence isn't evidence of absence. Additionally, I haven't seen that client-go log line since deploying this change so that error may well have been fixed by me building from master and thus not trigger this error. ¯\\_(ツ)_/¯

**Comment by liamawhite** [comment]
Ok, just confirmed that if I build from master without the `/tmp` directory it still occurs.

**Comment by jpkrohling** [comment]
I'm also experiencing this and I would expect logging to *only* occur at stdout/stderr, so, writing to a log file in `/tmp` shouldn't happen at all.

**Comment by pjanotti** [comment]
This seems a k8s issue (the one writing to `/tmp`) @liamawhite a PR to workaround it is welcome.

**Comment by liamawhite** [comment]
@pjanotti just to confirm you want me to PR the Dockerfile hack with comments?

**Comment by pjanotti** [comment]
@liamawhite correct: create the temporary folder and add a comment why it was needed.

**Comment by liamawhite** [comment]
@pjanotti would it be possible to cut a new release, with a new image?

**Comment by pjanotti** [comment]
There should be a new release at most by the beginning of next week. I will ping you when it is ready.
