### ISSUE TITLE
exporter/loggingexporter.Config.LogLevel has different behavior after #5677

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#5878]
After https://github.com/open-telemetry/opentelemetry-collector/pull/5677 was merged, we no longer use `LogLevel` the way was before (where we set it for zap.Core). 

We need to look into what that configuration does right now, if we need to deprecate/rename/re-describe or what we need to do.

**Comment by mx-psi** [comment]
The new behavior or the log level option is described on this comment https://github.com/open-telemetry/opentelemetry-collector/pull/5677#pullrequestreview-1036046290.

We have only ever used `debug` and `info` levels, and I doubt we would use `warn` or `error` here. Some possible renames:
- `verbosity`or `verbosity_level` (either keeping `info` and `debug` or maybe with `brief` and `detailed` values)
- `verbose`, `detailed` or `show_payload_contents` (boolean flag, defaults to `false`)

@bogdandrutu (and also @tigrannajaryan ) Do you prefer any particular option among those?

**Comment by bogdandrutu** [comment]
I think I like the "verbosity" level. The reason is that, it may allow us to add new levels if needed in the future. Also look into https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtelemetry/configtelemetry.go#L26 may use that?

**Comment by mx-psi** [comment]
Take a look at #6334

**Comment by mx-psi** [comment]
Fixed by #6334
