### ISSUE TITLE
No HTTP trace nor service map

### ISSUE THREAD

**Issue by jinfanzon** [open-telemetry/opentelemetry-collector#5880]
**Describe the bug**
I have several java spring microservices and I have done the automatic java instrumentation. After running the services, in opensearch I don't see HTTP traces, nor service map. I only see DB traces.

**Steps to reproduce**

1. I launch data-prepper with OpenSearch as a sink for two pipelines: "raw-pipeline" and "service-map-pipeline":

> 
![image](https://user-images.githubusercontent.com/5643016/183770717-df2028d6-3c0d-42ce-aacc-fbd34f81419f.png)

2. I launch OTEL with data-prepper as the exporter

> 
![image](https://user-images.githubusercontent.com/5643016/183770520-28a9003c-477e-4207-92df-cede7480acef.png)

3. I instrument my microservices with the automatic instrumentation (I use http instead of grpc port):
![image](https://user-images.githubusercontent.com/5643016/183770908-80f076c0-96f3-4dd4-b817-bbcb87d087f8.png)

**What did you expect to see?**
I expect to see the service map in OpenSearch and the HTTP traces

**What did you see instead?**
I don't see the service map, and I don't see the HTTP traces. I only see the DB traces:
![image](https://user-images.githubusercontent.com/5643016/183771151-7565dc61-c364-4e03-b707-097b7420f219.png)

![image](https://user-images.githubusercontent.com/5643016/183771202-baca69a1-392a-4304-940f-4f7b08abfa77.png)

**What version did you use?**
otel/opentelemetry-collector-contrib:latest
opensearchproject/data-prepper:latest

**What config did you use?**
![image](https://user-images.githubusercontent.com/5643016/183770717-df2028d6-3c0d-42ce-aacc-fbd34f81419f.png)
![image](https://user-images.githubusercontent.com/5643016/183770520-28a9003c-477e-4207-92df-cede7480acef.png)
![image](https://user-images.githubusercontent.com/5643016/183770908-80f076c0-96f3-4dd4-b817-bbcb87d087f8.png)

**Environment**
 "Ubuntu 20.04"

**Additional context**
-

**Comment by bogdandrutu** [comment]
@open-telemetry/java-instrumentation-approvers @open-telemetry/java-approvers any idea about why? This looks to me like an instrumentation problem not an collector problem, since at least some of the traces are present.

**Comment by trask** [comment]
@jinfanzon I'd start with making sure you're using a recent javaagent version (1.16 is the latest), and then I'd [enable debugging](https://github.com/open-telemetry/opentelemetry-java-instrumentation#troubleshooting) on the javaagent to check whether any http spans are being captured or not

**Comment by mateuszrzeszutek** [comment]
Also, @jinfanzon what HTTP library/framework are you using? What version of it?

**Comment by jinfanzon** [comment]
@mateuszrzeszutek, we are using springboot. Is it covered by the automatic instrumentation?

**Comment by jinfanzon** [comment]
Hi all! - I've downloaded the latest java agent and turned on debug mode. One of the first log is, where we can see that 185 instrumenters were installed:

`@timestamp:Aug 11, 2022 @ 16:27:08.117 container_name:/ecs-payment-order-dev-104-payment-ordertask-dec7bfe684e5c1de8c01 source:stderr log:[otel.javaagent 2022-08-11 19:27:08:110 +0000] [main] DEBUG io.opentelemetry.javaagent.tooling.instrumentation.InstrumentationLoader - Installed 185 instrumenter(s) container_id:d6f0789862fc2fbd916aca49ce81f03205d675264d9a8eb895ca38446178b388 ec2_instance_id:i-07a0136ec03c6a416 ecs_cluster:dev-kalto-cluster ecs_task_arn:arn:aws:ecs:us-west-1:304270547771:task/dev-kalto-cluster/e6324556cd6c422d8595a348ee6f433b ecs_task_definition:payment-order-dev:104 _id:FC9fjoIBwNQ3RiDG70G5 _type:_doc _index:payment-order-ms _score: -`

After that I only see logs related to Hibernate, but nothing related to HTTP traces:
[Patebin Logs](https://pastebin.com/YXBdDgJv)

Not sure if spring-boot requires manual instrumentation?

**Comment by jinfanzon** [comment]
After going deeper into the logs I've found the following errors:

Aug 11, 2022 @ 17:27:23.222 | [otel.javaagent 2022-08-11 20:27:23:222 +0000] [OkHttp http://analytics.dev.kalto.xyx:4318/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Broken pipe (Write failed)
-- | --
  Aug 11, 2022 @ 17:27:17.924 | [otel.javaagent 2022-08-11 20:27:17:924 +0000] [OkHttp http://analytics.dev.kalto.xyx:4318/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: exhausted all routes
-- | --
Aug 11, 2022 @ 17:26:17.919 | [otel.javaagent 2022-08-11 20:26:17:919 +0000] [OkHttp http://analytics.dev.kalto.xyx:4318/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Broken pipe (Write failed)
-- | --
Aug 11, 2022 @ 17:25:18.316 | [otel.javaagent 2022-08-11 20:25:18:316 +0000] [OkHttp http://analytics.dev.kalto.xyx:4318/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Broken pipe (Write failed)
-- | --
Aug 11, 2022 @ 17:24:22.520 | [otel.javaagent 2022-08-11 20:24:22:520 +0000] [OkHttp http://analytics.dev.kalto.xyx:4318/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180

Is it trying to use GRPC? That is strange, since I've setup 4318 as the port for otlp endpoint, and it is my understanding that is the http port: 
`ENV OTEL_EXPORTER_OTLP_ENDPOINT "http://analytics.dev.kalto.xyx:4318"`

**Comment by mateuszrzeszutek** [comment]
> Is it trying to use GRPC?

It looks like you've only configured the traces exporter to use http/protobuf:

```dockerfile
ENV OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="http/protobuf"
```

Try setting the `OTEL_EXPORTER_OTLP_PROTOCOL` env var instead, it will affect all signals exported by the OTLP exporters -- metrics exporter included.

> Not sure if spring-boot requires manual instrumentation?

It does not, it should be covered by auto-instrumentation. 

> After that I only see logs related to Hibernate, but nothing related to HTTP traces:

Can you post the full javaagent log output? The pastebin you posted only contains 25 lines of log, which is just a small part of what the agent usually prints out in debug mode.

**Comment by jinfanzon** [comment]
@mateuszrzeszutek thanks, that seems to do the magic. HTTP traces were sent correctly though when **metrics** are sent I get the following **404 error** in otel logs:

![image](https://user-images.githubusercontent.com/5643016/184436648-c3000b2e-0821-4a6d-90b1-199df5218fa0.png)

I've added the following entry in data-prepper config:

![image](https://user-images.githubusercontent.com/5643016/184436769-4b682643-5150-4df6-850e-277e23f3659e.png)
![image](https://user-images.githubusercontent.com/5643016/184437004-2351f48b-5783-4221-8f6b-b59e9e74dc8c.png)

I've tried with an exporte **otlp/data-prepper otlp/2 otlp/http**. All with the same error

Might this be an data-prepper issue? did I missconfigured something?

**Comment by jinfanzon** [comment]
hi @mateuszrzeszutek - That works correctly, I'm getting traces and logs, but I still have an error with metrics:

> otel-collector    | 2022-08-16T18:31:45.994Z	error	exporterhelper/queued_retry.go:183	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "otlp/2", "error": "Permanent error: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain; charset=utf-8\"", "dropped_items": 180}
otel-collector    | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
otel-collector    | 	go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry.go:183
otel-collector    | go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
otel-collector    | 	go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/metrics.go:132
otel-collector    | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
otel-collector    | 	go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry_inmemory.go:119
otel-collector    | go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
otel-collector    | 	go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
otel-collector    | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
otel-collector    | 	go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69

I've added the metrics pipeline in data-prepper:
![image](https://user-images.githubusercontent.com/5643016/184953734-76ab16c9-3b3a-4c65-bd27-e9baaa1a5a7f.png)

But no luck in getting metrics from OTEL. Also, I'm not sure if data-prepper is expecting the metrics through grpc

**Comment by mateuszrzeszutek** [comment]
It looks like whatever you're connecting to (data-prepper?) does not accept metrics -- judging from its response, it doesn't implement the metrics endpoint.

**Comment by jinfanzon** [comment]
Hi @mateuszrzeszutek - Thanks for your reply, I've created a [ticket](https://github.com/opensearch-project/data-prepper/issues/1664) with data-prepper team and metrics has to be exported through grpc. I did that, but now I have the following data-prepper error:

![image](https://user-images.githubusercontent.com/5643016/186900740-714eb5b7-1fd8-44b4-8acd-4d4f6d21cd9b.png)

I've already reported that error to their team, but I also wanted to check it here, since maybe some config is required on OTEL side to export metrics to data-prepper.

**Comment by jinfanzon** [comment]
Hi - I was missing config:

processor: - otel_metrics_raw_processor:
