### ISSUE TITLE
[pdata] Need a clean way to convert pcommon.Value into a Map or Slice

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5973]
Currently, `pcommon.Value` can be switched to a different type only between primitive types, e.g. `String` -> `Int` using `Value.SetInt`, but there is no way to convert `Int` into `Slice` for example. It's not a problem when we work with `common.Map`, but it is a problem when we need to convert a `Value` of `LogRecord.Body`. It's still possible to work around with `Value.CopyTo`, but it goes against the recommended pdata workflow when we handle pdata objects without using constructors like NewValuMap.

The suggestion is to introduce new `pcommon.Value` methods: `Value.InitMap() Map` and `Value.InitSlice() Map`. The naming is arguable.

**Comment by bogdandrutu** [comment]
Here is somewhere where we do this kind of "conversion" inside metrics https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pmetric/metrics.go#L136. we need to be consistent with that as well.

**Comment by dmitryax** [comment]
Completed in https://github.com/open-telemetry/opentelemetry-collector/pull/5975

**Comment by dmitryax** [comment]
Completed in https://github.com/open-telemetry/opentelemetry-collector/pull/5975
