### ISSUE TITLE
[pdata] Revisit Map.Insert/Update/Upsert methods

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5974]
`pcommon.Map.Insert/Update/Upsert` are the only methods allowing setting the mutable types on the Map. This practice  is generaly discouraged in pdata module since it potentially can lead to setting the same maps/slices across different parts of pdata.

Setting mutable types should be replaced with other methods, e.g. `Map.UpsertEmpty() Value`.

**Comment by dmitryax** [comment]
@bogdandrutu I realized all the Upsert/Insert/Update methods copy the underlying data under the hood. It means that my concern about sharing the same objects in different parts of pdata is invalid. But it means that the only way to put a map or a slice as a child of another map is to generate a map and copy it, which always implies another extra allocation for the whole map.

```go
childMap := NewValueMap()
... fill childMap ...
parentMap.Upsert("key", childMap) // childMap is copied here
```

If we move to `UpsertEmptyMap`, we don't have any extra allocations

```go
childMap := parentMap.UpsertEmptyMap("key")
... fill childMap ...
```

So even if Upsert/Insert/Update do defensive copying, I think we should still deprecate them.

**Comment by bogdandrutu** [comment]
This is done, since we removed or deprecate (last one is Insert) all the funcs.
