### ISSUE TITLE
otlphttpexporter: add config option for json payload encoding

### ISSUE THREAD

**Issue by Syn3rman** [open-telemetry/opentelemetry-collector#5981]
**Is your feature request related to a problem? Please describe.**
It seems like there is currently no way to json encode and export logs in the otlphttpexporter. It would be nice to have this.

**Describe the solution you'd like**
A config option for the otlphttpexporter which allows users to use json/http with a default of proto

**Describe alternatives you've considered**
The only way to do this was to clone the repo and build after changing `marshalProto()` to `marshalJSON()`

I would be happy to send over a PR for this so please let me know if this is required. Thanks!

**Comment by bogdandrutu** [comment]
We are trying to not support that, and discourage that usage. Where do you need to send JSON?

We do accept JSON since it is common to send from the JS apps.

**Comment by Syn3rman** [comment]
Oh no I just wanted to generate a sample payload to inspect it. I thought that it should've been supported in the output since it is supported in the input but if that is not the case, I don't really mind. Thanks for the response!

**Comment by bogdandrutu** [comment]
@Syn3rman for inspection use `logging` exporter?

**Comment by dseeley** [comment]
> We are trying to not support that, and discourage that usage. Where do you need to send JSON?
> 

Our use case is to send to fluentd, which doesn't have good support for protobuf - can you elaborate on why this usage is discouraged?

**Comment by rpasche** [comment]
Same here for example if you would like to forward some data to "logstash" or something else, that does not - yet? - "speak" protobuf
