### ISSUE TITLE
golangci-lint reports: times.Total is deprecated

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-collector#5988]
**Describe the bug**
The usage of the `cpu.Total` function was deprecated in https://github.com/shirou/gopsutil/pull/1325

**Steps to reproduce**
When running `make lint`, the this error is produced:
```sh
$ make lint
golangci-lint run
service/internal/telemetry/process_telemetry.go:162:9: SA1019: times.Total is deprecated: Total returns the total number of seconds in a CPUTimesStat Please do not use this internal function. (staticcheck)
	return times.Total()
	       ^
make: *** [Makefile.Common:41: lint] Error 1
```

**What version did you use?**
Version: `master`. Commit: `1eda0c4e4f6fbd90966359e12b226db01a845223`.

**Comment by bogdandrutu** [comment]
done
