### ISSUE TITLE
Revisit need of Map.Update<Type> and Map.Insert<Type>

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#5998]
We need to make sure that all the pdata API is needed before declaring 1.0. 

Problem with `Map.Update<Type>` and `Map.Insert<Type>` is that they cannot be applied to all the types. `Map.Upsert...` methods that require returning a value like `Map.UpsertEmpty` and `Map.UpsertEmptyMap` cannot have clean and useful equivalents for `Map.Update...` and `Map.Insert...`. 

Usage of `Update...` in contrib is very limited. There are only few places where it's actually needed. Most of `Insert...` usages in contrib can be replaced with `Upsert...` since there is no data under the key. 

All the use cases when `Update...` and `Insert...` are really needed can be replaced with a combination of `Get` and `Upsert...`. 

Removing `Update...` and `Insert...` helps us to keep the Map API concise and consistent. `Upsert...` methods can be potentially renamed to `Put...`.

**Comment by bogdandrutu** [comment]
`Map.Update<Type>` where marked as deprecated and will be removed next release.

**Comment by bogdandrutu** [comment]
@dmitryax agreed, for the moment does not seem that important to offer "Insert" like functionality. Let's deprecate, and we should finalize the name for "Upsert" since that confused lots of people (everyone was using "Insert" as default)

**Comment by dmitryax** [comment]
@bogdandrutu Submitted https://github.com/open-telemetry/opentelemetry-collector/issues/6059
