### ISSUE TITLE
Revisit current `ptrace.TraceState` API

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#6022]
- [ ] Move to `pcommon`? Reason to do it is because the ids are already part of the `pcommon` and most likely this will become part of logs and metrics exemplars.
- [ ] Right now is a typedef to string. If we intend to have the type doing parsing, we may look into something like what otel-go has defined for this. We can start by just making this a proper struct and do not expose implicit conversions to/from string as we do right now because of the typedef, but have `AsRaw` and `FromRaw`.

**Comment by bogdandrutu** [comment]
Will have to pick one solution between https://github.com/open-telemetry/opentelemetry-collector/pull/6053 and https://github.com/open-telemetry/opentelemetry-collector/pull/6052

**Comment by dmitryax** [comment]
I think https://github.com/open-telemetry/opentelemetry-collector/pull/6052 is a better option providing extensibility that possibly can be utilized

**Comment by bogdandrutu** [comment]
@jpkrohling also vote for the same. So will move forward with that proposal. Will close the alternate PR.
