### ISSUE TITLE
[builder] Remove setting of the Go executable from Validate()

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#6030]
Context: https://github.com/open-telemetry/opentelemetry-collector/pull/6026/files#r963914627

The Validate function currently sets the path to the Go executable, when the function's name does not imply this behavior at all.

**Comment by rahuldimri** [comment]
Can I work on this ?

**Comment by codeboten** [comment]
@rahuldimri all yours!

**Comment by sakshi1215** [comment]
Hey @jpkrohling @codeboten , I am an outreachy applicant & would like to work on this issue if @rahuldimri hasn't made sufficient progress yet.

**Comment by sakshi1215** [comment]
@dmitryax Can you assign me this issue?

**Comment by dmitryax** [comment]
@sakshi1215 assigned
