### ISSUE TITLE
Replace New[Map|Slice]FromRaw with New[Map|Slice]().FromRaw

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6041]
After https://github.com/open-telemetry/opentelemetry-collector/pull/5971 is merged, we need to replace New[Map|Slice]FromRaw to New[Map|Slice] and FromRaw in order to have consistent interface

**Comment by bogdandrutu** [comment]
Only to remove deprecate funcs left.
