### ISSUE TITLE
Find a better name for Map.Upsert

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6059]
In https://github.com/open-telemetry/opentelemetry-collector/issues/5998, we found out that `Map.Insert*` and `Map.Update*` methods are not that useful as we probably initially expected and we decided to go with `Map.Upsert*` that suites all the use cases and can be applied to all the `Value` types consistently. Having `Map.Upsert*` alone doesn't seem like the best name pick, so we should consider other names. I see the following options:
- `Map.Put*` (`Put`,  `PutString`, `PutSlice`, `PutMap` etc). Inspired by Java and REST API.
- `Map.Store*` (`Store`,  `StoreString`, `StoreSlice`, `StoreMap` etc). Inspired by https://pkg.go.dev/sync#Map.Store.
- `Map.Set*` (`Set`,  `SetString`, `SetSlice`, `SetMap` etc).

So we need to pick one.

cc @open-telemetry/collector-approvers

**Comment by bogdandrutu** [comment]
I think to go well with `Get` and `Remove` we can use the Java/REST API conventions and use `Put`.

**Comment by dmitryax** [comment]
`Put` seems like a pretty good option to me as well
