### ISSUE TITLE
Remove configuration for otelcorecol

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#6077]
Verify that the default config file matches the one we use for otelcorecol. If so, remove the config from the repository to rely on the default one.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/6075#discussion_r970886635_

**Comment by jpeach** [comment]
The embedded default config for ocb doesn't have the "replaces" directives because in that case ocb could be running from anywhere. When you generate otelcorecol, you want the "replaces" because you know that you are building in a multi-module repo, and you want to use the local modules.

**Comment by atoulme** [comment]
It looks like work is completed. Can we close the issue?
