### ISSUE TITLE
All logs should be written to stdout/stderr

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#608]
As seen on #587, the collector will attempt to write to local files when it faces some specific problems. In container environments, such as Kubernetes, writing to log files isn't recommended nor expected. The collector should always write to stdout/stderr, as those are retained automatically by the platform, potentially being submitted to an external tool to analyze those log entries.

**Comment by pjanotti** [comment]
@jpkrohling my understanding from #587 is that a k8s lib via Prometheus client is writing to file (see https://github.com/prometheus/prometheus/pull/4931) that said we should check if an updated lib fixes the issue.

**Comment by jpkrohling** [comment]
Or whether the lib can be configured to use a `io.Writer` specified by the us.

**Comment by bogdandrutu** [comment]
@pjanotti you seem to know about this, can you check if things got fix after prom update? Also maybe describe what needs to happen for this to get fixed.

**Comment by pjanotti** [comment]
I will check this @bogdandrutu - if it is ok as suggested by the links we should remove the `/tmp` from the Docker image: there is a risk of someone having taken a dependency on it but we should be aware if other components are also writing to that folder.
