### ISSUE TITLE
[pdata] Revisit primitive slice length mutation API

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6106]
Following the discussion in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/479 is seems like `EnsureCapacity` + `Append` maybe not that intuitive to use when we have `SetAt` interface. Other slices don't have `SetAt`, so it maybe unnecessary to provide the same API for length mutation as they have, and we can introduce different API to update slice length. `SetLen` still seems a pretty good option to me, in that case I would remove `Append` and `EnsureCapacity`.

cc @bogdandrutu @dashpole

**Comment by dmitryax** [comment]
Here is the commit with `SetLen` implementation for the reference https://github.com/open-telemetry/opentelemetry-collector/commit/965858eb3972b9588e82766a428fd61b3a2e0656

**Comment by dashpole** [comment]
I think there is a difference between `EnsureCapacity` + `Append` vs `SetLen` + `SetAt` if we need to not add an item, right?  It seems better to encourage EnsureCapacity + Append so there aren't empty elements in the list?

e.g. 
```golang
EnsureCapacityOrSetLen(len(foo))
for i := 0; i < len(foo); i++ {
   If foo[i].IsBad() {
       continue
   }
   AppendOrSetAt(i)
}
```

**Comment by dmitryax** [comment]
@dashpole this is a good example for append when we fill the slice from another slice. But if we want to filter the pdata slice in place we cannot do it without `SetLen` or another allocation. I'm not sure if that's a very popular use case. Maybe we can have both `SetLen` and `EnsureCapacity/Append`

**Comment by bogdandrutu** [comment]
@dmitryax I think we should do this (from the linked issue):

> Document "slice equivalent" of pdata functions (e.g. append() for Append(), make([]foo, 0, 5) for EnsureCapacity, foo[i] = bar for SetAt)
