### ISSUE TITLE
Failure to build from source with GOOS=windows

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-collector#611]
`github.com/prometheus/client_golang v1.1.0` in `go.mod` should be updated to at least `v1.2.0` to fix https://github.com/prometheus/client_golang/issues/642

```
$ GOOS=windows make otelcol
go: downloading github.com/inconshreveable/mousetrap v1.0.0
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/windows/otelcol -ldflags "-X github.com/open-telemetry/opentelemetry-collector/internal/version.GitHash=ea76156 " ./cmd/otelcol
# github.com/prometheus/client_golang/prometheus
../go/pkg/mod/github.com/prometheus/client_golang@v1.1.0/prometheus/process_collector_windows.go:78:9: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values
make: *** [otelcol] Error 2
```

**Comment by lizthegrey** [comment]
We fail to catch this in CI because `binaries-all-sys` is not run automatically by our CI, only building for native architecture.

**Comment by flands** [comment]
Windows support was unfortunately dropped back in the OC days. Support needs to be added back so thanks for filing this.

**Comment by lizthegrey** [comment]
@flands review appreciated on the PR
