### ISSUE TITLE
Add capability to specify full exporter endpoint

### ISSUE THREAD

**Issue by sliat3pm** [open-telemetry/opentelemetry-collector#6142]
### Description

I'd like to use Google Cloud Trace as an `exporter`. But its endpoint has the following structure:
`https://cloudtrace.googleapis.com/v1/projects/{projectId}/traces`
As you can see `/v1` and `/traces` are separated by `/projects/{projectId}`

At the same time, the current otc way of configuring allows specifying only the base URL (`https://cloudtrace.googleapis.com`). And `/v1/traces` is appended automatically.

### Solution

Allow the end-user to specify the full endpoint URL for exporters. Do not append any extra path implicitly.

**Comment by bogdandrutu** [comment]
I am confused, `https://cloudtrace.googleapis.com/v1/projects/{projectId}/traces` I think this endpoint does not support OTLP, and has it's own resource path definition very established in Google APIs.

Which specific exporter are you trying to use?

**Comment by dashpole** [comment]
Google cloud trace doesn't support OTLP today.  Are you trying to send Google Cloud Trace-formatted spans somewhere else?  Or what are you trying to do?

This probably should also be moved to contrib.

**Comment by sliat3pm** [comment]
I am trying to send traces from opentelementry-collector to Google Cloud Trace. Is it possible?

**Comment by dashpole** [comment]
Yes, please use the `googlecloud` exporter in the contrib distribution. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter#google-cloud-exporter.  There is an example configuration there to get you started.

**Comment by sliat3pm** [comment]
Somehow I missed it. Thanks a lot. I believe we can close the issue.
