### ISSUE TITLE
Support for Events

### ISSUE THREAD

**Issue by unqork-eddie** [open-telemetry/opentelemetry-collector#6144]
**Describe the solution you'd like**

APM tools like [DataDog](https://docs.datadoghq.com/events/) and [New Relic](https://docs.newrelic.com/docs/data-apis/understand-data/new-relic-data-types/#event-data) support a fourth telemetry data type - events. Adding support to ingest/process/export events would be huge.

**Describe alternatives you've considered**

This might be attainable by treating incoming events as a type of special log, then creating custom exports to supported providers. I'm still relatively new to OTEL so if that's not a good idea I'm open to suggestions.

**Comment by jpkrohling** [comment]
This would probably be a better issue for the spec repository: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification .

Take a look at the issues there (open and closed), I'm confident that there is or was a discussion about this already.

**Comment by unqork-eddie** [comment]
Thanks @jpkrohling!
