### ISSUE TITLE
Setting InstrumentationScope when exporting OTLP from another format

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-collector#6145]
This feature/issue is related to the spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/2833 but in the case of the collector this applies to all Signals.

When spans, metrics and logs come into the collector from sources that don't have InstrumentationScope how are the export protos constructed to export over OTLP? A blank or empty Scope?

**Comment by bogdandrutu** [comment]
This is what we do right now. Do you have a proposal on what to do?

**Comment by tsloughter** [comment]
I don't. @tigrannajaryan asked me to open this on the collector when I asked about what we do for logs in the SDK.

But which do you do in the collector, empty name/version or no scope? The former I guess would group together while the latter wouldn't necessarily mean they are grouped together.

**Comment by bogdandrutu** [comment]
> But which do you do in the collector, empty name/version or no scope? 

In the collector we do not distinguish between empty name/version and no scope. Based on the proto definition https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L66 they are equivalent.

**Comment by tsloughter** [comment]
Ok, maybe this isn't an issue in the collector (or the log spec as I take it it should also just be unset, but should still be mentioned in the spec). I'll wait to hear from Tigran if this can be closed and will open a PR for the log spec tomorrow to propose an addition to the log spec making it clear an empty scope should be used for those logs with no scope.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I don't remember if we discussed this in the past. I was wondering if we want to have some explicit guidance about this in the Collector? Do we think that empty/no scope is the right approach for all Collector receivers except otlp?

**Comment by bogdandrutu** [comment]
>Do we think that empty/no scope is the right approach for all Collector receivers except otlp?

I think we should have something, maybe similar to what metrics decides to do for the MetricProducer case as well. @dashpole any insight here?

**Comment by dashpole** [comment]
IMO receivers should set scope if they define the telemetry (e.g. hostmetrics receiver).  If they don't, they can try and find a similar notion of scope for the telemetry they receive and use that. Otherwise, they should leave scope empty.

If scope just means "something that touched telemetry" as part of an ingestion pipeline, I don't think it is as meaningful or useful
