### ISSUE TITLE
Do we need MoveAndAppendTo or can we replaces with simpler MoveTo for consistency?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#6155]

**Comment by dmitryax** [comment]
`MoveTo` always replaces the destination, but `MoveAndAppendTo` appends new elements. I think we should have distinctive names for those purposes, maybe not to verbose?

**Comment by bogdandrutu** [comment]
But do we need the one with the Append functionality at this point?

**Comment by dmitryax** [comment]
You mean `AppendEmpty`? It cannot be replaces with a one-liner. User would have to iterate over the source slice with `At(i).CopyTo(dest.AppendEmpty())`

**Comment by bogdandrutu** [comment]
Look at these PRs:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14546
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14547
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14548
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14549
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14550
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14551
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14552

What I am saying is that I believe we need a "MoveTo" version, and the `MoveAndAppendTo` showed be replaced if possible with multiple `AppendEmpty`. There are couple more usages of `MoveAndAppendTo`, will look into that soon.

**Comment by dmitryax** [comment]
Sound good. I believe, if we confirm that `MoveAndAppendTo` is redundant in contrib, we can remove it

**Comment by bogdandrutu** [comment]
Few more PRs:

* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14621
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14622

**Comment by bogdandrutu** [comment]
Few more usages removed:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14628
* https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14628

**Comment by bogdandrutu** [comment]
My investigation led to the conclusion that there are few cases where the "MoveAndAppend" is useful, see the usages:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/45142e9320d940deba9e5889a9daa437200437a2/processor/metricstransformprocessor/operation_aggregate_labels.go#L254
* https://github.com/open-telemetry/opentelemetry-collector/blob/f0d69d68220d8bcc2f38070e72516bd1b18cd586/processor/batchprocessor/batch_processor.go#L242

Because of that, I believe we may want to keep it. The only thing that is left then, is to investigate:
1. Do we also need a simple `MoveTo` version? I believe this can be done also by adding a `Clear` func, and combine that with the current `MoveAndAppendTo`.
2. Is the `MoveAndAppendTo` a good enough name? I believe it is decent, unless anyone has a better suggestion I would not change it.

@open-telemetry/collector-approvers

**Comment by dmitryax** [comment]
I agree that name `MoveAndAppendTo` is good enough. 

Currently we have only `CopyTo` and `MoveAndAppendTo` for slices. Maybe it make sense to have `MoveTo`, `CopyTo`, `MoveAndAppendTo ` and `CopyAndAppendTo ` for consistency? It'll be move clear that the first two override the destination. Or they can be removed in favor of `Clear`.

Also `pcommon.Map` currently has `CopyTo` only. I've seen a few places where merge capability would be pretty useful in contrib. So maybe we can add `MoveTo`, `MoveAndPutTo`, `CopyAndPutTo` there?

**Comment by bogdandrutu** [comment]
Is anything right now that blocks us to evolve in the future? Adding new funcs can always happen later, the problem is with removing, so do we want to remove any of them?

**Comment by dmitryax** [comment]
Right. I don't see any method that should be removed at this point.

**Comment by bogdandrutu** [comment]
Then we can move this after the release

**Comment by dmitryax** [comment]
> Then we can move this after the release?

Sure, no rush needed with that. No breaking changes acpected

**Comment by bogdandrutu** [comment]
I think this issue is now complete. If needed in the future to extend the functionality we can reopen.
