### ISSUE TITLE
Should [pmetric|ptraces|plogs]otlp.[Client|Server] be renamed to GrpcClient|GrpcServer?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#6156]
Initially I think we had "grpc" inside the name of the package, but we found that Request/Response are generic for HTTP as well, so renamed that with `otlp` prefix. Because of this, to not confuse that Client is http or grpc (same for Server) should we add `Grpc` in the name?

**Comment by jpkrohling** [comment]
It does make sense to me to have Grpc in the name.

**Comment by dmitryax** [comment]
Good catch. I agree
