### ISSUE TITLE
Feedback on `pdata` for OTLP+Arrow as described in OTEP 171

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector#6166]
This issue relates to the project described in https://github.com/open-telemetry/oteps/pull/171.

## Primary feedback

(Probably a lot of this is known and/or you've heard before! Apologies if this is repetitive.)

1. The new code is definitely more readable
2. The new code is forced to copy and allocate more often than I would like
3. Semantics of `pcommon.Map` make it difficult to de-duplicate
4. Pdata is infectious, eliminates the possibility of "going back"; I want to use the same library for an OTel-Go Traces exporter, but this will be challenging.

### Readability

The [draft PR](https://github.com/lquerel/otel-arrow-adapter/pull/3) is large because it begins with a `sed` script rewriting the import paths to keep `go mod` happy. 😃 

Although I am primarily interested in Traces for this initiative, the [OTLP Logs proto is the simplest to examine](https://github.com/lquerel/otel-arrow-adapter/pull/3/files#diff-31b5fdb24ae12676299390c5b174e70b313eacb15c2dcd10ef5ed594ee534da1). 

### Allocations and copies

Basically this is a request for an "unsafe" mechanism unlike today's `pdata`. When a receiver can promise not to modify its byte arrays, ideally it could directly reference those bytes.

a. For a column-to-row transformation, all data points in a table share the same attributes (i.e,. `pcommon.Map`) but we can't re-use these objects. You can copy or move them, but not use references.
~b. Same for `pcommon.TraceID` and `pcommon.SpanID` byte arrays.~ **EDIT: was incorrect, see below**

### Difficulty in making `pcommon.Map` keys unique

It is not possible to de-duplicate the entries of a `pcommon.Map` without allocating a new `pcommon.Map`. An in-place de-duplicate would be helpful, at the cost of calling `Sort()` w/o memory allocations (as is done in OTel-Go's `attribute` package). 

Note also some inconsistencies: if I use `Map.Get()` to look up a key value, I get the first value in the list. If I use `Map.ToRaw()`, I get the last value in the list. The correct response (IMO) is the last value in the list, which is what OTel-Go does--`Map.Get()` should probably use reverse-iteration.

### It's infectious

If an OTel-Go SDK exporter were to (try to) use this library to convert the standard (row-oriented) OTLP objects it has in-hand prior to export and use OTLP+Arrow, the SDK would have to adopt the `pdata` mechanism itself for its non-OTLP+Arrow spans/logs/metrics exporters; otherwise, we cannot exchange protocol buffer objects that were not compiled by the OTel Collector with this library.

**Comment by jmacd** [comment]
This was discussed in the 9/28 Collector SIG. The Collector and `pdata` maintainers were receptive of this feedback. 

For the questions about "infectiousness", the position is "we will see". As pdata APIs mature we expect better coordination between the OTel-Go SDK and the OTel Collector. Eventually we should have one compiled copy of the protocol and we should have an easier time integrating libraries that work with raw protos. Also note pdata could move to avoid protobuf libraries and generate messages "by hand", which would change how we think about sharing compiled protos.

For the question about forced copies, `pdata` is still evolving and there is a known desire to support zero-copy telemetry ingest. This could be done through some kind of "unsafe" package.

For the question about key de-duplication in a `pcommon.Map`, I will open a new issue.

**Comment by jmacd** [comment]
Follow-on issue: https://github.com/open-telemetry/opentelemetry-collector/issues/6169

**Comment by bogdandrutu** [comment]
Unfortunately I had an emergency and could not join the call.

>  Eventually we should have one compiled copy of the protocol and we should have an easier time integrating libraries that work with raw protos. Also note pdata could move to avoid protobuf libraries and generate messages "by hand", which would change how we think about sharing compiled protos. 

We already do this, so there is no way for us to go easy to from compiled protos. This is a decision we made long time ago by having this package (e.g. we have hand written messages for trace/span id, soon will have for the `AnyValue`). So the answer to this is, no we will not have a easy way to work with compiled protos, but we have a very easy way to work with "serialized bytes" protos.

> a. For a column-to-row transformation, all data points in a table share the same attributes (i.e,. pcommon.Map) but we can't re-use these objects. You can copy or move them, but not use references.

We were thinking to implement copy on write, and the model/api still allows us to do so.

> b. Same for pcommon.TraceID and pcommon.SpanID byte arrays.

Copying a 8/16 bytes object is one of the fastest store operation, copying an int64(8bytes) or a interface{} (16bytes) has the same overhead, so I will not worry about this, unless I am missing something.

> Difficulty in making pcommon.Map keys unique
> Note also some inconsistencies: if I use Map.Get() to look up a key value, I get the first value in the list. If I use Map.ToRaw(), I get the last value in the list. The correct response (IMO) is the last value in the list, which is what OTel-Go does--Map.Get() should probably use reverse-iteration.

How did you manage to construct a map that does not have unique keys? The operations that we expose on the `pcommon.Map` will not allow you to get to that, only if you receive from the wire, where we made the deliberate decision to not check for duplicates, maybe we can add a property on the Marshaler/Unmarshaler to check for that if you need this guarantee.

Overall the feedback is great, and thanks for writing it.

**Comment by jmacd** [comment]
> Copying a 8/16 bytes object is one of the fastest store operation, copying an int64(8bytes) or a interface{} (16bytes) has the same overhead, so I will not worry about this, unless I am missing something.

It's not the copy, it's the allocation. If I've got `[]byte` with len()=16 I'm going to have to allocate a new `[16]byte`. If I could imagine an unsafe interface here, the `pcommon.TraceID` would store `[]byte` and return the copy, then it's the reader's decision to allocate instead of the writer's.

> How did you manage to construct a map that does not have unique keys? The operations that we expose on the pcommon.Map will not allow you to get to that, only if you receive from the wire, where we made the deliberate decision to not check for duplicates, maybe we can add a property on the Marshaler/Unmarshaler to check for that if you need this guarantee.

I agree with the decision, actually. I'm afraid of inconsistency in the conversion to-and-from Arrow that might result, it's more of a concern than a hard problem at this point. So much like there's a `Sort()` method for reasons, a `SortAndDeduplicate()` could be useful for reasons. The fact that `Get()` and `ToRaw()` give different results feels like a danger anyway.

**Comment by bogdandrutu** [comment]
> It's not the copy, it's the allocation. If I've got []byte with len()=16 I'm going to have to allocate a new [16]byte. If I could imagine an unsafe interface here, the pcommon.TraceID would store []byte and return the copy, then it's the reader's decision to allocate instead of the writer's.

99.99% I believe that the [16]byte is actually stack allocated (and not heap allocated). You pass this to "SetTraceID" where we copy in an already allocated spot in the parent object (without allocation), hence it will not escape the scope of the function that calls `SetTraceID` and will be on the stack.

See also https://medium.com/@yulang.chu/go-stack-or-heap-2-slices-which-keep-in-stack-have-limitation-of-size-b3f3adfd6190

**Comment by jmacd** [comment]
I get it, now. Because your protobuf object includes a [16]byte there is no allocation. The copy is not a concern. Thanks.
