### ISSUE TITLE
Make pdata access to Map values consistent; support de-duplication in place

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector#6169]
**Is your feature request related to a problem? Please describe.**

Noticed while investigating that `pcommon.Map` has an inconsitent approach to duplicate attribute values. The `Get()` method will return a different result than the `ToRaw()`. In both cases, I am forced to copy the Map in order to remove duplicate keys. It would be nice to have a stable-sort followed by a consistent selection.

I believe the OTel specification says to choose the last value (i.e., assume overwrite): https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute-collections

**Describe the solution you'd like**
Two things:
1. The `Get()` method should use reverse iteration
2. Suggest a new method that sorts and deduplicates in place, which ensures that `Range()` will see only a single value.

**Describe alternatives you've considered**
If we do nothing, users have to copy the Map to deduplicate.

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/issues/6166#issuecomment-1261220280

How did you manage to construct a map that does not have unique keys? The operations that we expose on the `pcommon.Map` will not allow you to get to that, only if you receive from the wire, where we made the deliberate decision to not check for duplicates, maybe we can add a property on the Marshaler/Unmarshaler to check for that if you need this guarantee.

**Comment by jmacd** [comment]
I am willing to ensure that OTLP+Arrow properly propagates `pcommon.Map` a.k.a. `[]*KeyValue` that contain duplicates if necessary. In that case, I still require the call to `StableSort` but I would leave in duplicates. I am preparing for the worst case-- I just want to be sure that data round-trips and de-duplicating feels simpler than handling duplicates.
