### ISSUE TITLE
Move Jaeger thrift exporter to Contrib

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-collector#618]
The purpose of the exporter is to send the trace data to Jaeger's backend. Not sure we need two different protocols to support this requirement?

What is the benefit of offering end users the ability to choose between the protocols - wouldn't it be easier to provide the simplest possible configuration (i.e. just provide the gRPC protocol)?

If the decision is to provide users with the choice, then the configuration of the protocol should be part of a single Jaeger exporter, rather than defining the protocols as separate exporters. The current approach is inconsistent with all other exporters.

cc @yurishkuro @pavolloffay @jpkrohling @joe-elliott @annanay25

**Comment by jpkrohling** [comment]
gRPC is now well-established in the Jaeger Collector and contains even more features. To avoid confusion, I would vote to keep only gRPC in the OpenTelemetry Collector.

**Comment by pavolloffay** [comment]
If there are no benefits/differences between using one or another we should decrease the maintenance overhead and support only one.

**Comment by annanay25** [comment]
+1 to removing thrift exporter.

**Comment by objectiser** [comment]
@pjanotti @tigrannajaryan As original contributors of the thrift exporter, would you have any objections to it being removed in favour of just supporting the gRPC exporter?

**Comment by flands** [comment]
Removing from core makes sense, but not entirely as other may still be using it. I would propose it move to contrib instead. We still have Zipkin scribe in contrib for exactly this reason.

**Comment by pjanotti** [comment]
@objectiser No objections, the practice should be as @flands described: we move components to contrib (and then delete) as appropriate.

**Comment by objectiser** [comment]
@pjanotti Ok no problem - although given that collector hasn't reached 1.x yet, thought now would be a good time to clean out? Is there a deprecation policy associated with components in the contrib?

**Comment by yurishkuro** [comment]
FWIW the next version of jaeger backend (1.18) removes support for tchannel altogether.

**Comment by jpkrohling** [comment]
To be clear: I think the only valid case for having TChannel/Thrift and not gRPC is when someone has implemented their own Jaeger-like backend without gRPC support.

**Comment by pjanotti** [comment]
@objectiser no written policy yet. That said we should make a distinction between exporters and receivers: exporters can be deleted (added to contrib if there is demand), receivers typically should go to contrib (there are apps that some times generate a specific format).

@yurishkuro "collector" tchannel exporter support was removed a few months ago, there is still agent tchannel support (there is an open issue to remove it https://github.com/open-telemetry/opentelemetry-collector/issues/267https://github.com/open-telemetry/opentelemetry-collector/issues/267)

**Comment by objectiser** [comment]
@pjanotti Thanks for the clarification - I was specifically referring to exporters. I would propose to delete the jaeger-thrift exporter, and if anyone raises an issue with justification why gRPC is not sufficient, then we add to contrib?

**Comment by pjanotti** [comment]
@objectiser sgtm

**Comment by tigrannajaryan** [comment]
Based on today's discussion in SIG meeting I suggest the following action plan:
1. Announce in gitter that Jaeger thrift will be moved from Core to Contrib.
2. Wait a few days and see if there are any objections that need to be taken into account.
3. Copy the code to Contrib (can we preserve the history somehow?)
4. Delete from Core.

**Comment by tigrannajaryan** [comment]
@yurishkuro are you OK with this?

**Comment by yurishkuro** [comment]
Ack
