### ISSUE TITLE
Name of the ptrace.StatusCode should be ptrace.SpanStatusCode?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#6200]
Don't remember if we discussed this, but if we did and agreed on that name document the rational in an issue or code comment.

**Comment by dmitryax** [comment]
This makes sense to me given that we have `SpanKind`. Looks like all other enums have parent object in their names:

```
pmetric.MetricType
pmetric.MetricAggregationTemporality
pmetric.NumberDataPointValueType
pmetric.ExemplarValueType
ptrace.SpanKind
```

except for

```
ptrace.StatusCode
plog.SeverityNumber
```

I think we should replace `ptrace.StatusCode` with `ptrace.SpanStatusCode`. 

Not sure if we should `plog.SeverityNumber` to `plog.LogRecorsSeverityNumber` or keep it as an exception. I think we can keep it as an exception with a reasoning that `SeverityNumber` name is clear enough to understand what it can be applied on, also `plog.LogRecordSeverityNumberError` would be probably too long name.

WDYT?

**Comment by dmitryax** [comment]
@bogdandrutu I believe the CodeStatus comes from the spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status. I don't believe we necessary should follow that, right?

**Comment by bogdandrutu** [comment]
We can keep it StatusCode if we want but then we should rename SpanStatus to Status and we get consistency there.

**Comment by dmitryax** [comment]
We can agree to drop the owner prefix, if it's defined at the top-level of a protobuf package. In that case we can keep:

```
ptrace.StatusCode
plog.SeverityNumber
```

but will have to rename 

```
ptrace.SpanStatus -> ptrace.Status
pmetric.MetricAggregationTemporality -> pmetric.AggregationTemporality
```

I like this approach maybe a bit more more. `pmetric.AggregationTemporality` seems more concise, but I'm not sure about `ptrace.Status`. No strong opinion.

**Comment by bogdandrutu** [comment]
Here is what I propose as rules for Enum names (@dmitryax you should document all of these somewhere in a readme file in the pdatagen):
* The `Type` enums which we create based on the oneof will follow the rules we agreed on in https://github.com/open-telemetry/opentelemetry-collector/issues/6081#issuecomment-1251287404, 
* The other enums/messages which are defined by the proto repository, we should try to follow the names defined in the proto as much as possible:
    * A top level message/enum has the same name as defined in the proto.
    * A nested message/enum has the parent name as prefix, see `SpanEvent` where `Event` is a nested message. The exception is if the nested message/enum already has the prefix, see `StatusCode` which MUST NOT be `StatusStatusCode`.
    * We can have exceptions, but if we do we need to document them.

Based on this:

* `pmetric.MetricAggregationTemporality -> pmetric.AggregationTemporality` see https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L246
* `ptrace.SpanStatus -> ptrace.Status` see https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L260
* `plog.SeverityNumber` see https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L78

**Comment by bogdandrutu** [comment]
> pmetric.MetricDataPointFlags -> pmetric.DataPointFlags

+1

> pmetric.ValueAtQuantile -> pmetric.SummaryDataPointValueAtQuantile

+1, Also we should do `Buckets` to `ExponentialHistogramDataPointBuckets`

> ptrace.Traces vs TracesData in proto and the same for other types

I think we drop the "Data" long time ago, but happy to consider that.

> Many of structs from pcommon don't match https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto like pcommon.Value, pcommon.Map and pcommon.Slice.

Agree with the exception. One thing that I had in mind in past 1m to maybe have a `pattr` or `pkv` package, think if you like that, but is a separate effort.

**Comment by dmitryax** [comment]
> I think we drop the "Data" long time ago, but happy to consider that.

Here is the discussion https://github.com/open-telemetry/opentelemetry-collector/issues/822 led to the renaming. If we rename it back, we would need to change consumer interfaces to have `ConsumeTracesData` etc. I maybe still prefer `TracesData` slightly more, but I'm good with keeping `Traces` as well.

**Comment by dmitryax** [comment]
@bogdandrutu I added the documentaion, PTAL https://github.com/open-telemetry/opentelemetry-collector/pull/6255

**Comment by dmitryax** [comment]
Closing this issue in favor of https://github.com/open-telemetry/opentelemetry-collector/issues/6257
