### ISSUE TITLE
Building a pipeline with no exporters panics

### ISSUE THREAD

**Issue by gr0l0rg** [open-telemetry/opentelemetry-collector#6204]
**Describe the bug**
Looks like the function `fanoutconsumer.NewMetrics()` which is called by ` buildFanOutExportersMetricsConsumer` does not account for the case when there are the slice of exporters in the pipeline is empty and causes panic with error `panic: runtime error: index out of range [-1]`. It seems that `fanoutconsumer.NewLogs()` and `fanoutconsumer.NewTraces()` behave similarily.

**Steps to reproduce**
Create a collector config programmatically via `service.Config` with no `Exporters` in the `config.Pipeline` struct.

**What did you expect to see?**
the collector runs successfully while having no exporters.

**What did you see instead?**
panic

```
panic: runtime error: index out of range [-1]

goroutine 113 [running]:
go.opentelemetry.io/collector/service/internal/fanoutconsumer.NewMetrics({0x44794f8, 0x0, 0x0?})
        ~/go/pkg/mod/go.opentelemetry.io/collector@v0.60.0/service/internal/fanoutconsumer/metrics.go:49 +0x525
go.opentelemetry.io/collector/service/internal/pipelines.buildFanOutExportersMetricsConsumer({0x44794f8, 0x0, 0x28c4d3f?})
        ~/go/pkg/mod/go.opentelemetry.io/collector@v0.60.0/service/internal/pipelines/pipelines.go:397 +0x6f
go.opentelemetry.io/collector/service/internal/pipelines.Build({0x2e03328, 0xc00012a000}, {{0xc000189f10, {0x2de78a0, 0xc00095e600}, {0x2dea720, 0x44794f8}, 0x0}, {{0x0, 0x0}, ...}, ...})
```

**What version did you use?**
v0.60.0

**Comment by mx-psi** [comment]
I don't understand what you mean with

>  the collector runs successfully while having no exporters.

We could return an error instead of panicking, but otherwise, what would you expect the Collector to do?

**Comment by bogdandrutu** [comment]
@mx-psi the problem is the they passed an invalid "Config" to the Service instance. If they would have called "Validate" that will return their error. A bad usage of or APIs is not a bug.
