### ISSUE TITLE
A CI/CD Observability Solution Suggestion

### ISSUE THREAD

**Issue by serkan-ozal** [open-telemetry/opentelemetry-collector#6245]
Hi **open-telemetry** community,

This is Serkan, Co-Founder & CTO at [Thundra](https://www.thundra.io/), the company behind [Foresight](https://www.runforesight.com).

Thundra is open-telemetry compatible tracing and debugging solution and so we are big fan of open-telemetry. 

I am here with the suggestion of [Juraci](https://github.com/jpkrohling) for our CI/CD observability tool, [Foresight](https://www.runforesight.com). 

Foresight brings visibility into CI workflows and test runs, enabling developers to debug CI, build, and test failures and latencies quickly. Furthermore, Foresight’s change impact analysis helps you analyze the impact of the code changes to detect defects early in the release cycle.

With Foresight, you can set rules that will help you to set up robust and customizable policies for your workflows and tests. Receive notifications for fluctuations in key performance metrics as your workflow runs.

Foresight is 100% FREE for open-source projects and I think Foresight can be useful for a repository contributed by many developers, such as `opentelemetry-collector`.

Some of the prominent features of Foresight are:
- Monitor and optimize your Github Actions Workflows (CI/CD pipelines)
![Monitor Github Actions Workflows](https://www.thundra.io/hubfs/Untitled%20-Foresight-Hero(2)2.gif)

- Identify and debug failing, slow and unreliable tests
![Debug Failing Tests](https://www.thundra.io/hubfs/ghvsfrs2.gif)
![Identify Unreliable Tests](https://www.thundra.io/hubfs/Testing%20Insights%20and%20Analytics.png)

- Automatically assess the level of risk of software changes
![Change Impact Analysis](https://www.thundra.io/hubfs/633414075626026c3d36da6a_Change%20risk%20assessment-p-800.png)

Best regards,
Serkan

**Comment by serkan-ozal** [comment]
Hi @codeboten, I think Foresight is still useful for the contrib repos as well.

Because Foresight supports **"tokenless authentication"** for open-source projects. 

So when contributors open PRs to this repository from their forks and workflow run is triggered, collected workflow, test and telemetry data (metrics, logs, etc ...) will be associated to the Foresight account of this repository. 

This means that, all the workflow runs from this main repo and its all forks will be able to monitored in a single Foresight account without need to share any credentials.

**Comment by dmitryax** [comment]
I'd like to try this out. Seems like must be really helpful for the collector repos.

**Comment by mx-psi** [comment]
+1 from my side to trying this out, having this kind of visibility would help us deal with flaky tests and improve the contributing experience

**Comment by serkan-ozal** [comment]
In addition to **"tokenless authentication"** (https://github.com/open-telemetry/opentelemetry-collector/issues/6245#issuecomment-1270605739) to associate all workflow runs and test runs by PRs from community forked repos, there is another important feature for open-source projects I forgot to mention.

Foresight also supports custom sub-domain for open-source projects (for ex: it might be `ot-collector.app.runforesight.com` for this repository) and you can share your workflow run and test metrics/insights with all your community as readonly in public without requiring everyone to signup Foresight.

**Comment by djaglowski** [comment]
+1, I'm excited to try this out.

**Comment by serkan-ozal** [comment]
Hi everyone, 

Here is an example of Foresight public view for another popular open-source project `Keycloak` (https://github.com/keycloak/keycloak) with its own custom sub-domain name: https://keycloak.app.runforesight.com

With Keyclocak Foresight public view, all Keyclocak contributors (in fact everyone) are able to see the workflow and test insights for Keycloak organization as readonly without requiring to signup Foresight.

Public view over custom sub-domain is free for open-source projects like `opentelemetry-collector`. If there is consensus on the use of Foresight, we can provide a custom sub-domain `ot-collector.app.runforesight.com` for this repository after integrating Foresight.

**Comment by jpkrohling** [comment]
@serkan-ozal, what do you need from us to get started?

**Comment by serkan-ozal** [comment]
Hi @jpkrohling,

You can start by creating a Foresight account [here](https://app.runforesight.com/) for `open-telemetry `org (https://github.com/open-telemetry) and then our UI will ask you to install Foresight Github app to access `open-telemetry` Github `org. 

Later you can select repositories you want to allow access to. Then Foresight will monitor workflows of those repositories automatically.

**Comment by serkan-ozal** [comment]
Hi @jpkrohling,

After then I can send a PR for your workflows to collect resource usage metrics, process traces, test and coverage results through our Github actions.

**Comment by serkan-ozal** [comment]
Hi @jpkrohling and open-telemetry community, how we should proceed on this?

**Comment by codeboten** [comment]
I'm happy to take a stab at trying this out in a fork of the core/contrib repos and report back to the community with findings. I suspect before we can add this to the open-telemetry org, we would need an issue in the community repo.

**Comment by jpkrohling** [comment]
Community issue created: https://github.com/open-telemetry/community/issues/1263

**Comment by serkan-ozal** [comment]
H, @jpkrohling @codeboten, 
Yes all we ask is for you to create a Foresight account here (https://app.runforesight.com) and install our Github app (our UI will redirect you to Github page to install the app).

Our Github app can work at repo level by giving access only for particular repositories. So you don't need to give access to all repositories.

Then we are happy to create a PR to this repo for adding our Github actions into your workflow to collect metrics, resource usages, process traces, test results and coverage reports.

**Comment by jpkrohling** [comment]
I don't think even maintainers have access to a repository's security settings, we need an org admin to set this up.

**Comment by tigrannajaryan** [comment]
Foresight for Collector contrib should be accessible at https://app.runforesight.com/repositories/github/open-telemetry/opentelemetry-collector-contrib/pull-requests

**Comment by serkan-ozal** [comment]
Hi @tigrannajaryan and OTEL community,

[app.runforesight.com](https://app.runforesight.com) requires authorization (which can be assumed to be used by admins who have access to the account with different roles) but [otel.app.runforesight.com](https://otel.app.runforesight.com) is not as it is public view for the community as we assigned custom sub-domain and enabled public view for the community.

**Comment by jpkrohling** [comment]
I'm closing this, as I believe the original goal was completed. If that's not the case, feel free to reopen.
