### ISSUE TITLE
[pdata] Revisit ValueType.String() output

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6249]
The output of the ValueType.String() is inconsistent with other similar methods. It has 2 issues:

1. After applying https://github.com/open-telemetry/opentelemetry-collector/issues/6081, all the string value identifies were consistently renamed to `Str`. The short name `Str` is chosen instead of `String` in order to avoid unintentionally implementing `fmt.Stringer` interface by string type `Value` getter. Output of `ValueType.String` for string type is still `STRING` which is inconsistent with other types:

```
ValueTypeEmpty -> "EMPTY"
ValueTypeStr -> "STRING"
ValueTypeBool -> "BOOL"
ValueTypeInt -> "INT"
ValueTypeDouble -> "DOUBLE"
ValueTypeMap -> "MAP"
ValueTypeSlice -> "SLICE"
ValueTypeBytes -> "BYTES"
```

2. String value returned by `pcommon.ValueType.String` has been generated by uppercasing type identifiers while other similar methods return identifies as e.g.:

```
MetricTypeNone -> "None"
MetricTypeGauge -> "Gauge"
MetricTypeSum -> "Sum"
MetricTypeHistogram -> "Histogram"
MetricTypeExponentialHistogram -> "ExponentialHistogram"
MetricTypeSummary -> "Summary"
```

Suggestion is to change `ValueType.String()` output to return the string representation of corresponding type identifiers:

```
ValueTypeEmpty -> "Empty"
ValueTypeStr -> "Str"
ValueTypeBool -> "Bool"
ValueTypeInt -> "Int"
ValueTypeDouble -> "Double"
ValueTypeMap -> "Map"
ValueTypeSlice -> "Slice"
ValueTypeBytes -> "Bytes"
```

It means we choose consistency over readability ("Str" instead of "String"). I believe it's ok given that we already return "BOOL" not "Boolean" for ValueTypeBool, but I'm open for any other suggestions.

cc @open-telemetry/collector-approvers

**Comment by bogdandrutu** [comment]
One more enum that we don't do this is `plog.SeverityNumber` see https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/plog/logs.go#L73

**Comment by dmitryax** [comment]
Makes sense. I'm looking into how `String` is being used in contrib. I think we can make it shorter and update `plog.SeverityNumber` accordingly

**Comment by bogdandrutu** [comment]
Please open a different issue about enums defined in the proto file. The enums Type defined by us are consistent now.

**Comment by bogdandrutu** [comment]
Also make sure we look at all of them and we come up with the rules

**Comment by dmitryax** [comment]
Sounds good. Closing this issue in favor of https://github.com/open-telemetry/opentelemetry-collector/issues/6251
