### ISSUE TITLE
[pdata] Inconsistent names of zero enum constants

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6256]
There are two categories of  enum types in pdata:

1. To represent enum fields in proto:
- `plog.SeverityNumber`
- `pmetrc.AggregationTemporality`
- `ptrace.SpanKind`
- `ptrace.StatusCode`

2. To represent options of oneof proto fieds:
- `pcommon.ValueType`
- `pmetric.MetricType`
- `pmetric.NumberDataPointValueType`
- `pmetric.ExemplarValueType`

Zero enums constants are called inconsistently across pdata.

For proto-defined enums (1), we mostly use the same name as defined in proto which is always `Unspecified`, e.g. `otrace.SpanKindUnspecified`. The only exception is SeverityNumber where we use `Undefined` for some reason:

```
SeverityNumberUndefined = SeverityNumber(otlplogs.SeverityNumber_SEVERITY_NUMBER_UNSPECIFIED)
```

For enums that defined in pdata (2) only, we use `Empty` and `None` suffixes for zero enum constants:

- `pcommon.ValueTypeEmpty`
- `pmetric.MetricTypeNone`
- `pmetric.NumberDataPointValueTypeNone`
- `pmetric.ExemplarValueTypeNone`

We should consider if we want to set the same suffix for all of them or allow different names. 

If we stick with `Unspecified` for (1), we need to rename at least `SeverityNumberUndefined` to `SeverityNumberUnspecified`. 

Renaming `pcommon.ValueTypeEmpty` doesn't seem desirable to me given that we have functions like `pcommon.NewValueEmpty` and `pcommon.Map.PutEmpty` that doesn't seem like should be renamed. 

Using `Empty` for `pmetric.MetricTypeNone`, `pmetric.NumberDataPointValueType` and `pmetric.ExemplarValueTypeNone` seems like acceptable option to me. Possibly `Empty` can be also applied to (1) enums as well.

@open-telemetry/collector-approvers

**Comment by bogdandrutu** [comment]
> For proto-defined enums (1), we mostly use the same name as defined in proto which is always Unspecified, e.g. otrace.SpanKindUnspecified. The only exception is SeverityNumber where we use Undefined for some reason:

I think we should change everywhere with `Unspecified`

> For enums that defined in pdata (2) only, we use Empty and None suffixes for zero enum constants:

I think we should consider Empty for Value an exception since it has a specific meaning.

**Comment by dmitryax** [comment]
Sounds to me. I'll submit PRs to have `Unspecified` for (1) and `Empty` for (2)
