### ISSUE TITLE
[pcommon.Map] CopyTo method replaces existing map

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector#6286]
**Describe the bug**
When using the `pcommon.Map.CopyTo` method as such:

```golang
a.CopyTo(b)
```
The contents of B are replaced with the contents of A instead of copied as the method describes: `CopyTo copies all elements from the current map to the dest.` 

**Steps to reproduce**

Using an initialised go mod project with the following go.mod values:

```
module bug-repoduce

go 1.19

require go.opentelemetry.io/collector/pdata v0.61.0

require (
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4 // indirect
	golang.org/x/sys v0.0.0-20210510120138-977fb7262007 // indirect
	golang.org/x/text v0.3.3 // indirect
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 // indirect
	google.golang.org/grpc v1.49.0 // indirect
	google.golang.org/protobuf v1.28.1 // indirect
)
```

You can run this section of code and have it panic.

```golang
func main() {
	a := pcommon.NewMap()
	a.FromRaw(map[string]interface{}{
		"foo": 1,
		"bar": 2,
	})

	b := pcommon.NewMap()
	b.FromRaw(map[string]interface{}{
		"baz": 3,
		"wee": 4,
	})

	a.CopyTo(b)

	c := pcommon.NewMap()
	c.FromRaw(map[string]interface{}{
		"foo": 1,
		"bar": 2,
		"baz": 3,
		"wee": 4,
	})

	c.Range(func(k string, v pcommon.Value) bool {
		actual, exist := b.Get(k)
		if !exist {
			panic("missing attribute " + k)
		}
		if !actual.Equal(v) {
			panic("value don't match for attribute " + k)
		}
		return true
	})

	if c.Len() != b.Len() {
		panic("size don't match")
	}
}
```

**What did you expect to see?**
Ideally C should contain the contents of both A and B from the above example code.

**What did you see instead?**
The contents of B is replaced with the values of A.

**What version did you use?**
Version: v0.61.0

**What config did you use?**
NA

**Environment**
OS: Darwin 
Compiler(if manually compiled): go 1.19.1

**Additional context**

**Comment by bogdandrutu** [comment]
This is expected behavior, probably the description of the func should be improved. See also few related things:
* https://github.com/open-telemetry/opentelemetry-collector/issues/6155
* https://github.com/open-telemetry/opentelemetry-collector/pull/6255

We want "CopyTo" to be equivalent of "assignment operation" so hence will overwrite not "append".

**Comment by MovieStoreGuy** [comment]
Right, with the function description I basically understood it to mean `Merge` and that is where my misunderstanding comes from.
