### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by alinskens** [open-telemetry/opentelemetry-collector#6317]
This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for OpenTelemetry](https://clomonitor.io/projects/cncf/open-telemetry) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: opentelemetry-collector
**URL**: https://github.com/open-telemetry/opentelemetry-collector
**Checks sets**:  `CODE`
**Score**: 69

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  31%  |
|  Security  |  65%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] [Changelog](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/CODEOWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/open-telemetry/opentelemetry-collector/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [31%]

  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco)) `EXEMPT`
  - [ ] OpenSSF badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.62.1) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [65%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [ ] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
I took a look into diagnosing the cause of the [Dangerous Workflow](https://github.com/ossf/scorecard/blob/7cd6406aef0b80a819402e631919293d5eb6adcf/docs/checks.md#dangerous-workflow) check today.

You can see the offending code is at the end of the ["Inform Incompatible PRs"](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/api-compatibility.yml#L47-L63) workflow.

And you can see the code for the [failing check](https://github.com/ossf/scorecard/blob/main/checks/raw/dangerous_workflow.go#L211-L233) in the Scorecard repo.

It seems the check is failing because vars are used inside the run statement.
