### ISSUE TITLE
ops-agent-opentelemetry-collector

### ISSUE THREAD

**Issue by agni3921** [open-telemetry/opentelemetry-collector#6341]
Hello,

I get an error message after ops agent install:

1.6660882501032064e+09	error	exporterhelper/queued_retry.go:361	Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors	{"error": "failed to export time series to GCM: rpc error: code = InvalidArgument desc = Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/"}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	C:/Users/abc/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:361
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	C:/Users/abc/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/metrics.go:133
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	C:/Users/abc/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:206
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	C:/Users/abc/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
All 3 services are running but the Agent reports 'Not Detected' in the Monitoring Cosole.

Please advise, Thanks

**Comment by haseeb-aziz** [comment]
@agni3921 hello how did you resolve this error? actually im facing exactly the same problem. Please guide

**Comment by artickl** [comment]
Same issue here...

**Comment by haseeb-aziz** [comment]
This is the logs  of opentelemetry pod. I'm getting this error 

info	exporterhelper/queued_retry.go:433	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\"", "interval": "38.375612262s"}

Please advise
