### ISSUE TITLE
Reference drive-letter specification link invalid

### ISSUE THREAD

**Issue by Chinwendu20** [open-telemetry/opentelemetry-collector#6374]
The link to reference drive letter specification, [here](https://github.com/open-telemetry/opentelemetry-collector/blob/c157b128e9ff32ed06e2913e2afa83c9abbed9ba/confmap/resolver.go#L32)
Redirects so:

![image](https://user-images.githubusercontent.com/59079323/197345089-2a7aa57a-a387-43e5-8b51-b1ac14275a7b.png)

**Comment by McGon-Fid** [comment]
I've picked this up. I will submit a PR later.
