### ISSUE TITLE
[OtelMetrics] Counters have a suffix "_total"

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#6403]
This is according to the Prometheus specs, but inconsistent with what was there before. We need to check that metrics scraped by otel/collector prometheus receiver remove this suffix and we are good then, otherwise this is a breaking change.

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/pull/6401/files

**Comment by paivagustavo** [comment]
@bogdandrutu tried this out today, and the prometheus receiver doesn't remove neither unit or type suffixes. Otel-go has an option to disable the `units` suffixes (`_bytes`, `_ratio` and `_milliseconds`) but not the type suffixes (`_total`).

There is an open ticket on the contrib repo tracking this https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8950. I'll try to make some time this week or the next to work on that.

**Comment by paivagustavo** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/6559 addresses the unit suffixes: `_bytes`, `_ratio` and `_milliseconds`

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16071 addresses the type suffixes: `_total`

**Comment by codeboten** [comment]
This was addressed some time ago, closing
