### ISSUE TITLE
Run as Windows Service

### ISSUE THREAD

**Issue by elitistphoenix** [open-telemetry/opentelemetry-collector#6433]
When running as a windows service installed by new-service (PS) or sc.exe I get

Error from windows event logs
The OpenTelemetry service terminated with the following error: 
An exception occurred in the service when handling the control request.

I know this was added
https://github.com/open-telemetry/opentelemetry-collector/issues/1119

What is the correct way to add + run + run with config file as a windows service

Sample code:
New-Service -Name "OpenTelemetry" -BinaryPathName '"C:\OpenTelemetry\otelcol-contrib.exe --config otel-iis.yaml"'
New-Service -Name "OpenTelemetry" -BinaryPathName '"C:\OpenTelemetry\otelcol-contrib.exe --config C:\OpenTelemetry\otel-iis.yaml"'

Neither works with obviously bin an config file in that location.

Windows event logs
EventData 
  param1 OpenTelemetry 
  param2 %%1064 
   4F00700065006E00540065006C0065006D0065007400720079000000

**Comment by bogdandrutu** [comment]
This should be fixed, we are doing a patch release now.

**Comment by elitistphoenix** [comment]
This works. Thank you!

**Comment by kooshan** [comment]
Hello there! I still have this issue with `contrib` distribution on version 0.80.0. Are there any workarounds to get this to work?

**Comment by mx-psi** [comment]
> Hello there! I still have this issue with `contrib` distribution on version 0.80.0. Are there any workarounds to get this to work?

@kooshan can you file a new issue for this? It is likely that the problem you are facing is not the same as the one on this issue.
