### ISSUE TITLE
Add test to validate service is up and running on windows

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#6455]
A [regression](https://github.com/open-telemetry/opentelemetry-collector/issues/6433) in v0.63.0 caused the collector service to crash. This should be tested through an integration test either in this repo or the contrib repository, or maybe even both to prevent further regressions.

**Comment by Sunilwali679** [comment]
@codeboten  I am interested in working on this issue . could you please assist me .
thanks

**Comment by codeboten** [comment]
Thanks @Sunilwali679!
