### ISSUE TITLE
Document adherence to Go style guidelines

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6463]
Effective Go [recommends not adding the `Get` prefix](https://go.dev/doc/effective_go#Getters) to getters. We should add this to our contributing guidelines.

We may just want to note that we abide by Effective Go guidelines instead.

_Based on comment by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/6447#discussion_r1011603439_

**Comment by Abhishek-569** [comment]
can I work on this ?  I am a beginner.

**Comment by mx-psi** [comment]
Sure, assigned to you @Abhishek-569 !

**Comment by Abhishek-569** [comment]
Should I  mention only  in [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md) that u cannot use get in getters name but u can use set in a setters name as suggested by [Effective Go Guidelines](https://go.dev/doc/effective_go#Getters).

**Comment by mx-psi** [comment]
I would add this under the ['Naming conventions'](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#naming-convention) header; we can mention both getters and setters convention

**Comment by Abhishek-569** [comment]
Okay

**Comment by Abhishek-569** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/7113 review it please. Feedback is appreciated.

**Comment by Abhishek-569** [comment]
Can someone close the issue as have completed it ?
