### ISSUE TITLE
Zipkin Receiver does not work with C++ OpenTelemetry Zipkin Exporter

### ISSUE THREAD

**Issue by zhixinwen** [open-telemetry/opentelemetry-collector#6477]
**Describe the bug**
I am using opentelemetry c++ lib and uses Zipkin as exporter.

**Steps to reproduce**
create a span and set the status code

**What did you expect to see?**
trace gets ingested by collector

**What did you see instead?**
trace rejected by collector, collector responds: `json: cannot unmarshal number into Go struct field .tags of type string`

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
0.63.0

**What config did you use?**
```
receivers:
  zipkin:
    parse_string_tags: true
```

**Environment**
Linux, C++

**Additional context**
I think the issue is the receiver except all tags to be in string format only, but C++ zipkin exporter is producing int for status fields. And they do allow int for other tags. 
If I export the trace to zipkin server directly, the trace would be ingested. I think the receiver behavior should be the same as zipkin server, otherwise it is going to be very confusing to the users.
Example trace:
```
[
  {
    "duration": 163843,
    "id": "dd5a6e8cd7fa5583",
    "kind": "SERVER",
    "localEndpoint": {
      "port": 9411,
      "serviceName": "test"
    },
    "name": "Test",
    "tags": {
      "error": "Error Message.",
      "arg": "arg: \"Hello\"\n",
      "otel.library.name": "grpc",
      "otel.library.version": "",
      "otel.status_code": 2,
      "rpc.grpc.status_code": 5
    },
    "timestamp": 1667588652215680,
    "traceId": "063f3d18cc40c2aa22e69754b78aa5b3"
  }
]
```

**Comment by lalitb** [comment]
I think the status code should be text - "OK" or "ERROR" as per the specs here - https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/trace/sdk_exporters/zipkin.md#status.

So, otel-cpp needs to fix this, and NOT the collector.

**Comment by codeboten** [comment]
closing issue as it is a c++ SIG issue.
