### ISSUE TITLE
String representation of `component.StabilityLevel` and `configtelemetry.Level` is inconsistent with other types

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6490]
`String` methods of all types in `pdata` module along with `service.State` return capitalized strings, for example:
- `pmetric.AggregationTemporality.String()`: "Unspecified", "Delta" or "Cumulative"
- `service.State.String()`: "Starting", "Running", "Closing", etc.

But `component.StabilityLevel` and `configtelemetry.Level` return lowercase strings:
- component.StabilityLevel.String(): "unmaintained", "deprecated", "in development", etc.
- `configtelemetry.Level.String()`: "none", "basic", "normal" or"detailed"

Should we align the to the same Capitalized format?

Or there is still a chance to make all other strings lowercase if we think that's a better option.

cc @bogdandrutu @codeboten @Aneurysm9

**Comment by bogdandrutu** [comment]
I think I like the "Capitalized" version more.

**Comment by Aneurysm9** [comment]
I also prefer capitalization.  It aligns with my expectation that Capitalized Terms are well-defined somewhere in the domain and may carry denotations beyond what might otherwise be considered as their plain meaning.

**Comment by bogdandrutu** [comment]
@dmitryax for configs I think we should allow any capitalization? I think it is fine if in the config file (like `configtelemetry.Level`) we allow users to write `"none"`, `"NONE"` or `"None"`.

**Comment by dmitryax** [comment]
> @dmitryax for configs I think we should allow any capitalization? I think it is fine if in the config file (like configtelemetry.Level) we allow users to write "none", "NONE" or "None".

Yes, that's how it's currently done in `configtelemetry.Level`, input of any case is supported

**Comment by codeboten** [comment]
Capitalized is fine with me.

**Comment by dmitryax** [comment]
Sounds good! I'll submit a PR to capitalize `component.StabilityLevel` and `configtelemetry.Level` strings.

**Comment by bogdandrutu** [comment]
For `CompressionType` there are some things:
* Capitalization does not make that much sense
* Maybe rename to `Compression`, but anyway we also need to fix the enum value names.

**Comment by atoulme** [comment]
It looks like the original issue is completed. Bogdan mentions we could look at renaming `CompressionType` `Compression` additionally.

**Comment by TylerHelmuth** [comment]
I've captured the configcompression piece in its own issue.  Closing this as completed.
