### ISSUE TITLE
Adding new data types to pdata module

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6508]
This is part of https://github.com/open-telemetry/opentelemetry-collector/issues/4705. 

Going forward we will need to add new signal types that are initially considered experimental. Before releasing pdata 1.0, we need to decide how we will be doing that given that the new signals probably shouldn't be part of pdata 1.0 right when they are added.

Currently, we have `pdata` as one module. This issue is intended to decide if we want to keep it this way or if we want to break it down into 4 modules. Let's consider both approaches applying profiling data signal as a possible candidate for the new experimental data type.

### Breaking down pdata into more modules

Breaking down pdata into more modules makes the addition of the new experimental signals straightforward. Let's imagine we add profiling data when stable modules are at the `1.2.0` version and beta modules are at `0.70.0`. The pdata modules structure would look like this:

- `go.opentelemetry.io/collector/pdata/pcommon 1.2.0`
- `go.opentelemetry.io/collector/pdata/plog 1.2.0`
- `go.opentelemetry.io/collector/pdata/pmetric 1.2.0`
- `go.opentelemetry.io/collector/pdata/ptrace 1.2.0`
- `go.opentelemetry.io/collector/pdata/pprofiling 0.70.0`

Once the profiling signal is stabilized, it's just upgraded to the current stable 1.x version

### Keeping one module

If we keep `pdata` as one module, things become a bit more complicated. According to the [go package resolving process](https://go.dev/ref/mod#resolve-pkg-mod):

> If one or more modules contain the requested package, the module with the longest path is used.

It means that we cannot introduce `go.opentelemetry.io/collector/pdata/pprofiling 0.70.0` and then make it part of `go.opentelemetry.io/collector/pdata 1.x` without changing the package path. So we will need to introduce an experimental module like `go.opentelemetry.io/collector/pdata/experimental 0.70.0` where we can put `pprofiling` until it's stabilized and moved to `go.opentelemetry.io/collector/pdata/pprofiling`

---

Given all the complications with adding experimental new signals to pdata, I'd lean towards further breaking down `pdata` package. We can break it down after 0.64.0 release and set the version of the new modules to `1.0.0-rc.1`. Looking for other opinions. 

cc @open-telemetry/collector-approvers

**Comment by dmitryax** [comment]
> If I remember correctly it is backwards compatible to break the pdata into smaller packages later (after 1.0). If that is the case why not doing that when there is a need for a new package?

Look like you're right. I played with it and can confirm that it's not a breaking change for a package migrating to the new module structure even if some indirect dependencies still use the old module structure.

**Comment by dmitryax** [comment]
@bogdandrutu I've played with it a bit more and found that it'll be not a smooth upgrade experience for packages on 1.16 and earlier go versions. Splitting the pdata module can cause `ambiguous import` errors on dependant packages on that version if there are any other indirect dependencies using pdata, the errors can be fixed with explicit `replace` statements tho.

I believe it's still ok to keep it in one module for now. When we will need to do the split, go 1.16 probably will be way too outdated.

**Comment by bogdandrutu** [comment]
>  1.16 and earlier go versions.

We are already on go 1.18 minimum anyway (and allowed to use generics etc.). So would not worry about that.

**Comment by mx-psi** [comment]
AIUI the outcome of this discussion is that we will keep a single pdata module and add new signals on separate modules while experimental, I think that should clear the situation. Can we therefore close this or is there anything left to discuss?
