### ISSUE TITLE
Reload client CAs periodically

### ISSUE THREAD

**Issue by akorompai** [open-telemetry/opentelemetry-collector#6524]
**Is your feature request related to a problem? Please describe.**
Need to restart the collector in order to reload the client CAs.

**Describe the solution you'd like**
Make it work like [certificate reloader](https://github.com/open-telemetry/opentelemetry-collector/blob/e07665cacabfdf6769f2c01576abde9786d0160b/config/configtls/configtls.go#L178) in same context.
Could use `GetClientConfig` callback as a hook to reload the client CAs from disk.

**Comment by atoulme** [comment]
The issue appears fixed with #6708. Please reopen if more work is needed.
