### ISSUE TITLE
Remove Set for non immutable fields in the new data package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#653]
This was a problem before with protos but I think we have a chance to fix it now, let's assume we have a pipeline Processor1 -> Processor2:
* Processor1 creates an "immutable" from its perspective `MetricDescriptor` and uses `Metric.SetMetricDescriptor()`. Let's assume we just copy the pointer and do not make a copy of the immutable fields inside the MetricDescriptor (this was possible in the proto because you set the pointer).
* Processor2 calls "MetricDescriptor.SetName()" this actually changes the name in the Processor1 instance which is bad.

Options:
1. Do a deep copy when we call SetX where X is mutable. Probably we should rename the methods `CopyFrom` and move them from the parent to the actual object. In the example above `MetricDescriptor.CopyFrom(MetricDescriptor)` will be the new function where we copy all the fields. Probably need to provide some helpers for constructions to avoid deep-copy of the objects that are under construction.
1. Remove completely all `Set` methods for mutable fields and ask users to manually do a deep copy by calling all set methods for all the immutable fields, this has a problem that if we add a new field then we need to change calls in all the places.
1. Remove all `Set` methods (including the once for immutable fields) and make all objects immutable. This has the disadvantage that changing any field will require at least one allocation.

**Comment by tigrannajaryan** [comment]
We have clear data ownership guidelines which say that 2 processors cannot own the data at the same time. Once the Processor1 hands over the data to Processors2 the ownership is transferred and Processor1 must forget about that data.
See https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#data-ownership

Given these ownership rules do we still have this problem?

**Comment by bogdandrutu** [comment]
It is still a problem, let's assume in the current model where we use ocprotos, can a MyProcessor that is marked as "Exclusive data ownership" do the following?
```
attributesMap = span.getAttributes()
attrVal := attributesMap["myKey"]
if (attrVal != nil) {
  attrVal.Type = STRING
  attrVal.StringValue = "foo"
}
```

If the answer is yes (it is correct valid this) then if the "myKey" attribute was added by the AttributesProcessor via INSERT (we have a pointer to the attributeValue that we reuse every time we do insert) then `MyProcessor` will change the what we believed immutable `AttributeValue`.

**Comment by bogdandrutu** [comment]
I think if we want to keep the Set functions we need to clarify this:

> The ownership of the TraceData and MetricsData in a pipeline is passed as the data travels through the pipeline. The data is created by the receiver and then the ownership is passed to the first processor when ConsumeTraceData/ConsumeMetricsData function is called.

We need to clear say that same pointer (in the v1) object (in the v2) cannot be set multiple times.

**Comment by tigrannajaryan** [comment]
You are right. I don't think ownership rules are enough.

For example if AttributesProcessor does this:
```go
attributesMap = span.getAttributes()
attributesMap.Insert("myKey", akv)
```
then it gives up the ownership of `akv` and `akv` may be modified by others later in the pipeline. But it is really very difficult to clarify this in ownership rules and it is very easy to make this mistake.

Thinking of options that you listed. Option 1 seems reasonable. It eliminates the mistakes since we always copy. On the other hand I do not think it is a big performance hit since processors usually operate on small nested parts of the data, such as attributes. Are there cases when this can cause significant performance issues?
