### ISSUE TITLE
Resize(newSize) Function on ResourceLogsSlice, InstrumentationLibraryLogsSlice, LogRecordsSlice

### ISSUE THREAD

**Issue by lprakashv** [open-telemetry/opentelemetry-collector#6541]
**Is your feature request related to a problem? Please describe.**
My use case is that I want to split (or limit) my `*pdata.Logs` packet created for a list of log events if the size of `*pdata.Logs` exceeds some `maxBytes`. 

As part of the existing system, we are building the packet from a list of events where we keep appending to `ResourceLogs`, `InstrumentationLibraryLogs` and `LogRecords`.

To achieve our goal we are planning to add the size calculation using the `LogSizer` implementation provided by the `LogsMarshaler` and remove the last appended `ResourceLogs`, `InstrumentationLibraryLogs` and `LogRecords` based on the requirement if size exceeds the `maxBytes`.

**Describe the solution you'd like**
If there is a `Resize(newCap int)` or `RemoveLast()` methods available for each of the Slices, our job would be quite easy.

**Describe alternatives you've considered**
We cannot access the internal representation due to that being part of the `internal` package.

**Additional context**

**Comment by bogdandrutu** [comment]
Have you checked "RemoveIf", we use that in the split logic in batch processor, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/splittraces.go#L29

**Comment by lprakashv** [comment]
Thanks @bogdandrutu but here `RemoveIf()` won't make sense as we do not want to iterate the entire slice, just want to remove the last appended element for performance reasons.

And based on the snippet in the link you shared, it is working based on the size in terms of length/count but not in terms of bytes. And the problem with calculating bytes using `LogSizer.logSize(pdatalogs)` is that it only needs the `*pdata.Logs` so child element size is not available to me before adding to the top level OTLP log.

So, in my logic, when we built the otlp log packet and calculate the size, if that exceeds some maxBytes, we want remove the last appended element to the slices.

**Comment by bogdandrutu** [comment]
> So, in my logic, when we built the otlp log packet and calculate the size, if that exceeds some maxBytes, we want remove the last appended element to the slices.

Why do you care about performance since the calculation of the size iterates over all elements anyway?

> And based on the snippet in the link you shared, it is working based on the size in terms of length/count but not in terms of bytes. And the problem with calculating bytes using LogSizer.logSize(pdatalogs) is that it only needs the *pdata.Logs so child element size is not available to me before adding to the top level OTLP log.

It is, because calculating the "wire size" of a message does not make too much sense (who am I to judge that, but I still don't understand why you need it), since you have also compression, etc. which will influence the size of the final payload.

**Comment by bogdandrutu** [comment]
Also keep in mind that "remove" for say a "log record" it is a complex operation, because you need to copy its Resource/Scope and construct the entire message structure, you cannot simply remove the "Log Record" and create an empty message.

**Comment by lprakashv** [comment]
Thanks for the inputs @bogdandrutu I initially thought re-slicing is an in-place operation. Now, it makes sense to avoid this.

More on my use-case wire size matters to avoid larger size message downstream, because log messages can vary a lot in size.

**Comment by lprakashv** [comment]
Closing this issue, will create a new issue for the `LogSizer` like implementation for `ResourceLog` and `LogRecord`
