### ISSUE TITLE
Fix consistency between Attributes (struct) and events/links

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#656]
There is currently a definition for an object call Attributes that encapsulates an AttributesMap and dropped information, but not available for other fields like links/events.

Suggestions:
1. Remove Attributes and have a specific setDroppedAttributes call for all the struct that include attributes.
1. Add Links/Events as structs similar with Attributes.

Personally I prefer the first suggestion.

**Comment by tigrannajaryan** [comment]
I am fine with the first approach.
