### ISSUE TITLE
[component] Move [Receiver|Processor|Exporter|Extension] specific parts from component module

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6578]
Currently `component` package includes API specific to [Receiver|Processor|Exporter|Extension] components. That API can be moved to the corresponding packages to simplify the API. 

Instead of 

```
import "go.opentelemetry.io/collector/component"

component.ExporterConfig
component.UnmarshalExporterConfig
component.Exporter
component.[Traces|Metrics|Logs]Exporter
component.ExporterCreateSettings
component.ExporterFactory
component.ExporterFactoryOption
component.Create[Traces|Metrics|Logs]ExporterFunc
component.With[Traces|Metrics|Logs]Exporter
component.NewExporterFactory
component.ExporterFactoryOption
```

users will use

```
import "go.opentelemetry.io/collector/exporter"

exporter.Config
exporter.UnmarshalConfig
exporter.Exporter
exporter.[Traces|Metrics|Logs]
exporter.CreateSettings
exporter.Factory
exporter.FactoryOption
exporter.Create[Traces|Metrics|Logs]Func
exporter.With[Traces|Metrics|Logs]
exporter.NewFactory
exporter.FactoryOption
```

Prototype PR: https://github.com/open-telemetry/opentelemetry-collector/pull/6552

**Comment by bogdandrutu** [comment]
Proposing few changes to the plan:
* Remove per component kind Config, we can simply use "component.Config" everywhere, no need to have any special functionality there, especially since we are aiming to make `Config` a totally opaque object from collector perspective.
