### ISSUE TITLE
Implement ability for extensions to be notified about effective configuration

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#6596]
To implement OpAMP for the Collector we need a way for extensions to know what is the current effective configuration of the Collector, see the [design document](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit#heading=h.ioikt02qpy5f.

This can be implemented as an optional interface that extensions can implement to be notified of the current config.

The config must be reported immediately after the extensions are started and then every time the config changes as a result of ConfigProvider reloads.

**Comment by evan-bradley** [comment]
I can work on this.

**Comment by tigrannajaryan** [comment]
@evan-bradley feel free to add me a as a reviewer on all OpAMP-related PRs.

**Comment by bogdandrutu** [comment]
> This can be implemented as an optional interface that extensions can implement to be notified of the current config.

Why not an optional interface on the Host? I would like to determine when to do one or the other.

**Comment by evan-bradley** [comment]
>Why not an optional interface on the Host? I would like to determine when to do one or the other.

I would like to use a push-based model for this so in the future the Host can update extensions that persist across configuration updates. Even if that doesn't happen anytime soon, having the Host push updates to extensions is not much more complex than having extensions call a method on the Host to get the effective configuration.

To notify extensions, we will either need to provide an interface on the Host that allows extensions to register message handlers, or allow the Host to call a method on extensions that want to be notified of updates. I think having an optional interface for extensions will provide the simplest solution. This also matches the approach to host-component communication for component status reporting in https://github.com/open-telemetry/opentelemetry-collector/pull/6560.
