### ISSUE TITLE
Collector Is Exporting Unicode Sequences Within Data

### ISSUE THREAD

**Issue by hannan-khan-intelops** [open-telemetry/opentelemetry-collector#6609]
**Describe the bug**
I am currently using the OpenTelemetry Collector to collect data gathered from [Pixie](https://github.com/pixie-io/pixie). The data is in OpenTelmetry format. I have two `exporter` configurations, one for `logging` and one `otlphttp` for exporting the data to [Vector](https://github.com/vectordotdev/vector). The data that shows up in the logs is fine. However, the data that shows up in Vector contains Unicode sequences (see image). I have even tried exporting the data with `gzip` compression disabled, to no avail. I have also tried changing the encoding on the Vector end of things, and that has still not worked.
`Data From The Logging Exporter (working fine)`
<img width="480" alt="image" src="https://user-images.githubusercontent.com/114026668/203453441-e74a4aa8-1b0c-4b77-ae7f-10deb32404da.png">
`Data From The Vector Exporter (not working fine)`
<img width="466" alt="image" src="https://user-images.githubusercontent.com/114026668/203453586-f2a2ddfd-c57a-46ed-9663-c2d8e981656f.png">
**Steps to reproduce**
Export data using otlphttp, with the following configuration:
```yaml
    otlphttp:
      endpoint: http://vector.vector.svc.cluster.local:80
      metrics_endpoint: http://vector.vector.svc.cluster.local:80
      compression: none
```
**What did you expect to see?**
I expected to see the data in Vector without any Unicode sequences.
**What did you see instead?**
Presence of Unicode sequences within the exported OpenTelemetry data.

**What version did you use?**
Version: 0.64.1

**What config did you use?**
Config: config file [here](https://gist.github.com/hannan-khan-intelops/006e81377ef064465995cfd345cb4a2f).

**Environment**
OS: Ubuntu 20.04.5 LTS

**Additional context**
...

**Comment by bogdandrutu** [comment]
This seem to me as a bug from <`0.64.1` (was fixed in `0.64.1`) can you double check the version? Also try disable "debug" level in the logging exporter, that will also fix the problem.

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/issues/6420

**Comment by bogdandrutu** [comment]
Inactive issue. Please reopen if you can provide the answers.
