### ISSUE TITLE
why can't we config the Multiplier and RandomizationFactor for retry_on_failure

### ISSUE THREAD

**Issue by yutingcaicyt** [open-telemetry/opentelemetry-collector#6610]
**Describe the bug**
For retry_on_failure, Multiplier and RandomizationFactor are fixed in code, Multiplier=1.5, RandomizationFactor=0.5. In this situation, min_interval may be less than current_interval after calculation which cause the unpredictable retry times. 

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
If we can set the Multiplier as 2, then min_interval would not be less than current_interval, so the max_retry_times can be measured.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by bogdandrutu** [comment]
> why can't we config the Multiplier and RandomizationFactor for retry_on_failure 

Because it is not implemented.

**Comment by Gabrielopesantos** [comment]
Hello,
I would like to work on this issue. Is there anything I should know before starting (Besides the [documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)]? Thank you

**Comment by jpkrohling** [comment]
Take a look at the contributing guidelines. Other than that, have fun and let us know if you get stuck.

**Comment by Chinwendu20** [comment]
I think this issue should be closed?

**Comment by atoulme** [comment]
Looks that way! Closing, thanks!
