### ISSUE TITLE
Consider ability to specify a noop, heavily sampled or restricted zap logger for a pipeline

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#6635]
A common approach to collect Collector's own metrics today is to create a dedicated pipeline that uses a Prometheus receiver to scrape the Collector. This works fairly well.

It would be useful to use a similar technique to collect Collector's own logs, by redirecting them to a file and using a filelog receiver on a dedicated pipeline to collect the logs. However, we can't do this since there is danger that collecting logs can result in creation of more logs and result in catastrophic amplification of log generation.

One possible solution is to allow specifying a special logger for a particular pipeline. The dedicated pipeline and all components attached to the pipeline could then use a noop logger (or a sampled logger or a logger with Level>=ERROR only) so that we ensure that log amplification is not a problem.

It is not entirely clear what this should look like in the config file.

**Comment by jpkrohling** [comment]
This is related to an issue proposed by @TylerHelmuth (#6629), in the context of traces. Let us make it very easy for people to receive our telemetry data in a separate process, following the best practices around the "monitor of monitors" pattern.

In that sense, we should keep sending logs to stdout/stderr, the current best practice for applications (the collector being one in this context), and letting external processes read and collect that. At most, we should provide an option for people to send data via OTLP to an external process.
