### ISSUE TITLE
[pdata] Reconsider [Map|...Slice].Sort methods 

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6660]
Currently we have two types of Sort method in pdata:
1. `Map.Sort() Map`
2. `...Slice.Sort(func(a, b ...) bool) ...Slice` e.g. `func (es SummaryDataPointSlice) Sort(less func(a, b SummaryDataPoint) bool) SummaryDataPointSlice`

We don't have any other methods which mutate and return the same objects in pdata. Documentation for (2) says

```golang
// Returns the same instance to allow nicer code like:
//
//	lessFunc := func(a, b SummaryDataPoint) bool {
//	  return a.Name() < b.Name() // choose any comparison here
//	}
//	assert.Equal(t, expected.Sort(lessFunc), actual.Sort(lessFunc))
```

but we don't have any usages like that for (2). All the usages of (2) are applied on the contrib tests and all of them don't use the returned object.

Contrib usages of (1) do rely on the returned object, but most of them are done in tests. Places where the returned object is used in production code usually use that object only and don't expect the original one to be mutated. This assumption was recently found in multiple exporters claimed as not mutating, and it caused several issues:
- https://github.com/open-telemetry/opentelemetry-collector/issues/6420
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16499

The suggestion is to change both types of the Sort method to not return any value. It'll complicate some tests relying on (1) but will make it clear that it's a mutating method to avoid the mentioned issues. We can also consider https://pkg.go.dev/sort#Slice as a reference that doesn't return any value. Later, maybe we can introduce some helpers for checking the Map equality without doing the sort. That will make the contrib tests cleaner.

Given that most of the usages are done in test code, believe we can make an exception here and introduce a breaking change just by changing the function signature to not return any value.

**Comment by bogdandrutu** [comment]
+1
