### ISSUE TITLE
Contrib tests output is not visible

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6669]
**Describe the bug**

While working on #6637 contrib tests were failing but I could not see why. It looks like since open-telemetry/opentelemetry-collector-contrib#16427 we pipe the output of `go test` to a file to use Foresight. 

**Steps to reproduce**

Run contrib tests on a PR that will make them fail.

**What did you expect to see?**

Errors show up in the log

**What did you see instead?**

They don't!

**Additional context**

We can use `tee`, but the output will be in JSON format, so we may want to use a tool like [`gotestsum`](https://github.com/gotestyourself/gotestsum) that can handle both human readable output and JSON output at the same time.

**Comment by bogdandrutu** [comment]
Apparently you can find them in `Foresight`, not sure where, I was not able to do that :))

**Comment by serkan-ozal** [comment]
Hi @bogdandrutu, @jpkrohling,

Test results are already available in Foresight but as far as I can see that test logs are missing.  Are you looking for seeing test logs in the Foresight, right?

**Comment by jpkrohling** [comment]
Ideally, they would be both at the console output in human-readable format and in Foresight.

**Comment by serkan-ozal** [comment]
Hi @jpkrohling @mx-psi,

For a quick workaround we are considering consuming (parsing) test reports in TEXT (human readable) format and redirecting it to both stdout and file by tea (`... 2>&1 | tee outfile`). Does it make sense?

**Comment by jpkrohling** [comment]
Yes!

**Comment by mx-psi** [comment]
Yes, that would make sense

**Comment by serkan-ozal** [comment]
Hi @jpkrohling @mx-psi, 
I have opened this PR for the fix: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16731

**Comment by mx-psi** [comment]
Test output is now visible at the latest main contrib tests https://github.com/open-telemetry/opentelemetry-collector/actions/runs/3634393231/jobs/6132428024 so we can close this. Thanks @serkan-ozal !
