### ISSUE TITLE
Add E2E test for OTLP receiver

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#668]
See how E2E tests for other receivers are done in the `testbed`.

**Comment by nilebox** [comment]
@tigrannajaryan please assign to me.

**Comment by bogdandrutu** [comment]
@nilebox please apply to become a member of the community. Look for instructions in the community repository I am happy to support that, @tigrannajaryan can also support it.

**Comment by tigrannajaryan** [comment]
@nilebox I implemented the E2E test for OTLP exporter and will do this one as well, it is trivial for me to do that, no need for you to spend time on this.

**Comment by nilebox** [comment]
Sure, thanks.
