### ISSUE TITLE
Handle partial success responses from OTLP export services

### ISSUE THREAD

**Issue by joaopgrassi** [open-telemetry/opentelemetry-collector#6686]
### Problem Statement

Following the https://github.com/open-telemetry/opentelemetry-specification/pull/2696, each OTel SDK is encouraged to handle the resulting error message string in an appropriate way, considering existing norms. This requires OTLP v0.19. If I got it correct, this PR already added support for it in pdata https://github.com/open-telemetry/opentelemetry-collector/pull/6361

### Proposed Solution

For each of the `Export*ServiceResponse` methods used by OTLP Trace and Metrics exporters, construct an error and call the appropriate handler with the error message string and the number of spans/points(/logs) dropped. Future OTel specifications may call for optional treatment of the number of dropped items, but presently that is just additional information to include in the handled error.

For context, here's a few SDKs that already implemented handling partial success responses: [Go](https://github.com/open-telemetry/opentelemetry-go/issues/3102), [PHP](https://github.com/open-telemetry/opentelemetry-php/issues/802)

cc @jmacd @tigrannajaryan @evan-bradley

**Comment by evan-bradley** [comment]
I'll work on implementing this.

**Comment by jmacd** [comment]
I would say that ideally the return from a PartialSuccess would factor into the counts of dropped points/spans/logs vs accepted points/spans/logs. Was this considered? The way the PRs #6971 and #6970 were written, these become total errors and the result is `exporterhelper` counts them as such, meaning:

1. The metrics are wrong in a way that PartialSuccess was meant to preserve.
2. The producer of the metrics doesn't get propagated results telling them how many of their points dropped.

I think the collector's metrics should factor the meaning of PartialSuccess in and also propagate the partial success to the original producer. Can we leave this open, hoping for improvements?
