### ISSUE TITLE
pdata Map.Sort() leaks underlying storage behavior and prevents future optimizations

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#6688]
The Map.Sort() contract is that it makes the data comparable using reflection-based equality methods, primarily used for testing.

Unfortunately the Sort() method is abused in many places with the expectation that it impacts the behavior of a subsequent Range() operation. See for example https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1ad54c003dcdd21d7f0bf44a67adf2862ddb9b49/processor/cumulativetodeltaprocessor/internal/tracking/identity.go#L45 or https://github.com/influxdata/influxdb-observability/blob/694f0a4cf4906008a896b7ac8a154fa033bf7b89/influx2otel/metrics_telegraf_prometheus_v2.go#L65

The pattern Sort/Range makes an assumption that the Range honours the sorted state. This leaks the implementation and can prevent future optimizations (for example we may want to make the map storage an open addressing hash map instead of unsorted vector).

I suggest to deprecate the Sort function and replace it with:
- IsEqual(map1, map2) or map1.IsEqual(map2)
- Optionally also add Map.SortedRange or Map.OrderedRange if think this is important. Or, we don't provide this and whoever needs an ordered range can do a Range() and copy from the map to a temp slice and sort the slice.

cc @open-telemetry/collector-maintainers

**Comment by dmitryax** [comment]
We discussed that during the SIG call and agreed that is an important issue to fix before releasing pdata 1.0, but we will release 1.0.0-rc1 as planned and do it after

**Comment by dmitryax** [comment]
For the (1) use case, where map equality check is needed in tests, we can use `AsRaw()` for direct comparison. But, sometimes users need to compare pdata instances that include several maps and slices in it. Currently, Sort() can help with that as done in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/551e5c97b32588c33a3852f2635052813e727c2e/pkg/stanza/adapter/frompdataconverter_test.go#L116. Removing it makes the workaround much more complicated. And I think there can be use cases like this outside of contrib.

There is a great module for this particular need: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/scrapertest. It should be expanded to work with traces and logs. And I think it's a good candidate to be moved to pdata as part of `pdata/pmetric/pmetrictest`, `pdata/ptrace/ptracetest` etc. It should make writing test much easier for pdata users.

@bogdandrutu WDYT?

**Comment by bogdandrutu** [comment]
So you think that a "Equal" func on the map is needed? I would call it `Equal` since we have the same on `Value`

**Comment by dmitryax** [comment]
I think we need some API to compare all the pdata objects with each other. If we have `Map.Equal` only, users will have to call it on all the nested maps manually if they need to compare pmetric.Metrics for example.

We can introduce `Equal` to all the pdata objects. But `Value.Equal` is being used in contrib tests only and  [https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/comparetest/compare.go](comparetest package) (sorry, I renamed the package, so the link in the previous message is broken now) provides much nicer functionality where you get the diff instead of bool. So maybe we can bring [https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/comparetest/compare.go](comparetest package) into `pdata/pmetric/pmetrictests`?

**Comment by dmitryax** [comment]
Or we can start with `Equal` on all pdata objects to remove `Map.Sort` and bring the `comparetest` later additionally if want to

**Comment by dmitryax** [comment]
I see another use case raised in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13944 where deterministic marshaling of pdata.Map is needed. To resolve that I think we can introduce an option in https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pmetric/json.go#L29 to make sure that maps are always marshaled with KeyValue sorted by keys:

```
type JSONMarshaler struct {
	SortMaps bool
}
```

**Comment by bogdandrutu** [comment]
I think for the moment we should aim to remove Sort and not provide anything (less API better API). Let's see how the tests will look like in contrib and learn if that is possible.

> https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13944

That is another test example... we SHOULD NOT pollute our public API for testing reasons where performance does not matter, etc.

**Comment by dmitryax** [comment]
Ok, let's start with minimal changes first. I added Map.Equal in https://github.com/open-telemetry/opentelemetry-collector/pull/6786

**Comment by dmitryax** [comment]
We discussed the issue with @bogdandrutu and decided not to introduce any new API in pdata for a moment. Instead, we improve the `consumertest` in the contrib and ensure it's used by more test cases needing such functionality. Potentially that can be added to pdata as test helper packages. We will also deprecate `Value.Equal` to be consistent which can be easily replaced with `Value.AsRaw()` in tests

**Comment by tigrannajaryan** [comment]
> We discussed the issue with @bogdandrutu and decided not to introduce any new API in pdata for a moment.

Just to clarify: you still intend to deprecate Map.Sort(), right?

**Comment by dmitryax** [comment]
> Just to clarify: you still intend to deprecate Map.Sort(), right?

Yes, we do. Just discussing what we provide as a replacement for test use cases
