### ISSUE TITLE
Add E2E test using Prometheus receiver

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#67]
We don't have E2E test with Prometheus and changes that can break it are not caught.

**Comment by punya** [comment]
Closing this out because we now have https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/prometheusexporter/end_to_end_test.go and https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/prometheusreceiver/internal/staleness_end_to_end_test.go .
