### ISSUE TITLE
Code coverage target

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector#671]
Since Jaeger is planning to start using otel collector, I wanted to check what code quality tooling is being used here. The code coverage is showing at 75%, which is much lower than Jaeger's target of 95% (*). Can it be raised and threshold checks added to CI?

(*): in Jaeger some small packages are explicitly excluded due to requiring external dependencies like storage or kafka.

cc @pavolloffay @objectiser

**Comment by bogdandrutu** [comment]
@yurishkuro we should make this our top priority in April. Let's call April the coverage month :)

**Comment by bogdandrutu** [comment]
I think the major difference was that you did calculate the coverage across packages which we did not, added #723 to fix that problem.

@yurishkuro suggest you use go-acc instead of manually written bash script to execute coverage across packages.
