### ISSUE TITLE
Proper division between "service" & "otelcol" packages

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#6766]
In #6723, I attempted to move `component.Factories` and `componenttest.NopFactories` to `otelcol` and `otelcoltest`, respectively. However, I was not able to identify a clear separation point between `service` and `otelcol` packages. 

Additional context: https://github.com/open-telemetry/opentelemetry-collector/pull/6723#discussion_r1044763514

The immediate problems are:
1. Both `otelcol` and `service` contain many references to `Factories`.
2. `otelcol` contains many references to `service`. 

Therefore, `Factories` can exist in `service` without causing import cycles, but the opposite is not true. 

In order to move `Factories` to `otelcol`, we must determine which of the two points above should change. Should `otelcol` not depend on `service`, or should `service` not depend on `Factories`?

**Comment by bogdandrutu** [comment]
> or should service not depend on Factories?

Done in https://github.com/open-telemetry/opentelemetry-collector/pull/6774
