### ISSUE TITLE
Clearly separate Config and Settings terms used in struct names throughout the codebase

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6767]
Currently, we use the `Config` term for collector configuration as a whole and parts of it defined for receivers/processors/exporters/extensions. Examples:

- `otelcol.Config`
- `component.Config`
- `otlpexporter.Config`

But for unmarshalling some deeper parts of the user config, we use `Settings` structs, for example:

- [x] `exporterhelper.QueueSettings`
- [x] `configgrpc.GRPCClientSettings`
- [x] `configtls.TLSSetting`

At the same time `service/telemetry` package still uses `Config`, e.g. `MetricsConfig`, `LogsSamplingConfig`, and `TracesConfig`.

The suggestion is to use `Config` term for all the structs used to unmarshal any parts of the YAML config provided by users. We will keep `Settings` only for structs that are populated programmatically, like:

- `component.TelemetrySettings`
- `component.ReceiverSettings`

**Comment by bogdandrutu** [comment]
I think we should start working on this, because we cannot delay until the stability.

**Comment by atoulme** [comment]
List of renames:
* [ ] `GRPCClientSettings`
* [ ] `GRPCServerSettings`
* [ ] `HTTPClientSettings`
* [ ] `HTTPServerSettings`
* [ ] `CORSSettings`
* [ ] `QueueSettings`
* [ ] `TimeoutSettings`
* [ ] `ScraperControllerSettings`

**Comment by TylerHelmuth** [comment]
Removing from the confighttp milestone as the public structs now use `Config`.

**Comment by codeboten** [comment]
Closing this in favour of https://github.com/open-telemetry/opentelemetry-collector/issues/9428

**Comment by codeboten** [comment]
exporterhelper still needs updating

**Comment by jade-guiton-dd** [comment]
I'll work on this.

**Comment by jade-guiton-dd** [comment]
If I'm not mistaken, #11264 was the last step for this issue, so it can probably be closed.

**Comment by mx-psi** [comment]
Taking a look at the output of `rg 'type \w*Setting' -tgo -i` it looks like this is indeed the case :rocket:
