### ISSUE TITLE
[pdata] Remove pcommon.Value.Equal()

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#6811]
This method should be removed because we don't have the `Equal` method on other pdata structs and it's used in tests where it can be easily replaced by comparing the results of the `AsRaw` method.

We don't want to introduce the `Equal` method on other pdata structures because it's not clear if different orders of pdata slices with the same items should be considered equal. It's not defined in the spec, and we don't want to define that in pdata.

This issue is related to https://github.com/open-telemetry/opentelemetry-collector/issues/6688.

**Comment by jpkrohling** [comment]
Should this be closed?

**Comment by dmitryax** [comment]
> Should this be closed?

Not yet, let's keep it open for now since if referenced in the code https://github.com/open-telemetry/opentelemetry-collector/pull/6812/files#diff-a0694cfd0d20ad1bb48788b6034d7e47349a86caae7f0db55b88f171c1a8342bR371
