### ISSUE TITLE
Release script did not create Github release

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6849]
On the v0.68.0 release cycle, the release script did not create a v0.68.0 Github release, creating only a [`cmd/builder/v0.68.0`](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.68.0) release instead.

This caused trouble on the opentelemetry-collector-releases repository, where we had to fix the URL on open-telemetry/opentelemetry-collector-releases#256.

I am creating the Github release manually myself for this release, but it would be great to go back to have releases be done automatically and be consistent with each other.

----

This also happened on v0.70.0 and v0.76.0

**Comment by djaglowski** [comment]
@mx-psi, I may need to do this manually today - can you help me understand what specifically was done manually?

**Comment by mx-psi** [comment]
Looks like it worked this time? What I did was manually creating a new release pointing to the `v0.68.0` tag with the same structure as previous releases, and adding a link to the `cmd/builder/v0.68.0` release to it, so that people could find the release link

**Comment by djaglowski** [comment]
Thanks @mx-psi. If I recall correctly, the generated release was named `cmd/builder/v0.69.0`, but it seemed to contain all the artifacts expected in prior releases, so I just renamed it.

**Comment by dmitryax** [comment]
Looks like it's still the case. v0.70.0 release was not created automatically

**Comment by mx-psi** [comment]
Did you run into this on the last release @Aneurysm9?

**Comment by Aneurysm9** [comment]
No.  You can see [here](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/cmd%2Fbuilder%2Fv0.73.0) that the release was created by `github-actions`.

**Comment by codeboten** [comment]
Added a separate step in the action to create the release for the v* tag in https://github.com/open-telemetry/opentelemetry-collector/pull/7596
