### ISSUE TITLE
Add security recommendation to use `configopaque.String` for sensitive fields.

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6854]
We should add a nudge to using [the `configopaque` package](https://pkg.go.dev/go.opentelemetry.io/collector/config/configopaque) on configuration structs to the [security recommendations document](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.68.0/docs/security-best-practices.md#configuration).

Additionally, it may be good to add a mention about this to the ["when adding a new component"](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.68.0/CONTRIBUTING.md#when-adding-a-new-component) section on the contributing doc.

**Comment by vitorguidi** [comment]
I would like to take ownership of this issue.

**Comment by mx-psi** [comment]
All yours @vitorguidi :rocket:

**Comment by Abhishek-569** [comment]
Can I work on this issue since there have been no update since last 1 month?

**Comment by mx-psi** [comment]
> Can I work on this issue since there have been no update since last 1 month?

Feel free to give it a go @Abhishek-569

**Comment by ReprogramAkash** [comment]
Is it still open for contribution? and if yes, can I work on this?

**Comment by Abhishek-569** [comment]
@ReprogramAkash if you want to we can collaborate on this.

**Comment by Abhishek-569** [comment]
Created this PR https://github.com/open-telemetry/opentelemetry-collector/pull/7314 for this issue.
