### ISSUE TITLE
Add examples and package documentation to the `configopaque` package.

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6855]
To make it easier for users to understand and use [the `configopaque` package](https://pkg.go.dev/go.opentelemetry.io/collector/config/configopaque), we should

- [ ] Add a [package-level comment](https://go.dev/doc/comment#package) explaining the rationale for using `configopaque` (see #5653 for details)
- [ ] Add a [testable example](https://go.dev/blog/examples) with a configuration struct with fields using `configopaque.String`, `[]configopaque.String` and/or `map[string]configopaque.String` and showcasing how it looks once marshaled.

**Comment by jackycsl** [comment]
Can you please assign me this issue? 
Thanks.

**Comment by mx-psi** [comment]
@jackycsl Consider it assigned and feel free to work on it :) (can't assign to you on the Github UI because you are not part of the OTel Github org, but that's not a problem, you can work on this!)
