### ISSUE TITLE
[ci] Add shellcheck linter

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6864]
[shellcheck](https://github.com/koalaman/shellcheck) is a static analysis tool for identifying issues on shell scripts. It's generally good for enforcing idiomatic and sensible shell scripts.

To ensure we continously lint our scripts with shellcheck, we should add a Github workflow that lints our shell scripts with shellcheck and fixes the issues pointed out by the command above.

See also open-telemetry/opentelemetry-collector-contrib/issues/17279 and open-telemetry/opentelemetry-collector-releases/issues/264 for similar issues on contrib and releases.

**Comment by noelukwa** [comment]
@mx-psi I want to give this a shot.

**Comment by mx-psi** [comment]
Assigned to you @noelukwa, thanks!

**Comment by pirgeo** [comment]
I guess this can be marked as done due to #6870 being merged, right?

**Comment by mx-psi** [comment]
Indeed, thanks for catching this @pirgeo, closing...
