### ISSUE TITLE
[config] configopaque discloses the length of the secret

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#6868]
**Describe the bug**
See https://github.com/open-telemetry/opentelemetry-collector/blob/e4e76dec22ecf8cf1d5b70af6d74215f0e05f0c0/config/configopaque/opaque.go#L27
`MarshalText marshals into a string of '*' of length equal to the opaque string.`

This inadvertently discloses the length of the secret. It should be of fixed length instead.

**Comment by mx-psi** [comment]
Looks like this was fixed by #6869
