### ISSUE TITLE
Add ability to pass MeterProvider, TraceProvider to otelcol.CollectorSettings

### ISSUE THREAD

**Issue by rfratto** [open-telemetry/opentelemetry-collector#6888]
grafana/agent imports OpenTelemetry Collector as a library, where it's possible to spawn many OpenTelemetry Collectors in-memory from the same process. 

Previously, this was done through a fork of OpenTelemetry Collector which exported all internal packages. As of v0.67.0, the internal APIs we were previously using were made completely internal (e.g., no longer exposed even at the package level), so we have to migrate to using the public APIs. 

As far as I can tell, the only thing we're missing is the ability to pass a custom MeterProvider and TraceProvider to the otelcol package (which would eventually get propagated to `service.Service`). We need to pass custom MeterProviders and TraceProviders to be able to distinguish which in-memory OpenTelemetry Collector component metrics are coming from. 

Would adding this capability be accepted so we can upgrade to the latest release? 

https://github.com/open-telemetry/opentelemetry-collector/blob/2fc6b0e893928647341f0f68b65d66a4673b1852/otelcol/collector.go#L64-L87

**Comment by mx-psi** [comment]
I think this is a duplicate of #4970. There was some work by @bogdandrutu on this and (I think!) the end goal is to have the pipelines from https://github.com/open-telemetry/opentelemetry-collector/blob/v0.68.0/service/pipelines.go be exposed for this kind of use case.

**Comment by rfratto** [comment]
Thanks! I'll close this in favor of #4970 and keep an eye on that.
