### ISSUE TITLE
k8s network and storage information should be added in the semconv

### ISSUE THREAD

**Issue by bhogayatakb** [open-telemetry/opentelemetry-collector#6943]
Current semantic conventions for k8s does not include Network & Storage resources like k8s.service, k8s.volume, k8s.persistentvolumeclaim, etc.

I suggest, they should be added in the semantic conventions so that components like "k8sclusterreceiver" can add the relevant data following the predefined standards.

**Comment by mx-psi** [comment]
The `semconv` module includes the semantic conventions defined by the OpenTelemetry specification. Kubernetes related semantic conventions are defined on [this document][1].

The package is generated automatically, so we won't be adding any of these manually if they are not part of the specification.

Could you open an issue on https://github.com/open-telemetry/opentelemetry-specification instead?

[1]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.16.0/specification/resource/semantic_conventions/k8s.md
