### ISSUE TITLE
Allow otlphttpexporter to export in JSON format

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#6945]
**Is your feature request related to a problem? Please describe.**

Currently the otlphttpexporter only supports exporting data in Binary Protobuf Encoding: https://github.com/open-telemetry/opentelemetry-collector/blob/f2a0133bf677b9fe2e18b7c02eb1b6bf5e849999/exporter/otlphttpexporter/otlp.go#L132
While the otlp spec and the otlp http receiver support both binary protobuf encoding and JSON encoding. It will be nice to be able to export telemetry data in JSON using the otlphttpexporter.

**Describe the solution you'd like**

Add a config to otlphttpexporter like:
```
exporters:
  otlphttp:
    ...
    encoding: [binary_protobuf | json]
```
And have the corresponding encoder in otlphttpexporter.

Feel free to mark this as duplicated if there's an existing issue on otlphttpexporter json support.

**Comment by bogdandrutu** [comment]
We want to discourage use of JSON between collectors (unnecessary overhead). We do accept receiving because JS libraries need that.

**Comment by vainiusd** [comment]
This was also mentioned in opentelemetry-collector-contrib [issue 10836](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10836).

It could be useful when sending logs to collectors that do not support OTLP.

**Comment by aubm** [comment]
Just to mention that I've been trying to send logs collected by the OpenTelemetry Collector to Logstash and it looks like support for Protobuf is limited and I can't get it working properly.

I've just opened an issue on the Github Logstash Protobuf codec plugin repository.
You can find all the details here: https://github.com/logstash-plugins/logstash-codec-protobuf/issues/70

At this point, if I don't find a way to make it work and I can't get otlphttpexporter to offer JSON encoding, which is well supported by Logstash, I'll have to implement my own exporter.
This is a bummer, and probably an obstacle for more people to adopt it as well.

Just give me the go and I'll submit a PR.

**Comment by atoulme** [comment]
You could try to use the splunkhec exporter in raw mode to push data over to logstash, that's not really meant for it but might get you what you need. If you can push a test showing the problems with logstash, I'm sure folks here can help on their end.

**Comment by aubm** [comment]
Hi @tvaintrob, I ended up starting working on a generic HTTP/JSON exporter.
I might submit a PR to contribute it back eventually if anyone is interested.

The solution suggested by @atoulme to use the splunkhec exporter was interesting, but I couldn't make it work (not sure I remember why exactly, it's been a couple months, but I think it still required me to provide a valid authentication to a splunk server, something like that).

**Comment by tvaintrob** [comment]
@aubm Thanks for the suggestion! I'll look into that, I also started working on it, I have a fork with the required changes

Hopefully we can push this to the upstream

**Comment by songy23** [comment]
Looks to me there are enough interests on the otlp http json exporter, I'll bring this up in today's collector SIG

**Comment by songy23** [comment]
Recap from today's SIG: exporting OTLP in http/json sounds a valid use case. The spec on SDKs JSON support says:
> SDKs SHOULD support both grpc and http/protobuf transports and MUST support at least one of them. If they support only one, it SHOULD be http/protobuf. They also MAY support http/json.

It may not be worth adding a new exporter e.g. `otlphttpjsonexporter`, but instead can add the JSON encoding to the current `otlphttpexporter`. The implementation should follow https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding, there are a few caveats there.

@aubm @tvaintrob would either of you be interested in taking this issue?

**Comment by aubm** [comment]
Thanks @songy23! I would be happy to take the ball. I can work on that this Friday afternoon EST

**Comment by songy23** [comment]
Appreciated @aubm!

**Comment by aubm** [comment]
Hey @tvaintrob, if you already did the work, feel free to open a PR, I hadn't started working on it yet myself.
Just let me know if you do plan on submitting it indeed, otherwise I had dedicated time for it tomorrow.

**Comment by tvaintrob** [comment]
@songy23 @aubm here is the PR, please let me know if any changes are needed

https://github.com/open-telemetry/opentelemetry-collector/pull/9276

**Comment by songy23** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/9276, thanks @tvaintrob
