### ISSUE TITLE
otlpreceiver: performance issue about otlpreceiver invoke proto.Size slow path

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector#6947]
**Describe the bug**
The otlpreceiver consume lots of cpu for `proto.Size`, marshal to buffer, get buffer size.
Here is the pprof: 
![image](https://user-images.githubusercontent.com/7621241/212468290-9d71a3e5-c070-44bd-b00c-0859a9eed509.png)
<img width="1858" alt="image" src="https://user-images.githubusercontent.com/7621241/212468377-b68b19f5-13f3-45fe-951a-84891ccbe4f8.png">
![image](https://user-images.githubusercontent.com/7621241/212468301-a93de6e3-37af-460b-b36c-e2cbe48108cd.png)
Code:
https://github.com/open-telemetry/opentelemetry-collector/blob/f2a0133bf677b9fe2e18b7c02eb1b6bf5e849999/config/configgrpc/configgrpc.go#L266-L267
**Steps to reproduce**
Run collector with otlp receiver.

**What did you expect to see?**
Use fast path to get size of proto message.
**What did you see instead?**
slow path to get size of proto message, marshal to buffer, get buffer size.

**What version did you use?**
v0.59.0

**What config did you use?**

**Environment**
OS: Linux 
Compiler: Go 1.19

**Additional context**

**Comment by gbbr** [comment]
Hi Jimmie!

I'm not sure familiar with this code, but maybe I can help? What is the fast path that you were thinking of? How should it work instead?

Also, is this the right repository for this issue? It seems like the problematic code lives in [open-telemetry/opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go), and the problematic call lives in [golang/protobuf](https://github.com/golang/protobuf/blob/v1.5.2/proto/wire.go#L13).

**Comment by hanjm** [comment]
hi @gbbr , thank your reply.
> What is the fast path that you were thinking of? How should it work instead?

I think it shoud try get size from asserting interface Size() int, then try to use proto.Size

> is this the right repository for this issue? 

opentelemetry-collector use gogoprotobuf, but opentelemetry-go-contrib use golang/profobuf.  it happens in otlpreceiver, so i create issue in this repository, I have open a issue to opentelemetry-go-contrib repository just now.

**Comment by gbbr** [comment]
> I think it shoud try get size from asserting interface Size() int, then try to use proto.Size

Thanks for clarifying. I think that makes sense. I would update the "What did you expect to see?" in the Description of the issue to say that.

**Comment by atoulme** [comment]
Is this fixed with https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3168?

**Comment by hanjm** [comment]
fixed. close it .
