### ISSUE TITLE
[confmap] Decide on how/whether to allow to configure confmap providers

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#6956]
**Is your feature request related to a problem? Please describe.**

In both #6683 and open-telemetry/opentelemetry-collector-contrib/pull/14897 there are use cases where confmap providers need to have some sort of configuration passed to them. 

Currently, while not explicitly enforced by an interface it is assumed that all providers have a constructor with signature `func New() confmap.Provider` that does not allow configuring it in any way.

**Describe the solution you'd like**

Define a way to configure providers or decide that we are not going to support this. My preferred way of doing this for global settings would be to allow passing a `Config` struct to the `New` builder that is populated from CLI flags (example on this comment https://github.com/open-telemetry/opentelemetry-collector/pull/6683#pullrequestreview-1209945033). We would need to figure out a way to namespace the CLI flags.

**Describe alternatives you've considered**

An alternative is to pass this in the URI (see https://github.com/open-telemetry/opentelemetry-collector/pull/6683#discussion_r1057820092) and handle specific configuration on each `Retrieve` call. This has the following implications:
- We don't support configuration of providers in any special way: it is up to the individual providers to implement URI parsing however they want.
- We risk a lack of consistency among providers; it may also be the case that any strategy that we generally recommend (e.g. URL fragments in the case of the httpsprovider) is not really doable in some other provider.
- It seems like a less comfortable option when dealing with the Go API directly (e.g. building a downstream distro).
- We delay building the struct that fetches the configuration until a `Retrieve` call happens. This may have performance implications.

---

cc @Aneurysm9 @rapphil @neelayu

**Comment by rapphil** [comment]
Here is the proposal to use url fragments. https://github.com/open-telemetry/opentelemetry-collector/issues/6892

**Comment by Aneurysm9** [comment]
A concern I would have with passing a `Config` struct extracted from CLI args is that there would be no way to have differing configurations for different configuration locations.  Changing the cert pool or validation settings for the HTTP provider would apply to all HTTP-based configurations and not allow having some not perform cert validation or use a specific cert pool.  A similar issue might arise with S3 or other AWS resources providing configuration where it might be necessary to provide a distinct role to assume to access different resources.

**Comment by bogdandrutu** [comment]
>Define a way to configure providers or decide that we are not going to support this. My preferred way of doing this for global settings would be to allow passing a Config struct to the New builder that is populated from CLI flags (example on this comment https://github.com/open-telemetry/opentelemetry-collector/pull/6683#pullrequestreview-1209945033). We would need to figure out a way to namespace the CLI flags.

The other problem with this proposal is that the "URI" like configs are also embedded into the config (not only provided via CLI flags, where is that config coming from in that case)?

**Comment by mx-psi** [comment]
Per last week's Collector SIG we can close this as wontfix, we decided that the way to support this will be by passing configuration as URI fragments.
