### ISSUE TITLE
Allow the Collector to use the kubernetes service account jwt to authenticate to external receivers 

### ISSUE THREAD

**Issue by EStork09** [open-telemetry/opentelemetry-collector#6987]
**Is your feature request related to a problem? Please describe.**
We are looking to setup oidc auth from multiple collectors to a central collector and don't want to setup an oidc issuer.

**Describe the solution you'd like**
All of our clusters are setup in kubernetes and we have the service account issuer discovery enabled, is there a way to allow the collector agent to read the projected volume that contains the jwt token to perform the auth so we don't have to rely on an external oidc issuer?

**Describe alternatives you've considered**
We can just setup an oidc issuer

**Comment by jpkrohling** [comment]
It's so weird that Kubernetes can't provide an OIDC endpoint for us to get the public key for the tokens generated by it... Anyway, I can think of a couple of solutions, but those require the same contents to be used by both the server and the client side of the connection. Inevitably, the client will end up sending a token that is not in sync with the server: either because it's using a new token not seen yet by the server, or vice-versa. The cleanest solution is indeed to use a proper OIDC issuer.

**Comment by EStork09** [comment]
The oidc endpoint for k8s get's placed on the kube-apiservers, which other solutions will proxy (i.e. eks they appear to throw it into an s3 bucket, and provide docs on how to do it for non-eks clusters [here](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md)) then you project the volume into the pods. But similarly AWS will just reachout to your endpoint to validate the jwt with the jwks at your proxy endpoint. In this case it appears the collector can do that on a receive of just looking at the issuer info and audience, but when exporting it requires the client secret, my ask is if the collector could reference the projected volume instead of requiring the client secret and such since that should be updated by k8s itself. If this makes any sense.

**Comment by jpkrohling** [comment]
> since that should be updated by k8s itself

If we decide to go this route, and I'm not convinced we should, I believe we will end up with the situation I mentioned earlier. Or perhaps there's something I'm still missing?

> Inevitably, the client will end up sending a token that is not in sync with the server

**Comment by EStork09** [comment]
Sorry for delay on this. I think that is the point of the projected volumes, so they JWT is always up to date.
https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken

I don't think that I would be so worried about the client sending an invalid token that isn't in sync from the server. I could easily be missing something but if the clients are sending invalid JWT tokens then all of AWS implementation requiring this would be not working after the first few hours and I have not experienced that issue.

If I get some cycles I can try to mock it up and test it out, this could easily not be something that gets added, it just would reduce the requirement to add another oidc provider if we could leverage the built in k8s oidc providers. I am just a big fan of reducing down the client requirements to get a JWT token if we could leverage existing tokens.

**Comment by jpkrohling** [comment]
It just occurred to me: are you talking about using those tokens on the client side? The "receiver" on the title made me believe you would be accepting a token and you want to compare with a static token that is mounted on a volume, but perhaps you are talking about reading the token from a volume and using it when making calls to an external service? In that case, I'm with you. But wouldn't the bearer token auth with a local file as the token source work in your case?

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/bearertokenauthextension

**Comment by EStork09** [comment]
Yes, I apologize, I think using the local file should work, I'll have to play with it, I must have missed the option. The other piece to the puzzle is that on the actual receiver side, it looks like we can only have on auth option per endpoint per the example [provided](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oidcauthextension). There is no way to be able to allow that to support multiple issuers for one endpoint? Would we either have to handle the auth at another layer like an oauth2-proxy that can trust multiple issuers or have multiple ports for otel recieve but with each having a different oidc authenticator issues setup?

**Comment by jpkrohling** [comment]
You could also have your authentication extension that supports multiple issuers.

**Comment by EStork09** [comment]
So maybe I am just dumb or missing something, but as an example I don't know of any authentication extensions that support the idea of multiple providers for one end point.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oidcauthextension
```
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    issuer_ca_path: /etc/pki/tls/cert.pem
    audience: account
    username_claim: email

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: oidc
```

I don't believe there is any notion on receivers to allow a list of authenticators or any authentication extensions that would allow for a list to be applied to check against.

This might be getting a bit out of scope but right now I have a number of kubernetes clusters that ideally I would like to allow them to use their JWTs to be able to securely send data to a central collector, so this would be the last piece to allow a collector to recieve the auth from many different oidc providers.

**Comment by jpkrohling** [comment]
You are absolutely right that we don't currently have an auth extension that allows multiple issuer URLs. We currently rely on github.com/coreos/go-oidc, which seems to use only one [isuer URL per provider](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/69971b73de0d0d1665468bef4bfb6f796a90c23c/extension/oidcauthextension/extension.go#L215). There seems to be an option to have multiple verifiers, [each one with its own issuer](https://github.com/coreos/go-oidc/blob/921a42b4b63d5b618d17d7e7a36a4acb59e643c6/oidc/verify.go#L74), but we don't seem to be making use of that.

The problem that I see with multiple verifiers is that we (currently) have no way of knowing which verifier to use for each request. We'd have to do a trial-and-error approach, which might not be acceptable for high-volume receivers.

Do you happen to know how would your solution look like if you were to use an oauth proxy in front of the collector?

**Comment by EStork09** [comment]
Sorry for the delay on this. I haven't dug too deep into this to see if there is a clean way to do it (something like include a header or something simple to determine which provider to look at before having to do the trial and error).

The Oauth2 Proxy project has been working on this for a long while. [#926](https://github.com/oauth2-proxy/oauth2-proxy/issues/926) I would probably wait for this to do a thing, I just want to get ahead of the inevitable, in the mean time I think I will probably just lean on a basic auth concept to keep things simple until something gets figured out.

Do we want to keep this open? I can open a new issue to track having multiple oidc providers on the oidc receiver, or just rename this issue. I don't 100% think that this would be solved by the otel collector itself, but it would be neat.

**Comment by jpkrohling** [comment]
I think I'll prefer a new issue, with a clear description of the problem as understood now. I'm closing this, feel free to open the new one and ping me there.
