### ISSUE TITLE
Error when using service discovery in prometheusreceiver with metadata cache

### ISSUE THREAD

**Issue by olagacek** [open-telemetry/opentelemetry-collector#709]
I was trying out Kubernetes Service Discovery in Open Telemetry prometheus receiver, and while it did discovered pods correctly and scraped them it failed to append the metrics, with following error:

{"level":"info","ts":1585146576.7671049,"caller":"scrape/scrape.go:1190","msg":"","level":"debug","scrape_pool":"jvm","target":"http://10.4.1.7:8090/metrics","msg":"unexpected error","series":"jmx_config_reload_success_total","err":"unable to find a target with job=sd_k, and instance=10.4.1.7:8090"}

It seems that error is coming from this line: https://github.com/open-telemetry/opentelemetry-collector/blob/master/receiver/prometheusreceiver/internal/metadata.go#L53

I noticed that in this line model.Address discovered label  is used, while I think model.Instance label should be used instead.

I validated, that with this fix both static target and dynamic service discovery works as expected.

**Comment by bogdandrutu** [comment]
@nilebox is this issue closed? If yes please close it since you have the power :)

**Comment by nilebox** [comment]
The issue was fixed in #843
