### ISSUE TITLE
Investigate alternative for `Unmarshaler` and `Marshaler`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#7101]
The `Unmarshaler` because of the `Unmarshal` definition, has an issue when recursively unmarshal other structs that implement the `Unmarshaler`, see https://github.com/open-telemetry/opentelemetry-collector/pull/6029 where the "given" destination to Conf.Unmarshal cannot be checked against the Unmarshaler implementation to avoid a deadlock. The Marshaler seem to not have (I did not carefully check) the same problem, but this needs to be confirmed.

Some possible solutions:
* See yaml.v2 interfaces, they seem to work fine. We may want to switch to that.
* Ignore this issue, document properly in the Conf.Unmarshal the caveat.

**Comment by mx-psi** [comment]
#9750 would remove this caveat from `Conf.Unmarshal`, solving this.
