### ISSUE TITLE
Remove expandconverter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#7111]
Need to investigate if the current expand providers logic in the [`confmap.Resolver`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/confmap/resolver.go#L168) has all the equivalent functionality. Then we also need to propose some kind of deprecation process: e.g. disable by default via a featuregate; or other alternatives.

One caveat that I know and need to document is that because of this we have a workaround in prometheus receiver see the note [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver#getting-started). Once this is disable that is no longer necessary which is a good thing, but may break some users so we need to find a way to handle/communicate that.

**Comment by mx-psi** [comment]
> but may break some users so we need to find a way to handle/communicate that.

We may want to have some sort of subcommand/flag/separate tool to migrate a config from the old syntax to the new one. This could be useful for other future changes in the configuration (whether breaking or just recommendations). If that sounds like a good idea, should we create a separate issue to discuss how to go about it?

**Comment by bogdandrutu** [comment]
Let's start that issue. We definitely need it. I think the best we can do is to have it as a subcommand but this is just me prematurely commenting 👯

**Comment by mx-psi** [comment]
See #7631 :)

**Comment by mx-psi** [comment]
Per https://github.com/open-telemetry/opentelemetry-collector/issues/8215#issuecomment-1865028717 before doing this we need to add support for `${...}` to the provider, to align with https://github.com/open-telemetry/opentelemetry-specification/pull/3744
