### ISSUE TITLE
Use Go 1.19 `sync/atomic` wrappers instead of `go.uber.org/atomic`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#7160]
Go 1.19 includes new builtin [atomic wrappers](https://go.dev/doc/go1.19#atomic_types) that can replace the usage of `go.uber.org/atomic`. We should switch to using these and ban the usage of `go.uber.org/atomic` via `depguard` (basically, inverting [this](https://github.com/open-telemetry/opentelemetry-collector/blob/6e6597eb24f5b838b929c18165d207c0dc1f2b53/.golangci.yml#L107)).

This was **blocked by** #7159

**Comment by mx-psi** [comment]
This is now unblocked

**Comment by patil-kshitij** [comment]
Can I please take ownership for this ?

**Comment by mx-psi** [comment]
@patil-kshitij all yours :)

**Comment by patil-kshitij** [comment]
PR for this issue is raised.

https://github.com/open-telemetry/opentelemetry-collector/pull/7220

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/7220
