### ISSUE TITLE
Track @songy23 interest and contributions for approver

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#7271]
This is an issue to track my (@songy23) contributions to the collector repo and track when I meet the requirements to (re-)become approver. I am interested and have time commitment to contribute to the collector repo.

#### Core repo
![Screenshot 2023-03-01 at 10 54 03 AM](https://user-images.githubusercontent.com/10536136/222192821-ec4997bb-48dd-4ea5-b43a-af11eafabf68.png)

- [76 commits](https://github.com/open-telemetry/opentelemetry-collector/commits?author=songy23)
- [9 issues](https://github.com/open-telemetry/opentelemetry-collector/issues?q=+is%3Aissue+author%3Asongy23)
- [27 PRs authored](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=+is%3Apr+author%3Asongy23)
- [194 PRs reviewed](https://github.com/open-telemetry/opentelemetry-collector/pulls?q=+is%3Apr+reviewed-by%3Asongy23+)

#### Contrib repo
![Screenshot 2023-03-01 at 10 59 09 AM](https://user-images.githubusercontent.com/10536136/222193620-731f5625-5dca-4e7a-a0da-1d66469a4944.png)

- [106 commits](https://github.com/open-telemetry/opentelemetry-collector-contrib/commits?author=songy23)
- [5 issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=+is%3Aissue+author%3Asongy23)
- [26 PRs authored](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=+is%3Apr+author%3Asongy23)
- [26 PRs reviewed](https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=+is%3Apr+reviewed-by%3Asongy23+)

#### Emeritus Approver

I'm listed under the [Emeritus Approvers in the collector repo](https://github.com/open-telemetry/opentelemetry-collector#contributing), and am following this section: https://github.com/open-telemetry/community/blob/main/community-membership.md#emeritus-maintainerapprovertriager:

> When a contributor returns to being more active, they may be promoted back to a their previous position at the discretion of the current maintainers following the process defined above.

**Comment by bogdandrutu** [comment]
@songy23 thanks for your interest. Looking forward to see you back as approver :)

**Comment by songy23** [comment]
cc @open-telemetry/collector-approvers would love to hear your opinions since we are calling for approvers now :)
