### ISSUE TITLE
[processor] Add config for processor to enable/disable

### ISSUE THREAD

**Issue by yehaotian** [open-telemetry/opentelemetry-collector#7297]
### Component(s)

General processors or just tail sampling processor for now.

### Is your feature request related to a problem? Please describe.

For different environment we may or may not need specific processor.
For example, in production env we want to have tail sampling processor but not for some test env. Since we are using the same template for all env, it is good to have enable/disable config for such flexibility.

### Describe the solution you'd like

Have enable/disable configuration for processors so that we can choose if need to skip for different environment.

```
tail_sampling:
    enable_processor: ${should_enable_processor}  # could be bool or other identifier   
```

**Comment by yehaotian** [comment]
The configuration sources is not quite straightforward to me, especially we are using terraform and nomad for deployment.
The otel collector yaml template contains all config we need with some placeholder/variables for different env settings, having other yaml/env files for this one will make things too complicated IMO

**Comment by bogdandrutu** [comment]
Also, we don't intend (unless a very strong argument, or lots of users are asking) to add enable/disable to processors since you can control that via the presence in a pipeline or not.

**Comment by yehaotian** [comment]
Interesting, we are using ${} for other configurable variables, not realizing this can be applied to the pipleline, will give it a try

**Comment by atoulme** [comment]
Closing this ticket as complete, please reopen if more work is needed.
