### ISSUE TITLE
HTTPServerSettings: Support for additional headers

### ISSUE THREAD

**Issue by ledor473** [open-telemetry/opentelemetry-collector#7328]
**Is your feature request related to a problem? Please describe.**
When deploying an OpenTelemetry Collector with `httpforwarder` or `healthcheckextension` behind a caching proxy or a CDN, the GET requests gets cached and there's currently no options to pass additional headers on HTTPServerSettings.  

Here are some links for various caching proxy that documents the headers that can be used to configure the cache behavior:
- https://www.varnish-software.com/developers/tutorials/http-caching-basics/
- https://docs.fastly.com/en/guides/caching-best-practices#cache-control-headers
- https://www.nginx.com/blog/nginx-caching-guide/

**Describe the solution you'd like**
Add a `headers` configuration to HTTPServerSettings. 
  
It would be similar to the `headers` property on HTTPClientSettings:
https://github.com/open-telemetry/opentelemetry-collector/blob/687d5b77926f55d2f8e20eddd3f184f5434dc5c3/config/confighttp/confighttp.go#L57-L60

**Describe alternatives you've considered**
I've looked at CORSSettings that is exposed but it only exposes `MaxAge` that ends up in Access-Control-Max-Age

**Comment by atoulme** [comment]
@ledor473 would you like to work on this issue? I'd be happy to assign it to you.

**Comment by ledor473** [comment]
If the proposal makes sense, I'd be happy to contribute it yes.

**Comment by atoulme** [comment]
not sure, you can bring it to the SIG meeting for discussion or open a PR to provoke thoughts.

**Comment by atoulme** [comment]
@ledor473 ready to close? This was shipped in 0.81.0.

**Comment by ledor473** [comment]
Yep! I thought it would auto-close. Closing..

**Comment by atoulme** [comment]
It closes only if in the PR you use the keyword `Fixes`, as in `Fixes #foo`
