### ISSUE TITLE
Alternative method to configure NO_WINDOWS_SERVICE

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#7350]
**Is your feature request related to a problem? Please describe.**
The collector uses an environment variable `NO_WINDOWS_SERVICE` to regulate its behavior on Windows. By default, the collector will run as a windows service. This environment variable disables the behavior.
However, we operate in environments where we cannot set environment variables.

**Describe the solution you'd like**
We need an alternate way to set this flag, either as command line argument, configuration switch, or other mean.

**Describe alternatives you've considered**
N/A

**Additional context**
See https://github.com/signalfx/splunk-otel-collector/issues/2643 for original issue.

**Comment by mx-psi** [comment]
Tagging as builder since this behavior is dealt with in the builder https://github.com/open-telemetry/opentelemetry-collector/blob/v0.73.0/cmd/builder/internal/builder/templates/main_windows.go.tmpl#L30

**Comment by atoulme** [comment]
Thanks!

I am investigating if we could use [godotenv](https://github.com/joho/godotenv) to satisfy this need. Does anyone have reservations with using [godotenv](https://github.com/joho/godotenv)?

**Comment by bogdandrutu** [comment]
Alternative would be to have different binaries?

**Comment by mx-psi** [comment]
I like the different binaries option more, more complicated behavior can be built on top of the binaries. This would be a breaking change, so I think we would need a deprecation plan

**Comment by bogdandrutu** [comment]
> Would we have a different binary for Windows only to run the collector as service?

yes, is this common in windows world?

**Comment by atoulme** [comment]
In the Windows world, it seems to be equally as common to run as a service or interactive. You'll need both.

**Comment by cwegener** [comment]
> yes, is this common in windows world?

No.
