### ISSUE TITLE
Is opentelemetry-collector multi arch supported ?

### ISSUE THREAD

**Issue by LAVA-KUMAR** [open-telemetry/opentelemetry-collector#7391]
I was able to run on amd machines but not on arm64. Can anyone confirm that is it multi arch supported(arm,amd)? 
if it is multi arch supported , can you please tell that from what version it is multi arch supported ?

FYI: I built image using buildx by passing following platform params: --platform linux/arm64 , linux/amd64

**Comment by codeboten** [comment]
The released packages of the collector supports arm64 and amd64: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.73.0

Does that answer your question?

**Comment by atoulme** [comment]
Closed as answered. See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md for more information.
