### ISSUE TITLE
Unscoped yaml unmarshal cause config provider to fail

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector#7399]
**Describe the bug**
A small subset of our deployments of the collector were failing with the error:

```
2023/03/20 04:48:16 collector server run finished with error: failed to get config: cannot resolve the configuration: unsupported type=time.Time for retrieved config
```

This meant that these subset of deployments were failing to start repeatedly.

**Steps to reproduce**

1. Make yourself config that contains time formatted string (a string not formatted in quotes):
2. Start the collector
3. Watch the collector fail with the same error 

**What did you expect to see?**

In an ideal world, this should haven't occurred, and should let the collector run.

**What did you see instead?**
Added in the description with failing to start.

**What version did you use?**
Version: v0.73.0

**What config did you use?**
```yaml
---
receivers:
  nop: 
     misc: 2002-12-14
```

**Environment**
OS: linux
Compiler(if manually compiled): 1.20.2

**Additional context**

I've managed to do some sluething into the reasoning why this happened:

The error happens within the `ConfigProvider` on collector start up, using the URI scheme of `file` performs loading of bytes, then delegate do the `yamlprovider`, which then calls an internal function:

https://github.com/open-telemetry/opentelemetry-collector/blob/v0.73.0/confmap/provider/internal/provider.go#L26

However, since the unmarshalled type is `any`, it means that "[gopkg.in/yaml.v3](http://gopkg.in/yaml.v3)" can infer what strings are meant to represent so we it ends up within this check [parseTimestamp](https://github.com/go-yaml/yaml/blob/f6f7691b1fdeb513f56608cd2c32c51f8194bf51/resolve.go#L306) if the string pattern matches: [yaml timestamp spec](https://yaml.org/type/timestamp.html) as shown here [example playground](https://go.dev/play/p/d-KSG4oOK1k)

It appears if you wrap the value in quotes it resolve the problem as a work around.

**Comment by mx-psi** [comment]
I am not sure we can do much here, this sounds to me like a "YAML spec has some unexpected features" more than something Collector-specific. If there are components where one needs to pass these kinds of strings frequently it may be worth documenting the need for explicit quotes, otherwise I don't think we can/should do much.

**Comment by MovieStoreGuy** [comment]
Having thought on it more, I think the best way to address this would be to improve the error message returns since it isn't obvious as a user how `time.Time` isn't supported but if it were to return an error of the likes of "Field converted to an unsupported type %T, ensure fields are quoted to resolve this issue".

Conversely, I wonder on `time.Time` we could just return the string to avoid this in future?

**Comment by mx-psi** [comment]
> Having thought on it more, I think the best way to address this would be to improve the error message returns since it isn't obvious as a user how `time.Time` isn't supported but if it were to return an error of the likes of "Field converted to an unsupported type %T, ensure fields are quoted to resolve this issue".

Improving error messages makes sense to me

> Conversely, I wonder on `time.Time` we could just return the string to avoid this in future?

I don't think we should modify the YAML parser behavior, since AFAICT this seems to be part of the YAML spec
