### ISSUE TITLE
Test: add obsreport test support for components

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#741]
This should be supplied so components can check if they are generating the proper observability data. This will avoid trivial mistakes like using the wrong methods for a given component.

The mistake risk can also be reduced by changing the `obsreport` interfaces. Either by having strong types on the interfaces per component and data type or by splitting it in packages per component and data type. Either way test helpers are valuable in both cases.

**Comment by bogdandrutu** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/1299
