### ISSUE TITLE
Send metrics data in JSON format to Collector

### ISSUE THREAD

**Issue by w00ski** [open-telemetry/opentelemetry-collector#7433]
**Describe the bug**
Assume that I already have the metrics values and timestamps and I want to add them manually in the collector. I did not find any example for my use case, but from what I discovered from the documentation it should be possible to do. I have reached this format until now:
`{ "resourceMetrics": [ { "resource": { "attributes": [{ "key": "attr_key", "stringValue": "attr_value" }] }, "scopeMetrics": [ { "scope": { "name": "metrics_scope", "version": "4.2.0", "attributes": [] }, "metrics": [ { "name": "metric_1", "description": "metric_1 description string", "unit": "1", "gauge": { "dataPoints": [ { "attributes": [], "timeUnixNano": 1679912468340000000, "asDouble": 5.66 }, { "attributes": [], "timeUnixNano": 1679912463340000000, "asDouble": 10.66 } ] } }, { "name": "metric_2", "description": "metric_2 description string", "unit": "1", "gauge": { "dataPoints": [ { "attributes": [], "timeUnixNano": 1679912468340000000, "asDouble": 3.33 }, { "attributes": [], "timeUnixNano": 1679912463340000000, "asDouble": 6.33 } ] } } ] } ] } ] } `
But when sending this through a POST request with curl (content type set to application/json), it returns "partialSuccess" and only the last value is visible in the Prometheus graph, at the time of the request was sent, not at the time specified in "timeUnixNano".

**What did you expect to see?**
All the points added correctly with the specified timestamp.

**Configuration**
I am using this example, running it in docker:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo

With 2 small modifications:

1. Added `- "4318:4318"   # OTLP http receiver` in [docker-compose.yaml(line 32)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/docker-compose.yaml#L32)

2. Added `http:` in [otel-collector-config.yaml(line 4)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/otel-collector-config.yaml#L4)

Sending the requests on port 4318.

**Comment by atoulme** [comment]
`timeUnixNano` is serialized as a string. See here for an example: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/file-exporter.md

Please try it out and let us know.

**Comment by atoulme** [comment]
I haven't heard back ; I assume my earlier comment helped. Please comment, reopen the issue or open a new issue if the issue persists.
