### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by Praveena23-2003** [open-telemetry/opentelemetry-collector#7458]
**Describe the bug**
>/kind enhancement
**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

**Comment by mx-psi** [comment]
This looks like it was accidentally opened, since there are no fields filled in. Closing as wontfix
