### ISSUE TITLE
Add ability to export components when generating components.go

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#7462]
**Is your feature request related to a problem? Please describe.**
I need to export components so other modules can rely on the list.

**Describe the solution you'd like**
Add a config flag so it's possible to export components.

**Comment by jpkrohling** [comment]
Can you expand a bit on your use case? Where do you need it? Do you need it from the core/contrib, or do you need it from custom distributions?

**Comment by atoulme** [comment]
For contrib to get the components list from the otelcontribcol package to configschema package.

I mentioned it during the SIG meeting 2 weeks ago or so. I now believe there is probably a better solution.
