### ISSUE TITLE
Should in-memory QueuedRetry exporter helper use requeuingEnabled=true?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#7480]
Retry exporter helper does not have `requeuingEnabled=true` when in-memory queue is used. This results in data being dropped after after 5mins of retries (in default configuration).

What are the reasons why we think this is the right setting for the persistent queue but a wrong setting for the in-memory queue?

**Comment by dmitryax** [comment]
I'm not sure about the necessity of this option. If the backend is unavailable for a long time, the collector will be blocked and memory will never be freed. Maybe we should better propose what's being implemented in https://github.com/open-telemetry/opentelemetry-collector/pull/7098 instead?

**Comment by tigrannajaryan** [comment]
I rephrased this as a question rather then a bug.

**Comment by dmitryax** [comment]
As part of https://github.com/open-telemetry/opentelemetry-collector/issues/8382, the decision was made to remove the re-enquiring capability and rely on the back-off retry mechanism only. So the issue is not relevant anymore.
