### ISSUE TITLE
Batch processor: support zero timeout (split only)

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector#7508]
**Is your feature request related to a problem? Please describe.**
I have an application where it would be nice to limit requests without introducing delay. The batchprocessor contains exactly the code necessary, but the configuration with zero timeout and/or zero SendBatchSize does not work correctly. 

**Describe the solution you'd like**
It is relatively easy to fix this. When `timeout` is zero, no timer is needed and all requests are sent immediately. In this configuration, only the `send_batch_max_size` configuration matters and (I propose) `send_batch_size` should be ignored.

**Describe alternatives you've considered**
Make it an error if `send_batch_size != 1` when `timeout == 0`, since if the timeout is zero there the minimum batch size is irrelevant.

I think we should not send an empty batch just because `send_batch_size` is set to zero.

**Comment by dmitryax** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector/pull/7509
