### ISSUE TITLE
docked image naming and tagging

### ISSUE THREAD

**Issue by naseemkullah** [open-telemetry/opentelemetry-collector#751]
https://hub.docker.com/u/otel

IMHO The prepending `opentelemetry-` seems redundant since the repo is named `otel`.

Furthermore could there simply be a collector image with various tags: e.g. dev, contrib, contrib-dev, stable or are they really different and require different images altogether?

**Comment by tigrannajaryan** [comment]
> https://hub.docker.com/u/otel
> 
> IMHO The prepending `opentelemetry-` seems redundant since the repo is named `otel`.

This repo is named `opentelemetry-collector`. It is not quite clear what your proposal is.

> Furthermore could there simply be a collector image with various tags: e.g. dev, contrib, contrib-dev, stable or are they really different and require different images altogether?

Yes, they are different. `dev` is from master build. `stable` is the releases. `contrib` is from https://github.com/open-telemetry/opentelemetry-collector-contrib/ repo.

**Comment by naseemkullah** [comment]
> > https://hub.docker.com/u/otel
> > IMHO The prepending `opentelemetry-` seems redundant since the repo is named `otel`.
> 
> This repo is named `opentelemetry-collector`. It is not quite clear what your proposal is.
> 

That the image be `otel/collector:stable` instead of `otel/opentelemetry-collector:stable` ,
but by that logic this repo should be `opentelemetry/collector` rather than `opentelemetry/opentelemetry-collector` so 🤷‍♂️ 

> > Furthermore could there simply be a collector image with various tags: e.g. dev, contrib, contrib-dev, stable or are they really different and require different images altogether?
> 
> Yes, they are different. `dev` is from master build. `stable` is the releases. `contrib` is from https://github.com/open-telemetry/opentelemetry-collector-contrib/ repo.

could then `dev` and `stable` just be image tags of the same image? i.e. `otel/(opentelemetry-)collector:dev` and `otel/(opentelemetry-)collector:stable` ?

**Comment by atrauzzi** [comment]
I don't know about you guys, but `otel` as the organization name is flat out confusing and not even slightly discoverable.

The docker image based on this repo should be one of:
 - `opentelemetry/collector`
 - `opentelemetry/opentelemetry-collector`

This scheme works for countless other organizations. `otel` is just way too inside-baseball to assume people are going to know to search **and** recognize it as an official source.  At a glance, it earns no legitimacy and serves no purpose to obscure what's typically interpreted as the organization portion of the image name.

**Comment by tigrannajaryan** [comment]
> > > https://hub.docker.com/u/otel
> > > IMHO The prepending `opentelemetry-` seems redundant since the repo is named `otel`.
> > 
> > 
> > This repo is named `opentelemetry-collector`. It is not quite clear what your proposal is.
> 
> That the image be `otel/collector:stable` instead of `otel/opentelemetry-collector:stable` ,
> but by that logic this repo should be `opentelemetry/collector` rather than `opentelemetry/opentelemetry-collector` so 🤷‍♂️
> 
> > > Furthermore could there simply be a collector image with various tags: e.g. dev, contrib, contrib-dev, stable or are they really different and require different images altogether?
> > 
> > 
> > Yes, they are different. `dev` is from master build. `stable` is the releases. `contrib` is from https://github.com/open-telemetry/opentelemetry-collector-contrib/ repo.
> 
> could then `dev` and `stable` just be image tags of the same image? i.e. `otel/(opentelemetry-)collector:dev` and `otel/(opentelemetry-)collector:stable` ?

@dmitryax @owais any thoughts on what would be best practices for naming Dockerhub images?

**Comment by tigrannajaryan** [comment]
> I don't know about you guys, but `otel` as the organization name is flat out confusing and not even slightly discoverable.
> 
> The docker image based on this repo should be one of:
> 
>     * `opentelemetry/collector`
> 
>     * `opentelemetry/opentelemetry-collector`
> 
> 
> This scheme works for countless other organizations. `otel` is just way too inside-baseball to assume people are going to know to search **and** recognize it as an official source. It's like putting your nickname on a government form: At a glance, it earns no legitimacy and serves no purpose but to obscure what's typically interpreted as the organization portion of the image name.

@atrauzzi `opentelemetry` Dockerhub organization is not available. See previous discussion  https://github.com/open-telemetry/community/issues/164

**Comment by owais** [comment]
I think the docker image should contain the full name because the org is named `otel` so having opentelemetry in the name helps. Also contributors and users often build images from the repo and use them somewhere without uploading to docker hub. Having such images named just `collector` doesn't help. I don't have any strong opinion about the docker hub org name but I think container images should definitely continue to be `opentelemetry-collector*`

**Comment by tigrannajaryan** [comment]
Closing as it appears there is nothing to do. Feel free to reopen if you have further comments.
