### ISSUE TITLE
Allow users to specify a path prefix for OTLP HTTP receiver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#7511]
When running the OTLP receiver behind a regular proxy or gateway, it's often easier to have consistent URLs between the proxy and the backend (OTLP receiver, in this case). Typically, those proxies would be used for multiple backends, each one under a specific path prefix. For instance, `/otlp` would be used by the proxy to pick the collector with the OTLP HTTP receiver at the backend. In practice this means URLs like `https://proxy.example.com/otlp/v1/traces`.

To make it easier to configure an environment like that, I would like to propose a new configuration option, allowing users to specify a path prefix for the OTLP HTTP receiver, likely in the following places:

https://github.com/open-telemetry/opentelemetry-collector/blob/7c982345763f963f9fecf65423096b18890696e6/receiver/otlpreceiver/otlp.go#L203

https://github.com/open-telemetry/opentelemetry-collector/blob/7c982345763f963f9fecf65423096b18890696e6/receiver/otlpreceiver/otlp.go#L228

https://github.com/open-telemetry/opentelemetry-collector/blob/7c982345763f963f9fecf65423096b18890696e6/receiver/otlpreceiver/otlp.go#L253

**Comment by fredthomsen** [comment]
Interested in this due to issues with the current operator ingress implementation as mentioned here: https://github.com/open-telemetry/opentelemetry-operator/issues/902#issuecomment-1330819117.  This is something we need, and could take it on now if no one is working on it yet.

**Comment by bogdandrutu** [comment]
I would like this to be somehow consistent with exporter options, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/config.go#L26?
