### ISSUE TITLE
support for reading in JSON files

### ISSUE THREAD

**Issue by savishy** [open-telemetry/opentelemetry-collector#7515]
**Is your feature request related to a problem? Please describe.**

This feature request adds support for reading in JSON files in `fileprovider`.

As of `0.73.0`, `fileprovider` assumes that the passed-in file is YAML. See [link to code.](https://github.com/open-telemetry/opentelemetry-collector/blob/release/v0.73.x/confmap/provider/fileprovider/provider.go#L62)

This poses a problem when configuration is managed via systems that pass in configuration in other formats (specifically JSON). 

**Describe the solution you'd like**

I'd like the `fileprovider` code to be able to unmarshal JSON as well as YAML based on the file extension. 

In such a scenario, users would be able to provide either the entire configuration as a JSON file, or parts of it as shown (example for the `service` field)

```
service: ${file://path/to/service/config.json}
```

**Describe alternatives you've considered**

None so far.

**Additional context**

I have reviewed the code and locally modified it to add JSON file support. I am willing to contribute a PR.

**Comment by mx-psi** [comment]
For the most part, all valid JSON is also valid YAML (see [here](https://stackoverflow.com/a/21585224) for the very minor differences), so unless running into an edge cases you should be able to uses the existing file provider to load a JSON file.

**Comment by savishy** [comment]
@mx-psi , 

Here's the line 

```
	return internal.NewRetrievedFromYAML(content)
```

which basically does `yaml.Unmarshal` - [link](https://github.com/open-telemetry/opentelemetry-collector/blob/883433989aa5287ba0948bb5c8f1f31fb8879c61/confmap/provider/internal/provider.go#L26-L32).

Unless I'm mistaken, `yaml.Unmarshal` would not handle a JSON file right?

**Comment by mx-psi** [comment]
@savishy Yes, `yaml.Unmarshal` does handle JSON files; see [here](https://go.dev/play/p/JK9ibSjT_fd) for a simple example using the function to parse a JSON object. The latest YAML spec is built with JSON compatibility in mind. You can try it out yourself by giving the Collector configuration as a JSON file :)

As I said above, strictly speaking there are some edge cases where valid JSON files won't be accepted by a YAML v1.2 compliant parser (e.g. if you have *very* long keys in your JSON objects), but those are unlikely to happen in practice.

**Comment by savishy** [comment]
Whoa! Somehow I assumed `yaml` libraries would only handle YAML :-) I just tried it myself and was surprised. 
This sort of thing ought to be documented better, in my opinion.  

I guess that means this issue is no longer required; I'll do a check with the Collector anyway and then close this. Thanks again!
