### ISSUE TITLE
How to handle SpanKind.Internal from otlp in opencensus

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#754]
Currently SpanKind - PRODUCER and CONSUMER - are handled using attributes in opencensus, but Internal is currently converted to opencensus Span_SPAN_KIND_UNSPECIFIED which was used in opencensus as the default.

Proposals:
* OpenCensus' Span_SPAN_KIND_UNSPECIFIED should be translated to INTERNAL if no attribute for PRODUCER or CONSUMER.
* Implement the same mechanism as we did for PRODUCER and CONSUMER.

Any thoughts?

**Comment by bogdandrutu** [comment]
From the OTLP proto definition:
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L105

**Comment by tigrannajaryan** [comment]
Looks like a bug in internal->OC translation. OC->translation handles this correctly.

**Comment by kbrockhoff** [comment]
Fix of #1136 will fix this.
