### ISSUE TITLE
Multi Tenancy for Loki Exporter

### ISSUE THREAD

**Issue by psangamkar** [open-telemetry/opentelemetry-collector#7591]
We have otel collector and loki-distributed stack deployed on K8s cluster using helm chart. Where in the Otel loki exporter we are using X-scope-OrgID as header for multi tenancy but we want more than 1 tenant as header. 

**oter config :** 
  
   exporters:
        loki/multitenant:
          endpoint: "http://loki-gateway:80/loki/api/v1/push"
          tls:
            insecure: true
            insecure_skip_verify: true
          headers:
            "X-Scope-OrgID": acme
            "X-Scope-OrgID": abc

We are facing this error
`Error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: yaml: unmarshal errors:
  line 32: mapping key "X-Scope-OrgID" already defined at line 31
2023/05/02 13:32:48 collector server run finished with error: failed to get config: cannot resolve the configuration: cannot retrieve the configuration: yaml: unmarshal errors:
  line 32: mapping key "X-Scope-OrgID" already defined at line 31`

Along with that How can we update **X-Scope-OrgID** dynamically from log attribute?

**Comment by fatsheep9146** [comment]
I think this issue should be transferred to contrib, do you have permission to do this? @codeboten

**Comment by mar4uk** [comment]
here is the same issue in contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21489.
Probably this one could be closed

**Comment by codeboten** [comment]
Thanks @mar4uk! Closing
