### ISSUE TITLE
create builds for 0.76.3

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector#7598]
The defautl yaml is  not in sync with latest labels, like 0.76.3
https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/builder/internal/config/default.yaml

It seems that there are build error because of deps which are not yet compatible- build with o.76.3

 github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector tested by
        github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector.test imports
        go.opentelemetry.io/collector/connector/connectortest: reading go.opentelemetry.io/collector/go.mod at revision v0.76.3: unknown revision v0.76.3

github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver imports
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/networkscraper imports
        github.com/shirou/gopsutil/v3/net: go.opentelemetry.io/collector@v0.76.3: reading go.opentelemetry.io/collector/go.mod at revision v0.76.3: unknown revision v0.76.3

...

**Comment by codeboten** [comment]
@cforce would you be able to open a PR to update https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/builder/internal/config/default.yaml to 0.76.1?

**Comment by codeboten** [comment]
Fixed by #7633, thanks @cforce!
