### ISSUE TITLE
Logging Exporter verbosity doesn't support warn level used in the old loglevel option

### ISSUE THREAD

**Issue by nadavleva** [open-telemetry/opentelemetry-collector#7623]
https://github.com/open-telemetry/opentelemetry-collector/blob/525594565deb07d8c76987751e2b1b89d89ca1d3/exporter/loggingexporter/config.go#L65

Exporter loggingexporter new verbosity doesn't support all the loglevel used in old / deprecated loglevel option.

**Comment by mx-psi** [comment]
@nadavleva AFAICT these should work as before; they didn't have any special functionality before and they don't have it now. If we ever use them again, we can change the code in a backwards compatible way to use these.

**Comment by astencel-sumo** [comment]
This is not a problem. Just use the `verbosity: normal` or `verbosity: basic` property if you used `loglevel: warn` before.

The Logging exporter has in fact only two output modes: basic/normal and detailed. With basic/normal, the Logging exporter only outputs a summary line for each signal, containing the number of records, for example for logs:

```console
info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 26}
```

In the detailed mode, the exporter outputs each record's full details ([source](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.78.2/exporter/loggingexporter/logging_exporter.go#L61-L75)).

When using the deprecated `loglevel` config property, the zapcore's values `warn`, `error` and higher would cause the non-detailed output of Logging exporter, so you can just replace `loglevel: warn` with `verbosity: normal` and there will be no change in the exporter's behavior.
