### ISSUE TITLE
[admin] Add guidance for release candidates version schema

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#7628]
On the v0.76.x release cycle we learned that Go orders prerelease version tag with dictionary order if not containing dots, which means that `v1.0.0-rc10` comes before `v1.0.0-rc9` or any other single digit release candidate. To work around this we released `pdata` with version `v1.0.0-rcv0011`.

Since we intend to go through release candidates in other modules, we should add guidance reflecting that we should add a `.` between the `rc` and the version (e.g. `v1.0.0-rc.1).

Relates to #7576

**Comment by Aneurysm9** [comment]
I believe that using `rc.1` rather than `rc1` should solve the issue.  This is the [recommended form for pre-release versions](https://go.dev/doc/modules/version-numbers#pre-release) from the Go module documentation.

**Comment by mx-psi** [comment]
That seems to check out with a quick experiment, reworded the issue text

```
❯ go get github.com/mx-psi/go-tag-experiments@v0.0.3-rc.10
go: downloading github.com/mx-psi/go-tag-experiments v0.0.3-rc.10
go: upgraded github.com/mx-psi/go-tag-experiments v0.0.3-rc.9 => v0.0.3-rc.10

```

**Comment by atoulme** [comment]
It seems this issue is resolved, is it ok to close?

**Comment by mx-psi** [comment]
We are not going to have any more release candidates, so we don't need this.
