### ISSUE TITLE
add ability to create `connector.*Routers` for tests

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-collector#7672]
In order to test routing based connectors we need to be able to construct `connector.*Router`s in order to build connectors via their factory methods. The [connector internals](https://github.com/open-telemetry/opentelemetry-collector/blob/9ef6429bd0fa1eb101deed570d5177c0ecd31030/service/internal/graph/nodes.go#L252-L258) handles this for us in the real world. 

As suggested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21498#issuecomment-1542682841 we can move the fanoutconsumer from `service/internal` to `internal` and add methods to aid construction of `connector.*Router`s in `connectortest`.

Please assign this to me. I have PR to add this functionality that I will open shortly.

**Comment by atoulme** [comment]
Can we close this issue as complete?

**Comment by mwear** [comment]
We can!
