### ISSUE TITLE
Resource Processor: incorrect documentation or bug in implementation?

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#768]
The doc for Resource Processor doesn't match the actual purpose of the `type` field:
- The documentation states that it's used to filter by source type to which we want to apply static labels.
- In fact Resource Processor always overwrites the resource type.

Code and doc were written by different people, so there probably was some misunderstanding:
- code: #423 @dinooliva
- doc: #573 @flands

Which one is intended behavior?
For our use case at Google we actually prefer as it's written in the documentation: apply labels without overwriting the resource type.

---

Doc (https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#resource-processor):
> - `type`: Type of resource to which labels should be applied. Only
applicable to `type` of `host` today.

But in the code `type` is not used for matching, and actually overwrites the resource type regardless of the original one: https://github.com/open-telemetry/opentelemetry-collector/blob/1937b715826bb8e6f8645bbb91670b0be2aa75aa/processor/resourceprocessor/resource_processor.go#L124 (the `Type` is copied from the config in https://github.com/open-telemetry/opentelemetry-collector/blob/1937b715826bb8e6f8645bbb91670b0be2aa75aa/processor/resourceprocessor/resource_processor.go#L108

---

Also not sure what does this phrase mean
> Only applicable to `type` of `host` today.

/cc @rghetia @x13n @tigrannajaryan

**Comment by rghetia** [comment]
I believe the intention was to override but I can see this expand to more elaborate resource processing that would allow to
- add resources
- overwrite resource
- modify resource (add additional labels)
- do the above conditionally.

**Comment by dinooliva** [comment]
Yes, the intention was to override. There's a lot of room for expanding resource processing, as noted by @rghetia and including adding support for dynamic resources (e.g. based on label values).

**Comment by nilebox** [comment]
One particular issue with the current implementation of the Resource Processor is that it effectively makes collector support only **one resource type**, which might be okay for sidecar mode, but doesn't scale well for generic `DaemonSet` per node serving various types of metrics and spans.

**Comment by nilebox** [comment]
Created a separate issue for discussing improvements in Resource Processor: #773

**Comment by tigrannajaryan** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/772
