### ISSUE TITLE
Possibility of building custom collector with coverage profiling ( '-cover') for integration test

### ISSUE THREAD

**Issue by antonjim-te** [open-telemetry/opentelemetry-collector#7690]
We need to collect coverage of our integration test when running the collector.
As you can see here https://go.dev/testing/coverage/ it can be solved by adding `-cover` to `go build`.
It is supported starting in Go `1.20`.

I have tried `--ldflags -cover`, however `-cover` is not supported due to the Go version.
```
ocb --config builder-config.yaml --ldflags -cover
2023-05-17T09:12:02.060+0200	INFO	internal/command.go:126	OpenTelemetry Collector Builder	{"version": "0.77.0", "date": "2023-05-08T21:10:46Z"}
2023-05-17T09:12:02.136+0200	INFO	internal/command.go:159	Using config file	{"path": "builder-config.yaml"}
2023-05-17T09:12:02.136+0200	INFO	builder/config.go:116	Using go	{"go-executable": "/usr/local/go/bin/go"}
2023-05-17T09:12:02.140+0200	INFO	builder/main.go:76	Sources created	{"path": "./otelcol-dev"}
2023-05-17T09:12:04.824+0200	INFO	builder/main.go:128	Getting go modules
2023-05-17T09:12:04.885+0200	INFO	builder/main.go:87	Compiling
Error: failed to compile the OpenTelemetry Collector distribution: exit status 1. Output:
# go.opentelemetry.io/collector/cmd/builder
flag provided but not defined: -cover
```

**Describe the solution you'd like**
The solution is the option to build the custom collector with coverage profiling for integration tests.

Could you help me? Thank you in advance.

**Comment by seankhliao** [comment]
`-cover` is a build flag, not a linker flag.
you can set it via default env vars, eg `GOFLAGS='-cover'`

**Comment by seankhliao** [comment]
the documentation also mentions the -coverpkg flag if you want a non default set of modules to be included.

**Comment by antonjim-te** [comment]
Thank you @seankhliao . I am able to get the code coverage using the environment variable:
```
 GOFLAGS=-coverpkg=`cat pkgs.txt`
```

The `pkgs.txt` file is the result of running the following command inside of the `otelcol-dev` folder:
```
go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' -deps . | paste -sd "," > pkgs.txt
```

In order to save the code coverage, you need to:
```
GOCOVERDIR=${PWD}/coverage
mkdir -p ${GOCOVERDIR}
./otelcol-dev/otelcol-dev --config=run-config.yaml
go tool covdata percent -i=${GOCOVERDIR}
```

Thank you for all your help.
