### ISSUE TITLE
Adding static labels to resource without changing its type

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#773]
We have a use case where we need a processor that would add static labels to resource without changing its type. It seems generic enough to be supported by collector out of the box.

The existing [Resource Processor](https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#resource) always overrides the resource type, which makes it impossible to use when there is more than one resource type per collector.

One simple code change we could make there is make the `type` parameter optional, and don't mutate the original resource type if it's not configured.
In other words, we could make the change in https://github.com/open-telemetry/opentelemetry-collector/blob/81cc48ca892c46ec7a7cd39443147b59eff6b8fd/processor/resourceprocessor/resource_processor.go#L124 to
```go
if from.Type != "" {
  to.Type = from.Type
}
```

It's unclear though what to do when the resource is missing in the original `TraceData` / `MetricData`, and we haven't set the resource type in the Resource Processor config. It seems that we should keep it `nil` since Resource without resource type would be invalid.

---

Alternatively, we may discuss developing a new processor that would provide a lot more flexibility than the existing Resource Processor.

**Comment by tigrannajaryan** [comment]
@nilebox is this fully resolved by #792?

**Comment by nilebox** [comment]
Yes, it's resolved.
