### ISSUE TITLE
Triager role request for @astencel-sumo

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector#7778]
Hi, I'd like to help with triaging issues in this repo. I'm an approver for the [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) repo.

Just today I stumbled upon a couple issues that should be closed:
- https://github.com/open-telemetry/opentelemetry-collector/issues/7623
- https://github.com/open-telemetry/opentelemetry-collector/issues/7619

**Comment by jpkrohling** [comment]
We commented on Slack already, but I also wanted to tell you that we have seen this request and are evaluating it. You should be hearing more about this soon.
