### ISSUE TITLE
Create a metadata.yaml file with all internal telemetry metrics exposed by the collector

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#7813]
**Is your feature request related to a problem? Please describe.**
We currently expose multiple metrics as part of the collector internal telemetry, but those are poorly documented and hard to find. They are defined inline with the code here: https://github.com/open-telemetry/opentelemetry-collector/blob/ce6535092daee23d1d7492844dee639a24cd803d/service/internal/proctelemetry/process_telemetry.go#L145

**Describe the solution you'd like**
I understand that we eventually want to move to a native pmetric format to generate and export those metrics rather than OpenCensus. Rather than trying to get there in one step, this issue offers that we document the metrics in a metadata.yaml file that we make part of the telemetry package. This file for the time being would not be used to generate metrics, but simply document them.

**Comment by codeboten** [comment]
@atoulme your wish is my command :) This is now done via metadata.yaml with the following config:

```yaml
telemetry: 
  metrics:
```
