### ISSUE TITLE
[loggingexporter] `detailed` verbosity level should also log exemplars

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-collector#7912]
**Is your feature request related to a problem? Please describe.**
When doing various testing / debugging with the `detailed` verbosity, it would be nice to see exemplars attached to a metric data points.

**Describe the solution you'd like**
Logging exporter, when configured with `detailed` verbosity, logs exemplar information.

**Describe alternatives you've considered**
No alternative.

**Additional context**
I'd be happy to put in the work to add this feature.

**Comment by mx-psi** [comment]
Makes sense to me to add this :)

**Comment by shivanshu1333** [comment]
I'd like to work on this, Can I get it assigned to me? Thanks!

**Comment by matej-g** [comment]
Feel free to go for it @shivanshu1333, I'd be happy to assist or review if any help will be needed 🙂

**Comment by oliver-zhang** [comment]
@shivanshu1333 Are you starting on this ?

**Comment by shivanshu1333** [comment]
Hi @oliver-zhang I've done some work would try to open a PR this weekend.

**Comment by matej-g** [comment]
Hey folks 👋, I opened https://github.com/open-telemetry/opentelemetry-collector/pull/8142 in order to try and speed up the process a bit, I hope that's fine. Reviews are welcome!
