### ISSUE TITLE
importing opentelemetry-collector clobbers previously registered gRPC compressors

### ISSUE THREAD

**Issue by mostynb** [open-telemetry/opentelemetry-collector#7920]
**Describe the bug**

Some consumers of this library have registered grpc compressors, and the init() order can cause their compressors to be clobbered by opentelemetry-collector's use of github.com/mostynb/go-grpc-compression, which follows the pattern of https://github.com/grpc/grpc-go/blob/master/encoding/gzip/gzip.go (overwrite any previously registered encoders with the same name).

**Steps to reproduce**
1. Write a program that uses a specific zstd grpc compressor implementation (that isn't github.com/mostynb/go-grpc-compression/zstd).
2. Add opentelemetry-collector to that program.
3. Note that the zstd grpc compressor is now github.com/mostynb/go-grpc-compression/zstd, depending on init() ordering

**What did you expect to see?**
The programs original grpc compressor should be used.

**What did you see instead?**
github.com/mostynb/go-grpc-compression/zstd is used instead of the preferred compressor.

**What version did you use?**
Any version of opentelemetry-collector that uses github.com/mostynb/go-grpc-compression/* should be affected.

**Proposed solution**
https://github.com/mostynb/go-grpc-compression/pull/19 adds "nonclobbering" versions of each compressor. If I were to land that and make a new release, we could change all opentelemetry-collector imports of github.com/mostynb/go-grpc-compression/* to the corresponding github.com/mostynb/go-grpc-compression/nonclobbering/* package.

If you would accept such a change, I will land that PR in github.com/mostynb/go-grpc-compression (reviews of the PR above are welcome too).

**Comment by mx-psi** [comment]
Hi @mostynb thanks for taking the time to open the issue. I think this is a reasonable solution, cc @open-telemetry/collector-approvers

**Comment by codeboten** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/7966
