### ISSUE TITLE
pcommon.Map.EnsureCapacity clears the map as a side effect

### ISSUE THREAD

**Issue by krdln** [open-telemetry/opentelemetry-collector#7955]
**Describe the bug**
pcommon.Map.EnsureCapacity clears the map as a side effect

**Steps to reproduce**
```
package main

import "go.opentelemetry.io/collector/pdata/pcommon"

func main() {
	m := pcommon.NewMap()
	m.PutStr("foo", "bar")
	m.EnsureCapacity(2)
	if m.Len() != 1 {
		panic("?")
	}
}
```

**What did you expect to see?**
No panic – map should contain `"foo"`.

**What did you see instead?**
Map is empty.

**What version did you use?**
v0.79.0

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector/blob/0b88ff96861bd1c87ab909c6cf71836498cd68c9/pdata/pcommon/map.go#L35-L44

The `copy` will copy zero elements, because `copy`

> returns the number of elements copied, which will be the minimum of len(src) and len(dst).

**Comment by mx-psi** [comment]
cc @dmitryax @bogdandrutu

**Comment by krdln** [comment]
Seems to be fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/8040
