### ISSUE TITLE
Release stable vY.Y.Y and beta vX.X.X

### ISSUE THREAD

**Issue by Apdlrcjafg19** [open-telemetry/opentelemetry-collector#8044]
Like #4522, but for vX.X.X

**Performed by collector release manager**

- [x] Prepare stable core release vY.Y.Y
- [x] Tag and release stable core vY.Y.Y
- [x] Prepare beta core release vX.X.X
- [x] Tag and release beta core vX.X.X
- [x] Prepare contrib release vX.X.X
- [x] Tag and release contrib vX.X.X
- [x] Prepare otelcol-releases vX.X.X
- [x] Release binaries and container images vX.X.X

**Performed by operator maintainers**

- [x] Release the operator vX.X.X

**Performed by helm chart maintainers**

- [x] Update the opentelemetry-collector helm chart to use vX.X.X docker image

**Comment by atoulme** [comment]
I am not sure what this is. Please help understand or close this issue, thanks!

**Comment by mx-psi** [comment]
Closing this since it was likely an error
