### ISSUE TITLE
Span traceId, spanId and parentSpanId doesn't work when setting them as bytes

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-collector#805]
The description for traceId, spanId, parentSpanId says it should be bytes, however it works only if it is set to base64

https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L58
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L68
https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L83

So either description for proto is wrong or opentelemetry collector has a bug.

**Comment by obecny** [comment]
related issue in proto 
https://github.com/open-telemetry/opentelemetry-proto/issues/136

**Comment by bogdandrutu** [comment]
@obecny happy to look into this issue, but please tell us the configuration, receiver/exporter you use and protocol.

**Comment by tigrannajaryan** [comment]
Closing as it appears to be working as designed (spans are supposed to be base64 encoded in JSON).
