### ISSUE TITLE
How to print recieve span nums in console like TracesExporter

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector#8092]
## Important (read before submitting)

**Is your feature request related to a problem? Please describe.**

2023-07-14T08:14:05.820Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 90, "spans": 170}
exporter can got this logging, How to set in reciever such as oltl

**Describe the solution you'd like**
confirm how many spans I have recieved

**Describe alternatives you've considered**

**Additional context**

**Comment by codeboten** [comment]
You can view received spans by looking at the collector's internal metrics, which can be enabled via the config shown in the troubleshooting guide:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics
