### ISSUE TITLE
Change in handling Content-Encoding:"identity" in version v0.81.0

### ISSUE THREAD

**Issue by tj---** [open-telemetry/opentelemetry-collector#8114]
**Describe the bug**
Introduced with this change: https://github.com/open-telemetry/opentelemetry-collector/pull/7927
When a request is sent with `Content-Encoding: identity`, the request is rejected with HTTP_400 (`unsupported Content-Encoding: identity`)
This breaks some of the existing HTTP clients (eg: [influxdb_client](https://github.com/influxdata/influxdb-client-python/blob/master/influxdb_client/client/write_api.py#L509)) that we use to export data to OTel Collector (Influxdb receiver). This client, for instance, sets `Content-Encoding: identity` while making a request.

**Steps to reproduce**
Detailed here: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24387
This [line](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/compression.go#L154). Until v0.80.x, a `nil` was returned, and the request was accepted

**What did you expect to see?**
I expect the request to be accepted. I think "identity" is an acceptable value for the encoding, besides, this is a breaking change.

**What did you see instead?**
Request being rejected with a HTTP_400

**What version did you use?**
0.81.0

**What config did you use?**
```
receivers:
 influxdb:
   endpoint: 0.0.0.0:19000
```

**Environment**
Docker on mac

**Comment by tj---** [comment]
@codeboten @tigrannajaryan let me know if you're okay with having `identity` as a key in the [`decoders` map here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/compression.go#L88). I can make the change.

**Comment by tj---** [comment]
Was hoping for some backward compatibility of the behavior between v0.80.0 and v0.81.0.
Will patch the client.

**Comment by atoulme** [comment]
I understand, I had the same turn. The HTTPClientSettings and HTTPServerSettings allow you to set decoders.

**Comment by tj---** [comment]
Closing this in favor of client-side changes.
