### ISSUE TITLE
Support additional exporters for exporting collector logs

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#8118]

**Comment by codeboten** [comment]
Traces and metrics both rely on the go sdk to export internal telemetry. This issue will be blocked by https://github.com/open-telemetry/opentelemetry-go/issues/3827 unless an alternative proposal is put forward until logs are supported in the go SDK.

**Comment by codeboten** [comment]
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/3460

**Comment by mx-psi** [comment]
Is this done?

**Comment by codeboten** [comment]
Yes this was completed with https://github.com/open-telemetry/opentelemetry-collector/pull/10544
