### ISSUE TITLE
Request: support monitoring thread count of process

### ISSUE THREAD

**Issue by jamesbraza** [open-telemetry/opentelemetry-collector#8126]
**Is your feature request related to a problem? Please describe.**

I am trying to root cause what causes a program to leak threads over time.

Can OTEL support monitoring of threads for a specific process (by name)?

**Describe the solution you'd like**

Somehow in a config file entering the process name (or regex pattern for process name(s)) to monitor its thread count.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by atoulme** [comment]
Yes, please see hostmetricsreceiver under the processes section.
