### ISSUE TITLE
Dependency error trying to build custom collector distribution 0.81.0 within a workspace

### ISSUE THREAD

**Issue by mattsains** [open-telemetry/opentelemetry-collector#8127]
**Describe the bug**
When building a custom collector with version 0.81.0, if the collector is built into a directory which forms part of a go workspace, the builds fails with this error:

```
2023-07-24T15:05:12.598-0700    INFO    internal/command.go:117 OpenTelemetry Collector Builder {"version": "dev", "date": "unknown"}
2023-07-24T15:05:12.599-0700    INFO    internal/command.go:150 Using config file       {"path": "builder-config.yaml"}
2023-07-24T15:05:12.599-0700    INFO    builder/config.go:106   Using go        {"go-executable": "/usr/local/go/bin/go"}
2023-07-24T15:05:12.599-0700    INFO    builder/main.go:69      Sources created {"path": "./"}
2023-07-24T15:05:13.177-0700    INFO    builder/main.go:121     Getting go modules
2023-07-24T15:05:13.448-0700    INFO    builder/main.go:80      Compiling
Error: failed to compile the OpenTelemetry Collector distribution: exit status 1. Output:
../../../go/pkg/mod/go.opentelemetry.io/collector/confmap@v0.81.0/confmap.go:11:2: ambiguous import: found package github.com/knadh/koanf/maps in multiple modules:
        github.com/knadh/koanf v1.5.0 (/home/msainsbury/go/pkg/mod/github.com/knadh/koanf@v1.5.0/maps)
        github.com/knadh/koanf/maps v0.1.1 (/home/msainsbury/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.1)
../../../go/pkg/mod/go.opentelemetry.io/collector/confmap@v0.81.0/confmap.go:12:2: ambiguous import: found package github.com/knadh/koanf/providers/confmap in multiple modules:
        github.com/knadh/koanf v1.5.0 (/home/msainsbury/go/pkg/mod/github.com/knadh/koanf@v1.5.0/providers/confmap)
        github.com/knadh/koanf/providers/confmap v0.1.0 (/home/msainsbury/go/pkg/mod/github.com/knadh/koanf/providers/confmap@v0.1.0)
```

This error does not occur on 0.80.0.

**Steps to reproduce**
A minimal working example can be found here: https://github.com/mattsains/otel-builder-test

Go to directory `bloop` and run:

```
go install go.opentelemetry.io/collector/cmd/builder@v0.81.0
builder --config builder-config.yaml
```

The error occurs.

Downgrade the builder to version 0.80.0 and change all instances of 0.81.0 in the builder-config.yaml file to 0.80.0, and try again. It succeeds.

**What did you expect to see?**
I expected to be able to build a custom collector in a workspace. This is a reasonable scenario if you are also building custom components to include in your distribution.

**What did you see instead?**
A dependency error. I am sure this is not conflicts with my own code, because, as you can see in the repro, it is a trivial workspace with only the collector build included.

**What version did you use?**
0.81.0

**What config did you use?**
See repo linked above

**Environment**
OS: Linux 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Compiler(if manually compiled): go version go1.20.5 linux/amd64

**Additional context**
Could this be because the koanf dependency is older than workspaces? https://github.com/knadh/koanf/blob/v1.5.0/go.mod#L3

**Comment by dyladan** [comment]
I ran into this as well. Removing the `go.work` file fixed the error for me, though that may not be possible for everyone. Looks like Jaeger also had the same problem (with the same solution) https://github.com/open-telemetry/opentelemetry-collector/pull/7841#issuecomment-1631242979

**Comment by taj-p** [comment]
We were able to build the collector by adding the following to our `builder-config.yaml`:

```yaml
excludes:
  - github.com/knadh/koanf v1.5.0
```

**Comment by mattsains** [comment]
Nice, I was able to do the same with:

```
  - github.com/knadh/koanf v1.5.0
  - github.com/knadh/koanf/providers/confmap v0.1.0
  - github.com/knadh/koanf/maps v0.1.1
```

**Comment by codeboten** [comment]
This should be fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/8219, please re-open if its not the case

**Comment by mattsains** [comment]
@mmynk if it's still happening, please re-open this issue
