### ISSUE TITLE
MetricData or Metric[s]Data for the new internal data?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#822]

**Comment by bogdandrutu** [comment]
@tigrannajaryan any thoughts on this?

**Comment by dmitryax** [comment]
I'd prefer `MetricData`. It's consistent TraceData and doesn't sound wrong.

**Comment by tigrannajaryan** [comment]
I agree with @dmitryax 
I would also do it across all names, e.g. `ConsumeMetricData` in new interfaces if not already done (I don't remember).

**Comment by bogdandrutu** [comment]
@tigrannajaryan I think in the new interface we have `ConsumeMetrics` because we need different name than the old interface.

**Comment by dmitryax** [comment]
I agree that we should use `Metric` in all the places. `ConsumeMetricsData` is the name in the old interface, `ConsumeMetric` is not being used, if I'm not missing anything.

**Comment by bogdandrutu** [comment]
@dmitryax probably we should use `ConsumeMetricData` and `ConsumeTraceData` after we remove the old interface.

**Comment by dmitryax** [comment]
@bogdandrutu agree, that would be better name

**Comment by bogdandrutu** [comment]
@tigrannajaryan and I decided to use:
`pdata.Traces`
`pdata.Metrics`
respectively:
`ConsumeMetrics`
`ConsumeTraces`
