### ISSUE TITLE
Release `featuregate` 1.0

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8220]
The [`featuregate`][1] module [milestone][2] has been completed for three months at time of writing. None of the remaining [open issues related to featuregate][3] seem like a blocker for GA for me.

This issue is for discussing if there are any blockers not listed on the issue tracker to release a 1.0 version of this module, and, if not, release this module. At time of writing this would be our first 1.0 module.

A 1.0 release would [honor our stability guarantees][4].

[1]: https://github.com/open-telemetry/opentelemetry-collector/tree/main/featuregate
[2]: https://github.com/open-telemetry/opentelemetry-collector/milestone/30
[3]: https://github.com/open-telemetry/opentelemetry-collector/labels/area%3Afeaturegate
[4]: https://github.com/open-telemetry/opentelemetry-collector/blob/main/VERSIONING.md

**Comment by atoulme** [comment]
I would like to see https://github.com/open-telemetry/opentelemetry-collector/issues/7804 addressed first as https://github.com/open-telemetry/opentelemetry-collector/pull/7991 introduces an API breaking change.

**Comment by mx-psi** [comment]
#8766 may be necessary for 1.0

**Comment by mx-psi** [comment]
I am going to close this one in favor of #8946, which follows the template from #8935
