### ISSUE TITLE
Does the new data model need to support "SourceFormat"?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#823]
`SourceFormat string` was part of the old data model and no equivalent in the new data-model.

**Comment by pjanotti** [comment]
I don't think so: in practice, it was not that useful (at least for me) and we want to be able to mix data from different sources under the same batch and tracking the original source format becomes an extra amount of work without clear benefit.

**Comment by tigrannajaryan** [comment]
Closing this as "won't do". Feel free to reopen if needed.
