### ISSUE TITLE
Units titles

### ISSUE THREAD

**Issue by yonatan555** [open-telemetry/opentelemetry-collector#8246]
Hi all,
is there any guide or page for units I can follow,
like unit with types, which indicate how the metric is measured,

**An example:**
Uptime which is measured by seconds and the convention is 's'
Or tempreuate that is measure by celcius and the convention is 'Cel'

Thanks.

**Comment by dmitryax** [comment]
Hi @yonatan555, please see https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#instrument-units

**Comment by dmitryax** [comment]
Closing as not relevant to this repository
