### ISSUE TITLE
Decompressor is not installed for grpc-encoding \"gzip\""

### ISSUE THREAD

**Issue by techtug-a** [open-telemetry/opentelemetry-collector#8280]
**Describe the bug**
2023-08-24T08:32:05.743Z	error	exporterhelper/queued_retry.go:391	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlp/elastic", "error": "Permanent error: rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding \"gzip\"", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector/exporter@v0.82.0/exporterhelper/queued_retry.go:391
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
	go.opentelemetry.io/collector/exporter@v0.82.0/exporterhelper/traces.go:126
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector/exporter@v0.82.0/exporterhelper/queued_retry.go:195
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector/exporter@v0.82.0/exporterhelper/internal/bounded_memory_queue.go:47

**What version did you use?**
otelcol version 0.82.0

**What config did you use?**
receivers:
  otlp:
   protocols:
      http:
        endpoint: 192.168.20.67:4318
        tls:
          #client_ca_file: /srv/drooms/ca.crt
          cert_file: /srv/drooms/elkstack-certs.crt
          key_file: /srv/drooms/elkstack-certs.key

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  logging:
    verbosity: detailed

  otlp/elastic:
    compression: none
    endpoint: 172.18.2.19:8200
    tls:
      insecure: true
      #insecure_skip_verify: false
      ca_file: /srv/example/ca.crt
      cert_file: /srv/example/elkstack-certs.crt
      key_file: /srv/example/elkstack-certs.key
    headers:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/elastic]

**Environment**
OS: CentOS Linux release 7.6.1810 (Core)

**Additional context**
Gzip, snappy is installed on both receiver and sender end, only works if compression is set to none.

**Comment by alvescoms** [comment]
The same problem here, its really a bug?

**Comment by codeboten** [comment]
The following error is reported from the destination `172.18.2.19:8200`:

```
Decompressor is not installed for grpc-encoding "gzip"
```

Does your backend support gzip over gRPC?

**Comment by amccool** [comment]
running the 0.83 contrib on windows server 2019 exporting ElasticCloud

Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding \"gzip\"", "dropped_items": 71}

same exporter for logs,metrics,traces, and getting errors for all three.

I only get this when exporting to ElasticCloud

**Comment by techtug-a** [comment]
> The following error is reported from the destination `172.18.2.19:8200`:
> 
> ```
> Decompressor is not installed for grpc-encoding "gzip"
> ```
> 
> Does your backend support gzip over gRPC?

Hi Codeboten,
Thanks for your response.
My backend is the opentelemtry collector on top of CentOS Linux release 7.6.1810 which has the gzip package installed by default. The receiver is an Elastic APM Server on top of Ubuntu 22.04.3 LTS which has also gzip installed by default.
Possible that this issue is related to the Elastic Stack since the error only started after the Stack was updgraded to the latest release.

Br,
Fred

**Comment by joshdover** [comment]
Also ran into this today on Elastic APM Server 8.9.1 cc @simitt

**Comment by simitt** [comment]
Thanks for the ping on this. Unfortunately there was a regression in the Elastic APM Server in `8.9.1` to not support gzip compression. A fix has already been merged and is planned to be part of the `8.9.2` release, see details in https://github.com/elastic/apm-server/issues/11512#issuecomment-1697207275.

**Comment by codeboten** [comment]
Thanks @simitt! Closing the issue here

**Comment by amccool** [comment]
> Thanks for the ping on this. Unfortunately there was a regression in the Elastic APM Server in `8.9.1` to not support gzip compression. A fix has already been merged and is planned to be part of the `8.9.2` release, see details in [elastic/apm-server#11512 (comment)](https://github.com/elastic/apm-server/issues/11512#issuecomment-1697207275).

are there particular versions of the ElasticAPM which do or do not support compression?
