### ISSUE TITLE
Release beta v0.84.0

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#8308]
Like open-telemetry/opentelemetry-collector#4522, but for v0.84.0

**Performed by collector release manager**

- [x] Prepare stable core release v0.84.0
- [x] Tag and release stable core v0.84.0
- [x] Prepare beta core release v0.84.0
- [x] Tag and release beta core v0.84.0
- [x] Prepare contrib release v0.84.0
- [x] Tag and release contrib v0.84.0
- [x] Prepare otelcol-releases v0.84.0
- [x] Release binaries and container images v0.84.0

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#2071

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#880

**Comment by codeboten** [comment]
This is complete
