### ISSUE TITLE
OTel Instrument names not conforming to otel spec

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#8346]
The OpenTelemetry instruments created for the Collector's internal metrics use a `/` separator. This breaks when trying to upgrade to the latest version of the otel go SDK as per the change: https://github.com/open-telemetry/opentelemetry-go/pull/4210

**Comment by codeboten** [comment]
This may be addressed when https://github.com/open-telemetry/opentelemetry-specification/issues/3422 is closed

**Comment by dashpole** [comment]
It is possible (but not pretty) to work around this with Views, which do not do any validation on the stream name.

**Comment by dashpole** [comment]
Also, the error about "/" can be ignored.  You still get a valid instrument.  cc @MrAlias

**Comment by codeboten** [comment]
@dashpole are you saying the result is a valid instrument even with the invalid instrument name error?

```
            	            	error creating batch processor telemetry: invalid instrument name: processor/batch/batch_size_trigger_send: must only contain [A-Za-z0-9_.-]
```

**Comment by codeboten** [comment]
Ah yes i see in the code that the instrument is returned regardless of what the validation returns. Is it safe to ignore this error then?

**Comment by MrAlias** [comment]
> Ah yes i see in the code that the instrument is returned regardless of what the validation returns. Is it safe to ignore this error then?

It should be safe in the sense that the SDK will not have a problem with this (it should process the instrument measurements as before). The only issue would be downstream, if the data goes to a place that expects the instrument names to conform to the OTel spec that expectation will not be meet.

**Comment by codeboten** [comment]
Once https://github.com/open-telemetry/opentelemetry-go/issues/4500 is released, we should be able to revert the workaround to ignore the error
