### ISSUE TITLE
OCProtoToJaegerProto appends parent to the end of references, parent should be first

### ISSUE THREAD

**Issue by william-tran** [open-telemetry/opentelemetry-collector#840]
This block runs after the references list is put together: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.3.0/translator/trace/jaeger/protospan_to_jaegerproto.go#L490-L501

Jaeger UI assumes the parent is the first reference and has no parent span ID in its object model, so it renders the trace incorrectly. This was encountered when trying to resolve https://github.com/jaegertracing/jaeger-client-java/issues/705. My setup is jaeger thrift http -> otel-collector -> jaeger grpc -> jaeger.

**Comment by tigrannajaryan** [comment]
@dmitryax is this related to what you found recently?

**Comment by dmitryax** [comment]
@tigrannajaryan yes, this is related, but a bit different issue.

It makes sense to put parent as the first reference in the list. I'll apply it in the the new jaeger exporter.

**Comment by william-tran** [comment]
Thanks for taking this on, I have another more general issue https://github.com/open-telemetry/opentelemetry-specification/issues/562 that might be of interest as this translation work continues.
