### ISSUE TITLE
Label Processor Proposal

### ISSUE THREAD

**Issue by jjzeng-seattle** [open-telemetry/opentelemetry-collector#842]
# Label Processor
A processor for removing metric labels, including the label key and the corresponding label values.  We could add other operations such as insert and update later, if there is a need for them.

## Motivation
This is to prepare the knative metrics for the stackdriver exporter, but it could apply to other scenarios. 

Stackdriver does not accept metrics sent with unknown metric labels, so any metric labels outside of the [ones listed for each Stackdriver Knative metric](https://cloud.google.com/monitoring/api/metrics_knative) must be removed before being sent to Stackdriver.  Currently this is done inside knative since it sends metrics to stackdriver directly.

[Knative is the process to move away from sending metrics to stackdriver directly](https://github.com/knative/serving/issues/5972), instead it will use opencensus agent to send metrics to the opentelemetry collector, and then different vendors can use different exporters  for different backends.

For stackdriver, we therefore lose the ability to remove those extraneous labels inside knative.  We need a processor in the opentelemetry collector to do the job.   

## Proposed Configuration

Keep consistency with [attribute/span processor's filtering configuration](https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/attributesprocessor/testdata/config.yaml).

```
processors:
  labelprocessor/delete:
    actions:
      - label: foo
        action: delete
      - label: bar
        action: delete
```

**Comment by bogdandrutu** [comment]
@jjzeng-seattle removing labels is not as simple as span attribute processor because it requires merging points in case they have the same labels after labels are removed. @rghetia I remember you wrote a doc about label reduction. Is it possible to share that?

**Comment by rghetia** [comment]
> @jjzeng-seattle removing labels is not as simple as span attribute processor because it requires merging points in case they have the same labels after labels are removed. @rghetia I remember you wrote a doc about label reduction. Is it possible to share that?

here is the [doc](https://docs.google.com/document/d/1OjYes0E4Ruy5rIYYn99yF1-lqy23D5QhYoyAx4SabDI/edit?usp=sharing).

**Comment by jjzeng-seattle** [comment]
Do they need to be merged?  Could we have 2 metrics with the same labels?

I understand it would be nice to merge them for obvious reasons, but is it a requirement?

@bogdandrutu @rghetia

**Comment by rghetia** [comment]
> Do they need to be merged? Could we have 2 metrics with the same labels?
> 
> I understand it would be nice to merge them for obvious reasons, but is it a requirement?
> 
> @bogdandrutu @rghetia

It would depend on the backend. For example, stackdriver will not accept the un-merged timeseries. There will two problems
1. Two datapoints posted for the same timeseries within 1 minute. Backend has to merge these data points appropriately before displaying it on the chart. If the backend has limitation on how many data points can you post within X seconds then this will out right fail.
2. Each timeseries prior to label dropping has its own start time. After label drop, the series are identical but they have two different start time. Which one to pick? Granted that this is only applicable to cummulative counters.

**Comment by jjzeng-seattle** [comment]
After discussion with @rghetia  and @anniefu, a label processor dropping labels without aggregation is not useful.  What we really need is an aggregation processor.

**Comment by clheikes** [comment]
"The metrics transform processor can be used to rename metrics, and add, rename or delete label keys and values"

Are there any methods to remove labels at this point? I don't see a way to do it with the metric transform processor although it says you can delete label keys. In our case we added labels/attributes using the resource processor and can safely delete labels without needing aggregation.
