### ISSUE TITLE
Host Metrics Receiver

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#847]
Add a receiver to generate Host Metrics about the machine the collector is running on. Initially this will be for Windows only, but extendable so that the same receiver can be used to collect Linux metrics when implemented

This [Host Metrics](https://docs.google.com/document/d/1i-QG-TxkIWVbdx86UM2GXcFvpeCV7zSBsPmMyMkOEBk/edit?usp=sharing) document captures the metrics we intend to collect.

Update list of Metrics here: https://docs.google.com/spreadsheets/d/11qSmzD9e7PnzaJPYRFdkkKbjTLrAKmvyQpjBjpJsR2s/edit

**Comment by tigrannajaryan** [comment]
@james-bebbington assigning this to you since you started working on it.

**Comment by james-bebbington** [comment]
Feature request from @bogdandrutu: We need to think of a generic config to allow users to enable / disable individual metrics in a scraper

e.g.
```yaml
scrapers:
  network:
    enabled_metrics:
    - packets
    - dropped_packets
```

**Comment by jrcamp** [comment]
We should do this in a way that all scraping receivers can use it as it is a problem every receiver will have. I've created a ticket to track the larger issue: https://github.com/open-telemetry/opentelemetry-collector/issues/934
