### ISSUE TITLE
Log receiver for Opentelemetry

### ISSUE THREAD

**Issue by DeeptiGuptaP** [open-telemetry/opentelemetry-collector#8495]
Hello Team,

Could you please advise if we have any receiver in OpenTelemetry Collector which can scrape endpoints to get Logs?  

Regards,
Deepti Gupta

**Comment by atoulme** [comment]
Can you explain what you mean by scrape endpoint? Do you mean periodically request over HTTP a payload and record it for example? Is the payload one log record or multiple?
