### ISSUE TITLE
Find owners for orphan platforms

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8526]
The tiered platform support model introduced in #8224 requires owners for each platform we support in some capacity. We don't have owners for most Tier 3 platforms. This issue lists the platforms without an owner. If you are interested in becoming an owner for a given platform, please comment below or in the dedicated issue if it exists.

- [x] #9114
- [x] #8531
- [x] #9010
- [x] #9351
- [x] #8527
- [x] #8528
- [x] #9112

**Comment by MovieStoreGuy** [comment]
I am happy to look after `darwin/arm64` issues, it is my daily driver and what I do most of my time developing on.

**Comment by atoulme** [comment]
I am happy to take on `linux/arm64` issues.

**Comment by mx-psi** [comment]
@atoulme nice, would you mind opening a PR to add yourself as an owner? I filed #9010 and assigned it to you

**Comment by mx-psi** [comment]
@pjanotti any chance you would be interested in owning `windows/386` specific issues?

**Comment by pjanotti** [comment]
@mx-psi yes, I can work on `windows/386` issues.

**Comment by mx-psi** [comment]
> @mx-psi yes, I can work on `windows/386` issues.

Awesome! I filed #9113 then :)

**Comment by h0cheung** [comment]
Hi, I'm happy to take on `darwin/amd64` issues.

**Comment by mx-psi** [comment]
@h0cheung Awesome!! See #9350

**Comment by adilhusain-s** [comment]
Hi @mx-psi 
 I can work on [ppc64le issues](https://github.com/open-telemetry/opentelemetry-collector/issues/8528)

**Comment by mx-psi** [comment]
I am going to unpin this since we will close this with the PowerPC owners after everyone has approved. Thanks everyone :)

**Comment by IBM-Currency-Helper** [comment]
You should be cleared to close this one now.  Sorry for the delay on our side!!  --gh
