### ISSUE TITLE
Find owners for the linux/arm platform

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8527]
`linux/arm` builds were added in open-telemetry/opentelemetry-collector-releases/pull/349, but we don't have an explicit owner for this platform.

**Comment by mx-psi** [comment]
@Wal8800 as the person who introduced the `linux/arm` build, would you be interested in becoming an owner for the `linux/arm` platform? You will be pinged on issues specific to `linux/arm` (none so far AFAIK) and asked for help by maintainers if something specific to this platform is needed.

**Comment by Wal8800** [comment]
Sorry for the late reply. I recently changed jobs so I no longer use the `linux/arm` builds on a daily basis. I'm happy to look after the `linux/arm` builds if no one else is interested.

**Comment by atoulme** [comment]
I can also volunteer.

**Comment by mx-psi** [comment]
PTAL at #8635
