### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#854]
This is a brief proposal for updating the CI to better support Windows development & code that targets Windows specifically. I have been thinking about this as I started building out the new Host Metrics receiver which has code to gather Windows specific metrics. While I can't see it in the design docs anywhere, as I understand it the Collector is intended to be able to run with similar functionality on any OS.

**There's two main issues that would be nice to address:**
- There are a few unit tests that are dependent on the OS (see the list provided below), and some code that won't run on windows; the GRPC UseSecure option used by some exporters won't work due to not being able to obtain the system cert pool via the x509 package.
- We have some code & tests targeted to Windows only. While we do currently have a cross-compile job that builds a binary targeting windows, we don't run any of the Windows specific tests, so these could be broken at any time without breaking our CI build.

**Proposal:**
- Fix up tests that fail on windows by putting them behind an OS specific build flag, or condition, or by fixing the test so that it can run on Windows where appropriate.
- Add a CircleCI job that uses the windows executor (https://circleci.com/docs/2.0/executor-types/#using-the-windows-executor) to build & test the app (or maybe just selected parts of it).

**Open Questions:**
- How much do we care about this? Running the collector on Windows is probably not super common - maybe we are okay with just producing a windows binary & manually testing any windows specific concerns? (rather than adding time to the CI build)
- If we do create a new CI job, should we run this on every commit, or on some other trigger?

**For reference, here's the list of tests currently failing on windows:**
- Doesn't build due to referencing unix specific code:
  - configgrpc/configgrpc_test.go
  - receiver/securereceiverconfig_test.go
- Fails due to "system root pool is not available on Windows" (see https://github.com/golang/go/issues/16736):
  - jaegerexporter/exporter_test.go TestNew
  - opencensusexporter/factory_test.go TestCreateTraceExporter
  - oltpexporter/factory_test.go TestCreateTraceExporter
- Fails due to "The process cannot access the file because it is being used by another process" (can be fixed by closing `tmpfile` before removing it):
  - opencensusreceiver/opencensus_test.go TestReceiveOnUnixDomainSocket_endToEnd
  - otlpreceiver/otlp_test.go.go TestReceiveOnUnixDomainSocket_endToEnd

**Comment by tigrannajaryan** [comment]
>Fix up tests that fail on windows by putting them behind an OS specific build flag, or condition, or by fixing the test so that it can run on Windows where appropriate.

This is a good approach. I would first try to fix the tests but would not spend too much time if fixing is difficult and would just skip the test on Windows.

>How much do we care about this? Running the collector on Windows is probably not super common - maybe we are okay with just producing a windows binary & manually testing any windows specific concerns? (rather than adding time to the CI build)

It likely is going to be rare. I would be OK if we maintain a Windows build if it has a low maintenance cost. If it turns out to be a high cost we need a better justification and need contributors who care about Windows to help maintain it. I am not aware of any current maintainer or approver who is interested in this.
