### ISSUE TITLE
Collector internal (OTel telemetry) metrics don't allow for specifying custom histogram buckets

### ISSUE THREAD

**Issue by mdonkers** [open-telemetry/opentelemetry-collector#8559]
**Is your feature request related to a problem? Please describe.**
We are writing our own Exporter and capturing internal telemetry about number of data-points exported and latency of writing the data to a storage solution. For this we're using o.a. Histograms.

But because of the design of OTel Histogram metrics, custom buckets can only be configured via Views, not when creating the meter itself.
And with the OTel Collector, there is no current possibility to extend the existing set of views.

Some custom views for the batch processor are created here:
https://github.com/open-telemetry/opentelemetry-collector/blob/589488839f582632f53d84526207e733475ccc21/service/internal/proctelemetry/config.go#L155

But where OpenTelemetry is initialized, only additional `Readers` can be configured, no `Views`:
https://github.com/open-telemetry/opentelemetry-collector/blob/589488839f582632f53d84526207e733475ccc21/service/telemetry.go#L166

We'd like to define additional views because default bucket sizes don't make sense for us.

**Describe the solution you'd like**
Some way, either via configuration or via code, to extend the Histogram views to set custom bucket bounds.

**Describe alternatives you've considered**
There aren't any, really (OpenCensus allows defining views together with the meters but long-term OpenCensus should be replaced completely by OpenTelemetry for the Collector)

**Comment by mx-psi** [comment]
#8247 may be what you are looking for. This is currently blocked but is something we intend to support

**Comment by mdonkers** [comment]
Thanks, seems like I have missed that PR but it's exactly what I'm looking for.
And in that respect, would opt for the component factory to provide the View or wait for the Hints to be available. Because as @jpkrohling states:

> I believe component owners are best positioned to configure how the telemetry should be exposed. I think advanced users might be interested in tweaking this, but I don't think the majority of the users of, say, load-balancing exporter would be willing to configure the views in the config to have the same level of metrics that are being exposed today.

That would be my expectation as well and then its only needed in 1 place. Otherwise depending on the deployment mechanism this means a lot of configuration to put in place.

**Comment by mx-psi** [comment]
Feel free to leave a review on the PR itself :) I have linked the PR to close this issue

**Comment by mdonkers** [comment]
Closing, as I'll track the PR itself. Thx!
