### ISSUE TITLE
Add an AddMetric (or similar) function to pdata/pdatautil package

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#864]
Add a convenience method for appending a metric to a metric slice & returning it. Something like:

```func AddMetric(metrics pdata.MetricSlice) pdata.Metric```

It would probably be useful to add an Add or Append function for all Slice objects.

Once we have this we should update the host metrics receiver to make use of it.

Originally posted by @bogdandrutu in #862

**Comment by bogdandrutu** [comment]
I am trying to avoid adding this because:
* Calling `AddMetric` multiple times is way more inefficient than resizing directly to the number of metrics you expect to add.

So I am trying to avoid the following:
```golang
for _, el := range els {
  m := ms.AddMetric()
  // fill m
}
```

User should do:
```golang
ms.Resize(len(els))
for i, el := range els {
  m := ms.At(i)
  // fill m
}
```

**Comment by james-bebbington** [comment]
Yea I figured this was the case.

I was following the `Resize`/`At` pattern when, for example, creating a set of data points from an array. But when creating individual metrics it's a bit weird to have to write something like:

```
ms.Resize(ms.Len()+1)
m := ms.At(me.Len()-1)
// fill m
```

I guess it's a rare use case to be creating individual elements rather than iterating through a set (that may be very large), so I can see why you don't want to pollute the public api.

For my purposes, I can just use a helper function to achieve the same thing. Feel free to close this ticket if you don't want to add this.

**Comment by bogdandrutu** [comment]
Closing this for the moment. We can revisit if we find more cases like this.
