### ISSUE TITLE
Auto detect the host resource and apply to metrics generated by receivers

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#871]
When the Collector is running as an agent and collecting system metrics (see the `hostmetricsreceiver`), or metrics from applications running on the host machine, there is a need to include resource information from the host in the generated metrics. Resource information can currently be added from config using the Resource processor or added using custom logic in an exporter, but it would be useful to have the option to automatically detect resource information from the host (e.g. from an env variable or from aws, gcp, etc metadata) and insert this into metrics when they are created.

**Detecting Resource Information:**

**Option 1:** Clone https://github.com/census-ecosystem/opencensus-go-resource and repurpose to return an OpenTelemetry resource (Go SDK format) instead of an OpenCensus one (and ensure it follows the expected semantic conventions). Reference this from the core repo (or implement it here directly). This will mean the Core repo has at least an indirect dependency on vendor specific code (such as "github.com/aws/aws-sdk-go/aws/ec2metadata" & "cloud.google.com/go/compute/metadata") - not sure if that is okay?

**Option 2:** Implement a simple `ResourceDetector` interface in the Core repo (including the default `FromEnv` implementation), with a function to allow adding custom detectors - custom detectors can then live as separate modules in the Contrib repo (and could be shared with the Go SDK in the future if similar auto-detection is implemented there).

```go
type ResourceDetector interface {
    Detect(ctx context.Context) (*resource.Resource, error) // from "go.opentelemetry.io/otel/sdk/resource"
}

func AddDetector(detector ResourceDetector) { ... }

// for each added ResourceDetector, call Detect() & return resolved resource
func AutoDetect(ctx context.Context) (*resource.Resource, error) { ... }
```
_This is somewhat similar to what was done in the OpenCensus Go SDK [here](https://github.com/census-instrumentation/opencensus-go/blob/master/resource/resource.go) - maybe it makes more sense for this code to live in the OpenTelemetry Go SDK?_ 

**Making Resource Information available to Components:**

**Option A:** Let each component that needs resource information access it via a call to global `AutoDetect()` function on startup.
**Option B:** Make resource information accesible via `component.Host` - add a `GetResource()` function to this interface & instantiate the resource value when creating the `Application` struct.

Regardless of the approach, it would be straightforward to add an option to the existing Resource processor to automatically apply the auto-detected resource info, rather than statically configured info, if desired (though I'll leave the implementation of this until someone has a need for it).

---

Under the assumption that referencing vendor code in the Core repo is frowned upon, and given it seems to make sense that the detected resource information is tied to the host object, I'm planning to implement Option 2B

**Comment by james-bebbington** [comment]
@bogdandrutu @tigrannajaryan - I don't think there's a huge amount of work to be done here, but I updated the ticket description if you could take a look and let me know if that makes sense.

**Comment by jrcamp** [comment]
> This is somewhat similar to what was done in the OpenCensus Go SDK here - maybe it makes more sense for this code to live in the OpenTelemetry Go SDK?

That's a good point. Could people want to auto detect resource labels when instrumenting code that's not running on a physical/virtual host? Serverless maybe?

**Comment by jrcamp** [comment]
> Option B: Make resource information accesible via component.Host - add a GetResource() function to this interface & instantiate the resource value when creating the Application struct.

This will require ensuring individual receivers adhere to calling GetResource() and using it correctly. Ideally the individual receivers wouldn't have to know anything about it. I was thinking the processor would call the autodetect method at startup. I think adding it as an option to the existing resource processor makes sense.

**Comment by james-bebbington** [comment]
> That's a good point. Could people want to auto detect resource labels when instrumenting code that's not reporting to a collector on the physical/virtual host? Serverless maybe?

Given that we support exporting directly from the SDKs to a (non-Agent) BE, I would think that we should also support auto-detecting the resource in the SDK

> This will require ensuring individual receivers adhere to calling GetResource() and using it correctly. Ideally the individual receivers wouldn't have to know anything about it. I was thinking the processor would call the autodetect method at startup. I think adding it as an option to the existing resource processor makes sense.

Isn't it roughly similar either way? Components (in this case the resource processor) either call `AutoDetect(ctx)` or `host.GetResource()` on startup. I slightly prefer storing the resource against the host as it a) feels logically correct for this to be tied to the host, and b) doesn't rely on a global function

**Comment by james-bebbington** [comment]
Example code: https://github.com/james-bebbington/opentelemetry-collector/pull/1

**Comment by rghetia** [comment]
> This is somewhat similar to what was done in the OpenCensus Go SDK [here](https://github.com/census-instrumentation/opencensus-go/blob/master/resource/resource.go) - maybe it makes more sense for this code to live in the OpenTelemetry Go SDK?

Agreed. The interface should be in OTel SDK. Vendor specific detectors can then be included either in the collector or directly with the SDK.

**Comment by james-bebbington** [comment]
See https://github.com/open-telemetry/oteps/pull/111

**Comment by tigrannajaryan** [comment]
>Resource information can currently be added from config using the Resource processor or added using custom logic in an exporter, but it would be useful to have the option to automatically detect resource information from the host (e.g. from an env variable or from aws, gcp, etc metadata) and insert this into metrics when they are created.

@james-bebbington Why can't this be done in a processor? A processor in a metric pipeline can automatically detect the host information and add that information to all metrics in that pipeline. You will need to have a separate pipeline for metrics collected from the localhost which I think is fine.

**Comment by james-bebbington** [comment]
> James Bebbington Why can't this be done in a processor? A processor in a metric pipeline can automatically detect the host information and add that information to all metrics in that pipeline. You will need to have a separate pipeline for metrics collected from the localhost which I think is fine.

Sure, this could be done in a processor. The only reason for suggesting otherwise is that its conceptually nicer (and loosely more consistent with the SDKs) if resource information is included at the time the metric is "created". I was envisioning doing both since this could be easily shared, e.g.: https://github.com/open-telemetry/opentelemetry-collector/pull/1059#discussion_r433111748

The main concerns of this proposal though are around 1. Avoiding including cloud-vendor specific code in the Core repo, and 2. Making an interface that is compatible with the Go SDK. That would still be relevant if the resource info is appended in a processor. If we don't need to be concerned with either of those points, then we could just:

- Add an "auto-detect" option to the existing resource processor
- Put code to auto-detect the resource directly in this processor

Maybe I can draft that up now, and we can consider refactoring later depending on the outcome of the OTEP.

**Comment by tigrannajaryan** [comment]
>if resource information is included at the time the metric is "created".

Wouldn't this require _every_ receiver that create metrics obtained locally to be aware of this concept and apply it to the metric data it creates? Seems like poor separation of concerns to me.

I am not convinced that the core repo and Service are the right place to implement this.

Functionally the desired functionality sounds like a processor to me and probably a separate one, not the existing resource processor. It can live in the contrib. That way it be a clear separation of concerns. None of existing receivers or processors or main Service need to know anything about auto-detection of host resources.

Happy to hear arguments and be convinced otherwise.

**Comment by james-bebbington** [comment]
@bogdandrutu mentioned one potential concern with doing this in a Processor is that if you have a receiver configured to go to two pipelines, and use a processor to append resource info (i.e. modify the data), the metrics would need to be copied into each pipeline.

But otherwise a processor in Contrib sounds reasonable to me

**Comment by tigrannajaryan** [comment]
That's a correct observation and applies to [any processor that modifies data](https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#data-ownership). I think that's acceptable. Please feel free if you want to double check to see what the performance implications of that are. If it has a big impact I am open to reconsider this.

**Comment by tigrannajaryan** [comment]
We have a resource detection processor that seems to serve the purpose. Closing, feel free to reopen if there is more work expected to be done.
