### ISSUE TITLE
Support component specific flags

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#873]
Hi, 

in Jaeger project we are extending OTEL collector by adding Jaeger storage exporters and we are also exposing component-specif flags (e.g. sampling strategies file, `--es.server-urls` and so on).
The motivation is to provide a smooth migration from Jaeger collector to our build of OTEL collector. 
The Jaeger OTEL collector uses a specific configuration if the conf file is missing and the components in this configuration can be configured via flags (it does not fail to start if the config is missing).

Are there any plans to support component-specific flags in the OTEL collector? Was there any previous discussion relate to component-specific flags? 

OC collector used to support enabling/disabling of some components https://github.com/census-instrumentation/opencensus-service#usage-1

**Comment by tigrannajaryan** [comment]
I do not quite understand. What is a component specific flag? Is this about command line flags that are passed onto the components? Can you expand a bit on how you want to use this for Jaeger collector?

**Comment by pavolloffay** [comment]
> What is a component specific flag

It is a flag used to configure any receiver/processor/exporter. For example it can be `--batch.send_batch_size` https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#batch-processor.

>  Can you expand a bit on how you want to use this for Jaeger collector?

In [Jaeger OTEL collector](https://github.com/jaegertracing/jaeger/tree/master/cmd/opentelemetry-collector) we have implemented storage layer as exporters. These exporters can be configured by flags e.g. `--es.server-urls` or in the OTEL config file (higher precedence). 

The motivation is to create drop-in replacement for the current Jaeger collector that is configured by flags. The old Jaeger collector supports also configuring sampling strategies or receiver and exporter by flags and the issue is that these components are hosted in this repository. I have submitted a PR that wraps Jaeger receiver and exposes some configuration as flags.

https://github.com/jaegertracing/jaeger/pull/2195/files#diff-b87cefb261d172e43035631619ee62a2R49

My question here is whether components in OTEL will ever expose any flags? If so we should sync for any compatibility reasons.

**Comment by tigrannajaryan** [comment]
@pjanotti do you remember? I think we had an ability to specify the config via command line options (or was it the opposite?). I don't quite remember.

**Comment by pjanotti** [comment]
@tigrannajaryan I don't recall the details from the top of my head but Viper supports integration with of flags and environment variables. The way that the components were reading the config facilitated that and many of the options were available either as flags or env vars. That was lost when the code was refactored to the "new config" - in principle it should be possible to re-enabled again, but once more I don't remember the details (we may need to use reflection on the config structures to proper setup Viper)

**Comment by tigrannajaryan** [comment]
I think it will be useful to be able to provide specific config options via the command line.

For this to be unambiguous we will likely need to use the full path in the yaml. I.e. to specify the batch size for the batch processor we would use `--processors.batch.send_batch_size=123`. This would also limit the pollution of the command line flag namespace, basically limiting it to the currently defined 5 top-level config keys (exporters, receivers, processors, extensions, service).

I am also not sure how escaping should be done for keys that contain weird characters like `/`. Is it a valid character in the command line flag name?

If there is anyone willing to undertake this it is open for grabs.

**Comment by pavolloffay** [comment]
The `/` seems to work with cobra. With a simple test I got a response `Error: unknown flag: --foo.bar/my`. Though I am not sure if that works on Windows.

Do we intend to provide flags for all components, even for named instances e.g. `processors.batch/second_instance`? To make this work we would have to parse the config before running the cobra command and add flags dynamically. My understanding is that cobra requires to initialize all flags before running the command.

**Comment by jrcamp** [comment]
A common way this is handled (e.g. git, helm) is to just have a single `--set` flag. So you'd do `--set processors.batch.send_batch_size 123`. This also avoids any potential issues with `/` being in the flag name as well as polluting the flag set.

**Comment by pavolloffay** [comment]
This approach makes sense to me since we don't know all the flags at startup (without parsing the conf file) and it also does not pollute help command.

Do we know if that works with cobra OOTB?   

@tigrannajaryan are you fine with that?

**Comment by pavolloffay** [comment]
I have started looking into this and I would like to share some observations:

The `--set` flag with multiple values can be added via `pflag` package e.g. `flagSet.StringArray("set",...`. Then the values can be obtained via `app.rootCmd.Flags().GetStringArray("set")`. 

The next step was to merge these values obtained as `processors.batch.timeout=1s` into the viper that loded the configuration file. It can be done via `v.MergeConfig`, but it requires to change the config type to `properties`. However, this does not work as expected. The merge fails if the original config file does not contain leaf properties e.g.  the following config

```yaml
processors:
  batch:
```

will fail to merge with `processors.batch.timeout=2s`.

As a workaround instead of merging the files the flags could use the new viper instance and modify the existing configs created by the `config.Load` when the main config file was loaded.
