### ISSUE TITLE
Triager role request for @songy23

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#8742]
Formal request to grant triager scope to @songy23, I'd like to help with issue triaging in core. I'm an approver for the [contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/) repo and am in the [Emeritus Approvers](https://github.com/open-telemetry/opentelemetry-collector#contributing) list in this repo.

**Comment by songy23** [comment]
cc @open-telemetry/collector-approvers

**Comment by djaglowski** [comment]
I support

**Comment by mx-psi** [comment]
I support

**Comment by jpkrohling** [comment]
I support too!

**Comment by atoulme** [comment]
I support

**Comment by dmitryax** [comment]
I support

**Comment by codeboten** [comment]
Thanks @songy23, I support 👍🏻

**Comment by bogdandrutu** [comment]
+1

**Comment by bogdandrutu** [comment]
@songy23 please open a PR

**Comment by songy23** [comment]
https://github.com/open-telemetry/opentelemetry-collector/pull/8744 Thanks folks! 🚀
