### ISSUE TITLE
[cmd/builder] Use runtime.DebugInfo to show version

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8770]
As suggested in https://github.com/gordonklaus/ineffassign/issues/53#issuecomment-753688189 we can use `runtime.DebugInfo` to get the version when installing via `go install`. This avoids the confusion of #8691. We should check our official builds to avoid breaking the version on non-`go install` binaries (in the worst case, we can check which of the two we are in)

**Comment by devoc09** [comment]
@mx-psi Hi! Is it okay if I take on this issue?

**Comment by mx-psi** [comment]
@devoc09 assigned to you :)

**Comment by atoulme** [comment]
Closing as completed, thanks!
