### ISSUE TITLE
Grafana explore link does not support grafana 10.

### ISSUE THREAD

**Issue by weeTyphoon** [open-telemetry/opentelemetry-collector#8772]
**Describe the bug**
On the "view pipeline" link in the Jenkins job, the link constructed for Grafana is the version 9 format and not the version 10 format.

**Steps to reproduce**
Configure the plugin to point to a current grafana cloud stack.
Push a build trace there,
Click the link tothe build trace - the grafana 10.2 in the cloud today does not like the format of the explore link and rewrites it to the "proper" format but drops some important information like the trace ID.

**What did you expect to see?**
I thought I would get to my trace, but I get a blank explore view.

**What did you see instead?**
The explore view is blank

**What version did you use?**
Jenkins 2.401.3
Opentelemetry plugin 2.18.0
Grafana 10.2 (current cloud instance)

**What config did you use?**
NA

**Environment**
Unknown, this jenkins is hosted for me; some Linux I think.

**Additional context**
I think the Grafana 10 format is more like: 
https://mystack.grafana.net/explore?orgId=1&panes=%7B%22pane%22:%7B%22datasource%22:%22grafanacloud-traces%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22grafanacloud-traces%22%7D,%22queryType%22:%22traceql%22,%22limit%22:20,%22tableType%22:%22traces%22,%22query%22:%2213ef3429e973cc9d065b176c33168a0f%22%7D%5D,%22range%22:%7B%22from%22:%221698262198636%22,%22to%22:%221698263398636%22%7D%7D%7D&schemaVersion=1

In the GrafanaBackend.java I think the construction of the URL is like this:
        String grafana10URL =  "${" + TemplateBindings.GRAFANA_BASE_URL + "}" +
            "/explore?orgId="+
            TemplateBindings.GRAFANA_ORG_ID+
            "&panes=%7B%22pane%22:%7B" +
            "%22datasource%22:%22"+
            TemplateBindings.GRAFANA_TEMPO_DATASOURCE_IDENTIFIER +
            "%22,%22queries%22:%5B%7B"+
            "%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,"+
            "%22uid%22:%22"+
            TemplateBindings.GRAFANA_TEMPO_DATASOURCE_IDENTIFIER +
            "%22%7D,"+
            "%22queryType%22:%22"+
            TemplateBindings.GRAFANA_TEMPO_QUERY_TYPE +
            "%22,%22limit%22:100,%22tableType%22:%22traces%22,"+
            "%22query%22:%22"+
            "${traceId}" +
            "%22%7D%5D,"+
            "%22range%22:%7B%22from%22:%22"+
            "${" + TemplateBindings.START_TIME + ".minusSeconds(600).atZone(java.util.TimeZone.getDefault().toZoneId()).toInstant().toEpochMilli()}" +
            "%22,%22to%22:%22"+
            "${" + TemplateBindings.START_TIME + ".plusSeconds(600).atZone(java.util.TimeZone.getDefault().toZoneId()).toInstant().toEpochMilli()}" +
            "%22%7D%7D%7D&schemaVersion=1";

But I don't see a mechanism to choose a grafana target version. I'm not sure if you would add that or just keep up with the latest grafana syntax.

**Comment by weeTyphoon** [comment]
In the time that I created the documentation and tracked down what was goin on here, something changes in Grafana. I know in the cloud they deploy little changes all the time, so maybe this URL rewrite was causing other problems elsewhere? In any case it seems to "work" now, though my URL is still rewritten:
`https://mystack.grafana.net//explore?orgId=1&left={"datasource":"grafanacloud-traces","queries":[{"refId":"A","datasource":{"type":"tempo","uid":"grafanacloud-traces"},"queryType":"traceql","query":"13ef3429e973cc9d065b176c33168a0f"}],"range":{"from":"1698262198636","to":"1698263398636"}}`
from the Jenkins link becomes
`https://mystack.grafana.net/explore?orgId=1&panes={"_5q":{"datasource":"grafanacloud-traces","queries":[{"refId":"A","datasource":{"type":"tempo","uid":"grafanacloud-traces"},"queryType":"traceql","query":"13ef3429e973cc9d065b176c33168a0f","limit":20,"tableType":"traces"}],"range":{"from":"1698262198636","to":"1698263398636"}}}&schemaVersion=1`

So maybe instead of a bug this should be a feature request to update the link generator to match the new format more closely? Notice the new schema includes a pager limit variable not supported in the current plugin.

**Comment by yurishkuro** [comment]
> On the "view pipeline" link in the Jenkins job

what Jenkins job?

**Comment by mx-psi** [comment]
@weeTyphoon Are you using the OpenTelemetry Collector in your setup or is this a Grafana-specific issue? If it's the latter, please reach out to Grafana support (cc @jpkrohling who may be able to confirm that this is a Grafana-specific issue)

**Comment by jpkrohling** [comment]
This is a bit confusing to me as well. But perhaps @cyrille-leclerc can help here? Perhaps this is a bug in the Jenkins plugin for OTel?

**Comment by cyrille-leclerc** [comment]
@weeTyphoon thanks for using the Jenkins OpenTelemetry plugin and Grafana.

This bug has been fixed in the latest Jenkins OpenTelemetry plugin version https://github.com/jenkinsci/opentelemetry-plugin/releases/tag/opentelemetry-2.19.0

I just cut the release today but w have been having a release candidate for a while.

**Comment by mx-psi** [comment]
Thanks all! I am going to close this as wontfix since it is not related to the Collector. For further discussion, please open a bug on the Jenkins OpenTelemetry plugin repository as stated above :)

**Comment by weeTyphoon** [comment]
Sorry I missed the notifications and could not clarify that I am using the link from the plugin to go directly to grafana for traces, but thanks for your attention and the fix.
