### ISSUE TITLE
Implement OTLP/HTTP receiver

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#881]
See protocol spec https://github.com/open-telemetry/oteps/blob/master/text/0099-otlp-http.md

This needs to listen on the same port as existing OTLP/gRPC and be part of the same "otlp" receiver.

**Comment by tigrannajaryan** [comment]
See a similar protocol implementation as an example: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/sapmreceiver

**Comment by kirbyquerby** [comment]
May I work on this?

**Comment by tigrannajaryan** [comment]
@kirbyquerby sure, that would be great! I think this is going to be your first contribution, so please read https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#coding-guidelines

**Comment by tigrannajaryan** [comment]
@kirbyquerby if there is anything unclear in the OTLP/HTTP spec please let me know, I will be happy to clarify.

**Comment by odeke-em** [comment]
Just for a bit of current context, in the collector https://github.com/open-telemetry/opentelemetry-collector/blob/86c72c282d3813f4a404f18145a57e6dda1537af/receiver/opencensusreceiver/opencensus.go#L211-L222
we've already got HTTP(1.1, 2.0) + JSON being received, perhaps this issue could be to expand and receive content that's protobuf as well, or perhaps please update that @tigrannajaryan in the prior art section? We use that endpoint over HTTP to receive traces and metrics from OpenCensus-Web plus other apps like Go tools telemetry.

**Comment by tigrannajaryan** [comment]
@odeke-em I think you are referring to gRPC-Web transport, right? I am not familiar with it but from what I remember it allows to use JSON representation of ProtoBufs to make the life of webapps easier (correct me if I am wrong). I think we should be able to support it on the same receiver port but for now OTLP/HTTP only specifies the behavior for binary Protobuf payloads. We can extend OTLP spec to allow JSON payloads too.

**Comment by tigrannajaryan** [comment]
I suggest that in the scope this issue we implement what the spec says and we can add JSON payload support later.

**Comment by tigrannajaryan** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-collector/pull/1021
