### ISSUE TITLE
Implement OTLP/HTTP exporter

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#882]
See spec https://github.com/open-telemetry/oteps/blob/master/text/0099-otlp-http.md

This likely should be part of the existing "otlp" exporter and the transport may be selectable via a config option.

**Comment by tigrannajaryan** [comment]
See a similar protocol implementation as an example https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/sapmexporter

**Comment by kirbyquerby** [comment]
May I work on this?

**Comment by tigrannajaryan** [comment]
@kirbyquerby yes, please!

**Comment by tigrannajaryan** [comment]
@kirbyquerby do you still plan to work on this?

**Comment by tigrannajaryan** [comment]
@bogdandrutu assigning this to you since you started working on it.

**Comment by tigrannajaryan** [comment]
Basic implementation is ready: https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/otlphttpexporter
Closing. Create new issues for improvements.
