### ISSUE TITLE
Reference to Deprecated Metrics

### ISSUE THREAD

**Issue by AuHoppe** [open-telemetry/opentelemetry-collector#8835]
**Issue:**
The v2 release of `kube-state-metrics` removes several deprecated metrics. Documentation here [is referencing](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md?plain=1#L19) the obsolete (and removed) `kube_pod_container_resource_limits_cpu_cores` form.

**Additional Context:**
Referenced at: https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/README.md#metrics-deprecation

**Resolution:**
`docs/monitoring.md` should have its reference updated to the new form of this metric:
`kube_pod_container_resource_limits_cpu_cores` ~ `kube_pod_container_resource_limits{resource="cpu",unit="core"}`

**Comment by victorhauvi** [comment]
Hello, I would love to have this issue assigned to me.
