### ISSUE TITLE
[docs] Remove docs/design.md

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8889]
I think we should remove [docs/design.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md) in favor of the docs in opentelemetry.io.

The document is outdated in some regards (connectors), does not receive a lot of traffic (the only page within the [top 10 pages by traffic in this repo](https://github.com/open-telemetry/opentelemetry-collector/graphs/traffic) within `docs/` is the troubleshooting page) and information in this document is already covered on https://opentelemetry.io/docs/collector/configuration and https://opentelemetry.io/docs/collector/deployment.

I would like @open-telemetry/docs-approvers to chime in here and give us their opinion.

**Comment by mx-psi** [comment]
cc @bogdandrutu @tigrannajaryan @songy23 since you were involved in creating this doc, in case you think it's worth keeping in some form

**Comment by svrnm** [comment]
I am all in for having this on the website, since those are mostly end-user specific information. We have some of that on the website already, but some details / diagrams could make the existing docs better.

@mhausenblas @theletterf please take a look as well

**Comment by mhausenblas** [comment]
Agreed with @svrnm!

**Comment by tigrannajaryan** [comment]
> but some details / diagrams could make the existing docs better.

+1 to this. The [docs/design.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md) has diagrams that  https://opentelemetry.io/docs/collector/configuration  does not. I find the diagrams helpful for understanding.

**Comment by mx-psi** [comment]
Filed open-telemetry/opentelemetry.io/issues/3547 to move the diagrams

**Comment by theletterf** [comment]
Agree with moving this documentation. Do we support Mermaid diagrams or similar in OpenTelemetry.io? I'm tempted to add it to Docsy otherwise.

**Comment by cartermp** [comment]
Specifically, I think this can be a top-level doc under the collector folder, perhaps just called `architecture`. We can then merge in/remove content either as a part of that PR or later.

**Comment by mhausenblas** [comment]
> Specifically, I think this can be a top-level doc under the collector folder, perhaps just called architecture. We can then merge in/remove content either as a part of that PR or later.

+1 to `docs/collector/architecture` and maybe (in terms of left-hand side menu) right before "Building a custom collector"? Also, we should set clear expectations who the target audience is.

**Comment by lavishpal** [comment]
Could you assign this issue to me ?
