### ISSUE TITLE
[docs] Move processing.md to a more appropriate place

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8893]
The [docs/processing.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md) document describes OTTL and the transform processor design and desiderata. 

I want to propose moving this document to contrib to `processor/transformprocessor/rfc.md` where I think it fits best, since the `docs/` folder on opentelemetry-collector has become an all-catch folder. 

Alternatively, we could move it to a `docs/rfc` or `docs/proposal` folder here to make it clear it is a historical document for designing the transform processor.

Codeowners of the transform processor (@TylerHelmuth, @kentquirk, @bogdandrutu, @evan-bradley), what do you think?

**Comment by evan-bradley** [comment]
I think it would be okay to simply remove this. @TylerHelmuth and I recently had an offline discussion about repurposing or moving this document, but now that I look closer I don't think it's needed. OTTL's existing docs already cover the majority of information in it and could be easily updated to include the pieces that aren't.

I'm not sure it would have much value as a historical document, but I'm open to other opinions on that.

**Comment by mx-psi** [comment]
> I'm not sure it would have much value as a historical document, but I'm open to other opinions on that.

We always have git history for this :) I filed #8925 to just remove it if that's an acceptable option

**Comment by mx-psi** [comment]
Since #8925 didn't land, I filed #9828 instead
