### ISSUE TITLE
Generic way for components to expose HTTP APIs

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#893]
For some new [extensions](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/extension/observer/k8sobserver) and [receivers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/receivercreator) they have state that we want to query at runtime that is not easily modeled through traces. 

This proposes have a generic way for components to optionally hook into an HTTP endpoint. It uses standard library Go with no additional dependencies. A component opts-in by implementing the `APIMux` interface:

```go
type APIMux interface {
	APIMux() *http.ServeMux
}
```

The component instance returns its own [mux](https://golang.org/pkg/net/http/#ServeMux) with routes specific to it. For example:

```go
mux.HandleFunc("/status", func(writer http.ResponseWriter, request *http.Request) {
 // returns some custom state
})
```

If this was part of an extension called `foo/1` it would then be accessible by fetching `http://localhost:<port>/extensions/foo/1/_/status`. Similarly if you had a receiver called `baz/a` it would be located at `http://localhost:<port>/receivers/baz/a/_`.

The `_` is there to separate custom routes provided by the specific component from generic endpoints the collector itself may want to provide in the future.

The implementation from the agent is fairly simple. It starts an `http.Server` and wires up any mux returned by components implementing `APIMux`. In the future the agent may provide additional common functionality (perhaps a UI) but for now this just creates the skeleton and everything will be namespaced under `_` to avoid any possible collisions in the future.

**Comment by atoulme** [comment]
Can we consider closing this issue as Won't Fix? We now have confighttp which handles creating http.Server objects for receivers.
