### ISSUE TITLE
Question about  Mb saved/s data for benchmark data

### ISSUE THREAD

**Issue by HackToday** [open-telemetry/opentelemetry-collector#8943]
**Describe the bug**
This may not bug, I checked with https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md

It have one column `Mb saved / second`,  I could not figure it out, how can that value be calculated from metrics: `raw_byte` `compressed_byte`  `ns/op`.

For example, this data below:

| Request           | Compressor | Raw Bytes | Compressed bytes | Compression ratio | Ns / op | Mb compressed / second | Mb saved / second |
|-------------------|------------|-----------|------------------|-------------------|---------|------------------------|-------------------|
| lg_log_request    | gzip       | 5150      | 262              | 19.66             | 49231   | 104.61                 | **_99.29_**             |

**Steps to reproduce**
N/A

**What did you expect to see?**
N/A

**What did you see instead?**
N/A

**What version did you use?**
main branch

**What config did you use?**
N/A
**Environment**

N/A

**Additional context**
N/A

**Comment by jpkrohling** [comment]
This comes from this benchmark, which has the same payload being compressed with different compressors:

https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/configgrpc_benchmark_test.go
