### ISSUE TITLE
Map() does not panic on zero-initialized value

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector#9025]
**Describe the bug**
The following code will not cause a panic:
```
var test pcommon.Value

func main() {
	test.Map()
}
```
 although the doc states:

> Calling this function on zero-initialized Value will cause a panic.

**Steps to reproduce**
```
package main

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

var test pcommon.Value

func main() {
	test.Map()
}
```

**What did you expect to see?**
A Panic.

**What did you see instead?**
No Panic.

**What version did you use?**
```
require go.opentelemetry.io/collector/pdata v1.0.0
```

**Comment by dmitryax** [comment]
It returns a zero-initialized map which will panic after being used. Unless say the comment says it panics right away, it's close to be true :)

We may complicate the logic and make sure it panics right away, but I'm not sure it worth it. Maybe just updating the comment is good enough. Something like

```
// Map returns the map value associated with this Value.
// If the function is called on zero-initialized Value or if the Type() is not ValueTypeMap 
// then it returns an invalid map. Note that using such map can cause panic.
```

**Comment by mackjmr** [comment]
> Maybe just updating the comment is good enough.

Agreed that updating the comment should be good enough 👍

**Comment by dmitryax** [comment]
@mackjmr I updated all the comments in value.go, but it might be the same issue for other structs. I'd great if you can submit another issue or help with resolving them as well
