### ISSUE TITLE
Stabilize module confignet

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#9045]
Before stabilizing a module, an approver or maintainer must make sure that the following criteria have been met for at least two successive minor version releases:

- [x] No open issues or PRs in the module that would require breaking changes
- [x] No TODOs in the module code that would require breaking changes
- [x] No deprecated symbols in the module
- [x] No symbols marked as experimental in the module
- [x] The module follows the [Coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)

Please also make sure to publicly announce our intent to stabilize the module on:

- [x] The #otel-collector CNCF Slack Channel
- [x] The #opentelemetry CNCF Slack channel
- [x] A Collector SIG meeting (if unable to attend, just add to the agenda)

To help other people verify the above criteria, please link to the announcement and other links used to complete the above in a comment on this issue.

Once all criteria are met, close this issue by moving this module to the `stable` module set.

**Comment by codeboten** [comment]
Open issues regarding confignet:
- [ ] https://github.com/open-telemetry/opentelemetry-collector/issues/4331

**Comment by dmitryax** [comment]
I think we should have 1.0 milestones for each module that we want to release as 1.0 so we can include all the issues there

**Comment by mx-psi** [comment]
@codeboten I think it would be helpful to have links as in #8978 so that right before marking as 1.0 one can quickly check that we did not accidentally introduce any new TODOs or experimental symbols

**Comment by atoulme** [comment]
We need to address the new comments in https://github.com/open-telemetry/opentelemetry-collector/pull/7954 as well.

**Comment by mx-psi** [comment]
Filed #9159 to add this to coding guidelines

**Comment by atoulme** [comment]
I see the comments in #7954 have been acted upon with #9105 - can we move to announce stabilization intent, anything else left to consider?

**Comment by mx-psi** [comment]
Should we remove `Context` from the method names? (That is, effectively just add `context.Context` to the original methods?)

**Comment by codeboten** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/pull/9258

**Comment by codeboten** [comment]
Blocked by the stabilization work for confmap

**Comment by atoulme** [comment]
Is this now unblocked since confmap was just declared stable?
