### ISSUE TITLE
Stabilize module consumer

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#9046]
Before stabilizing a module, an approver or maintainer must make sure that the following criteria have been met for at least two successive minor version releases:

- [x] No open issues or PRs in the module that would require breaking changes
- [x] No TODOs in the module code that would require breaking changes
- [x] No deprecated symbols in the module
- [x] No symbols marked as experimental in the module
- [x] The module follows the [Coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)

Please also make sure to publicly announce our intent to stabilize the module on:

- [x] The #otel-collector CNCF Slack Channel
- [x] The #opentelemetry CNCF Slack channel
- [x] A Collector SIG meeting (if unable to attend, just add to the agenda)

To help other people verify the above criteria, please link to the announcement and other links used to complete the above in a comment on this issue.

Once all criteria are met, close this issue by moving this module to the `stable` module set.

**Comment by atoulme** [comment]
`git grep TODO` gives no results
`git grep Deprecated` gives no results

**Comment by atoulme** [comment]
Published intent on #otel-collector CNCF Slack Channel:
https://cloud-native.slack.com/archives/C01N6P7KR6W/p1703026224363709 
Published intent on #opentelemetry CNCF Slack channel:
https://cloud-native.slack.com/archives/CJFCJHG4Q/p1703026318636549

**Comment by atoulme** [comment]
Scheduled for SIG meeting 9am 12/19. Please feel free to attend and bring up any items for discussion, your feedback is helpful.

**Comment by atoulme** [comment]
I have not identified any open issues on this repository related to this module.

**Comment by TylerHelmuth** [comment]
I believe issues are being tracked in https://github.com/open-telemetry/opentelemetry-collector/milestone/31

**Comment by atoulme** [comment]
Looks like the milestone doesn't track PRs, just issues. Do we need to reopen #8833?

**Comment by atoulme** [comment]
Discussed with maintainers, we can for now not reopen #8833 and keep it out of scope of the consumer 1.0 package.
