### ISSUE TITLE
Leaking goroutine in memorylimiterprocessor

### ISSUE THREAD

**Issue by jskiba** [open-telemetry/opentelemetry-collector#9099]
**Describe the bug**
Memorylimiter processor never leaves that loop https://github.com/open-telemetry/opentelemetry-collector/blob/1d0d1ef21baebfcc9ed1d67f0237437ceb9a0049/processor/memorylimiterprocessor/memorylimiter.go#L230C1-L230C1. In result this goroutine or many of them leak every time after shutdown procedure.

**Steps to reproduce**
https://github.com/jskiba/opentelemetry-collector/commit/2f8ee15b03a84739acbdd62bc87c4691b703800b
The only leaking goroutine is the one from this bug https://github.com/open-telemetry/opentelemetry-collector/issues/8945.

**What did you expect to see?**
No leaking goroutine and correct exit from for loop.

**What did you see instead?**
Goroutine https://github.com/open-telemetry/opentelemetry-collector/blob/1d0d1ef21baebfcc9ed1d67f0237437ceb9a0049/processor/memorylimiterprocessor/memorylimiter.go#L229 never exits. When a ticker is stopped it does not return information that it was closed, different mechanism should be used.

**What version did you use?**
[1d0d1ef](https://github.com/open-telemetry/opentelemetry-collector/commit/1d0d1ef21baebfcc9ed1d67f0237437ceb9a0049)

**What config did you use?**
not applicable

**Environment**
OS: Debian 12.4 bookworm
Compiler(if manually compiled): go 1.21.5"

**Additional context**
---

**Comment by dmitryax** [comment]
@jskiba thanks for reporting. Do you have a chance to help with a PR?

**Comment by jskiba** [comment]
@dmitryax it's already approved https://github.com/open-telemetry/opentelemetry-collector/pull/9100
