### ISSUE TITLE
[confignet] Update public methods to accept `context.Context`

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9105]
> It looks like the net authors let net.Dial and net.DialTimeout use context.Background() and expect users to use net.DialContext()

They are legacy, because net was added before context. I think we should have a rule of thumb that all our public APIs should accept Context. This is not yet 1.0 so we can fix that here.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/9066#discussion_r1424591736_

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-triagers please add this to  https://github.com/open-telemetry/opentelemetry-collector/milestone/54

**Comment by codeboten** [comment]
>I think we should have a rule of thumb that all our public APIs should accept Context. This is not yet 1.0 so we can fix that here.

@bogdandrutu are you suggesting this for all APIs or specifically around the confignet package?

**Comment by mx-psi** [comment]
> > I think we should have a rule of thumb that all our public APIs should accept Context. This is not yet 1.0 so we can fix that here.
> 
> @bogdandrutu are you suggesting this for all APIs or specifically around the confignet package?

I feel like we should have this for all APIs that do or can do anything related to networks or filesystems
