### ISSUE TITLE
Decide what to do w/ mapstructure library

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#9161]
The library is going to be deprecated and a few options for existing forks are coming up. Should we move to another fork, fork it ourselves?

See https://github.com/mitchellh/mapstructure/issues/349

**Comment by codeboten** [comment]
One of the options for existing forks: https://github.com/go-viper/mapstructure

**Comment by mx-psi** [comment]
Trying to get #6671 fixed upstream and seeing how it goes could be a good test to see how receptive the new owners are to our use case

**Comment by atoulme** [comment]
I am offering that we switch over to the fork which will be maintained moving forward: https://github.com/open-telemetry/opentelemetry-collector/pull/9634

**Comment by TylerHelmuth** [comment]
Since we've taking the forked version can we close this issue?

**Comment by mx-psi** [comment]
Will close it once we merge #9635, which fixes one of the things we were considering when tackling this issue
