### ISSUE TITLE
Consider enforcing https://github.com/uber-go/goleak in all tests

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#9165]
This will require fixing all existing leaks first.

Suggested in https://github.com/open-telemetry/opentelemetry-collector/pull/9100#issuecomment-1856422113

**Comment by crobert-1** [comment]
I've submitted a PR that adds `goleak` for all packages in which it's currently passing. Here's the complete list (that I'm aware of) of failing packages:
```
cmd/otelcorecol/
config/configgrpc/
config/configtls/
exporter/debugexporter/
exporter/exporterhelper/
exporter/exportertest/
exporter/internal/common/
exporter/loggingexporter/
exporter/otlpexporter/
exporter/otlphttpexporter/
internal/e2e/
internal/obsreportconfig/
obsreport/obsreporttest/
otelcol/
otelcol/otelcoltest/
processor/batchprocessor/
processor/memorylimiterprocessor/
processor/processorhelper/
receiver/otlpreceiver/internal/logs/
receiver/otlpreceiver/internal/metrics/
receiver/otlpreceiver/internal/trace/
receiver/otlpreceiver/
receiver/receiverhelper/
receiver/scraperhelper/
service/internal/proctelemetry/
service/
```

**Comment by crobert-1** [comment]
It looks like a pretty common cause of `goleak` failures is the `go.opencensus.io/stats/views` package, specifically the `start` [method](https://github.com/census-instrumentation/opencensus-go/blob/01e6da5fc01c42aca1e0ce315f41744876e9fcbb/stats/view/worker.go#L287). This is called by `init()`, so it's running in the background for any collector package that's importing the `go.opencensus.io` package, even indirectly.

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 21 in state select, with go.opencensus.io/stats/view.(*worker).start on top of the stack:
go.opencensus.io/stats/view.(*worker).start(0xc0001a7b80)
	/Users/crobert/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/Users/crobert/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
```

_I'm still investigating to better understand the impact and possible solution for this one cause of failures._

**Comment by yurishkuro** [comment]
We disabled check for opencensus worker in Jaeger because it starts via init() and not under control of the tests or any other code. Cf https://github.com/jaegertracing/jaeger/pull/5055/files#diff-13b40ba61afb4ff3b34affd949b1e9751f855f8c7f974e1896dc984aac2c212cR26

**Comment by yurishkuro** [comment]
There is a similar issue with glog, which we also ignored in goleak.

**Comment by crobert-1** [comment]
Once all packages enable `goleak`, the last work item to close this issue should be to require every package to have `goleak` enabled, by a CI script. This will allow us to catch new packages being added to make sure they don't get added without `goleak`.

We can use [this Jaegar PR](https://github.com/jaegertracing/jaeger/pull/5010) as a reference for how the check could work.

**Comment by crobert-1** [comment]
Just to note, here's the original opencensus issue for the leaking goroutine:
https://github.com/census-instrumentation/opencensus-go/issues/1191

**Comment by codeboten** [comment]
@crobert-1 can this issue be closed now that we're enforcing goleak checks (even with the exceptions currently in place) or is the expectation that all goleaks will be addressed before closing this issue?

**Comment by crobert-1** [comment]
We can probably close. Any time we have to skip `goleak` it's obvious that we're skipping in `metadata.yaml`. The only exception to this is that `goleak` may be missing for subdirectories, since it's not automatically generated. I've filed https://github.com/open-telemetry/opentelemetry-collector/issues/10420 for this.
