### ISSUE TITLE
Use `obsreport.StartMetricsReceiveOp/EndMetricsReceiveOp` in host scrapers

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#918]
From @james-bebbington:

Had a bit of a deeper look at this. From what I understand, obsreport is a helper package for generating standard traces & metrics for collector components, and currently uses the OpenCensus libraries for this.

A couple of questions if I want to use this here:

I'm not sure what to provide for the "transport" attribute value (third parameter of StartMetricsReceiveOp). These metrics are scraped from the host rather than being "received" as such so it doesn't seem applicable - is it okay to pass an empty string?
obsreport.CountMetricPoints is only implemented for the OC proto format. It probably needs a second implementation for the in-memory data structure rather than doing a transformation manually before calling that function (should be relatively straightforward to add this, but probably better done in a separate PR)

**Comment by james-bebbington** [comment]
To clarify:

1. `opsreport.StartMetricsReceiveOp`, and other opsreport metric functions, require passing a "transport" parameter that's used to set a corresponding attribute value. Consider making this optional
2. `obsreport.CountMetricPoints` takes a `consumerdata.MetricsData` parameter. Consider adding an alternative function that takes `data.MetricsData`

**Comment by james-bebbington** [comment]
Note #2 is not necessary as `pdatautil.MetricAndDataPointCount` already exists which does exactly the same thing and should be used instead
