### ISSUE TITLE
Add documentation or logging reminding people to enable configured extensions

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-collector#9195]
**Is your feature request related to a problem? Please describe.**
People (like myself) might forget to enable an extension after configuring it, like below:

```
extensions:
  health_check:

service:
 extensions: [health_check]
```

I don't think it's intuitive why you'd want to configure an extension but not enable it? Also, a lot of extensions' documentation omit the `service.extensions` part of their example yaml config, making people think they just need the `extensions` part.   

**Describe the solution you'd like**
- Update the READMEs to include the `service.extensions` yaml as a reminder
- Maybe add a warning/debug log to the collector if any extension is configured but not enabled. Possibly this is implemented by comparing the configured extensions in `otelcol.Config.Extensions` to the enabled extensions in `otelcol.Config.Service.Extensions` immediately after validating the config

**Additional context**
I can make any of the above changes

**Comment by atoulme** [comment]
You can say the same thing about exporters, receivers, processors or connectors. Just because they’re configured doesn’t guarantee they are going to be used in pipelines.

This is to allow a separation of concerns between configuration and execution I guess.

You could create a separate command to check if all components are used as a dry run validation.

**Comment by swar8080** [comment]
> You can say the same thing about exporters, receivers, processors or connectors. Just because they’re configured doesn’t guarantee they are going to be used in pipelines. This is to allow a separation of concerns between configuration and execution I guess.

I focused on extensions because they're most likely to accidentally configure but then not enable. Pipelines are front and centre in the documentation and most tutorials, so people are more likely to know they have to pick the pipelines for the other components. Since extensions aren't added to a pipeline it's less obvious they need to be enabled separately under `services`

> You could create a separate command to check if all components are used as a dry run validation.

In my case, I was just copy-pasting incomplete yaml from extensions' READMEs, so I likely wouldn't know that this command exists 

So I can go ahead and just update the READMEs for now, but lmk if you think the originally suggested code change makes sense too
