### ISSUE TITLE
Set gomaxprocs and gomemlimit automatically based on cgroup limits

### ISSUE THREAD

**Issue by tomershafir** [open-telemetry/opentelemetry-collector#9203]
Use https://github.com/uber-go/automaxprocs and https://github.com/KimMachineGun/automemlimit or implement alike for non-lib otelcol

**Comment by mx-psi** [comment]
@tomershafir Would this be feasible to have as an extension?

**Comment by tomershafir** [comment]
@mx-psi yes, it seems like the extension model fits. How would you think to address this, import the libs or copy them? for example I saw that you copied cgroup lib from automaxprocs

**Comment by mx-psi** [comment]
@tomershafir Importing the libs would work for me. I think this can be an extension in opentelemetry-collector-contrib, I would be happy to sponsor it. Can you [file a new component proposal in contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/new?assignees=&labels=Sponsor+Needed%2Cneeds+triage&projects=&template=new_component.yaml&title=New+component%3A+)? You can add me on the sponsor field, and we can let other people on the community comment on the idea first :)

**Comment by tomershafir** [comment]
@mx-psi done https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30289

**Comment by mx-psi** [comment]
Helm chart maintainers agree the proposed extension is a good idea, so I am going to close this one and we can continue the discussion and development over at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30289
