### ISSUE TITLE
[otlpreceiver] Incorrect JSON format description

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-collector#9207]
**Describe the bug**
Incorrect documentation

**Steps to reproduce**
https://github.com/open-telemetry/opentelemetry-collector/blob/bb76d9cf45839b2f34bc88e033e0533e2ff92b29/receiver/otlpreceiver/README.md?plain=1#L44-L48

**What did you expect to see?**
If I read the implementation correctly, the accepted JSON format is OTLP-JSON, not Protobuf-JSON (in particular, IDs are parsed as hex, and enums are parsed as numbers)

**What did you see instead?**
Readme says the format is Protobuf-JSON.

**Comment by rehanpfmr** [comment]
Let me update the document.

**Comment by AkhigbeEromo** [comment]
Hello, I would like to work on this issue, can it be assigned to me
@mx-psi @yurishkuro

**Comment by mx-psi** [comment]
@AkhigbeEromo all yours :)

**Comment by AkhigbeEromo** [comment]
Hello @mx-psi , i submitted a PR for this issue but it has not been approved

Wanted to ask if there is any correction that i need to make

**Comment by mx-psi** [comment]
Left a comment, sorry that it didn't get reviewed
