### ISSUE TITLE
Contrib tests are broken

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9237]
**Describe the bug**
https://github.com/open-telemetry/opentelemetry-collector/pull/9091 contrib tests should have caught the errors that happened in open-telemetry/opentelemetry-collector-contrib/pull/30167 but it did not. We need to investigate why, and check that contrib tests are actually testing.

This is important to avoid delays in the release like it is happening for v0.92.0

**Comment by atoulme** [comment]
looks like they run just the root module:
https://github.com/open-telemetry/opentelemetry-collector/actions/runs/7218308599/job/19667498944?pr=9091#step:4:12603
```
make[1]: Entering directory '/tmp/opentelemetry-collector-contrib'
go test -race -timeout 300s -parallel 4 --tags="" ./...
?   	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/checkapi	[no test files]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/internal/components	[no test files]
make[1]: Leaving directory '/tmp/opentelemetry-collector-contrib'
```
