### ISSUE TITLE
Should `configopaque.String` implement `encoding.BinaryMarshaler`?

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9272]
It would be easy to do (e.g. [here is the implementation for `net.URL`](https://github.com/golang/go/blob/b2dbfbfc2315557815e1d5de12f28ed57f60958a/src/net/url/url.go#L1184-L1186), ours would just be returning `[]bytes(maskedString), nil`). 

Any reason *not* to do it?

**Comment by bogdandrutu** [comment]
I don't have a reason to not to, but I do not have a reason on why to. So my rule of thumb when in doubt leave it out :)

**Comment by TylerHelmuth** [comment]
If [this statement](https://github.com/open-telemetry/opentelemetry-collector/issues/9274#issuecomment-1889781216) is true, then I do think we'd want to prevent this situation. If the goal of `configopaque.String` is to hide the value unless the user explicitly decides they want to see it, then I think the roundabout situation of `configopaque` -> `[]byte` -> `string` is a leak.

**Comment by mx-psi** [comment]
> I don't have a reason to not to, but I do not have a reason on why to. So my rule of thumb when in doubt leave it out :)

Two arguments in favor:

- Implementing this interface later may be breaking for users, so we may as well do it now
- What Tyler said on https://github.com/open-telemetry/opentelemetry-collector/issues/9272#issuecomment-1889786700: if the goal is to prevent leaking other than by casting to `string` then this would prevent leakage.
