### ISSUE TITLE
Document `configopaque` security expectations

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9274]
The aim of the `configopaque` package is to have opaque types to prevent leakage of secrets in configuration. We should document under what situations do we aim to redact output, since it's kind of fuzzy right now (it used to be just for marshaling, now we also redact logs). 

It may also be that we miss some cases, would we be justified in making breaking changes if something like this happens again?

**Comment by TylerHelmuth** [comment]
Would a over-arching statement like:

`The only way to view the value store in `configopaque.String` is to first convert it to a string.`

be enough?

**Comment by mx-psi** [comment]
@TylerHelmuth That makes sense to me. My main goal with this is that we have a guide if we have to make changes after 1.0 (e.g. what is bug, what should be kept as is)

**Comment by mx-psi** [comment]
Filed #9295 adding the statement by @TylerHelmuth as well as some more information
