### ISSUE TITLE
Triager role request for @TylerHelmuth

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9303]
Formal request to grant triager role to @TylerHelmuth so I can more effectively help move the Collector forwards.

**Comment by codeboten** [comment]
I approve, thanks @TylerHelmuth

**Comment by mx-psi** [comment]
I support! :tada: 

cc @open-telemetry/collector-approvers

**Comment by jpkrohling** [comment]
I support

**Comment by bogdandrutu** [comment]
+1
