### ISSUE TITLE
Consider to move the ticker logic to the main receiver

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#931]
Currently every scraper has it's own ticker logic which can be sub-optimal - will send one RPC call for every scraper tick, in general most of the users will report all these metrics with the same frequency, so we can scrape all of them and append to the same MetricsData which will result in only one RPC call to the next level if using OTLP or any protocol that supports multiple metrics/timeseries like Stackdriver.

The proposal is to change scraper interface to expose only one function `ScrapeAndAppend` and move the ticker logic to the main hostmetrics receiver, where we will have one ticker for the default interval (if any scraper uses the default interval) and one per scraper with a scrape interval different than default - we can optimize maybe and group scrapers with same interval in the same ticker (if it is not too complicated).

**Comment by jrcamp** [comment]
Worth keeping in mind for https://github.com/open-telemetry/opentelemetry-collector/issues/934

**Comment by bogdandrutu** [comment]
Even if a common pattern is proposed, still merging the result metrics is a benefit.

**Comment by james-bebbington** [comment]
Makes sense - I'd been thinking about doing this as an optimization at some point in the future, but I'll get onto it this week
