### ISSUE TITLE
Make memory_limiter and otlp_receiver return 503 status code instead of 500 on failure

### ISSUE THREAD

**Issue by climberfree** [open-telemetry/opentelemetry-collector#9337]
**The problem**
When the collector fails due to memory_limiter, the agent receives a **500 status code**. This status code i**s not retryable**, and the error sometimes resolves within minutes, especially after creating one more collector's instance through autoscaling.

**The solution**
We propose **making the `memory_limiter` and `otlp_receiver` return a 503 status** code instead of 500 in situations where the failure is temporary and expected to be resolved shortly.

**Benefits:**
- makes the situation retryable, allowing the agent to attempt a new connection after a brief delay.
- aligns with common HTTP status code semantics, indicating that the service is temporarily unavailable.

**Comment by dmitryax** [comment]
This should be already resolved and available in 0.93.0 with https://github.com/open-telemetry/opentelemetry-collector/pull/8080 merged

**Comment by TylerHelmuth** [comment]
@dmitryax I think #8080 actually only fixed the problem when using grpc.  If using http, we still have these line in our code:
 
 https://github.com/open-telemetry/opentelemetry-collector/blob/d78b748d7ae84c623c386876945d1efcb87f076c/receiver/otlpreceiver/otlphttp.go#L105-L109
 
 With #8080 the value in `err` is now properly a `Status` with code `Unavailable`, but our `http` logic is still returning `500`.
