### ISSUE TITLE
Create common scraping library

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#934]
Many of the new receivers being created (host metrics, redis, kubelet-stats, etc.) are all scrape based. They each collect metrics on a periodic interval and have other common needs like enabling/disabling individual metrics.

@james-bebbington @asuresh4 @pmcollins @bogdandrutu

**Comment by pmcollins** [comment]
@bogdandrutu 's suggestion in slack:

> we can start with something easy:
> I think we can have a "configmodels.MetricsScraper extends configmodels.Receiver" config that includes a "scrape_interval" and it comes with a reasonable default.
> Then we can make a change to allow flag or env variable to configure that default
