### ISSUE TITLE
[confignet] Should the two structs implement `ConfigValidator`?

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9364]
**Is your feature request related to a problem? Please describe.**

Since these structs could be used in configuration, should we add `Validate` functions to implement `ConfigValidator`? For `NetAddr`, for example, we could validate that `Transport` is one of `"tcp", "tcp4", "tcp6", "udp", "udp4", "udp6", "ip", "ip4", "ip6", "unix", "unixgram" and "unixpacket"`.

**Comment by mx-psi** [comment]
Should we make `Transport` into a type with `UnmarshalText`?
