### ISSUE TITLE
Release beta v0.93.0

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#9365]
**Performed by collector release manager**

- [x] Prepare beta core release v0.93.0
- [x] Tag and release beta core v0.93.0
- [x] Prepare contrib release v0.93.0
- [x] Tag and release contrib v0.93.0
- [x] Prepare otelcol-releases v0.93.0
- [x] Release binaries and container images v0.93.0

**Performed by operator maintainers**

- [x] open-telemetry/opentelemetry-operator#2567

**Performed by helm chart maintainers**

- [x] open-telemetry/opentelemetry-helm-charts#1016

**Comment by mx-psi** [comment]
Looks like the core release goreleaser job failed: #9370
