### ISSUE TITLE
[extension/zpages] zpages extension should use `confighttp.HTTPServerSettings`

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#9368]
**Is your feature request related to a problem? Please describe.**
The zpages extension declares a http.Server without much option besides setting its endpoint.

**Describe the solution you'd like**
It would be good to instead use `confighttp.HTTPServerSettings` to set up the extension server.

**Comment by Sanket-0510** [comment]
I would like to take on this issue, from my understanding of the issue, we need to use` httpSettingServer` from `confighttp` go module to setup the extension server.
1. Will need to import the required go packages from `go.opentelemetry.io/collector/config/confighttp`,
2. Implement extension server using confighttp instance
3. use `ToServer` method provided by confighttp to configure the server.

I think I can address this issue. I'll open PR for this and will try to fix this.

**Comment by atoulme** [comment]
I think that’s the right plan. Holler for help if needed!

**Comment by Sanket-0510** [comment]
@atoulme I have opened a draft pull request, I don't know why but was failing onto some checks, but the server implementation looks good to me but still facing some issues, better if you can provide some feedback.

regards,
Sanket
