### ISSUE TITLE
Stabilize module confmap

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#9379]
Before stabilizing a module, an approver or maintainer must make sure that the following criteria have been met for at least two successive minor version releases:

- [x] No open issues or PRs in the module that would require breaking changes
- [x] No TODOs in the module code that would require breaking changes
- [x] No deprecated symbols in the module
- [x] No symbols marked as experimental in the module
- [x] The module follows the [Coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)

Please also make sure to publicly announce our intent to stabilize the module on:

- [x] The #otel-collector CNCF Slack Channel
- [x] The #opentelemetry CNCF Slack channel
- [x] A Collector SIG meeting (if unable to attend, just add to the agenda)

To help other people verify the above criteria, please link to the announcement and other links used to complete the above in a comment on this issue.

Once all criteria are met, close this issue by moving this module to the `stable` module set.

**Comment by atoulme** [comment]
Posted https://cloud-native.slack.com/archives/CJFCJHG4Q/p1710912151670599 and https://cloud-native.slack.com/archives/C01N6P7KR6W/p1710912143827149 to announce the stabilization intent.
