### ISSUE TITLE
[config/configgrpc] Introduce new functions that use `context.Context`

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#9389]
Similar and building on https://github.com/open-telemetry/opentelemetry-collector/issues/9105, we now can expose context in configgrprc `ToListener`.

**Comment by TylerHelmuth** [comment]
We are instead deciding on removing `ToListener`: https://github.com/open-telemetry/opentelemetry-collector/issues/9481.  Closing for now.
