### ISSUE TITLE
export metrics from traces

### ISSUE THREAD

**Issue by Liorba** [open-telemetry/opentelemetry-collector#944]
Hello,
I'm trying to use the collector to receive metrics from jaeger and send metrics regarding those trances to Prometheus.
for example, suppose I have span for writing to a database, I really want to know what is the avg db query time on my app or maybe have an alert on long db db query time (i.e 95 percentile is larger the 200 millis).
today I need to create those separately.
it will be very conveniente to have those metrics auto generate inside a collector's pipeline.
currently I cannot mix tracing receivers with metrics exporters. 
I'm getting the following error:
```
Error: cannot setup pipelines: cannot build builtExporters: traces/1 is a traces pipeline but │
│  has a prometheus which does not support traces                                               │
│ 2020/05/10 13:38:05 Application run finished with error: cannot setup pipelines: cannot build │
│  builtExporters: traces/1 is a traces pipeline but has a prometheus which does not support tr │
│ aces
```
Does opentelemetry collector roadmap has something of that sort?

**Comment by bogdandrutu** [comment]
So just to clarify what you need is not `export` (because the Span does not have any metric) but `build` or `create` metrics from Spans.

I don't think is on our short term roadmap but happy to review a contribution for this. I would add it in the contrib repo.

**Comment by Liorba** [comment]
ok, Thank you!
