### ISSUE TITLE
Decide if `configopaque.String` should be a string or a type alias

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9441]
On #9427 @bogdandrutu brought up the possibility of turning `configopaque.String` into a struct instead of it being a type alias. This would require adding a method `Raw() string` to fetch the internal string.

|      | `configopaque.String` is a string alias                                                          | `configopaque.String` is a struct                                                                                       |
|------|--------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| Pros | - You can assign a string literal to `configopaque.String` fields <br><br> - No need for breaking changes | - More explicit way of getting the value of a `configopaque.String`                                                     |
| Cons | - Less explicit way of getting the value out of a `configopaque.String` (type cast)              | - You need to explicitly use the constructor to assign to a `configopaque.String` field <br><br> - We need to break everybody :( |

Notes: 
- The API would look like the following in each case: https://github.com/open-telemetry/opentelemetry-collector/pull/9427#issuecomment-1917640055
- The breaking change can be done in two steps as described on https://github.com/open-telemetry/opentelemetry-collector/pull/9427#issuecomment-1917845520

I want to poll what people think about this to decide on how to move forward. If you have further arguments in favor of one or the other, please comment below and I will update the table.

Voting options:
- :heart:: I prefer keeping as a string alias
- :tada:: I prefer turning `configopaque.String` into a struct

Please **vote for a single option**.

cc @open-telemetry/collector-approvers

**Comment by bogdandrutu** [comment]
The voting sounds to me that is biased because of "no changes", but I would like to understand if this was done from scratch how would we do it.

**Comment by mx-psi** [comment]
> for me is the security aspect (see why we added 10s of interface implementations to not leak the string and is still not clearly safe in my opinion).

Is there any way to make it more clearly safe? To be clear, the interfaces would also be needed if we had a struct ([the default string representation for structs also leaks private fields](https://go.dev/play/p/Z-0uIJQPtlQ)).

> the problem is that conversion to string may happen when you call a function that accepts string for example and is not clear that you pass the raw value actually

Could you provide a code example with the concrete situation you think it is confusing? I wrote a snippet of code with some examples on when implicit casting happens. The rule of thumb is that it will only implicitly cast string literals:

```go
package main

import (
	"fmt"

	"go.opentelemetry.io/collector/config/configopaque"
)

func takesOpaque(str configopaque.String) {
	fmt.Println("takesOpaque called with", str)
}

func takesString(str string) {
	fmt.Println("takesString called with", str)
}

type Config struct {
	Secret configopaque.String
}

func main() {
	takesOpaque("literal string") // ✓ <-- Implicit literal cast

	cfg := Config{Secret: "literal string"} // ✓ <-- Implicit literal cast
	fmt.Println("Config value", cfg)

	strInVar := "string in var"
	takesOpaque(strInVar)          // X <-- Compile-time error (line 28)
	cfg = Config{Secret: strInVar} // X <-- Compile-time error (line 29)

	var opaque configopaque.String = "opaque string" // ✓ <-- Implicit literal cast
	takesOpaque(opaque)                              // ✓ <-- Matching types
	takesString(opaque)                              // X <-- Compile-time error (line 33)
}
```

Output:
```
...
go: found go.opentelemetry.io/collector/config/configopaque in go.opentelemetry.io/collector/config/configopaque v0.93.0
# play
./prog.go:28:14: cannot use strInVar (variable of type string) as configopaque.String value in argument to takesOpaque
./prog.go:29:23: cannot use strInVar (variable of type string) as configopaque.String value in struct literal
./prog.go:33:14: cannot use opaque (variable of type configopaque.String) as string value in argument to takesString
```

Golang playground version: https://go.dev/play/p/CsW25hCvprj

I don't see a situation where an opaque string would be passed to a function that takes strings and be leaked (in particular line 33 is a compile-time error).

**Comment by bogdandrutu** [comment]
I think this example clarifies that this cannot be miss-use because of the compiler error in line 33. Thanks @mx-psi, my concerns are gone :)
