### ISSUE TITLE
`scraperhelper.NewScraper` is awkward to use

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9473]
While working on #9208 I realized that the current way `scraperhelper.NewScraper` works is a bit awkward. The function takes a `name string` and then builds an ID with it:

https://github.com/open-telemetry/opentelemetry-collector/blob/f5a7315cf88e10c0bce0166b35d9227727deaa61/receiver/scraperhelper/scraper.go#L64

It is very common among contrib scrapers to name the scraper with the same name as the component itself, and so we end up building a `component.Type`, converting it to string to pass to `NewScraper` and then building it again. I propose we change the first argument to take a `component.Type` instead.

**Comment by bogdandrutu** [comment]
I think Scraper interface needs a bit more "love" than that. Will give a try to send some PRs/ideas soon

**Comment by mx-psi** [comment]
>  the empty value is still in use

Where do we use the empty value?

**Comment by mrasu** [comment]
I'd like to try this at https://github.com/open-telemetry/opentelemetry-collector/pull/11082

**Comment by codeboten** [comment]
Thanks @mrasu, I'll assign it to you

**Comment by codeboten** [comment]
Re-opening as it wont be completed until the deprecated methods have been removed
