### ISSUE TITLE
[configtls] Validate `MinVersion` and `MaxVersion`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9475]
We effectively restrict the allowed versions to the set defined here:

https://github.com/open-telemetry/opentelemetry-collector/blob/f5a7315cf88e10c0bce0166b35d9227727deaa61/config/configtls/configtls.go#L382

We should validate for it! This can be done after 1.0 per the rules we have here https://github.com/open-telemetry/opentelemetry-collector/blob/f5a7315cf88e10c0bce0166b35d9227727deaa61/VERSIONING.md#L52-L54

Still, it would be nice to have before 1.0 IMO

**Comment by molejnik88** [comment]
Hi,
Isn't `MinVersion` validated here: [configtls.go#L176](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/configtls.go#L176) and `MaxVersion` validated here: [configtls.go#L180](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/configtls.go#L180)?

**Comment by molejnik88** [comment]
I'd like to work on this issue. Can you please assign it to me?

**Comment by atoulme** [comment]
Done, go for it
