### ISSUE TITLE
[configrpc] Consider adding option wrapper on `ToServer` and `ToClientConn`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9480]
Instead of passing `grpc.ServerOption`s to each, we could pass new `ToServerOption`s or `ToClientOption`s and require wrapping `grpc.ServerOption`s into these, to make the interface more flexible and allow for other kinds of options in the future.

**Comment by TylerHelmuth** [comment]
@mx-psi can you elaborate a little more on what you'd like to see?

For our `ServerConfig.ToServer` for example, we end up calling `grpc.NewServer` and passing it a `[]grpc.ServerOption`.  But `grpc.ServerOption` is an interface that we can't implement in `configgrpc`.  We need to end up with `grpc.ServerOption` to call `grpc.NewServer`, so would we be creating a wrapper of every `Option` function in `grpc`? Something like:

```go
type ToServerOption func() grpc.ServerOption

func MaxConcurrentStreams(n uint32) ToServerOption {
	return func() grpc.ServerOption {
		return grpc.MaxConcurrentStreams(n)
	}
}
```

Since `grpc.ServerOption` isn't extendable I don't see how we make our own package more extendable.

I believe `grpc.DialOption` has the same limitation.

**Comment by TylerHelmuth** [comment]
Are you thinking we add something like `confighttp` has and then add wrappers for each `grpc.ServerOption`?

**Comment by mx-psi** [comment]
> Are you thinking we add something like `confighttp` has and then add wrappers for each `grpc.ServerOption`?

Yes, that's what I was thinking:

```
type ToServerOption ... // opaque type here, likely a sealed interface

func WithgRPCServerOption(opt grpc.ServerOption) ToServerOption {
	return // wrap the option here into a `ToServerOption`
}

// Maybe add other options in the future that are not grpc.ServerOption
```

**Comment by TylerHelmuth** [comment]
@mx-psi i am worried that this solution will mean we have to remember to update our options whenever a new grpc option comes out. If we are ever behind it will mean a grpc option exists that isn't usable with configgrpc. Is that ok?

**Comment by mx-psi** [comment]
@TylerHelmuth We would just have just a single wrapper `WithGRPCServerOption(opt grpc.ServerOption) ToServerOption`, so there's no need to keep up to date, right?

**Comment by TylerHelmuth** [comment]
@mx-psi if we can get away with just the 1 generic wrapper that's great. Based on my brief experimentation the lack of exported fields in grpc and the need to end up with []grpc.ServerOption before calling grpc.NewServer will pose a challenge I think, but worth looking into more.

**Comment by TylerHelmuth** [comment]
@mx-psi we could do something like this:

```go
// toServerOptions has options that change the behavior of the gRPC server
// returned by ServerConfig.ToServer().
type toServerOptions struct {
	grpcServerOptions []grpc.ServerOption
}

// ToServerOption is an option to change the behavior of the gRPC server
// returned by ServerConfig.ToServer().
type ToServerOption func(opts *toServerOptions)

func WithgRPCServerOption(opt grpc.ServerOption) ToServerOption {
	return func(opts *toServerOptions) {
		opts.grpcServerOptions = append(opts.grpcServerOptions, opt)
	}
}

// ToServer returns a grpc.Server for the configuration
func (gss *ServerConfig) ToServer(_ context.Context, host component.Host, settings component.TelemetrySettings, extraOpts ...ToServerOption) (*grpc.Server, error) {
        // this is an existing function that makes a bunch of grpc.ServerOptions based on the host/settings.
	opts, err := gss.toServerOption(host, settings)
	if err != nil {
		return nil, err
	}
	tso := toServerOptions{}
	for _, otp := range extraOpts {
		otp(&tso)
	}
	opts = append(opts, tso.grpcServerOptions...)
	return grpc.NewServer(opts...), nil
}
```

Is this what you had in mind?

**Comment by TylerHelmuth** [comment]
This pattern conflicts with https://github.com/open-telemetry/opentelemetry-collector/issues/9479 tho, but it could be made to fit the interface pattern instead.

**Comment by mx-psi** [comment]
@TylerHelmuth Yeah, that's what I had in mind! Sorry that I wasn't very clear in the previous messages, my bad :sweat_smile:

**Comment by legendary-acp** [comment]
Hi @mx-psi, 
I was reviewing the code related to this issue and noticed that `toServerOption` is already implemented. Am I correct in assuming that only `toClientOption` is left to be completed? Please let me know if I'm mistaken.

I would love to contribute!

Thank you!

**Comment by atoulme** [comment]
@legendary-acp go for it

**Comment by jade-guiton-dd** [comment]
I'll take this one.

**Comment by mx-psi** [comment]
This still needs removing and renaming the deprecated APIs, reopening
