### ISSUE TITLE
[configgrpc] Remove `ServerConfig.ToListener` and `ToListenerContext`?

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9481]
This option is redundant since one can already call `ServerConfig.NetAddr.Listen` instead. Should we deprecate it?

**Comment by bogdandrutu** [comment]
+1, agree.

**Comment by bogdandrutu** [comment]
Also, as a general rule all these "ToFoo" should have options in the signature for future proof and very important `Context` as first argument.

**Comment by mx-psi** [comment]
> Also, as a general rule all these "ToFoo" should have options in the signature for future proof and very important `Context` as first argument.

Split off at #9490
