### ISSUE TITLE
[configrpc] Remove `SanitizedEndpoint`?

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9482]
As far as I can tell, this function is not used by any code, either in core or contrib. Should we remove it?

**Comment by TylerHelmuth** [comment]
I think we need to reconsider removing this feature.  The https://github.com/open-telemetry/opentelemetry-collector/pull/9616 showed the otlpexporter relies on it.

We could reproduce the functionality directly in the otlpexporter, but leaving it in configgrpc seems ok as well.

**Comment by mx-psi** [comment]
> I think we need to reconsider removing this feature. https://github.com/open-telemetry/opentelemetry-collector/pull/9616 showed the otlpexporter relies on it.
>
> We could reproduce the functionality directly in the otlpexporter, but leaving it in configgrpc seems ok as well.

@TylerHelmuth Do we have more than one usage of this function? If not, I would vote to move this to the OTLP exporter

**Comment by TylerHelmuth** [comment]
@mx-psi it has been used in [configgrpc's `ToClientConn` function](https://github.com/open-telemetry/opentelemetry-collector/blob/6affda628707970bfdb875036b72cbf3ff04e9cd/config/configgrpc/configgrpc.go#L183) for a long time.  Looking at usage of `ToClientConn`, it is used in the `otlpexporter`, `coralogixexporter`, `opencensusexporter`, `otelarrowexporter`, `skywalkingexporter`, `jaegerremotesamplingextension`, and `testbed`.

**Comment by atoulme** [comment]
The OTLP exporter has another way to deal with sanitized endpoint by stripping the scheme of the URL at unmarshaling time.

OK, so for this to happen:
1. We need embedded struct unmarshaling support https://github.com/open-telemetry/opentelemetry-collector/pull/9635
2. Then we can implement an unmarshaler for configgrpc. We need one anyway for https://github.com/open-telemetry/opentelemetry-collector/pull/9537

**Comment by mx-psi** [comment]
@TylerHelmuth As you said, I don't think uses on `configrpc` itself count; we can just unexport the function, my concern is about having it as part of the public API.
