### ISSUE TITLE
All public funcs in the config modules (e.g. `ToServer`) should accept Context.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#9490]
- [x] #9808
- [x] [configcompression] Update public methods to accept context.Context
- [x] #9807
- [x] #9812
- [x] #9105
- [x] [configopaque] Update public methods to accept context.Context
- [x] #9809
- [x] #9810
- [x] #9811

**Comment by atoulme** [comment]
Closing as complete.
