### ISSUE TITLE
[otlpexporter] Validate endpoint has port

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#9505]
```
2024-02-07T02:18:55.694Z	error	exporterhelper/queue_sender.go:123	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlp/XXX", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: address example.com: missing port in address\"", "dropped_items": 335}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/queue_sender.go:123
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/bounded_memory_queue.go:55
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/consumers.go:43
```

If you omit the port from the endpoint used by the otlp exporter, it starts ok but fails to run with an error. Instead, we should have a default port or validate the endpoint on start.

**Comment by atmask** [comment]
@atoulme I'm just getting familiar with the project and looking for an entry point to get started with. Could I take a look into this if there's not a time constraint (might have to do a bit of environment set up)? Is there a preference between setting the default port or doing the validation?

**Comment by atmask** [comment]
Okay I've found how the otlp exporter makes use of the `configgrpc.Config` in the exporter config. I think that the solution I will add is to also validate that a port is specified as part of the otlp exporter's config validation.

**Comment by Kimbohlovette** [comment]
Hello @Aneurysm9  can I take this issue
I would like to work on this issue

**Comment by atmask** [comment]
@Kimbohlovette There is already a PR to resolve this issue. Please see: https://github.com/open-telemetry/opentelemetry-collector/pull/9632.

**Comment by Kimbohlovette** [comment]
Alright @atmask thanks very much
I will look for another issue

**Comment by atmask** [comment]
@atoulme This has been stalled in PR review for a month. Can we please get a review from a code owner?

**Comment by atoulme** [comment]
Closing as complete.
