### ISSUE TITLE
Add `NewDefaultFoo` for configurations

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9508]
[...] We should add a `NewDefaultFoo` for all configs, so that we can easily add new fields and set the right default value. 

So we can say that in order to guarantee "backwards compatible behavior" user should always initialize the config with default and overwrite anything as needed instead of creating a struct with "initial value" and leave others unset.

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/issues/9478#issuecomment-1930475996_
            

We should add this to the contributing guidelines and, once approved, create subissues to address this on configtls, configgrpc and confighttp.

- [ ] #9654
- [ ] #9655
- [x] #9656
- [x] [configretry] Add `NewDefault*` functions for all config structs
- [x] #9657
- [ ] #9821

**Comment by codeboten** [comment]
The decision has been made and individual module PRs have been opened, closing.
