### ISSUE TITLE
[confignet] Should we change the name of `NetAddr` and `NetTCP` to end in `Config`?

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9509]
Few others:
* NetAddr -> AddrConfig?
* NetTCP -> TCPConfig?

_Originally posted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/issues/9474#issuecomment-1930426896_

**Comment by bogdandrutu** [comment]
Also we duplicate the "net" prefix in `config[net].[Net]Addr` for example

**Comment by arjunmahishi** [comment]
Taking this up.

---

> NetTCP -> TCPConfig?

I am assuming, by this you mean `TCPAddr` ?
https://github.com/open-telemetry/opentelemetry-collector/blob/de6287de839a7d2c0273dd1df3a064a08f733904/config/confignet/confignet.go#L48-L49

**Comment by TylerHelmuth** [comment]
Requires https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31354
