### ISSUE TITLE
[configtelemetry, exporter/debug, exporter/logging] Stop using `configtelemetry.Level` for `verbosity`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9528]
Per https://github.com/open-telemetry/opentelemetry-collector/issues/9510#issuecomment-1932569156, we want to remove `configtelemetry` in favor of views. We would still have to use a type in `debug` and `logging`, so we should make a copy of this type to use in these exporters instead of using the package that eventually will be deprecated.

**Comment by AkhigbeEromo** [comment]
Hello @mx-psi would like to work on this issue.
Just to clarify what i am to do.

Deprecate configtelemetry.Level.

If this is done what other function will replace it

**Comment by mx-psi** [comment]
Hey @AkhigbeEromo, the idea for this issue would be to create a new enum type with the same fields that gets used in the `debug` and `logging` exporter configuration. 

We don't want to deprecate `configtelemetry.Level` for this task (we need to do more work for that!), just stop using it on these exporters' configuration.

**Comment by AkhigbeEromo** [comment]
Been trying to work on this task😂, 
Getting stuck in some places
Let me ask
Can I use this approach to solve this problem:
`
type VerbosityLevel int32

const (
	VerbosityLevelNone VerbosityLevel = iota - 1
	VerbosityLevelBasic
	VerbosityLevelNormal
	VerbosityLevelDetailed

	verbosityLevelNoneStr     = "None"
	verbosityLevelBasicStr    = "Basic"
	verbosityLevelNormalStr   = "Normal"
	verbosityLevelDetailedStr = "Detailed"
)
`
Can I use this method to declare a new struct that will store the different verbosity levels

Or is there something better I can apply @mx-psi

**Comment by mx-psi** [comment]
@AkhigbeEromo Apologies for the delay. Based on https://github.com/open-telemetry/opentelemetry-collector/issues/9510#issuecomment-2037683776, I am going to put this issue on hold until #9510 is resolved, since we may end up not wanting to do this

**Comment by AkhigbeEromo** [comment]
Okay understood @mx-psi

**Comment by mx-psi** [comment]
I am going to close this as wontfix
