### ISSUE TITLE
Go semconv seems not be consistent with otel semconv spec

### ISSUE THREAD

**Issue by aygalinc** [open-telemetry/opentelemetry-collector#9592]
**Describe the bug**
Starting with the semconv 1.21.0, info in trace resource seems to not correspond to semantic convention. 
As example all info related to http is missing, is it intended ? 

I see that exporter-contrib are base on the generated semconv, so basically if trace that follow semantic convention in version > 1.20 is ingested some exporter failed to map field to trace store. We use the azuremonitor in our production system and it is not usable anymore.

**Comment by aygalinc** [comment]
Link to : https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31255

**Comment by codeboten** [comment]
thanks for reporting this @aygalinc, as of the [merge of v1.25.0](https://github.com/open-telemetry/opentelemetry-collector/pull/10075), the generated_attribute_group.go includes the http semconv. Please re-open if that doesn't solve the issue
