### ISSUE TITLE
[client] `Metadata` is not thread safe

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9594]
**Describe the bug**
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31289

I believe there is a bug in `Metadata.Get` when accessed by multiple threads.  

If the `Metadata` struct is added to a context that is then shared between multiple exporters and those exporters attempt a `Get` at the same time the collector will panic with `fatal error: concurrent map writes`.

We are seeing this happen right now with the headerssetterextension.  The extension is telling the exporters to grab details out of the context, but it is the same context used between all the exporters in the pipeline.

Code that I suspect is not thread safe: https://github.com/open-telemetry/opentelemetry-collector/blob/59b45a575d9094b977f3904e8d1408a47ef1d70f/client/client.go#L150-L171

**Steps to reproduce**

1. Setup a collector to receive OTLP metrics
2. Configure a headerssetter extension to extract a value from the context.
4. Use the headerssetter extension as auth to multiple exporters (the more exporters, the faster you get crashes)
5. Send data through the pipeline for several minutes. 
6. Watch for the collector to crash 

**What did you expect to see?**
No crashes, multiple exporters could extract from the same context

**What did you see instead?**
Panic with `fatal error: concurrent map writes`

**What version did you use?**
Latest

**Comment by TylerHelmuth** [comment]
Is it expected that this feature NOT be thread-safe and that users (like the extension) should implement protection around `Metadata.Get` to make it thread safe?

**Comment by jpkrohling** [comment]
I believe it should be made thread safe. The initial assumption I had back then was that receivers would write and other components would read, meaning that only one part would write at any given time. I think the optimization that causes the write was added later and a lock should have been added there, given the initial assumption changed.

**Comment by TylerHelmuth** [comment]
As @bogdandrutu pointed out, the issue is happening specifically because of `m.data[key] = v`.  If the request headers match the configured value exactly then this issue does not happen.
