### ISSUE TITLE
[bug] release notes: images and binaries link = 404

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-collector#9617]
**Describe the bug**

The link in the release notes leads to a 404.

<img width="936" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector/assets/26523841/23e948af-6a81-43ba-b0bf-1c694a960bad">

 >>>

<img width="1203" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector/assets/26523841/4f4b99b7-48a6-4c9c-b684-aa1a46e912e9">

https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.95.0

**Comment by TylerHelmuth** [comment]
The release is not complete yet: https://github.com/open-telemetry/opentelemetry-collector/issues/9601.  When it is, the links will work.
