### ISSUE TITLE
[configgrpc] Add `NewDefault*` functions for all config structs

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9654]

**Comment by Sanket-0510** [comment]
I am working on this!

**Comment by AkhigbeEromo** [comment]
Hey @Sanket-0510 are you still working over this ?

**Comment by Sanket-0510** [comment]
> Hey @Sanket-0510 are you still working over this ?

Actually I am having exams currently so I may not be able to work on this 😅 feel free to take this also you can refer my Other PR for refference #9671

**Comment by AkhigbeEromo** [comment]
Can this be assigned to me? @TylerHelmuth

**Comment by AkhigbeEromo** [comment]
Just created a pull request concerning this issue : https://github.com/open-telemetry/opentelemetry-collector/pull/9819
