### ISSUE TITLE
Prometheus receiver: log error message when `process_start_time_seconds` gauge is missing

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#969]
Prometheus receiver supports the flag `use_start_time_metric: true`.
When this flag is enabled, every Prometheus endpoint must have the `process_start_time_seconds` gauge, e.g.
```
# TYPE process_start_time_seconds gauge
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
process_start_time_seconds 1508230997
```

When this metric is present, it will set the `startTime` in 
https://github.com/open-telemetry/opentelemetry-collector/blob/66d7acdc5a697c7be777cff9f83302fd066c7c7e/receiver/prometheusreceiver/internal/metricsbuilder.go#L106-L108

and will be used for adjusting time in metrics - this is expected behavior.

But if the `process_start_time_seconds` gauge is missing, `startTime` will have the default zero value.

The problem is that during transaction commit phase, we perform the check https://github.com/open-telemetry/opentelemetry-collector/blob/66d7acdc5a697c7be777cff9f83302fd066c7c7e/receiver/prometheusreceiver/internal/transaction.go#L168-L171

which **silently drops all metrics** and updates the local variable `droppedTimeseries` that is never used.

As a result, debugging this corner case is a nightmare, and the only way to discover all of this is to use Go debugger (that's how I found this issue).

At the very least, we should log a message when metrics get dropped.
I would suggest using `WARN` level for this specific issue, but if it's considered normal for some situations, we should print `INFO` or `DEBUG` message.

---

Is there also some other existing way of reporting counters like `droppedTimeseries`?

**Comment by nilebox** [comment]
@dinooliva as the author of PR #394 which introduced this flag, you may have more context on this, and share your opinion?

**Comment by nilebox** [comment]
The http://localhost:55679/debug/tracez endpoint simply always returns zeros, e.g.
```
Attributes:{accepted_metric_points=0, format="prometheus", refused_metric_points=0, transport="http"}
```
regardless of how the Prometheus receiver is doing (before and after the fix), so I suppose this is also a bug?

**Comment by nilebox** [comment]
FYI the issue is easy to reproduce with JMX to Prometheus exporter, https://github.com/prometheus/jmx_exporter/blob/master/run_sample_httpserver.sh

**Comment by rf232** [comment]
I also got hit by this and second @nilebox' desire for at least some kind of logging in this situation and maybe adding this to some exposed metric
