### ISSUE TITLE
Deprecate third party code from host metrics receiver

### ISSUE THREAD

**Issue by james-bebbington** [open-telemetry/opentelemetry-collector#973]
The Host Metrics receiver currently includes [third party code](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/hostmetricsreceiver/internal/third_party) for retrieving windows performance counter info, which is used to calculate load and paging metrics. We also calculate page file usage from a direct syscall into `psapi.dll`.

Ideally, we would like to upstream code to [gopsutil](https://github.com/shirou/gopsutil) to calculate these values directly so we can remove this code from the Collector repo.

**Comment by james-bebbington** [comment]
Updated plans for this:

1. The Host Metrics receiver currently uses third party code that accesses `pdh.dll` to extract perf counter data. This is useful for getting generic performance counter data, so will move this code to Contrib and create a perf counter receiver that targets Windows only. That receiver will be useful for generating stats on IIS, SQL Server, etc. Tracked in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1088.
2. Update core to use https://github.com/leoluk/perflib_exporter (note this is also used by https://github.com/prometheus-community/windows_exporter). This package reads from the Windows registry directly so 
3. Upstream page file usage calls to gopsutil (this is still the long term plan)

Benefits of (2):

- Slightly faster since reading from the registry directly
- Can remove `third_party` code from Core 🎉 
- Don't need to refactor the current `third_party` code to be accessible from Contrib. Just move it to Contrib instead as part of (1).
- Don't need to reverse engineer Sums from rates, and can report the Sums since boot time instead of since process start.

**Comment by tigrannajaryan** [comment]
@james-bebbington are we done with this issue?

**Comment by james-bebbington** [comment]
The part about moving the pagefile syscalls to gopsutil is not done but that is not third party code and not very high priority so yes I think it makes sense to close this issue.
