### ISSUE TITLE
Move linux/arm64 to secondary support

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#9731]
linux/arm64 is currently considered tier 3 "community support" per https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md.

The intent of this issue is to track moving linux/arm64 to tier 2 support "Secondary support".

**Comment by atoulme** [comment]
CI issues tracking support:

* [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12920
* [ ] https://github.com/open-telemetry/opentelemetry-collector/pull/9584

**Comment by dneary** [comment]
What would be required to get OTel to Tier 1 support?

**Comment by atoulme** [comment]
@dneary see https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/platform-support.md for the detail.

**Comment by atoulme** [comment]
I have opened https://github.com/open-telemetry/opentelemetry-collector/issues/9731 to move linux/arm64 to tier 2: https://github.com/open-telemetry/opentelemetry-collector/issues/9731 which will fix this issue. We can open a follow up issue for tier 1 right after.

The difference is fairly minimal: we just need to run performance tests and end to end tests with arm64 machines to declare tier 1 support, everything else is already on parity.
