### ISSUE TITLE
Fix Prepare release workflow

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#9748]
To avoid regex replacements like https://github.com/open-telemetry/opentelemetry-collector/commit/998f64d7771a660d3ce030ba0f2b6684b887b460#diff-c7c8156618a7f8126b25ca1bdfde3e172a0d2cb75c533d63a71617ae2a5c54aeR198

**Comment by mowies** [comment]
@dmitryax I submitted a fix for this issue. Will also apply the fix to the collector-contrib repo, which seems to have the same issue.
