### ISSUE TITLE
Zipkin V2 Trace Receiver doesn't parse tags like http.status_code

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-collector#975]
Zipkin tags/annotations is always a string and they must be parsed to successfully convert to the open census format.

Current the v1 and v2 zipkin tag/binary annotation parsers are separate code paths

V1 supports
- integers
- booleans
- span status from common tags

https://github.com/open-telemetry/opentelemetry-collector/blob/86e5805aaed83a7e9642a5b09eac2889f2fef3fa/translator/trace/zipkin/zipkinv1_to_protospan.go#L216-L219

https://github.com/open-telemetry/opentelemetry-collector/blob/86e5805aaed83a7e9642a5b09eac2889f2fef3fa/translator/trace/zipkin/status_code.go#L69-L98

V2 only supports
- booleans (restricted formats)
- span status (only open census canonical code)

https://github.com/open-telemetry/opentelemetry-collector/blob/86e5805aaed83a7e9642a5b09eac2889f2fef3fa/receiver/zipkinreceiver/trace_receiver.go#L594-L611

https://github.com/open-telemetry/opentelemetry-collector/blob/d86bcd06e7ac113a8d33e112141d2fb5776364ad/receiver/zipkinreceiver/trace_receiver.go#L488-L529

I think these code paths should be unified so they have the same behavior.

**Comment by Verlet64** [comment]
I'd be happy to pick this up, if that's okay?

**Comment by chris-smith-zocdoc** [comment]
I'm actually planning on working on this today @Verlet64 as its a requirement for my work

**Comment by kbrockhoff** [comment]
This fix needs to be coordinated with any fixes for #1138
