### ISSUE TITLE
configtls does not actually honor field `include_system_ca_certs_pool` (`IncludeSystemCACertsPool`)

### ISSUE THREAD

**Issue by SeanPMiller** [open-telemetry/opentelemetry-collector#9789]
**Describe the bug**
The [docs for configtls](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md) say that `include_system_ca_certs_pool=true` causes the component in which it is embedded to load the system CA-cert pool before loading any other certificate configured in the object. The associated fields include `ca_file`, `ca_pem`, and `client_ca_file`.

For clients, this does not happen.

**Steps to reproduce**
Set both `include_system_ca_certs_pool=true` and also `ca_file=<path to some non-system CA-cert pool>`.

**What did you expect to see?**
System CA-cert pool loaded in addition to the file at the `ca_file` path.

**What did you see instead?**
System CA-cert pool is not, in fact, loaded.

According to my reading of the code, it would be correctly loaded before loading the file at the `client_ca_file` path, but that is set for servers, not clients.

**What version did you use?**
v0.96.0

**What config did you use?**
Irrelevant. See above to reproduce.

**Environment**
Irrelevant. All environments.

**Additional context**
None should be needed.

**Comment by TylerHelmuth** [comment]
@SeanPMiller would you like to submit a PR for this issue?
