### ISSUE TITLE
[confighttp] Update public methods to accept context.Context

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9807]

**Comment by AkhigbeEromo** [comment]
Hello @TylerHelmuth can this issue be assigned to me?

And also just to confirm what I am working on, the public functions in this package are:

- ToClient
- ToListener
- ToServer

**Comment by TylerHelmuth** [comment]
@AkhigbeEromo I agree that those are 3 three functions to add context to.

**Comment by AkhigbeEromo** [comment]
Okay @TylerHelmuth , i will start working on this issue.

Can it be assigned to me?

**Comment by codeboten** [comment]
Closed by #9895

**Comment by TylerHelmuth** [comment]
This isn't complete until we go through the deprecation cycle. We need to:

- [ ] Release v0.98.0
- [ ] Rename the `To*Context` functions to `To*` by deprecating the `To*Context` versions and adding `context.Context` to the `To*` versions.
- [ ] Wait for the v0.99.0 release
- [ ] Remove the deprecated `To*Context` functions.

**Comment by AkhigbeEromo** [comment]
Is there anything i will need to do? @TylerHelmuth

**Comment by codeboten** [comment]
@TylerHelmuth fair enough, apologies for closing too eagerly

**Comment by TylerHelmuth** [comment]
@AkhigbeEromo yup, over the next 2 release cycles you can work on those tasks I listed out.  For now we wait for the next release.

**Comment by AkhigbeEromo** [comment]
Understood, Thank you @TylerHelmuth
