### ISSUE TITLE
[configretry] Update public methods to accept context.Context

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9809]

**Comment by AkhigbeEromo** [comment]
Hello @TylerHelmuth, Just submitted a PR concerning this issue

**Comment by TylerHelmuth** [comment]
Reviewing the module there are only 2 public functions, `Validate` and `NewDefaultBackOffConfig`. Neither of these functions qualify for adding context, so this module is covered.

**Comment by AkhigbeEromo** [comment]
Okay, understood. Will close the PR now
