### ISSUE TITLE
[configtelemetry] Update public methods to accept context.Context

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9810]

**Comment by AkhigbeEromo** [comment]
Hello @TylerHelmuth can this issue be assigned to me?

And also just to confirm what I am working on, the public functions in this package are:
- MarshalText
- UnmarshalText

**Comment by TylerHelmuth** [comment]
`configtelemetry` currently has 3 public functions:
- `UnmarshalText`
- `MarshalText`
- `String`

None of these quality for adding `context.Context` since they are implementations of interfaces.
