### ISSUE TITLE
[configtls] Update public methods to accept context.Context

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9811]

**Comment by TylerHelmuth** [comment]
There are currently 3 public functions in `configtls`:
- `ServerConfig.LoadTLSConfig`
- `ClientConfig.LoadTLSConfig`
- `Config.Validate`

`Validate` doesn't qualify for the issue since it needs to conform to the `ConfigValidator` interface.

**Comment by atoulme** [comment]
It looks like this is completed. OK to close as done?
