### ISSUE TITLE
[configgrpc] Update public methods to accept context.Context

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#9812]

**Comment by AkhigbeEromo** [comment]
hello @TylerHelmuth, while working on this issue I realized that all the public functions in `configgrpc.go` already accept context. The only public function that does not accept context is a deprecated function called `SanitizedEndpoint()`

**Comment by TylerHelmuth** [comment]
@AkhigbeEromo correct.  There is 1 more round of deprecation and then we'll be able to call this closed.
