### ISSUE TITLE
Recently stabilized module breaks tooling

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#9827]
In this case, `configcompression` was recently marked stable. This causes failures when running `make update-otel` on contrib (step 1 of the release process).

@TylerHelmuth explained the situation well: `configcompression` has been moved from beta to stable but not had a release yet. The multimod tool sees it in the stable set, knows there was a 1.3.0 release, and tries to make the tag 1.3.1 for everything, but configcompression never had a 1.3.0. I was able to proceed my moving `configcompression` back to beta locally and then running `make update-otel`. It will generate a 0.96.1 tag for `configcompression`.

Also see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31778

**Comment by mx-psi** [comment]
Another thing to fix: we have not documented that we need to update this when stabilizing a module: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9adb91e165fb90c22c0dab0e658bf04414bfcb7c/internal/buildscripts/modules#L36 We should add this to the release steps

**Comment by TylerHelmuth** [comment]
Commenting that this came up again for release 0.104.0 when configretry was stabilized.

**Comment by mx-psi** [comment]
This will come up again in v0.105.0 because of `configtls`. I am looking into it, but it feels like we will need to fix this in multimod itself

**Comment by mx-psi** [comment]
I filed open-telemetry/opentelemetry-go-build-tools/pull/582 that I think should fix this, PTAL
