### ISSUE TITLE
Generated code is clunky and not idiomatic of Go

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-collector#986]
I'm working through trying to build an exporter that supports the "new" data model currently and started building a `traceDataPusher`. In the process I've found the generated code to be intrusive, poorly structured, wrappers around Go instead of actual Go, and ultimately going to cause more developer frustration than adoption.

For instance, take the [`pdata.Traces`](https://github.com/open-telemetry/opentelemetry-collector/blob/master/consumer/pdata/trace.go#L26-L31). It is a `struct` wrapping an unexported `ResourceSpans`. It might seem like it provides added functionality with the added `SpanCount` function, but all that does is descend into the unexported field and pull `len` from that struct. Why not just a slice of a usefully defined `Trace` type? This is needlessly complex for no reason.

At the end of the day, whatever, I can live with a wrapper around another struct. That's clunky and annoying, yes, but more of a bad smell than a show stopper. However, that is not the case when you ask for the underlying data structure. The [`ResourceSpansSlice`](https://github.com/open-telemetry/opentelemetry-collector/blob/master/consumer/pdata/generated_trace.go#L24-L35) returned from `ResourceSpans` is bad. First off, it is not a slice, it is a struct. Instead of it being a slice and using the Go language to interact with the data directly, helper methods (`Len`, `At`, `MoveAndAppendTo`, `CopyTo`, `Resize`, ...) are added to this struct to try and recreate (with a different design) the already existing functionality the Go syntax implements on a slice or is natively handled by the compiler.

I haven't worked with all the generated code, but a quick look through the rest of the generated code shows these poor design choices to be systematic. This is extremely frustrating to a Go programmer. It imposes arbitrary ideas of how this data should be interacted with. Interactions that are not only foreign to a Go programmer, but highly unoptimized in the Go language.

I am not familiar with the generation tool used to generate this code, but I earnestly think its use should be questioned if it cannot be used to generate more native Go code. I think the poor developer experience caused by this codebase is likely to drive potential developers away and overall hurt the adoption of this project.

**Comment by MrAlias** [comment]
I just got off a call with @bogdandrutu where he was able to provide context around the design choices made here, including sharing a document that went in depth on the subject. To summarize, the goal is to avoid any deserialization of the underlying bytes. This will ensure the optimized transport of telemetry data through any tiered collection system and optimized processors within those systems. It makes a lot of sense to preserve the data in this fashion for these constraints and the overall design has more context because of this.

In talking through the history that culminated in this design, it sounds like there has been a lot of work exploring alternative implementations. Ultimately, using the performance metric as a forcing function, the current design was arrived at.

A thing I failed to do in opening this issue, in addition to missing this context, was include any suggestions to move forward. After talking with @bogdandrutu it sounds as though the previous work already done by this group includes things we can add back in to provide an alternate path in working with this data.

Using a callback model to operate on all the `ResourceSpans` was explored previously (i.e. adding a `func (r *ResourceSpansSlice) ForEach(callback func(...))` method to iterate through all the spans), and it sounded liked it might be possible to add this functionality back. Adding this back in would be in addition to the highly optimized methods currently in place that do not transform the bytes into any Go structures instead of a replacement. With this added functionality it would be up to the developer to choose what interaction (and consequent resource usage) they would like to have.

Additionally, we talked about adding a `ToSlice` method that would just return a Go slice for these types. I would greatly appreciate this addition. It would allow things that sit at the end of the collection chain and are doing a singular translations (i.e. don't have severe performance requirements) to use Go types and the full syntax.

**Comment by tigrannajaryan** [comment]
@MrAlias there is already a `ForEach` for `AttributesMap` and adding `ForEach` to all slice types is trivial. I believe we did try that and it was somewhat slower than `Let`/`At` combo used with `for` and performance is always a concern for us. (@bogdandrutu please correct me if I am not remember this correctly).

Just to make it clear. Today we have to do this:
```go
for i := 0; i < someslice.Len(); i++ {
  item := someslice.At(i)
  // do something with item.  
}
```

With `ForEach` you would be able to do this:
```go
someslice.ForEach(func (item ItemType) {
  // do something with item.  
})
```
Do you think it is worth it and it is more idiomatic? The functional programming style that ForEach uses does not seem to be very widespread in Go community.

As for `ToSlice`. What would this return? Would it return a slice of wrappers of elements? If the answer is yes then `ToSlice` will have to make an allocation and populate the wrappers with pointers to underlying OTLP data, which can be quite costly.

BTW, any improvement suggestions are welcome. I agree that the API that we expose currently is not very idiomatic and I would be very happy if we could improve it without hurting the performance.

P.S. I am also adding a link to the doc that captured our initial experimentation for anyone interested to have a look: https://docs.google.com/document/d/1MSKjMVXQsP51lA6OwpfyLfZhWK-MkGo5vff43LhrqZU/edit#

**Comment by MrAlias** [comment]
> @MrAlias there is already a `ForEach` for `AttributesMap` and adding `ForEach` to all slice types is trivial. I believe we did try that and it was somewhat slower than `Let`/`At` combo used with `for` and performance is always a concern for us. (@bogdandrutu please correct me if I am not remember this correctly).
> 
> Just to make it clear. Today we have to do this:
> 
> ```go
> for i := 0; i < someslice.Len(); i++ {
>   item := someslice.At(i)
>   // do something with item.  
> }
> ```
> 
> With `ForEach` you would be able to do this:
> 
> ```go
> someslice.ForEach(func (item ItemType) {
>   // do something with item.  
> })
> ```
> 
> Do you think it is worth it and it is more idiomatic? The functional programming style that ForEach uses does not seem to be very widespread in Go community.

I don't care too much about including a `ForEach` method. It was something @bogdandrutu and I had discussed as it had already existed. I'm more interested in having a slice to work with so I can `range` over the slice and use Go indexing syntax.

> As for `ToSlice`. What would this return? Would it return a slice of wrappers of elements? If the answer is yes then `ToSlice` will have to make an allocation and populate the wrappers with pointers to underlying OTLP data, which can be quite costly.

The idea behind adding the `ToSlice` method was to have it return a valid slice and indeed allocated data. It was going to be understood, and commented as such, that it was less performant that other methods, but provide a viable alternative to the developer who wants it. Like a developer writing an exporter at the end of a collection chain that needs to transform data (i.e. make allocation regardless) into some other form.

That all said, I'm realizing I don't have the bandwidth to drive this uphill initiative. Going to close and just move on.
