### ISSUE TITLE
[component] Reject `component.ID`s that are too long

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9872]
Follow up to #9208, proposed by @hughesjj at https://github.com/open-telemetry/opentelemetry-collector/pull/9670#discussion_r1514964449.

While this is a breaking change I think we can make it in one go since it's likely to affect nobody.

**Comment by atoulme** [comment]
@hughesjj what would be the max length allowed?

**Comment by TylerHelmuth** [comment]
k8s uses 63, thats good enough for me

**Comment by ankitpatel96** [comment]
I can work on this!
