### ISSUE TITLE
make `collector/internal/testdata` available as a public utility package

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#9886]
Right now this package being included in `go.opentelemetry.io/collector` means that anyone using the package for its tests depends on all the packages the `collector` package depends on.

Making the package a public package with no intention of stabilizing it means that we can at least untangle those dependencies.

**Comment by codeboten** [comment]
Alternatively, i could just copy the test files in the places where i dont want to incur dependencies :) but it would be convenient not to

**Comment by codeboten** [comment]
Another alternative is to make this a package under `pdata/testdata`

**Comment by atoulme** [comment]
I vote to make it available under `testdata` and create enough documentation that implementers downstream can leverage this package.

**Comment by dmitryax** [comment]
I don't like moving it to `pdata/testdata` as it is given that it's 1.x. I think we should better assess the interface to make it cleaner and extensible in the future. For example, each `Generate...` function probably needs to accept some settings struct instead of just one number

**Comment by dmitryax** [comment]
UPD: Oh, I see you moved it as another 0.x module on top of pdata. I think that should be ok
