### ISSUE TITLE
Allow partial retries of trace data in queued retry processor

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#990]
The [queued retry processor](https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#queued-retry-processor) retries the whole batch, however some exporters (e.g. Elasticsearch bulk API) can fail only part of the request (e.g. only specific spans).

A possible non-intrusive solution could be that the returned (exporter) error would carry properties that would identify objects that should be retried.

**Comment by pavolloffay** [comment]
cc) @flands @tigrannajaryan any thoughts?

**Comment by flands** [comment]
This was discussed during the last community meeting -- it is possible but is a significant change from today. A design would be needed for this.
