### ISSUE TITLE
Track @songy23 interest and contributions for approver

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#9953]
Hi @songy23,

This is a tracking issue to know if you are interested and have time to become (again) an approver for the core collector repository. If yes please confirm here. This issue should track contributions to ensure when requirements are met we add you to the approver list.

For previous work see #7271 and #8742

**Comment by songy23** [comment]
Thank you @mx-psi I confirm my interest in becoming core collector approver, looking forward to contributing in core!
